yarn.lock

Ran `npx update-browserslist-db@latest`. Should silence the annoying warnings until whenever it gets updated again.

Update Browserslist DB

---

src/Navigation.tsx
src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx

- Add typed event names/metadata for Statsig calls. Similar to how our Segment setup works. I'm starting from scratch so we can vet them again. For now I'm adding just typing `init`.
- Automatically include the current route name with every event. This is distinct from page URL — it's our router's "route name" concept. Might help track which features are used from which screens.
Checked on web and iOS.

Send route name with Statsig events

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx
src/state/queries/post.ts
src/state/queries/profile.ts
src/view/com/auth/onboarding/RecommendedFollowsItem.tsx
src/view/com/post-thread/PostThreadFollowBtn.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/FollowButton.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

Adds `post:like` and `post:unlike` events, similar to our Segment setup. Using lowercase for the new ones to distinguish from existing Segment events, as I don't aim to port them 1:1.
I'm introducing the notion of "log context", in the sense of which-part-of-the-UI-the-action-originated-from. It will be a required parameter for most mutations. Open to other names but I want to keep it relatively short, have "log" in the name to discourage any other attempts to use this information, and something to imply it's contextual to the UI.
I'm using component names here. I didn't reify this in an explicit type which is maybe a bad idea but I want to see how far we can take it with just copy paste / find-and-replace. We don't change the fundamental product UI structure that much.
I decided against …

[Statsig] Track likes, reposts, follows

---

src/components/forms/DateField/index.android.tsx
src/components/forms/DateField/index.shared.tsx
src/components/forms/DateField/index.tsx
src/components/forms/DateField/index.web.tsx
src/components/forms/DateField/types.ts
src/screens/Signup/StepInfo.tsx

Date input implementation is currently a bit of a mess. It's a huge inline picker on iOS, and the android implementation was super broken looking.
This PR fixes android styles, shares the textfield-like button implementation with iOS, and moves the iOS picker to a dialog so that in its closed state it matches other platforms
Demo in Hailey's ALF'd Signup PR
https://github.com/bluesky-social/social-app/assets/10959775/81f9ce8c-498b-4204-b6b6-da73b2fe2d62

Standardise date input across platforms

---

src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/lightbox/ImageViewing/components/ImageDefaultHeader.tsx
src/view/com/util/BottomSheetCustomBackdrop.tsx
src/view/com/util/ErrorBoundary.tsx
src/view/shell/index.web.tsx

Changed all the places I could find where the `t` macro is used, since this doesn't change when changing the app language, and replaced it with `msg`

Fix instances of static translations (`t` macro)

---

src/state/queries/labeler.ts

Now that entryway handles `labeler.getServices` we should use the agent again

Use entryway for labeler getServices

---

src/components/ReportDialog/SelectLabelerView.tsx
src/components/ReportDialog/SelectReportOptionView.tsx
src/components/ReportDialog/SubmitView.tsx
src/components/ReportDialog/index.tsx

- If the user has >1 labeler subscribed, adds an initial screen where you choose the moderation service
- Doesn't change any other logic, including the ability to check multiple recipients in the final step
- If the user has only 1 labeler, doesnt do that initial step

Update the reporting flow to first select a recipient if the user has multiple labelers

---

src/screens/Profile/Sections/Labels.tsx

No changes on web by adding `sideBorders` to `CenteredView`

fix borders for labels tab

---

src/components/Dialog/types.ts

In order to facilitate easy passing of `.open` to a `Pressable` or `TouchableX` `onPress` prop, adding the `GestureResponderEvent` type to the `options` parameter is necessary.
For example right now we have to do one of the following.
```tsx
const control = useDialogControl()
const onPressTwo = React.useMemo(() => {
control.open()
}, [])
<Pressable onPress={() => control.open()}>
<Text>Hello</Text>
</Pressable>
<Pressable onPress={onPressTwo}>
<Text>Hello Again</Text>
</Pressable>
```
If we add `Partial<GestureResponderEvent>` to the `options` type, we can simply use a pressable like so
```tsx
const control = useDialogControl()
<Pressable onPress={control.open}>
<Text>Yay</Text>
</Pressable>
```
Making this `Partial` allows us to still use `.open({index: 10})` for example if we wanted to …

add `Partial<GestureResponderEvent>` to `.open()` on dialog control

---

src/screens/Moderation/index.tsx

Also, fixed the loading spinner not being centred.
Before:
After:

Fix overflow of PWI opt out label

---

src/screens/Moderation/index.tsx

Just removes the wrapping `View`, idk why that was there.
Before
After

Fix space on bottom of mod screen

---

__tests__/lib/strings/url-helpers.test.ts
src/lib/strings/url-helpers.ts

Fixes https://github.com/bluesky-social/social-app/issues/3229
- We were not ignoring the `#` case for a URL, and it would display a link warning
- Create stronger cases for trusted URLs. Any `bsky.social`, `bsky.app`, `blueskyweb.xyz`, or help desk URL is now trusted.
- Excessively long posts no longer show a warning when pressing "Show More"
- Test cases in `url-helpers.test.ts` have been updated for various internal domains that should be trusted.

Update trusted hosts, allow `#`, and add more tests

---

patches/react-native+0.73.2.patch
patches/react-native+0.73.2.patch.md

Since iOS 17.4, there appears to have been a regression where `RCTRefreshControl` does not play a haptic on refresh if the `tintColor` prop is set. This patch produces a haptic on refresh.
There are no haptics played by the `RCTRefreshControl` or `RCTScrollView`, so my thought is that there is something going on with the passing of props from JS to native, causing some issue here, although I do not know for sure. I don't want to spend an overwhelming amount of time looking into a fix here though, so this is just a temporary fix until it gets resolved upstream.
I might give it a closer poke later maybe on a weekend or something to find a better fix.
I also RM'd the old `TextInput` patch because it is not necessary - we removed the `lineHeight` completely from that component, so the patch …

patch-fix `RCTRefreshControl` to play an impact on refresh

---

bskyweb/templates/base.html
src/lib/hooks/useWebBodyScrollLock.ts
src/view/com/lightbox/ImageViewing/components/ImageDefaultHeader.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/util/forms/NativeDropdown.web.tsx
src/view/com/util/text/Text.tsx
web/index.html

As seen on Firefox v123.0, Linux Mint
1. Consistent button styles in lightbox
|--------|--------|
| ![image](https://github.com/bluesky-social/social-app/assets/790659/7a5110f0-eca1-4228-b1a2-3f9f24ea0e8c) | ![image](https://github.com/bluesky-social/social-app/assets/790659/894fedf7-148e-45e2-a58d-e28ad68eb182) |
| ![image](https://github.com/bluesky-social/social-app/assets/790659/fcc03f51-9593-4427-a35b-f3f2e77a6d5e) | ![image](https://github.com/bluesky-social/social-app/assets/790659/04ac5d0d-f41b-4b7b-ba04-27acda877e94) | 
2. Add `Liberation Sans` to prevent broken `Helvetica` replacement in Firefox on Linux (**TBD**: check other platforms/browsers)
|--------|--------|
| ![image](https://github.com/bluesky-social/social-app/assets/790659/739858ed …

Add 'Liberation Sans' font for FireFox; lightbox buttons adjustments

---

src/components/moderation/ScreenHider.tsx
src/view/com/post-thread/PostThread.tsx

Was causing us to show a content warning screen rather than this:

Fix detection of !no-unauthenticated

---

src/lib/moderation/useModerationCauseDescription.ts
src/view/com/posts/FeedErrorMessage.tsx

Also fixes a generic error message `FeedNSFPublic` on profiles.

use different labels for `porn` and `sexual`

---

src/components/Dialog/index.tsx
src/components/Dialog/types.ts
src/components/ReportDialog/index.tsx

Because the default behavior is to dismiss on-drag, we run into this:
https://github.com/bluesky-social/social-app/assets/153161762/a3e215d7-162d-49cc-b6e8-adb8165ebd18
This adds a param to control the behavior and switches it to interactive on the report dialog.

Set keyboardDismisMode to interactive on the report dialog

---

src/Navigation.tsx
src/lib/hooks/useAccountSwitcher.ts
src/lib/statsig/events.ts
src/screens/Deactivated.tsx
src/state/session/index.tsx
src/view/com/auth/login/ChooseAccountForm.tsx
src/view/com/auth/login/LoginForm.tsx
src/view/com/modals/SwitchAccount.tsx
src/view/com/testing/TestCtrls.e2e.tsx
src/view/screens/Settings/index.tsx

Adds tracking for login/logout operations.
This only tracks operations *initiated by the user*. We don't count automatic logins here. (The way those work is pretty convoluted so I think for now I'd just like to keep track of explicit actions to err on the side of understanding the events.)
I'm also only counting success for now. If we see significant gaps compared to `init` events we can dive deeper.
I've placed the events themselves closer to the API calls (so we don't miss adding new calls to them) but I require passing in `logContext` from outside which forces us to add attribution for which part of the UI triggered the event.
It's a bit ugly not not too bad to thread it through.
- Login form
- Sign out button in Settings
- Switch between accounts in Settings
- Switch between accounts …

[Statsig] Track login/logout

---

src/view/com/auth/SplashScreen.tsx
src/view/com/auth/SplashScreen.web.tsx

Splashscreen refresh using ALF. Minor change to web - added the "What's up?" subtitle that's missing on web. Was this difference intentional? I can remove it again if so.
iOS:
Web (desktop):
Web (mobile):

Use ALF for Splashscreen

---

src/lib/statsig/statsig.tsx

[Review without whitespace](https://github.com/bluesky-social/social-app/pull/3315/files?w=1)
Apparently `logEvent` can throw otherwise. (To repro, remove the provider.) This adds a safeguard.
In practice the only way this can happen right now is via the `AppState` listener that is setup early.
I've also added a try-catch with a rethrow inside `setTimeout` so that this can never happen again.
Fixes this:

[Statsig] Protect against early logEvent call crashing

---

package.json

I'm not sure if it's yarn or node, but something keep trying to add this field automatically. I think its probably good to have anyway, so why not.

Specify package manager in package.json

---

src/lib/statsig/statsig.tsx

Rethrowing on a clean stack works in dev in RN but hard-crashes the app in prod. I didn't know that.
Use the logger instead.

Use logger.error instead of rethrow

---

src/view/com/auth/HomeLoggedOutCTA.tsx
src/view/com/auth/SplashScreen.tsx
src/view/com/auth/SplashScreen.web.tsx

Current:
I think the "In" should be lower case, to match the other button

Change Sign In -> Sign in on Splashscreen

---

src/screens/Login/FormContainer.tsx
src/screens/Login/index.tsx
src/screens/Signup/StepCaptcha/index.tsx
src/screens/Signup/index.tsx
src/view/com/util/layouts/LoggedOutLayout.tsx

Currently, the signup/login scrollviews for the desktop layout don't work. This normally doesn't show up, but on a smaller screen you can see it on the captcha step (see below). I'm not 100% sure what the exact cause is (something to do with height: 100% vs height: 100vh I think?) but even if it did work, it would be broken anyway because `LoggedOutView` adds horizontal padding to the content area, leaving the scrollbars inset which looks terrible. This PR adds an optional scrollview to `LoggedOutView`, and removes the two different scrollviews from both the sign up and log in flows. Also, the way that it was centred using flexbox didn't work with the scrollview, so I changed it to use vertical auto margins so that once the scrolling kicks in, it stops being centred.

Move scrollview to `LoggedOutLayout` to fix scrolling on web

---

src/screens/Signup/StepInfo/Policies.tsx
src/screens/Signup/index.tsx

This PR marks the `under13` string and the `Next` and `Back` buttons (and their labels) in the signup flow for translation.

Mark `under13` and `Next` and `Back` buttons in signup for localisation

---

src/view/com/composer/Composer.tsx

This is a temporary fix for closing the composer on web. We should not rely on this and should re-evaluate a few things about the dialogs and the callbacks here.
The `PromptControl` allows for passing a callback that runs after closing the dialog. This works fine on native but does not work on mobile. If we do the opposite and just use `onClose` as the callback to `onConfirm`, it breaks the Android back button. We should do a deeper investigation on this @estrattonbailey

revert change for closing composer on web only

---

src/components/Error.tsx

This PR marks the `Retry` and `Go Back` buttons in Error.tsx for localisation and updates their labels.
edit: I hope I got the imports (and the `useLingui()` export) right 🤞  The linter stopped giving me errors, at least.

Mark `Retry` and `Go Back` buttons in Error.tsx for localisation

---

package.json
patches/@mattermost+react-native-paste-input+0.6.4.patch

Inline predictions are causing some pretty bad jank with the post composer. This patch disables those suggestions. This is fairly common on other apps, so disabling it should not cause any issues for users.

disable inline predictions to prevent ios composer jank

---

src/components/Button.tsx

We've added an error boundary _inside_ each button in https://github.com/bluesky-social/social-app/pull/3340 in case there are some existing places in the app where we accidentally render raw text inside (not wrapped in `<ButtonText>`) which would lead to a crash. In that case, the error boundary would display "ERROR" inside the button instead. 
Let's remove this.
The release including this fix has largely propagated:
We are not observing any related logs in Sentry:
It's confusing if a button just says `ERROR`. You might even do a destructive action (e.g. deletion) because you're not aware what the button actually does. We shouldn't be showing buttons without real labels:
In general, defensive coding can be helpful for working around issues in short term, but it makes it harder to …

Remove Button error boundary

---

src/App.native.tsx
src/App.web.tsx
src/lib/react-query.tsx

This removes the `queryClient` export and instead adds a `<QueryProvider>` export used from both web and native, similar to how we do with other providers. This will let us make `queryClient` replaceable in a follow-up PR. 
The actual commit to review is https://github.com/bluesky-social/social-app/commit/57a72a110834d7dd27480e04cfe74809c98d3193.
Straightforward refactor.

Factor QueryProvider out

---

.github/workflows/bundle-deploy-eas-update.yml

We don't need to fetch from origin/main if we are already on the main branch. This results in an error if we try to.
Eventually we can actually just remove this step completely, but I want to leave it here as we continue testing since we might have separate branches that we want the action to run on.

don't fetch from origin if unnecessary when performing OTA deploy

---

src/platform/polyfills.web.ts

Suppose we add a string somewhere like this:
```js
<View>stuff</View>
```
On RN, this would be a crash, but it works on the web. So if you mostly develop on web, it's easy to miss.
RNW includes some basic protection against this with [this DEV-only `console.error` call](
https://github.com/necolas/react-native-web/blob/a0cd8ffba4ade1b5860164cb4ef89a652a68580f/packages/react-native-web/src/exports/View/index.js#L71-L79). Note it isn't as exhaustive as the real check RN needs because it will only catch direct `<View>` children. It's still better than nothing though.
The problem is, it's very easy to miss because we have a bunch of `console.error` console logspam on web. We should fix that logspam, but still, for this particular error we should just show the redbox in DEV on web. So we can't …

Show redbox in DEV on string <View> child for web

---

src/components/moderation/ScreenHider.tsx

Supersedes https://github.com/bluesky-social/social-app/pull/2880, which fell out of date
Small thing -- just adds a cursor to the "Learn More" link on the screen hider. Tested by forcing a blur on the screenhider and then running on web.

Add cursor to 'learn more' on screenhider (close #2871)

---

.github/workflows/build-submit-android.yml
.github/workflows/bundle-deploy-eas-update.yml

Infuriatingly, GitHub thinks that the string `[]` _or_ any string containing any sort of hash contains a secret. Therefore, we can't just simply pass `[]` to the outputs of the first job in the workflow.
This is a little hack to output either the string "true" or the string "false" instead.
Also, just updating the base android build script to support manual deployment of a testflight client for Android.

Work around GitHub false-positive for passing secret to another action

---

src/lib/icons.tsx

Fixes the icons `MagnifyingGlassIcon2` and `MagnifyingGlassIcon2Solid`. Closes #2893.
|--------|-------|
| <img width="155" alt="스크린샷 2024-03-20 22 17 38" src="https://github.com/bluesky-social/social-app/assets/11014257/94b9b833-9334-4895-9546-417655f78c2f"> | <img width="155" alt="스크린샷 2024-03-20 22 24 55" src="https://github.com/bluesky-social/social-app/assets/11014257/f6205003-960a-457a-9877-67f93ce879f9"> |
| <img width="247" alt="스크린샷 2024-03-20 22 29 08" src="https://github.com/bluesky-social/social-app/assets/11014257/df60056e-7540-44f5-92f8-2ed7de97c506"> | <img width="247" alt="스크린샷 2024-03-20 22 26 43" src="https://github.com/bluesky-social/social-app/assets/11014257/f01dbe40-bdd5-4943-b434-40bdb00f5a64"> |

Fix magnify icon

---

src/App.native.tsx
src/App.web.tsx
src/lib/react-query.tsx
src/state/session/index.tsx

Inspired by #3321, this is an attempt to have a guarantee that we never ever reuse the same cache instance (and the associated tree) between different DIDs. If we have that guarantee then we also should not have a need to `clear` the cache or `resetQueries` or any of the related things since we should be able to expect a cache instance to eventually get GC'd.
So I removed those `clear` calls.
Switched between users. I think it works (not seeing cached feed etc). We should check if it fixes the issue https://github.com/bluesky-social/social-app/pull/3254 was set out to solve. I haven't done extensive testing here.

Scope query client per DID

---

src/state/queries/post-liked-by.ts

Pretty bad that this broke. I'll do a pass over these files so we always use constants, but this is a quick fix.
https://github.com/bluesky-social/social-app/assets/810438/a2f2eb57-1029-4afe-b6f9-cb9a80003fa9
https://github.com/bluesky-social/social-app/assets/810438/76a29a73-4a7e-4e79-912e-932193854da9

Fix profile follow from Likes

---

src/state/queries/labeler.ts

Drive-by fix. Code isn't being used but still.

Don't mutate array

---

src/lib/moderation/useGlobalLabelStrings.ts
src/lib/moderation/useReportOptions.ts

This is a follow up to https://github.com/bluesky-social/social-app/pull/3282 where we reverted the change to the "Adult Content". The appeals screen still shows "Pornography", so this PR replaces that with "Adult Content" again.

rm 'pornography' label wording

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx

Supersedes https://github.com/bluesky-social/social-app/pull/3093
Closes #3081 
Enables tags in profile descriptions. Tested on iOS and Android simulator and on Web.

Enable tags on profile descriptions (close #3081)

---

src/state/queries/actor-autocomplete.ts
src/state/queries/actor-search.ts

Removes deprecated query param, see https://github.com/bluesky-social/atproto/pull/2376/files#diff-94910126c7c4193579395efd9490525ceeef6a8ce01ab7a9d7687e099af9ac62L13

replace deprecated `term` with `q` in search actor

---

src/platform/polyfills.web.ts

Follow-up to https://github.com/bluesky-social/social-app/pull/3394.
React can already handle stray _empty_ strings just fine, so the `console.error` from RNW is overzelaous.
Let's silence it to match the actual behavior.
Moderation -> Muted words and tags
No longer crashes in DEV on web.

Fix false positive DEV check

---

bskyweb/templates/base.html
src/components/Loader.tsx
src/components/Loader.web.tsx
web/index.html

We're using reanimated to make something spin in a circle. This is fine on native due to the UI thread, but on web it's prone to stuttering, especially on lower end devices.
End result is exactly the same:
https://github.com/bluesky-social/social-app/assets/10959775/41c0be98-bde2-48a2-b33a-b19ac56fdde5

Use CSS keyframe animation for spinner on web

---

src/components/Button.tsx
src/components/GradientFill.tsx
src/screens/Onboarding/StepAlgoFeeds/FeedCard.tsx
src/view/com/composer/Composer.tsx
src/view/com/modals/AltImage.tsx
src/view/com/modals/CreateOrEditList.tsx
src/view/com/modals/DeleteAccount.tsx
src/view/com/modals/EditImage.tsx
src/view/com/modals/EditProfile.tsx
src/view/com/modals/EmbedConsent.tsx
src/view/com/modals/Repost.tsx
src/view/com/modals/crop-image/CropImage.web.tsx
src/view/com/modals/lang-settings/ConfirmLanguagesButton.tsx
src/view/com/util/fab/FABInner.tsx
yarn.lock

Not sure why this build went through, but it did. Imports for `LinearGradient` should be `{LinearGradient}`.

Properly import LinearGradient

---

.github/workflows/bundle-deploy-eas-update.yml

In order to prevent bad builds from getting deployed, we should check types and lint before building.

Lint and check types before building

---

.eslintrc.js
src/components/Prompt.tsx
src/components/forms/ToggleButton.tsx
src/components/moderation/LabelPreference.tsx
src/screens/Onboarding/StepModeration/ModerationOption.tsx
src/view/com/auth/server-input/index.tsx
src/view/screens/DebugMod.tsx
src/view/screens/Storybook/Dialogs.tsx
src/view/screens/Storybook/Forms.tsx

Follow-up to https://github.com/bluesky-social/social-app/pull/3407.
I'm continuing removing special cases so that we can confidently render stuff and know whether it supports text or not.
- `Prompt.Cancel` and `Prompt.Action`: Those are barely used, and all usages are text-only. I'm just enforcing that they _don't_ take `children`. The `cta` prop is then sufficient. (Side note: We should really stop using `PropsWithChildren`.)
- `Toggle.Button` -> `Toggle.ButtonWithText`: This case is more interesting. I settled on a convention:
- `Button` is a raw vanilla button with no opinion on children. Can't nest strings there (lint rule would flag it).
- `ButtonText` is a button-specific text component. Similar to `ButtonText` in normal buttons.
- <s>`ButtonWithText` **(new!)** combines them as a …

Remove special cases for some buttons with text

---

.github/workflows/bundle-deploy-eas-update.yml
package.json

Because merges can happen quickly, we need to make sure that the previous commit hash we use belongs to the ***last successfully deployed update*** for internal builds, not just the previous commit.
This PR simply adds a GitHub action cache that contains the commit of the last successfully deployed update. It is restored from the cache on build for comparison and is updated at the end of the run.
Also properly handles JSON in the diff variable. Because JSON uses `"` and we surrounded the variable name with `"`, bash was unhappy. Instead, we surround the JSON with `'` since it will not include single quotes.

prevent deployment race conditions

---

.github/workflows/pull-request-commit.yml

In the neverending battle against GitHub actions, I stumbled across this issue https://github.com/marocchino/sticky-pull-request-comment/issues/930
It looks like the proper `on` event to use is `pull_request_target` rather than `pull_request` 🤯

only run labelers for core team

---

src/components/Dialog/index.web.tsx
src/components/Prompt.tsx
src/view/com/composer/Composer.tsx

This is a follow-up to https://github.com/bluesky-social/social-app/pull/3330 and https://github.com/bluesky-social/social-app/pull/3343
I am implementing the change in #3330 here for _all_ dialogs now. I am also adding a callback to `close()` on web, so that the functionality remains the same across all platforms. This prevents issues where the dialog gets unmounted before the removal of the dialog from the dialog state is finished.
- Hide post through the post menu
- Open another post
- Try to use the back button
- Open the post composer on web
- Insert some text
- Press cancel, dismiss the composer

fix dialog back button for android

---

app.config.js

We don't want to enable code signing in development, so we can set `codeSigningCertificate` and `codeSigningMetadata` to `undefined`.
Once we actually start using this in prod, we can probably simplify this down to just only adding the `updates` block when `EXPO_PUBLIC_ENV` is not `development`. However, because we will be incrementally testing changes in production, we want to leave the updates block here regardless of whether they are enabled or not.

adjust `app.config.js` to prevent development manifest error

---

package.json
yarn.lock

Apple recently added some requires for accessing some native API categories. One of those API categories is `NSPrivacyAccessedAPICategoryFileTimestamp`, which is used by the `async-storage` package. This was added here.
https://github.com/react-native-async-storage/async-storage/pull/1075
There are still some APIs that we will need to either manually add declarations for or upgrade packages for when possible. Will keep an eye on those.
The only changes between `1.21` and `1.23.1` are some bug fixes and some changes for the new architecture. We shouldn't run into any issues with this change. I have built the app for iOS without issue.

Bump `async-storage` to comply with App Store guidelines

---

.github/workflows/bundle-deploy-eas-update.yml

One more small change to the bundle/deploy action. Because building of a new IPA/APK can be slow, we don't want to cancel this whole workflow if another change gets merged into main. Instead, we only want to cancel the deploy script. Any new builds that have been started should be kept running.

Keep each deployment job in a separate concurrency group

---

src/components/Dialog/context.ts

This follows up https://github.com/bluesky-social/social-app/pull/3428
We fixed the Android back button in the previous PR, but it breaks the way we were using the callback in the post composer. This fixes the issue so that our prompts close properly _everywhere_ and the back button works _everywhere_.
I don't totally understand what is going on here though. I think maybe there's a wrong type here, or the `control` ref is getting updated somewhere. Supposedly `control.close()` accepts a callback, however I don't see anywhere that is used. I want to take a better pass at that, or at least figure out why this was so borked in the first place.
- Attempt to discard a post
- Hide a post
- Attempt to discard a post
- Hide a post
- Visit another post
- Use the back button to verify it still …

Implement back button fix for all places in the app

---

src/lib/statsig/statsig.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx

If you're in the `autoexpand_suggestions_on_profile_follow` gate, you'll get this behavior:
https://github.com/bluesky-social/social-app/assets/810438/08656e5c-ea18-4e5a-8745-a6ed24ea2903
It's web-only because of scrolling issues on iOS/Android.
I've gated it as web-only in the code but I also had to add web-only condition to the gate setup itself. This is because we don't want to count exposures to the flag being on unless we're actually providing the changed behavior.

[Experiment] Auto-expand follow suggestions on web

---

src/lib/statsig/events.ts
src/view/com/feeds/FeedPage.tsx
src/view/com/posts/Feed.tsx

The first commit adds the feed URL to the metadata so we can check metrics against individual feeds.
In the second commit, I add a feature gate that disables polling for Discover. The hypothesis is that the blue dot is getting people to refresh it more often instead of scrolling to the end, but the blue dot doesn't quite make sense for algo feeds where the content is _always_ different. This removes the polling-based blue dot for Discover so we can check if this changes the user behavior. The blue dot will still appear when foregrounding the app.
We can run more variations on this experiment so this is just something to play with while learning how to do it.
Decreased polling interval to 5 seconds. Verified blue dot stopped getting blue on timer for the Discover feed. Still gets blue on …

[Experiment] Turn off interval polling for Discover

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx
src/state/queries/post.ts
src/state/queries/profile.ts

For follows:
- Track whether you became mutual
- Track the "clout" level of the person you're following
- Track the "clout" level of the person who's doing the following (you)
For likes:
- Track the "clout" level of the post you're liking
- Track the "clout" level of the person who's doing the liking (you)
- Whether you follow the poster
- Whether the poster follows you
The "clout level" of `something` is defined as `Math.max(0, Math.round(Math.log(something)))`. I'm using this as a universal measure for easier grouping in stats.
When we can't grab something out of the objects we have, I send `undefined`.

[Statsig] Track like/follow metadata

---

src/view/com/post-thread/PostThreadFollowBtn.tsx

An experiment that shows "Follow Back" rather than just "Follow" if the person is following you.
Pass myself in the gate. Observe the new button label:
I see the old button label if the person is not following me:
I also see the old button label if I fail myself in this gate:

[Experiment] Show "Follow Back" label in Post Thread

---

src/state/shell/selected-feed.tsx

We currently always persist the last selected tab between reloads. I think this more obviously makes sense when you only have two such tabs (like For You vs Following), but it might be easy to miss where you landed when you open the app.
We previously used to persist on mobile but reset to Following on web.
I want to run an experiment where we always put you into Following when reloading the app. On the web, this would be if you open a new browser tab (or a window). Reloads within the current tab would still preserve the selected tab until it's closed. This might be a little bit annoying, or a little bit helpful, or some unfortunate mix of those.
Let's give it a try under a gate?
Flipped the gate. New window started from Following.
Same on mobile after quitting the app — getting …

[Experiment] Ignore the persisted tab

---

src/components/Dialog/index.tsx
src/components/Dialog/index.web.tsx
src/view/screens/Storybook/Dialogs.tsx

- Test edge cases inside of the Storybook. Press `Open Tester` to see the various edge cases and watch the console logs.
- Composer
- Type some junk
- Attempt to close
- On Android, attempt to use the back button now
- Hide Post
- On Android, attempt to use the back button now
- Report Post
- Again, try to use the back button on Android (I usually just do a trash report to Beans Labeler for testing, lol)
- Just swipe to close a dialog. Everything should still work.
- Use the mute words dialog
- Delete a mute word, and make sure the back button is working

Small logic cleanups

---

src/lib/statsig/events.ts
src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/screens/Home.tsx

Adds an event that fires when a feed is displayed, along with the index and the reason. It was a bit tricky to figure out the right place to thread these through. This is the minimally invasive way I've found.
Add `console.log` to `logEvent` in `statsig.tsx`.
- Reload
- Use tabbar
- Use swipe
- On desktop, use right nav
- Switch between tabs
You should see events firing according to the schema.

[Statsig] Instrument feed display

---

src/Navigation.tsx

Sending previous only for navigation events. (We're already sending the current one with each event.)

[Statsig] Send prev route name

---

src/locale/locales/it/messages.po

New strings translated for v.1.75

Italian Localization

---

src/Navigation.tsx
src/components/Prompt.tsx
src/lib/hooks/useNavigationTabState.ts
src/lib/routes/types.ts
src/view/com/composer/Composer.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/SimpleViewHeader.tsx
src/view/com/util/fab/FAB.web.tsx
src/view/com/util/fab/FABInner.tsx
src/view/com/util/layouts/TitleColumnLayout.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx
src/view/screens/Search/Search.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/desktop/LeftNav.tsx
src/view/shell/desktop/RightNav.tsx
src/view/shell/index.tsx

Stacked on:
#1569 
#3369 
Goal: get the web tablet layout working on native tablet.
This PR:
- Renames `DesktopSideNav` to `SideNav`
- Branches `TabNavigator` into `TabNavigatorMobile` or `TabNavigatorTablet`, depending on platform
- Turns the list, moderation, and settings screens into their own tab stacks on native tablet
- Created `TabNavigatorTablet` which adds the extra tab stacks and uses `SideNav` rather than `TabBar`
Not a huge fan of some of the ways it splits the navigator logic depending on platform. Suggestions on how to branch this better are welcome.

[iPad support] Custom tab navigator for native tablet, with side nav

---

.eslintrc.js
eslint/index.js
eslint/use-typed-gates.js
src/lib/statsig/gates.ts
src/lib/statsig/statsig.tsx
src/view/screens/Search/Search.tsx

@mozzius added `gates.ts` in #3408 to statically check the gate name. I'd prefer we do this using types so that we don't have to keep adding methods. This still gives us autocomplete etc.
I also added a lint rule that enforces we use the local (typed) version of `useGate`. This is important because ours also has a different signature — it returns the `value` directly rather than `{isLoading, value}` as the upstream one does.
Gates are typechecked.
Importing the wrong `useGate` errros.

[Statsig] Typecheck gates

---

src/state/queries/actor-search.ts
src/state/queries/search-posts.ts
src/view/screens/Search/Search.tsx

Keeps track of the active tab, and only enables the queries once the tab is active
Look at the network tab - tabs should only load once you click on them

Search - only enable queries once tab is active

---

patches/expo-haptics+12.8.1.md
patches/expo-haptics+12.8.1.patch
src/lib/haptics.ts
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/state/persisted/legacy.ts
src/state/persisted/schema.ts
src/state/preferences/disable-haptics.tsx
src/state/preferences/index.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx
src/view/screens/SavedFeeds.tsx
src/view/screens/Settings/index.tsx
src/view/shell/bottom-bar/BottomBar.tsx

Fixes https://github.com/bluesky-social/social-app/issues/3484
We recently migrated to `expo-haptics`, mostly in preparation for using Fabric. There's a difference however in how the two libraries run an iOS "light" haptic config on Android.
The previous library used the `Vibration` API solely, which does not
have any configuration for intensity of vibration. The `Vibration` API has also been deprecated since SDK 26. See:
https://github.com/mkuczera/react-native-haptic-feedback/blob/master/android/src/main/java/com/mkuczera/vibrateFactory/VibrateWithDuration.java
Expo Haptics is using `VibrationManager` API on SDK >= 31. See: https://github.com/expo/expo/blob/main/packages/expo-haptics/android/src/main/java/expo/modules/haptics/HapticsModule.kt#L44
The timing and intensity of their haptic …

Improve Android haptic, offer toggle for haptics in the app

---

eslint/use-typed-gates.js

Fixes false positive firing on main because https://github.com/bluesky-social/social-app/pull/2931 imports it from `lib/...`.
Let's just explicitly disallow imports starting with `statsig` or `@statsig` that refer to npm packages.

Fix useGate lint rule

---

src/lib/statsig/gates.ts

New `Gate` type that was not present in https://github.com/bluesky-social/social-app/pull/2931. This fixes one lint issue, the other lint issue will be fixed in https://github.com/bluesky-social/social-app/pull/3486

Added `new_profile_scroll_component` to `Gate` type

---

src/lib/statsig/gates.ts
src/lib/statsig/statsig.tsx
src/view/screens/Search/Search.tsx

When `use_new_suggestions_endpoint` is `true`, the Search tab uses the `getSuggestions` endpoint instead of what we're doing now (which hits `getSuggestedFollowsByActor` and then does the same for a few of them). The old behavior is preserved when the flag is off (which it currently is for everyone).
Go to search tab. Observe roughly the same set (or at least after a few refreshes) as in prod.
Then pass yourself in overrides for the `use_new_suggestions_endpoint` gate.
Observe a difference set of results. (They're not currently very relevant but we'll be improving that on the backend.)

Use getSuggestions endpoint behind the gate

---

src/state/cache/post-shadow.ts

Fixes a bug where disliking an already liked post would optimistically decrease its repost count.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/3503/files?w=1)
https://github.com/bluesky-social/social-app/assets/810438/0db57eea-3ee9-4d17-a944-528f7b9a4eec
https://github.com/bluesky-social/social-app/assets/810438/9de3c419-ab3f-4b5d-8f99-309034545b74
The logic assumed `!!shadow.likeUri` is a good way to test if something is optimistically liked, and `!!shadow.repostUri` is a good way to test if something is optimistically reposted. But this doesn't take into account that the shadow object may be partial — and indeed it usually is — so it might not have those fields in the first place. In that case, they should be ignored rather than assumed to be an "unlike" …

Fix optimistic like/repost

---

src/state/queries/post-thread.ts
src/view/com/post-thread/PostThreadItem.tsx

https://github.com/bluesky-social/social-app/pull/3500 should have removed the need for the shimmer/placeholder portion of a post's metrics. However, in some cases - specifically when opening a QT from inside of another `PostThread` - there was still missing metrics.
We had duplicated the logic for creating a `PostView` from an embed record, which made it rather unobvious that we needed to update two places for converting an embed record.
With this, the expected result of no longer needing the shimmer is correct, so we can rm. The big spinner will be fixed in a separate PR, where we need to address caching the QP author's DID (right now we have to wait to resolve the handle to a DID which is causing the spinner).
You can use the same post as before, but test in two different ways:
- From …

QT Jump Pt. 2 - Remove code duplication

---

src/view/shell/bottom-bar/BottomBar.tsx

Without this change, it's possible for the count to go behind the icon on android. That's right yall: z-index can sometimes be overridden by component tree order in RN.

Fix: dont let notifications count go behind the icon

---

src/lib/notifications/notifications.ts
src/state/queries/notifications/unread.tsx

Should fix notifications being stale after foregrounding the app.
The issue was that the Notifications query checks the unread count cache first, but that cache gets out of date.
Added a fake handler to `notifications.ts` to simulate a push notif 20 seconds after app startup.
```js
setTimeout(() => {
invalidateCachedUnreadPage()
truncateAndInvalidate(queryClient, RQKEY_NOTIFS())
resetToTab('NotificationsTab') // open notifications tab
}, 20000)
```
Open the app, open Notifs, switch to Home, background the app.
Like your own post from another acc.
Wait so 20 seconds pass and foreground the app.
Before the fix, you wouldn't see the new notif. Now you do.
The new notification doesn't show until PTR:
https://github.com/bluesky-social/social-app/assets/810438/fe8ac40a-ddf3-401b-9568-c2d9b4d8924 …

Fix stale Notifications after push

---

src/state/queries/resolve-uri.ts
src/view/com/util/post-embeds/QuoteEmbed.tsx

This is another follow up to https://github.com/bluesky-social/social-app/pull/3500. We uncovered that quote post authors are not having their DIDs cached, which results in a full spinner when we navigate to the quoted post.
An existing solution to this would be to use `useResolveDid()`, however this results in an extra request for information that we already have. Instead, it makes more sense to update the cache with the author's handle and DID without performing a resolution, since we already have that information in the embed record.
Using this post: http://localhost:19006/profile/kevinmkruse.bsky.social/post/3kpxbhmzcym2p
[screen-capture (2).webm](https://github.com/bluesky-social/social-app/assets/153161762/c186c063-0e58-439e-81bc-338f1415f7c2)

Store QP authors in the DID cache

---

src/locale/locales/pt-BR/messages.po

I've removed all unused translations and added the few that were new from 1.76. I also fixed a translation that was being used in a button and I didn't check it after it was merged, so it wasn't making much sense.
I changed this translation a bit, removing the "as" in "Silenciar apenas as tags" to see if it properly works in the layout here:

Update pt-BR localization to latest version

---

src/locale/locales/de/messages.po

There was some discussion in my circles on Bluesky, that the recently-added translation of "liked" → "likt" (and its variations) looked weird and uncommon. 
As far as I can tell, this originated from the last update by @surfdude29 using DeepL, although it is not *wrong*, but there's also no 100% fixed consensus about it in German grammar literature. I personally think "liked" works better than "likt" in German. 
While I was at it, I modified and added a bunch more translations, although I don't have time to complete any more currently.

Update German translations 

---

src/locale/locales/en/messages.po

Supersedes #3280.
Similar to #2706, this is a cleanup PR that removes strings from the `en` message catalog that are obsolete and no longer used.

Remove obsolete strings from `en` message catalog

---

app.config.js
src/App.native.tsx
src/lib/hooks/useOTAUpdates.ts
src/lib/hooks/useOTAUpdates.web.ts
src/lib/statsig/gates.ts
src/view/screens/Home.tsx

We have been testing updates internally for a few weeks ago. So far we have not seen any issues with this on either platform amongst any of our team.
This PR will enable updates in production behind a Statsig feature gate. The update flow will be the same as it currently is in testflight, with two differences:
- Users will not receive an "Update Available" alert
- The update will be downloaded in the background upon app launch and will be installed automatically either:
- After an app force quite and re-open
- After fifteen minutes of inactivity in the background
The app will also check for updates every fifteen minutes while in the foreground. If an update becomes available, it will be downloaded in the background, and will be installed as described above.
However, as long as the …

Enable updates for `production` behind `receive_updates` gate

---

src/components/ProfileHoverCard/index.web.tsx

Small timeout before showing card so it doesn't show up immediately while moving cursor around.

wait a sec before showing card

---

src/state/queries/post-thread.ts
src/view/com/post/Post.tsx

Similar to https://github.com/bluesky-social/social-app/pull/3509. We set the author's DID in the cache whenever we press on a post so that we remove all spinners.
We also add `findAllPostsInSearchQueryData()` to the `findAllPostsInQueryData()` so that we populate from search results (we already had this function ready to go, but it was just not being used).
Search up something, see results
[screen-capture (4).webm](https://github.com/bluesky-social/social-app/assets/153161762/79493710-fb42-46f4-8e19-dde29e272703)

cache fix for search post results

---

bskyembed/src/screens/landing.tsx

Makes embed landing show an error if the user opted out of PWI, just as a real embed itself would.

[Embeds] Show error for users with PWI flag on landing

---

bskyembed/src/components/embed.tsx

I had quotepost embeds only allow images and externals, however the app allows the image from a recordWithMedia. This PR changes the way we cap nesting by passing a "hideRecord" prop, so we can explicitly only hide quotes in a quote, allowing their image to appear
Current behaviour:
New behaviour:
App:

[Embeds] Align nested quote behaviour with the app

---

bskyembed/src/components/post.tsx

Makes the author links only span their length instead of full width so it's easier to click on post and end up there.
Also gives cursor: pointer everywhere except post text to make it more obvious it's a link.
Gives underline to the timestamp so people can right-click it to copy url.
https://github.com/bluesky-social/social-app/assets/810438/601bfffc-63f8-4e05-ae90-c937c461cfff

[Embeds] More obvious click area

---

bskyembed/src/components/container.tsx
bskyembed/src/components/post.tsx
bskyembed/src/screens/landing.tsx

While it's slightly "nicer", it's also disconcerting to see previous embed while the next one is loading after you paste a link. I'd propose immediately clearing it to avoid any confusion.
It would be nice to add a spinner but I don't have the design chops for that. Feel free to add.

[Embed] Don't reuse DOM when changing embed

---

src/components/ProfileHoverCard/index.web.tsx

Doesn't matter hugely cause it's fine to call prefetch again but I forgot to set this ref.

Fix oopsie

---

src/components/AppLanguageDropdown.web.tsx
src/view/com/auth/SplashScreen.web.tsx
src/view/shell/Drawer.tsx

14px seems hard to tap, so let's make it 32px instead.

Increase hit slop for web's app language picker

---

src/view/com/notifications/FeedItem.tsx

We added profile hovers to the users in a notification dropdown in #3508. When we did this, we introduced the usage of another wrapper, `NewLink` (the new `Link` component). Because of how flexbox and text works in React Native, sometimes these additional wrappers really mess with text layout. Here, we just need to remove the extra `View` and place the styles that were used in that view on `NewLink` instead.
Open the notifications page on native and expand a notification.
Before:
After:

Remove extra wrapper on notification user links

---

src/view/com/profile/ProfileCard.tsx

Similar to other changes like https://github.com/bluesky-social/social-app/pull/3509. Caches the DID and profile basic view before navigating to the profile screen. This allows us to have some of the shell already visible to the user.
You can see this change in action both from the suggestions screen as well as well as from the various "Liked By", "Reposted By", etc. screens.
[screen-capture (6).webm](https://github.com/bluesky-social/social-app/assets/153161762/8f4c6be4-a6a9-42a8-889b-374f6943183f)

Cache DID and profile basic on profile card presses

---

src/view/shell/index.web.tsx

Was trying to figure out why the language picker on th drawer was near-impossible to open with touch, noticed that we're closing the drawer *even if* the tap happens inside the drawer.
Doesn't seem like the right behavior to do, this makes it so that it only happens on the backdrop instead.

Only close mobile web drawer if press happens on backdrop

---

src/components/AppLanguageDropdown.tsx
src/components/AppLanguageDropdown.web.tsx
src/lib/api/feed/custom.ts
src/state/preferences/languages.tsx
src/state/queries/post-feed.ts
src/view/shell/NavSignupCard.tsx

The goal is to get the PWI to a place where switching the language immediately has effects. This is currently blocked by some caching issues on Discover which we need to work with ops to fix. UPDATE: had to do a hackfix to workaround this (query parameter busting).
After this update:
https://github.com/bluesky-social/social-app/assets/1270099/5d2c2569-c024-41f9-bb27-8ad3a38010cb

Improve the language behaviors around the PWI

---

src/screens/Onboarding/util.ts

When we removed For You, we didn't update this sort function and it's been throwing during onboard

Fix error getting thrown by primary feed sort

---

src/state/queries/search-posts.ts

Makes the top/latest tab actually do something now
Results don't seem different yet, but I can see it in the network request

[Search] New API `sort` param

---

src/lib/statsig/statsig.tsx

Seems like conditionally including them isn't enough to get Statsig to show them in the UI. Also, let's decode the URL so it's more readable.
Tried an existing link but changed to localhost.
Also verified default values are empty strings.

Always send ref_ params

---

src/view/com/composer/ExternalEmbed.tsx

There's no real correlation between how our link cards look in the composer when seeing the preview and what you might see in your feed. To that end, we can use the existing `ExternalLinkEmbed` component to show previews to users.
Adding various types of links to the composer gives us the expected results

Use the existing `ExternalLinkEmbed` for embed previews in the composer

---

app.config.js
src/lib/app-info.ts
src/lib/sentry.ts

This resolves two problems:
- We use environment variables now to determine the channel to use for Expo updates, so the `info.channel` variable is undefined. This results in the default of `development` showing up for our builds on Sentry.
- It can be difficult to determine when adoption actually started for a particular version, since we release internally sometimes a week or so prior to cutting the production release. Instead, now we will use `-tf` or `-dev` to differentiate the various internal builds. Production builds will have nothing appended.
Also did a check to see if we rely on this `info.channel` anywhere else in the codebase, and we do not 👍 
We can check the logs going to Sentry in a Testflight client to ensure that the `-tf` string is being properly appended. We can also …

Better dist strings for Sentry

---

src/components/ProfileHoverCard/index.web.tsx

This is kind of subtle but pretty important.
If you're just scrolling, you don't want the hover popup to appear all the time due to your cursor position. In this PR, I'm adding a new behavior: scrolling away dismisses the popover (similar to unhovering).
There are some nuances.
Scrolling away _while the hover is on the card itself_ will not dismiss it. This is because, to end up in this situation, you must have moved the cursor on the card. So you might legitimately be trying to do something with it. 
Also, scrolling before the card is even visible (i.e. during the "might show" state) will reset it back to the hidden state. So this will restart the timer, reducing false positives.
I've needed to massage the abstraction a little bit to get it to be able to do this. In particular:
- The …

Scrolling while target is hovered and card is visible should hide the card

---

src/components/ProfileHoverCard/index.web.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

Self-explanatory.
Also ever-so-slightly adjusted the durations to be more conservative (wait longer before showing, hide them faster).
Verified it doesn't break native.

Add hovercards to "Reply To"

---

src/components/ProfileHoverCard/index.web.tsx

It was pointed out that hover card animations on Firefox were not working very well. If you were scrolled down the page far enough, they would stutter. Turns out we had not properly implemented `useFloating()`.
See https://floating-ui.com/docs/useFloating#open and https://floating-ui.com/docs/useFloating#ispositioned
Edit: Well, we don't actually need to use `open` or `isPositioned`, but this seems to give us a hint as to what might be causing the jank. The card starts off at 0,0 when it gets rendered, then moves to wherever it's supposed to be positioned. Moving the animation _inside_ of the moving element fixes the jank.
Using Firefox, scroll down the page about 20 posts or so, and hover over an avatar. The animations should now be smooth.

properly animate the profile hover card

---

package.json
src/lib/api/index.ts
yarn.lock

This kicks off a migration to `expo-file-system`. All we do here is remove files from the local storage after they are uploaded to prevent a growing cache.
Attempting to upload an image or images in the composer still works, and a log lets us know that the image has been deleted. Similarly, after uploading an external link card, the downloaded image gets deleted.

Cleanup files after upload on native

---

src/view/com/util/Link.tsx
src/view/com/util/PostMeta.tsx

It looks ugly.
But seriously. Right now, having the single underline for the entire text doesn't look great at all. We can separate them into two components, so they are individually underlined, but the @ doesn't look great.
Instead, let's just not underline the handle at all. It is still a link though.
Hover the display name which should still be underlined, then the handle which should not.

don't underline handle in post meta

---

eslint/use-typed-gates.js
src/lib/hooks/useOTAUpdates.ts
src/lib/statsig/statsig.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/state/shell/selected-feed.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/post-thread/PostThreadFollowBtn.tsx
src/view/com/util/List.tsx
src/view/com/util/Views.jsx
src/view/screens/Home.tsx
src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx
src/view/screens/Profile.tsx
src/view/screens/Search/Search.tsx

Our experiments are noisy. The hypothesis is that they're noisy in part because we're overcounting exposures. We only want an exposure if the GK result materially affects the outcome. However, the previous `useGate(...)` API forced us to do exposures early even if the GK results isn't even used (such as if it's only taken into account during some future event, or maybe it's used inside another condition).
To counter-act that, I'm changing the API to be:
```js
const gate = useGate()
if (gate('foo')) {
// ...
}
```
The `gate('foo')` call will log an exposure so it must be put as late as possible — i.e. at the point where it actually affects the outcome in some user-perceptible way.
```js
// Bad ❌
if (gk('foo') && bar) {
// ...
}
// Good ✅
if (bar && gk('foo')) {
// ...
}
```
Although look …

[Statsig] Fix exposure logging by doing gate checks lazily

---

src/lib/statsig/statsig.tsx

Currently, we only fetch (and poll) the feature gate configuration for the _current_ user. So if the configuration has updated for another user, and then you switch accounts, we won't know that, and we'll use stale configs from the cache. It's only another refresh that you'll get the new config for the other user.
With this change, we're always fetching configs for all accounts:
- During init, we prefetch the "other" accounts.
- During polling, we prefetch all accounts (both current and "other").
While this doesn't by itself guarantee that an account switch would give you a fresh config (we'll improve on this in a follow-up PR), it would make it more likely because last poll could've grabbed it.
Note I've also changed the polling method from `updateUser(currentUser)` to …

[Statsig] Prefetch configs for other accounts

---

src/lib/statsig/statsig.tsx
src/state/session/index.tsx

This adds a `tryFetchGates` method which can be used to optimistically prefetch gates for some user. We are using this method to kick off the fetching in these situations:
- When you sign up
- When you log in
- When you switch accounts
- When you resume session
Then, by the time we ready the UI, we *may* already have the gates. This lets them kick in immediately instead of after a refresh. That's particularly important for signup since otherwise we have no ability to AB test onboarding.
There are some nuances. If the gate service goes down or if it's too slow, we don't want to block important operations. So there is a timeout. Also, a delay on rare operations (e.g. signup) is more acceptable than, say, a delay every time you start the app. Especially considering that if you're an existing …

[Statsig] Slightly block the UI on gates

---

src/view/com/composer/Composer.tsx
src/view/com/composer/photos/Gallery.tsx

Adds layout animations + a little fade-in transition on the image. iOS-only (looks horrible on Android and `LayoutAnimation` is not available on web)
https://github.com/bluesky-social/social-app/assets/10959775/24bc180d-f49e-4eba-8ad1-73f799b99671

Add layout transitions to the composer photo gallery on iOS

---

src/components/AppLanguageDropdown.web.tsx

Closes #2963
Missed this during the initial pull request, Chrome's `<select>` menu inherits background color and font styling from CSS. Using `transparent` here causes the menu to look completely blank.
This pull request fixes the issue by placing the `<select>` behind the view, while making the view's pointer events nulled. `<select>` has been styled such that it uses the currently selected theme palette now.
(Not sure what's up with the top-left borders there, I think that's just Chrome having fractional scaling issues)

Fix splash screen language picker appearance on Chrome

---

src/view/com/composer/Composer.tsx

We don't have anywhere in this schema right now to place height and width measurements for GIFs, so we have to load the thumbnail _before_ we know the size of container which is janky. Putting it at the end of the URL like this works, and does not break the URL if the user does click through.

add dimensions to data

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx

Prior to adjustments on the left, this PR on the right. (`displayNameStyle` in this one spot, so does not affect styles elsewhere in the app)

align center post meta in threaded

---

src/components/Dialog/index.web.tsx
src/components/dialogs/GifSelect.tsx

FlatList was endlessly triggering `onEndReached` on web, and it turns out that was because it was the dialog that was scrolling rather than the flatlist. By capping the height of `Dialog.Inner`, it means that the FlatList does the scrolling.
Also includes some style tweaks.
If you want to see the original bug in action, go to https://main.bsky.dev, scroll down the timeline a bit and open the gif viewer. In the network tab you can see it loading new pages of trending gifs.
To test the fix, follow the same steps and check that this doesn't happen

[GIFs] Fix infinite pagination issue by forcing flatlist to scroll

---

__tests__/lib/string.test.ts
src/lib/statsig/gates.ts
src/lib/strings/embed-player.ts
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

This is a small pre-reqs PR that
- Updates the Giphy link rewriter to account for our new system.
- Accounts for https://github.com/bluesky-social/social-app/pull/3616 by updating the `EmbedPlayerParams` type with `dimensions`.
- Adds an additional test for that case
- Creates a new Statsig gate "new_gif_player`
- Adds some space for the new player to be rendered at inside of `ExternalLinkEmbed` although this is getting reworked a bit more in https://github.com/bluesky-social/social-app/pull/3605
There should not be any noticeable differences except right now _except_ if you have the gate enabled _and _ you use the new composer GIF picker to post a GIF. Check that other embeds still render properly and are still clickable. Also can check that the gate works properly.

Player improvement pre-reqs

---

src/view/screens/Search/Search.tsx

I kept the special empty state for PWI (since we have no suggested follows), the rest moved out of the `hasSession` codepath.
https://github.com/bluesky-social/social-app/assets/810438/8bfbfed6-b7ff-4dfc-ae2b-005920c99a02
https://github.com/bluesky-social/social-app/assets/810438/2757f150-c91d-443f-be7d-5ac87318bcad
Tried search both logged in and logged out. Switched between tabs.
Also verified directly landing on `/search` works and shows a good empty state.

Search in PWI

---

src/lib/hooks/useOTAUpdates.ts
src/lib/statsig/gates.ts

Small PR to remove updates gate. We've been receiving requests from half the user base for a bit over a week now, with no errors coming in from Sentry and a reliable backend that can handle the load.
Verified again that even if something does happen to the updates server, it does not affect the client (besides sending an error to Sentry). We actually saw this in practice during the initial 5% rollout where the backend was returning a 500 error rather than a 200. Just errors coming to sentry, no interference for the user.

remove gate from updates

---

src/components/AppLanguageDropdown.web.tsx

`<select>` has a default width, so you can't just set it's size with `inset: 0`. This was causing overflow in the nav signup card. We can just add a `max-width: 100%` to fix this.

Fix scrollbar in nav signup card 

---

src/components/RichText.tsx

Native: opens hashtag page on press. opens tag menu on long press
Web: opens tag menu on press
1. Press a hashtag
2. Long press a hashtag
3. Make sure current behaviour remains on web

Only open tag menu on long press

---

src/view/com/post-thread/PostThreadItem.tsx

Noticed over the weekend while testing that there's some strange padding on the right hand side of the post in threaded mode which makes photos or other embeds look skewed in the thread.
This should be safe, because we still have other padding that prevents the content from reaching the side of the screen:
Open a post in threaded mode that has some embeds before and after to see the difference in alignment.

remove unnecessary padding from the right hand side of the post in threaded mode

---

src/components/dialogs/GifSelect.tsx
src/view/com/util/ErrorBoundary.tsx

Adds an error boundary to the GIF picker. I couldn't reuse our existing `<ErrorBoundary>` since the error screen needs wrapping in a Dialog `<Inner>`, so I added a `renderError` prop to it so we can display a custom error screen.
Throw some errors in the GIF picker, and see if it behaves as it should

[GIFs] Add error boundary to GIF picker

---

src/locale/locales/fr/messages.po

Following on from [my previous PR](https://github.com/bluesky-social/social-app/pull/3117), I have followed the same process to update the French translations.
The way labelers are described in strings is a bit inconsistent, sometimes `labeler`, sometimes `moderation service` etc. At the moment, I have simply tried to translate (with the huge help of [DeepL](https://www.deepl.com/translator) of course 😄) the strings as they are, but now I'm thinking that perhaps aiming for more consistency would be a better approach?
Anyway, all feedback from native French speakers is gratefully welcomed – especially @Signez who was so helpful last time 🙏  Please forgive all the grammatical mistakes that I'm sure are in there, and tell me how best to fix them :)
Merci! 😊

Update French translations

---

src/components/Dialog/index.web.tsx
src/components/dialogs/GifSelect.tsx

Resets the GIF picker list to the top when the query changes. I found that triggering an effect on the debounced search string value was most reliable.
Also, this PR closes the keyboard on swipe

[GIFs] Reset scroll on query change

---

src/components/dialogs/GifSelect.tsx
src/view/screens/PreferencesExternalEmbeds.tsx

We don't need this anymore because we're going to proxy all requests.
NOTE: We still need to actually add proxying to the player — this isn't happening in this PR.
Load picker on clean storage. Doesn't ask anything. 
Load settings. See Tenor not listed there.

[GIFs] Remove consent flow

---

package.json
src/screens/Login/LoginForm.tsx
src/state/modals/index.tsx
src/state/persisted/schema.ts
src/state/session/index.tsx
src/view/com/modals/VerifyEmail.tsx
src/view/screens/Settings/DisableEmail2FADialog.tsx
src/view/screens/Settings/Email2FAToggle.tsx
src/view/screens/Settings/index.tsx
yarn.lock

- Create a test account.
- Go to settings. Enable 2FA. This will trigger email verification. Complete verification and it will be enabled.
- Log out. Log back in. You will be prompted to provide the code.
- Go to settings. Disable 2FA. This will email a confirmation code. Enter the code and it will be disabled.
- Log out. Log back in. Code no longer required.
https://github.com/bluesky-social/social-app/assets/1270099/6129f917-329f-48d1-8829-c74c81e93e88

Email auth factor

---

src/lib/statsig/events.ts
src/lib/statsig/gates.ts
src/view/screens/Profile.tsx

This adds some test-only gates and events so we can see if Metric Lifts work as we expect.
See inline comments.

[Statsig] Add test gates and events

---

src/view/com/util/post-embeds/GifEmbed.tsx

Current (notice the corners are cut off):
This PR:

Add border radius to GIF loading state

---

src/view/com/composer/Composer.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx

Adds an X in the top corner of the quote post. Does not apply to quotes added via the repost menu, should only be for pasted in quotes.
It's small, to keep it out of the way, but it has a generous hitslop
1. Paste in link and try clearing it
2. Observe you can't clear a quote added via repost menu
3. Paste in a link on top of a repost menu quote and see it is clearable

Add option to remove quoted post in composer

---

src/platform/detection.ts
src/state/persisted/schema.ts

Web-only change. Only affects the default the first time we init this setting. From that point on, it will be read from storage, as usual.
Clear local storage. Set "reduce motion" to true in system settings. Log in.
Clear local storage. Set "reduce motion" to false in system settings. Log in.
(It's playing)

Disable autoplay by default if prefers-reduced-motion

---

src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/text-input-util.ts

Follow-up to https://github.com/bluesky-social/social-app/pull/3672
Fixes https://github.com/bluesky-social/social-app/issues/3679
Fixes https://github.com/bluesky-social/social-app/issues/3665
This rewrites the logic that detects links. The main change is that we no longer rely on the cursor position — it works deterministically based on the previous and the next text content. I'm also removing regexes that try to match the URL inside the text, and instead rely on the information we already have from the facet. This also makes it work with newlines.
See inline comments for exact heuristics.
This is pretty subtle. Just watch the whole thing.
https://github.com/bluesky-social/social-app/assets/810438/4e605352-1276-4026-8044-4eac355b179e
Did some of the same testing on mobile. Running into …

Rewrite the link detection

---

src/view/screens/Settings/index.tsx
src/view/shell/Drawer.tsx
src/view/shell/desktop/LeftNav.tsx

It's pretty busy in the left pane. Adjusting moderation settings isn't something you do every day, and it makes sense for them to just live in Settings. Let's remove the shortcut from the left pane. So you'd have to go Settings > Moderation. In Settings, I moved Moderation up so that it goes after Accessibility and Languages. So it's still easy to find.
(Finally, I don't need to scroll to get to Settings.)
I reordered some stuff so these go first:

Remove Moderation from the sidebar

---

src/state/persisted/schema.ts
src/state/session/index.tsx

Fixes the pesky issue where non-blocking session resumption would cause API requests to go through `bsky.social` rather than the intended PDS URL.
This is a little more annoying than it needed to be because there isn't a single function for mapping the agent's state to the intended persisted schema. I *believe* I have caught all the cases (looked at where `upsertAccount` is being called)
**This fixes handle resolution issues during initial page load for _any and all_ accounts that are currently residing outside of bsky.social instances**. (only happens when authenticated, PWI works fine because it goes through AppView)
Should have a slight network improvement as well as it doesn't have to make connection requests to `bsky.social` first before going through the user's actual PDS.

Persist PDS URL for session resumption

---

__tests__/lib/images.test.ts
src/lib/media/manip.ts

We currently crash in simulator if Cardy returns a non-200 response (as it does when an image is missing, e.g. for google.com). Let's instead check the response status.
Verified callsites are resilient to returning undefined.
https://github.com/bluesky-social/social-app/assets/810438/43dda678-9e51-4325-afe7-f8eb062b525a
https://github.com/bluesky-social/social-app/assets/810438/419da788-213e-4dbd-9312-5b00f7e640fa
https://github.com/bluesky-social/social-app/assets/810438/d7f4a669-8383-40a6-b085-ee91658ccbe4

Ignore image responses on non-200 status

---

src/lib/api/index.ts
src/lib/media/manip.ts

We currently do not remove files after each iteration of compression. This isn't ideal because we create a lot of extra copies of images that we don't need, bloating the document storage size
This also replaces a few current uses of `RNFS.unlink()` in favor of `deleteAsync()`, although there is no difference outside of the API change.
We also make a change to `moveToPermanentPath()` which ensures the move happens. It is possible for `moveAsync()` to fail (or in this case `RNFS.moveFile()`. If it does, then we may be in trouble later on. What we should instead do is _always_ copy the file, and then delete the original if possible. That way, we are guaranteed to have a copy that we can work with in the next step of the file upload process.
This PR might not solve the root issue at hand …

Cleanup files after each iteration of compression and downloading

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/screens/Profile/Header/Shell.tsx
src/view/com/pager/PagerWithHeader.tsx

Using `pointerEvents` on iOS is preventing some areas of the bio from being "swipebackable". Since we now handle touch gestures in this region separately on iOS, we can set `pointerEvents` to `auto` in these areas.
There were a few places that we know couldn't be swiped from before:
- Banner
- Under the following count
- Very close to the left edge of the screen
On a simulator, these areas appear to be good now. Just needs to be tested in client.

remove use of `pointerEvents` on iOS profile header

---

src/App.native.tsx
src/App.web.tsx
src/lib/constants.ts
src/state/queries/index.ts
src/state/session/util/readLastActiveAccount.ts

Moves the storage read for `currentAccount` into its own util, and adds/migrates to new const for the default public `BskyAgent`.
Other PRs on this stack:
- https://github.com/bluesky-social/social-app/pull/3543
- https://github.com/bluesky-social/social-app/pull/3544
Next steps:

[Session] Base

---

src/state/persisted/schema.ts
src/state/session/index.tsx

Right now we're duplicating data between `accounts[]` and `currentAccount` on our persisted storage. This updates the schemas so that all fields except `did` are optional, and moves to using `accounts[]` as the source of truth for fresh account data for the active account.

[Session] Schema updates

---

src/lib/api/feed/author.ts
src/lib/api/feed/custom.ts
src/lib/api/feed/following.ts
src/lib/api/feed/home.ts
src/lib/api/feed/likes.ts
src/lib/api/feed/list.ts
src/lib/api/feed/merge.ts
src/state/queries/post-feed.ts

Part 1/? migrating non-trivial usages of `getAgent`. Post #3333 this approach is safe, since the whole query cache will be replaced any time the account changes (and therefore `agent` updates).
I also updated feed API constructors to accept objects, gonna want in #3695 too.

[Session] Drill `getAgent` into feed APIs

---

src/state/queries/notifications/feed.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts

Part 3/? migrating non-trivial usages of `getAgent`.

[Session] Drill `getAgent` into `notifications/utils`

---

src/lib/notifications/notifications.ts
src/view/shell/index.tsx

Part 5/? migrating non-trivial usages of `getAgent`.

[Session] Drill `getAgent` into notifications handlers

---

src/view/shell/desktop/LeftNav.tsx

I think this feels a bit better. Places Feeds and Lists closer together. Groups most commonly used ones at the top. Matches mobile which already uses this order.

Move Notifications up on desktop web

---

bskyweb/cmd/embedr/handlers.go

Looks like the default width is actually 600px, so I increased to that. Not sure if we should allow larger widths? Or whether that param is de facto even being used?
And don't return an error on out-of-range params, just return range-limited value.

embedr: handle out-of-range maxwidth; change default

---

__tests__/lib/strings/url-helpers.test.ts
src/components/Link.tsx
src/lib/constants.ts
src/lib/strings/url-helpers.ts

We have a new bsky.app/download path that redirects users to the device-relevant app store. However, if you click the link in the app it tries to do a local navigation to a non-existent page and 404s. This PR opens the share sheet instead.
Click the link in this post: https://bsky.app/profile/bsky.app/post/3kqy4mjw5eo2t

Special-case bsky.app/download to open share sheet or copy to clipboard

---

src/lib/ScrollContext.tsx
src/screens/Profile/Sections/Labels.tsx
src/view/com/util/List.tsx
src/view/com/util/MainScrollProvider.tsx

Several tweaks to how we toggle the minimal shell based on scroll for native apps:
- If there is a velocity, don't snap scroll on drag end. Instead, wait for the momentum end.
- When snapping, always hide the bar if we scrolled down. (Previously, it was snap to closest position.)
- Bump the threshold for when we always show the shell at the top. (Avoids weird empty space at the top.)
No changes on web.
This is easier to understand on video (before/after below).
This aims to resolve several interaction problems:
- If you quickly flick the feed down, the bar would previously often snap back up — because it wouldn't take the velocity into account (so the calculation would think you haven't scrolled down "far enough"). With these changes, it will no longer snap "just" at the drag end, and …

Account for momentum when hiding minimal shell

---

src/components/Menu/index.web.tsx
src/view/com/util/forms/NativeDropdown.web.tsx

Web-only.
Previously, pressing Enter on a dropdown trigger by mistake caused it to immediately auto-close.
https://github.com/bluesky-social/social-app/assets/810438/75adac58-8925-4082-9c5e-45f73799f3ce
This is because we have a hack that delays the popover toggle until `onPress` (rather than `onPointerDown` as Radix would do by default — see https://github.com/radix-ui/primitives/issues/2418). The hack helps solve the mobile scroll problem, but it _also_ kicks in for presses caused by keyboard events. This doesn't make sense because Radix has already processed the keyboard event too — so we were flipping it right after Radix has flipped it, resulting in a reversal.
The fix is to disable the hack for presses caused by keyboard events.
```diff
onPress={() => {
+            if (window.event …
```

Fix dropdown immediately closing on Enter

---

src/view/com/util/TimeElapsed.tsx

It's not needed and forces an unnecessary second render pass.
See https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes.
Waited a minute, verified timestamps get updated.

Remove useEffect from TimeElapsed

---

src/view/screens/Search/Search.tsx

Makes this work on iOS.
https://github.com/bluesky-social/social-app/assets/810438/399c753d-f351-46e9-bd12-efd065c5ab1e
Doesn't touch Android or web.

[iOS] Fix selecting search input on focus

---

src/view/screens/Search/Search.tsx

The hit area on the search text input is pretty small right now. What we can do instead is make the wrapper a `Pressable` and call `.focus()` whenever we press anywhere inside the gray pill.
Open the app, tap around on the input. It should be a lot easier to focus now.
Also tested that the clear input button still works as well as our "select text on focus".
https://github.com/bluesky-social/social-app/assets/153161762/31c3dc26-79c4-41c2-8f3e-dc831e7908fe

Increase search `TextInput` hit area and improve the related UI

---

src/view/screens/Search/Search.tsx

Removes the layout animation I added to #3748 because they break after navigation. Might be same issue as https://github.com/software-mansion/react-native-reanimated/issues/4516 but the fix is chunky and not worth the risk upgrading.

Remove layout animation from search

---

src/view/screens/Search/Search.tsx
src/view/shell/desktop/Search.tsx

The first few commits extract components with no changes to their logic and add some `memo`s.
The main real change is https://github.com/bluesky-social/social-app/commit/e46aac205c808caea2311c15b55455013eeec0f2. It renders both the autocomplete *and* the result list so that switching between those is less laggy. This is especially noticeable on iOS.
Finally, there's a few drive-by changes. https://github.com/bluesky-social/social-app/commit/16a13c5347e224a28bfe6c7612c94f9859da6a34 removes subdomain matching — it is not very useful now that we properly rank results, and it looks a bit out-of-place in the list. Also, https://github.com/bluesky-social/social-app/commit/36485ea7e9d7db5eddd5b95ac85c4d8cab2ec9bf adds some missing hitslops to the recent searches.
The usual for this screen. …

Improve search screen perf

---

src/view/screens/Search/Search.tsx

We used to do this, but looks like we removed the logic on accident while reworking `onPressCancelSearch`. This adds back the logic that returns the user to the "Follow Suggestions" root screen after pressing the tab button again.
Normal for this screen, and test the search tab button after searching to see if it properly takes you back.
https://github.com/bluesky-social/social-app/assets/153161762/f15c5558-90fb-4b57-8338-ca63b823c882

clear search on tab press

---

app.config.js
plugins/withAndroidStylesAccentColorPlugin.js

Some places on Android are currently using the default [Material Teal](https://m1.material.io/style/color.html#:~:text=Teal) color, including the TextInput cursor, TextInput selection, and the spinner (ActivityIndicator) --- it's quite out of place whenever it shows up.
This PR sets Expo's primaryColor to #1083fe (which is the color that defaultTheme.palette.default.brandText resolves to), then applies it as the native accent color via a plugin (because Expo doesn't apply the accent color).
Comparison:
| Before (composer & signup) | After (composer & signup) |
|--------|--------|
| ![before-composer](https://github.com/bluesky-social/social-app/assets/11722318/6d8eaee4-5fd9-4938-afca-867058e68db7) | ![after-composer](https://github.com/bluesky-social/social-app/assets/11722318/4b94e4a0-d36 …

android: fix various places still using default Material Teal

---

package.json
yarn.lock

Just switches to using the main branch vs the `4.6.1` branch. I did:
- Merged Discord's 4.6.1 branch - what we were using - into main
- Reverted https://github.com/gorhom/react-native-bottom-sheet/pull/1288. See https://github.com/bluesky-social/react-native-bottom-sheet/commit/4af77ba9158fd2356650c952f6e8ff6ae9e8ec0b
- Tested that accessibility now works.
- Tested that closing the dialog w/ the keyboard open still works (this verifies that the 4.6.1 branch is now on main).
We shouldn't need to mess with this anymore.

switch branch for installing `react-native-bottom-sheet`

---

src/components/dialogs/GifSelect.tsx

Forgot about this prop when adding this, so I dismissed the keyboard manually when scrolling starts. `keyboardDismissMode` is much clearer
Make sure keyboard still dismisses on scroll

Use keyboardDismissMode rather than onScrollBeginDrag in GIF select

---

src/lib/hooks/useAccountSwitcher.ts
src/screens/Login/ChooseAccountForm.tsx
src/state/persisted/schema.ts
src/state/session/index.tsx

Extracted from https://github.com/bluesky-social/social-app/pull/3728.
These changes are supposed to be 100% safe.
See individual commits. I'll comment inline on a few things.
Careful reading. The point of these is that largely you can apply them without testing because they "obviously" work.
Also, some logging in / logging out / switching accounts.
Should be no observable changes.

Session fixes, pt. 1

---

src/state/session/index.tsx

This didn't make sense because `prevSession` is only used as something we assign to `agent.session` (or pass to `agent.resumeSession` that does that assignment for us). But sessions have no `.deactivated` fields — only accounts do.
The only actual place where we depend on this field is right below, so I extracted it to a variable.
Careful reading. Following types. Grepping `deactivated` to see usages.

[Session] Move deactivated field off the session object

---

src/screens/Signup/StepCaptcha/CaptchaWebView.tsx
src/screens/Signup/StepCaptcha/CaptchaWebView.web.tsx
src/screens/Signup/StepCaptcha/index.tsx
src/screens/Signup/index.tsx
src/screens/Signup/state.ts

We should have some more robust error reporting around signups. This adds Sentry logs to the most sensitive areas of that flow:
- Captcha webview errors
- Other cases where a captcha isn't set (we shouldn't hit this one but just in case?)
- Any failure after submitting the registration request
Not really sure how to test this one, aside from waiting for these to come through on Sentry. For what it's worth, we already had some of these coming through but this makes the errors a little easier to set up alerts for using the "Signup Flow Error:" prefix.

sentry errors for captcha web views and registration attempts

---

tsconfig.json

My editor's typescript language server kept crashing and overall being extremely slow. I realised this started when we did the embeds, and on closer inspection our base tsconfig is not scoped to the `src` directory, so was looking at every directory. This PR excludes `bskyembed`, which has its own tsconfig, and also `bskyweb` and `web-build` because there might be some lingering JS files in there that we don't need typechecking.

Exclude bskyweb, bskyembed, and web-build in tsconfig

---

src/state/session/index.tsx
src/state/session/types.ts

See individual commits.
- cf360ed927a573d43ec67647c09e8843c0c21a36 and 5d0d740a75b77146eb990b90643c6601f4f22ea6 move `isInitialLoad` and `isSwitchingAccounts` out of the main `state` object, similar to how they're taken out in #3728.
- 5d0d740a75b77146eb990b90643c6601f4f22ea6 is just a visual cleanup so we always see the `state` object shape.
- Now, 9e0dd84fc3b5c627caadff7e3abb6aea35a1c610 is the interesting bit. This is a change in strategy both from what's in main and what's in #3728. If this change looks good, I'll update the other PR to match it. See below.
- 2cdab86f97546b5b44286aff40f5eae506eb3860 is just a line reorder.
Whenever we update `accounts` or `currentAccount`, we need to persist that change to the local storage. There is only one exception to that — we don't want to do …

[Session] Use flag on state for persistence

---

src/state/session/index.tsx

We should be able to reconstruct `currentAccount` on demand from `accounts` and only track the current DID instead. Although we've wanted to make a bigger change to this in #3728 (and reconstruct it from agent), I'm doing a more incremental step here.
Careful reading. Verify login/logout/switch still works. Do it in another tab too.

[Session] Derive currentAccount from accounts + currentAccountDid

---

package.json
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
yarn.lock

I'm adding one new package here for web `react-textarea-autoresize`. If anyone has a good idea on how to do this on web w/o the library that would be fine too. Seems to be quite a pain to get right though and to maintain accessibility.
https://github.com/bluesky-social/social-app/assets/153161762/eb603925-09d1-4225-ac19-6c6e87c6c55b
The first messages are me just hitting Enter. The subsequent new lines are me pressing Shift + Enter
https://github.com/bluesky-social/social-app/assets/153161762/7de6b4ad-f2ee-4ff1-a700-8cf93fe0f265

[Clipclops] Dynamic input height

---

src/App.native.tsx
src/App.web.tsx

Turns out that the moderation opts context depends on the label defs context. This fix restores 3p labeler behaviors.

Fix: put label defs provider above moderation opts provider

---

src/view/screens/ProfileList.tsx

We were still allowing users to mute/block user lists. We made this mistake a long time ago, and at the time, backend actually allowed user lists to block and mute other users. We've since updated this so that only moderation lists work in this way, but some users still have user lists that are blocked or muted.
The intention is to NOT allow users to block/mute user lists. But if they have them blocked/muted bc of this mistake, we should allow them to un-do this. That's what this PR does.

Allow unmuting and unblocking of curate lists, but not the opposite

---

src/App.native.tsx
src/App.web.tsx
src/state/session/index.tsx
src/state/session/types.ts

`resumeSession` is a thin wrapper over `initSession` which sets `setIsInitialLoad(false)` to hide the splash and then becomes effectively the same as `initSession`. I was wondering if I could get rid of it, and the only usage of `resumeSession` was from top-level `InnerApp` components which, conveniently, were the ones who needed `isInitialLoad` in the first place (to hide the splash). So I removed `resumeSession` from the Session API and removed `isInitialLoad` from its context.
I want to pare it down, and `resumeSession` doesn't depend on any knowledge that isn't already available through the Session API. So it made sense to me to move it out to keep that code more focused. Conceptually we have one instance of the `InnerApp` component (it's just forked between two platforms). The local …

[Session] Extract resumeSession out

---

src/components/AccountList.tsx
src/components/dialogs/SwitchAccount.tsx
src/lib/hooks/useAccountSwitcher.ts
src/screens/Login/ChooseAccountForm.tsx
src/state/session/index.tsx
src/state/session/types.ts
src/view/screens/Settings/index.tsx

This is similar to https://github.com/bluesky-social/social-app/pull/3811 in spirit and is based on the same insight. `selectAccount` has nothing to do with session management per se, it's just a wrapper around `initSession` that tracks the progress of that call. It makes sense to make such state tracking local to where the action was triggered in the UI code. So I'm moving that state back into components.
I moved the `isSwitchingAccounts` state variable out of the Session API and into the calling components which now call `initSession` directly. For `AccountList`, I've plumbed it down from the component that owns the switch press handler.
Use the account switcher, both the popover and the settings one. It feels a bit janky but I replicated the existing logic. This should make it a bit …

[Session] Extract selectAccount out

---

src/Navigation.tsx
src/components/dms/ConvoMenu.tsx
src/lib/hooks/useNavigationTabState.ts
src/lib/hooks/useNavigationTabState.web.ts
src/lib/routes/types.ts
src/routes.ts
src/screens/Messages/Conversation/index.tsx
src/screens/Messages/List/index.tsx

There's a convention I didn't notice that the root screen of each tab has to be named `Xyz` and the tab, `XyzTab`. I'd named them `MessageList` and `MessagesTab` so it wasn't able to figure out that `MessagesList` was the root screen

[Clipclops] Fix messages tab active state

---

src/screens/Messages/Conversation/MessagesList.tsx

The `KeyboardAvoidingView` requires adjustment to position the input correctly. Previously, I had trial-and-error'd the numbers requires for `keyboardVerticalOffset`. However, since the gap looks different on my base iPhone 14 vs the iPhone 15 simulator, I am fairly confident in saying that it's device specific.
On iOS: seems like it's the `top` safe area inset
On Android: seems like it's the navigation bar height
To handle this, I moved the logic out to a custom hook

[Clipclops] Create `useKeyboardVerticalOffset` hook

---

src/lib/statsig/gates.ts
src/view/screens/Home.tsx

Currently, the "disable min shell on foregrounding" behaviour is in a `useEffect` in the home screen component. However, React Navigation does not unmount components even if you're on a different tab, so this means that this actually happens on every screen in the app, so long as you've loaded the home tab at some point (which you almost certainly have).
This wouldn't matter except that the new messages screen uses min shell mode, so if you unbackground it on the messages screen the tab bar overlaps the text input.
I've changed it to use `useFocusEffect` from React Navigation, which only runs the effect when the screen is active
Check that the behaviour is unchanged on the home tab
Unbackground on the messages screen, and see that there's no tab bar

Only run "disable min shell on foregrounding" behaviour if on the home screen

---

src/components/AccountList.tsx
src/components/dialogs/SwitchAccount.tsx
src/lib/hooks/useAccountSwitcher.ts
src/screens/Login/ChooseAccountForm.tsx
src/view/screens/Settings/index.tsx

Addresses https://github.com/bluesky-social/social-app/pull/3812#issuecomment-2090771077.
- No longer jump the vertical height when switching accounts
- Fix potential races by ignoring switch requests while switching
- Provide visual feedback while switching (pending account remains selected)
- Ignore _all_ presses within that UI (even "Sign out" or "...") while switching
Still far from perfect but a little bit more sturdy. I kept the visual style mostly as-is.
Recorded with an extra 1500ms artificial delay inside `initSession`.
https://github.com/bluesky-social/social-app/assets/810438/9c5ac207-412d-47e0-9e99-3f5c10443cdc

Improve account switcher pending state

---

src/state/session/index.tsx

Extracted from https://github.com/bluesky-social/social-app/pull/3728.
This is a plain refactor, no change in functionality. We had a bunch of indirection that turned out to be unnecessary and that made it way harder to read what this code is actually doing. This removes the indirection.
Concretely, `networkErrorCallback` was always specified to be `clearCurrentAccount`, and `persistSessionCallback` was always specified to be `upsertAccount`. So this inlines those calls directly and removes the configurable parameters.
There are likely some fixes and simplifications we can do on top but let's get this in first.
This is a bit tricky to test because you need to trigger one of the conditions that get us into the persist handler. One of those is the initial update when resuming a session. So …

[Session] Call persist handler directly

---

src/state/session/index.tsx

Extracted from #3728 but slightly adjusted.
The point of #3728 was to move the agent into React state so that it has a predictable lifetime and we don't depend on reading the global. This PR takes an incremental step by storing a `{did, agent}` pair in state instead of just the `did`.
Note I'm storing `{did, agent}` rather than just `agent` as done in #3728. This is because we can't safely derive a did from an agent instance. The only way to do that is to do `agent.session.did`, but `agent.session` is `undefined` if the session has expired. So keeping track of the agent alone is not enough.
To avoid them getting out of sync, I store them in a group (rather than two top-level keys) and encourage thinking about `{did, agent}` as a unit ("agent state"). I'll later change agent factories to …

[Session] Track agent in state

---

src/state/session/index.tsx

Extracted from #3728. The fix is https://github.com/bluesky-social/social-app/commit/b0aa70d26ade390704e735f3ababc6d493b9ac1c.
The intent of this code was to use the value from the session and fallback to the stored value if the session isn't present. However, if `session.emailAuthFactor` (newer) is `false` but `account.emailAuthFactor` (older) is `true`, the `session?.emailAuthFactor || account.emailAuthFactor` expression will keep giving us `true` even though `false` is the fresh value here. So we'll store and display the incorrect stored `true` value.
The fix is to use `??` instead. I've updated a few other places we use `||` for fallback values for consistency in the second commit, but that shouldn't affect the behavior.
To trigger this, you'd need to get a "session changed" event …

[Session] Fix stale emailAuthFactor and emailConfirmed on the client

---

src/logger/debugContext.ts
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/__tests__/convo.test.ts
src/state/messages/convo.ts
src/state/messages/index.tsx

With this PR, `Convo` is hooked up to `useSyncExternalStore`.
- When React subscribes (goes from 0->1 listener) we init the `Convo`, and when React unsubscribes (1->0) the `Convo` enters a `suspended` status
- `Convo` can resume from `suspended` status if it needs to
- When screen is backgrounded by React Navigation, `Convo` enters a `backgrounded` status, and polling drops to once every 10s (from every 2s by default)
- When refocused, `Convo` resumes from `backgrounded`
- Snapshotting is lazy, only when React requests it
- Snapshots only change when a new message is received or sent
- Each `Convo` interface returned from `useSyncExternalStore` differs by `status`, but retains the same shape each time
- This discriminated union might be a little much, but didn't want to totally change it …

[Clipclops] External store, suspend/resume

---

src/state/session/index.tsx

Extracted from #3728.
See two individual commits.
- 7095822a5b97ffad86ee1a7bccf431594f216790: When we resume session, we don't want to block the UI so we assume it'll come through. Still, we kick off a `resumeSession` request in background. When that request comes back, we want to persist the new session if it's different from what we've stored. Turns out, we don't actually need to write this logic explicitly because the `onAgentSessionChange` handler already has the logic to handle session updates — and the agent will call it. So just kicking off a resume is sufficient on its own. Errors would be reported to `onAgentSessionChange` as well.
- https://github.com/bluesky-social/social-app/commit/529d1fec07e0f6be67895a49882bf0919ad26ccd: Previously, we had an optimization that avoids a state …

[Session] Rely on agent session change event for persisting resumed session

---

src/state/session/index.tsx

Fixes a mistake I introduced in https://github.com/bluesky-social/social-app/pull/3836.
Extracted from https://github.com/bluesky-social/social-app/pull/3728.
The change in https://github.com/bluesky-social/social-app/pull/3836 assumes the persistence handler will handle any errors. However, our `onAgentSessionChange` persistence handler does not currently update `__globalAgent` on expiry (despite updating the related state). This is inconsistent with how the same persistence handler treats `network-error` (for which it does update `__globalAgent`).
Updating the global agent seems like the correct behavior if we're updating the UI to show PWI. So this seems like an omission in the existing code (which #3836 made worse). I suppose this was less important before …

[Session] Reset global agent on expire

---

src/screens/Messages/Conversation/MessageListError.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo.ts

Review without whitespace: https://github.com/bluesky-social/social-app/pull/3837/files?diff=split&w=1
This PR introduces some new `ConvoType`s, `error-fatal` (unused atm) and `error-recoverable`, which has a `retry` method and will probably be used differently from the fatal version (if we even need that). The idea is to insert a given `ConvoError` type into the flow of items.
This PR handles only failed history fetches. But imagine similar errors appearing above or below other messages.

[Clipclops] Moar error

---

src/components/dms/MessageItem.tsx

We were using `toISOString().slice(0, 10)` to determine if a message was sent yesterday, but it only worked if you live at GMT+0. Updated to use the local date instead

[Clipclop] Update date logic to account for timezones

---

src/App.native.tsx
src/App.web.tsx
src/lib/hooks/useAccountSwitcher.ts
src/screens/Login/ChooseAccountForm.tsx

While working on the session code I've noticed we have a bunch of weird `setTimeout`s around toasts, and that toasts work poorly when switching accounts in general. Turns out, it's because we unmount them.
In this PR, I've relaxed it so that toasts are placed outside the area that gets remounted on user change. As a result, I was able to remove the fragile `setTimeout` hacks. See individual commits.
- https://github.com/bluesky-social/social-app/commit/dcb14756808c813ef79176a27f8ebf09bb70fb8e?w=1: Puts legacy theme provider next to Alf provider.
- https://github.com/bluesky-social/social-app/commit/38a02b85ec0b15cff18b712cd626c16ce81cff55?w=1: Moves `RootSiblingParent` upwards. This is where toasts get mounted on native. I'll assume we _only_ use it for toasts so it's fine to bleed …

Don't clear toasts when changing users

---

src/lib/hooks/useAccountSwitcher.ts
src/screens/Login/ChooseAccountForm.tsx
src/state/session/index.tsx

Extracted from #3728.
There's a few different changes here but they all work together towards the goal of aligning `__globalAgent` assignments with `setState` calls that modify `currentAgentState`. Once they fully align, we can kill the global.
This PR doesn't fully get us all the way there because it leaves some existing timing differences.
I will address them in a follow-up.
These are meant to be safe but slightly riskier than the ones before.
I suggest reading each change in isolation.
This moves [this `setState` on `persisted.onUpdate` callback](https://github.com/bluesky-social/social-app/blob/1e484c6318c0f1a2fa46c028d53b92d817293d11/src/state/session/index.tsx#L538-L542) to the beginning of the function.
The purpose of this `setState` is to update the current `accounts` to the …

[Session] Align state and global agent switchpoints

---

src/components/dms/MessageItem.tsx
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/useScrollToEndOnFocus.ts
src/screens/Messages/Conversation/useScrollToEndOnFocus.web.ts
src/state/messages/convo.ts

Turns out that `inverted` messeds up the accessibility - the accessibility is _also_ inverted on android and web. So this refactors to a normal `FlatList`
Did some explaining of the quirky things below. There are sure to be some things to tweak over the next week, but this feels like a _decent_ implementation of what we need. At some point, a better implementation - maybe one that fixes some of the issues present in `FlatList` as of right now - would be useful and probably feel better.

[Clipclops] Refactor message list

---

src/view/com/util/List.web.tsx

Right now, we use `IntersectionObserver`  to tell when we have reached the bottom of the page in our web `List` implementation. The currently implementation however has not worked correctly with the `onEndReachedThreshold` parameter. The parameter should fire `onEndReached` whenever we reach X pages away from the bottom of the scrollable content. That has not worked here, and we would have to hit the end to actually load new data.
The problem turned out to be that we were not configuring the `rootMargin` properly. We can think of the value we supply to `rootMargin` as a box surrounding the parent of the `Visibility` element. So, with our current logic of using `100%, 0px, 0px, 0px` this is what it looks like.
We will never end up firing `onEndReached` here until we reach the end!
Instead, …

Fix `IntersectionObserver` `rootMargin` in web `List` implementation, add `onStartReached`

---

src/components/Prompt.tsx
src/components/dialogs/MutedWords.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ExternalEmbed.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/composer/photos/Gallery.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/GifEmbed.tsx

Adds a way to add alt text to GIFs, via the `description` field on the embed.

Alt text for gifs

---

src/lib/statsig/gates.ts
src/view/com/util/List.tsx
src/view/com/util/Views.jsx
src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx

Since https://github.com/bluesky-social/social-app/pull/3429 we've been running some tests where we removed the vertical scroll indicators for some users. In the end - after figuring out the proper way to test this case - it seems that there is not a significant difference in usage between having these scrollbars visible and not having them visible.
I think that there would have been a time that I would have said "since there is not a significant difference in usage, maybe we should just keep the change since it appears cleaner". However, two things have changed my mind on this
1. I asked some users how they felt about this and - although a really small sample size - they were mostly in favor of keeping the scroll bars visible.
2. I actually discovered - thanks to [this …

remove `hide_vertical_scrollbars` test

---

src/screens/Messages/Conversation/MessageListError.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/__tests__/convo.test.ts
src/state/messages/convo.ts

This PR handles the obvious error states. There are likely more to consider, but wanted to get the main guards in place.
- Clarified which states have what data
- Moved some state into `Convo` to help with this, see `sender` and `recipients`
- Most errors are retry-able, except failures during initialization
- Handled initialization error, needs UI
- Handled failed resumption and polling

[Clipclops] All my clops gone

---

app.config.js
package.json
yarn.lock

Deadline is looming tomorrow. I believe this should be an automatic process in 0.74 (my early testing resulted in the build process generating one of these files for us!) However, there's various upgrades that need to happen and I think it would be safer for us to not prematurely upgrade these without a bit of testing.
Documentation for the app config can be found here: https://docs.expo.dev/guides/apple-privacy/
Apple's documentation can be found here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
See https://github.com/react-native-async-storage/async-storage/pull/1075
See https://github.com/expo/expo/blob/c50b313944694af95c7ac22799eb33495332fb11/packages/expo-application/ios/PrivacyInfo.xcprivacy
See …

Add PrivacyManifest info to comply with new App Store guidelines

---

src/lib/media/picker.tsx
src/lib/media/picker.web.tsx
src/state/modals/index.tsx
src/view/com/modals/crop-image/CropImage.web.tsx
src/view/com/modals/crop-image/cropImageUtil.ts
src/view/com/util/UserBanner.tsx

This is a fix for the banner cropper issue closes https://github.com/bluesky-social/social-app/issues/760
Before:
After:
Note that in the "after" image the preview matches what you'd actually see ending up in the banner after clicking "Done"
Previously when uploading an image, you could choose aspect ratios, but none of them would fit the banner aspect ratio. I have modified the banner cropper on web to take into account the aspect ratio of the given width/height provided to the cropper [here](https://github.com/bluesky-social/social-app/blob/main/src/view/com/util/UserBanner.tsx#L67):
```
onSelectNewBanner?.(
await openCropper({
mediaType: 'photo',
path: items[0].path,
width: 3000,
height: 1000,
}),
)
```
I have also hidden the options to pick an aspect ratio in the cropper when the …

[Issue 760] Use correct aspect ratio in banner cropper

---

bskyweb/templates/base.html
src/App.web.tsx
web/index.html

- Bluesky logo in the center when a new visitor or shift+refresh by browser client
Demonstration:
https://github.com/bluesky-social/social-app/assets/31815005/5803c5f0-7cb5-4ff3-a701-f284a176e8ab

Add Preload for Web

---

.easignore
.github/workflows/build-submit-android.yml
.github/workflows/build-submit-ios.yml
.github/workflows/bundle-deploy-eas-update.yml
src/lib/app-info.ts

- Don't cancel still-running bundle deploys if we merge another PR. Feels better to just let them run (this is for internal use only)
- Replace a null check with what is supposed to just be an equality check
- Always fetch some commits so that we can get the commit hash
- Add `.env` to `.easignore`
Regarding the last point, if we don't add this to the `.easignore`, it won't pick up our environment variables. See `eas build:inspect --stage archive -p ios --output sampleBuildFiles`

fix bad bool check in action

---

src/view/com/threadgate/WhoCanReply.tsx

Before:
After:
Fixes an issue in `WhoCanReply.tsx` where a bigger font size was set for `TextLink` only.

Update font size in WhoCanReply

---

src/view/screens/Feeds.tsx

Sets the `paddingHorizontal` of the Saved feeds header to 18, just like the headers on other pages, such as Settings, Notifications, etc.

Update horizontal padding for Saved feed header

---

src/lib/gif-alt-text.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/util/post-embeds/GifEmbed.tsx

If user-defined alt text is blank, this falls back to the bad one we get from tenor
- Starts with 'Alt text: ': user-defined, show badge
- Starts with 'ALT: ': default, don't show badge

[GIFs] Restore default alt text

---

.github/workflows/bundle-deploy-eas-update.yml

So, it turns out that `actions/checkout@v4` does not overwrite cache keys. This was revealed after fixing a boolean check last night. Now, TestFlight releases are using a bad previous commit hash which is always triggering a new build now.
Instead, let's save to a new key on every run. We'll pull from the cache using the `last-successful-deployment-commit-{branch}-` prefix to find the old one instead of just a static string.
Production builds were running appropriately because they do not pull from the cache but rather use version-specific tag for a base commit, so this only affects internal builds.
This also lets us actually use the `cancel-in-progress` correctly, since the cache will actually be properly updated.

create new cache key on each run when saving previous commit hash

---

src/screens/Messages/Conversation/MessageListError.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/convo.ts
src/state/messages/index.tsx

[Reviewing without whitespace](https://github.com/bluesky-social/social-app/pull/3880/files?diff=split&w=1) helps a bit.
This PR handles state transitions from app foreground to background, including tab focus on web. It also begins to guard async data fetching from being called while another request is in-flight.
To do so, I refactored the state transition logic into a reducer. All updates to `this.status` go through this reducer. Various side effects are then called.
- state transition logic is synchronous
- consecutive state transitions don't clobber each other
- example: open chat, then nav away while initializing, chat will resolve to correct `status`
- certain states only support a subset of actions
This should make it far more clear what's happening, and help us avoid invalid …

[🐴] State transitions

---

src/App.native.tsx
src/App.web.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/current-convo-id.tsx
src/state/messages/events/index.tsx
src/state/messages/index.tsx

Integrates global clipclop log event bus + introduces a small bit of context at a top level for current convo id, so that we can suppress unread state updates and push notifications.
Double checked the conditional rendering of the event bus context, should not affect uses without clipclops enabled, or without the service URL.

[🐴] Integrate global event bus

---

package.json
src/state/session/__tests__/session-test.ts
src/state/session/reducer.ts

Adds tests for the code from https://github.com/bluesky-social/social-app/pull/3852 and https://github.com/bluesky-social/social-app/pull/3854.
I chose to test the reducer directly because that's where most of the domain logic is, and some of it is subtle. Normally I don't like unit tests in product code and I wouldn't encourage adding many more of them, but this seems worth it.
I've chosen a combination of explicit assertions (to catch critical mistakes) and inline snapshots (to catch accidental drift in the output). If these tests start feeling painful at any point I think we shouldn't hesitate relaxing and/or deleting them.
From what I've tested, this seems to give 100% coverage on the existing reducer codepaths.

[Session] Add tests

---

bskyweb/cmd/bskyweb/rss.go

for any typescript reviewer: the way the golang `time` library works is that you give it an example string with special values for each part (year, minute, etc), and the library infers the pattern. I copied the RFC822Z example from the library and made it a four digit year, then tested locally that this is working as expected.
closes: #3362

use four-digit years for RSS pubDate

---

src/state/messages/events/agent.ts
src/state/messages/events/const.ts
src/state/messages/events/index.tsx
src/state/messages/events/types.ts

This PR refactors the existing event bus to remove `useSyncExternalStore` and therefore remove coupling of the state within the event bus from React's state system. This class is a simple singleton now, and will be interacted with via implicit methods and event listeners.
It also adds two new events: `connect` and `error`, for communicating with the `Convo` class.
- `error` reports initialization or polling errors
- `connect` reports a successful connection, and can be considered the success outcome from an `error` state
These events [will be hooked up to the Convo class](https://github.com/bluesky-social/social-app/pull/3915/files#diff-725d0af24590b680253cf466890391f282b0c019ab5555dc0d701903f739d7d2R46-R57) so it can communicate with it and let it know if polling has failed. This will …

[🐴] Refactor event bus

---

src/state/messages/convo/agent.ts
src/state/messages/convo/const.ts
src/state/messages/convo/index.tsx
src/state/messages/convo/types.ts
src/state/messages/events/agent.ts

This PR integrates the newly refactored event bus from #3919. This removes the need for the `Convo` agent to do its own polling.
Another key improvement is that `Convo` can now handle incoming firehose events _prior to being in a `Ready` state_. Meaning, you can open a chat, and see incoming messages immediately, and we fetch history in the background.

[🐴] Integrate event bus

---

src/lib/statsig/gates.ts
src/screens/Onboarding/index.tsx
src/screens/Onboarding/state.ts

This PR adds the feature gate, and copies the full state from existing -> reduced. So even with the flag enabled, onboarding should function the same as it does today.
Test:
- load locally and clear onboarding, should look the same

[Reduced Onboarding] Add feature gate, a:a swap onboarding state

---

src/alf/atoms.ts
src/components/RichText.tsx
src/components/dms/MessageItem.tsx
src/lib/strings/rich-text-manip.ts
src/screens/Messages/Conversation/MessagesList.tsx

Adds support for links, mentions, tags. Not yet displayed while typing, it generates them just as you send and then the bubble can now display them

[🐴] Rich text in messages

---

src/state/session/agent.ts

Carries over https://github.com/bluesky-social/social-app/pull/3728/files#diff-ba67025ff0027278031f772f88a9ed2f7fa4b12421d0a423ad74b4937aa2ca53R281 from #3728.
My bad that I missed it.
This fixes the false positive "you have not verified your email" popup. The `emailConfirmed` flag is not required so I forgot to specify it. So when you resume session from storage, the first render will not have the full object.
The full object still arrives a bit later (and gets written to the persistent storage) but then the same problem happens on next refresh. (The reason people don't see the same problem on next refreshes now is due to the auto-snoozing flag for this popup.)
Comment out all the other checks in `shouldRequestEmailConfirmation`. Verify that the full object comes through when you refresh …

[Session] Restore emailAuthFactor and emailConfirmed from last session

---

src/screens/Messages/Conversation/MessageListError.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo/agent.ts
src/state/messages/convo/types.ts

This PR:
- gets rid of original retry message UI and handling and replaces with the same handling as other errors
- makes sure all network errors are handled
- improves styling

[🐴] Handle errors, improve styling

---

src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/convo/agent.ts

Cherry picking this out of https://github.com/bluesky-social/social-app/pull/3945, because it's really separate from that PR and I'd like to get this one in to test on device.

[🐴] Remove extra spinner states from chat screen

---

src/lib/hooks/useNotificationHandler.ts
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/screens/Messages/List/index.tsx

**[without whitespace](https://github.com/bluesky-social/social-app/pull/3945/files?w=1)**
I'm a little concerned about obscuring handles in DMs behind long display names. Since it's a more personal conversation, I think there's benefit in making sure that the user can actually see who it is that they are talking to.
Open to ideas on this of course!
Also removes the extra spinner states that were jumpy, and prevents the list from flickering on initial render on native.
Use the same size and (almost) alignment as feeds so there isn't a noticeable shift. I say almost because we really need to move away from the odd-number old style system - or convert the new one to odd numbers - so there's an ever-so-slight difference here. (Note, spacing between handle and message is a little higher here, …

[🐴] Adjust messages list styles

---

src/state/messages/__tests__/convo.test.ts
src/state/messages/convo/agent.ts

I noticed the other day that I was retaining deleted messages in the optimistic `deletedMessages` array. `pastMessages` are things loaded from history, and `newMessages` are things added from the firehose. So I need to check for existence in both those arrays and clean up once I get a committed event from the firehose.

[🐴] Clean up after deleting message

---

src/state/messages/convo/agent.ts
src/state/messages/events/agent.ts
src/state/messages/events/types.ts

Simplifies the contract between the two agents and removes some unused types. It also ensures the events are torn down when the class is suspended.

[🐴] Simplify message passing, cleanup

---

src/screens/Onboarding/StepFinished.tsx
src/screens/Onboarding/StepProfile/index.tsx
src/screens/Onboarding/index.tsx
src/screens/Onboarding/state.ts

Base of #3933
Gated behind a feature flag. If enabled, you'll see this reduced onboarding flow. Pictured is the first step, which is currently empty. The second and third steps are interest selection and a welcome screen, but nothing has or will change there.
Note: I applied new fields in `state.ts` to old types, so they apply for the old flow too, for simplicity. They'll have no effect, and we'll be able to remove these when we ship reduced onboarding to 100% (or not).

[Reduced Onboarding] Add new step, new state to reducer

---

src/screens/Onboarding/StepFinished.tsx
src/state/queries/profile.ts

See individual commits.
- https://github.com/bluesky-social/social-app/commit/d8ee3b630d2ae907df0a0e613cd3640ed683296a: Fixes a flash after new onboarding that caused Following to get selected instead of Discover. The problem is we were writing Discover into `savedFeeds` via `overwriteSavedFeeds`, but RQ has already cached initial `savedFeeds` (just the `following`), and we had a flash of that during the initial Home render. The fix is to invalidate RQ cache before going to Home.
- d8265e52650941a565e8593316a2326e9931b39a: There is no reason for this call to be serial from what I can see. It can be parallelized against bulk follows and setting prefs. Only setting prefs has to be serial (because lol, we designed it to be this way).
- …

Onboarding fixes

---

src/state/queries/preferences/index.ts
src/view/com/posts/FeedShutdownMsg.tsx

We were triggering multiple mutations, each of which invalidates the prefs. So the transition felt very jumpy (two full screen refreshes one after another). This fixes it by introducing a special mutation just for this case, with one invalidation at the end.
This also changes "Remove" button to move you to Discover if you already have it pinned.
Note it's still a bit janky because there's an interrupting pager animation. But that already exists on main too.
Press Remove when Discover is not saved:
https://github.com/bluesky-social/social-app/assets/810438/39c7a851-5188-487a-bee6-45ed58d9f0c7
Press Remove when Discover is saved (but not pinned):
https://github.com/bluesky-social/social-app/assets/810438/022a96da-dae2-444d-9382-793582a3b239
Press Remove when Discover is pinned: …

Fix flashes when replacing For You

---

src/lib/api/feed-manip.ts
src/state/queries/post-feed.ts
src/view/com/util/List.tsx
src/view/com/util/List.web.tsx

- https://github.com/bluesky-social/social-app/commit/3cc47165a9bd6f064ef269e4995838e4b6d97502: Lower the time threshold to 1500ms as discussed with @whyrusleeping.
- https://github.com/bluesky-social/social-app/commit/14f00d55cae9a8ed0168b30b3ac53c0388982e52: Replies were missing `feedContext` because the parent item (which was unshifted) didn't have it. For our purposes, the entire convo has the same context. The fix is mostly copypaste from how we handle `source`. There's probably a simpler way to write this but I don't understand the data structure for sure — and this will definitely work.
Read the code for the first change. For the second change, added
```diff
--- a/src/state/queries/post-feed.ts
+++ b/src/state/queries/post-feed.ts
@@ -294,6 +294,14 @@ export function …
```

FeedFeedback fixes

---

src/lib/api/api-polyfill.ts
src/lib/media/manip.ts
src/lib/media/manip.web.ts
src/view/screens/Settings/ExportCarDialog.tsx

This change allows to download the CAR file in mobile apps.

✅ Fix "Download CAR file" on mobile

---

__tests__/lib/string.test.ts
src/lib/strings/time.ts

Because we are assuming months have 28 days, we're starting to see some cases like this:
Obviously, we know that a year cannot have 13 months in it, but we're starting to encounter cases like this because...well it was just Bluesky's "mainstream" birthday!
So, what do we want to do instead?
- Keep the same logic as before for anything under 30 days
- 29 days should be `29d`
- 30 days should be `1mo`
- Anything like 1 month and 15 days, 1 month and 20 days, etc. should display `1mo` in most cases.
- As we approach 28, 29, or 30 days, we can show the next month, i.e. 1 month and 19 days should show `2mo`
- As we reach the end of the year, we should not show `12mo` but instead begin showing the full date. I.e. 11 months and 29 days should show `4/20/24`
- As before, anything over a year old …

get a little more accurate with month length

---

src/lib/notifications/notifications.ts
src/lib/statsig/events.ts
src/lib/statsig/gates.ts
src/screens/Onboarding/StepInterests/index.tsx
src/screens/Onboarding/StepProfile/index.tsx
src/view/screens/Home.tsx
src/view/shell/index.tsx

Asking for permissions randomly at the start of onboarding can be pretty jarring and might result in more denials of permission. Instead, we can ask for permission after onboarding is complete.
We also want to be able to track this, so I have:
1. Added a feature gate on whether to show this at the start of onboarding or afterward
- Display it on the interests screen of onboarding if the reduced onboarding gate is false
- Display it on the profile screen of onboarding if the reduced onboarding gate is true
2. Added a new log type - `notifications:request`
- Accepts a `status` with values `granted`, `denied`, or `undetermined` - the default values for Expo Notifications
On top of these changes, I am fixing/cleaning up some other logic. On main right now, we can see that we are registering …

Move request for notifications permissions to `HomeReadyScreen`

---

src/lib/notifications/notifications.ts

Follow up to https://github.com/bluesky-social/social-app/pull/3977
While testing on a physical device, it became apparent that `currentPermissions` does _not_ cause a re-render when used in this way
```tsx
const [currentPermissions] = Notifications.usePermissions()
React.useEffect(() => {
console.log('change')
}, [currentPermissions])
```
As a result, we don't end up registering a push token immediately when relying on `currentPermissions` to result in `getDevicePushTokenAsync()` being called.
We already know that calling `getDevicePushTokenAsync()` fires a `PushTokenEvent`. Therefore, what we want to do is call the `getDevicePushTokenAsync()` as soon as we receive the request response, instead of relying on the `useEffect` to re-run.
We should see `Sent push token (init)` logged as soon …

actually register token on permissions change

---

src/lib/statsig/events.ts
src/screens/Onboarding/StepFinished.tsx
src/screens/Onboarding/StepProfile/index.tsx
src/screens/Onboarding/state.ts

Initially made this work with the image, but realized when adding metrics that it didn't work for created avatars. This PR ensures that whatever your last choice was, it retains that state when navigating forward and backward through onboarding.
Lint error fixed in #3999, will merge that into this before merging into main.

[Reduced Onboarding] Fix forward/backward nav with profile step

---

src/view/com/feeds/FeedSourceCard.tsx

Small tweaks to #3998 
No real changes to desktop, so just mobile screenshots.
This PR adjusts `FeedSourceCard` to truncate the display name and `Feed by` text to 1 line. This would affect rendering in other locations in the app.
However, `displayName` for a feed gen is limited to 24 graphemes, so this is really only an issue on small screens.
For the `Feed by` text, this could be much longer, but as you can see with a long handle, the wrapping is pretty bad. When clicking into a feed detail screen, this text is shown in full.

Tweak feed card styles

---

src/lib/notifications/notifications.ts
src/lib/statsig/events.ts
src/screens/Login/LoginForm.tsx

Add another log context for notifications request, for 'Login'. Don't want this to conflict with events for `StartOnboarding` or `AfterOnboarding`

add a `Login` notifications request

---

src/components/dms/MessageMenu.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/state/messages/convo/index.tsx
src/state/messages/convo/types.ts
src/state/messages/convo/util.ts

One of the goals of the `Convo` agent is to help prevent invalid states and invalid prop access. This PR adds a couple utils to help with this:
- `isConvoActive` — checks if the `Convo` is in an active `status`
- `useConvoActive` — provides assurance that `isConvoActive(convo)` is true
This helps when creating UI, so that we don't always need to check `Convo.status`, and with load states for the same reason.
See below where the convo no longer re-initializes when backgrounded.
https://github.com/bluesky-social/social-app/assets/4732330/93fce095-c9ae-41f5-b9f2-1ba40531064c

[🐴] Make status checks easier, fix load state

---

src/screens/Messages/Conversation/index.tsx
src/screens/Messages/List/ChatListItem.tsx

[🐴] show deleted account for `missing.invalid`

---

src/components/dms/ConvoMenu.tsx
src/screens/Messages/Conversation/index.tsx
src/state/cache/profile-shadow.ts
src/state/queries/messages/list-converations.ts
src/state/queries/profile.ts

Stacked on #4022
This PR adds the block/unblock queue used elsewhere in the app. To do so, I had to do a couple things.
First, I needed to add a profile shadow generator method. This pulls out the profiles from the `listConvos` response and allows them to be shadowed.
Second, I needed the source of data for the `Conversation/*` to be accessible by the shadow, which meant a call to `useProfileQuery`. So within the context of the `Conversation/*` screen, the `ConvoView` is fetched by RQ and also by the `Convo` agent. I don't have a good way around this for right now.

[🐴] Block states, writes

---

src/components/dms/ConvoMenu.tsx
src/screens/Messages/Conversation/index.tsx
src/screens/Messages/List/ChatListItem.tsx
src/screens/Messages/List/index.tsx
src/state/cache/profile-shadow.ts
src/state/queries/messages/list-converations.ts
src/state/queries/profile.ts

This PR hooks up `ChatListItem` and `Conversation/index` with a profile shadow and moderation UI in a read-only state. Here, you can test blocking a user directly, and via a list.
In either block case, avatars are blurred and display names are moderated if need be. The block/unblock actions in the `ConvoMenu` atm does nothing, unless it's a list, in which case it shows the following dialog:

[🐴] Block states, read only

---

src/state/messages/convo/agent.ts
src/state/messages/convo/const.ts

Reset and re-initialize the chat after 5 minutes of inactivity. Only (potentially) runs from a `Backgrounded` to a `Ready` transition. Other `-> Ready` transitions already reset where needed.

[🐴] Reset after 5 min

---

src/components/moderation/LabelsOnMeDialog.tsx
src/screens/Feeds/NoFollowingFeed.tsx
src/view/screens/ProfileList.tsx
src/view/screens/SavedFeeds.tsx

````diff
- Toast.show(_(msg`${pinned ? 'Pinned to' : 'Unpinned from'} your feeds`))
+ Toast.show(
+   pinned
+     ? _(msg`Pinned to your feeds`)
+     : _(msg`Unpinned from your feeds`),
+ )
````
Enables localization of these strings.
---
This part
Before:
````po
#: src/screens/Feeds/NoFollowingFeed.tsx:38
msgid "Looks like you're missing a following feed."
msgstr ""
#: src/screens/Feeds/NoFollowingFeed.tsx:46
msgid "Click here to add one."
msgstr ""
````
After:
````po
#: src/screens/Feeds/NoFollowingFeed.tsx:37
msgid "Looks like you're missing a following feed. <0>Click here to add one.</0>"
msgstr ""
````
Makes it easier to understand the context of a string. It's also better suited for localization in languages that don't use whitespace.

Make more localizable

---

src/components/dms/MessageItem.tsx
src/components/dms/MessageReportDialog.tsx
src/screens/Messages/Conversation/MessageListError.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo/agent.ts
src/state/messages/convo/types.ts

Instead of handling retries as a separate `ConvoItem`, I've added a prop to `pending-message` types so that we can style it within `MessageItem`.

[🐴] Better retry styling

---

src/state/messages/convo/agent.ts

`refreshConvo` is used when transitioning some states just to get a fresh `ConvoView` and any updates therein. In these cases, it's not currently useful to alert the user if this fails, since failures here don't require us to update the `status` of the `Convo`.
Network failures e.g. failure to send or firehose errors are more important, and actually recoverable e.g. we need to manually re-enter a `Ready` status.
This reduces noise for the user.

[🐴] Remove error for refresh, not necessary

---

patches/react-native-reanimated+3.6.0.patch
src/platform/detection.ts

Currently, we only get the `prefersReducedMotion` value on web. Luckily, Reanimated has a `useReducedMotion` hook, but we need the value not in a hook. This PR uses the (internal) `isReducedMotion` function from Reanimated since it does exactly the same thing on web, and gets the value as it is at app startup on native. Check the simple implementation here
https://github.com/software-mansion/react-native-reanimated/blob/44d55dd3b6b92759fa820538d4f7c420bc8c2fa0/src/reanimated2/PlatformChecker.ts#L49
Note that the implementation of `useReducedMotion` is ultra simple and we could just call it here as not to rely on internal functions, but I think it's probably unsafe to break the rule of hooks here in case they change the implementation. …

Implement prefersReducedMotion on native

---

package.json
src/screens/Messages/Conversation/MessageInput.tsx

- Adjust the hitslop
- Account for line height on iOS

[🐴] A few tweaks to message input on native

---

src/components/dms/NewMessagesPill.tsx
src/lib/custom-animations/ScaleAndFade.ts
src/screens/Messages/Conversation/MessagesList.tsx

Stacked on https://github.com/bluesky-social/social-app/pull/4027
Needs some styling work, but not sure how to make it look right now.
Go to about 2/3 of the way through the video to see effect when foregrounding.
https://github.com/bluesky-social/social-app/assets/153161762/e70500f1-281a-407a-89ac-47214b82c304

[🐴] Pill for additional unreads when coming from background

---

package.json
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
yarn.lock

The keyboard controller library we were using for this was a little glitchy and was causing some side effects on Android that would have affected the composer 😮‍💨
What I've done here is taken a look at using Reanimated's `useAnimatedKeyboard` to achieve the same effect.
`useAnimatedKeyboard` has a shared value containing the current height of the keyboard at any given point during the animation. We can use this value to do two things:
1. Move a "sticky input" - an input with relative positioning and with a bottom that's always the height of the keyboard
2. Adjust the size of a `ListFooterComponent`, which will provide the needed "offset" and will fire a content size changed event.
The result is something that's actually a little closer to 60FPS than what we have right now, seemingly on …

[🐴] Remove keyboard controller lib

---

src/lib/hooks/useNotificationHandler.ts
src/lib/notifications/notifications.ts
src/screens/Messages/List/ChatListItem.tsx
src/state/queries/messages/list-converations.ts

- Decrement the badge when opening a chat from the messages list
- Decrement the badge when opening a chat from a push notification
- Increment the badge every time you receive a notification for a chat
- EXCEPT for if it is the chat you are currently looking at

[🐴] Decrement app badge when opening unread chat

---

src/screens/Profile/Header/Shell.tsx

Fixes https://github.com/bluesky-social/social-app/issues/4054
I think this showed up as a result of this: https://github.com/bluesky-social/atproto/commit/0b6f6f8636e6b9212568bdb508f8e6f61102b3e7#diff-1003892846e81d97c6492ad916b5379e6dac4e3b25c923d0a5007ec3eac08260
I think we only want to display individual labels on accounts which are _not_ our own, since on our own profile we show the appeal dialog.
There's a labeler that has a applied labels to a lot of our accounts here: https://bsky.app/profile/yardcrow.com
Subscribe to that labeler and see if you have a label on your account. If you do, great. Test:
- On production, you should see both a list of labels _and_ the "placed on this account..." label
- On this branch, you should _only_ see the "placed on this account..." label
- On my …

don't show individual labels on own profile, only "have been placed..."

---

src/state/queries/messages/leave-conversation.ts

If the `leaveConvo` call failed, we weren't resetting the optimistic mutation that we run `onMutate`.

[🐴] Reset leave chat optimistic update if fails

---

src/components/dms/MessageMenu.tsx

There was some competing optimistic stuff here. Deleting a message would immediately hide (handled in `Convo`) but then we tried to open a retry prompt from the `MessageMenu`. To keep it simple, let's just show a toast that it failed. The deleted message will be re-inserted if it fails in `Convo`.

[🐴] Fix delete message error

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/index.tsx

[🐴] Reduce header size

---

src/screens/Messages/List/ChatListItem.tsx
src/state/queries/messages/list-converations.ts

[🐴] don't include blocked convos in unread count

---

src/view/com/modals/DeleteAccount.tsx

Deletes chat service account before deleting account. Throws if API call fails so that the main delete account call only happens if this one goes through
Backend not yet deployed so I have not tested it

[🐴] delete chat service account on account delete

---

src/lib/hooks/useNotificationHandler.ts

When we are already in the conversation screen, we can't just do a `.navigate` - it won't work! Instead, we should use `reset`.

[🐴] Reset screen when pressing a DM notification while already in the conversation screen

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx

Also made it in this one so that as the message input increases in height, the content scrolls up with it, looks a lot better.
https://github.com/bluesky-social/social-app/assets/153161762/d0409d97-eb94-4096-8750-91d83b628b14

[🐴] 🤞 This should be the final message list change - Use `dispatchCommand` so we don't need to know the content height

---

src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/List/ChatListItem.tsx
src/screens/Messages/List/index.tsx

Few minor tweaks
- Memo the chat list item
- Set the initialNumToRender min height to something a little smaller (default is 100px but chat items are about 80px)
- Use `scrollTo` with an arbitrary height to get around async scroll jank on Android

[🐴] Minor nits

---

src/screens/Messages/Conversation/index.tsx

was able to get to the screen via tapping a notification from the home screen which left the min shell mode active

[🐴] disable min shell on convo screen

---

src/components/dms/MessagesListHeader.tsx

I have a hunch this will help Reanimated's `useAnimatedKeyboard` to properly reset, but need to test on device. Cannot reproduce the original issue on simulator.

[🐴] Ensure keyboard gets dismissed when leaving screen

---

package.json
src/App.native.tsx
src/components/dms/ActionsWrapper.tsx
src/components/dms/MessagesListHeader.tsx
src/components/dms/NewMessagesPill.tsx
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx
src/view/com/composer/Composer.tsx
yarn.lock

This branch should not actually be called `bump-reanimated`, it didn't rename correctly. This does _not_ bump reanimated.
**[without whitespace](https://github.com/bluesky-social/social-app/pull/4106/files?w=1)**
After debugging some of the issues with `useAnimatedKeyboard`, I also figured out where some of the issues were at in the keyboard controller library that we _really_ want to be using. I've implemented that here, both for the messaging and for the composer.
I've tested on both iOS and Android pretty extensively on simulators, going to build some native clients now and see how those feel as well.

[🐴] Fully implement keyboard controller

---

src/components/dms/MessageProfileButton.tsx
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/state/queries/messages/get-convo-for-members.ts
src/view/com/profile/ProfileMenu.tsx

Calls `getProfileForMembers` to decide whether or not to show the button, since you can still chat someone if they have DMs closed if you already have an ongoing chat (I set mozzius.dev to `none` if you want to test). Means that it pops in after the rest of the profile but it doesn't cause layout shift. Buttons now wrap if needed, rather than flowing behind the avatar. Also includes a cleanup of the button sizes to make them all equal sizes (because before they were all different apparently????)
Opted not to show on labellers, you can still message them through the new chat dialog if you really need to but I think we want to avoid the perception of labellers as normal users.

[🐴] DM button on profile

---

modules/expo-bluesky-translate/index.ts
modules/expo-bluesky-translate/ios/ExpoBlueskyTranslateModule.swift
modules/expo-bluesky-translate/ios/ExpoBlueskyTranslateView.swift
modules/expo-bluesky-translate/ios/TranslateView.swift
modules/expo-bluesky-translate/src/ExpoBlueskyTranslate.types.ts
modules/expo-bluesky-translate/src/ExpoBlueskyTranslateView.ios.tsx
modules/expo-bluesky-translate/src/ExpoBlueskyTranslateView.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/shell/index.tsx

This is a little building on this amazing PR https://github.com/bluesky-social/social-app/pull/4098
I think however it might be more useful to make this a global API that can be called from anywhere, rather than a wrapper.
Currently, the wrapper presents the translation modal with a prop that needs to be set via state which is okay, however we probably would probably want to build on that.
The first thought I had was to just add a view function to the native view, like `presentAsync()`, that could be triggered with a press, maybe like so:
```tsx
const ref = React.useRef(null)
const onPress = React.useCallback(() => {
// Text is a prop
ref.presentAsync(text)
}, [text])
return (
<Pressable onPress={onPress}>
<NativeView ref={ref} />
</Pressable>
)
```
This also seems like a fine option - …

Make iOS native translation view available globally

---

src/screens/Messages/Conversation/index.tsx

Small, but noticed we never stopped the load state for users whose DM privileges have been revoked.
https://github.com/bluesky-social/social-app/assets/4732330/e9e9723e-7da8-4dd9-92cd-569a73438ab0

[🐴] Fix load state for disabled chats

---

src/screens/Messages/Conversation/MessageInput.tsx

Using the `useFocusedInputHandler` alongside Reanimate'd `measure`, `useAnimatedStyle`, and `useAnimatedProps` to make all layout changes synchronous. Should get rid of weird glitches.
We should do this in the composer too 👍

[🐴] Make message input layout resizing synchronous

---

src/view/com/feeds/FeedSourceCard.tsx

Two issues here:
- if the feed fails to load, the `find` for `SavedFeedConfig` fails and we don't have anything to remove from prefs
- the warning dialog when removing a saved feed isn't part of the failed/loading state
- fix here is to simply call `onUnsave`, don't need to warn the user if feed is failing to load and they want to remove

Allow removal of feeds that fail to load

---

src/locale/locales/fr/messages.po

Includes all the new strings for the future Chat feature (translated as `Discussions`, even though `chat` is also used in French for this purpose, but is more linked to "group chat" and "chatrooms" ; it also means _cat_ in French 🐈).
Pinging @surfdude29 and @pfrazee :)

Update French localization

---

src/components/dms/ConvoMenu.tsx
src/screens/Messages/List/ChatListItem.tsx

Review without whitespace: https://github.com/bluesky-social/social-app/pull/4114/files?diff=split&w=1
Deleted accounts delete all messages for both parties, so there's no need to load the Convo screen. This PR disables that link.
This PR also converts to a `Link` for better a11y, and restructures the `ChatListItem` so that the context menu is outside the `Link` for better a11y. It should also fix some alignment issues we had with deleted accounts.

[🐴] Handle deleted accounts, restructure ChatListItem

---

src/components/dms/NewChatDialog/index.tsx
src/components/moderation/LabelsOnMeDialog.tsx
src/screens/Messages/Conversation/ChatDisabled.tsx

mostly a straight copy of `LabelsOnMeDialog`, although I improved the onSubmit action by using `useMutation` and backported it to `LabelsOnMeDialog`

[🐴] Appeal form for disabled DMs

---

src/lib/statsig/gates.ts
src/lib/statsig/statsig.tsx
src/screens/Onboarding/StepFinished.tsx
src/screens/Onboarding/StepInterests/index.tsx
src/screens/Onboarding/StepProfile/index.tsx
src/screens/Onboarding/index.tsx
src/state/queries/post-feed.ts
src/view/com/testing/TestCtrls.e2e.tsx

First commit adds an option that disables exposure logging for a specific gate check. Then we rename the onboarding experiment name (to get fresh data) and enable the option for the place where we don't want exposures.
Add a logpoint to Statsig exposure logger.
Confirm that on `main`, we expose the user to the onboarding experiment while on Following tab.
Confirm that on this branch, we don't.

[Statsig] Fix exposure logging for reduced onboarding

---

src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx

Test with old version
- create fresh chat, leave one, or otherwise reset to no items in the MessageList
- send first message, see flash of load state
This PR fixes that, but probably breaks other stuff.

[🐴] Prevent flash upon first message

---

src/screens/Profile/Sections/Labels.tsx
src/view/com/util/List.tsx

Scrolling through some screens (such as the feed on the Home screen) in the Bluesky app is laggy on some mid- to low-end Android devices, with frame rates dropping below 30 FPS.
While not having a noticeable impact on iOS or high-end Android devices, this situation will start escalating to a severe level on mid- or low-end Android devices, giving the user a bad experience or even causing them to decide to switch to the web version instead to avoid the laggy scroll hurting their eyes.
Notably, this issue does not affect every scrollable List, such as the one on the Profile screen.
The small change in this PR improves performance by 200% on some Android devices 
(worst case <15 FPS → worst case >30 FPS).
See screen recording: https://youtu.be/ipZeTkb2mAk
In the `List` component …

Fix laggy scrolling on mobile app's home screen, etc.

---

src/view/screens/Settings/index.tsx

This is just a minor visual tweak to make the settings screen look better on iOS.
| --- | --- |
| <img width="240" src="https://github.com/bluesky-social/social-app/assets/3784687/b867483b-3672-41e5-98a4-97b9ffada4b0" /> | <img width="240" src="https://github.com/bluesky-social/social-app/assets/3784687/27a78df7-2f49-47df-aa44-a1081df2b1e7" /> |

Expand the background color to cover the overscroll area on settings screen on iOS

---

src/components/dms/MessagesNUX.tsx

If the initial request fails for some reason, the state resets to `undefined`, causing an infinite loop. We should store some state that tells us we already tried to initialize.

[🐴] only try to initialize once in the NUX

---

src/Navigation.tsx
src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx

Adds simple sampling mechanism. For now enabling just for the noisiest event.
Add some console logs. Verify that usually, the nav events get filtered out. Verify that forcing the probability to be lower results in sending nav events.

[Statsig] Sample router events

---

src/components/Lists.tsx
src/components/dms/MessagesNUX.tsx
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po
src/screens/Messages/List/index.tsx

We added an end message to the list footer, thought it felt a little too generic. Instead, let's keep them disabled by default and we can add them as we want.
I added one to the conversation list screen for now, which reads "No more conversations to show". Definitely can add this elsewhere - like the end of a post thread to signify that there's no more posts, but we can do that later.
Check a post thread, and there should not be a footer. However, if you go to the chats tab, there should be a footer that says "No more conversations to show".

Make list end text customizable

---

src/screens/Login/LoginForm.tsx

This fixes the (unlikely) scenario of a user being logged in with Account A, clicking "Add Account", and then trying to log in again with Account A.
The reducer is updating the account with fresh tokens, but since the `did` doesn't change, the app doesn't re-render. This fix waits for the login action to complete, then hides the logged out view.

Close loggedout view when logging in

---

src/components/ProfileHoverCard/index.web.tsx

Right now the hover cards do not work on Firefox Windows are not working, because - specifically on Windows and specifically with Firefox - `maxTouchPoints` is set to one, not zero.
The MDN docs also say that we should be using `> 1` instead of `> 0`
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints
Now that we are using `> 1`, this works correctly.
Before and after, on bsky.app vs localhost.
https://github.com/bluesky-social/social-app/assets/153161762/859bbced-bae4-4e31-890e-c8bdb5e965a3

check `maxTouchPoints` is greater than 1 - not 0 - for hover card

---

src/screens/Messages/List/ChatListItem.tsx

Before:
After:
I also moved the unread notification, this means we don't need platform-specific styles anymore

[🐴] Fix convo menu overlap (web)

---

src/screens/Messages/Conversation/MessageInput.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/4157
Because we are listening for the `onKeyDown` event to know when to submit the message with the enter key, Japanese users cannot properly use the Japanese IME because it relies on using the enter key.
This PR uses the `onCompositionStart` and `onCompositionEnd` events on the `textarea` to prevent submission while the user is composing.
I've recorded a video below of me using the Japanese keyboard IME with some console logs for clarification on what is going on.
https://github.com/bluesky-social/social-app/assets/153161762/5abfd67e-898b-4d25-8f23-6d0315b649bd

[🐴] Support Japanese (et al.) IME in message input on web

---

src/screens/Messages/Settings.tsx

Concern that this setting might be a bit ambiguous, esp. from a safety perspective (i.e. someone trying to "turn off dms" and then still getting messages) so added a little note.

[🐴] Add note to clarify "allow new messages from" setting

---

src/state/session/agent.ts

A few of us have noticed getting signed out occasionally. For me anyway, this seems to happen when resuming from a background state e.g. foregrounding the app, or opening my laptop after being away.
The thinking in this PR is: if we have checked your JWT and it's not expired, we want to be _very_ sure the `resumeSession` call returns a real failure, and not some sort of network issue while the device reconnects to its wifi/cellular.
Other things that could be done here:
- check for network errors and retry those, but fail on actual auth errors
- add a back-off, so requests are spaced out a bit

More retries when resuming non-stale account

---

src/lib/statsig/gates.ts
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/view/com/feeds/FeedPage.tsx
src/view/screens/Home.tsx

Launching:
- `disable_min_shell_on_foregrounding_v3` (positive results)
Unlaunching:
- `autoexpand_suggestions_on_profile_follow_v2` (negative results)
- `disable_poll_on_discover_v2` (neutral)
Removing unused:
- `start_session_with_following_v2`
- `test_gate_1`
- `test_gate_2`
Read the code.

Cleanup gates

---

.eslintrc.js
.prettierignore
babel.config.js
lib/react-compiler-runtime/index.js
lib/react-compiler-runtime/package.json
package.json
yarn.lock

In my ReactConf [talk](https://www.youtube.com/watch?v=T8TZQ6k4SLE&t=12020s) I demo'd adding React Compiler to bluesky, so I wanted to add it for real! 
Adding the compiler and eslint plugin was pretty straightforward. The only hiccup I ran into was an interesting interaction with @lingui/macro:
lingui recommends running their `macro` plugin [first in the pipeline](https://lingui.dev/ref/macro). Normally with the React Compiler, the compiler plugin should run first as we want to see the original code as it was written. However, this sometimes causes conflicts with other babel plugins.
In this case, it looks like the @lingui/macro plugin does some very light transformation that the compiler can still understand and compile correctly, so I made it run first.
Without letting @lingui/macro …

Add React Compiler

---

.eslintrc.js

This task gets stuck on CI and when I run `yarn lint` locally. Let's skip it for now and @poteto will have a look later.

[Temporary] Disable React Compiler lint rules

---

src/App.web.tsx

`react-native-keyboard-controller` logs a warning - on every keystroke - if the app isn't wrapped in a `KeyboardProvider`. This makes sense of course on native, where it's a useful indication that something is wrong, but annoying when debugging on web.
This wraps the app in the keyboard provider on web as well to silence these warnings.
The context (https://github.com/kirillzyusko/react-native-keyboard-controller/blob/6da7f58bd692e0eeac26e44fd4960c1f4a31f3c0/src/context.ts#L20) contains just a few shared values and a couple functions. Hooks are no-op on web. https://github.com/kirillzyusko/react-native-keyboard-controller/blob/6da7f58bd692e0eeac26e44fd4960c1f4a31f3c0/src/reanimated.ts

wrap web in disabled keyboard provider

---

src/state/session/__tests__/session-test.ts
src/state/session/index.tsx
src/state/session/reducer.ts

In #4181, I added some logic for the case when a stale agent refreshes the token. We'd like to persist the new refresh token if that happens. However, that by itself is more like a failsafe — ideally stale agents wouldn't even _be able_ to consume existing refresh tokens. Since otherwise two agents may keep fighting for tokens and invalidating each other.
So this stacks a second commit which disposes of stale agents by clearing out their session (and the persistence handler for good measure). This means that the failsafe I added in #4181 actually become a no-op (i.e. this should never happen). Still, both fixes make sense to me in isolation so I think I'd like to get both of them in.
Careful inspection of the logic. One thing we can do for testing is to force the old agent to keep doing …

[Session] Dispose of stale agents immediately

---

src/screens/Messages/Conversation/MessagesList.tsx

It is fairly difficult on iOS for us to calculate our real safe area because our bottom is clamping the padding based on the device's inset. For example, on an iPhone 8 or lower, the padding gets set to `15` - because the real bottom inset is `0`. However, on other devices it becomes `30` because the inset _is_ set (an iPhone X or higher has a bottom inset of `34`).
this results in some bad behavior with the message input in the chat screen. We need to account for this _missing_ padding in these circumstances.
On most devices this offset is very small, even on Android devices. Newer iPhone devices have the tallest offsets, so for thos devices we want to set the max to 76. The minimum - when the offset is zero - should be 60.
With the adjusted offset for these circumstances, all devices …

Handle zero bottom inset on iOS

---

bskyembed/.eslintrc
bskyembed/src/components/embed.tsx
bskyembed/src/components/link.tsx
bskyembed/src/components/post.tsx
bskyembed/src/screens/landing.tsx
bskyembed/src/screens/post.tsx

The `ref_src` and `ref_url` params were being added to the embed cards within the embed, which is undesirable. This adds a `disableTracking` prop to the link component to try and avoid that

[Embeds] stop adding tracking params to non-bsky.app links

---

src/state/messages/events/index.tsx

This provider is mounted in `App.*.tsx` and unmounts when the account changes. When unmounting, we need to call `suspend()` to deactivate the active event bus.

[🐴] Suspend event bus when switching accounts

---

src/state/messages/events/agent.ts
src/state/messages/events/const.ts

Built this with this use case in mind, but never returned to reduce polling when the app is backgrounded. This is mostly for web, which does actually continue to poll in the background. iOS and Android both pause and resume when foregrounded.

[🐴] Reduce polling when app is backgrounded

---

src/components/Dialog/index.tsx
src/components/KeyboardPadding.android.tsx
src/components/KeyboardPadding.tsx
src/components/ReportDialog/SubmitView.tsx
src/components/dialogs/MutedWords.tsx
src/components/moderation/LabelsOnMeDialog.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/modals/Modal.tsx

Because of the needed changes on Android for the keyboard to behave correctly for DMs (as well as, eventually, the composer), it seems to have affected some users ability to properly scroll down to the button for saving alt-text. This is also apparent on the report dialog. Although it doesn't _break_ functionality (the text can still be input) it isn't possible to see the input, since the container does not get resized correctly.
While it would be possible to use a `KeyboardAvoidingView` inside of the new dialogs fairly easily, this becomes complicated with dialogs that are presented inside of the composer itself. That is because our composer is actually a dialog in the _old_ system, and then we are presenting another _new_  dialog inside of that one. This results in a …

Add padding to dialogs when keyboard is open on Android

---

src/screens/Messages/Settings.tsx
src/view/icons/index.tsx
src/view/screens/Settings/index.tsx

Fixes https://github.com/bluesky-social/social-app/issues/4195
Added under basic

[🐴] add link to chat settings from main settings

---

src/view/com/modals/AltImage.tsx

On Android, focusing this input automatically causes problems with resizing the container correctly. Even prior to the latest release - where something else broke - this still happens occasionally. It isn't consistent, it works 80% of the time but the other 20% it breaks.
For now, let's disable the autofocus on Android until we get a better chance to rework these dialogs.

disable alt text auto focus on Android

---

src/state/session/agent.ts

I want to better understand what failures occur here. We can pull status codes from our backend logs too, but network connectivity issues and local timeouts need to be captured here.

Log error statuses from failed resume session calls

---

src/state/queries/post-feed.ts
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/screens/DebugMod.tsx

Currently, we make a ton of calls to `getProfile()` to display the "Reply to" label. However, since https://github.com/bluesky-social/atproto/pull/2461, we can now get this info from the `grandparentAuthor` field in the API response.
Verify that the requests are no longer present when loading your timeline. Also verify that posts properly display the `Reply to` label when they should.
Check situations where:
- It appears normally: i.e. a post with one parent above. It should show the parent's parent's author.
- We remove the parent from the timeline. It should show the parent's author.
- Where we put a thread together, i.e. below

Remove `getProfile` calls when loading feed

---

src/screens/Messages/Conversation/MessageInput.web.tsx

Buttons on Safari, Firefox, and Chrome - respectively.

[🐴] Fix Firefox send button positioning

---

src/components/dms/NewChatDialog/index.tsx

Ok last thing I had on my list to get in was related to the new chat dialog. Users are confused that they can’t message the users in the list.
The easiest way to help that right now is to overfetch follows and apply the same sorting, so that presumably a greater # of users can be messaged.
Right now we’re fetching 12, which for me rn returns only 6 I can follow. If I increase that to the default of 50, I get ~15, which is more than enough to fill the window.

[🐴] Overfetch follow for default new dialog state

---

package.json
src/state/queries/app-passwords.ts
src/view/com/modals/AddAppPasswords.tsx
src/view/screens/AppPasswords.tsx
yarn.lock

Privileged app passwords

---

src/components/ProfileHoverCard/index.web.tsx
src/lib/browser.native.ts
src/lib/browser.ts
src/screens/Messages/Conversation/MessageInput.web.tsx

We want to keep parity on mobile web with the native app, so we should not submit messages when the return key gets pressed.
It would be nice if we could do the same for tablets, but this is complicated by the fact that these devices might have an external keyboard attached (the Surface or even an iPad Pro) and would still be a "touch device". Let's just require shift key for new lines on tablet or higher.
I've moved `isTouchDevice` into `browser.ts` to make this more accessible to other areas of the app (we are using it in multiple places).

[🐴] Don't submit the message on return press when on a phone (web input)

---

src/state/messages/convo/agent.ts

Error handling for message send failures was incomplete. This PR adds handling for all our known errors, and ensures that `pendingMessageFailure` is set for all failures.

[🐴] Make sure failed messages enter error state

---

src/state/messages/events/agent.ts

We've had some reports of chats failing to update. One possible culprit I've thought of so far is what this PR addresses: if the event bus/firehose is in an error state, starting a new chat will not restart the polling.
So if the user:
- opens app
- event log fails for any reason
- they nav to a chat or start a new one
- send a message
- we never poll for messages, and so never get a response back from their recipient
It's not clear why the event log is failing yet, but we have had issues with session agents that could cause failures like this, and fixes have been merged already.
What this PR does is handle a dispatched `UpdatePoll` event when the firehose is in an error state, and uses that to basically restart from 0 and attempt a recovery. If it fails again after this, the Convo screen …

[🐴] Recover from initial failed firehose state

---

src/view/com/notifications/Feed.tsx

The notifications tab is one of the last places I consistently hit the end of now, especially on web. Ideally we want to prevent seeing the spinner at the bottom of the page as much as possible.
This page should be much more difficult to hit the end of now, as we should load in the new notifications well before hitting the end.
https://github.com/bluesky-social/social-app/assets/153161762/eb7a6483-bc75-483d-9765-a1b2558bc630

set `onEndReachedThreshold` to `2` for notifications

---

app.config.js

Some upcoming features are going to require a minimum target of iOS 14 or higher. While we can technically still keep targeting 13.4, this doesn't seem necessary. I've checked Statsig logs and we don't have any daily inits on any iOS 13 version.
Just `yarn prebuild` and `yarn ios`

bump iOS target to `14.0`

---

yarn.lock

CI is failing typecheck because it says that `hitSlop` on a `TextInput` cannot be `null`. However, this isn't the case. See: https://github.com/facebook/react-native/blob/a93a15aca3e380f2f8158465b1b315ac3fab8307/packages/react-native/Libraries/Components/View/ViewPropTypes.d.ts#L135
This is a problem with `react-native-gesture-detector`'s type for `hitSlop` and it's version of `TextInput`. We don't use this in our codebase at all - and don't have any need to either. Nor do we use the `BottomSheetTextInput`. We use our own UI kit's text input component.
I've asserted the type for now in the `react-native-bottom-sheet` library to silence this error, so need to update the `yarn.lock`.

Fix `hitSlop` type

---

src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/GifEmbed.tsx
src/view/com/util/post-embeds/index.tsx

- Slightly bumped up the text size of the alt text indicator
- Moved the GIF alt indicator to the right
- On Web, kept the GIF alt indicator large because it needs to be specifically clicked
- On Mobile, made it small but gave a larger hit slop
|Before|After|
|-|-|
|![CleanShot 2024-05-28 at 20 23 12@2x](https://github.com/bluesky-social/social-app/assets/1270099/528388c2-fed2-40be-8a24-451edc873ded)|![CleanShot 2024-05-28 at 20 22 23@2x](https://github.com/bluesky-social/social-app/assets/1270099/a01fe0c1-8319-4716-81bf-d83acf142326)|
|Before|After (Web)|After (Mobile)|
|-|-|-|
|![CleanShot 2024-05-28 at 19 57 50@2x](https://github.com/bluesky-social/social-app/assets/1270099/b902820c-d2aa-4ff0-8dd7-b0f1e03698d2)|![CleanShot 2024-05-28 at 19 59 …

Alt text followups -- SLIGHTLY larger, and update gifs

---

src/App.native.tsx

In current version (1.83.0.190), splash screen on Android has unwanted white (not translucent) status bar. In previous version, status bar had the same color as background (blue on light mode or dark blue on dark mode).
This is due to `KeyboardProvider` of the Keyboard Controller library. By default Keyboard Controller adds the padding of status bar. To override this behavior, we can add `statusBarTranslucent` prop and set to true. See [the document of Keyboard Controller](https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/keyboard-provider#statusbartranslucent-) for more information.
Note: I do not check all side effects of this modification about the Keyboard Controller library. Before merging, check the behavior of existing implimentation using Keyboard Controller …

Add statusBarTranslucent prop (= true) to KeyboardProvider in App.native.tsx

---

.github/workflows/build-submit-android.yml
.github/workflows/build-submit-ios.yml
.github/workflows/bundle-deploy-eas-update.yml

We added some code recently to a native module that requires iOS 17.4.1. To build for that iOS version, we need XCode 15.3 or greater.
See https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md#installed-sdks. We are already using `macos-14`, so `15.3` should be available and will give us access to the 17.4 SDK.
Merge, see if the action runs.

use xcode 15.3

---

src/lib/app-info.web.ts
src/lib/media/manip.web.ts
src/view/com/util/images/Image.web.tsx

There were a couple of places where some exports were added to some files but not to their `.web.ts` version. Doesn't have any behaviour changes, but reduces some of the log spam in the console when running web

Fix mismatched exports for platform-specific files

---

app.config.js
plugins/withAndroidManifestLaunchModePlugin.js
src/App.native.tsx

Expo sets the `launchMode` property of  `.MainActivity` to `singleTask` in `AndroidManifest.xml` by default. This causes any activity above it in the app's stack to be destroyed any time the app is launched from the home screen. Since the app is a single activity, this normally isn't a problem since there aren't any activities above it in the stack. However, the in-app browser is a different activity, so reopening the app from the home screen when the browser had been open causes it to be closed and return the user to previous screen instead. The Android developer documentation cautions against using any mode other than `standard` or `singleTop`.
I've added a config plugin to alter the AndroidManifest to use `singleTop`. This seems to have resolved the issue.
Fixes #4212 
I have built the …

Change Android's MainActivity launchMode to singleTop

---

src/view/com/composer/Prompt.tsx

This is a follow up to https://github.com/bluesky-social/social-app/pull/4254. It became even more apparent to me how big the reply prompt is on native once the header was always there. This PR adjusts the height of this prompt.
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>
<table>
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>

Adjust size of reply prompt on native

---

src/lib/notifications/notifications.ts
src/lib/statsig/gates.ts
src/screens/Onboarding/StepFinished.tsx
src/view/screens/Home.tsx

There was a significantly higher number of people hitting the `request_notifications_permission_after_onboarding` gate that were not actually new signups. It looks like this may have been tied to `canAskAgain` being `true` on some devices. Let's remove that check completely, and just skip the check if `permissions.status` is `granted` or `denied`.
We can probably do some minimal testing by flipping the gate back and forth and creating new accounts to check the Statsig logs, but I'm not certain how we can verify whether the `canAskAgain` was indeed the problem here. Might be something we just need to wait and see results for.

adjust notifications experiment by removing `canAskAgain`

---

src/screens/Messages/Conversation/MessagesList.tsx
src/view/com/util/List.tsx
src/view/com/util/List.web.tsx

We recently discovered that there was some problems with the `content-visibility` style in the `ListImpl` for chat on Firefox. We originally just removed this style all together on Firefox, however that came with what seems like some performance hits. It seems like a better idea to scope this down to specific cases where it causes problems instead.
I've added a prop to `ListProps` called `disableContentVisibility`, which will simply not add the style when set to `true`.
We could scope this down further to just set this prop to `true` if the browser is Firefox, though this might not always work in cases such as:
- Spoofed user agent
- Some older Chrome version that might not have good support for this style (?)
Using the `MessagesList`, you can comment out the `disableContentVisibility` …

add prop to ListImpl for disabling `content-visibility` style

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post-thread/PostThreadShowHiddenReplies.tsx

Whenever we introduced PRs for fixing layout jank in the post thread `List`, we inadvertently broke the header always being visible. Lots users - especially on iOS - miss not having the back button easily available.
This is just a rudimentary PR that adds back that header. It doesn't animate the header in/out like we do on some other screens. We may decide to do that, in which case we'll need a different approach.
I also did a bit of StyleSheet housekeeping while I was here by using ALFredo instead of the few uses of `palette`.
Open a thread, and make sure the header stays at the top while also not breaking things in larger threads. This is a great thread to test in: https://bsky.app/profile/www.mozzius.dev/post/3kjqhblh6qk2o
https://github.com/bluesky-social/social-app/assets/153161762/93 …

Always show the header on post threads on native

---

src/components/moderation/PostAlerts.tsx
src/components/moderation/ProfileHeaderAlerts.tsx
src/lib/moderation/useModerationCauseDescription.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx

In https://github.com/bluesky-social/social-app/pull/3677, we updated the label rendering to show the origin of labels. Unfortunately this has been extremely visually noisy, making the labels difficult to digest.
Some folks smartly suggested we just show the avatar, so that's what this PR does if it's from a 3p labeler. In other cases, it'll show the icon.
|.|.|
|-|-|
|![CleanShot 2024-05-29 at 08 01 22@2x](https://github.com/bluesky-social/social-app/assets/1270099/d4944405-e71c-4c70-8e30-f9f58ee9961f)|![CleanShot 2024-05-29 at 08 01 46@2x](https://github.com/bluesky-social/social-app/assets/1270099/69b3bec3-ccdd-4323-b446-e61e3cadb6d2)|
|.|.|
|-|-|
|![CleanShot 2024-05-29 at 08 02 40@2x](https://github.com/bluesky-social/social-app/assets/1270099/99db610c-8178-4742-9bf5-59542f53eca0)|![C …

Improve the visual clarity of labels on profiles and posts

---

src/components/moderation/PostHider.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx

While working on another PR, I noticed that we don't currently handle the "Hide" behavior correctly in thread replies.
The current interpretation is that "Hide" only filters replies out of feeds. This means that replies only get blurred by `blur=content`. Put another way, on "badge"-style labels, the hide preference has no effect.
|Blur=content|Effect|
|-|-|
|![CleanShot 2024-05-29 at 12 54 10@2x](https://github.com/bluesky-social/social-app/assets/1270099/20b79d6e-3cf2-47c9-ac2c-5a4e56673d2c)|![CleanShot 2024-05-29 at 12 54 22@2x](https://github.com/bluesky-social/social-app/assets/1270099/726bdf4e-5534-4781-afd1-a7f8d49bb41a)|
|Blur=none|Effect|
|-|-|
|![CleanShot 2024-05-29 at 12 52 45@2x](https://github.com/bluesky-social/social-app/assets/1270099/cc43094e-aae0-40ac-92c4-1af3babdea88)| …

Interpret 'hide' setting as ALWAYS hiding from thread replies

---

modules/expo-bluesky-translate/src/ExpoBlueskyTranslateView.ios.tsx

Seems like simulators just report 17.5, so this dumb mistake totally slipped past me. Whoops!

Fix native translations on iOS 17.5.1

---

src/view/com/post-thread/PostThread.tsx

In https://github.com/bluesky-social/social-app/pull/4254, we removed the `ViewHeader` from the items given to `FlatList` and instead placed it outside the `FlatList`. In doing so, we removed the first element of our array.
Now, whenever we open a post that has no parents but has a link card inside of it, we see that the list is maintaining the position of the root post - since that is the first item in the list that can be "latched onto".
https://github.com/bluesky-social/social-app/assets/153161762/8eb22c0d-3240-4cac-a644-24d15605395c
The solution is to set the `maintainVisibleContentPosition` prop to `undefined` whenever we know there are no parents that could cause a layout jump.
Visit this post and test opening the quoted post. There should be no layout jump. …

don't maintain position whenever there are no parents

---

src/alf/util/useColorModeTheme.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/shell/Composer.tsx

- Uses `formSheet` presentation iOS, which speeds up the animation and allows swipe-to-dismiss
- I figured out a way to keep the black backdrop without needing to impact the rest of the app
- Cleans up a bunch of the janky spacing in the composer top bar (turns out we were adding 15px padding and then -14px margin? lol)
- Make composer generally a little more compact, thanks to #4275 making the whitespace less necessary
https://github.com/bluesky-social/social-app/assets/10959775/3bd6fd6e-4697-49ce-8310-62dfb9c5ac96

Composer - Use sheet presentation on iOS

---

src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx

New repost dialog introduces a bit of a delay before the action takes place, due to needing to close the dialog first. This meant there was a bit of a pause before the haptic plays. This moves the haptic call to before the dialog starts closing.
Also removed some unnecessary legacy dialog stuff

Play haptics before closing repost dialog

---

src/view/com/util/Views.jsx
src/view/com/util/Views.web.tsx

The ref wasn't being forwarded through these wrappers. (We had a React warning fire about this btw.) The wrappers are unnecessary so I collapsed them but I added a note.
https://github.com/bluesky-social/social-app/assets/810438/b1a2772c-4a1b-4544-be84-9d1a556a96db

Fix scrolling for labeler profiles

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

This moves more events to be sampled:
- `state:foreground` -> `state:foreground:sampled`
- `state:background` -> `state:background:sampled`
- `feed:refresh` -> `feed:refresh:sampled`
- `feed:endReached` -> `feed:endReached:sampled`
- `home:feedDisplayed` -> `home:feedDisplayed:sampled`
As a reminder, sampling is done on a per-session basis and determined by a fair dice roll (9 out of 10 sessions are sampled).
I'll adjust the metrics in the dashboard to account for this.

[Statsig] Sample noisy events

---

src/lib/statsig/statsig.tsx

The logic that is logging errors in dev mode for a missing entry in `DOWNSAMPLED_EVENTS` gets logged any time that `isDownsampledSession` is true - which is most often since there's a 90% chance of downsampling, since there is no `.has` check before the log, just a check for `endsWith`.
I've fixed that, as well as moved this log above the `isDownsampledSession` check, so we are sure to get an error rather than possibly missing it if we get the 10% chance of a downsampled session.
Open the app, see that there is no longer an error displayed when viewing the home tab. You can invert the check on line 108 to see that the logs do still show up in dev mode.

Don't log downsample warning when unnecessary

---

__tests__/lib/string.test.ts

Skip test to unbreak main.
I tried fixing it properly but couldn't figure out how/why. This is a bit worrying. However it's still failing if I go back in time on `main` so this either points to the test already being flawed in some way, or at the implementation already having an issue. It's definitely worth another look but I need to get the CI fixed.

Disable non-deterministic flaky test

---

src/components/Dialog/index.tsx
src/components/FullWindowOverlay.ios.tsx
src/components/FullWindowOverlay.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/composer/threadgate/ThreadgateBtn.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Threadgate.tsx
src/view/com/util/BottomSheetCustomBackdrop.tsx
src/view/com/util/forms/DropdownButton.tsx
src/view/shell/Composer.tsx

- Fix modals
- iOS: wrap modals in `<FullScreenOverlay>` from React Native Screens
- Android: wrap modal content in `<GestureHandlerRootView>` and put providers inside modal
- Animate the language dropdown
- Fix content appearing behind composer bottom bar (adjust keyboard offset + add background)
- Line up content of bottom bar visually (gallery *icon* is now 16px from the edge, rather than the whole button)
- Reduce size of threadgate button and line it up visually as well
- Make top border go across the whole screen now that it only appears on scroll
- Move errors/alt text reminder inside of the header above border
- Make border colours consistent now that the whole app is hairlineWidth
1. Make sure all the modals work as expected on all platforms. Composer ones especially, but double …

Composer - fix modals, and other tweaks

---

src/lib/api/index.ts
src/lib/strings/rich-text-manip.ts
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo/agent.ts
src/view/com/modals/CreateOrEditList.tsx

Extracts bsky.app links from messages and converts them to embeds before sending

[🐴] send record via link in text (Record DMs - base PR)

---

src/components/dms/MessageItem.tsx
src/components/dms/MessageItemEmbed.tsx
src/components/dms/MessageMenu.tsx
src/components/moderation/ContentHider.tsx
src/lib/api/index.ts
src/lib/strings/rich-text-manip.ts
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo/agent.ts
src/view/com/modals/CreateOrEditList.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx

The post is not hydrated by the server, so we have to fetch it clientside. Hopefully we can remove this in the future.

[🐴] Record message

---

src/components/dms/MessageItemEmbed.tsx
src/screens/Messages/Conversation/MessagesList.tsx

This PR removes the handling that stripped the post links from the message text, since old clients can't display embeds. We'll continue to improve this over time, but this allows us to move forward with post embeds.
New client, old client

[🐴] Embed backwards compat

---

src/lib/statsig/events.ts
src/screens/Deactivated.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx

Adds a new screen that replaces all other app screens if the user's account `status === 'deactivated'`. Atm, this value defaults to `active`, which is the server default. So this PR can also be safely merged prior to backend being ready.

[🙅] Add new deactivated screen

---

src/lib/statsig/events.ts
src/screens/Deactivated.tsx
src/state/persisted/schema.ts
src/state/session/__tests__/session-test.ts
src/state/session/agent.ts
src/view/shell/createNativeStackNavigatorWithAuth.tsx

The new `status` prop will [soon be coming down](https://github.com/bluesky-social/atproto/pull/2531/commits/72320720d3553f1d9c6ab5407c45752a3c7a2349) on `agent.session`. This PR gets ready for it, and uses the default value of `active` as a fallback for now.
Because this adds the fallback to the default value, it's safe to merge ahead of backend if we need to.

[🙅] Add status to session state

---

src/view/com/notifications/FeedItem.tsx
src/view/com/util/Link.tsx
src/view/com/util/UserAvatar.tsx

The notifications accessibility was fairly convoluted (not that other places are much better yet either). This introduces a serious improvement that we can actually start implementing elsewhere, such as `FeedItem`.
- An optional prop on `PreviewableUserAvatar` that disables VoiceOver for this element
- The ability to pass `accessibilityActions` and `onAccessibilityAction` to `Link` without completely removing the default `activate` action.
In this PR, we're making the expansion of the list of users an accessibility action so that it doesn't interfere with other interactions on the notification. See the video below for an example.
https://github.com/bluesky-social/social-app/assets/153161762/75af572b-4c9c-4ca6-a5dc-71c3497b4c01

fix accessibility label in notifications

---

src/screens/Settings/components/DeactivateAccountDialog.tsx
src/view/com/modals/DeleteAccount.tsx
src/view/screens/Settings/index.tsx

Adds the dialog as its own button on the Settings screen, and accessible from within the delete account dialog.

[🙅] Add deactivate account dialog

---

src/view/com/notifications/FeedItem.tsx
src/view/com/post/Post.tsx

Missed one of these top borders when we moved to hairline widths. Likes, feegens, and reposts already hid the border, but we didn't add it to `Post`, which handles mentions, replies, and quotes.
Check the notifications tab with a mention, reply, or quote as your top-most notification. There should no longer be a top border.
https://github.com/bluesky-social/social-app/assets/153161762/c5b112e9-3368-4fb6-ae93-584cdbed5960

hide top border for mentions and replies in notifications tab

---

src/components/dms/MessageItemEmbed.tsx

Using `flexBasis: 0` on web is causing messages to lose their positioning:

don't use flexBasis on web for message post embeds

---

src/view/screens/Settings/index.tsx

This has been bothering me for a bit, since I have a testing alt account that has a long name. Every time I open the settings page I get layout shift once the display name is shown:
https://github.com/bluesky-social/social-app/assets/153161762/cddf5798-1506-4426-8d7b-55140ab70779
Just adding a `numberOfLines={1}` to the `Text` here. No need to add `flex: 1` since the container already has it applied.
Verify layout doesn't break on web or native.

truncate if display name extends one line in the settings account switcher

---

src/view/com/posts/FeedItem.tsx

We changed the icon elsewhere, but missed the reposted by label.

use the new icon in reposted by

---

src/state/queries/notifications/util.ts

On the “Notifications” page,  there was a problem in handling uris filtering to get the details of posts, so I fixed it.
Repost and Like operations can also be performed on Records other than `app.bsky.feed.post` (e.g. `app.bsky.actor.profile/self`).  When someone performs a like or repost operation on those my Records, it seems to be included in my `listNotifications` response. (I don't know if this behavior of the current appview is correct.)
Anyway, the results of the `listNotifications` are grouped and the `subjectUri` is collected in `fetchSubjects` and passed to `app.bsky.feed.getPosts`, but only those containing `feed.generator` were excluded from `uris`. 
However, if `app.bsky.actor.profile`, such as the one described above, is included, `getPosts` returns an error, and the …

Fix filtering uris of fetchSubjects for notifications list

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/MyLists.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/com/util/EmptyState.tsx
src/view/screens/Lists.tsx

Spotted that profile tabs and lists screen placeholders appearance varies. 
Also wanted to address an additional border on mobile platforms when refreshing an empty feed.
Reuse `EmptyState` component inside profile tabs feeds and lists screen as a placeholder content. Go through all places which used the component before, to make sure that result after changes matches the appearance on PROD. Preform minor spacing tweaks.
I have also spotted that `EmptyState` relies on FA icons, with one custom icon introduced. I was wondering if similar exception should be done for "Feeds" and "Lists" placeholder icons to match them with one used in the drawer, but for the sake of changeset simplicity I have left it as-is. Happy to made an update or follow up PR, if you think it would a better for the …

Unify profile tabs and lists screens placeholders

---

src/view/com/modals/UserAddRemoveLists.tsx

While reviewing https://github.com/bluesky-social/social-app/pull/4315, I noticed a couple of existing nits to clean up:
- Still using some `borderTopWidth: 1` instead of `hairline` in the add/remove users to list screen
- Title was hitting the side of the screen and could take up multiple lines
- Border above the `Done` button was also using `1` instead of `hairline`.
See Below

fix top border width for user list updates

---

.github/workflows/build-submit-android.yml
eas.json
package.json

https://github.com/bluesky-social/social-app/issues/898
Fixes https://github.com/bluesky-social/social-app/issues/2222
There are a lot of users who either cannot or prefer not to use the Google Play store for downloading apps. It appears that Obtanium allows users to keep their apps up-to-date based on GitHub releases, as long as we provide an APK for them to use inside of that release.
We can create another step in the workflow that produces an APK rather than an AAB but with all the production environment variables:
- Still includes Firebase credentials for notifications
- Uses the `production` channel for OTA updates
- Uses the AAB's bundle version
This can be ran _after_ the production AAB build completes and notifies Slack, since we don't want to slow down the process of getting the …

add an apk to production build outputs for Obtanium release support

---

src/view/com/composer/Composer.tsx

- Floored values
- Changed `>=` to `>`
- Added 5px of leeway before showing the border
- Adjusted `keyboardVerticalOffset` to 162
> We should figure out *why* `keyboardVerticalOffset` needs to be 162

Composer - make bottom border more consistent when typing

---

src/components/dms/MessageItemEmbed.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Since we were using the `PostEmbeds` component, we lost the ability to see quoted content of quote posts. This adds a prop which stops the component from showing nested quotes
Also removes unused text style prop

[🐴] allow nested quotes in DMs

---

src/view/com/util/Views.web.tsx

Fixes this:
No real behavior change because we're not using it anywhere.

Fix forwarded ref

---

src/view/screens/Search/Search.tsx

As a small follow-up to #4169 this marks the `accessibilityLabel` and `accessibilityHint` for translation.

Mark `accessibilityLabel` and `accessibilityHint` for translation

---

src/components/dms/dialogs/SearchablePeopleList.tsx
src/components/dms/dialogs/ShareViaChatDialog.tsx
src/state/queries/messages/list-converations.tsx

Conditionally prepends recent convo user to beginning of Share Via DM dialog list, instead of just follows. Follows fill in remaining slots, and no change to search functionality. New Chat dialog is unchanged.
This uses the existing list convos query, which should be cached by the time this loads. So even though it loads the last 50 convos, we should be ok to put them all in there.

[🐴] Use recent convos for share via dialog

---

src/state/session/__tests__/session-test.ts
src/state/session/agent.ts

This fallback is no longer valid, and will result in validation errors after a WIP PR is merged. Might as well get this in so the value is corrected for anyone touching the `main` deployment.

[🙅] Remove fallback that's no longer valid

---

src/screens/Profile/Header/Shell.tsx

Fixes the loading sequence to avoid shifting layout.
After this change, labels are only displayed when the stuff above them is also ready.
[Review sans whitespace](https://github.com/bluesky-social/social-app/pull/4357/files?w=1)
https://github.com/bluesky-social/social-app/assets/810438/807fde7c-89a4-4ee5-a8f7-d0a0a1d88c70
https://github.com/bluesky-social/social-app/assets/810438/a4e116af-c18b-45d3-b647-4f4b89c89001

Don't show profile labels until loaded

---

src/state/persisted/store.ts

Just noticed this, and I think this has been overlooked since the beginning, but if this parse fails we silently return `undefined`. No reason we can't report some info around what failed validation.
Here I'm purposefully only including fields that will not include PII. This should give us a better idea of what's wrong, if something ever fails validation

Report persisted schema validation failures

---

src/view/com/util/post-embeds/QuoteEmbed.tsx

There's been some confusion with the current "blurring" control for quote posts, where it looks like the quoting post is the one labeled. This update fixes that issue by showing the border around the blur control.
(The example below is not actually labeled)
|Before|After|
|-|-|
|![CleanShot 2024-06-04 at 16 59 06@2x](https://github.com/bluesky-social/social-app/assets/1270099/008157ce-38c9-4991-8678-49da2cb5ee43)![CleanShot 2024-06-04 at 16 59 19@2x](https://github.com/bluesky-social/social-app/assets/1270099/b16caa2c-42f4-44e3-8c3a-4d3a40299fec)|![CleanShot 2024-06-04 at 16 56 53@2x](https://github.com/bluesky-social/social-app/assets/1270099/52540c79-5333-43ed-bbac-e75dfe7c7644)![CleanShot 2024-06-04 at 16 58 30@2x](https://github.com/bluesky-social/social-app/assets/1270099/38ee9663-224 …

Fix: visually indicate when quoted content is labeled

---

src/locale/locales/fr/messages.po

A few more strings that were introduced / changed just after my last pass on translations (it happens! 🤷‍♂️), mainly about the Chat feature.
Pinging @surfdude29 and @pfrazee as usual, but nothing should raise any eyebrows anyway :)

Update French localizations

---

src/view/com/util/List.tsx
src/view/com/util/List.web.tsx

Let's stop requiring `@ts-ignore` for this prop in our `List` implementation

add types for `desktopFixedHeight` to `List`

---

src/lib/statsig/gates.ts
src/view/shell/bottom-bar/BottomBarWeb.tsx

No count is shown right now on mobile web, so let's add it.
- Set gate to 100%
- Send yourself a DM. The chats badge should increment and should clear once you open the message
- Like your own post or something from an alt, and the notifications tab badge should appear and clear once you open the tab.

add notification count badge mobile web

---

src/lib/media/picker.shared.ts
src/screens/Onboarding/StepProfile/index.tsx

Missed adding this flag in (big whoops on my part!). Android now _does_ show the `...` by default, but it _only_ allows browsing "Cloud media". The `legacy` flag is required for _local_ content.
Build the app, see that the `...` also has the `Browse` option in the dropdown.

add `legacy` to picker for Android

---

package.json
yarn.lock

It's not valid to have different versions of these within one app. Possible cause of Android crashes we're seeing.
I'm no longer seeing this warning on the simulator:

Pin resolution of Statsig Expo dependencies

---

src/components/dms/dialogs/ShareViaChatDialog.tsx

Prevents calling `useGetConvoForMembers` for every feed item until needed.
By moving it inside the inner dialog component.
Send via DM button still works.

Split ShareViaChatDialog

---

src/state/shell/minimal-mode.tsx

When we switched from Reanimated 3.6 to 3.11, scrolling on Home has gotten incredibly choppy. @haileyok and I narrowed it down to this animated value — it's being set to both plain numbers and to `withTiming`, and for some reason it appears that doing both (or maybe even just `withTiming` by itself) makes it choppy even _after_ the animation has completed (i.e. while scrolling later). It seems like `withSpring` doesn't have this problem so this just switches us to do that.
I've looked at other places where we have `withTiming` and they don't seem negatively affected so I didn't touch it.
Scroll Home feed on low-end Android. It was super choppy before, now it's okay (with some dropped frames).

Switch to withSpring to work around Reanimated regression

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx

Tall images didn't fully fit due to a flawed calculation.
I'm not sure why the new calculation makes sense or when it regressed but it does appear to have correct results.
https://github.com/bluesky-social/social-app/assets/810438/b223536f-3c2a-4fb2-9dbe-b2da10ae7e06
https://github.com/bluesky-social/social-app/assets/810438/6a7405a3-ccfc-4212-99d3-1e8eeb1c9c0d

Fix lightbox on Android for tall images

---

src/view/com/notifications/Feed.tsx

Reverts https://github.com/bluesky-social/social-app/pull/4235
It looks like the issue is that fetching the next page doesn't reliably add 2x list height to the scrollview. The intersection observer only tells us when the boundary is crossed -- it doesn't trigger if we're still in the boundary -- and so the next page successfully fires but then doesn't retrigger.
It's entirely possible, with client-side filtering, that even dropping the threshold down to 60% doesn't totally fix the issue.
- We could possibly solve this by calculating the number of new list items getting added post-grouping and, if it's too low, queue another fetch. That feels brittle though.
- We could look for some way to fire an event post-layout, perhaps by running …

Fix notifications pagination on web

---

src/view/com/composer/Composer.tsx

See https://kirillzyusko.github.io/react-native-keyboard-controller/blog/set-enabled
It appears that on some devices, the `react-native-keyboard-controller` library is setting some padding on the bottom of the composer. This breaks the composer, for example as seen here:
Instead, what we can do is enable it in the app, but specifically disable it in this screen. If we do that, this is the result:
- Test on simulator, medium device, API level 28 ✅ 
- Test on device one (personal) ✅ 
- Test on device two (personal) ✅

disable keyboard controller in the composer screen

---

src/view/com/composer/Composer.tsx

Follow up to https://github.com/bluesky-social/social-app/pull/4399. Let's scope this to only Android, doesn't work well on iOS.
Just changing the iOS version back to what it was before disabling in https://github.com/bluesky-social/social-app/pull/4399, so no new behavior.

scope enable/disable of keyboard controller in composer to only android

---

src/view/com/composer/Composer.tsx

My best attempt at making it work based on a real device. Requires some testing.

Reliably focus keyboard on Android

---

src/locale/helpers.ts
src/platform/detection.ts

Maps some old language codes that still get reported by Java (and thus Android)
https://stackoverflow.com/questions/55955641/correct-locale-for-indonesia-id-id-vs-in-id
> it is not a bug in Java, but "the problem" with backward compatibility. Java uses the first version of ISO 639. Later the standard has been updated, and some codes have been updated. Java was designed as fully backward compatible, so the authors decided to not update that codes. It is the cause why "id_ID" is changed to "in_ID". Indonesian is not the only code which is used in an old form. At least Hebrew and Yiddish are also used in the old form.
This is supported in https://xml.coverpages.org/iso639a.html

Override legacy language codes for indonesian, hebrew, and yiddish

---

src/view/com/posts/FeedErrorMessage.tsx

Previously we were relying on the saved config to ensure the Known Feed Error UI was being given on feedgens. This updates it to work even if unsaved.
Can test with memgraph's authors feed

Fix: show known feed error UI more reliably

---

src/view/com/composer/Composer.tsx

When you reply to a deleted post, you now get an error that's human-meaningful

Give a meaningful error in the composer when replying to a deleted post

---

src/screens/Profile/Sections/Feed.tsx
src/view/com/util/EmptyState.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

This isn't a huge improvement but I just can't take the ugliness of the old screen anymore
|Light|Dark|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-10 at 13 30 20](https://github.com/bluesky-social/social-app/assets/1270099/f3f2d406-1751-4b3a-b758-92a11eff665f)|![Simulator Screenshot - iPhone 15 Pro - 2024-06-10 at 13 30 27](https://github.com/bluesky-social/social-app/assets/1270099/ea70bece-f398-4fa0-9e86-c36edeb79378)|
|Light|Dark|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2024-06-10 at 13 29 59](https://github.com/bluesky-social/social-app/assets/1270099/8bc0212a-6cbc-4ff3-a0b3-ab04abc912e4)|![Simulator Screenshot - iPhone 15 Pro - 2024-06-10 at 13 29 50](https://github.com/bluesky-social/social-app/assets/1270099/0d7a79bc-dcbb-46a9-9bf2-55f0fe855927)|

Visually improve the empty state of feeds

---

src/view/screens/Notifications.tsx

Right now we give no visual indication of when loading latest on notifications due to the "soft reset" or the scroll-to-top button. This PR adds a spinner to the top right.
EDIT: Tested on all platforms via sims.
https://github.com/bluesky-social/social-app/assets/1270099/3624ae48-e4e7-4d9f-8f93-162a5cd1bb2d
https://github.com/bluesky-social/social-app/assets/1270099/fb428229-93d8-4080-a337-754e76262ec5

Add a loading indicator to notifications when loading latest

---

patches/expo-notifications+0.28.7.patch
src/lib/notifications/notifications.ts

The callback in `addPushTokenListener` is not fired once the token changes on Android. This appears to be a possible regression in `expo-notifications` - we are inquiring on that now.
What we know:
- Notifications.getDevicePushTokenAsync() still works on both iOS and Android
- The callback in addPushTokenListener() does get called on iOS
- The callback does not get called on Android
What is unclear:
- If this is actually expected behavior. I do not believe it is because:
- It certainly worked in the past (this isn't a guarantee that it's expected of course though)
- It continues to work on iOS
- The documentation suggests to use this callback for registering your push token.
- What can happen if the listener is not added/it is broken. see …

stop using `addPushTokenListener`

---

src/view/com/posts/FeedItem.tsx

This fixes #4322
https://github.com/bluesky-social/social-app/assets/91714073/6a3048ad-d556-445f-8fca-8776d2eefa2d

Fix undefined block

---

src/screens/Messages/List/ChatListItem.tsx

As a better interim solution, this PR opens the `ConvoMenu` on click/press.

Open convo menu when tapping on chat with deleted account

---

src/state/queries/profile-feedgens.ts

Sorts _each page_ of profile feedgens by likes. Because this is per-page, I upped the page size to `50` to lower the chances of not getting a good sort for users with many feeds.
I also considered appending results and re-sorting as it paginates, but this would mean that if a popular feed loads from page 2, it would get sorted to the top out of the user's view, and they _still_ may not see it. So best to retain per-page sorts for the moment.

Sort profile feedgens by likes

---

patches/expo-notifications+0.28.7.patch
patches/expo-notifications-0.28.7.patch.md

The library that `expo-notifications` is using to clear the badge - `ShortcutBadger` does not clear the badge count correctly for some reason. The documentation says that either `clearCount(context, 0)` or `resetCount(context)` should reset the badge, but it does not - even though the call returns `true`.
Instead, we can use the Android API to clear the badge count.
Solution from https://github.com/flutter/flutter/issues/25030#issuecomment-491232528, albeit in Java
- Send yourself some notifications
- Verify the badge increments
- Open the app, visit the notifications tab
- Verify the badge has been removed

patch `expo-notifications` to clear badge

---

modules/expo-background-notification-handler/android/src/main/java/expo/modules/backgroundnotificationhandler/BackgroundNotificationHandler.kt
src/lib/notifications/notifications.ts
src/screens/Messages/List/ChatListItem.tsx

Temporary adjustment for now until we can mark messages read on the server and update the count. This will just decrement the badge count by the number of unread messages in the conversation when you open it.
Far from perfect, but given we're going to actually fix this in earnest in the nearish future, let's just make the badge clear for now and avoid digging too deeply at something that could cause more breaks.
I'm also adding one more fallback for push notification registration given the current expo bug. It shouldn't result in two push notification token registrations, but if it does that's fine too. Better to ensure their token registered right after onboarding.
- Receive DM notification on Android
- Open the conversation
- See the badge has cleared

register the push token after request has been approved on android

---

src/state/queries/post-thread.ts
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadLoadMore.tsx

Ignore the first commit. The second commit took a different approach:
- Increase depth to 10
- Replace the last post in a self-thread with a "Continue thread..." link
Here's a screenshot with the depth decreased to show the behavior:

Improve thread loading

---

src/view/screens/Feeds.tsx

We plan to add an "edit mode" to the feeds page, but in the meantime I think we're better off just giving a clear edit link here.

Update feeds header to just have edit link

---

src/state/queries/post-thread.ts

The logic for identifying the self-thread cutoff (where a "load more" is needed) assumed that the self-thread was being gathered in order. I accidentally appended when I needed to prepend. This fixes it.
|Before|After|
|-|-|
|![CleanShot 2024-06-11 at 14 49 19@2x](https://github.com/bluesky-social/social-app/assets/1270099/4b23bbe1-4f3d-471e-b3d1-43d27e3e84b0)|![CleanShot 2024-06-11 at 14 49 35@2x](https://github.com/bluesky-social/social-app/assets/1270099/aac40e54-8d8d-449b-961e-5b635447595c)|

Fix to thread load-more bug

---

src/locale/locales/ga/messages.po

This PR brings us back to 100%, and fixes a couple of small linguistic bugs in our plural forms.  Thanks to @Aonghuso and Donncha King as usual!
Small review request from someone who knows the setup for plural forms: I've assumed here that we can leave out the "#" from the translation if we don't need it. For example in the "one" case, we can say "1 duine amháin" for "1 person", but it's nicer to say just "Duine amháin" so that's what I've done here.

Irish l10n update

---

src/view/com/profile/ProfileMenu.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

As the title says. Annoying to have to press "Share Anyway" every time you share your own post if you're in PWI opt-out
- Test sharing on an account that is opted-out
- Share a post from post controls
- Share a post from the post dropdown/dialog
- Share a profile from the profile dropdown
- Test sharing on an account that isn't your own and is opted-out
- Same as above
https://github.com/bluesky-social/social-app/assets/153161762/70767c42-4e19-4717-a8e2-4596109c50f1

Don't show warning when sharing your own post in PWI opt-out mode

---

src/components/KnownFollowers.tsx

Was trying to be clever, but this logic was clearly flawed: the server only hydrates 5 profiles, and if any blocks exists, it filters those out. Adjusting the count here on the client isn't possible to do correctly, since there could still be 300 other follows in common that weren't hydrated.
Also, the count wasn't reflecting the few that show up as previews, so `and n others` was always wrong.
So we'll still rarely have the issue where we count 300 known followers, but all 300 are blocked. For this, `KnownFollowers` simply won't be rendered. But if say, 2 are not blocked, you'll get `followed by X, Y, and 298 others`, and when clicking into to view all, you'll see only those 2.

Just use server count

---

src/components/KnownFollowers.tsx
src/components/ProfileHoverCard/index.web.tsx

Just copy-paste from the profile. Web-only.
Doesn't show up if there's no social proof.

Show social proof in hovercards

---

src/view/com/composer/text-input/TextInput.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1321
Fixes https://github.com/bluesky-social/social-app/issues/3032
Fixes https://github.com/bluesky-social/social-app/issues/4301
We don't actually support rich WYSIWYG formatting in the composer, check if what's being pasted is one, and retrieve a plain-text version of it. This won't interfere with pasting HTML files (even though that's not supported either) as pasted files only have `Files` in the types array.

Prevent rich-formatting paste

---

src/state/queries/profile.ts
src/view/com/util/PostMeta.tsx

Two related things were happening in this PR:
- though `ProfileHoverCard` was using `onPointerMove` to prevent triggering prefetches while scrolling, `PostMeta` was still using `onPointerEnter`, which triggers while scrolling
- whether scroll or roll-over, profile prefetch was being called every time, so adding stale time of 30s effectively debounces those calls
So the result is: `getProfile` is no longer called on scroll, and it's called at most once every 30s if the user intentionally hovers over the triggers.
In `PostMeta`, `Text` doesn't support `onPointerMove`, so I wrapped it in a `View` and double checked overflow, should be OK (see screenshots)

Set profile hover prefetch stale time to 30s

---

src/components/ProfileHoverCard/index.web.tsx
src/components/moderation/ProfileHeaderAlerts.tsx

Fixes the blocked state of the profile hover cards, fixes #4423
The profile label here is non-interactive, the overlaying multiple modals was causing issues.

Fix profile hover card blocked state

---

src/components/KnownFollowers.tsx

Provides full context to the KnownFollowers string to allow for easier localization.
```po
#: src/components/KnownFollowers.tsx:169
#~ msgid "Followed by"
#~ msgstr ""
#: src/components/KnownFollowers.tsx:179
#~ msgid "{0, plural, one {and # other} other {and # others}}"
#~ msgstr ""
#: src/components/KnownFollowers.tsx:194
msgid "Followed by <0>{0}</0>"
msgstr ""
#: src/components/KnownFollowers.tsx:183
msgid "Followed by <0>{0}</0> and <1>{1}</1>"
msgstr ""
#: src/components/KnownFollowers.tsx:170
msgid "Followed by <0>{0}</0>, <1>{1}</1>, and {2, plural, one {# other} other {# others}}"
msgstr ""
```

KnownFollowers localization

---

src/screens/Profile/Header/ProfileHeaderStandard.tsx

Twitter doesn't display them. I'm not sure we should either. Showing social proof definitely feels off on a block. For bio, I could see it either way, but I lean towards not displaying it either if there's a block relationship.
https://github.com/bluesky-social/social-app/assets/810438/c590d632-a6d9-443a-ba31-5aef0a2b4deb

Hide bio and social proof for blocked users

---

src/view/com/composer/Composer.tsx

`KeyboardAvoidingView` needs a an offset in the new composer modal. Currently, it's hardcoded with a value of 70, which works for dynamic island iPhones. However, it does not work for other models (see the SE below, it also doesn't quite work on my 14).
This is because it needs to be set to the height of this area, above the sheet:
This PR calculates it by getting the height of the sheet and subtracting that value from the screen height. This produces 69 on the iPhone 15 and 40 on the iPhone SE, which just about matches the hardcoded value.
<table>
<tr>
<td>Before</td>
<td>After</td>
<td>After</td>
</tr>
<tr>
<td><img src="https://github.com/bluesky-social/social-app/assets/10959775/60abb3a0-9635-4abb-a0da-2a8778b55fb2" alt="Before" width="200"></td>
<td><img …

Calculate correct keyboard offset in composer

---

src/lib/statsig/statsig.tsx

Want to add referrer to statsig events. We currently have `refUrl`, but that requires a URL parameter that doesn't get set outside of our embeds.
On web, let's add the value of `document.referrer` to the statsig session `custom` object.
I modified a link on google to direct me to `http://localhost:19006` with a console log inside of `statsig.tsx`.

add `document.referrer` to statsig custom

---

src/state/queries/feed.ts
src/view/screens/Feeds.tsx

The popular feeds query returns a static list of feeds. Some are not available logged out, and it returns feeds even if you've already pinned them. We had logic on the Feeds screen to filter based on session state and by which feeds you have saved.
I needed to reuse the same logic in #4491 and seemed like we could push this logic into the query handler itself.
This means that **the popular feeds query will now return results with the feeds you've saved filtered out.** We don't use this for anything else at the moment, and if we do need this, it'd be easy enough to add a param to this query to conditionally filter.
The only semi-noticeable change that this PR introduces is over-fetching if the first page of results doesn't return enough feeds that aren't already pinned. It reuses the exact …

DRY up popular feeds query

---

src/components/KnownFollowers.tsx

[Confused myself here](https://github.com/bluesky-social/social-app/pull/4499/files#diff-74e85eaa949c16e6b2da5eb5a60265bfd6ca8c5a2753e1829a8262382bcffa32R98) and was subtracting previewed users twice. This count value should be the server count, and the # of other users is already handled further down in this file.

Fix count again

---

src/view/com/home/HomeHeaderLayout.web.tsx

Fix kawaii logo

---

src/components/FeedCard.tsx
src/components/Prompt.tsx
src/components/dms/LeaveConvoPrompt.tsx
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/view/com/util/post-embeds/GifEmbed.tsx
src/view/screens/Feeds.tsx

Refactors `FeedSourceCard` into `FeedCard`.
Why? Because `FeedSourceCard` loads its own data, and in my cases (like on the Feeds screen) we already have data from the list endpoint. In fact, sometimes these `n+1` loads fail, and we leave the user with a loading state.
The old component is used a handful of places, so a re-implementation is the easiest way to replace.
This PR adds new "macro" components to replace `FeedSourceCard` that allow different compositions e.g. no likes data, or save instead of pin, without needed to bloat the main API contract.
However, this PR defines a `Default` export that is essentially a direct replacement for `FeedSourceCard` as it is today.
This PR does _not_ reimplement the placeholder states for the card itself, since it's not strictly needed in this PR. …

Feed source card

---

src/view/screens/Search/Search.tsx

Was getting a duplicate key error — fat-fingered `did` instead of `uri`.

Use URI as key

---

src/components/ProfileHoverCard/index.web.tsx
src/view/com/util/PostMeta.tsx

**[without whitespace](https://github.com/bluesky-social/social-app/pull/4530/files?w=1)**
Looks like we added a `View` around the text in `PostMeta`. This breaks the layout on iOS, particularly since we added `flex: 1` to the `View`.
Removing that flex though then breaks Android. Since we want to avoid breaking things in any scenario - which is fairly hard to test - let's just move this new wrapper (and all of the prefetch logic) into the web implementation.
Moved the wrapper view into the `ProfileHoverCard` in `index.web.tsx`. On native, it will continue to just return children.
https://github.com/bluesky-social/social-app/assets/153161762/41143e4a-bbb5-4c62-bd5a-c50f6540b078

Fix spacing on native post meta

---

.husky/pre-commit

When setting up the environment on a Windows machine with Git Bash, the pre-commit hook errored out:
> /usr/bin/bash: line 1: C:UsersNameFoldersocial-appnode_modules.binlint-staged: command not found
Seemingly, `yarn lint-staged` is not able to correctly resolve the path.
This commit changes the pre-commit hook to use `npx` instead of `yarn`, for 2 reasons:
1. It works on my machine (and is supposedly a more universal solution)
2. It is how it is done in the documentation: https://github.com/lint-staged/lint-staged?tab=readme-ov-file#examples

Make `lint-staged` work in more envs

---

src/App.native.tsx
src/lib/statsig/gates.ts
src/lib/statsig/statsig.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx

This adds an experiment to the logged-out view on native only. To do so, we need to fetch Statsig config immediately. So, if we have no user to resume from, we do a full load of Statsig data to ensure we have accurate config based on the stable device ID.
To do this, I tested calling `initialize` with `prefetchUsers` on the options object, but this failed all three tests I did, in that it didn't load the config in time. So I opted to adjust the API of `tryFetchGates` to allow `undefined` as the DID value, [which will then fall back](https://docs.statsig.com/client/jsClientSDK#statsig-user) to using the stable device ID.
This works in my testing every time:
- delete app to clear storage
- re-run `yarn ios`
- see that the config in Statsig dashboard is correct
- I've been using 100% on or …

Add `native_pwi_disabled` feature gate experiment

---

__tests__/lib/string.test.ts
src/lib/strings/time.ts

The [current tests for ago() function](https://github.com/bluesky-social/social-app/blob/22858192dc5848cf75fb48fa911c8a9bbf08dbaa/__tests__/lib/string.test.ts#L146) are not deterministic, so they are currently disabled.
Create a testable version of ago(), **dateDiff()**, that has two parameter, allowing for deterministic tests. ago() is then implemented as a special case of dateDiff(), where one of the dates is `new Date()`.
The implementation is changed so that months are now considered to a fixed 30 days instead of the current 30.41675 days. Using 30 days is arguably less precise, but it is a lot easier to reason about because the cut off from month to month is always a full day. I think this simpler solution was preferable. The root cause of the mess is that "a month ago" means a …

Create a testable version of ago() and re-enable the disabled test

---

.eslintrc.js
eslint/index.js
eslint/keep-i18n-patch-in-sync.js
patches/@formatjs+intl-pluralrules+5.2.10.patch

Patch `supportedLocales` from  `@formatjs/intl-pluralrules` to only include the ones we actually use. Since this is easy to mess up, I also added a lint rule that enforces we don't add new locales without also tweaking that patch.
I'm not sure why the `@formatjs/intl-pluralrules` polyfill is so slow but I didn't have time to get into it. I filed https://github.com/formatjs/formatjs/issues/4463.
Disable the `console`-removing Babel plugin in the Babel config.
Before (5 runs):
```
Time to first paint: 2675 ms
Time to first paint: 2926 ms
Time to first paint: 2762 ms
Time to first paint: 2928 ms
Time to first paint: 2853 ms
```
After (5 runs):
```
Time to first paint: 1905 ms
Time to first paint: 1921 ms
Time to first paint: 1926 ms
Time to first paint: 1929 ms
Time to first paint: 1901 ms …
```

Fix Android startup perf regression

---

src/components/forms/DateField/index.tsx
src/view/com/util/layouts/LoggedOutLayout.tsx

Small PR to address the keyboard being in the way of some inputs during onboarding on some devices/font sizes. Also makes sure that the keyboard gets dismissed when opening the DOB modal.
Make sure the screen is scrollable, and that you can scroll all the way to the bottom with keyboard shown.
https://github.com/bluesky-social/social-app/assets/153161762/38017bd4-c1fe-4890-b961-079e2d62129f

fix keyboard overlaying onboarding inputs

---

src/alf/atoms.ts
src/alf/tokens.ts
src/view/screens/Search/Explore.tsx

Fixes border width math on iOS by not using hairline widths around the avis. Also ensures that if fewer than 3 items are available for the `LoadMore` component, styling is consistent. EDIT: Also introduces font_heavy and uses it on the headers of Explore.
Also adds safer checks for the `LoadMore` component
- only render if `hasNextPage` is true
- only render if the array of preview items has valid values

Explore fixes

---

src/state/queries/post-thread.ts

Issue:
[This post demonstrates the issue](https://bsky.app/profile/o.simardcasanova.net/post/3kv4clsfcyk2x)
|Screenshot|Description|
|-|-|
|![CleanShot 2024-06-18 at 10 00 07@2x](https://github.com/bluesky-social/social-app/assets/1270099/0783d648-76a6-4751-8236-e1e2dc74204a)|The "Continue thread..." link is incorrectly showing on post 3 instead of post 10. In this case, there isn't actually a post 10. What did happen is, after 3 posts, another user replied and then was subsequently blocked.|
The reason this is happening is that a blocked reply and a truncation at the limit of the reply tree both look the same: a non-zero `replyCount` and an empty/undefined `replies`.
It turns out the solution to this is pretty straight-forward: only apply the "Continue thread" logic when you're at the …

Fix: don't interpret blocked replies as truncated self-threads

---

src/state/cache/thread-mutes.tsx
src/state/persisted/schema.ts
src/state/queries/post.ts

Simple. Uploads existing thread mutes then deletes them.
Does not account for multi-accounts, but I'm not sure if there is a neat solution here without making this far more complex than necessary

Migrate local thread mutes

---

src/components/KnownFollowers.tsx

So the issue here is that there are two count values that matter, `length` or `count`:
- `knownFollowers.followers.length`
- `knownFollowers.count`
`followers[]` filters out blocks, and only hydrates 5 profiles server-side, so that array _could_ be `0`, though it's unlikely. If that ever happened, we'd just not render anything at all.
More likely is `followers.length < count` because 1 or more profiles are blocked and filtered out.
So rendering should be driven by `followers.length`, but `and N others` can only be driven by `count` since that can be much higher than the 5 max returned on `followers`.
So the fix here is:
- determine if we have 1, or more than 1 `followers[]` to render
- use the `count` to determine if we need a `, ` or ` and `
- use `count` to determine if we need `and N …

Better handling of blocks in `KnownFollowers`

---

src/screens/Signup/state.ts

We've heard rumors of pinned feeds and other profile data being lost when creating accounts. Aaron experienced this earlier, and was able to walk me through the exact steps he took.
The issue was that `createAccount` was failing AND he had multiple tabs open with a currently logged in account. So onboarding state was updated to `start`, which updates for all tabs, but the active tab then failed.
Upon failure, it does reset in the active tab, but in some cases it evidently doesn't reset in the other tabs, perhaps because of a write in one of those other tabs clobbering the active tab. When testing with Aaron we were able to enter onboarding in the inactive tabs, and when returning to the active tab where signup was taking place, we were also pulled into onboarding.
The other half of the …

Move onboarding start to after successfull account creation

---

src/state/session/agent.ts
src/state/session/index.tsx

We were previously suppressing a type error which was a legit mismatch in types. We were assigning `SessionAccount` (an app concept) directly into `agent.session` as if it were `AtpSessionData`.
Strictly saying, this isn't valid — for example, `refreshJwt` can be `undefined` in `SessionAcount` but is expected to be a `string` (even if empty) in `AtpSessionData`. We *do* have a check (per suppression comment) that should rule out this actually happening but I think it's better to ensure this statically. This also avoids unrelated account fields like `pdsUrl` ending up attached to the `session` object.
This PR removes the suppression and adds an explicit conversion based on existing logic from the resume session codepath.
**I don't expect this to change anything in practice.**
Idk how to …

[Session] Convert account to session data explicitly

---

src/view/com/util/List.web.tsx

The native `FlatList` implementation allows `data` to be `undefined`. It does not _have_ to be an array. In our web implementation though, we assume that it is since all we do is assert `data as Array<ItemT>`.
To test this, use `Feed.tsx` and change the `data` prop to `undefined`. This appears fine - since the `FlatList` types allow it - but our causes an error.
There is a `ListEmptyComponent` prop on `FlatList` that will render the given element when the `data` is empty or `undefined`. I've added support for that view as well in this PR.
- Use `Feeds.tsx` as an example
- Change `data` in the `List` to `undefined`
- There should no longer be an error 
- Add `ListEmptyComponent` prop to the `List`, with a value like:
```tsx
<View style={{alignItems: 'center', marginTop: 20}}>
<Loader …
```

add support for `ListEmptyComponent`, allow `undefined` data

---

src/screens/Profile/Header/index.tsx

Seems like it grew from 80px to 90px at some point. Adjusting accordingly. Also tweaked the button placeholder padding to match the real one.
https://github.com/bluesky-social/social-app/assets/810438/e06c66f6-ba55-4514-a14a-17c67904a058
https://github.com/bluesky-social/social-app/assets/810438/421e3bd6-da1c-4c94-87ad-09b70173c6f6
Tested on web (above), verified it's also 1:1 on iOS and Android.

Fix avi placeholder layout

---

src/state/persisted/schema.ts
src/state/preferences/hidden-posts.tsx
src/state/preferences/index.tsx
src/state/preferences/large-alt-badge.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/GifEmbed.tsx
src/view/com/util/post-embeds/index.tsx
src/view/screens/AccessibilitySettings.tsx

Text size bumped from 7px -> 12px
<table>
<tr>
<td>Settings</td>
<td>Single image</td>
<td>Two images</td>
</tr>
<tr>
<td><img width="596" alt="Screenshot 2024-06-19 at 18 35 33" src="https://github.com/bluesky-social/social-app/assets/10959775/d5c916d4-b370-4554-9acc-e2f4cba60599"></td>
<td><img width="592" alt="Screenshot 2024-06-19 at 18 36 26" src="https://github.com/bluesky-social/social-app/assets/10959775/61d42292-4f53-428e-aaa2-77f49ccee9ac"></td>
<td><img width="582" alt="Screenshot 2024-06-19 at 18 36 03" src="https://github.com/bluesky-social/social-app/assets/10959775/1caeed74-8d9d-4ce9-a9fb-b8914e76e0bc"></td>
</tr>
</table>

Option for large alt badges

---

src/view/com/home/HomeHeaderLayoutMobile.tsx

Header size was being influenced by the presence of the feeds button. This sets a min-height

Fix double border in PWI

---

src/components/forms/TextField.tsx

Scoped to web only. Adds 2px of margin to the top and bottom of the text input so that it doesn't cover the border, and reduces padding by that amount
<table>
<tr>
<td>Before (ff)</td>
<td>After (ff)</td>
<td>Before (chrome)</td>
<td>After (chrome)</td>
</tr>
<tr>
<td><img width="700" alt="Screenshot 2024-06-19 at 19 20 34" src="https://github.com/bluesky-social/social-app/assets/10959775/2106733f-0975-46f9-9695-333ae6b82760"></td>
<td><img width="701" alt="Screenshot 2024-06-19 at 19 20 24" src="https://github.com/bluesky-social/social-app/assets/10959775/cf29a42d-5065-41a4-b640-51752c9abf9e"></td>
<td><img width="695" alt="Screenshot 2024-06-19 at 19 21 50" src="https://github.com/bluesky-social/social-app/assets/10959775/594cba4f-248e-4579-b733-4dcce043b2ae"></td>
<td><img width="698" …

Fix for autofill covering border

---

src/screens/Onboarding/StepProfile/index.tsx
src/view/com/util/UserAvatar.tsx

Avatar cropping on Android is not great right now, since the current logic requires the new image be the same size as whatever the input is. For example, a 3000x1500 input will expect an image of that same aspect when cropping. This doesn't work very well for avatar crops.
https://github.com/bluesky-social/social-app/assets/153161762/8f592f37-36ee-463a-a322-c0587e055f3c
Instead of using the input picture's height and width, we should just set this to a size with equal height and width. We'll use 1000x1000 for now. This ends up allowing us to crop to whatever region of the photo we want.
https://github.com/bluesky-social/social-app/assets/153161762/89f6af7d-f631-49d1-8847-5c3a60819018
- Verify that crops still work correctly on Android on various devices
- Verify that iOS cropping still …

Use a 1:1 ratio for avatar cropper

---

src/components/Button.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/screens/ProfileFeed.tsx

* Makes the ProfileMenu button in the ProfileHeader change color based on mouse over.
- Before:
<video src="https://github.com/bluesky-social/social-app/assets/11014257/991e3a35-88fa-4a3e-a8b0-149c7d2c94b3">
- After:
<video src="https://github.com/bluesky-social/social-app/assets/11014257/8a1c916d-e3e0-416d-9658-c5c8747319ca">
* Match the hover color of the other buttons to the other parts. And Match the icon to the ProfileMenu button.
- Before:
<video src="https://github.com/bluesky-social/social-app/assets/11014257/f4da6076-11c7-4a8a-8395-3aec62a4146b">
- After:
<video src="https://github.com/bluesky-social/social-app/assets/11014257/845f1177-316a-4e9e-9dbb-d3e9a208bdaa">
* Match the hover color of the ghost button accordingly.
- Before:
<video …

Fix button hover color

---

src/App.native.tsx
src/App.web.tsx
src/state/a11y.tsx

Adds a couple a11y props to context so that they're available synchronously in the app. Right now we only check for reduced motion, so I've used that same value from Reanimated as the initial value here (that check IS sync, actually).
This also adds screen reader state for use in Starter Packs and eventually other infinite scroll cases.
Note case on web: screen reader always returns `true`. Since we're primarily concerned about mobile for this immediate need, I've opted to override on web to always be `false`. Eventually we may want to fork these props into something like `isScreenReaderEnabledWeb` and handle some cases differently.

Add a11y context

---

src/state/session/index.tsx
src/state/session/logging.ts
src/state/session/reducer.ts

This adds enough logging to key parts of the session logic that we should be able to figure out what's going on if something goes wrong. Note that agents are numbered (using WeakMap), tokens are sent as hashes (so we can trace what happens to each of them over time).
Allowlist your stable ID (`Statsig.getStableID()`) for the `debug_session` gate. We'll only enable it for the few users who reported problems. Observe events rolling in. (Don't forget to turn on "Show non-production logs"!)
Note that there's a notion of separate "realms" (`realmId`) which correspond to browser tabs or app instances, a notion of separate "messages" (which are JSON objects describing what happened), and "slices" (which is an artifact of the transport — Statsig forces us to break apart the logs into smaller …

[Session] Logging

---

src/state/queries/suggested-follows.ts
src/view/screens/Search/Explore.tsx

New Explore page only loads 3 suggested follows up front in order to show feeds above the fold. But when loading more, we should load more than 3 at a time.
This PR loads 10 users _after_ the first page has been returned. Additionally, since feeds are already below the fold, we might as well fetch more than 3. So this PR updates to fetch 10 of those and let them extend below the fold.

Fetch more than 3 suggested follows after first load

---

src/lib/statsig/gates.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

If you pass the gate (meant only for debugging), this shows a tiny label with `feedContext`. I could make it bigger but I don't want to interfere with the "real" layout or to have it be obscured by anything. It copies to clipboard on tap.

Add debug feedContext label

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx
src/state/feed-feedback.tsx

To get more statistical power in experiments, let's reuse the feed feedback system. There's some aggregation, throttling, and sampling to ensure that we don't blow too many event credits.
Try scrolling, liking, engaging with posts in Discover. Turn off sampling in `statsig.ts`, put `console.log` in `logEvent`, and verify the events coming through.

[Statsig] Send Discover aggregate interactions

---

src/components/FeedCard.tsx
src/state/queries/feed.ts
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/screens/Feeds.tsx

There's some spinner states on feed cards - in prod, not related to the `FeedCard` change necessarily - that we'd like to remove. Easy little win.
We also didn't actually migrate to using the new `FeedCard` in the `ProfileFeedgens` list. I had done this work in the starterpacks branch, so I picked it out of there and made a couple tweaks after the recent `FeedCard` merge into main.
Finally, made a little types tweak inside of `FeedCard` so that `Link` knows whether something is a `ListView` or `GeneratorView`, supporting this new precaching.
We already have a `precacheFeed` function that takes in `FeedSourceInfo` from inside one of our query functions. However, we also want to make it possible to run this with a `GeneratorView`.
Following a similar pattern that we use for posts and …

Tweak feed card to prevent spinnerz when pushing to screen

---

src/screens/StarterPack/Wizard/index.tsx

In some languages, a measure word (counter word) may be required after a number, and different counter words are used to show the number of "profiles" and "feeds" in a sentence.
ref. https://en.wikipedia.org/wiki/Measure_word
In Japanese, you can use "人" for "(human) profiles", and "個" or "フィード" for "feeds" (if the number of feeds is less than 10. "つ" is also fine).
| | 1 profile | 2 profiles | 1 feed | 2 feeds |
| --- | --- | --- | --- | --- |
| English   | 1 other | 1 other | 2 others | 2 others |
| Japanese | 他1人 | 他1フィード | 他2人 | 他2フィード |
The current StarterPack does not distinguish between profiles and feeds, so I tried making it possible to distinguish by specifying the context property in <Trans>.

Modified to use "measure word" in "# others"

---

src/components/WhoCanReply.tsx
src/view/com/post-thread/PostThreadItem.tsx

This PR:
- Adds an edit-pencil icon to WhoCanReply if you are the OP
- Removes the WhoCanReply element from the reply parentage when not viewing the OP
|Screenshot|Description|
|-|-|
|![CleanShot 2024-06-24 at 08 32 55@2x](https://github.com/bluesky-social/social-app/assets/1270099/7407c0eb-6ef4-45d5-a745-dc5b0d4d80c3)|After spending the weekend QAing, I found this element somewhat jarring to see everywhere when viewing replies. Visually it scans like a moderated post (eg "Post by muted user") and it breaks up the conversation. It also just takes up more real-estate that the information deserves.|
|Screenshot|Description|
|-|-|
|![CleanShot 2024-06-24 at 08 39 40@2x](https://github.com/bluesky-social/social-app/assets/1270099/462daa91-8fa8-4a0d-b2de-aef2e5e81ee8)|When viewing the OP, the …

Remove the 'Who can reply' element except when viewing root, and add "edit"

---

src/screens/StarterPack/Wizard/StepFeeds.tsx
src/state/queries/feed.ts

See inline comments.
Add `throw Error('no')` [here](https://github.com/bluesky-social/social-app/blob/873d91d4664403577fff0438bfc81304f1fafe5b/src/state/queries/feed.ts#L544), then add it [here](https://github.com/bluesky-social/social-app/blob/873d91d4664403577fff0438bfc81304f1fafe5b/src/state/queries/feed.ts#L531). In both cases the Feeds page should be able to recover, and show the rest instead. Similarly start pack creation should recover in both cases.

Fix crash in Feeds and Starter Packs

---

src/screens/StarterPack/Wizard/StepFeeds.tsx

The `useSavedFeeds` query needs the user's preferences to be loaded first. Generally a user's preferences should be loaded already and cached before we enter the wizard, but its possible for them to be invalidated when we enter. If they are invalidated, they will get refetched inside of `useSavedFeeds`.
While fetching preferences, the `useQuery` in `useSavedFeeds` is disabled. This means that `isLoading` will be _false_ for a moment - so just checking `isLoadingSavedFeeds` will not always work. Instead, we want to look at `isFetchedAfterMount`.
You can add a test promise as shown in the video below and remove `staleTime: Infinity`.
https://github.com/bluesky-social/social-app/assets/153161762/b0ae5fd7-7dae-4aff-ac85-250fa8a9a246
https://github.com/bluesky-social/social-app/assets/153161762 …

Wait for preferences before showing suggested feeds

---

plugins/starterPackAppClipExtension/withClipInfoPlist.js

Make sure the app clip can't rotate to horizontal mode. Using the same values here as our app.

Maintain portrait in app clip

---

src/components/FeedCard.tsx
src/screens/StarterPack/StarterPackLandingScreen.tsx

This PR disables links within `FeedCard.Description`. It _does_ run `detectFacetsWithoutResolution` so that URLs look nice.
If we ever have need for them, we can add another export here called like `DescriptionWithFacets`, sorta like the first commit in this PR.

Disable facets in `FeedCard.Description` component

---

src/components/dialogs/ThreadgateEditor.tsx

As a follow-up to #4329, this tiny PR fixes a typo in the threadgate modal, changing `Chose` to `Choose`.

Fix typo in threadgate modal

---

bskylink/src/routes/siteAssociation.ts
bskyweb/static/.well-known/apple-app-site-association

AASA requires `applinks` to be present, even if the domain is only used for an app clip.

tweak app clip AASA

---

src/locale/locales/fr/messages.po
src/locale/locales/ja/messages.po
src/screens/StarterPack/Wizard/index.tsx

At footer messages in starter pack wizard, when selected two feeds, first of selected items are displayed as 'You', not the feed's name. This PR fixes this problem.
This PR also contains companion Japanese message updates.

Fix footer messages in starter pack wizard

---

src/components/StarterPack/ProfileStarterPacks.tsx

After seeing [this video](https://github.com/bluesky-social/social-app/pull/4650#issuecomment-2191884933) I noticed that two of the starter pack strings haven't yet been marked for localization. This PR does that.

Mark two starter pack strings for localization

---

src/screens/Onboarding/StepInterests/InterestButton.tsx
src/screens/Onboarding/StepInterests/index.tsx
src/screens/Onboarding/state.ts

Updates the interest selection set to match what's returned from the server, and provides translation extraction for these values. I did this with a hook, which meant I could replace the static values that were previously stored on context.

[D1X] Onboarding interest display names

---

src/view/com/composer/text-input/TextInput.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/4656.
This regressed in https://github.com/bluesky-social/social-app/pull/4327. Copying an image _does_ include `text/html` so the fix is to do both the `text/html` condition _and_ to run the code below searching for images.
Copied an image, tried pasting it in Chrome, Safari, and FF. It works after the fix.
I haven't verified whether #4327 itself regressed (for Edge) but I don't see why it would. We're still taking plain text for the main paste, we just happen to _also_ look for images now. So it's probably fine.

Fix pasting images on web

---

src/state/preferences/feed-tuners.tsx

See [here](https://bsky.app/profile/retr0.id/post/3kvwayynkxj2v). Generally "Replies" is expected to show only original content. This is easy to do on the client so I'll just filter it out locally but IMO we should change it on the backend in the future.

Remove reposts from the Replies tab

---

src/components/ProfileCard.tsx

Refactors the new `ProfileCard` component to be flexible and composable. Also handles blocked account state, see screenshot, but we should really filter those accounts out from this view.
Main exports here are `Default` (which matches the `StarterPackCard` and `FeedCard`) and `Card` which does not include a `Link` that wraps the card by default.
We could integrate `KnownFollowers` into the default exports here, or we could integrate that compositionally, tbd.
Only used in starter packs in two places right now:

Refactor `ProfileCard` to be composable

---

src/Navigation.tsx
src/lib/link-meta/resolve-short-link.ts
src/lib/routes/types.ts
src/lib/strings/url-helpers.ts
src/routes.ts
src/screens/StarterPack/StarterPackLandingScreen.tsx
src/screens/StarterPack/StarterPackScreen.tsx
src/state/queries/resolve-short-link.ts
src/state/shell/logged-out.tsx

We want to be able to resolve any short links in the app, even if they don't get resolved while posting. This is a little challenging because we have to reach out to `go.bsky.app` first. I added JSON response support in https://github.com/bluesky-social/social-app/pull/4671, which we can now use to perform resolution when landing on these.
1. First, we click on a link in the app. We already check for if links start with `bsky.app` but we don't check `go.bsky.app` which we add here.
2. We then push to the `StarterPackScreenShort` route
3. The short route attempts to resolve the real URI and then render the starter pack screen with the resolved did and rkey
The nice thing here is this is extensible to other schemes whenever we want to. For example, post short links - which we are less …

Handle pressing all go.bsky.app links in-app w/ resolution

---

src/components/FeedCard.tsx
src/components/ListCard.tsx
src/components/StarterPack/Main/FeedsList.tsx
src/screens/StarterPack/StarterPackLandingScreen.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/screens/Feeds.tsx
src/view/screens/Search/Explore.tsx
src/view/screens/Search/Search.tsx

This PR refactors `FeedCard` a bit and extracts a `ListCard` component for easier usage in either case. If you're rendering a feed, use `FeedCard`. List, use `ListCard`.
`ListCard` inherits from `FeedCard`, since they're very similar, but I think the clarity of usage like this makes this pattern worth it. If we need to further differentiate in the future we can pretty easily like this. Examples:
- lists don't have likes, no need for `Likes` component
- maybe one day we need a different action export for modlists like `SubscribeButton`
- `TitleAndByline` needs a `purpose` for lists, but not for feeds
- maybe soon we need a `type` or `purpose` field for feeds  👀

FeedCard & ListCard cleanups

---

src/lib/statsig/events.ts
src/screens/Signup/StepCaptcha/index.tsx
src/screens/Signup/index.tsx

It would be nice to know whenever people successfully complete the captcha. There's some weird stats that are hard to understand if users are not actually failing captchas - which is the most likely 
reason we're seeing this. It would be good to have confirmation on this though.
Adds a success and failure event that get logged upon completion of the captcha - whether it fails or not.
Check network tab while stepping through onboarding to ensure events get logged where they should.

Add events to signup for captcha results

---

src/screens/Signup/BackNextButtons.tsx
src/screens/Signup/StepHandle.tsx

A few changes to match the old behavior:
- Adds back live validation based on a controlled "draft" local state (the input remains uncontrolled though)
- Adds back clearing of server event on first keystroke (and removes clearing on pressing Next)
Small tweak on top:
- Don't show the validation "errors" and a broken `@.bsky.social` until the user types something
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/4720/files?w=1)
https://github.com/bluesky-social/social-app/assets/810438/67dcde35-a534-4a49-ba0d-55c108b1cc4d

Re-add live validation to signup form

---

src/components/Pills.tsx
src/components/ProfileHoverCard/index.web.tsx
src/components/dms/MessagesListHeader.tsx
src/components/moderation/ContentHider.tsx
src/components/moderation/PostAlerts.tsx
src/components/moderation/ProfileHeaderAlerts.tsx
src/screens/Messages/List/ChatListItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/profile/ProfileCard.tsx

We have 4 variations of labels in the app right now: profiles, post thread small/large, and one in the old ProfileCard. 
This PR copies the pill component from `PostAlerts` and consolidates styles to `sm` and `lg`, which almost exactly match what's in prod, and where they don't, try to strike a happy medium. This way, labels are presented and handled consistently throughout the app.
**Testing**
See screenshots for locations, and here's a good thread to use: http://localhost:19006/profile/darthbluesky.bsky.social/post/3kutuafqadc2k
All screenshots are after -> before

Unify label pills

---

src/view/com/auth/LoggedOut.tsx

If PWI is disabled for this experiment, we need to hide the link to search as well, since those routes are now inaccessible. Tested and confirmed this experiment only applies to native.

Remove search from disabled PWI state

---

src/view/com/util/post-embeds/GifEmbed.tsx

Changes `maxWidth: 100%` to `width: 100%`. GIFs are full-width anyway so I don't believe this should cause any issues.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img width="289" alt="Screenshot 2024-07-02 at 16 21 43" src="https://github.com/bluesky-social/social-app/assets/10959775/c567ca80-8871-4538-a9c9-9897b95113bb"></td>
<td><img width="289" alt="Screenshot 2024-07-02 at 16 21 27" src="https://github.com/bluesky-social/social-app/assets/10959775/b0f375a3-799a-4768-9a22-20a426c980bc"></td>
</tr>
</table>
Check GIFs still work in other places across the app

Fix GIFs in DMs

---

src/components/Link.tsx
src/components/StarterPack/Main/ProfilesList.tsx
src/components/StarterPack/StarterPackCard.tsx
src/lib/link-meta/bsky.ts
src/lib/strings/starter-pack.ts
src/lib/strings/url-helpers.ts
src/screens/StarterPack/StarterPackScreen.tsx
src/screens/StarterPack/Wizard/index.tsx
src/state/queries/starter-packs.ts
src/view/com/composer/useExternalLinkFetch.ts
src/view/com/util/post-embeds/index.tsx

Relies on https://github.com/bluesky-social/atproto/pull/2613 being deployed or using dev env from that branch.
Note that these will work with `go.bsky.app` links as well, though those records wouldn't work in the local dev env. Once ^ gets deployed we should just test again to make sure.

Add starter pack embeds to posts

---

package.json
src/App.native.tsx
src/App.web.tsx
src/components/FeedInterstitials.tsx
src/components/ProgressGuide/List.tsx
src/components/ProgressGuide/Task.tsx
src/components/ProgressGuide/Toast.tsx
src/components/anim/AnimatedCheck.tsx
src/lib/statsig/gates.ts
src/screens/Onboarding/StepFinished.tsx
src/screens/StarterPack/StarterPackScreen.tsx
src/state/queries/preferences/const.ts
src/state/queries/preferences/index.ts
src/state/queries/profile.ts
src/state/shell/progress-guide.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/com/posts/Feed.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/shell/desktop/RightNav.tsx
yarn.lock

https://github.com/bluesky-social/social-app/assets/1270099/4e61c85c-9661-4e8f-afb1-29dabf079135
(Interstitials showing progress not yet done in this recording)
https://github.com/bluesky-social/social-app/assets/1270099/699aef79-7f1b-4187-81fc-e99e541480a6

New user progress guides

---

src/lib/statsig/gates.ts
src/state/queries/notifications/feed.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/view/com/notifications/FeedItem.tsx

If someone follows you _back_, this PR ungroups that notification from the other follows and shows it as below. Multiple follow-backs are shown separately.

[D1X] Pull out follow-backs for higher signal

---

src/state/feed-feedback.tsx
src/view/com/posts/Feed.tsx

We broke feed feedback when adding interstitials because feed list item is no longer a slice but a wrapper over it. Solving by adding a utility function that maps between the two types so that we don't break this again.
Feedback is being sent again:
Interstitials get filtered out:

Fix feed feedback

---

src/state/shell/progress-guide.tsx

The details of this thing are goofy, but here's the sitch:
- We maintain the progress guide's canonical state in prefs where it's persisted.
- We also maintain a local copy of the active guide state. That local copy is what's used in the UI.
- The reason we do this is because when the guide is complete, the two states need to diverge.
- Persisted state needs to be cleared out. It doesn't _need_ to be, but it's much better if we don't accumulate dead state for no reason.
- Local state needs to keep the guide object with `isCompleted=true` so that the UI continues to render in the completed state.
Local state needs to correctly hydrate from persisted state upon init, so we have to read the persisted state into it. After that, the local state can operate pretty much independently. The trick …

Fix responsiveness of dismissing the progress guide

---

src/view/com/notifications/Feed.tsx
src/view/com/util/List.web.tsx

Currently, if the tail intersection observer is intersecting, and then we fetch more items but not enough to push it offscreen, we won't get another `onEndReached` event (because we only fire `onEndReached` when the intersection status _changes_ but in this case it's `true` -> `true`). We need to retrigger `onEndReached` if it's _still_ intersecting after fetch.
Add `key={data.length}` to the intersection observer at the tail. This remounts it if the number of items changes, so it re-executes the intersection callback if it's still close to the viewport.
You can set the `onEndReachedThreshold` inside of `src/view/com/notifications/Feed.tsx` to some big number like 10, and see that we end up making a few calls for notifications as soon as we load the page. The behavior when the height is …

Fix `onEndReached` not firing sometimes on web

---

src/view/shell/createNativeStackNavigatorWithAuth.tsx

Same logic, but we're checking `gate()` only when it's actually gonna change the outcome.
Careful inspection. It's just a bunch of booleans. (Famous last words)
Also try logging out.

Fix order of checks in experiment

---

src/components/FeedInterstitials.tsx
src/state/queries/post-feed.ts
src/state/queries/post.ts
src/state/queries/profile.ts
src/state/userActionHistory.ts
src/view/com/posts/Feed.tsx

Keeps an in-memory store of liked posts, followed users, and post URIs seen on the Discover feed. This is only used in memory and is not stored or transmit anywhere.
This data is then used to grab up to 16 profiles, which are then filtered for any users already followed by the acting user. Up to 6 are then shown to the user as suggestions for others to follow.

[D1X] Use user action and viewing history to inform suggested follows

---

src/view/com/posts/AviFollowButton.tsx

It's really hard to press the follow button on avatars. That is because Zeego/RN iOS context menu is not actually applying any hit slop at all. The slop around our button has no affect on the hit slop, as it needs to be explicitly the content area of the `Dropdown.Trigger` that opens the menu - not the button wrapping it.
Placing a button _inside_ the trigger and adding a hit slop to that _also_ does not work for the same reason. The pressable area will _only_ be the area of the content, not the extended hit slop area.
Instead, we can use some additional `View`s with transparent background to increase the size of the `Dropdown.Trigger`, making it a lot easier to press.
See how this feels on a device mainly. On a simulator it's much easier to tap now - you can tap a little outside the …

Fix hit slop for profile avi follow button

---

src/screens/StarterPack/StarterPackScreen.tsx

@cdfzo pointed out in a [review comment](https://github.com/bluesky-social/social-app/pull/4742/files#r1667428796) that there's a missing `to` in the string that the user is shown when they're deleting a starter pack. This PR adds it.

Add missing `to` in StarterPackScreen.tsx string

---

src/lib/strings/url-helpers.ts
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

**[without whitespace](https://github.com/bluesky-social/social-app/pull/4745/files?w=1)**
Links that lead to `/start` should just navigate to `/starter-pack` when clicking them within the app. Although the current behavior is generally fine, it is possible to trigger this crash with the current behavior:
`<RNSNavigationController: 0x111824200> is pushing the same view controller instance (<RNSScreen: 0x159982600>) more than once which is not supported and is most likely an error in the application : xyz.blueskyweb.app`. It seems to only affect iOS users as well.
Whenever we call `convertBskyAppUrlIfNeeded()`, we can add a check to replace `/start/` with `/starter-pack/` if the link is indeed pointing toward `/start/`. While this is generally not needed after …

Ensure `/start` navigates to `/starter-pack` when clicking a link internally

---

src/screens/StarterPack/StarterPackLandingScreen.tsx

https://github.com/bluesky-social/social-app/assets/91714073/5b0f60a0-1654-4e8f-8596-fbe400093e67
This back button shouldn't be here. This button isn't programmed to go back, but instead updates "setActiveStarterPack(undefined)". Which causes a permanent 'processing' state.
However, this button causes an infinite loading spin and sucks for new users, especially for mobile users. Also, Because it's the same URL, browsers do not go back, my immediate instinct upon getting this infinite spin was to go back a page, but instead it will send the user to a new tab or what they were looking at, so they'd need to go back to their chat app (or whatever) and re-click the link. Horrifically bad for new user sign-ups. Because of browser caching, going back and forward (at least in FireFox) will …

Remove broken and void back button

---

src/components/StarterPack/QrCode.tsx

Fixes https://github.com/bluesky-social/social-app/issues/4740
Some of the generated QR codes cannot be scanned if the logo is too big - presumably certain combinations of data have pieces that end up underneath the logo.
For example, see:
- https://bsky.app/starter-pack/esb.lol/3kvuiptvhkx2y
- https://bsky.app/starter-pack/pfrazee.com/3kvaphb2hpf2u
- https://bsky.app/starter-pack/joshuajfriedman.com/3kvuh7u324m2c
- https://bsky.app/starter-pack/rudyfraser.com/3kvubqmzzi32t
These QR codes can indeed be scanned just fine. However, see these starter packs:
- https://bsky.app/starter-pack/pfrazee.com/3kvaqmutnga2z
- https://bsky.app/starter-pack/did:plc:fb3iwxg23jziddgbtsixx3zu/3kwjfvvlve32g
These ones cannot be scanned.
If we change the `scale` of the logo to `1` instead of `1.2`, then all …

Reduce the size of the inner logo in the QR code

---

src/components/ProfileCard.tsx
src/components/ProfileHoverCard/index.web.tsx
src/components/StarterPack/Wizard/WizardListCard.tsx
src/components/dms/MessagesListHeader.tsx
src/components/dms/dialogs/SearchablePeopleList.tsx
src/lib/strings/constants.ts
src/screens/Profile/Header/DisplayName.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/util/PostMeta.tsx
src/view/screens/Settings/index.tsx
src/view/shell/desktop/Search.tsx

Right now it's pretty rough on web and Android (iOS handles it pretty well for some reason). After getting https://github.com/bluesky-social/social-app/pull/4531 merged in, felt like a good time to hit these.
Using `alignSelf: 'flex-start'` in the `Text` styles whenever rendering the display name keeps the text aligned properly.
I'm probably forgetting somewhere that we render the display name, but I tried to find them all with a search for `sanitizeDisplayName(`
|--------|--------|
| <img width="420" alt="Screenshot 2024-07-07 at 3 28 13 PM" src="https://github.com/bluesky-social/social-app/assets/153161762/d0b4b6d8-cc7c-41e1-b5a1-12cba14b9c43"> | <img width="407" alt="Screenshot 2024-07-07 at 3 28 33 PM" src="https://github.com/bluesky-social/social-app/assets/15316176 …

Fix RTL text rendering for display names

---

src/screens/Messages/Conversation/MessagesList.tsx
src/screens/StarterPack/Wizard/StepFeeds.tsx
src/screens/StarterPack/Wizard/StepProfiles.tsx
src/view/com/util/List.tsx
src/view/com/util/List.web.tsx
src/view/screens/Storybook/ListContained.tsx

We've ran into another weird quirk when using `content-visiblity`. Scroll views often don't resize whenever new items get added to the list, which is causing problems with `onEndReached` in the web implementation of `FlatList`. We're switching to `contain: layout paint` instead.
When opening the notifications tab on a large monitor, there shouldn't be chained requests for notifications.

change `contentVisibility` to `contain`

---

src/state/session/agent.ts
src/state/session/logging.ts

Adds a log when an agent emits an event (`update`, `expired`, and a few others). We want to get a baseline on how much expiration is occurring in practice, and we want to be able to target that with experiment fixes.
Force early expiration using the short session debug header, verify it results in sending this event.

Log session events unconditionally

---

src/state/session/agent.ts
src/state/session/logging.ts

Follow-up to https://github.com/bluesky-social/social-app/pull/4758. Turns out there's just a _lot_ of `update` events so it makes hard to notice problems. Let's filter out expected successful events and focus on the failures.
On `session-stress` branch, I still see this:
Also manual inspection.

Rename session event, scope to errors

---

src/components/ReportDialog/SubmitView.tsx
src/components/moderation/LabelsOnMeDialog.tsx
src/lib/statsig/gates.ts
src/state/feed-feedback.tsx

There's a theory that some of the logouts may be due to a bug in how `withProxy` interacts with the expiry logic (a cloned agent may expire and fork the token). I'm adding a gate that forks the logic to not use `withProxy`. We _could_ do this without the gate (the behavior should be equivalent) but I want to see if this actually reduces the number of `expired` events or not.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/4762/files?w=1)
This is basically what `withProxy` does at the lower level:
https://github.com/bluesky-social/atproto/blob/7761a463b221717e5923dff77b1cc4c3755f3fd7/packages/api/src/agent.ts#L95-L99
which means this:
https://github.com/bluesky-social/atproto/blob/7761a463b221717e5923dff77b1cc4c3755f3fd7/packages/api/src/agent.ts#L128-L133 …

[Session] Experiment: Don't use withProxy

---

src/state/session/logging.ts

Seems useful to have it, maybe even if it's minified, it'll retain the Bsky agent method names?
Tried on web, on iOS and Android on top of the `session-stress` branch. The stack is unfortunately not good on native due to the async/await transform that Hermes requires (which causes `await` continuations to get anonymous names).
But the web one seems good. It's fine if we at least get these for web.

[Session] Include stack with the debug event

---

src/view/com/composer/GifAltText.tsx
src/view/com/util/post-embeds/GifEmbed.tsx

We changed `maxWidth` to `width` in #4717. This works fine everywhere except in the ALT dialog, where we want to adjust the styles a bit.
The easiest way to always allow us to make changes to how this looks is by making `style` a prop we can adjust from outside the `GifView` component. The default of `width: '100%'` works for pretty much every case except these edges.
Check the GIF alt dialog on all platforms. Also check that DMing a post with a GIF in it works fine and doesn't regress after #4717.

Fix alt text for GIFs

---

src/screens/Hashtag.tsx

Unexpected and totally reasonable thing that broke in #4531 — `forceLTR` is adding characters to the string and borking the search query. We weren't doing anything special before so let's just go back to that here.

Fix search hashtags by author

---

modules/expo-bluesky-swiss-army/src/Referrer/index.web.ts

Forgot to actually return a promise here. We use a promise because that matches the way it works on native.
The app will actually load now (main.bsky.dev ftw, thanks @mary-ext for catching it really fast! ❤️)

Return a promise for `getReferrerInfoAsync` on web

---

modules/expo-bluesky-swiss-army/android/src/main/java/expo/modules/blueskyswissarmy/referrer/ExpoBlueskyReferrerModule.kt
modules/expo-bluesky-swiss-army/src/Referrer/index.android.ts
modules/expo-bluesky-swiss-army/src/Referrer/index.ios.ts
modules/expo-bluesky-swiss-army/src/Referrer/index.ts
modules/expo-bluesky-swiss-army/src/Referrer/index.web.ts
src/Navigation.tsx
src/lib/hooks/useIntentHandler.ts

We wanted to make this sync, but in some merges there were some mixups. This corrects those.

Make all referrer info sync

---

src/lib/constants.ts
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/state/queries/labeler.ts

Users who have subscribed to labelers who have subsequently shut down (or were taken down) cannot unsubscribe from them. Those values are stuck in their prefs. If the user is at the labeler limit, they also can't subscribe to new labelers.
Since these are user prefs and live on the PDS, and because we don't validate this endpoint, we can't very well do this on the server. So we need to do it here.
This PR checks for any invalid labelers and removes them every time a user subscribes or unsubscribes to a labeler. When subscribing, if the user is still at the limit after labeler validation, we throw an error and handle it by showing the informational dialog.
Note: this also means that the button to Subscribe to a labeler remains active, **even if the user might be at the limit already.**

Remove invalid labelers when subscribing/unsubscribing

---

src/components/forms/Toggle.tsx

After we changed all the border widths to hairline, the switch component broke, since the size of the container was expecting the border to be 1px. Setting the height to `20 + hairlineWidth * 2` fixes it
While I'm here, I added a layout animation, made it slightly wider, and made it use flexbox instead of absolute positioning
Before
After

Fix switch style and animate

---

src/lib/statsig/gates.ts
src/view/com/util/UserAvatar.tsx

We now have smaller AVI thumbnails being served. We will eventually update our lexicons, or just the server responses, to give the new smaller AVI-thumb paths. For now, we're manually modifying the path.
Note: behind the `small_avi_thumb` gate so that we can roll this out progressively, since this change will result in a bunch of CDN cache misses and we need to control its rollout.

Hack-modify avi path to use smaller thumbs behind gate

---

src/view/com/posts/FeedSlice.tsx

This doesn't actually change anything in practice (at least right now) but it fixes an inconsistency in which item we're reading the index from. This inconsistency by itself is definitely possible:
The reason it didn't matter (despite wrong prop values) is that `showReplyTo` is `false` for this branch. It's still worth fixing though.
Visual inspection. Self-threads still show like before:

Use consistent index for reading last item

---

src/state/queries/notifications/settings.ts

`listNotifications` has a special cache for the first page, which needs to be separately invalidated

Priority notifications - use special invalidation logic

---

src/screens/Messages/Settings.tsx
src/view/screens/NotificationsSettings.tsx

Just using `CenteredView` on native causes some screens - like DM settings - to not allow the user to view all the options if they are using font scaling. Make them scrollviews instead.
Test that the views are the same, just scrollable now.

make some settings screens scrollable for accessibility

---

src/state/queries/post-feed.ts
src/state/queries/threadgate.ts
src/view/com/posts/FeedItem.tsx
src/view/screens/Search/Explore.tsx

We were using this `as Foo[]` pattern which is not good. I got bit by this in my ongoing feed slice refactor because the types were lyring. I'm using [this approach](https://stackoverflow.com/questions/47632622/typescript-and-filter-boolean#comment93284037_47636222) to get them typed more strongly. It requires extracting variables instead of early returns and some manual annotations, but these actually _do_ get checked.
This surfaced some violations. They're not actually breaking the logic. These two are trivial:
- https://github.com/bluesky-social/social-app/commit/16c714a4ba64da90cff696b742691fa9f0e7d1d6
- https://github.com/bluesky-social/social-app/commit/d3189d3fe27819a82046c6079e4f0b2875150584
This one is more involved:
- https://github.com/bluesky-social/social-app/commit/f3caf3e921 …

Fix sloppy filter(Boolean) types

---

src/lib/api/feed-manip.ts
src/lib/api/feed/merge.ts
src/state/queries/post-feed.ts

I'm refactoring feed slicing. This refactor should fully preserve the existing behavior but it makes strategic code changes that will prepare us for the next PR https://github.com/bluesky-social/social-app/pull/4835, which solves longstanding problems with how replies show up in the feed.
The best way to follow along, unfortunately, is to read commit-by-commit. Each change is meant to be atomic and safe (mostly manipulation). The main theme of this refactor is to decouple the shape of a "slice item" from `FeedPostView` so that https://github.com/bluesky-social/social-app/pull/4835 can construct it on-the-fly from parent and root with correct information. I'm tucking away low-level access of `slices[i].items.reply` and similar fields into the `slice` API itself so that I can later change …

Refactor feed slices

---

src/view/com/notifications/FeedItem.tsx
src/view/com/util/UserAvatar.tsx

There were two parts to this:
- disabling accessibility on the avi wasn't actually necessary bc of the accessible `Link` that wraps this context
- the `Link` didn't have a label, so VoiceOver was looking for content within to read out
The main improvement here is just to construct a custom `a11yLabel` for VoiceOver to read out when the outer `Link` is focused. Once expanded, each `Link` is in-turn focusable, and reads out correctly. I also applied the `a11yLabel` to the inner text so it reads nicely too.
We could further improve this by reading out "56 min ago" instead of the full date, but we don't have facilities in the codebase for this exact use case right now.
https://github.com/user-attachments/assets/b0211364-e0a2-4a85-89dd-9ee875c761aa

[LinkLab] Improve a11y on noty feed

---

src/view/com/util/List.web.tsx

We want to ensure that when you scroll to bottom and the next fetch yielded too few new items, we're triggering a refetch on the web. With https://github.com/bluesky-social/social-app/pull/4728, we've made it work by putting a `key` on the tail intersection observer so that it gets recomputed (and thus retriggers if the tail is _still_ in the viewport) when the number of items in the list changes.
However, the current behavior is still inconsistent with the native side. In particular, on native, it appears that having _the same number of rows but with different content for the footer_ (such as [here](https://github.com/bluesky-social/social-app/blob/c75bb65bef1671e493f10e06b51ee4d0cda98d83/src/view/com/posts/Feed.tsx#L511-L520)) also triggers `onEndReached`. Looking closer at the native …

[Web] Retrigger onEndReached if needed when content height changes

---

src/view/com/notifications/FeedItem.tsx

Right now, we will show the user "followed you back" in a follow notification if you follow the user. There's no other logic that checks if the follow occurred before or after you followed that person.
This means that if I follow you, then you follow me, your notification showing that I followed you will say "followed you back", even though I actually followed you first.
Let's compare the rkey's timestamp with the new record's timestamp.
See video
https://github.com/user-attachments/assets/f1961bfd-8169-44e3-9125-c154b8561bd8

Only show "followed you back" when appropriate

---

src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts

We have a hack that fetches enough items to fill the first page's worth of items (30) if we're not getting enough items within the first few pages (6). This hack isn't reliable and doesn't handle similar cases further down the scroll (e.g. when there's an empty `[]` response in for further pages, or when too many items get filtered out later).
I'm adding a more extensive fix that should handle these cases consistently. The idea of the fix is to keep track of the "wanted" item count. When we start paginating, we bump the "wanted" item count by the page size (30). If we then don't receive enough items, we keep trying to paginate until those 30 items are filled. There are a few conditions where we reset that counter.
This mostly acts as a failsafe. In practice `FlatList` content size change …

Fetch enough pages to fill a page's worth of items

---

src/view/com/posts/FeedSlice.tsx

Extracted from https://github.com/bluesky-social/social-app/pull/4835. When we start showing replies in the context of the threads they're in, they'll follow the same structure. So this makes a similar change for the case where we already display the context.
Overall I think this makes the slice feel more coherent. OP post sets the context for the thread, and the last two posts are an unbroken chain. As opposed to how it behaves now where the last post can be pretty far disconnected from the initial point.

Display second-to-last rather than second post in a slice

---

src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/screens/PostLikedBy.tsx
src/view/screens/PostRepostedBy.tsx
src/view/screens/ProfileFeedLikedBy.tsx

Bringing these screens in line with how Follows/Following lists work. These never got updated to new list components and adding perf optimizations, so here we go.
Essentially the same as Follows/Following. Simple stuff.
- Proper loading state in between push and load
- List works correctly
- Doesn't show a spinner when the end is reached

Fix missing header on Likes/Reposted By, add missing perf optimizations

---

src/lib/api/feed-manip.ts
src/state/preferences/feed-tuners.tsx
src/state/queries/preferences/const.ts
src/view/screens/PreferencesFollowingFeed.tsx

This removes the granular reply settings in favor of the current defaults. Only replies *between people you already follow* will be displayed in the Following timeline. (This is already the current default, and has been for many months — but this change applies it retroactively for people who might have changed this setting before the "followed only" filter existed.)
I'm also removing the like-based filter. The original purpose of the global like-based filter for replies in the Following feed was to avoid a flurry of replies overwhelming it. However, that was mostly necessary because there was no filtering by whether you follow both people in the exchange. Now that we have that filtering (and have had it as a default for many months), the like-based filter seems much less useful. It's …

Always limit Following replies to the people you follow

---

src/lib/api/feed-manip.ts

This fixes conditions where we erroneously show replies in Following where you don't follow somebody in the conversation. Unfortunately this is not a 100% solution because it only checks the following actors:
- The reply author
- The parent author
- The grandparent author
- (...But not the intermediate ones...)
- The root author
However, this catches most cases where it matters and fixes the issue where a reply chain from somebody you follow _in an unrelated account's thread_ ends up in your Following feed. Simply filtering by thread OP is already doing a lot.
The new logic is simpler than before. We simply check that all of the actors above are either you or someone you follow. That's it. If even one of them is someone you don't follow (and someone who isn't you), we omit that reply. …

Only show replies in Following if following all involved actors

---

src/components/Lists.tsx

Tweak desktop list header - it now matches the size of the notifications header

Tweak desktop list header

---

bskyweb/cmd/bskyweb/main.go
bskyweb/cmd/bskyweb/server.go

If this env var is configured, the golang web service will require HTTP Basic auth for access to the web interface.
Tested locally and this seems to work and not conflict with actual service auth. Not sure that will remain true in the future with OAuth, etc.
Not enabled by default, so should not impact prod deployment.

bskyweb: optional basic auth password middleware

---

jest/jestSetup.js
modules/expo-bluesky-swiss-army/android/src/main/java/expo/modules/blueskyswissarmy/platforminfo/ExpoPlatformInfoModule.kt
modules/expo-bluesky-swiss-army/expo-module.config.json
modules/expo-bluesky-swiss-army/index.ts
modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.native.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.web.ts
patches/react-native-reanimated+3.11.0.patch
src/platform/detection.ts
src/state/a11y.tsx
src/state/persisted/schema.ts
src/view/screens/Storybook/Dialogs.tsx

There's some various platform preferences we need from time to time (such as currently reduced motion preferences, or later font scale preferences, wifi status, etc). This is a little module that lets us grab values like that.
There's a patch for Reanimated we are using right now to get this value, though every time we change our Reanimated version we have to update the patch. It would be nice to get rid of that as well.
I've added a button to the story book that you can get grabbing this value on various platforms with.
https://github.com/user-attachments/assets/9cf5521f-7325-448b-9e90-27a3fee5c67d
https://github.com/user-attachments/assets/7d10405a-6f41-4bf3-848f-11dd4041fb28
https://github.com/user-attachments/assets/d1a42cea-2f20-4f82-8b6b-9a67cff6ac4c

Add `PlatformInfo` module

---

src/state/persisted/index.ts
src/state/persisted/index.web.ts
src/state/persisted/schema.ts

Stacked on #4872.
This removes defensive programming in the original code, extracts some shared logic between platforms, and fixes a race condition that caused potential clobbered concurrent writes between tabs. I recommend to review commit by commit:
- https://github.com/bluesky-social/social-app/commit/2e70c0c95ba8d47dcca6c95d6206517d349375c8: This removes the `setTimeout(..., 0)` around the `broadcast.postMessage` call. I believe its premise is incorrect. The premise of this wrapper is that the other tab might read stale data because the broadcast message can arrive before the local storage update is flushed. I find this difficult to believe given that the `localStorage` contract on the web is synchronous while `postMessage` is _definitely_ asynchronous and definitely can lag behind …

[Persisted] Fix the race condition causing clobbered writes between tabs

---

src/state/invites.tsx
src/state/persisted/index.ts
src/state/persisted/index.web.ts
src/state/persisted/types.ts
src/state/preferences/alt-text-required.tsx
src/state/preferences/autoplay.tsx
src/state/preferences/disable-haptics.tsx
src/state/preferences/external-embeds-prefs.tsx
src/state/preferences/hidden-posts.tsx
src/state/preferences/in-app-browser.tsx
src/state/preferences/kawaii.tsx
src/state/preferences/languages.tsx
src/state/preferences/large-alt-badge.tsx
src/state/preferences/used-starter-packs.tsx
src/state/session/index.tsx
src/state/shell/color-mode.tsx
src/state/shell/onboarding.tsx

Stacked on https://github.com/bluesky-social/social-app/pull/4872 and https://github.com/bluesky-social/social-app/pull/4873.
This optimizes cross-tab communication in a few ways.
- https://github.com/bluesky-social/social-app/commit/061fcef6f908189ddb4b7c0ac3fd020767f200c2: Don't broadcast if nothing has changed. This fixes a new tab always sending a broadcast. (There are ways to fix it at the callsite but it's a bit annoying to think about. This should be cheap enough since we don't write often.)
- https://github.com/bluesky-social/social-app/commit/8fb0ea21a4f3bbae04fc1ba43e2d7d77d2b81494: Tweaks the `onPersisted` API to include a key. This will let us subscribe granularly and avoid setting state on every provider when syncing persisted state. This commit does not actually enable …

[Persisted] Make broadcast subscriptions granular by key

---

src/lib/api/feed-manip.ts

Alternative to the heuristic https://github.com/bluesky-social/social-app/pull/4871 based on community feedback.
This fixes the double-reply loophole and actually _opens up_ the default Following heuristic to be a bit more broad than the current default one on the website. We'd include not only replies _between_ people you follow (which is the current default), but _also_ replies where you follow only the replier and the thread OP, _or_ only the replier and the grandparent. In other words, we'd show the reply if there's *at least one other person* you'd recognize looking at the context above that reply.
In practice this means you'd see banter where you don't follow _some_ people as long as there's _one more reason_ to display them (e.g. you follow the OP, the parent, or the grandparent). …

RFC: Show more replies in Following (different heuristic)

---

src/state/queries/post-thread.ts
src/view/com/post-thread/PostThread.tsx

We currently put OP replies first, then people you follow (for an option that's true by default), then other replies. However, we're not doing anything with _your own_ replies which [makes them a bit hard to find](https://bsky.app/profile/citizenkate.bsky.social/post/3kz2qmt5eac2k) in bigger threads.
This tweaks the heuristic so that your own replies go right after the OP (but above your follows).
Reply to a thread, see your reply below the OP.
https://github.com/user-attachments/assets/794c7262-4bc4-474b-9602-dabc0c4f507b

Show own replies before follows' replies in threads

---

src/lib/api/feed-manip.ts

Fixes where situations like `[A] -> [B]` wouldn't show up, since we were returning false if `grandparentAuthor` was `null`.

Tweak feed manip to show cases of A -> B without further children

---

src/lib/statsig/events.ts
src/view/screens/Home.tsx

We want to do a little logging to ensure we don't have a bug in following feed preferences. There have been some reports that maybe it isn't working correctly, so let's test it out and see.
We sample the feed displayed event now, so for the time being while we start debugging this, let's change that to always log these displays instead of sampling them.
Whenever opening the app and displaying the following feed, we should be sending `feedDisplayed` events now instead of `feedDisplayed:sampled`. However, for all other feeds, we should still be using `feedDisplayed:sampled`.
There should also be two additional fields in the metadata now, showing what the preference is and how many likes are needed to actually display a reply in the following feed.

Add logging of selected feed preference when displaying the following feed

---

src/components/FeedInterstitials.tsx

This just teaches the interstitial to prioritize it above the topical source.
Test you're hitting the breakpoint. Interstitial should start feeling a bit more relevant.

Include popcluster in suggestion ranking

---

src/view/com/posts/Feed.tsx

Refreshing Discover doesn't currently refresh the interstitial. This updates the content by keying it by first page's fetch time.
Scroll down.
Press Discover again to refresh. Scroll down again.
Observe different order/people:

Keep interstitial fresh on refresh

---

src/components/FeedInterstitials.tsx
src/state/queries/profile.ts
src/state/userActionHistory.ts

This incorporates a signal: if you follow someone, we'll show their "suggested by actor" results next time you see the interstitial during this session.
Verify people from the endpoint show up in the suggestions after next Discover refresh.
Note the result is better under the new gate, but the logic should work either way.
https://github.com/user-attachments/assets/9e54a659-7a67-4297-8505-5c35a196f508

Use the suggested actors in the follow suggestion interstitial after a follow

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadComposePrompt.tsx
src/view/screens/PostThread.tsx

Similar in spirit to https://github.com/bluesky-social/social-app/pull/4897.
The parent screen component doesn't really "know" about the inner state so we had to read the thread from the cache. This is a bit convoluted cause the thread is "right there" in the child component. The only reason we did it was because the mobile prompt used to be at the parent component level. We've moved it to the child, letting us move the handler too.
I've also renamed `ComposePrompt` and moved the file to make it clearer it's only used in post-thread.
Verify can still post via the mobile prompt. Verify it hits the `refetch` breakpoint when needed. New post shows up below.
https://github.com/user-attachments/assets/c8a92f74-dbe6-4417-8d8c-9fc138607c4a

Move onPressReply into child component

---

modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.native.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.web.ts

When there is an active `AVPlayer`, it seems like background audio gets paused on app open. The solution here is to set the `AVAudioSession`'s `CategoryOptions` to `.mixWithOthers`.
```
// When about to play a video, i.e. when going into fullscreen or watching a YouTube video
PlatformInfo.mixWithOthers(true)
// After exiting full screen or on app start
PlatformInfo.mixwithOthers(false)
```
Merge this, then add code where needed.

[Videos] Add iOS function to set `AVAudioSession.CategoryOptions` to `.mixWithOthers`

---

modules/expo-bluesky-swiss-army/index.ts
modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.native.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.web.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/types.ts
src/App.native.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Upon doing some documentation digging, it looks like we might actually want to be tweaking the category itself from `ambient` to `playback` depending on what state we are in.
First, it looks like we want to take our app out of the _default_ state, which is `soloAmbient`. This is described as
> Your audio is silenced by screen locking and by the Silent switch (called the Ring/Silent switch on iPhone).
>
> By default, using this category implies that your app’s audio is nonmixable—activating your session will interrupt any other audio sessions which are also nonmixable. To allow mixing, use the `ambient` category instead.
(https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616488-soloambient)
And the `ambient` category is described as
> This category is also …

[Video] More tweaks to `AVAudioSession` options

---

src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoFallback.tsx

Copies over error boundary logic and turns web UI into a reusable component

[Videos] Add error boundary to native

---

modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.native.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.ts
modules/expo-bluesky-swiss-army/src/PlatformInfo/index.web.ts
src/App.native.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

We want the background audio to properly resume once we either mute the video audio or exit fullscreen. Let's do that.
See https://developer.apple.com/documentation/avfaudio/avaudiosession/setactiveoptions/1616603-notifyothersondeactivation
Merge, build, test.

[Video] Resume background audio whenever muting video audio

---

src/view/com/composer/videos/VideoTranscodeProgress.tsx

This PR marks the `Compressing...` string in `src/view/com/composer/videos/VideoTranscodeProgress.tsx` for localization.

Mark string for localization

---

src/view/screens/Search/Search.tsx

The profile view in "recent searches" used to not show a label if the user didn't have a display name set:
Also, when the name was truncated, the existing implementation was supposed to add "...", but the way it was implemented, the ellipsis often spilled onto a second line that overflowed and didn't render. This change switches the label to use the built-in ellipsis truncation behavior.

Show handle in recent searches and fix truncation

---

src/view/com/composer/text-input/TextInput.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2703
It seems that we were using a `setTimeout()` hack in the `onChangeText` handler. This appears to have been previously necessary back in `@mattermost/react-native-paste-input@0.6.0`, and there were quite a few issues and "fixes" that came out of it. See https://github.com/bluesky-social/social-app/issues/929 which added this `setTimeout()`.
However, this timeout is actually causing problems on Android when composing posts. The cursor will frequently "move back" a space whenever the user is typing fast. After removing this timeout, I can't repro the behavior anymore. I also cannot reproduce the behavior that's noted about the wrong elements being painted. Maybe @estrattonbailey has more context on something I might be missing. …

Fix Android composer cursor bug by removing `setTimeout` from native composer `onChangeText`

---

src/App.native.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Typo, should have been the other way around for `true`/`false`

[Video] Invert usage of `setAudioActive`

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

More tweaks to come here, but we shouldn't try to access `player` inside of a cleanup function.

[Video] Fix crash when switching tabs

---

modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift

Seems that iOS doesn't like modifying the `AVAudioSession` on the main thread - this causes some lag. Let's run it on a background thread instead.

[Video] Audio duck off main thread

---

src/components/ReportDialog/SubmitView.tsx
src/components/moderation/LabelsOnMeDialog.tsx
src/lib/statsig/gates.ts
src/state/feed-feedback.tsx

We accidentally broke them by subclassing the agent. Could remove the subclass but also we might as well remove this gate (it had no meaningful impact on session events so must've been equivalent).

Remove .withProxy() calls

---

src/lib/react-query.tsx
src/state/events.ts
src/state/queries/feed.ts
src/state/session/__tests__/session-test.ts
src/state/session/agent.ts
src/state/session/reducer.ts

With this fix, we will no longer kick you to the login screen when the agent emits a `network-error` event. The original motivation for kicking you to the login screen was twofold:
- The agent was losing the `.session` field so it literally couldn't continue, and we wanted to mirror that in app state.
- The app did not have a reliable way to track when the network comes back online on native, so requests would get stuck.
We're fixing this by:
- Putting the `.session` field back on the agent after a `network-error` event. (We should maybe fix this upstream?)
- Adding a mechanism to track whether the app is online that works across platforms.
Regarding the mechanism. I tried initially to use different network libraries. But it seemed pretty unreliable — for example, on the Android simulator …

Don't kick to login screen on network error

---

__tests__/lib/string.test.ts
src/lib/strings/embed-player.ts

YouTube has a new `/live/` URL. Let's add it.
Works the same as other YouTube embeds (particularly the same as `/short/`
Embed this video: https://www.youtube.com/live/RpNW_UxRN3s
Note that you won't be able to load the player (because of CORS).

Add `/live/` to supported YouTube embed URLs

---

modules/expo-bluesky-swiss-army/ios/PlatformInfo/ExpoPlatformInfoModule.swift
src/view/com/composer/videos/VideoPreview.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
src/view/com/util/post-embeds/VideoPlayerContext.tsx

Audio category could get out of sync with the player if you switch video

[Video] set audio category to ambient every time a new player is made

---

src/App.native.tsx
src/App.web.tsx
src/components/moderation/ModerationDetailsDialog.tsx
src/lib/moderation/useModerationCauseDescription.ts
src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/state/queries/threadgate/index.ts
src/state/threadgate-hidden-replies.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/screens/DebugMod.tsx

[Review w/o whitespace](https://github.com/bluesky-social/social-app/pull/4933/files?diff=split&w=1). Can ignore the CI failures, I'll fix on the main branch.
This PR adds the ability to hide a reply directly from a feed generator as well as from the notifications feed. To do so, it adds an in-memory cache of replies that were hidden, and uses that array to filter out those replies from feed generators and notifications feed.
So what happens here is: when the user hides a reply, then the in-memory cache and threadgate record are updated with that URI. Then when navigating to other screens where this reply may be present, the reply is filtered on the client. Upon a full reload, the server strips out the reply, and the in-memory cache is reset.
For feed items, we're able to hydrate the …

Hidden reply cache

---

patches/expo-modules-core+1.12.11.patch

There's a crash that's happening when `reloadAsync()` gets called by `expo-updates`. This is coming from attempting to destructure a null pointer, whenever removing all of the `SharedObject`s in `SharedObjectRegistry.clear()`.
A little digging shows that the `deinit` block of `VideoPlayer` runs _after_ `clear()` get's called. However, right now `clear()` calls `dict.removeAll()` _asynchronously_ inside of a separate queue from the main one. This is a small test to see if this helps to alievate the crashes. I don't consider this a production fix.
Merge, let it build, and monitor for OTA crashes as we have been internally.

Hack patch for testing OTA update crash behavior

---

src/lib/hooks/useMinimalShellTransform.ts
src/lib/statsig/gates.ts
src/view/screens/Home.tsx

This is where your DMs and notifications are. Let's experiment with always keeping it visible.
No changes outside the gate.
With the gate:
https://github.com/user-attachments/assets/90d2974b-a151-4e68-916d-493baa0e7c87
https://github.com/user-attachments/assets/9e8096f6-ac33-40ba-b699-3a9888abc921
https://github.com/user-attachments/assets/49818daf-b849-46eb-9f60-6b2719e9f05e

[Experiment] Always show bottom bar

---

patches/expo-modules-core+1.12.11.patch

Per expo recommendation in https://bluesky-builders.slack.com/archives/C05R8KJK1PC/p1723836730258259, tweaking the patch added in https://github.com/bluesky-social/social-app/pull/4942.

Tweak `expo-modules-core` hack patch

---

src/lib/api/feed-manip.ts
src/state/preferences/feed-tuners.tsx
src/state/queries/post-feed.ts
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx

Fixes a regression in #4871 where `A -> B -> C` and `A` blocks `B`, we'd see the entire `A -> B -> C` thread, whereas the intention was to filter out those "orphaned" threads. If we want to show orphaned threads, it's a one-line change in `feed-tuners`.
Test the scenarios below using the backend PR. Otherwise test prod, nothing should look different using prod data. Only the backend PR sends down data needed to compute the correct view.
See in prod, thread is orphaned (and technically "Reply to test.esb.lol" should say "Reply to blocked post")
In main, you can see through the 3p blocks:
In this PR, `C` only sees `A` because the thread view would otherwise be "orphaned"
In all cases the entire feed slice is filtered out 👍 
In all cases, only `A` is visible 👍 
In case of `B` deleting their …

Fix orphaned feed slices, handle blocks

---

src/components/Menu/context.tsx
src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/components/Menu/types.ts

Extracted from #4878
Ensures `onPressIn/Out` works on items, and improves support for `disabled` on items.

Expose more methods, support disabled items

---

src/components/moderation/Hider.tsx
src/view/screens/ProfileList.tsx

Adds generic `Hider` component for use anywhere e.g.
- `ProfileList` entire screen
- list title on `Moderation > Lists` list of lists
Provides access to the result of `useModerationCauseDescription` and prepackages the `ModerationDetailsDialog`.
For lists right now we don't need to handle any other labels, so no need to have an override button for the moment.

Add Hider component

---

package.json
src/state/queries/postgate/util.ts
src/state/queries/util.ts
yarn.lock

Was missing the `quoteCount` for `EmbedView` previously. Bumping the API and adding this to our little view creator helpers, which helps with caching and layout smoothness.
Tap into a quote and the quote count should be immediately available, there shouldn't be any layout jank. (Pending appview deploy)

add `quoteCount` to view creators

---

src/state/queries/list-members.ts
src/state/queries/post-thread.ts

Adding a cache check to `usePostThreadQuery` so there is no spinner when going from list of quotes -> post thread.
https://github.com/user-attachments/assets/509bae99-f281-422c-bde3-6bf76e746dc4

update `usePostThreadQuery` to check quote query data

---

src/components/hooks/useThrottledValue.ts
src/screens/Signup/StepCaptcha/index.tsx
src/screens/Signup/StepHandle.tsx
src/screens/Signup/index.tsx
src/screens/Signup/state.ts

The closure was reading a stale value of `state` because it has not been updated by this point yet. To fix this, we need to let the reducer run first. Then in an effect we can run the `signup` function with fresh state.
## Test Plan
Go through the registration flow, confirm can still go through the captcha step.
Confirm that in local dev environment, the handle no longer is reported as invalid on first attempt.

Submit fix

---

package.json

New dev env requires https unless the node env is `development`.

have mock server run with `development` node env

---

src/lib/hooks/useMinimalShellTransform.ts
src/state/shell/minimal-mode.tsx
src/view/com/util/MainScrollProvider.tsx
src/view/screens/Home.tsx

Haven't tested this very deeply but I think this should fix the `fixed_bottom_bar` experiment.
It takes an alternate approach to what I had before. The idea is to split the `mode` variable into `headerMode` and `footerMode`. Initially we always update them in unison (but read from `headerMode` unless we're specifically interested in the footer). Then we rip out the current conditional logic during read. Then we add some conditional logic during write, and only for the `MainScrollProvider` case which governs on-scroll showing/hiding. Other cases still set both.
Individual commits tell the story.
I think this should be enough.
Verify the old mode (without gate) works like in prod.
Verify the experiment doesn't break starter pack wizard and other screens where we intentionally hide the …

Fix fixed footer experiment

---

src/view/com/util/AccountDropdownBtn.tsx
src/view/screens/Settings/index.tsx

Replaces the main line item wrapper with our new interactive elements, and replaces the ... menu with `Menu` and a larger click target. So we get nice hover/pressed states.
After:
Before

Make settings account buttons a little nicer

---

src/state/cache/post-shadow.ts
src/state/queries/post-thread.ts
src/state/queries/threadgate/index.ts
src/state/queries/threadgate/util.ts
src/state/threadgate-hidden-replies.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

Merges local hidden reply cache (specific to user) with initially hydrated threadgate record, if we have it. Uses that as the source of truth for rendering logic.
Integrates new app view PR that returns `threadgate` on the `getPostThread` response, so that we always have an initial record to hydrate from, if it exists.
Clarifies relationship, so that only OP sees labels.

Optimistic hidden replies

---

.eslintrc.js
src/lib/moderatePost_wrapped.ts
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/screens/DebugMod.tsx

A usage of the non-wrapped version slipped through, and on old label was applied to a post.

Use moderatePost_wrapped for post embeds

---

src/view/com/util/post-embeds/VideoEmbedInner/TimeIndicator.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Intended behaviour is indicator is shown when:
Video is autoplaying, but not focused (i.e. hasn't been interacted with so no sound), and controls aren't visible

[Video] Add indicator of time remaining to web

---

src/view/com/post-thread/PostThreadItem.tsx

Test post: http://localhost:19006/profile/pfrazee.com/post/3l2shzxiref2u

Hide quote counts for quotegated posts

---

patches/expo-video+1.2.4.patch
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

We were originally doing this with a `setInterval` in https://github.com/bluesky-social/social-app/pull/4997, but it would cause some problems - particularly on Android - where `player` was being accessed after it was disposed of on the native side. This kind of exposed something that would actually be easier to just get as an event from `player` itself, rather than having to do the calculations on the JS side.
Essentially, this should work the same as before. Worth checking that nothing broke in regards to time formatting and rounding, but it seems solid from my testing.

[Video] Add `timeRemainingChange` event to `player` in `expo-video`

---

src/lib/statsig/events.ts
src/view/screens/Home.tsx

We don't need to log these anymore so let's stop sending events.
(We can still do cohort analysis using events from the past.)
Verify Following feed loads, verify can switch between feeds.

Remove logging of following prefs

---

src/lib/api/feed-manip.ts

I broke this during a refactor — it was not ok to change iteration direction here. This is confusing enough that IMO we should just do a `filter`, especially given that we already clone the array anyway.

Fix language filtering for feeds

---

__tests__/lib/string.test.ts
src/components/ProfileHoverCard/index.web.tsx
src/components/dialogs/Embed.tsx
src/components/dms/MessageItem.tsx
src/components/forms/DateField/index.shared.tsx
src/components/forms/DateField/utils.ts
src/lib/strings/time.ts
src/locale/constants.ts
src/screens/Profile/Header/Metrics.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/TimeElapsed.tsx
src/view/com/util/forms/DateInput.tsx
src/view/com/util/numeric/format.ts
src/view/screens/AppPasswords.tsx
src/view/screens/Log.tsx
src/view/shell/Drawer.tsx

Stacked on #4268, adds proper datetime localization.
There's an issue where memoized components might not necessarily reflect, as the I18n class instance is reused across locale changes. If that's a concern, we can do another change where we'll remake the instance when changing languages.

Localized date time strings

---

src/components/Lists.tsx
src/screens/Hashtag.tsx

There was some double border/half screen border weirdness going on in prod. Fixing.
Hard refresh the hashtag screen (https://bsky.app/hashtag/test) and observe the jank. Then try on localhost.
Should be no change on native.

fix hashtag screen side borders

---

src/lib/hooks/useInitialNumToRender.ts

If the user's font size is too large, the current logic might return a value of 0 (Math.floor will give us -1 then add 1 for 0). Let's force it to always be at least 1.

Force at least one item to always be initially rendered

---

src/alf/index.tsx
src/components/Lists.tsx
src/screens/Post/PostLikedBy.tsx
src/screens/Post/PostQuotes.tsx
src/screens/Post/PostRepostedBy.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostQuotes.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/util/Views.web.tsx
src/view/screens/ProfileFollowers.tsx
src/view/screens/ProfileFollows.tsx

On web, some of the headers don't render initially because of how we were rendering them. Web headers were being added inside of the `ListHeaderComponent`, however the `List` itself doesn't get rendered until the initial load has completed.
We also were displaying some top borders that were a little weird and didn't match how we did things elsewhere in the app. I've tweaked those so they look better.
Moving the header to the outer `Screen` component means it will show up even while loading. This requires a little bit of refactoring (mostly wrapping the content in a `CenteredView` rather than just a `View`, but this will work for now. It would be nice to refactor these components entirely at some point, but that's more of a task.
- On desktop web, check that the header shows up even on a …

Tweak rendering of top headers so they always appear even during load

---

src/components/StarterPack/QrCode.tsx
src/lib/generate-starterpack.ts

* Improves localization of starter pack names when automatically creating starter packs.
* Improves localization of `on Bluesky` at the bottom of the QR code sharing screen in the starter pack. Allows the string to be positioned after the logo.

Improve localization

---

src/Navigation.tsx

Hello,
For some reason, I find the back button in my profile tab very annoying. I don't think it's necessary because you can go back by clicking any other tab button. I've never seen this pattern before.
Is this expected behavior? If so, please feel free to ignore this PR.
Before:
https://github.com/user-attachments/assets/3fc63f0a-d545-4f29-bf3d-f444e334aa6b
After:
https://github.com/user-attachments/assets/d602e620-2d2c-4f82-b794-6dd2647c3961

Hide back button in my profile

---

src/components/FeedInterstitials.tsx
src/lib/statsig/gates.ts
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/view/com/posts/Feed.tsx

A more prominent placement for the profile suggestions since they've gotten better recently. This adds an interstitial to profile feeds (Posts and Replies tabs only).
Enable the gate. Observe this block after 5 slices:
It should be profile-dependent. Check with different profiles. (Might work better with a fresh account if your cluster follows are already saturated.) Some profiles won't have it (if no suggestions were served). For some accounts you'll see generic suggestions (if we don't know their cluster).
Verify Discover interstitials work like before.

[Experiment] Suggest profiles in profile

---

src/screens/Profile/Header/Metrics.tsx

When viewing profiles, the following, followers, and post counts are truncated/rounded when they become larger numbers, such as **1,000** becoming **1K**. This change provides a tooltip on the web on hover to provide full information when truncation/rounding has occurred.
Resolves bluesky-social/social-app#4951

Provide full tooltips on counts when truncated and rounded

---

src/lib/strings/url-helpers.ts
src/state/queries/video/video-upload.ts
src/state/queries/video/video-upload.web.ts

Couple of recent whoopsies
1. Fixes the service auth expiration (I made a seconds/milliseconds mistake)
2. Fixes the PDS URL to use `dispatchUrl`

[Videos] Fix uploads

---

src/lib/statsig/gates.ts
src/view/com/composer/Composer.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx

Splits the `videos` gate in two - `video_upload` (which is also used in the backend) and `video_view_on_posts`
Cross-reference with statsig and check there's no type errors

[Video] Split 'videos' gate in two

---

src/view/com/util/post-ctrls/PostCtrls.tsx

Inspired by https://github.com/bluesky-social/social-app/pull/4405 but a slightly different animation (inspired by the one in examples on the React homepage).
https://github.com/user-attachments/assets/5d72dfd3-310e-4062-aaf1-7bea8986a28d
https://github.com/user-attachments/assets/a895de5f-66e9-4de9-83dd-aa3be4f7410c
https://github.com/user-attachments/assets/380c7704-3be1-4b5b-8379-1f411e09c623

Animate the like button

---

src/lib/api/feed-manip.ts

This adjusts the heuristic to show more replies in Following.
Concretely, replies like `A -> B -> A` or `A -> ... -> B -> A` will now show even if you _only_ follow A (but not B). Previously, they were getting filtered out. Effectively, this means that an OP reply bumps the OP thread if you follow OP — but the condition is that B has to have >0 likes. This would filter out replies that didn't get anyone interested so far.
This doesn't contribute to the snowballing effect because you're _already_ following A anyway.
I follow Mark but I don't follow Tim. With the change, this reply shows in Following.
I follow Joyce but I don't follow David. With the change, this reply shows in Following.
I follow Jerry but I don't follow Molly. With the change, this reply shows in Following.
I follow Megan …

Show some known OP replies in Following

---

src/lib/api/feed-manip.ts

Noticed this during appview/relay syncing issues.
(This logic existed in the old code but I dropped but because I didn't know why. Now I know.)
If we have `post.record.reply` but we didn't receive a `reply`, something went wrong (i.e. we don't know its parent or root). Let's mark it as orphaned in this case.
This will make it filtered out of Following. On other feeds, it will display as "reply to a post" (so it won't seem top-level).
Don't know how to force it to happen, but I hardcoded the condition as `true` and verified the above.

Mark unhydrated replies as orphaned

---

src/view/com/composer/videos/VideoPreview.tsx
src/view/com/composer/videos/VideoPreview.web.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/TimeIndicator.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
yarn.lock

- Makes the backgrounds actually black, not theme black (dim theme wasn't using black)
- Adjusts the sizes of the indicators
<table>
<tr>
<td><img width="349" alt="Screenshot 2024-09-01 at 14 28 36" src="https://github.com/user-attachments/assets/2705f699-084a-499a-a886-4ef1e8bf4a16"></td>
<td><img width="349" alt="Screenshot 2024-09-01 at 14 28 49" src="https://github.com/user-attachments/assets/5cf54f11-94b3-4587-a19c-68da30f316bb"></td>
</tr>
</table>

[Video] Misc player style tweaks

---

src/locale/locales/pt-BR/messages.po

Can't vouch for top quality here but better than what we had. Hopefully can get cleaned up soon.

Add some Portuguese (PT-BR)  translation

---

src/lib/media/video/compress.ts
src/lib/media/video/compress.web.ts
src/lib/media/video/errors.ts
src/lib/media/video/types.ts
src/state/queries/video/util.ts
src/state/queries/video/video-upload.ts
src/state/queries/video/video-upload.web.ts
src/state/queries/video/video.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/videos/SelectVideoBtn.tsx
src/view/com/composer/videos/VideoPreview.web.tsx

- Surface errors in UI
- Check mime types for disallowed types
- Try and show server errors where available
- Try and clean up reducer (replace `SetStatus` with transitions between states)
- Clean up upload UI
- Use `done` status rather than `idle`

[Video] Upload errors and UI improvements

---

patches/expo-video+1.2.4.patch
patches/expo-video+1.2.4.patch.md

We're managing `AudioSession` state on our own through `PlatformInfo`. This lets us decide what to do when we want to do it, rather than relying on Expo's hardcoded management.
Test different ways of starting/stopping video audio playback while background audio is playing on iOS. Things shouldn't get borked, even between backgrounding and foregrounding the app.

[Video] Say No to Audio (Disable `expo-video` `AudioSession` management)

---

patches/expo-video+1.2.4.patch
patches/expo-video+1.2.4.patch.md
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

There's a `useEffect` right now that's trying to manage playing/pausing the video whenever we foreground/backgorund the app, but it's causing some problems. Tapping the sign, let's move this to the expo module lifecycle events instead.
Videos in the feed should pause whenever you background, then they should resume whenever you foreground again.
This should also fix the problem where a video will try to mute/unmute itself over and over.

[Video] Manage foreground/background playback on the native side

---

src/lib/custom-animations/CountWheel.tsx
src/lib/custom-animations/CountWheel.web.tsx
src/lib/custom-animations/LikeIcon.tsx
src/lib/custom-animations/LikeIcon.web.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

A little hard to test from bsky pdses, but a good way to test is as follows:
- Find a post that has a quote in it
- Tap into the quote, and like the post
- Refresh/restart the app
- Find the post that contained the quote, and tap into the quote
- The like icon shouldn't animate when changing values (since we don't get that info from the server)

Only animate the like icon when from an actual toggle

---

src/alf/atoms.ts
src/screens/Post/PostLikedBy.tsx
src/screens/Post/PostQuotes.tsx
src/screens/Post/PostRepostedBy.tsx
src/view/screens/ProfileFollowers.tsx
src/view/screens/ProfileFollows.tsx

These views just didn't extend past 100vh on web. No change on mobile. This mimics the old `hContentRegion` style, and I've added that as a new `util_screen_outer` atom.

Fix border on some listing screens

---

src/locale/locales/pt-BR/messages.po

While browsing today I checked out some new updates. 
On the left as it is on the black social network.
I've made some translations/corrections for pt-BR that consist mainly in:
Changing 'kit' to 'pacote' (per official use in the website and use in Brazilian news);
Some minor grammatical corrections;
Correction of minor consistency errors;
Translation of a few (very few) strings.
- Change to PT - BR language.
And test the information I provided.

Updating some messages in the pt-BR locale file - [2]

---

src/lib/statsig/statsig.tsx

Fixes excessive logging of `state:background:sampled` with `secondsActive = 0` on iOS.
The problem is that on iOS, app state goes `active` -> `inactive` -> `background`. As a result, the `else` branch of this code gets triggered both on `inactive` and `background`. It "correctly" counts the time only once (i.e. when going `active` -> `inactive`) and reports the other change as `secondsActive = 0` (because we weren't active in the first place). But it would be better not to send the event at all. With this change, only actual changes _to_ and _from_ `active` state emit the event.
```diff
--- a/src/lib/statsig/statsig.tsx
+++ b/src/lib/statsig/statsig.tsx
@@ -222,11 +222,13 @@ AppState.addEventListener('change', (state: AppStateStatus) => {
if (state === 'active') {
lastActive = …
```

[Statsig] Don't log extra background events

---

src/lib/api/feed-manip.ts

Fixes a bug where the author's Posts feed would miss some thread because a reply from it is reposted.
Make a thread of two posts and repost the later one.
Before the fix:
After the fix:

Disable in-thread deduping for reposted replies

---

src/view/com/composer/videos/VideoPreview.web.tsx

Preview is required to figure out the aspect ratio, so only allow videos if it works in your browser
Web only
Upload a .mov on firefox, they often don't work

[Video] fail video if cannot load preview

---

src/view/com/util/post-embeds/ActiveVideoNativeContext.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Adjust the logic to start/stop playback whenever switching tabs.
- Visit one tab, unmute a video
- Switch to another tab. Audio should stop playing
- Switch back to the tab, the video should resume playing but audio should be muted
https://github.com/user-attachments/assets/7aa6a043-47de-4d7b-a96e-2cc3f2c1839e

[Video] Tweak playback handling

---

src/locale/locales/pt-BR/messages.po

When I was updating translations for other languages, I encountered this error indicating that a curly brace is missing in the pt-BR translation.
Although it’s a commented-out translation, it still seems to affect the generating process for target messages.js files, so I added the missing curly brace back.

Fix a missing curly brace in pt-BR

---

src/view/com/composer/Composer.tsx

Found it easy to hit the wrong button by accident since they are so close... This PR adds a slight gap between them to help prevent someone accidentally hitting “Post” when they want to add a CW first.
Before / After

Add slight spacing between Post and CW button

---

src/lib/custom-animations/util.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

Just tweaking the like icon animation to:
- Not roll from 0 -> 1. Only the heart will animate in this case
- Add `overflow: hidden` to the wrapper so that the numbers don't go outside of the container
Verify that liking a fresh post (zero likes) doesn't "roll in" the 1, and that the animation is "contained" to the button rather than animating outside of it.

Tweak animation to not roll 0 -> 1, overflow hidden

---

src/components/moderation/LabelsOnMe.tsx
src/components/moderation/LabelsOnMeDialog.tsx
src/lib/moderation.ts
src/screens/Profile/Header/Shell.tsx

We were essentially hard-coding the `subject` as an account. I moved that logic down to the `AppealForm` and inferred the subject from the label itself.

Ensure profile labels can be appealed separately from account labels

---

patches/expo-video+1.2.4.patch
patches/expo-video+1.2.4.patch.md
src/components/icons/common.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Adding loading state to the player, similar to what we do with JIFs.
TBD

[Video] Add loading state to player

---

src/view/com/composer/videos/VideoPreview.tsx
src/view/com/composer/videos/VideoPreview.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx
src/view/screens/AccessibilitySettings.tsx

Fixes:
- `autoplayDisabled` setting description
- Preview (web and native)
- Web player
Native player is a bit crashy for me so I'll do that later
Make sure behaviour is the same normally, then confirm nothing autoplays with the setting enabled

[Video] Disable autoplay option (preview + web player)

---

src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx

If `expo-video` or `hls.js` encounters a fatal error, throw it up to the error boundary. On web 404 errors are special-cased with a friendlier error message.
Check out https://bsky.app/profile/samuel.bsky.team/post/3l3drakerfs2o

[Video] throw HLS errors to be caught by error boundary

---

src/view/com/util/post-ctrls/RepostButton.tsx

This is an established UX pattern/power user shortcut from other social networks. When long pressing the repost button, you bypass the intermediate dialog and are sent straight to the compose screen.

Add quick access to “Quote” action via long press

---

src/locale/i18n.ts

Number formatting data was not being loaded along with the pluralization rule data when activating locales. This PR makes it so that numbers are now properly formatted across the different locales.
Before / After

Fix number formatting for non-English locales

---

assets/icons/crop_stroke2_corner0_rounded.svg
src/components/dms/MessageItemEmbed.tsx
src/components/icons/Crop.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx
src/view/com/util/post-embeds/types.ts

Constrains the height of images in feeds and threads.
- anything shorter than 1:1 appears in-full
- anything taller than 1:1 appears "contained" by it's parent height (a square, so proportional to column width)
- anything taller than 3:4 crops within a min-sized container (matches common photo size)
- in highlighted thread view, images are not cropped
- unless very tall, they're cropped to 1:4, but still appear full-width
- QP with media crops embed image to 1:1 to save space
**To do**
Too tall, crops to min-sized container
Same in quotes
Quotes with media appear slightly differently
Image shorter than 1:1 appears as it's normal crop
Very wide images display in full (TBD if we want this)
All images now have a background, so that while loading there's something to take up space
Works in …

Constrain image heights in feeds and threads

---

src/view/com/composer/Composer.tsx
src/view/com/composer/videos/SubtitleDialog.tsx

- Save the alt text dialog in the composer's state on dialog close rather than every keystroke
- Fix dialog not being visible on Android

[Video] Fix alt text dialog on iOS and Android

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/web/EmojiPicker.web.tsx

Closes https://github.com/bluesky-social/social-app/issues/5059
How it looks:
How it works:
https://github.com/user-attachments/assets/63a2e4de-f19b-4653-ab36-5a2499ad26bf
I'm not sure about the design, though—particularly the button style and position.

add emoji picker to chat composer

---

src/components/StarterPack/Main/ProfilesList.tsx

Before: https://github.com/bluesky-social/social-app/issues/5174
After: 
I'm not sure how the number 200 was initially calculated, but it definitely needs to be increased here.
Fixes: #5174
Fixes: #5086

Fix starter packs scroll

---

src/App.web.tsx

Add a eventListener to 'keydown' event and identifies the key pressed to open the new post modal.
Closes #5047

"N" keyboard shortcut to open a new post modal

---

src/view/com/util/Toast.tsx

Only one deduplicated style is removed in the `util/Toast.tsx` component.

fix: remove duplicate style `rounded_sm`

---

src/Navigation.tsx
src/components/ProfileCard.tsx
src/components/hooks/useFollowMethods.ts
src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx
src/state/queries/post.ts
src/state/queries/profile.ts

We want to do more downsampling of some events, because they are really noisy. Here we go! Doing two things here:
- Tweaking the downsample rate from 90% to 95%
- Remove navigation event, but continue recording navigation to the notifications tab
- Adding some more events for downsampling:
-  'post:like:sampled'
- 'post:unlike:sampled'
- 'post:repost:sampled'
- 'post:unrepost:sampled'
- 'profile:follow:sampled'
- 'profile:unfollow:sampled'
- Adding `downsampleRate` to downsampled event metadata
This is a pretty simple change that is mostly verified by typecheck. Adding `sampled` to the end of the existing events handles downsampling for us with existing logic.
Testing that the metadata is being added can be done by just changing `isDownsampledSession` to `false`, then checking the network …

[Statsig] Add more events to downsample, increase downsample rate

---

src/lib/statsig/gates.ts
src/view/com/util/MainScrollProvider.tsx
src/view/screens/Home.tsx

The experiment was positive, probably because otherwise you can miss notifications. Let's hardcode for simplicity and to avoid having to think about different layouts.
Verify the bottom bar shows up on iOS, web, Android.

Set fixed_bottom_bar to true

---

src/lib/constants.ts
src/lib/media/video/errors.ts
src/state/queries/video/util.ts
src/state/queries/video/video-upload.shared.ts
src/state/queries/video/video-upload.ts
src/state/queries/video/video-upload.web.ts
src/state/queries/video/video.ts
src/view/com/composer/videos/VideoPreview.web.tsx

Implementation of `getUploadLimits` API. This is the point where you'll recieve `uploads_disabled`/`uploads_forbidden` errors, so this includes nice messages for that case.
Check network request `getUploadLimits` for however many videos you have left, and upload more than that many
Comment out the upload gate then try with an account that does not pass the gate

[Video] Check upload limits before uploading

---

src/App.native.tsx
src/App.web.tsx
src/components/intents/IntentDialogs.tsx
src/components/intents/VerifyEmailIntentDialog.tsx
src/lib/hooks/useIntentHandler.ts

Since we're going to be a bit more pushy about email verifications for certain flows, we want to make it a lot easier to complete the verification instead of having to copy/paste the code out of the email.
Start by visiting `http://localhost:19006/intent/verify-email?code=test`. This should tell you that the code is invalid. Press "Resend", and you'll get a new one (even if you've already verified your email, heh).
Grab the code, and try visiting the same URL but with a valid code. It should tell you that your email has been verified.

Add intent for verifying email

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Currently, the same `Mute` string is used in the context of the tag menu and as a label on a control for muting the sound of a video:
https://github.com/bluesky-social/social-app/blob/6c6a76b193edfd8bd46139b85fefd684ee557a8c/src/locale/locales/fr/messages.po#L3701-L3704
Given the different contexts, this isn't ideal for localization.
This PR suggests tweaking the labels to `Unmute video` and `Mute video`.

Add `context` to `Mute` and `Unmute` labels on video control

---

src/locale/locales/pt-BR/messages.po
src/locale/locales/ru/messages.po

base #5245.
I noticed that the Brazilian Portuguese and Russian translations weren't updated to 50MB like other languages. The translation teams might not catch this for the already translated strings, so I opened this PR.

Adjust the translated strings to the correct max size.

---

src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Instead of hacking around the problem with some messed up `useEffect`s, this PR just turns off the intersection observer when fullscreen
Upsides:
- Significantly simpler logic
- You ~~Might~~ Do Not Need An Effect
- Fixes the video pausing when entering fullscreen
Downsides:
- New bug: on returning from fullscreen, the video player seems to reset itself and loses play state.
This seems like a significantly better tradeoff than before

[Video] Much simpler fix to fullscreen bug

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Currently, when you tap the video with a touch device on web, the controls disappear immediately because you've stopped hovering it.
This PR has two changes (for touchscreens only)
- The initial tap should *only* bring up the controls, and not unmute/pause/do anything else
- The controls should stay visible for 3 seconds after a tap, for you to press the buttons
Make sure there's no regressions for mouse users
Thanks @surfdude29 for the bug report!

[Video] make hover state stick around if tapped

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

10px height -> 18px height. too finicky on touchscreens atm

[Video] increase target area of scrubber

---

bskyembed/src/components/embed.tsx

[Enbeds] fix video preview

---

src/screens/Signup/StepInfo/index.tsx

Pretty small QOL change, found this while creating my first account some minutes ago. For some reason the main login form already have autoCapitalize to none, but the signup form hasn't.

Add autoCapitalize to Signup password field

---

src/view/com/composer/videos/SubtitleFilePicker.tsx

I can't replicate the bug, but this maybe might fix it? My guess is some OS/browser combo doesn't know what vtt files are and are giving a generic mime type
This also adds error logging so we can see what the actual mime type we're getting is

[Video] speculative .vtt file selection fix

---

src/state/queries/notifications/util.ts

I don't know how to reliably reproduce it, but I often get a scroll jump when going into a notification:
https://github.com/user-attachments/assets/d0d2613c-cd97-4cf7-9d10-ce44cdc3bb55
You can see that for a split frame, it doesn't have counters:
But we're obviously coming from a "Like" notification so it has to have _some_ likes.
My theory is that sometimes the notification `getPosts` request comes in too early before the like counts have propagated. So we end up caching an earlier version of the `getPosts` response with the notification page.
To work around this, I'm adding a hack — if the notification is a Like or a Repost, but the received number of likes/reposts is zero, we're going to bump it to one. It'll still show the correct count when you navigate to it, but this way we solve …

Fix notification scroll jump

---

src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/view/com/profile/FollowButton.tsx

Hi there! 👋 I’d like to suggest a small improvement:
Rename the “Follow” button to “Follow back” when the user is already followed by someone, similar to how Instagram handles it? I think this would make it more intuitive for users to follow each other back.
Before:
After:
Before:
After:

Renaming the Follow button to "Follow back" when followed by user

---

src/lib/api/feed-manip.ts

Reverts bluesky-social/social-app#5049
We've given this a spin, and we're getting quite a bit of feedback that it feels pretty noisy. Regardless of whether we let this be customizable in the future, this doesn't seem like the right default. I'm suggesting we dial A->B->A down.

Revert "Show some known OP replies in Following"

---

src/view/screens/Profile.tsx

We have not yet introduced tooling for accounts to have multiple handles. While we wait for that tooling to land, lula is a somewhat notable account who recently changed their handle to a verified domain. Let's make sure it resolves correctly!

Add a hard-coded redirect for lulaoficial.bsky.social

---

src/components/FeedInterstitials.tsx
src/components/ProfileCard.tsx
src/state/queries/suggested-follows.ts

The `isFallback` handling relies on backend https://github.com/bluesky-social/atproto/pull/2805 but this can be deployed independently without negative effects.
Also filtered out followed users from this response. I thought we had done that on the backend, but let's just do it here since backend is swamped right now.
To do:
Compressed the size of this a bit, before/after on desktop web:
Basically no change on mobile, looks like this now:

Suggested follows by actor (on profiles) updates

---

src/view/com/util/images/AutoSizedImage.tsx

Adjusting image sizing based on user feedback.
**Constraints:**
- desktop web
- height is limited by a 1:1 square container (see red dashed container in screenshot)
- images taller than 1:2 will be cropped (but 9:16, 2:3, 3:4 will not)
- mobile
- height is limited by a 9:16 container (see red dashed container in screenshot)
- images taller than 1:2 will be cropped (but 9:16, 2:3, 3:4 will not)

Adjust image sizing

---

src/state/queries/notifications/util.ts
src/state/queries/post-thread.ts

Reverts https://github.com/bluesky-social/social-app/pull/5297 which is the wrong fix.
The actual problem was that when we construct a placeholder, we're looking into the author feed first. 
So here's what can happen:
1. Write a post
2. Go to your profile tab and refetch Posts
3. Go to notifications and wait for likes to pour in
4. Click on the liked post from the like notification, observe a jump (due to initially missing likes)
Previously, the post from author feed would be found first, which still has `likeCount: 0`.
With this change, the version from notifs would be prioritized over the version from feeds.
I think this generally makes sense because notifs seem more likely to be fresh. Ideally we'd either keep this normalized or prioritize the most recently fetched version. But that …

Fix notification->post jump for real

---

src/lib/api/feed/custom.ts

https://github.com/user-attachments/assets/917b8388-3eec-4e48-a8af-52959c308984
https://github.com/user-attachments/assets/97cf6d7c-16f4-4a85-ba53-7ba2f52b03d7
None of the media embeds were passing Lexicon validation in the logged out Discover because it did not go through the json-to-lex rehydration codepath, and so blobs were plain objects instead of `BlobRef` instances.
The fix is to make it go through the same codepath as done in normal circumstances.
I verified we're not using this hack anywhere else so this should be enough.

Fix lexicon validation in PWI Discover

---

src/components/StarterPack/Main/PostsList.tsx
src/state/preferences/feed-tuners.tsx
src/state/queries/post-feed.ts

Currently Lists display every single reply from every user on the list. This makes them great for a narrow use case (watching every single reply from a small group of people) but difficult to use for a broad use case (keeping up with a scene).
This change applies the current Following feed settings and heuristics to Lists. This means you'll still see replies in Lists, but only when you have some context on that reply (i.e. you follow the parent, the grandparent, or the root). As a result, Lists where you follow a lot of people will appear chattier while Lists where you follow few people will mostly show top-level posts.
This also aligns Lists with the behavior of Posts tab in Starter Packs (which already worked this way).
Every single reply was displayed, so whenever someone went on a …

Apply Following settings to Lists

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Similar to #5234, this PR adds `context` to the `Unmute` and `Mute` strings that refer to video, which enables better localization.
I think I got the syntax right 🤞
But I don't know how the code should be formatted to make Prettier happy?

Add context to `Unmute` and `Mute` strings

---

src/components/LikedByList.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostQuotes.tsx
src/view/com/post-thread/PostRepostedBy.tsx

Take a post with no likes and add `/liked-by` to the URL. 
Before:
After:
Did the same for reposts and quotes for consistency. (Quotes had a different empty state.)
Also added more specific titles.

Fix wrong empty state for liked by

---

src/view/com/composer/videos/SubtitleFilePicker.tsx

Seems sometimes the mime type is just... missing. Let's just allow files all that have a `.vtt` extension, broken files will just be broken when parsed on the backend, not much we can do there
https://blueskyweb.sentry.io/issues/5839940358/?project=4505071690514432&query=Invalid+subtitle+file+type&referrer=issue-stream&statsPeriod=14d&stream_index=0

[Video] loosen checks on vtt file

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

I put the padding on the wrong element - whoops!
Also shifts it down a little

[Video] Fix scrubber tap target

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/Scrubber.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx

Safari seems to emit `stalled` events when changing between HLS segments. a simple fix is to clear buffering state if the video is still playing
Also, unrelated: added a small animation to the scrubber

[Video] Fix safari showing spinner

---

package.json
src/view/com/composer/videos/VideoPreview.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
yarn.lock

Only one small change in this repo (removing of an extra calculation for the aspect ratio). The rest of the logic is inside of the PR linked here: https://github.com/bluesky-social/bluesky-video/pull/2
Fixes:
- Final remaining rash
- Audio focusing (mimic iOS behavior)
- Occasional aspect weirdness
- Fix foregrounding logic

[Video] Additional android fixes

---

src/components/dialogs/nuxs/TenMillion/index.tsx
src/state/models/media/gallery.ts
src/state/models/media/image.ts
src/state/shell/composer/index.tsx

Adds a brief default alt text to the virtual card image generated for the 10-million user celebration post.
I’m not certain if this aligns with good accessibility practices, but I had the thought and found some others discussing it. I’m open to feedback, particularly from screen reader and other assistive technology users.
P.S. Congrats on 10 million users! 🥳

Pre-fill alt text with 10-million card post

---

src/locale/locales/pt-BR/messages.po

This PR tweaks a `pt-BR` string as proposed by @lavendercolor in #5371.
It changes:
`O Bluesky agora tem mais de 10 milhões de usuários, e eu tinha #{0}!`
which DeepL translates as:
`Bluesky now has more than 10 million users, and I had #{0}!`
to:
`O Bluesky agora tem mais de 10 milhões de usuários, e eu fui o #{0}!`
which DeepL translates as:
`Bluesky now has more than 10 million users, and I was #{0}!`

Tweak `pt-BR` string

---

src/lib/custom-animations/LikeIcon.web.tsx

Adjust speed of web like animation to be slower to match the iOS and Android like animations which look much smoother.
Closes #5390 
Mobile for comparison:
https://github.com/user-attachments/assets/278d9058-8897-46ce-a3a8-fb42f4aeaf72
Before:
https://github.com/user-attachments/assets/d35c61ad-429f-46dc-b3d0-bc046300ad8e
After:
https://github.com/user-attachments/assets/0802cdf5-85a5-40f3-9938-b292d3e6f2f6

Make like animation on web same speed as mobile

---

patches/expo-modules-core+1.12.11.patch

No longer needed since we are not using `expo-video`.

Revert unneeded changes to `expo-modules-core` patch

---

app.config.js
patches/@sentry+react-native+5.32.0.patch
postHooks/uploadSentrySourcemapsPostHook.js

This changed, a lot. Simplest way to adjust this is to:
- Patch `@sentry/react-native` to allow passing additional args in the `expo-upload-sourcemaps` script.
- Create our own posthook that runs after builds, and includes the needed config
Merge, let it build, check Sentry for sourcemaps after build

Update sentry sourcemaps upload

---

src/lib/embeds.ts
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://github.com/user-attachments/assets/dc0ffb0d-2405-468d-948e-668966d48974" alt="Before Screenshot - iPhone 16 - 2024-09-19 at 14 49 30" /></td>
<td><img src="https://github.com/user-attachments/assets/0cb00f90-8e2f-4c18-a073-1d4108f81343" /></td>
</tr>
</tbody>
</table>

Fix ext embeds in DMs

---

src/App.native.tsx
src/App.web.tsx

This reverts back to what we had before the Neue Base branch went in. This prevents us from feature-gating ALF features, but we have no need atm anyway.

Revert provider stacking changes

---

assets/icons/aspectRatio11_stroke2_corner0_rounded.svg
assets/icons/aspectRatio34_stroke2_corner0_rounded.svg
assets/icons/aspectRatio43_stroke2_corner0_rounded.svg
assets/icons/flipHorizontal_stroke2_corner0_rounded.svg
assets/icons/flipVertical_stroke2_corner0_rounded.svg
src/components/icons/AspectRatio.tsx
src/components/icons/FlipImage.tsx
src/view/com/modals/EditImage.tsx

`@expo/vector-icons` is a dep of `expo` itself, so we can't get rid of that. But I noticed yesterday that our build was outputting a Material Icons TTF file, which was only used in the modal.
This PR replaces all those icons with custom ones, and uses our button component.
New -> Old

Replace icons in `EditImage` modal

---

bskyweb/templates/base.html
src/alf/fonts.ts
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx
web/index.html

Very subtle differences
Text is subtly smaller, tracking was previously `0.2` and with this update it's set to `0` to match our other text, that's the biggest difference.
Same as iOS

[Neue] Ligatures & composer

---

src/components/forms/Toggle.tsx

Makes these all larger by 4px. Old old toggles are 26px tall, these are now 24px.

[Neue] Toggles

---

.eslintrc.js
eslint/index.js
eslint/use-exact-imports.js
eslint/use-prefixed-imports.js

Warns and auto-fixes imports without the `#/` path alias
Hopefully we can incrementally roll this out like we did with import sorting so the codebase gets cleaned up over time, and eventually we can remove the prefix-less path alias from the tsconfig.json
Also makes the `use-exact-import` rule more specific about which nodes it checks, which should be more efficient.

Add eslint rule to fix imports without the `#/` path alias
