src/state/messages/convo/agent.ts

I realized on slow connections that waiting for every message to be sent in order is actually quite slow, and as they queue up, I can batch them and send as a group using `sendMessageBatch`.
See in video below, first group is sent all at once. Second group sends one message, then the rest.
https://github.com/bluesky-social/social-app/assets/4732330/d74399dc-f5fa-4cfa-ac27-aa696879ccd0

[🐴] Batch send all messages

---

src/state/messages/convo/agent.ts

Seeing if this is causing some duplicates. Will refactor to fix later if so.

Revert "[🐴] Batch send all messages"

---

src/lib/hooks/useNotificationHandler.ts
src/lib/notifications/notifications.ts

This got switched on accident somehow, change it back.

[🐴] Don't always show notification for everything

---

src/screens/Messages/Conversation/ChatDisabled.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/messages/convo/agent.ts
src/state/messages/convo/index.tsx
src/state/messages/convo/types.ts
src/state/messages/convo/util.ts

https://github.com/bluesky-social/social-app/assets/4732330/ef56b827-ad9e-4cf2-a86a-ef6767c8bc5b

[🐴] Mod disabled

---

modules/BlueskyNSE/NotificationService.swift
modules/expo-background-notification-handler/android/src/main/java/expo/modules/backgroundnotificationhandler/BackgroundNotificationHandler.kt
src/lib/hooks/useNotificationHandler.ts
src/lib/notifications/notifications.ts
src/state/queries/messages/list-converations.ts
src/state/queries/notifications/unread.tsx

Discussed this a bit, it will be difficult to handle this properly for DMs, so let's only increment for other notifications for now.

Disable badge incrementing for DMs

---

src/components/dms/ActionsWrapper.tsx
src/screens/Messages/List/ChatListItem.tsx

Adding an accessibility "action" to each message. This will let the user hear what the option is and how to activate it.
https://github.com/bluesky-social/social-app/assets/153161762/52e3640a-90f1-4969-9891-af0f2a0d34bf

[🐴] Screenreader accessibility actions for individual chat items

---

src/locale/locales/es/messages.po

I corrected several strings, translated some untranslated ones, and cleaned things up. This is still not complete but I figured I'd push this out to fix the worst of it. I plan on continuing to work on this and to hopefully complete the localization.

Update Spanish Localization

---

src/screens/Messages/List/index.tsx

[🐴] Some styling of empty list chats states

---

src/components/dms/MessagesListHeader.tsx

[🐴] in-convo muted chat indicator

---

src/screens/Messages/Conversation/ChatDisabled.tsx

[🐴 Tweak appeal button styles

---

__e2e__/flows/curate-lists.yml
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po
src/view/com/testing/TestCtrls.e2e.tsx

- Small tests fix
- Run intl extract

Release 1.83

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx

Fix button size on labeler

---

src/screens/Messages/Conversation/index.tsx

[🐴] Add convoId as key to Convo wrapper

---

src/state/queries/post-feed.ts

Removes the gate check since it isn't correct — the population in the split that are eligible for new onboarding haven't necessarily gone through the new onboarding.
Instead, use a heuristic. If the Following feed is the first pinned feed, keep the old behavior with the fallback. If it has been moved (manually or due to new onboarding), don't mix in Discover in there. This should roughly map to the old vs new onboarding, but doesn't depend on the gate.
Add console logs to function creation. Verify putting Following first will create the "mixed in" instance, while putting something in front of it would create the "raw" following.

Only fallback to Discover if Following is first pinned

---

src/components/dms/ConvoMenu.tsx

They were the wrong way around

[🐴] Fix block/unblock icons

---

src/state/queries/messages/list-converations.ts
src/state/queries/profile.ts

[🐴] Invalidate list convos query on block

---

src/screens/Messages/List/ChatListItem.tsx

[🐴] stop line breaks for timeelapsed

---

src/state/messages/events/index.tsx

Event bus should not be initialized unless we have an active session.

[🐴] Do not init event bus if no session

---

src/lib/strings/errors.ts

[🐴] better error message for "Bad token scope" error

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx

Decrease thickness of border on message input

---

src/view/com/posts/FeedItem.tsx
src/view/com/util/Link.tsx

Include feedContext in DOM as data-

---

src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po

1.84 release prep

---

package.json
yarn.lock

https://github.com/software-mansion/react-native-svg/issues/2241#issuecomment-2115255421

upgrade `react-native-svg` to `15.3.0`

---

src/view/com/util/LoadingPlaceholder.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

Because if I zoomed in to 280% it looked a little off.

Use a margin of -6 instead of -5 for PostCtrls 😵‍💫

---

src/view/com/util/fab/FABInner.tsx

Just a lil scale animation
https://github.com/bluesky-social/social-app/assets/10959775/5f9fda3f-975e-45cb-9d08-ea16404f8bbe

Animate FAB on press

---

src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx

https://github.com/bluesky-social/social-app/assets/10959775/2ace0a6b-4b6c-456c-8d4d-012656738074

Composer - only show divider when scrolled

---

src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx

Forgot to account for replying to someone - just needed to move that border to beneath the reply

Composer - fix divider when replying to someone

---

src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/util/forms/DropdownButton.tsx
src/view/shell/Composer.web.tsx

Stops it from rendering behind the modal

Composer - put language dropdown in fullscreenoverlay on iOS

---

src/components/Button.tsx
src/view/com/composer/threadgate/ThreadgateBtn.tsx

Reduce Threadgate button size

---

package.json
yarn.lock

Removes the defaultProps deprecation warning.

Bump FontAwesome

---

src/state/cache/profile-shadow.ts
src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/state/queries/post-thread.ts
src/state/queries/search-posts.ts
src/view/com/posts/AviFollowButton.tsx

PFP follow button: profile shadows

---

src/components/dms/MessagesListHeader.tsx
src/components/moderation/PostAlerts.tsx
src/screens/Messages/List/ChatListItem.tsx

[🐴] Add labels to chats

---

src/components/dms/MessageItemEmbed.tsx
src/screens/Messages/Conversation/MessagesList.tsx

We're gonna go with the OTA option

Revert "[🐴] Embed backwards compat"

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/AviFollowButton.tsx
src/view/com/posts/AviFollowButton.web.tsx

- Move it by 1px down and right so that the circles visually align by content rather than by border
- This gives the avatar a bit more space
- Fix React warning
- Remove avi button from post threads for now — it obscures too much of the avatar

Avi follow experiment tweaks

---

src/components/dialogs/GifSelect.ios.tsx
src/components/dialogs/GifSelect.shared.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/photos/SelectGifBtn.tsx

Keeps existing ALF dialog for other platforms, just forks for iOS to provide a more native experience
https://github.com/bluesky-social/social-app/assets/10959775/7af7b1b7-ee34-412a-8c37-0ec5d8bf5d62
Make sure there's no regressions
- Selecting GIFs
- Searching
- Search errors
- Other errors (error boundary stuff)

Native `formSheet` for GIF select on iOS

---

src/lib/strings/url-helpers.ts
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/List/ChatListItem.tsx

This PR adds a few niceties on top of the existing handling:
- only strips the post link if it's at the start or end of the message string
- handles the last message view in the chat list

[🐴] Post embeds polish

---

src/view/com/composer/Composer.tsx
src/view/shell/Composer.web.tsx

Just needed some old styles deleting
Also:
- Remove side padding and add `overflow: hidden` so lines reach the edge
- Remove animations (they didn't work on prod anyway)
Fixing the border above the threadgate is done in https://github.com/bluesky-social/social-app/pull/4343

Composer - unbork web

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/posts/Feed.tsx

Fixes missing top borders on web.
Check each profile tab, list page, and feed page, on all breakpoints.
Verify in code the change doesn't affect native.
Home still looks fine to me:

Fix missing top borders

---

src/view/screens/Search/Search.tsx

Need to use the `react-native-guesture-handler` `ScrollView` for android for https://github.com/bluesky-social/social-app/pull/4169

use rngh scrollview in search horizontal list

---

src/view/com/notifications/Feed.tsx
src/view/screens/Notifications.tsx
src/view/screens/SavedFeeds.tsx

Fixes:
- Notifications header on tablet taking full width
- Notifications loading state double border
- Edit feeds harline

Fix a few border nits

---

src/screens/StarterPack/Main/ProfilesList.tsx
src/screens/StarterPack/Main/index.tsx

* minimal landing page
add a minimal gate
remove overlap row
add bg to avatar set
implement basic mock up
add header of mock
add route
* remove avatar from landing
* cleanup some web styles
* rm `now`
* hairline width

[🏁 #7] Starter packs 7

---

package.json
src/screens/Deactivated.tsx
src/screens/Settings/components/DeactivateAccountDialog.tsx
src/state/persisted/schema.ts
src/state/session/__tests__/session-test.ts
src/state/session/agent.ts
yarn.lock

[🙅] Integrate deactivate

---

src/locale/locales/ga/messages.po

Updated translations.  I believe we have the plural form strings correct, but would appreciate someone with knowledge of the code having a quick look. Irish has 5 plural forms in CLDR: https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html

Update Irish translations back to 100%

---

src/view/com/composer/Composer.tsx
src/view/shell/Composer.tsx
src/view/shell/Composer.web.tsx

Forces a rerender of the textinput once the modal has shown, fixing an android bug

Composer - make sure android keyboard opens

---

src/state/shell/minimal-mode.tsx

Fix prettier

---

patches/expo-modules-core+1.12.11.md

https://github.com/expo/expo/pull/29513
Have not tested yet.

Patch Expo Modules for Android crash

---

src/state/queries/messages/list-converations.tsx

Turns out RQ doesn't do it automatically. 
Before:
After:

Debounce refetching listconvos

---

src/lib/statsig/gates.ts
src/view/shell/bottom-bar/BottomBarWeb.tsx

Verified badges are showing up.

Ungate mobile web notification badge

---

src/components/Link.tsx
src/platform/urls.tsx
src/view/com/feeds/FeedSourceCard.tsx

I noticed that meta-clicking on feed cards wasn't working. Factored out the logic from the generic Link component and added it to FeedSourceCard

Add support for new-tab clicks on feeds

---

src/state/persisted/store.ts

Tiny thing, but we're reporting this error for all new users too. Only want to know about validation errors for existing users.

Only validate persisted data for existing users

---

src/view/com/util/post-ctrls/RepostButton.tsx

Now matches other buttons in PostCtrls

Add hitslop to repost button

---

src/components/ProfileHoverCard/index.web.tsx
src/view/com/posts/FeedItem.tsx

Reverts bluesky-social/social-app#4471

Revert "Fix undefined block"

---

src/state/modals/index.tsx
src/state/util.ts
src/view/com/composer/Composer.tsx
src/view/shell/Composer.ios.tsx
src/view/shell/Composer.tsx
src/view/shell/Composer.web.tsx

Too many problems in the end, this just feels nicer

Revert to old modal on android

---

src/state/persisted/store.ts

We want to know what the object `path` is here.

Stringify path error

---

src/lib/statsig/statsig.tsx

Try/catch URL parsing of referrer

---

patches/expo-haptics+13.0.1.patch
patches/expo-updates+0.25.14.patch

Seems like straightforward bumps. Resolves warnings after yarn.
👀🤔✅

Resolve patch-package warnings

---

src/state/queries/feed.ts

Instead of mutating the results, this maps/filters the response to select only the items we want.

Select, don't mutate

---

src/screens/Onboarding/Layout.tsx
src/screens/Onboarding/StepProfile/PlaceholderCanvas.tsx

Ensures edit button is accessible, even with max font size. Also increases the image resolution on generated avis.

Onboarding fixes

---

src/view/screens/Search/Explore.tsx
src/view/screens/Search/Search.tsx

Essentially no change in design or functionality, just swaps in the new component.

Explore feed cards

---

package.json
yarn.lock

Curious if it affects bundle size.

Dedupe Zod installation

---

src/components/NewskieDialog.tsx

(cherry picked from commit ecb48797675c5be24508bf47141e930c64dac14e)

Prevent unecessary calls

---

src/components/NewskieDialog.tsx
src/components/ProfileHoverCard/index.web.tsx
src/screens/Profile/Header/Handle.tsx

Shows sun icon in web profile hover card, but disables click to open dialog which conflicts with the hover card

Newskie fixes

---

__tests__/lib/string.test.ts
src/components/hooks/useStarterPackEntry.ts
src/lib/strings/starter-pack.ts
src/screens/Signup/index.tsx
src/screens/StarterPack/StarterPackLandingScreen.tsx
src/view/screens/Home.tsx

parse at uris

---

src/view/com/pager/TabBar.tsx

Fix gap between tab bar and its border

---

src/components/moderation/PostAlerts.tsx
src/components/moderation/PostHider.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/util/UserAvatar.tsx

- 5c2ef687567d398efbd5a4e8a6ed53fae79a8ea7 Fix to thread PostHider to ensure that blocked quote-posts do not cause the parent post to be blurred
- c0565393b91db0d79400efe4e4da5562b2812275 Change to "Show hidden replies" to subsequently show the post hiders with their reasons on each post, per some user requests
- c33b2dd2e6f3da4b862539603062da089e434e39 Fix to the fallback avatar used on labels (now shows the shield)

Collection of moderation fixes

---

src/lib/strings/embed-player.ts
src/view/com/notifications/FeedItem.tsx
src/view/com/util/images/ImageHorzList.tsx

Currently there's no preview, which is especially odd if the post has no text. It's not animated, but I included a little label

GIF previews in notifications

---

src/components/Button.tsx

Wraps `Button` with `fowardRef` so that we can use it within `Menu.Trigger`.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/4576/files?diff=split&w=1)

Convert button to use forwardRef

---

src/view/com/threadgate/WhoCanReply.tsx

- Fix read-after-write problem leading to threadgate update not propagating to the UI.
- Drive-by fix for React keys (feel free to ignore if you rewrote that in your branch).
Verified with console logs the logic works as intended.
https://github.com/bluesky-social/social-app/assets/810438/6eb08c27-f2b9-4488-87ff-fa7dc728296b

Fix threadgate read after write

---

src/view/com/composer/Composer.tsx

Similar to https://github.com/bluesky-social/social-app/pull/4577 but for posting.
https://github.com/bluesky-social/social-app/assets/810438/eb2f4403-8529-4a27-997d-7082ef41ccef
https://github.com/bluesky-social/social-app/assets/810438/b86bdd31-f0c5-4c0b-8785-d9a0c70a624a
See above videos. Notice that:
- Posts reliably show up now (in the "before" video, the first reply seemed to "disappear" until refresh/invalidation)
- When posts show up, parent posts reliably increment +1 reply count (in the "before" video, sometimes parents would show no replies)

Wait for AppView when posting

---

bskylink/src/routes/index.ts
bskylink/src/routes/siteAssociation.ts

Add AASA to bskylink

---

src/components/ProfileCard.tsx
src/components/StarterPack/Main/ProfilesList.tsx
src/screens/StarterPack/StarterPackLandingScreen.tsx
src/screens/StarterPack/StarterPackScreen.tsx
src/state/queries/starter-packs.ts

Don't render starter packs that are invalid, give option to delete for owner

---

__e2e__/flows/curate-lists.yml
__e2e__/flows/feed-reorder.yml
__e2e__/flows/home-screen.yml
__e2e__/flows/profile-screen-edit.yml
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po

- Update tests
- Run intl extract

Release 1.87 prep

---

src/components/NewskieDialog.tsx

Tweaks:
- line height of multiline text
- icon spacing around title
- used modal close X on web
Before/after

Newskie dialog tweaks

---

src/lib/constants.ts
src/screens/StarterPack/StarterPackLandingScreen.tsx

Updates the starter pack landing page to show the global hardcoded "joined this week"

Set up the global 'joined this week'

---

src/screens/StarterPack/StarterPackScreen.tsx
src/screens/StarterPack/Wizard/index.tsx
src/state/queries/starter-packs.ts

Make a pack with a mention or links in it and view the result.

add rich text facets to description

---

src/screens/StarterPack/StarterPackLandingScreen.tsx

Add borders around starter pack landing page when tablet or deskto

---

src/components/NewskieDialog.tsx

Tweaking the wording a bit when viewing your own newskie badge.
Verify that none of the strings changed for accounts other than your own. For your own, you should see "Welcome, friend" and "You" instead of a profile name.

tweak wording for own badge

---

Dockerfile.embedr

Followup to Go version changes from #4585.  Should fix CI on main!

Go version for embedr

---

src/components/FeedCard.tsx

Feed cards on Explore and Feeds screen lost the + button

Add back pin action for feed cards

---

src/screens/Moderation/index.tsx

Disable enabling adult content on iOS

---

src/components/StarterPack/Main/PostsList.tsx
src/screens/StarterPack/StarterPackScreen.tsx
src/state/preferences/feed-tuners.tsx
src/state/queries/post-feed.ts

Yay or nay?
https://github.com/bluesky-social/social-app/assets/810438/1e93a4be-b46c-4b48-b0c0-01da7ba7098b

[Starter Packs] Posts tab

---

src/screens/Onboarding/util.ts
src/screens/StarterPack/StarterPackScreen.tsx

Had to add a response to the `bulkWriteFollows` here.
- Create an rkey for each follow with `TID.nextStr()`
- Try to write the follows
- Return a map of subject:uri if it was successful

update follows when pressing follow all

---

src/screens/Signup/StepInfo/index.tsx
src/screens/Signup/index.tsx
src/screens/Signup/state.ts

Talked more about comment in https://github.com/bluesky-social/social-app/pull/4692, decided to just revert.

Revert animation change in signup

---

src/screens/Onboarding/state.ts

Source data has been added, this is just the translation.

Add music interest to onboarding

---

src/components/FeedInterstitials.tsx
src/lib/statsig/gates.ts
src/view/com/posts/Feed.tsx

Inserts interstitials in Discover and Following:
- Discover: adds a suggested feeds at 20 posts, and followers at 40
- Following: adds followers at 20 posts, and feeds at 40
Testing:
Add you ID to StatSig overrides.

[D1X] Integrate interstitials

---

src/components/Button.tsx
src/view/com/posts/Feed.tsx

- Move follows to a higher spot since that's what we'll start experimenting with
- Fix colors
(Ignore the placement on screenshots lol)

Feed interstitial tweaks

---

src/components/FeedInterstitials.tsx
src/components/ProfileCard.tsx
src/state/queries/profile.ts

- Fix button feedback by adding another cache traversal for the shadow
- Add a toast
Note the toast is added to a shared component that's also used by the starter packs, so individual Follow buttons also show toasts there too.
https://github.com/bluesky-social/social-app/assets/810438/de7ed0c5-f008-4d97-9b38-756b9aaf2168

Show feedback for Follow button in interstitials

---

src/locale/locales/id/messages.po

Crowdin project for Indonesian translation: https://crowdin.com/project/bluesky-id, co-maintained by @oops-wtf and @kodebanget. Thank you to the following Crowdin users for their contributions in this translation update: oops-wtf, kemarau, danninov, suvpen, Callmark, thinkbyte1024, Yukiriiiin, rainzalic, hFathurohman, thebricksplanet, androro, mhmmdiqbal19, unlucky.naas, naturbrilian, joovzxaa, cheekieys. We also thank the Indonesian Bluesky users we can't mention individually for their valuable discussions on this translation.

Update Indonesian translation

---

src/view/com/composer/Composer.tsx

I'm adding disabled state to the `Post` button inside of the video PR. Right now we just have a regular `TouchableOpacity` with a `LinearGradient` inside for the post button. This makes a disabled state pretty weird and is different than the rest of our button styles in the app now. Let's change it to be an ALF button instead.
Just see how it looks and feels
https://github.com/bluesky-social/social-app/assets/153161762/653bbb03-8bc6-41c1-ae2a-acde9bf80e99

ALF post button

---

src/view/shell/Drawer.tsx

Mentioned by [Hailey here](https://github.com/bluesky-social/social-app/pull/4769#pullrequestreview-2173054638)

Replace incongruous buttons in drawer

---

src/state/queries/actor-autocomplete.ts

Relies on https://github.com/bluesky-social/atproto/pull/2653
We want to be able to find accounts that either we or the other party has blocked in typeahead so that we can remove blocks or block back users.
After the appview change is deployed, test that a blocked profile will not show up in typeahead search until the handle that was input is an exact match.

Don't filter exact matches from typeahead regardless of block status

---

src/alf/atoms.ts
src/view/com/util/Toast.tsx

- New look
- Entry/exit animations
- Icons

Native toast rework

---

src/components/forms/Toggle.tsx

Accidentally got them the wrong way around (i.e. off was right)

Switch - fix on/off positions

---

src/view/screens/AccessibilitySettings.tsx
src/view/screens/PreferencesExternalEmbeds.tsx
src/view/screens/PreferencesFollowingFeed.tsx
src/view/screens/PreferencesThreads.tsx

<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img width="200" alt="Screenshot 2024-07-17 at 15 20 11" src="https://github.com/user-attachments/assets/b7620a03-9100-45f6-8e20-aefb461fe218"></td>
<td><img width="200" alt="Screenshot 2024-07-17 at 15 01 04" src="https://github.com/user-attachments/assets/1878f768-b23a-493c-b4ef-348ecf35ec97"></td>
</tr>
</table>
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img width="200" alt="Screenshot 2024-07-17 at 15 20 19" src="https://github.com/user-attachments/assets/773ca36b-4b03-4ad8-81b6-8b5544d4390b"></td>
<td><img width="200" alt="Screenshot 2024-07-17 at 15 01 13" src="https://github.com/user-attachments/assets/ec0856c2-86ed-4a3e-8eb7-f786ad579d97"></td>
</tr>
</table>
<table>
<tr>
<td>Before</td>
<td>After</td> …

Modernise thread/following feed settings screen

---

src/view/com/util/Toast.tsx

Too long, want short.
Goes away faster

make toast shorter

---

__e2e__/flows/curate-lists.yml
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po

Release 1.89 prep

---

src/alf/atoms.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/Prompt.tsx
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/lists/ListCard.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/com/notifications/Feed.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/pager/TabBar.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/LoadingPlaceholder.tsx
src/view/com/util/ViewHeader.tsx
src/view/com/util/Views.web.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx
src/view/screens/Feeds.tsx
src/view/screens/Lists.tsx
src/view/screens/ProfileList.tsx
src/view/screens/SavedFeeds.tsx
src/view/screens/Settings/index.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx
src/view/shell/desktop/RightNav.tsx

For whatever reason this was using the weird TypeScript typed CJS require import thing when it should've been a normal const. This was messing up the import sorting

Replace `import hairlineWidth =` with const

---

src/components/FeedInterstitials.tsx
src/components/ProfileCard.tsx

Updates `ProfileCard` to match what I did for [FeedCard](https://github.com/bluesky-social/social-app/pull/4836/files). Much nicer.

[LinkLab] Add label to profile card

---

package.json
src/components/dialogs/ThreadgateEditor.tsx
src/state/queries/post-feed.ts
src/state/queries/threadgate.ts
src/view/screens/Search/Explore.tsx
yarn.lock

This is a follow up to #4830. This is a pull request with an alternative solution: see #4841. Feel free to merge both or either.
This version upgrades Typescript and uses it's latest feature to make the boolean filter less verbose.

Boolean filter improvement alternative: TS upgrade

---

src/components/Button.tsx
src/components/Link.tsx

Once other [LinkLab] PRs are merged in this one can go in to make the prop required.

[LinkLab] Make label required in link components

---

src/lib/hooks/useDedupe.ts

useDedupe callback

---

src/lib/api/feed-manip.ts
src/state/queries/post-feed.ts

Drive-by fix. This isn't being used anywhere, let's remove it.

Remove unused NoopFeedTuner

---

package.json
src/state/queries/video/video-upload.ts
src/state/queries/video/video-upload.web.ts
yarn.lock

[Video] Authed video upload

---

src/lib/moderation/useModerationCauseDescription.ts
src/view/screens/AppPasswords.tsx

Adds some missing localization.

Make more localizable

---

src/lib/notifications/notifications.ts
src/lib/statsig/gates.ts
src/view/com/posts/Feed.tsx
src/view/com/util/UserAvatar.tsx

These are launched:
- `suggested_follows_interstitial`
- `small_avi_thumb`
https://github.com/bluesky-social/social-app/commit/cc4dbd34efff76a3758f942fc4e104fbf81ce503 hardcodes them to `true`.
This is disabled:
- `request_notifications_permission_after_onboarding_v2`
https://github.com/bluesky-social/social-app/commit/07261bed040285cebfb36a577fc3e70174ebccb3 hardcodes it to `false`.
Read the code closely.

Cleanup flags

---

src/view/com/posts/FeedItem.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
src/view/com/util/post-embeds/VideoPlayerContext.tsx

1. Unique playlist URLs on the debug video - video starts from scratch now
2. Fix background on time remaining indicator
3. Animate indicator in subtly
4. Mute video until fullscreen

[Video] Bundle of minor tweaks

---

package.json
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
yarn.lock

1. update expo-video to latest
2. pause when offscreen
3. add mute/unmute button

[Video] more minor tweaks

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

Controls can be a bit obtrusive, and I noticed twitter has a nice behaviour where the countdown time gets removed after a little while. This adds a nice animation, and fades out the controls after 5 seconds
https://github.com/user-attachments/assets/79750cf2-1a6b-4e8b-9f0f-ac4dba6dc921

[Video] Animate controls + fade out time after a while

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

1. Handles app backgrounding
2. Ensures video plays when fullscreening and unfullscreening, just in case it manages to get paused somehow

[Videos] handle app backgrounding

---

src/components/dialogs/GifSelect.tsx

Fix `occurred` typo

---

src/components/Button.tsx

Extracting this from #4878
Just exposes a few more handlers on `Button`

Expose more props from button

---

src/screens/StarterPack/StarterPackLandingScreen.tsx

Use RichText for sp description

---

src/state/queries/post-thread.ts

Shape of a thread is changing, so we also need to update the expected type for a `getQueriesData` response when getting that query's data.
Optimistic likes should work when viewing a thread.

fix `findAll*` type in `post-thread`

---

src/view/com/util/AccountDropdownBtn.tsx
src/view/screens/Settings/index.tsx

Reverts bluesky-social/social-app#4980

Revert "Make settings account buttons a little nicer"

---

src/locale/locales/ca/messages.po

More lines translated, It will be so kind of you to check it @jordimas @darccio @surfdude29
Thanks

Update catalan localization

---

jest/test-pds.ts
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po
src/screens/Onboarding/StepInterests/index.tsx
src/view/com/testing/TestCtrls.e2e.tsx

Some fixes for the simulations, plus intl extract

Release 1.90 prep

---

package.json

_It's time for a bump_
_So we may do more building_
_And bring users joy_

Bump 1.91.0 (with haiku)

---

src/lib/statsig/gates.ts
src/view/com/post-thread/PostThreadFollowBtn.tsx

This experiment is fully rolled out so just cleaning it up.
Open a post from somebody who follows you but you don't follow back, verify the button says Follow Back.

Enable "Follow back" label gate

---

src/App.native.tsx
src/App.web.tsx
src/state/shell/composer.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

After https://github.com/bluesky-social/atproto/pull/2758, I don't believe we have any chances for users to interact with someone who blocks them. But I tested this using a commit before that was merged.
This PR protects the `openComposer` method, which handles replies (and quotes). And it protects the obvious culprits of this issue, the post controls, so quotes is technically handled twice for good measure.

Composer blocks

---

src/alf/atoms.ts
src/lib/api/index.ts
src/lib/moderation/useLabelInfo.ts
src/lib/strings/helpers.ts
src/state/queries/video/video.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/videos/SubtitleDialog.tsx
src/view/com/composer/videos/SubtitleFilePicker.native.tsx
src/view/com/composer/videos/SubtitleFilePicker.tsx
src/view/com/composer/videos/VideoPreview.tsx
src/view/com/composer/videos/VideoPreview.web.tsx
src/view/com/composer/videos/VideoTranscodeBackdrop.web.tsx
src/view/com/composer/videos/VideoTranscodeProgress.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Alt text and caption dialog. Captions are only available on web. Max 4 languages.
<table>
<tr>
<td>Web composer</td>
<td>Web dialog open</td>
<td>Web with captions</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/024ca004-ccd8-4e55-a922-7190e3f4c8e7" alt="Screenshot 2024-08-28 at 17 05 00"></td>
<td><img src="https://github.com/user-attachments/assets/355e0ada-5f00-43b6-a188-8e6447be40f1" alt="Screenshot 2024-08-28 at 17 05 48"></td>
<td><img src="https://github.com/user-attachments/assets/de7663bb-cc63-4e43-b9aa-12f3dbdca60b" alt="Screenshot 2024-08-28 at 17 10 41"></td>
</tr>
</table>
<table>
<tr>
<td>iOS composer</td>
<td>iOS dialog open</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/afa408be-cc3c-484b-83d6-420143735ef5" alt="Simulator …

[Video] Captions and alt text

---

src/view/com/composer/videos/VideoPreview.tsx
src/view/com/composer/videos/VideoPreview.web.tsx
src/view/com/composer/videos/VideoTranscodeBackdrop.tsx
src/view/com/composer/videos/VideoTranscodeProgress.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx

- Caps preview in player to same as in the feed
- Fixes the thumbnails not showing on mobile

[Video] Minor player tweaks

---

src/App.native.tsx
src/App.web.tsx

i18n relies on prefs, shell relies on i18n. So moved these around. I think this should be fine, but have a poke around to double check me.
Fixes #5045

Fix provider order

---

src/locale/locales/pt-BR/messages.po

Can't vouch for top quality here but better than what we had. Hopefully can get cleaned up soon.

Add some Portuguese translation

---

src/lib/custom-animations/CountWheel.tsx
src/lib/custom-animations/CountWheel.web.tsx
src/lib/custom-animations/LikeIcon.tsx
src/lib/custom-animations/LikeIcon.web.tsx
src/lib/custom-animations/util.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

The current animation makes use of `useAnimatedStyle` and `interpolate`, which causes some pretty significant render performance issues, particularly on older Android phones.
https://github.com/user-attachments/assets/ebf19aa8-ea45-4cb1-8583-f9a84391abb2
https://github.com/user-attachments/assets/efde0975-23ad-4701-afe1-57e2e317d894

Improve animations for like button

---

bskyembed/package.json
bskyembed/src/components/post.tsx
bskyembed/src/utils.ts
bskyembed/tsconfig.json
bskyembed/tsconfig.snippet.json
bskyembed/yarn.lock

[Embeds] Format big numbers

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Hide mouse when it's in the blank area of the video and you haven't moved it in 2 seconds
Interact with the player and see if it messes with normal functionality

[Video] Hide mouse when inactive

---

src/lib/constants.ts
src/lib/media/video/compress.ts
src/state/queries/video/util.ts
src/state/queries/video/video.ts

Fixes mime checks so they only happen on web (compression step will handle other formats on native)
Also adds quicktime

[Video] Fix mime checks

---

src/locale/locales/pt-BR/messages.po

Closes this [issue](https://github.com/bluesky-social/social-app/issues/5137)

fix on 'reposted by you' translation to ptbr

---

src/view/com/composer/Composer.tsx
src/view/com/composer/videos/SubtitleDialog.tsx
src/view/com/composer/videos/VideoTranscodeProgress.tsx

Native only. Also fixes some layout jumping due to different margins between steps
The error appearing on cancel is fixed in #5163, so it'll be a lot smoother after that
https://github.com/user-attachments/assets/92504108-b147-4a7e-abf0-87abaf170ae5

[Video] Enter/exit animations for video in composer

---

package.json
src/storage/README.md
src/storage/__tests__/index.test.ts
src/storage/index.ts
src/storage/schema.ts
yarn.lock

Add MMKV interface

---

src/view/com/util/post-embeds/VideoEmbed.tsx
yarn.lock

Small change, includes changes in https://github.com/bluesky-social/expo/pull/2

[Video] More adjustments for loading state jank

---

src/view/com/util/post-embeds/QuoteEmbed.tsx

Basically reverts to the way it was

Remove record-with-media side-by-side layout

---

src/components/video/PlayButtonIcon.tsx
src/view/com/composer/videos/VideoPreview.tsx
src/view/com/composer/videos/VideoPreview.web.tsx

Redesign play button

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/state/shell/composer.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/textInputWebEmitter.ts
src/view/com/composer/text-input/web/EmojiPicker.web.tsx
src/view/shell/Composer.web.tsx

Add emoji picker to chat composer

---

src/view/com/util/fab/FABInner.tsx

Adds the cursor pointer property to the 'New post' button since it doesn't show on the web app, a minor style change

Add cursor pointer to 'New post' button

---

src/view/com/util/post-embeds/VideoEmbed.tsx

Reverts bluesky-social/social-app#5207

Revert "[Video] Ensure loop doesn't stop"

---

src/lib/statsig/gates.ts
src/view/com/posts/FeedItem.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx

- Remove view gate on native
- Remove debug gate (no longer needed)

[Video] Open the floodgates (partially)

---

__e2e__/flows/feed-reorder.yml
__e2e__/flows/home-screen.yml
__e2e__/flows/profile-screen-edit.yml
__e2e__/flows/profile-screen.yml
__e2e__/flows/thread-screen.yml
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po
src/view/shell/bottom-bar/BottomBar.tsx

- Intl extract
- Fix tests
- Add pt-BR translations

Release 1.91 prep

---

src/lib/media/video/compress.ts
src/state/queries/video/util.ts
src/view/com/composer/Composer.tsx

- Makes sure mimetype is correct
- Fix the spinner spinning when it shouldn't be spinning

[Video] Upload tweaks

---

src/components/MediaPreview.tsx

- Fix recordwithmedia not showing
- Add background color to images

[Video] Media preview improvements

---

src/locale/locales/en/messages.po
src/locale/locales/pt-BR/messages.po
src/state/queries/video/video.ts

- **add error**
- **add message**
- **add ptbr**

[Video] Add a string for localization

---

src/view/com/composer/videos/SubtitleDialog.tsx

Will revert when I get the CC picker working

[Video] Cap subtitle files to one 

---

src/components/hooks/useFullscreen.ts
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Makes sure component doesn't unmount on fullscreen. Also restores scroll position on chrome

[Video] Fix fullscreen on Chrome

---

src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.web.tsx

Allows videos to be DnD'd and pasted, like images
- Drag-and-drop a video
- Paste a video
- Make sure I didn't break doing the same to images

[Video] Allow drag-and-drop & pasting video

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Fixes the fullscreen button being cut off by the scrollbar gutters

[Video] Remove scrollbar-gutter in fullscreen

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoWebControls.tsx

Cap to 10s in future until clicked, after which it's 30s
Watch the network tab for video segments
https://github.com/user-attachments/assets/8bc9d4e9-a9ec-4653-9df0-2d36c0e6967b

[Video] HLS buffering tweaks

---

src/view/com/util/post-embeds/VideoEmbed.web.tsx

Reverts an earlier YOLO change

[Video] Fix web autoplay

---

src/lib/statsig/gates.ts
src/view/com/composer/Composer.tsx

Hardcodes to true.
Uploaded a video.

Enable video_upload gate

---

src/view/com/util/images/AutoSizedImage.tsx

Separate alt/crop, use new icon

---

src/components/Fill.tsx
src/components/MediaInsetBorder.tsx
src/components/MediaPreview.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/ExternalGifEmbed.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx
src/view/com/util/post-embeds/GifEmbed.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx

Abstracted a couple components and aligned with our new design system. Some of the old styles were legacy, but it wasn't obvious which were which.
In a few places I also updated some components to look nicer e.g. adding our new play button icon.
I tested all cases on web and iOS. Test cases here http://localhost:19006/profile/test.esb.lol

Image/video border + tweaks

---

__e2e__/flows/curate-lists.yml
__e2e__/flows/thread-screen.yml
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/ru/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po

Release 1.91.1 prep

---

package.json
yarn.lock

Relevant commit https://github.com/bluesky-social/bluesky-video/commit/fa807e51df7a046203ab90def9de42da97e87f34

[Video] Fix iOS crash

---

package.json
yarn.lock

Adds this commit: https://github.com/bluesky-social/react-native-uitextview/commit/3965014745fb60cf76be7bc3696c307cb343c4b4

[UITextView] Add background color support to iOS selectable text

---

src/components/dialogs/nuxs/TenMillion/index.tsx
src/locale/locales/ca/messages.po
src/locale/locales/pt-BR/messages.po
src/state/models/media/gallery.ts
src/state/models/media/image.ts
src/state/shell/composer/index.tsx

Many thanks to @clavin for their help!

Pre-fill alt text with 10-million card post

---

package.json
yarn.lock

- Updated `@sentry/react-native` to latest
- Updated `react-native-image-crop-picker` to latest

Make it work with Xcode 16

---

src/components/dialogs/nuxs/NeueTypography.tsx
src/screens/Settings/AppearanceSettings.tsx

[Neue] Copy and spacing tweaks

---

src/components/MediaInsetBorder.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx
src/view/com/util/post-embeds/ExternalGifEmbed.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx
src/view/com/util/post-embeds/GifEmbed.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx
src/view/com/util/post-embeds/index.tsx

Increases rounding on all embeds to `md`

Increase rounding for all embeds

---

src/view/com/pager/TabBar.tsx
src/view/com/util/PressableWithHover.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/ControlButton.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/VideoControls.tsx

Use pressable for video controls

---

src/view/screens/Profile.tsx

<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/053980f8-7a4a-45e6-babd-474058c1b184" alt="Screenshot 2024-08-26 at 14 02 18"></td>
<td><img src="https://github.com/user-attachments/assets/87b47a2e-44e1-472d-9c80-d48167cce0f6" alt="Screenshot 2024-08-26 at 14 00 31"></td>
</tr>
</table>

Add side borders to `<ProfileHeaderLoading>`

---

src/view/com/auth/server-input/index.tsx

Edit self hosting copy

---

package.json
src/screens/Profile/Header/GrowableBanner.tsx
src/screens/Profile/Header/Shell.tsx
src/state/queries/actor-starter-packs.ts
src/state/queries/post-feed.ts
src/state/queries/profile-feedgens.ts
src/state/queries/profile-lists.ts
src/view/com/pager/PagerHeaderContext.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/util/UserBanner.tsx
yarn.lock

Supercedes #2171 
iOS only. Grows and blurs the banner on overscroll, with a spinner overlaid.
https://github.com/user-attachments/assets/1d8b7282-555c-4d85-b126-e0459b74c6a3

Header blurred banner on overscroll (take 2)

---

src/screens/Profile/Header/GrowableBanner.tsx

Once it goes past -65 we shouldn't keep increasing the blur too much

Constrain blur amount

---

src/view/com/composer/ComposerReplyTo.tsx

Reply to a post with emojis or someone who has emojis in their display name

Add emoji prop to composer reply to text

---

src/components/dialogs/nuxs/index.tsx

Adjust dialog timing

---

src/components/hooks/useHeaderOffset.ts

Adjust header offset

---

src/view/screens/Search/Search.tsx

Add margin to bottom of search input

---

src/view/shell/bottom-bar/BottomBar.tsx

Matches other apps and the new animation better

Tab change on press rather than pressIn

---

src/view/screens/Search/Search.tsx

Fix alignment of cancel button on search

---

src/alf/atoms.ts
src/view/com/post-thread/PostThreadComposePrompt.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="643" alt="Screenshot 2024-10-02 at 14 44 16" src="https://github.com/user-attachments/assets/22c2b99e-2cfd-4feb-8cfe-7104a2aa5cd1" /></td>
<td><img width="656" alt="Screenshot 2024-10-02 at 14 44 02" src="https://github.com/user-attachments/assets/a0fa080d-251a-45cd-80ac-bcf15a0041ba" /></td>
</tr>
</tbody>
</table>

Make reply prompt more subtle on desktop

---

src/lib/statsig/events.ts
src/view/com/util/forms/PostDropdownBtn.tsx

Log pinning/unpinning

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx

Don't merge until Jaz has fixed it server-side

[Video] Revert safari hackfix

---

modules/expo-receive-android-intents/android/src/main/java/xyz/blueskyweb/app/exporeceiveandroidintents/ExpoReceiveAndroidIntentsModule.kt
package.json
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx
yarn.lock

Adds new logic from https://github.com/bluesky-social/bluesky-video/pull/4 to the app.
Full screen a video on both iOS and Android, observe that the screen does not dim while watching the video.

[Video] Prevent screen from dimming while in full screen

---

src/view/com/lightbox/Lightbox.tsx

When users have larger sized font settings, some big alt text blocks can be made unreadable since they do not scroll. Here we're adding that ability when you expand the alt text portion of the lightbox.
- Scrolls when expanded
- When stopping momentum scroll by "tapping", the alt text does not collapse
- Alt text does collapse when tapping _after_ momentum scroll ends.
https://github.com/user-attachments/assets/f26ee26b-2666-4c63-abcd-4b7e727cb251
https://github.com/user-attachments/assets/e8e6b977-f351-4b23-a233-d21566bd7cb7

Make alt text scrollable on native

---

src/components/forms/SearchInput.tsx

fix clear button in input

---

src/components/moderation/LabelsOnMeDialog.tsx

- **add padding to appeal form**
- **remove row/wrap**

Fix layout bugs in appeals dialog

---

modules/BlueskyClip/ViewController.swift

It isn't possible to even launch the App Clip from TestFlight or Xcode without calling `handleURL` some how, but let's just _make sure_ that it starts by loading the home screen for Apple's testing purposes...

More clip stuff for Apple

---

src/components/dialogs/GifSelect.tsx

Fixes https://github.com/bluesky-social/social-app/issues/5688
https://github.com/user-attachments/assets/adb4d02d-00b0-47ca-88df-c374cd6d9762

GIF dialog is scrollable on web

---

src/lib/strings/display-names.ts

see https://github.com/bluesky-social/social-app/pull/5703#issuecomment-2407459187

Protect against zero-width chars in display name sanitation

---

src/locale/locales/ja/messages.po

- delete obsolete translations https://github.com/bluesky-social/social-app/commit/c06040cc209338fc37980648b31d4d64cc0c5c09 and https://github.com/bluesky-social/social-app/commit/9a769b9a038fe32ca2faaaf7fd914e1081ad76e9 
- new messages for email verification dialog https://github.com/bluesky-social/social-app/commit/2ebe8f435bf573932c14c06aaa2dc3b55ad363c6

Update Japanese translation

---

.eslintrc.js
src/components/Admonition.tsx
src/view/screens/Storybook/Admonitions.tsx
src/view/screens/Storybook/index.tsx

Add Admonition component

---

src/components/Admonition.tsx
src/screens/Messages/Settings.tsx
src/view/screens/NotificationsSettings.tsx

<table>
<thead>
<tr>
<th>Chat settings</th>
<th>Notification settings</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot 1" src="https://github.com/user-attachments/assets/cfcea9c0-87d8-428e-96b6-eaae81531ef6" /></td>
<td><img width="200" alt="Simulator Screenshot 2" src="https://github.com/user-attachments/assets/5ddbc2f6-6670-41e8-b64e-31b9bdcef786" /></td>
</tr>
</tbody>
</table>

Use admonitions in settings screens

---

src/view/com/composer/Composer.tsx

This PR marks for translation the 5 strings relating to state shown in `VideoUploadToolbar`.

Translate video state strings

---

src/view/com/composer/labels/LabelsBtn.tsx

Self label dialog design changes

---

src/view/shell/desktop/RightNav.tsx

#5761 has marked 'Logo by ...' in Drawer translatable, so marked same message in RightNav translatable.

Mark "Logo by ..." in RightNav translatable like it in Drawer

---

src/alf/util/platform.ts

I keep finding places I want to use `Platform.select`. Now includes a disclaimer about what not to use it for

New `platform` utility function

---

src/style.css

remove font style for ProseMirror

---

src/view/screens/ProfileFeedLikedBy.tsx

Add back borders to feed liked-by screen

---

src/lib/api/index.ts

From https://github.com/bluesky-social/social-app/pull/4163
Let's get composer back on track again.
Use applyWrites instead of creating post, threadgate and postgate records separately.

Make use of applyWrites when publishing posts

---

src/lib/api/index.ts

Move unrelated asynchronous logic into separate functions and kick them off concurrently. Await results at the end.
Posting takes 10 seconds on a slow connection.
Posting takes 6 seconds on a slow connection.
Try posting plain post, post with facets, post with media, a reply, combinations of these.

Remove waterfalls from posting

---

src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx

This is just a refactor. Should be self-explanatory.
I want to do this so that it's easier to move parts around for the threaded composer.
Try all composer features.

Split composer into smaller components

---

src/view/com/composer/Composer.tsx

I lost this in https://github.com/bluesky-social/social-app/pull/5941.
Post, notice "processing" is no longer of wrong color.

Fix missing style

---

src/view/shell/Drawer.tsx

Border on drawer

---

src/view/com/post-thread/PostThreadComposePrompt.tsx
src/view/com/util/fab/FABInner.tsx

this ensures you can feel both of them even if you tap fast. also adds to reply prompt

FAB - delay followup haptic

---

src/view/com/post-thread/PostThreadComposePrompt.tsx
src/view/com/util/fab/FABInner.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

- remove delay, make both light
- make like haptic light

One more haptic tweak

---

src/locale/locales/de/messages.po

The German translation is not finished yet. I would recommend giving Crowdin a chance to handle translations.

Update German translation

---

src/locale/locales/es/messages.po

[Translations] Complete Update - Spanish 100%

---

src/screens/StarterPack/Wizard/index.tsx

fix starterpack wizard screen

---

src/view/shell/Drawer.tsx

Fix drawer icon alignment

---

src/view/com/auth/SplashScreen.web.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="733" alt="Screenshot 2024-10-29 at 13 26 48" src="https://github.com/user-attachments/assets/719893d8-4e1e-4df7-af1a-4b252de60f58" /></td>
<td><img width="679" alt="Screenshot 2024-10-29 at 13 26 57" src="https://github.com/user-attachments/assets/fd017326-4278-4de4-be43-a85b6bc8b710" /></td>
</tr>
</tbody>
</table>

Fix splash screen

---

src/view/com/composer/Composer.tsx

Stacked on https://github.com/bluesky-social/social-app/pull/5953, https://github.com/bluesky-social/social-app/pull/5945, and https://github.com/bluesky-social/social-app/pull/5954
---
This modifies some existing checks to prepare for the reality of multiple posts. There is no support for actual multiple posts yet, so the array will always have a single element.
There is no behavior change.
Look over the code. Verify discard codepath, alt text codepath, "can post" codepaths work like before.

Extend composer checks to all posts in a thread

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/state/modals/index.tsx
src/view/com/modals/EditProfile.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx

Unfortunately new edit profile dialog is borked on web. Let's temporarily revert until we can sort it (web only)

Temp revert edit profile to old modal on web

---

src/components/StarterPack/StarterPackCard.tsx

Fix starterpack cards with no description

---

docs/build.md

To address https://bsky.app/profile/danabra.mov/post/3l7opdotmoc2u.

Clarify build instructions

---

src/screens/Settings/FollowingFeedPreferences.tsx
src/screens/Settings/Settings.tsx
src/screens/Settings/ThreadPreferences.tsx
src/view/screens/PreferencesFollowingFeed.tsx

[Settings] Following feed prefs revamp

---

src/components/RichText.tsx

Emoji warning should go away when viewing @poll.blue's profile
https://bsky.app/profile/poll.blue

Allow emoji in link facets

---

package.json
src/lib/constants.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/composer/photos/Gallery.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/composer/state/composer.ts
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/videos/VideoPreview.tsx
src/view/com/util/forms/DropdownButton.tsx
yarn.lock

Stacked on https://github.com/bluesky-social/social-app/pull/5953, https://github.com/bluesky-social/social-app/pull/5945, https://github.com/bluesky-social/social-app/pull/5954, https://github.com/bluesky-social/social-app/pull/5955, https://github.com/bluesky-social/social-app/pull/5957, https://github.com/bluesky-social/social-app/pull/5960, and #5976
---
This isn't pretty or anything. But it kind of works.
This is the culmination of porting pieces from https://github.com/bluesky-social/social-app/pull/4163 by @mary-ext.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/5962/files?w=1)
https://github.com/user-attachments/assets/ec7e851c-ec7d-40c6-8c4c-4ee7ca76ddb5

Thread composer UI

---

src/view/com/composer/state/composer.ts

Composer regression.
http://localhost:19006/intent/compose?text=blabla
Before:
After:

Fix character count with intent

---

src/lib/statsig/events.ts
src/view/com/composer/Composer.tsx

Adds `isPartOfThread` to `post:create` + adds a new `thread:create` for threads with >1 post.
## Test Plan

[Statsig] Track threads

---

patches/expo-image-picker+15.0.5.patch

Patches in https://github.com/expo/expo/pull/32534.
We'll get it later anyway but let's fix now.
https://bsky.app/profile/dansshadow.bsky.social/post/3l7vi74udg22c

Fix some images getting squished on Android due to EXIF tags

---

src/screens/Settings/ContentAndMediaSettings.tsx

Change language for autoplay setting

---

src/screens/Settings/Settings.tsx

Dev options in new settings

---

app.config.js

Adds increased memory limit entitlement

Increase memory on iOS

---

src/screens/Profile/Header/Shell.tsx
src/view/com/lightbox/ImageViewing/@types/index.ts
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/post-embeds/index.tsx

Stacked on #6135
---
Self-explanatory.
On the web, I had to screw with the layout a bit so that it doesn't blow up the avi full screen cause that was also quite strange. Normal pictures display like before.
https://github.com/user-attachments/assets/d0f2a985-d173-4aee-b7bc-2d843a93825f
https://github.com/user-attachments/assets/36e7d85c-3960-40e9-8a62-22cc5b963783
https://github.com/user-attachments/assets/fc7981ff-2f7a-42ac-83fa-81219c9e13c1

[Lightbox] Add border radius to avatars

---

app.config.js

Reverts bluesky-social/social-app#6141
Looks like we can't update the entitlements yet for some reason, let's unblock main

Revert "Increase memory on iOS"

---

src/view/com/composer/labels/LabelsBtn.tsx

Radio buttons no. Check boxes yes. Nothing more to say.
Things work as they did before.

Switch label buttons to checkbox from radio

---

app.config.js

Reverts bluesky-social/social-app#6165

Revert "Revert "Increase memory on iOS""

---

src/screens/Profile/Header/Shell.tsx
src/state/lightbox.tsx
src/view/com/lightbox/ImageViewing/@types/index.ts
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx
src/view/com/util/post-embeds/index.tsx

[Lightbox] Open animation

---

src/alf/index.tsx
src/view/com/util/text/Text.tsx

Investigating Android performance problems led us to - at least in part - the lack of memoization here. There is a considerable improvement by memoizing here.
Essentially, checkout main and test from a low end Android device. Compare that to what this branch feels like. There should be a marked difference in performance.
Also worth checking - perhaps side by side with a different device running on main - to make sure that no styles have changed by doing this, though they shouldn't have.

android scroll performance fixes pt. 1

---

src/view/com/feeds/FeedSourceCard.tsx
src/view/com/notifications/FeedItem.tsx

It had a lopsided border of hairline at the top and 1px on the other sides. Easy fix

Use hairline border for feed like card

---

src/view/com/lightbox/ImageViewing/index.tsx

Ez. Adjusting after https://github.com/bluesky-social/social-app/pull/6336 to be a bit faster.

[Lightbox] Make the animation faster

---

src/components/dms/MessageMenu.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

kill your app prefs then open all the translate things (button, post menu, chat menu)

Always use IAB for translate

---

src/locale/locales/hi/messages.po

I have translated the currently incomplete Hindi translation of the Bluesky user interface, alongside fixing several typos and inconsistencies that existed in the previous translations.
The translations of various terms and phrases are aligned with Twitter and Youtube's Hindi interface to avoid confusion.

Big update of the Hindi translation

---

src/view/com/util/forms/PostDropdownBtn.tsx

There's no need to calculate all these Hooks whose values aren't used until the sheet shows.
Let's move all of that into a child. This is pure copy-paste.
Verify post bottom sheet works.
PostDropdownBtn is yellow in the flamegraph due to its self cost:
Its self cost is barely there:

Render dropdown menu items lazily

---

package.json
yarn.lock

Fixes: https://github.com/bluesky-social/social-app/issues/6440

Remove unused 'react-scripts' devDependency

---

src/components/Dialog/shared.tsx
src/screens/Settings/components/ChangeHandleDialog.tsx

Caused by putting `a.overflow_hidden` on the ScrollView

Fix change handle dialog on android

---

src/Navigation.tsx

They're nicer than I remember
Check em out on android, see if they're any good. Hopefully improves native feel

Use android native navigation animations

---

src/view/shell/index.tsx

Partial revert of https://github.com/bluesky-social/social-app/pull/6617. Noticed 1px of the white background is flashing during the drawer animation. Guess we need this after all.

Fix leaking background

---

src/components/dialogs/PostInteractionSettingsDialog.tsx

Fixes #6259
https://github.com/user-attachments/assets/e5d9e34e-6355-4736-92b3-2d6f333dfff8
New behaviour 
vs. 
https://github.com/user-attachments/assets/2da6575e-8c88-46d2-a11d-a7b7b131edc4
Old behaviour

fix: nothing selected bug

---

src/view/com/util/LoadingPlaceholder.tsx

Fixes Notifications skeleton alignment to match the actual sizes (which changed at some point).
This gets the left top avatar to pixel-perfect alignment.
https://github.com/user-attachments/assets/80afb515-720d-4d79-bd04-3c42856ffe2f
https://github.com/user-attachments/assets/05f9113f-d8c7-4af3-ad84-063569e3ef62
https://github.com/user-attachments/assets/ad06da3e-6d81-4a77-b765-0a51bd19ec5a

Fix skeleton alignment

---

src/locale/locales/ga/messages.po

Translation back to 100%, with thanks as usual to @aonghuso and Donncha King for their help.  
Thanks also the dev team for implementing variables in the "X liked your post/custom feed" strings. This is a big quality improvement for us as a verb-first language... impossible to get right without the variable.   From our perspective, it would be OK to close #3481.

Update Irish translation

---

src/locale/locales/hi/messages.po

I have translated the new text strings added in version 1.94 to Hindi. Also fixed some issues with my previous translation now that I was able to view the changes in-app.
(I also removed the old unused strings from the file, which is the reason for the large number in the red.)

Updated Hindi UI for Version 1.94

---

src/locale/locales/gl/messages.po
src/locale/locales/it/messages.po

This should hopefully fix the [glitches](https://github.com/bluesky-social/social-app/pull/6463#issuecomment-2496116888) in the gl messages.po file.
Although I'm a bit baffled by the last error shown, as I can't see that string in the file? EDIT: last error is in the Italian file, which explains it

Fix glitches in gl/messages.po

---

src/components/dialogs/PostInteractionSettingsDialog.tsx

Undoing part of https://github.com/bluesky-social/social-app/pull/6720 for this release. I do think the new string is better though so I'll revert this back later.

Edit string to avoid churning translations

---

src/alf/util/navigationBar.ts
src/view/com/lightbox/ImageViewing/index.tsx
src/view/shell/index.tsx

- Use dark mode for status bar/nav bar
- (iOS) hide status bar when controls are hidden or when zoomed
https://github.com/user-attachments/assets/f247a7ec-9ada-464c-9b97-3c096146c08e
Check it works on iOS and Android. Ensure the status bar/nav bar returns to previous state when closing the lightbox
Check light mode and dark mode

Lightbox status bar behaviour

---

src/locale/locales/nl/messages.po

Approximately 500 improvements have been incorporated in style and wording from various contributors. See also #6244 .

Informal tone and other improvements to Dutch

---

package.json

Reverts bluesky-social/social-app#6781
Temporary

Revert "Bump version to 1.96"

---

package.json

Reverts bluesky-social/social-app#6790

Revert "Revert "Bump version to 1.96""

---

src/components/icons/VideoClip.tsx

re: https://bsky.app/profile/did:plc:vwzwgnygau7ed7b7wt5ux7y2/post/3lcfvt6g6ds2l
Before:
After:

Update VideoClip icon - Fix pixel grid alignment

---

src/lib/hooks/useOpenLink.ts
src/lib/statsig/events.ts

We're into driving clicks to people's sites, and we want to be able to tell creators & publishers about it. These metrics will help us convince more folks to make the switch.

Add link-click metrics

---

bskyweb/cmd/embedr/handlers.go

Fixes https://github.com/bluesky-social/social-app/issues/6941

Fix oEmbed provider_url and provider_name

---

src/components/Layout/Header/index.tsx
src/view/com/profile/ProfileSubpageHeader.tsx

[Layout] Profile subpage header

---

src/components/Layout/Header/index.tsx
src/screens/StarterPack/Wizard/index.tsx

You get it. Check for regressions

[Layout] Starter pack wizard new header

---

package.json
yarn.lock

Pulls in https://github.com/gre/react-native-view-shot/pull/549 to fix https://github.com/gre/react-native-view-shot/issues/547#issuecomment-2494366248.

Update viewshot to fix a crash

---

src/view/screens/Feeds.tsx
src/view/screens/Search/Explore.tsx

Also changed "Search" to "Search feeds"

[ELI5] Change feed page     copy

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx

Reverts bluesky-social/social-app#5367
The server fix didn't work.

Revert "[Video] Revert safari hackfix"

---

src/components/Layout/Header/index.tsx
src/screens/Post/PostLikedBy.tsx
src/screens/Post/PostQuotes.tsx
src/screens/Post/PostRepostedBy.tsx
src/screens/Profile/ProfileFollowers.tsx
src/screens/Profile/ProfileFollows.tsx

Post likes, reposts, quotes
<table>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-11 at 21 41 40" src="https://github.com/user-attachments/assets/b693807e-a555-48a7-ab97-0ebde09a5722" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-11 at 21 41 36" src="https://github.com/user-attachments/assets/3963a325-cfb3-4cda-9239-e45349b873c0" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-11 at 21 41 30" src="https://github.com/user-attachments/assets/bdc614c3-49f0-47f1-8fa7-2b9bd8c224f4" /></td>
</tr>
</tbody>
</table>

More exact counts

---

package.json
src/view/com/util/MainScrollProvider.tsx
yarn.lock

Bumps Reanimated to a version with https://github.com/software-mansion/react-native-reanimated/pull/6758.
Also reverts my hackfix from https://github.com/bluesky-social/social-app/pull/6219.
This will need some walking around the app etc. Let's put it on TF to see better.
I verified that reverting the hackfix did not hurt with the bump (but *would* hurt without the bump). In other words, this actually _does_ fix the original problem described in https://github.com/bluesky-social/social-app/pull/6219.
So this probably improves perf in other places too.

Cache Reanimated worklets

---

src/logger/bitdriftTransport.ts
src/logger/bitdriftTransport.web.ts
src/logger/index.ts
src/logger/types.ts

It got borked by https://github.com/bluesky-social/social-app/pull/6979

Fix web build

---

src/screens/Profile/ProfileFollows.tsx

Accidentally used the wrong one on this screen

Fix followersCount -> followsCount

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/Scrubber.tsx

Supercedes #6939 
Increases scrubber height if touch device, since 18px is too small for touchscreens

Increase scrubber height if touch device

---

src/components/dialogs/PostInteractionSettingsDialog.tsx

Reverts bluesky-social/social-app#6737

Revert "Edit string to avoid churning translations"

---

src/alf/typography.tsx

Allow non-graphic emoji to inherit parent color

---

src/view/screens/Profile.tsx

Add safe area view to profile error screen

---

src/components/ProgressGuide/FollowDialog.tsx

To better explain what you can search for.

Tweak Search placeholder

---

src/locale/locales/vi/messages.po

This PR enhances the Vietnamese localization with the following improvements:
- Adds new translation strings introduced by Bluesky
- Updates terminology to align with established Vietnamese translations from Twitter for better consistency
- Improves contextual accuracy of certain translations
- Fixes typos and grammar issues
Special thanks to the Bluesky team and contributors for the initial Vietnamese translations.

Update Vietnamese localization

---

src/lib/statsig/events.ts
src/screens/Search/components/ExploreRecommendations.tsx

We wanted to keep showing Recommended unconditionally.
It shows even if you disable trending

Don't hide recommended

---

src/locale/locales/an/messages.po

Update messages. L10n completed at https://localazy.com/p/bsky

Update Aragonese (an) localization

---

.github/workflows/bundle-deploy-eas-update.yml
.github/workflows/lint.yml
package.json
yarn.lock

Seems like a good idea to aid manual review

Add lockfile lint

---

package.json
src/locale/i18n.ts
yarn.lock

Reverts bluesky-social/social-app#6742
See explanation in https://github.com/bluesky-social/social-app/pull/7195

Revert "Fix post time localization on Android"

---

src/view/com/post-thread/PostThread.tsx
src/view/shell/bottom-bar/BottomBar.tsx

Should fix the Android 15 issue

Bump clamp max value

---

src/view/com/util/post-embeds/QuoteEmbed.tsx

Moderate composer quote

---

src/view/screens/Search/Search.tsx

https://github.com/user-attachments/assets/a637f15a-4b7d-4fd6-ae3f-5fb351bd2ee7

Fix recent searches tap handling

---

package.json
yarn.lock

implements https://github.com/bluesky-social/bluesky-video/pull/9

bump video version, fix android crash

---

src/screens/List/ListHiddenScreen.tsx

Right now, if you view a list that is created by someone who has blocked you, it tells you that the list has been hidden by moderation for violations of TOS. However, it should just tell you that the author has blocked you or you have blocked the author.
Create a list, block account B. Check the list from account B.

change copy on list blocked

---

src/locale/locales/fr/messages.po

Trending topics are live! But the UI around it is not translated… let's fix that.
Very trivial translation work here (around 30 strings), should be quite trivial to review between two holiday meals — if you are inclined to do so! — dear @surfdude29 and/or @CerryTsuki ✨

Update French translation (1.96.3 or 1.97)

---

src/locale/locales/it/messages.po

Note for Italian reviewers/readers: these translations come from Transifex: instead of asking me to update them here, just ask me to add you to the [Transifex project](https://app.transifex.com/mlocati/bluesky-unofficial).
Note for the curious who are poking around: take a look at https://github.com/mlocati/bluesky-social-app to see how Italian translations (and potentially others) are managed in Transifex.

Update Italian translations

---

src/locale/locales/ca/messages.po

Ready for 1.96.0
Please take a look at it @jordimas @darccio @surfdude29 @rortan134 @magarcia @aryiu
I hope you can approve it before launching this version @pfrazee, thanks

Update catalan messages.po for 1.96.0

---

src/locale/locales/ru/messages.po

* Added translations for new strings
* Replaced `аккаунт` with `учётная запись` for consistency
* Replaced the letter `e` with `ё` in the words where it should be. (e.g. `учётная запись`, `ещё`, `её`)
* Added `few` key for some plurals (Looked up in the Polish localization)
* Fixed some translations

Update Russian localization

---

src/components/interstitials/Trending.tsx
src/view/com/util/LoadingPlaceholder.tsx

It was just an empty row which looked weird to me.
This adds a little glimmer.
https://github.com/user-attachments/assets/1900e83b-cba4-452c-9df9-e19cce18cc64

Add loading state to new trending interstitial

---

app.config.js
src/lib/statsig/gates.ts
src/view/screens/Profile.tsx

We're going to do some more statig testing, so adding back the gate testing logic to the profile screen.

add back statsig gate testing

---

LICENSE

Simple new year bump to licence date.

docs: bump license year to 2025

---

src/view/screens/Profile.tsx

Remove test gates

---

bskyweb/cmd/bskyweb/server.go

Need to use echo's before hook in order to observe the resulting status code, in order to decide whether to set the cache-control header.
Recommend peeking this ignoring whitespace changes!

Do not serve cache headers on non-2XX for static assets

---

src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/index.tsx

Bring video cropping in line with images

---

src/view/screens/Home.tsx

The issue was `.split` call on potentially `undefined` (when `allFeeds` is `[]`).
A proper way to protect against this would be to enable `"noUncheckedIndexedAccess": true` in the TS config. But this raises too many violations.
Unpin all feeds. Verify no crashes on all platforms. Re-add feeds. Verify you can switch tabs by swiping, tapping, or (on desktop) the right pane menu.

Fix crash when nothing is pinned

---

src/lib/api/feed-manip.ts
src/screens/VideoFeed/index.tsx
src/state/queries/post-feed.ts
src/view/com/posts/PostFeed.tsx

show video feeds from posts even if they are replies

---

src/components/Layout/index.tsx
src/components/StarterPack/ProfileStarterPacks.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/posts/PostFeed.tsx
src/view/com/util/List.tsx

Just a little cleanup - we want all lists to have this, but it was being set piecemeal. Moved down into core `List`

Move indicatorStyle to `List`

---

src/screens/Profile/Sections/Feed.tsx
src/state/queries/post-feed.ts
src/view/com/posts/PostFeed.tsx
src/view/screens/Profile.tsx

Add videos tab to profile

---

src/components/ReportDialog/SubmitView.tsx
src/components/dms/ConvoMenu.tsx
src/components/dms/LeaveConvoPrompt.tsx
src/components/dms/MessageMenu.tsx
src/components/dms/ReportDialog.tsx
src/screens/Messages/ChatList.tsx
src/state/queries/messages/leave-conversation.ts

Shows a menu offering to block and/or delete the conversation.
https://github.com/user-attachments/assets/e8aac306-8e0c-4358-b0dd-0dd00f42645d
You might want to comment out the line that sends the report (`ReportDialog.tsx:163`)
1. Test that the core functionality works (it blocks, it leaves)
2. Check the handling of when API calls is slow or fails - it fetches the profile view for example (`ReportDialog.tsx:75`)
3. Check web styles

Post-report menu

---

src/components/dms/ReportDialog.tsx

Just a small typo I found during the translation process.
BTW, I would greatly appreciate it if you could also take a look at #7175.

Fix typo in ReportDialog.tsx

---

src/locale/locales/pl/messages.po

Just a quick translation and maintenance pass to catch up to the most recent release. 
ping: #7542

Polish translations for 1.97

---

src/locale/locales/vi/messages.po

This PR enhances the Vietnamese localization with the following improvements:
- Adds new translation strings introduced by Bluesky v1.96.6
- Fixes typos
@EmbiiFox please help me review the translations. Thank you.

Update Vietnamese localization to v1.96.6

---

src/screens/VideoFeed/index.tsx

[Diff sans whitespace](https://github.com/bluesky-social/social-app/pull/7606/files?diff=split&w=1)

Prevent following self via Immersive player

---

src/storage/index.ts
src/storage/schema.ts

```ts
account.set(['did:plc:abc', 'searchTermHistory'], ['sports', 'bluesky'])
account.set(['a string', 'searchTermHistory'], ['sports', 'bluesky']) // type error
```

Add example account store

---

src/locale/locales/eu/messages.po

Pulls from https://github.com/bluesky-social/social-app/pull/7580 which had some additional changes that weren't needed
TYSM @REALSOULMAN !

Update Basque localization for 1.97.0 (supersedes #7580)

---

src/locale/locales/hi/messages.po

The Hindi localisation was last updated in November and it's now been updated to the current version with all the new features added since like Trends.

Updated Hindi localisation for 1.97.0

---

src/screens/VideoFeed/index.tsx

Fix CI on main

---

src/lib/statsig/gates.ts
src/state/trending-config.tsx

We already have a gate on our server. No need to double gate it

Ungate trending topics

---

src/locale/i18n.ts

Fix interlingua mapping

---

Makefile

makefile: bump nvm to use node 20

---

src/view/com/util/forms/PostDropdownBtnMenuItems.tsx

Fixes #1017 and #6964.
Self-explanatory. Same as blocking.
Test muting and unmuting

Mute account from post

---

src/components/forms/DateField/index.android.tsx
src/components/forms/DateField/index.tsx
src/components/forms/DateField/index.web.tsx
src/components/forms/DateField/types.ts
src/screens/Signup/StepInfo/index.tsx

Changes the return key to focus the next input, rather than just hiding the keyboard
Web is unchanged because tabbing worked already
https://github.com/user-attachments/assets/a0317d7b-7872-4286-ad1e-31da717dd7d5

Connect inputs together in signup

---

src/components/moderation/PostAlerts.tsx
src/components/moderation/ProfileHeaderAlerts.tsx
src/lib/moderation.ts
src/screens/Profile/Header/Shell.tsx

Subscribe to https://bsky.app/profile/decentralised.goeo.lol
Check https://bsky.app/profile/retr0.id has only 1 label

Dedupe profile labels

---

src/screens/Messages/components/ChatStatusInfo.tsx
src/screens/Messages/components/MessagesList.tsx
src/screens/Messages/components/RequestButtons.tsx
src/screens/Messages/components/RequestListItem.tsx
src/state/messages/convo/agent.ts
src/state/messages/convo/types.ts

Alternative design, with an accept button on the messages screen.
<table>
<thead>
<tr>
<th>iOS</th>
<th>web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/14e301a2-55e6-477d-ae8a-8d62e2c63634" /></td>
<td><img width="500" src="https://github.com/user-attachments/assets/d70f53da-c518-426e-9a3b-a3eaac544c1e" /></td>
</tr>
</tbody>
</table>
Confirm accept button works

[Inbox] Accept button on convo screen

---

src/view/com/posts/PostFeed.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/5dfa99bd-7889-484e-ad5e-e7a6eefb2d34" width="400" alt="Screenshot 1" /></td>
<td><img src="https://github.com/user-attachments/assets/29c7f6e9-792f-4dc7-a577-dcae124dae91" width="400" alt="Screenshot 2" /></td>
</tr>
</table>

Fix progress guide location breakpoints

---

src/view/screens/Search/Search.tsx

Fucked up the branch name, so new branch and new PR. Previous PR description:
I got quite bored on a flight lol
Replaces old components with ALF ones. Should not change functionality much, albeit some components are improved (like the X buttons on the search page)
Have a look at page and the various states it can be in (incl. PWI). Should be the same or similar.

Modernize search page (take 2)

---

src/screens/Profile/ProfileFeed/index.tsx
src/screens/Profile/components/ProfileFeedHeader.tsx

https://github.com/user-attachments/assets/494e0c3c-0bf2-465d-879d-62d20aab8f4d
https://github.com/user-attachments/assets/e995c0d3-02db-4d2f-b7e7-567ce5f4ade6

Fix layout shift in profile feed header

---

src/screens/Settings/AboutSettings.tsx
src/screens/Settings/components/OTAInfo.tsx
src/screens/Settings/components/OTAInfo.web.tsx

https://github.com/user-attachments/assets/d1be6df1-e46f-4fdf-be92-18ab3698f23b

OTA helper in dev mode

---

src/view/screens/Search/Search.tsx

Cancel button on search posts screen currently accidentally takes you to the main search page. Whoopsie!

Fix cancel button on search posts screen

---

src/view/com/post-thread/PostThread.tsx

More direct fix for issue #7586 by adding moderation cache element to PostThread Reply.
Ensures moderation blur is present on PostThread as well as Reply Button for Composer.

Profile Moderation Blur Bug Fix

---

src/screens/Messages/components/RequestButtons.tsx
src/screens/Settings/AppIconSettings/useAppIconSets.ts
src/screens/StarterPack/Wizard/StepDetails.tsx
src/view/com/composer/videos/SubtitleDialog.tsx
src/view/com/composer/videos/SubtitleFilePicker.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

Merge #7903

---

src/state/queries/profile.ts

fix: Account switcher shows outdated profile name

---

src/components/NewskieDialog.tsx

Fixes https://bsky.app/profile/ocrm.isledelfino.net/post/3lk27dhvs2c2o

Fix newskie dialog width

---

src/components/dms/MessageItem.tsx

Idk what I was cooking here. Terrible code, deopts React Compiler, and doesn't seem to do anything at all.

Remove bad ref in render usage

---

package.json

Sorry if you were hoping for 2.0.0

Bump version to 1.100.0

---

src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

Haptics on external link card

---

src/screens/Search/Explore.tsx
src/screens/Search/modules/ExploreTrendingVideos.tsx

- Remove header
- Disable module

[Explore] Disable Trending videos

---

src/view/com/lists/ListMembers.tsx

Fixes https://github.com/bluesky-social/social-app/issues/7914
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/9d1faec7-7f95-483d-b500-30349b8d29b1" width="200" alt="After Screenshot" /></td>
<td><img src="https://github.com/user-attachments/assets/b8c10be6-4a3f-4efd-834c-c0661e23f960" width="200" alt="Before Screenshot" /></td>
</tr>
</table>

Fix people list footer

---

.github/workflows/build-and-push-bskyweb-aws.yaml
.github/workflows/build-submit-android.yml
.github/workflows/build-submit-ios.yml
.github/workflows/bundle-deploy-eas-update.yml

Tested with a successful iOS build https://github.com/bluesky-social/social-app/actions/runs/14044881327

Make sure Sentry's auth token is set on process

---

src/logger/metrics.ts
src/screens/Signup/StepCaptcha/index.tsx
src/screens/Signup/StepHandle.tsx
src/screens/Signup/StepInfo/index.tsx
src/screens/Signup/index.tsx
src/screens/Signup/state.ts
src/state/session/index.tsx
src/state/session/types.ts

New instrumentation for signup
- Replaced logEvent with logger.metric across the signup flow
- Added instrumentation for signup duration tracking
- Added tracking for field-specific validation errors
- Added detection of app backgrounding/foregrounding during signup
- Added dedicated tracking for username-related errors
- Updated metrics schema with new event types
Create account. make sure to make various errors in the fields as you go. then check the logs and ensure:
- Each time you made an error, it was logged
- On success, the time it took and the the number of backgrounds and errors should be logged

Instrument signup

---

src/components/FeedCard.tsx
src/screens/Search/Explore.tsx

- Cap to 3 items
- Change button

[Explore] Discover feeds module

---

src/alf/atoms.ts
src/components/FeedCard.tsx
src/components/ProfileCard.tsx
src/components/ProgressGuide/FollowDialog.tsx
src/logger/metrics.ts
src/screens/Search/Explore.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx
src/state/queries/actor-search.ts

New suggested accounts module
Unlike the follow dialog, this one does not do more suggestions once you follow someone - just too complex for this first pass. Totally possible to do in a followup.
https://github.com/user-attachments/assets/a9b99f4f-ef68-45b8-a688-6a1547b066d0
Click on the tabs? Make sure the pagination works?

[Explore] Suggested accounts module

---

src/alf/atoms.ts
src/components/FeedCard.tsx
src/components/ProfileCard.tsx
src/components/ProgressGuide/FollowDialog.tsx
src/components/icons/common.tsx
src/logger/metrics.ts
src/screens/Search/Explore.tsx
src/screens/Search/Shell.tsx
src/screens/Search/components/ModuleHeader.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx
src/state/queries/actor-search.ts

New headers with search button (with metrics), and module seen metrics. Logic needs updating as we add more modules
Seen metrics demo
https://github.com/user-attachments/assets/6ef07c80-0544-40e5-a52e-1ae423455dfc
Look at logs, confirm works

[Explore] New headers, metrics

---

src/components/dms/ActionsWrapper.web.tsx
src/components/dms/EmojiReactionPicker.web.tsx
src/style.css

https://github.com/user-attachments/assets/0d7bdcc1-0479-4e44-b94c-0923ed8826e3

Some design tweaks to web emoji picker

---

src/components/dms/MessageItem.tsx

I felt it should have a lil more overlap, and stand out a little better, so I added a subtle bg and shadow.

Design tweaks to applied reactions

---

src/screens/Search/Explore.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx

Forgot about this - on the original follow guide, obviously the account has zero follows so we didn't need to worry about filtering out people you already follow. However, now we need to do that.
This comes with the unfortunate side effect of often needing to load multiple pages, since the search API upranks people you already follow
Confirm all the suggestions are not followed, and that there are no empty tabs

[Explore] Filter out followed suggestions

---

src/screens/Messages/Conversation.tsx

Fix broken error screen in DMs

---

src/lib/app-info.web.ts
src/screens/VideoFeed/index.web.tsx

Very minor stuff, just misnamed imports

Fix some warnings that the web build spits out

---

src/components/StarterPack/ProfileStarterPacks.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx

Use `isPending` rather than `isFetching` for skeleton state to prevent jumps. Also use proper `<ListFooter>`.
I also applied the same fix to the lists tab and the starter pack tab, but I don't know of any accounts with a ton of lists to test with.
https://github.com/user-attachments/assets/ec1f5c50-27db-4ecc-84f5-b901f8fad1e9
https://github.com/user-attachments/assets/2c3f0a09-8d7e-44ec-b583-582251636061
Scroll the feeds on `@trending.bsky.app`'s profile

Fix loading jumps and footer on feeds tab

---

src/components/AvatarStack.tsx
src/components/StarterPack/StarterPackCard.tsx
src/screens/Search/Explore.tsx
src/screens/Search/components/StarterPackCard.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx
src/state/queries/useSuggestedStarterPacksQuery.ts

[Explore] Starter Packs

---

src/components/FeedCard.tsx
src/screens/Search/Explore.tsx
src/screens/Search/Shell.tsx
src/screens/Search/components/ModuleHeader.tsx
src/screens/Search/modules/ExploreFeedPreviews.tsx
src/view/com/posts/PostFeed.tsx

Currently using the same feeds as the suggested feeds module - I presume we'll want to change this
https://github.com/user-attachments/assets/2976fdcd-d10e-4f23-b119-73560325cab8
# Test plan
Scroll down, confirm feeds appear. Confirm moderation/mute words work. Confirm headers are sticky. Confirm pinning works

[Explore] Feed previews module

---

src/logger/metrics.ts
src/screens/Search/Explore.tsx

Adds the index of the viewed item to the view metric

[Explore] Add index to view metric

---

src/components/AvatarStack.tsx
src/components/ProgressGuide/FollowDialog.tsx
src/screens/Search/Explore.tsx
src/screens/Search/Shell.tsx
src/screens/Search/components/ModuleHeader.tsx
src/screens/Search/components/StarterPackCard.tsx
src/screens/Search/modules/ExploreInterestsCard.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx

Commits explain the gist. I'm not able to run iOS rn so could use a second look by someone who can.

[Explore] Design tweaks

---

src/screens/Search/Explore.tsx
src/screens/Search/components/ModuleHeader.tsx

[Explore] Rm sticky headers

---

src/components/ProgressGuide/FollowDialog.tsx
src/screens/Search/components/StarterPackCard.tsx

Key changes:
- search remains unchanged,
- topic tabs are powered by new API
- replaced `Tab` button with what we made for the Explore page
- removed insertion of additional suggestions after following a user

Add in new suggested accounts endpoint into FollowDialog

---

src/components/Dialog/index.tsx
src/components/ProgressGuide/FollowDialog.tsx
src/state/queries/trending/useGetSuggestedUsersQuery.ts

- Increase number of accounts suggested 3bb4535af0eba84027a158be94852f895d2edd81
- Add bottom pad to the list to ensure all items are visible 4577538aabee7a9975e636f8298743e807babe29
Checked the bottom pad increase on other dialogs, seems fine

Increase suggested follows in the new user progress guide modal

---

src/components/Link.tsx
src/view/com/notifications/NotificationFeedItem.tsx

Simple, but nasty diff
Check it looks/works the same across all platforms. Especially font sizes/colors etc

ALF Notifications screen

---

src/screens/Search/components/AutocompleteResults.tsx
src/screens/Search/components/SearchProfileCard.tsx
src/view/shell/desktop/Search.tsx

ALF search cards

---

src/view/com/composer/text-input/mobile/Autocomplete.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx

Copy pasta of these inner components so that I could use the verification state hook. Made small tweaks to the layout to handle overflow and alignment.

Add check to composer user autocomplete

---

src/view/com/modals/EditProfile.tsx

This ticket is a misnomer, but I aligned the handling here so that all platforms match.

Align handling of verified warning

---

src/screens/Search/Shell.tsx
src/screens/Search/components/SearchHistory.tsx

Refactor search history

---

app.config.js
package.json
yarn.lock

We didn't end up using vision-camera

Remove unused dependency

---

src/screens/Search/modules/ExploreTrendingTopics.tsx

https://github.com/user-attachments/assets/7bac18bb-8658-4b1e-9b14-be15211bd2f4

Fix skeleton height, prevent loading layout shift in Explore

---

src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/desktop/LeftNav.tsx

Fixes #8216 
https://github.com/user-attachments/assets/377333b7-90c2-4c6e-8c31-771af6e9f283
https://github.com/user-attachments/assets/84b187f4-67de-4ce7-ba87-a91a1901a34e

Fix PWI at 1300px breakpoint

---

src/view/com/lightbox/ImageViewing/index.tsx

Some function in the lightbox was no longer getting auto-workletized. Let's just manually mark as worklet
https://github.com/user-attachments/assets/3f538ed1-2fa7-4b33-9140-38e5f705e371

[Fabric] Fix worklet error

---

modules/expo-scroll-forwarder/ios/ExpoScrollForwarderView.swift

Small PR that reverts changes made in the upgrade branch to the scroll forwarder. These are not required until Fabric, and actually break things on old arch.

revert changes made to scroll forwarder

---

package.json
yarn.lock

Fixes https://github.com/bluesky-social/social-app/issues/5354
Look at some videos
Skim-read the [changelog](https://github.com/video-dev/hls.js/releases) (I don't see any breaking changes listed)

Bump `hls.js`

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/f725fa90-4d30-4f39-849f-ff7d491df06d" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/a7cdafda-e97c-49bd-827e-12e870e952b8" /></td>
</tr>
</tbody>
</table>

Hide footer when lists list is empty

---

src/components/Select/index.web.tsx
src/components/Select/types.ts

Fixes https://github.com/bluesky-social/social-app/pull/8323#issuecomment-2855638145

Fix select triggers on ios safari

---

patches/react-native-view-shot+4.0.3.md
patches/react-native-view-shot+4.0.3.patch

Verify on web that:
- Web onboarding flow works fine
- Copying a QR code to the clipboard works fine

temporary react-native-view-shot patch

---

src/components/dms/EmojiReactionPicker.web.tsx

Also now resets back to the default view after closing

Fix emoji reaction expanded picker on web getting squished

---

src/view/com/composer/select-language/SuggestedLanguage.tsx

Fixes https://bsky.app/profile/deaidua.org/post/3lpf7wgiyd22x
ALF'd design, and fixed see-through bug

Improve select language prompt

---

package.json
src/components/PostControls/index.tsx
src/screens/VideoFeed/index.tsx
src/state/queries/notifications/types.ts
src/state/queries/notifications/util.ts
src/state/queries/post.ts
src/view/com/notifications/NotificationFeed.tsx
src/view/com/notifications/NotificationFeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/PostFeedItem.tsx
yarn.lock

Currently only testable in dev-env
- Test you get like/repost notifs when someone likes a post you reposted (from feed)
- Test that it still works when liking/reposting from the thread view (same as #8414)

Notifications for likes on reposts

---

src/state/queries/notifications/util.ts

Make via-repost notifs groupable

---

src/components/ProfileHoverCard/types.ts
src/components/RichText.tsx
src/screens/PostThread/components/ThreadItemAnchor.tsx
src/view/com/post/Post.tsx
src/view/com/posts/PostFeedItem.tsx
src/view/com/util/PostMeta.tsx

Added hover cards, and also updated link components to use the newer version

Hover card on anchor displayName/handle

---

.github/workflows/build-submit-android.yml
.github/workflows/bundle-deploy-eas-update.yml
package.json

- **add fabric package/lock files**
- **github scripts for fabric**

add fabric package/lock files

---

.github/workflows/build-submit-android.yml
.github/workflows/bundle-deploy-eas-update.yml

use right file name in github action

---

src/screens/PostThread/components/ThreadItemAnchor.tsx

Review without whitespace https://github.com/bluesky-social/social-app/pull/8522/files?diff=split&w=1

Fix anchor follow button alignment

---

src/App.native.tsx
src/App.web.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/index.tsx
src/view/shell/index.web.tsx

This reverts commit f83335f1102ecb451ea4ee53f35f711f528956c8.

Revert "Move dialog outputs inside navigation context (#8511)"

---

src/lib/hooks/useOpenLink.ts

Only logs in dev, and falls back to opening in external browser
not tested, I don't know how to trigger the error

Catch web browser errors

---

bskyweb/cmd/bskyweb/server.go
package.json
src/Navigation.tsx
src/lib/routes/types.ts
src/routes.ts
src/screens/Settings/AccessibilitySettings.tsx
src/screens/Settings/ActivityPrivacySettings.tsx
src/screens/Settings/AppPasswords.tsx
src/screens/Settings/AppearanceSettings.tsx
src/screens/Settings/ExternalMediaPreferences.tsx
src/screens/Settings/FollowingFeedPreferences.tsx
src/screens/Settings/NotificationSettings/components/PreferenceControls.tsx
src/screens/Settings/NotificationSettings/index.tsx
src/screens/Settings/PrivacyAndSecuritySettings.tsx
src/screens/Settings/Settings.tsx
src/screens/Settings/components/SettingsList.tsx
src/state/queries/activity-subscriptions.ts
src/state/queries/messages/actor-declaration.ts
yarn.lock

Includes an update to the settings components so everything lines up properly

Activity notification public preference settings

---

modules/expo-emoji-picker/ios/EmojiPickerModule.podspec

~~Might fix crash? Let's see~~ It works!

Specify MCEmojiPicker version

---

src/components/dialogs/nuxs/index.tsx

Move date to expected release date

Move NUX date

---

bskyweb/cmd/bskyweb/server.go

omitempty on Age Restricted Geo

---

src/components/moderation/ReportDialog/const.ts
src/components/moderation/ReportDialog/index.tsx

Awaiting confirmation on a question, but otherwise ready to go. See Linear ticket for details.

Update copy and link in reporting flow

---

.github/workflows/pull-request-comment.yml
src/lib/hooks/useOTAUpdates.web.ts

- **use correct sha**
- **add web hook**

add web hook, action tweaks

---

src/view/com/util/Toast.style.tsx

This PR adds toast.style file to style `Toast.web.tsx` and `Toast.tsx`

[APP-1345] Hot fix: add toast.style file 

---

src/screens/Messages/ChatList.tsx
src/screens/Messages/components/InboxPreview.tsx

The naming of a lot of variables here was a little confusing, so I've updated the names to make it a bit more clear and reduced the amount of work what we do to get the right results.
cc @APiligrim

Rework variable naming, logic for rendering chat requests

---

src/components/PostControls/ShareMenu/RecentChats.tsx

Share menu recent chats was showing blocked/muted users and muted convos. We should filter them out
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/825c142e-9eb8-46a1-ba28-46f5f854da6a" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/9663826d-dc12-47f0-9374-db03d767bf08" /></td>
</tr>
</tbody>
</table>

Filter out muted/blocked convos from share menu recent chats

---

src/screens/Profile/Header/Shell.tsx

Spotted that profile back button on web does not match position of other back buttons and lack the interaction effect.
https://github.com/user-attachments/assets/7d7b1fd0-31b4-4951-b432-83bd9fe1cc71
Alter the profile back button position, align border radius with other back buttons, replace `TouchableWithoutFeedback` with `Button` component to be able to use hover state, rearrange and simplify styles.
https://github.com/user-attachments/assets/a23b4aaf-9d1a-4da5-8da0-da120f2ff0be

Profile back button tweaks for web

---

.eslintrc.js
src/components/Toast/Toast.tsx
src/components/Toast/index.tsx
src/components/Toast/index.web.tsx
src/components/Toast/sonner/index.ts
src/components/Toast/sonner/index.web.ts
src/view/com/composer/Composer.tsx
src/view/screens/Storybook/Toasts.tsx

Adds support for "custom" toasts, by splitting out the `Toast` component into constituent parts. Provides `Default` component. Adds `Toast.Action` for adding a button on the right side.

Yeah toast

---

src/components/dialogs/StarterPackDialog.tsx

- rm React import
- absolute imports
- use button properly

Starter pack dialog tweaks

---

src/locale/i18n.web.ts

I don't know why it's async because that's very much not allowed and I'm frankly shocked it works at all

Fix hook being marked as async

---

src/components/PostControls/BookmarkButton.tsx

Thanks @surfdude29 for catching this!

Require auth for bookmarking a post

---

src/view/shell/Drawer.tsx
src/view/shell/desktop/LeftNav.tsx

Reverts bluesky-social/social-app#8987

Revert "Use comment instead of context"

---

bskyogcard/src/index.ts

Normalize ogcard path metrics

---

src/state/feed-feedback.tsx

Currently, non-Bluesky algorithmic feeds are operating at an enormous disadvantage because they don't get the "seen" interaction. So they either have to aggressively prune all posts they've already served (which causes them to run out of content too quickly) or use [convoluted workarounds](https://bsky.app/profile/spacecowboy17.bsky.social/post/3ly4qrpprfs2q) that don't work well to approximate it.
The "For You" feed in particular is gaining popularity as a Discover alternative (anecdotally, Discover still doesn't seem to be very good) but this limitation is [hurting it](http://bsky.app/profile/spacecowboy17.bsky.social/post/3lzwuholkvc2n). This PR removes the limitation.
The original concern was that sending "seen" events back to the feed could potentially be privacy-sensitive and thus …

Send inferrable interactions to third-party feeds

---

src/components/Button.tsx

Aligns styles with designs after some internal tweaking

Button tweaks

---

bskyweb/cmd/bskyweb/server.go

This PR prevents embeds for moderated posts from being included in metadata. It does so by simply not passing the embed to the metadata HTML template if any undesirable labels are set.

feat: hide embeds for moderated posts

---

bskyweb/cmd/bskyweb/server.go

same thing as https://github.com/bluesky-social/social-app/commit/7f4e302b856e638dcfd39cf9f6f924ae3b3a85c0, but also checking in the self labels
cc @elijaharita

check for self labels when determining if we should hide embeds
