bluesky-social/social-app

package.json
src/components/AppLanguageDropdown.tsx
src/components/AppLanguageDropdown.web.tsx
src/locale/deviceLocales.ts
src/locale/helpers.ts
src/platform/detection.ts
src/state/persisted/index.ts
src/state/persisted/index.web.ts
src/state/persisted/schema.ts
src/state/persisted/util.ts
src/state/session/__tests__/session-test.ts
src/view/com/modals/lang-settings/ContentLanguagesSettings.tsx
src/view/com/modals/lang-settings/PostLanguagesSettings.tsx
yarn.lock

The app currently only supports 2-letter BCP-47 language codes for most of its language handling. The exception is what we pass to Lingui for i18n, which _can_ include a region code e.g. `pt-BR`.
Using `pt-BR` locale as an example, we had two main issues in our handling:
1. When opening the app for the first time, `pt-BR` was normalized to `pt`, which matched none of our `AppLanguage` values, and so the app appeared translated in English.
2. Then, when adjusting the `appLanguage` preference to properly translate the app, we also updated the user's `primaryLanguage` and `contentLanguage` prefs, which resulted in region codes being inserted into those settings where they were not supported.
(1) is "fixed" by (2), but because of (2), many users who have fiddled with their UI translations may …

Language fixes

---

bskyembed/src/components/embed.tsx

My thinking here is that we don't need to publicize beef between users. If a embed exists on a site, and a quote is later detached, it should just render nothing and not entice users to click on it for negative reasons.
The embed already behaves like this, but I added a specific check to make it more clear.

(RFC) Add explicit non-handling of detached quotes in embed

---

src/components/ProfileHoverCard/index.web.tsx

Hey there! 👋 This PR fixes a bug in the ProfileHoverCard component where labeler status was not properly handled.
I have noticed this bug yesterday and it was also reported here #5337 
**Before:**
**After:**
**When hovering a user profile:**

Fixing hover card for labeler accounts

---

src/view/com/notifications/FeedItem.tsx

This PR removes unnecessary spaces around the word "and" in the FeedItem component's notification items. Previously, there was an extra space before and after "and" due to the inclusion of {' '}. These have been removed to ensure proper spacing is handled.
Before:
After

Fix notification spacing

---

package.json
src/alf/fonts.ts
src/style.css

Handy dandy. Plus, Webpack outputs the built files now, no need for the `expo-font` hack.

Resolve source files for fonts, remove hack

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx

Fixes #5315 
By default, once a fragment (~5 seconds of video) is loaded by HLS.js, it sticks around indefinitely. This means that the initial low-res fragments (which at minimum is the first 9 seconds of the video) stay low-res even after the video loops.
Solution:
1. Keep track of low-res fragments. We do this via the `FRAG_BUFFERED` event.
2. Once focused, we wait for the next fragment change, then:
3. If the auto-detected quality level at this time is greater than low-res, flush the low-res fragments
4. HLS.js will automatically reload the fragments on next loop, likely now in hi-res
This *shouldn't* result in unbounded loading of data - it only triggers the eviction if it has sufficient network conditions to load hi-res fragments, and once something is hi-res it should never be …

[Video] Flush low quality segments once focused

---

src/lib/haptics.ts
src/view/com/util/fab/FABInner.tsx

While implementing a fab elsewhere, I realized that it's actually pretty hard to see the FAB animation right now. The fab is decreasing in size, so if your finger is over it you can't see the animation. Twitter's FAB does shrink as well, though to me it's still bizarre, since you can't actually see the animation at all. This PR inverts the animation, so it actually scales outward rather than inward.
I also added a small delay to the opening of the modal itself. There is still a haptic that immediately played so there's immediate feedback, but it gives us the chance to visually see the button shrink back to its original size. This delay does not occur if the user has haptic feedback disabled.
Additionally, I've added a haptic to the FAB (a light haptic though, not the default medium). The …

invert the fab animation, play a haptic

---

src/components/dialogs/Embed.tsx
src/components/forms/TextField.tsx
src/view/screens/Storybook/Forms.tsx
src/view/screens/Storybook/index.tsx

Was having some trouble with `TextField` collapsing in flex contexts. Really, we should use flexbox for the layout, not the sizing of the low-level component itself.
Should be no visible change, fixed one sizing issue in the web Embed dialog. Here are all the current usages:

Don't use flex on `TextField.Root`

---

modules/BlueskyNSE/NotificationService.swift

Doing a bit of cleanup around the NSE. Primarily here, I'm adding a dispatch queue for updating `UserDefaults`. See code comment:
```
// Because multiple instances of `NotificationService` may exist, we should
// be careful in accessing preferences that will be mutated _by the
// extension itself_. For example, we should not worry about `playChatSound`
// changing, since we never mutate that value within the extension itself.
// However, since we mutate `badgeCount` frequently, we should ensure that
// these updates always run sync with each other and that the have access
// to the most recent values.
```
There shouldn't be any change in how things work most of the time. This may lead to some improvements in glitched counts, though.

Improvements to NSE

---

src/lib/haptics.ts
src/view/com/util/fab/FABInner.tsx

The "growing outward" animation didn't feel as good as hoped for on device. Let's revert to what we had before.
Also, I'm tweaking the haptic to be a `Light` variant rather than the default `Medium`, since it does feel good but maybe a bit too strong.
Animation should now be returned to what it was before, and he haptic should be a bit weaker.

Revert change in FAB animation

---

package.json
src/lib/api/upload-blob.ts
src/lib/media/picker.e2e.tsx
yarn.lock

This has been lingering for a bit for almost no reason. We've pretty much completely moved to using `expo-file-system`, but there was a couple small usages left over.
- Upload an image from both iOS and Android
- Verify the e2e `getFile()` still works (see video). It only needs to work on iOS
https://github.com/user-attachments/assets/ab7a4d93-ed59-4743-a0be-274c9616cde1

Remove `react-native-fs`

---

patches/react-native+0.74.1.patch

Fixes https://github.com/bluesky-social/social-app/issues/5100
The null check for `type` doesn't actually do anything here, because `type` will never be `nil`, but rather it will be either `NSString` or `NSNull`. We need to actually convert `NSNull` to `nil` first before the check.
React Native handles the response for a request in this block of code: https://github.com/facebook/react-native/blob/303e0ed7641409acf2d852c077f6be426afd7a0c/packages/react-native/Libraries/Blob/RCTBlobManager.mm#L314-L326
Here, we see that values of `nil` - which `[response MIMEType]` will return when no `content-type` is provided in the response and the actual type cannot be determined (https://developer.apple.com/documentation/foundation/nsurlresponse/1411613-mimetype) - gets converted to `NSNull` by …

[React Native] Patch `RCTFileReaderModule` `readAsDataURL` to prevent crash when `type` is `nil`

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx

Gets rid of the second effect.
Same as https://github.com/bluesky-social/social-app/pull/5430.
I have not actually tested myself properly.

[Video] Refactor HLS logic

---

src/components/StarterPack/ProfileStarterPacks.tsx
src/screens/Profile/Header/index.tsx
src/screens/Profile/Sections/Feed.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/com/posts/Feed.tsx
src/view/com/util/List.tsx
src/view/screens/Profile.tsx

This extracts the simple parts out of #2171 
Adds `allowHeaderOverScroll` prop to `PagerWithHeader` so that the profile header can scroll with the rest of the page
iOS only. does nothing on other platforms.
https://github.com/user-attachments/assets/44001625-268e-484a-bfd7-3a21d18f0543
Make sure android behaves the same, and make sure other list screens on iOS are unchanged (i.e. the PTR spinner is still visible)

Allow profile header to overscroll

---

src/screens/Profile/Header/GrowableAvatar.tsx
src/screens/Profile/Header/Shell.tsx

Subtle grow animation for the avatar when overscrolling, to make it feel a bit more dynamic. Matches how large headers work on iOS (i.e. in Settings)
https://github.com/user-attachments/assets/79bc9419-3011-4c94-828a-ae04436c3ca3

Avatar overscroll animation

---

src/lib/statsig/gates.ts
src/state/queries/post-feed.ts

Feeds that don't do language filtering themselves return all results to the client, where we do our best to filter by the user's `contentLanguages`. If we get no good results back, we "bail out" and return the raw results, which may all be in a different language.
This PR adds a flag so we can test upping this fetch limit to see if that improves how many posts we get back in the user's language.

Add gate to increase post-feed page size

---

src/lib/haptics.ts

Dev only. Should help test haptics while developing

Show a toast when a haptic is meant to fire while using simulator

---

src/lib/custom-animations/PressableScale.tsx
src/view/shell/bottom-bar/BottomBar.tsx

Uses the new `PressableScale` for tabs
https://github.com/user-attachments/assets/fc2348b5-2bfb-47db-a938-98dc1bd7589d

Use scale animation for tabs

---

src/view/screens/Search/Search.tsx

Without this we get a useless placeholder

Add back empty placeholder

---

src/screens/Messages/List/ChatListItem.tsx

Makes the avatar link to the user's profile and replaces `UserAvatar` with `PreviewableUserAvatar`

Messages list - make avatars link to profile

---

src/view/shell/desktop/LeftNav.tsx

I hope it wasn't intended design 😨 
Before:
After:
PS. The circle still isn't perfectly round because the width is half a pixel more than the height. If no one minds, I can make a PR to make it look more like this:

Make the counter more rounded

---

src/alf/tokens.ts
src/components/Button.tsx
src/view/shell/desktop/LeftNav.tsx

Does a few things:
- new compose button
- fixes sizing/alignment of nav icons, these were a little wonky
- increases font weight of active item
- fixes sizing/alignment of notification dot, was a little wonky with the new type

Clean up left nav on web

---

src/alf/fonts.ts
src/style.css

Had a mime type issue: `<link rel="preload" />` wants `font/otf`, but `@font-face` wants `format('opentype')`.
While I was here, I mapped fonts we don't load to fonts we do load.

Fix font loading

---

src/view/com/util/PostMeta.tsx

I noticed that somewhat rarely, handles were collapsing and not being shown at all on Android. We had some code in the previous version of `PostMeta` that I had deleted, but evidently it was to handle this case.
I was not able to reproduce a collapsed handle on iOS or web. The fix was to allow the display name and handle to expand, which pushes the timestamp all the way to the right, which matches what we have in production today.
Collapsed handle:
The fix was to allow the display name and handle to expand, which pushes the timestamp all the way to the right:
Which matches what we have in production today:

Fix handle collapse on Android

---

src/view/com/auth/SplashScreen.tsx
src/view/com/auth/SplashScreen.web.tsx

Android "Create a new account" button was wrapping weird and the only fix was new copy. Strange.
While I was at it, I fixed spacing and updated web too.

Fix weird button wrapping on splash

---

modules/Share-with-Bluesky/ShareViewController.swift

Fixes https://github.com/bluesky-social/social-app/issues/5492
Some apps - when sharing an image or movie - actually end up being `public.url` rather than `public.image` or `public.movie`. As a result, we need to do a little bit of parsing for these.
Hard to test this in simulator, since the easiest way to test is by sharing a movie or image from iMessage into Bluesky. However, you should be able to test that on a device. Should test:
- Sharing an image works
- Sharing a video works
- Sharing URLs (from something like Safari) still works as it did before

[Share Extension] Support images/movies from other apps like iMessage

---

src/components/StarterPack/QrCode.tsx
src/components/StarterPack/QrCodeDialog.tsx
src/screens/Onboarding/StepProfile/PlaceholderCanvas.tsx
src/screens/Onboarding/StepProfile/index.tsx
src/screens/Onboarding/state.ts
src/screens/Signup/StepInfo/index.tsx

Now that we are able to, we should lazy-load `ViewShot`, since it saves us almost 80kb
Just using `React.lazy` and `React.Suspense`. Extremely basic for the QR code dialog, we just use `React.Suspense` to show the spinner until `view-shot` has loaded.
For signup, we won't actually use `React.Suspense`, because we don't want the user to get blocked from signing up for any reason. However, we _will_ try to make sure it's ready to go by the time the user gets to that screen.
- On "continue" from the account info screen (very first step of registration), we'll call `import()` for `view-shot`
- By the time we get to the avatar creator, it should be loaded
- If it isn't loaded though, it will just result in an undefined avatar URL and the user will just get the default avatar.
Go through an …

Lazy load ViewShot

---

src/lib/strings/embed-player.ts

Fixes https://github.com/bluesky-social/social-app/issues/5162
Adding podcasts to embed support for Spotify
Add a Spotify podcast (either a `/show/` or `/episode/` type url) to a post.

[External Embeds] Add podcasts to Spotify embeds

---

src/view/com/pager/PagerWithHeader.tsx

The scroll listener is reporting strange values when the profile first loads (equal to negative header height).
This is a little bit hacky, but it appears safe to ignore those values, since they're typically way out of the range you can possibly achieve by just overscrolling.
Video showing the bogus values:
https://github.com/user-attachments/assets/d252d937-ed64-4043-82ac-0f1af2be4b66

Ignore bogus onScroll values

---

package.json
src/lib/api/feed/author.ts
src/state/cache/post-shadow.ts
src/state/queries/pinned-post.ts
src/state/queries/post-feed.ts
src/state/queries/post.ts
src/state/queries/profile.ts
src/state/queries/suggested-follows.ts
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
yarn.lock

~~Dependant on https://github.com/bluesky-social/atproto/pull/2771~~ Ready to go!
- Allows a user to pin and unpin a single post to the top of their profile feed
- Pinning a second post replaces the original
- Adds a `ReasonPin` reason, which custom feeds can also use if they want to indicate a post is pinned

Pinned posts

---

src/lib/custom-animations/PressableScale.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/mobile/Autocomplete.tsx
src/view/shell/bottom-bar/BottomBar.tsx

There was some clipping here that needed to get fixed. It also just kind of looked janky, so redid some design here.
- Add a border to the entire thing like there is on web
- Fix missing handles (`||` instead of `??`)
- Stop using `TouchableOpacity` and instead use `PressableScale`
- Change `PressableScale` to be a bit more in-line with stuff like `style` (remove `contentContainerStyle` prop)
Everything should be the same as before functionality wise, with a couple of fixes.
https://github.com/user-attachments/assets/d51e7dcb-ce14-4e6a-a911-e86865a56bfa

Rework native autocomplete

---

src/view/com/util/fab/FAB.web.tsx
src/view/com/util/fab/FABInner.tsx

Feels a bit snappier
Test it works the same across platforms

use PressableScale for FAB animation

---

src/view/screens/Search/Search.tsx

`headerHeight` is used on web to provide the sticky header offset, so additional height needs to be included there. Also adjusted the gear icon color to match the burger on mobile.

Fix sticky offset, gear color

---

src/style.css

The `local` check seemed to be taking precedence in Chrome (I have `InterVariable` installed), but weights weren't working. It was working fine in Safari and FF.
I time-boxed this to 10 min, and considering how low the % hit rate on `InterVariable` and the italics would be, I think we can just remove this. Tested with the prod server too.

Remove local file check

---

src/lib/api/index.ts

I'm starting to bring in different pieces inspired by / taken from https://github.com/bluesky-social/social-app/pull/4163. The first of these pieces will be moving decoupling link meta / embed resolution from composer previews. I'm not ready to do that yet so I'm starting by doing little refactorings.
In this refactor, I'm doing a few things to the post creation method:
- Removed unsafe `as` coercions. They were only needed due to how the logic was structured with `embed` being redefined to wrap the previous `embed`.
- I found the recursive definition of `embed` a bit difficult to trace in general because it wasn't clear which cases are mutually exclusive. I've refactored it with stronger types to actually follow the codepaths that _can_ execute.
- While doing so, I've added …

Paralellize image uploads

---

src/lib/api/index.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/photos/Gallery.tsx
src/view/com/composer/state.ts

Stacked on https://github.com/bluesky-social/social-app/pull/5535.
---
This continues taking apart / adapting https://github.com/bluesky-social/social-app/pull/4163.
Currently, all composer-related state lives in assorted state variables inside the `Composer` component. We're going to need to change this since we need to support composing multiple posts in a thread. So we're going to need to lift state up.
As a first step towards that future, I am adding a reducer for composer state. Reducers are much easier to lift up because we'll be able to index individual posts state by the ID/index of that post. For now, this reducer only manages the `images` state. But similarly to https://github.com/bluesky-social/social-app/pull/4163, I intend to move most composer state there, stacking …

Introduce a composer reducer and move image state there

---

bskyweb/cmd/bskyweb/server.go

Maybe fixes https://github.com/bluesky-social/social-app/issues/5545. Have not verified.

Handle /starter-pack-short/:code in Go

---

src/alf/fonts.ts

We use `expo export` when building for OTA updates. The although the `expo-font` plugin works for production builds, the `export` CLI command does not use the plugin config, and therefore does not output our font files for use in the OTA bundle.
The `useFonts` hook here ensures that the fonts are exported for native OTA, even though it is not otherwise used.

Include ghost hook to statically export fonts

---

bskyweb/cmd/bskyweb/server.go
src/components/intents/VerifyEmailIntentDialog.tsx

Tweak verify email dialog

---

src/state/queries/video/video.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/state.ts

In https://github.com/bluesky-social/social-app/pull/5547, I introduced a reducer for composer state management. Over time, we want to move the rest of meaningful composer state there so that we can later lift it up and make it work for multiple threaded posts. In https://github.com/bluesky-social/social-app/pull/5547 I started with managing the image state there. In this PR, I'm extending this approach to also handle videos.
Integrating videos into the reducer was a bit tricky because they were managed by a custom hook with a combination of React Query and a separate reducer. So there was no easy way to let that state be controlled. To fix this, I've refactored video state management in https://github.com/bluesky-social/social-app/pull/5570 to just be a plain reducer. Why? Because plain …

Manage video reducer from composer reducer

---

src/components/dms/DateDivider.tsx
src/components/dms/MessageItem.tsx
src/components/dms/ReportDialog.tsx
src/components/dms/util.ts
src/state/messages/convo/agent.ts
src/state/messages/convo/types.ts

<table>
<tr>
<td>Screenshot 1</td>
<td>Screenshot 2</td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/21d1e3cf-4349-44ee-aed6-0b4f3515b096" width="200"></td>
<td><img src="https://github.com/user-attachments/assets/09d9fa7b-6efb-4df0-b3b6-ffd889518a0f" width="200"></td>
</tr>
</table>

[🐴] Reduce amount that message sent date is shown

---

src/screens/Search/utils.ts
src/view/screens/Search/Search.tsx

A query like `<query> lang:en` that is updated to an empty value will just get filtered out and become `<query>`.

Add option to search in any language

---

package.json
yarn.lock

We bumped Sentry after XCode 16 upgrades to get things building, but the recommendation now is to use version 5.24.3. So let's downgrade.
It compiles.

Downgrade sentry to recommended 5.24.3

---

src/view/com/composer/Composer.tsx
src/view/com/composer/state/composer.ts

This adds tracking of remaining embed/media types to the composer reducer.
They're not being used for anything yet, but you should roughly expect their state to mirror how the composer works today. (There are also some improvements. For example, pasting a quote link after a regular link will correctly mark a quote in the reducer state, whereas the old composer logic was not able to handle that.)
In future PRs, I will be making this the source of truth for two things:
- Composer preview
- Publishing a post
However we're missing some pieces to be able to do that, so for now it's not connected yet.
Note that in the draft, we don't distinguish between different types of links (other than quote/other distinction). This is because they're only relevant for preview and for posting. They're not …

Track links and embeds in the composer reducer

---

src/lib/api/index.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/state/video.ts
src/view/com/composer/videos/SubtitleDialog.tsx

Stacked on #5593 although unrelated.
---
The first commit moves remaining video-related state into the video reducer.
The second commit finally makes the `composerState` source of truth for the publish function — although for now, in a limited way. Only images and videos are being read from there. We're going to be moving more things over there soon.
For first commit, upload video, verify you can edit alt text. Add some subtitles (like [this file](https://gist.githubusercontent.com/samdutton/ca37f3adaf4e23679957b8083e061177/raw/e19399fbccbc069a2af4266e5120ae6bad62699a/sample.vtt)). Verify they show up after posting. Verify they clear after removing and readding a video.
For second commit, verify that generally posting images and videos works like before.

Make composer reducer source of truth for images/video when publishing

---

patches/react-native+0.74.1.patch

This is a followup to a hack patch introduced in https://github.com/bluesky-social/social-app/pull/3259. This patch does work - and we continue to use it right now - though there is actually a subtle difference in feel between what iOS actually does for a haptic and what we were emulating. Unfortunately it is still a bug on iOS 18 and no fix was introduced to RN. See https://github.com/facebook/react-native/issues/43388.
The good news is that there was some insight made on how to work around the bug in https://github.com/duckduckgo/iOS/pull/2942.
Like the attached PR says, we don't want to actually set the tint color for the view until _after_ the `RCTRefreshControl` has been added to the `RCTScrollView` (`RCTScrollView` is the underlying component of `FlatList`, `ScrollView`, etc. so …

Properly patch React Native to fix iOS `RefreshControl` bug

---

bskyweb/templates/base.html
src/alf/fonts.ts
src/style.css
web/index.html

This moves the `@font-face` defs into the HTML files so we can prefix them with our CDN in #5610.
Previously, Webpack exported these font files and hashed them by reference from the CSS file, and they were then spit out into `/web-build`. But, we added the (unused) `useFonts` hook back for native the other day, and Expo statically exports the same files bc that hook is present. This works for prod build as well as local dev.
So the files output are the same. And these `@font-face` defs just need to point to the proper location.

Move font-face defs into HTML for CDN

---

src/lib/constants.ts
src/view/com/composer/AltTextCounterWrapper.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/composer/char-progress/CharProgress.tsx
src/view/com/composer/photos/ImageAltTextDialog.tsx

Updates alt text limit to 2k characters for both images and GIFs + updates the UI with our char counter.

Add alt text limit to image dialog

---

src/components/moderation/LabelsOnMeDialog.tsx
src/components/moderation/ModerationDetailsDialog.tsx

Recent modifications to the label-related code complicated the translation work for languages with word orders different from English. To address this, I made a patch to enclose the entire sentence within a Trans tag.

Enclose the entire message in Trans tags for translation

---

src/view/com/composer/Composer.tsx
src/view/com/composer/char-progress/CharProgress.tsx

This if a follow up to https://github.com/bluesky-social/social-app/pull/5611, but it also fixes some things that I realized are existent even in production right now.
For example, currently the language selector will jitter around as we type since the layout is shifting each time the character count updates (different chars take up different amounts of space). I'll be addressing that here as well as fixing the actual bug right now (bad layout, number shows above the wheel rather than to the left of it, oops!)
Check each progress wheel/counter in each part of the app on both native and web.
https://github.com/user-attachments/assets/0dd6906f-7706-417c-9247-c94309ac3623
https://github.com/user-attachments/assets/2fe572d3-fc0e-4009-898c-24b00e156036 …

Fix composer char progress layout

---

src/view/com/util/post-ctrls/RepostButton.tsx

Swaps out `Inner` for `ScrollableInner` which fixes the padding problem. Going to go through and check the other few places we use `Inner` and - probably - replace them.

Fix padding in repost dialog

---

src/components/moderation/ModerationDetailsDialog.tsx

Ah, I forgot to add trailing ``.`` in #5616 . This fix will eliminate the need to modify existing message translations.

Restore the dot in the message displayed in the moderation details dialog

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/bug_report_fabric.yml
.github/ISSUE_TEMPLATE/feature_request.yml

There are currently some awkward line breaks shown in the intro text when you open a new issue. This PR removes them.
The templates can be previewed here:
https://github.com/surfdude29/social-app/tree/rm-linebreaks/.github/ISSUE_TEMPLATE

Remove line breaks in intro text in issue templates

---

src/view/com/composer/char-progress/CharProgress.tsx

As a follow-up to #5620, I noticed that the character count doesn't use tabular numbers anymore. This adds back the style.
Inspired by #5293 🙏

Use tabular numbers in `CharProgress`

---

src/locale/locales/pt-BR/messages.po

I updated some terms to be more accurate (e.g. step as _etapa_ instead of _passo_), fixed some inconsistencies like some terms being capitalized and others not and vice versa and added translation to some terms missing it.

Update and inconsistency fixes to pt-br translation

---

src/locale/locales/ca/messages.po

100% translated again, take a look please @jordimas @darccio @surfdude29 @rortan134

Update catalana messages.po

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="600" alt="Before Screenshot - 2024-10-07 at 20 02 27" src="https://github.com/user-attachments/assets/0ccb1077-dae8-4c77-bd4a-6fd6be206e40" /></td>
<td><img width="600" alt="After Screenshot - 2024-10-07 at 20 03 19" src="https://github.com/user-attachments/assets/f06d8d46-1874-4fef-a575-6cfe656f56f7" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="600" alt="Before Screenshot - 2024-10-07 at 20 02 44" src="https://github.com/user-attachments/assets/ea4ec490-4ddf-4574-b406-d1b9fdd71f4e" /></td>
<td><img width="600" alt="After Screenshot - 2024-10-07 at 20 03 04" …

Equal spacing on displayName/handle

---

modules/Share-with-Bluesky/ShareViewController.swift
modules/expo-receive-android-intents/android/src/main/java/xyz/blueskyweb/app/exporeceiveandroidintents/ExpoReceiveAndroidIntentsModule.kt
src/lib/hooks/useIntentHandler.ts
src/state/shell/composer/index.tsx
src/view/com/composer/Composer.tsx

We added share intent for videos, though were not passing along any dimension info which is required for the upload. Adding that here.
Sharing a video into the app works and you can actually upload it.

[Video] Add dimension info to share intent

---

src/lib/api/resolve.ts
src/view/com/composer/Composer.tsx

Resolves https://github.com/bluesky-social/social-app/pull/5608#discussion_r1789041040.
This got lost in my refactor.

Nicer error message for disabled quotes

---

package.json
src/components/Dialog/index.web.tsx
src/components/Menu/index.tsx
src/components/Prompt.tsx
src/components/dialogs/GifSelect.tsx
src/lib/hooks/useWebBodyScrollLock.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/web/EmojiPicker.web.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx
src/view/screens/Storybook/Dialogs.tsx
src/view/screens/Storybook/Menus.tsx
src/view/shell/Composer.web.tsx
yarn.lock

Adds Radix's `focus-scope` and `focus-guard` utilities to the dialogs and composer, so that they can compose properly with the dropdown menus. This means that dialogs and menus can now be nested, and the `Escape` key will work properly.
I also did the same to the composer, so now focus loops around when you get to the end
I also added nested sheet support to the menu component on native
1. Test the new `Dialog with menu in it` button in the Storybook (all platforms). Before these changes, this would've caused a recursion bug on firefox, so make sure that doesn't happen
2. Test the dialogs on web, esp. with the keyboard. They should act the same
3. Test the composer and the nested dialogs within it for regressions. again, should act the same but now with looping focus

Move Dialogs to Radix

---

package.json
src/view/com/util/forms/NativeDropdown.tsx
yarn.lock

Zeego depends on Radix even though we don't use Zeego's Radix abstraction. I think something in [this Radix update](https://github.com/radix-ui/primitives/pull/2934/files#diff-5e95ef32039f278b6120df2487c18e5ada5be130bb884c0d36d89c0f20ee41dd) changed types, and this upgraded version of `react-dropdown-menu` was causing unusual type errors e.g. `prop 'style' does not exist on ...<props>`, even though it continued working.
Looking through the git history, I don't think we really need these updated versions, or to update resolutions to point to those latest versions.
After downgrading, there was still an error with `DropdownMenuContent` where it thought _optional_ props from Radix's `Popover` abstraction were required. But this was appearing on the native component, where Radix is not used. …

Downgrade Radix packages for type compat

---

modules/bottom-sheet/index.ts
modules/bottom-sheet/src/BottomSheet.tsx
modules/bottom-sheet/src/BottomSheetNativeComponent.tsx
modules/bottom-sheet/src/BottomSheetPortal.tsx
modules/bottom-sheet/src/lib/Portal.tsx
src/App.native.tsx
src/components/Dialog/index.tsx
src/components/Portal.tsx
src/components/dialogs/GifSelect.tsx
src/components/dialogs/MutedWords.tsx
src/components/dialogs/PostInteractionSettingsDialog.tsx
src/state/dialogs/index.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/composer/photos/Gallery.tsx
src/view/com/composer/photos/ImageAltTextDialog.tsx
src/view/com/composer/photos/SelectGifBtn.tsx
src/view/com/composer/threadgate/ThreadgateBtn.tsx
src/view/com/composer/videos/SubtitleDialog.tsx
src/view/screens/Storybook/Dialogs.tsx
src/view/shell/index.tsx

Due to the strict necessity of iOS native sheets needing to be nested, we were creating new portal groups manually and then prop drilling to the sub-dialogs. This felt like a leaky abstraction, so this PR handles this automatically ✨
This has let me delete all of the unnecessary prop drilling in more cases. I've kept the prop around for the more general-purpose components for if we want to use it in future, but they're no longer used
How it works
1. Dialogs get the Portal they use from context. the default value of the context is same as before (thus no top-level provider needed) (also can be overridden by prop still)
2. Dialogs set a new default portal provider for their children via `<DefaultPortalOverride>`
1. Test normal dialogs work as before
2. Test nested dialogs work: within …

Allow nested sheets without boilerplate

---

modules/BlueskyClip/ViewController.swift
src/screens/StarterPack/StarterPackLandingScreen.tsx
src/view/com/auth/SplashScreen.web.tsx
src/view/screens/Home.tsx

An unlikely edge case - which probably doesn't explain the thing Apple is seeing - that is possible to hit. The user would need to actually be signed in on web for this to be possible, since otherwise they'd get redirected to `/start` rather than `/starter-pack`, but might as well fix it here.

Ensure app clip works even with `starter-pack`

---

src/screens/Moderation/index.tsx
src/state/queries/preferences/moderation.ts

Non-configurable regional labelers should not appear in the report dialog. However, they should appear on the Moderation screen.
This PR filters them out by default (since users can't really interact with them), but adds a flag to optionally include them where needed.

Filter out non-configrable mod authorities from report dialog

---

src/view/com/util/UserBanner.tsx

With our avatar generation (even without) this blue default banner color is pretty garish. This tones it back to look a little nicer out of the gate.
Before

Make default banner more palatable

---

src/components/Button.tsx

This was an oversight, should definitely be a size up.

Bump icon size for small size buttons

---

src/alf/fonts.ts

Disables contextual alternates only in Inter because non-common contextual alternates such as `0x10` and `=> ->` are characteristic of Inter.

Disable contextual alternates only in Inter

---

modules/bottom-sheet/ios/SheetView.swift
modules/bottom-sheet/ios/SheetViewController.swift
modules/bottom-sheet/src/BottomSheetNativeComponent.tsx

https://github.com/user-attachments/assets/53a616bc-3064-4ed4-b98f-04534eafe48b

Fix sheets to work nicely on ios 15

---

src/view/com/composer/threadgate/ThreadgateBtn.tsx

Reduces the pad on Web so the button isnt so dominant
|Before|After|
|-|-|
|![CleanShot 2024-10-10 at 16 59 00@2x](https://github.com/user-attachments/assets/b22d0fa0-835c-4f9d-985e-f1d4c3bbb47e)|![CleanShot 2024-10-10 at 16 58 39@2x](https://github.com/user-attachments/assets/cd8754e8-61ab-420c-b7d1-2411c0f5c55c)|
Mobile remains unchanged
|Mobile|
|-|
|![CleanShot 2024-10-10 at 17 11 57@2x](https://github.com/user-attachments/assets/bd964508-7191-4439-8cbc-3f83000d1f61)|

Tweak threadgate button sizing in the composer on Web

---

src/alf/fonts.ts

Overrides the global tracking for the `system` font variant back to what it was prior to 2419096e2409008b7d71fd6b8f8d0dd5b016e267
System @ 0.25px tracking
Inter @ `normal` tracking (the default, since it's a variable font with contextual-sizing enabled)

Type tweaks

---

src/lib/strings/display-names.ts

Adds a display name sanitation rule which reduces runs of spaces into a single space.
|Before|After|
|-|-|
|![CleanShot 2024-10-10 at 20 05 44@2x](https://github.com/user-attachments/assets/5f1d7d92-37e4-47a3-b55e-36ffe701a29d)|![CleanShot 2024-10-10 at 20 05 29@2x](https://github.com/user-attachments/assets/b40ad942-765a-4eb1-96b4-6ae8342bf012)|
With apologies to rem.

Sanitize multiple spaces in display names to protect against some security concerns

---

src/view/screens/Search/Search.tsx

Some multilingual users were surprised by the new filter on search results. By just showing the filters consistently, we can help people realize what's happening.

Always show search options

---

src/view/screens/Search/Search.tsx

- Removes duplicates in the language options
- Sorts by: user's configured content languages, then application's "common" languages, then alphabetical

Improve sort & filter of language options in search

---

src/App.native.tsx
src/lib/hooks/useIntentHandler.ts
src/view/shell/index.tsx

We did some tweaking for the composer state, and that provider is now being used beneath the `useIntentHandler()` hook. We can move this to `Shell`, which actually gives us some additional benefits:
- Composer doesn't open until the app is seemingly "ready" (no longer opens with the splash screen as could happen right now)
- We ensure that the session is ready to go before attempting to use an intent
We should check that everything still works correctly though.
- Compose intents work
- Video
- Images
- Verify email intent works

Move intent handler to a child of `InnerApp`

---

src/view/screens/SavedFeeds.tsx

Changes the "Edit Feeds" screen to bundle all of the changes into one save action. Also adds animations. Tested on web, ios sim, and android sim.
|Mobile|Desktop|
|-|-|
|https://github.com/user-attachments/assets/9c8f6fe6-da36-47f0-871c-70f4d42a8be7|https://github.com/user-attachments/assets/19258a16-e5e6-438a-abfc-c8984a3b5370|

Fix performance of feed reordering and add layout animations

---

src/view/screens/Search/Search.tsx

Multilingual users are now suffering due to the search default not covering multiple languages.
After https://github.com/bluesky-social/social-app/pull/5706 the control is constantly visible. We can just set the default to "all languages", so there's a nice clear prompt to change this if needed. Problem solved!

Make default search language 'all languages'

---

src/view/com/posts/AviFollowButton.tsx

A smaller avatar makes it a little bit harder to "tap". The avi follow button's hitslop is currently extending into the avatar a bit, and because the overall avatar hit area is smaller, its harder to "correctly" hit it unless you tap the top of the avatar.
At least on a simulator, this lets us tap in the area the user probably expects and tries to tap in. Need to test on a physical device to be sure though, since simulator is easy to not realize problems with irt hit area.

shift hitslop of avi follow button

---

src/view/com/composer/GifAltText.tsx
src/view/com/composer/photos/ImageAltTextDialog.tsx

I have been unable to reproduce this issue, but in the past the autofocus prop has caused problems with these types of dialogs. Let's remove it from the alt composer for now and see if that provides us any success. If it does, we can re-evaluate with a better fix later perhaps.
Things should work as they do now, though the input should not be focused immediately.

Remove autofocus from alt text input

---

src/components/Dialog/index.tsx
src/view/com/composer/GifAltText.tsx
src/view/com/composer/photos/ImageAltTextDialog.tsx

Fixes https://github.com/bluesky-social/social-app/issues/5705
Extremely weird case, but the `react-native-keyboard-controller` library requires us to do this here, since we enable and then disable it on the DMs screen. If we don't do so when opening/closing a dialog as well, we get into a weird state where the scrollview doesn't resize appropriately when needed.
Eventually, this won't be needed at all (see open draft PR for fully handling the scroll in swift) but for now let's do this since it's an easy OTA patch.
Observe the current behavior and the new behavior.
https://github.com/user-attachments/assets/fa38ebc9-70e9-450c-98ec-825653342d67
https://github.com/user-attachments/assets/bfb12ef9-44f6-4749-8bb3-ce26c2818a92

Fix keyboard hiding alt text input after viewing DMs on iOS

---

src/alf/fonts.ts

Fixes #5722
This font stack is something we've all been copying around for years, but looks like we should update it to include `system-ui`. Thanks to @byemc for pointing that out!
I pulled this `font-family` definition from GitHub itself and prepended `system-ui`.

Update web font families def

---

src/lib/api/index.ts

Using the same method as #5740, this PR marks 7 strings for translation in `src/lib/api/index.ts`.

Translate strings in `src/lib/api/index.ts`

---

src/view/screens/Search/Search.tsx

Fixes #5737
Previous logic was showing the Explore page if `query` was falsy, but `queryWithParams` is really the new source of truth for if the user has searched for something.
So this PR uses `queryWithParams` to determine if results should be shown. If params are present in the search query, this PR hides the "People" and "Feeds" tabs, which don't support params anyway.
Example searches
- `eric` — shows all 4 tabs
- `from:esb.lol` — shows only first 2 tabs
- `from:esb.lol javascript` — shows only first 2 tabs

Support params-only searches

---

src/view/shell/Drawer.tsx
src/view/shell/NavSignupCard.tsx

Started as a fix for Android, ended up moving some things around. Main thing is removing the `SafeAreaView`, idk why that wasn't working on Android. Totally my opinion here on space, open to feedback!

Drawer nits

---

src/view/shell/Drawer.tsx
src/view/shell/NavSignupCard.tsx
src/view/shell/index.tsx

- ALF'd most styles
- Made profile smaller, with extra bold display name
- Made slightly wider
- Made items closer together
- Added link to Chats screen (closes #5516)
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-15 at 09 03 31" src="https://github.com/user-attachments/assets/991726ee-a551-43d8-94ea-3e2be25af3c3" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-15 at 09 00 23" src="https://github.com/user-attachments/assets/dd5eded9-9b0c-4086-8f53-dda2af1acf6d" /></td>
</tr>
</tbody>
</table>

Clean up drawer

---

src/state/preferences/moderation-opts.tsx

`BskyAgent.appLablers` is a static property that's configured via `configureAdditionalModerationAuthorities` called in our session code. This was working for logged in users because `BskyAgent` internally runs this same bit of code when we call `getPreferences`. But for logged out users, we were only configuring the Bluesky labeler by default.
This PR uses the same source of truth for logged out users as for logged in users: `BskyAgent.appLabelers`. It applies the same `DEFAULT_LOGGED_OUT_LABEL_PREFERENCES` config as well.

Ensure all configured appLabelers are applied for logged out users

---

src/view/shell/Drawer.tsx

Based on #5761.
the desktop leftnav and the mobile bottom-bar accessibility hints used "Chat," so I have standardized it to "Chat" to allows for the use of previously translated strings in lingui.

Unified 'Chats' in drawers into 'Chat'

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/view/com/posts/FeedErrorMessage.tsx
src/view/com/posts/FeedShutdownMsg.tsx
src/view/screens/ProfileFeed.tsx

I noticed that there are [four files](https://github.com/search?q=repo%3Abluesky-social%2Fsocial-app+%22there+was+an+an%22+language%3ATSX&type=code&l=TSX) where `an` is repeated in some strings. This PR removes the repeated words.
Also, I noticed some logger error messages that say `Failed up` which – unless it's dev-speak or something? – I'm guessing should be `Failed to`, so I changed those too.

Remove double `an` from error message strings

---

src/view/com/pager/Pager.tsx

Just needed a cheeky `overflow: hidden` :)
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="500" alt="Screenshot 2024-10-17 at 11 22 32" src="https://github.com/user-attachments/assets/4e0f958b-c639-49b4-8f8d-527fec218be5" /></td>
<td><img width="500" alt="Screenshot 2024-10-17 at 11 22 05" src="https://github.com/user-attachments/assets/7920c396-13cd-4ad7-aa9b-9ee9e09c5943" /></td>
</tr>
</tbody>
</table>

Fix PageWithHeader header leaking into safe area

---

src/view/com/composer/labels/LabelsBtn.tsx

For @haileyok's consideration
<table>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-17 at 12 18 56" src="https://github.com/user-attachments/assets/10d88103-dd2d-4d65-8fe1-9f53dd97476c" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-17 at 12 20 18" src="https://github.com/user-attachments/assets/e67b49ea-9e79-4935-9b9d-eb54f27982dd" /></td>
</tr>
</tbody>
</table>

Moved self-label button tweak

---

src/view/com/composer/labels/LabelsBtn.tsx

I felt that we may as well change the icon to make it more clear that something was added. And I like allowing pressing on it even though no media is present, but I think we should make it clear why there are no applicable labels. In the future if we allow labels for posts without media, we'll need to tweak this, but the purpose of it can remain the same.

Tweak it moar

---

src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx
src/view/com/composer/threadgate/ThreadgateBtn.tsx

Move self-label button

---

src/locale/locales/de/messages.po

This is a tiny PR that cherry-picks a change from #5451 (which is in draft) that fixes a translation error in one of the German strings that I inadvertently introduced and partially fixes #5559.

Tweak `de` string

---

app.config.js
src/alf/fonts.ts
src/alf/tokens.ts
src/alf/util/unusedUseFonts.android.ts
src/alf/util/unusedUseFonts.ts

After a thorough investigation and a few hints here and there like [this one](https://stackoverflow.com/questions/43021540/custom-font-not-working-in-react-native/58765980#58765980), it would appear that RN for Android doesn't support `fontWeight` or `fontStyle` for custom fonts, and so in turn does not support variable fonts.
So the solve for this is to load separate font files for Android-only, and map weights and styles to the separate font files.
Android still appears to be using alternate glyphs for some characters, such as lowercase `a` (it's using `a.1`), but I haven't been able to determine how to turn those off on Android, and iOS and web still work correctly. So maybe that's an investigation for another time, since this seems to work fine otherwise and Inter technically supports …

Fix font display on Android

---

src/lib/api/feed/custom.ts
src/state/preferences/languages.tsx

Noticed two things were happening:
1. PWI wasn't applying mod authorities to `getFeed` requests
2. PWI language selector wasn't applying to `getFeed` requests
I don't think we've ever noticed the first, and the second I broke when I untangled `appLanguage` from `contentLanguages` in #5384. We used to set `contentLanguages` to match the `appLanguage` when that field was changed. I understood this to be a UX decision without realizing that it was load bearing for the PWI experience. Since post record `lang` field doesn't support regional codes either, I don't think this has ever worked as intended for "app" languages with region codes.
This PR borrows the labeler logic from our base `Agent` class, and pulls the language value we pass to `getFeed` from the `appLanguage` setting, stripping …

Apply labelers and handle language for PWI home

---

src/components/Dialog/index.tsx

Fixes https://github.com/bluesky-social/social-app/issues/5728
Copying the logic over to `InnerFlatList` for disabling drag when scrolled past an offset of 0.
Test the GIF dialog or the edit starter pack dialog on Android to see that scrolling works properly now.

Fix dragging up in flat list dialogs on Android

---

src/components/AppLanguageDropdown.tsx
src/components/AppLanguageDropdown.web.tsx
src/view/shell/NavSignupCard.tsx
src/view/shell/desktop/LeftNav.tsx

The little "card" in the top left was overflowing, this fixes that and improves spacing a bit
Now:

Fix NavSignupCard on web

---

src/view/com/util/fab/FABInner.tsx

Buzzes on press in and on press out, with a stronger buzz on long press
Curious how this feels

FAB double haptic experiment

---

src/view/com/composer/ExternalEmbedRemoveBtn.tsx

Evidently wasn't high enough in certain contexts ([video](https://github.com/bluesky-social/social-app/pull/5677#issuecomment-2423715433)). This seem to work not for all embed types.

Put ExternalEmbedRemoveBtn on top

---

src/lib/api/resolve.ts
src/state/shell/composer/index.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/shell/Composer.ios.tsx
src/view/shell/Composer.tsx
src/view/shell/Composer.web.tsx

Gonna stack a few little cleanups.
This first one removes the special `ComposerOptsQuote` type in favor of plain `AppBskyFeedDefs.PostView`. The `meta` returned when resolving post records now also becomes `AppBskyFeedDefs.PostView`.
In a follow-up, I'll change `meta` for other links to also use normal views.
Note that this is touching actual quote display — not just composer previews. Verify quoting different types of posts (no media, media, quote, external link, non-post record, gif, some combinations) still works. Both in the composer (where you should see a preview of what you're quoting) and after posting (there should be no regression in displaying quotes — both in the feed and in the individual posts). It would be good to check moderation has not regressed (blocks get applied etc). …

Refactor post meta to return PostView

---

src/components/StarterPack/StarterPackCard.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ExternalEmbed.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Resolves https://github.com/bluesky-social/social-app/pull/5608#pullrequestreview-2352564290.
This finally adds previews for non-post records. Including fixing the special case (presence of quote will now correctly hide post record previews since they won't actually make it to the post.)
<s>The "X" button is not aligned perfectly for all cases, feel free to edit it up.</s> Fixed.
Note that https://go.bsky.app/* links don't currently go through this codepath in development because `resolveShortLink` doesn't work in development. So if you try that one, you should see a regular link preview. It looks almost the same tho.

Display non-post embeds in composer preview

---

src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx
src/view/com/composer/state/composer.ts

We only want to show the "Labels" button right now whenever there is media in the post that a label can be added to.
The labels button should show up when:
- A link embed is included in the post
- A video is added to the post
- One or more images are added to the post
The labels should be reset whenever you remove all of the media from your post as well. To test, add an image to the post, modify the labels, remove the images, then add another image. The labels should have reset.

Conditionally render labels button when media exists in post

---

src/view/com/util/images/ImageLayoutGrid.tsx

Simply removes the aspect ratio of the container, since it didn't account for the gap
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2024-10-14 at 13 29 19" src="https://github.com/user-attachments/assets/e5452cf9-0e38-417f-b15d-185fb79eb477" /></td>
<td><img width="400" alt="Screenshot 2024-10-14 at 13 29 32" src="https://github.com/user-attachments/assets/ad2469fb-60d7-484b-997f-cd031493171a" /></td>
</tr>
</tbody>
</table>

Fix clipping issue with 2 image grid

---

src/components/StarterPack/StarterPackCard.tsx

just a silly flexbox issue
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-21 at 19 46 58" src="https://github.com/user-attachments/assets/a12ee3c0-6b71-464f-aa16-ef9ff8ea7b7a" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-10-21 at 19 46 47" src="https://github.com/user-attachments/assets/d41cf98a-48e9-4b59-a086-4c19daf3be2d" /></td>
</tr>
</tbody>
</table>

Fix starter pack text overflow

---

src/components/StarterPack/StarterPackCard.tsx

Quick follow up to https://github.com/bluesky-social/social-app/pull/5891. Just avoiding any UI breaks because of excessive line counts.
Should be no change from https://github.com/bluesky-social/social-app/pull/5891.

Limit number of lines in starter pack card

---

src/view/com/composer/Composer.tsx

When replying to a post, we should only render `<ComposerPills>` whenever there is media in the image. Right now, even though the pill itself doesn't get rendered, the container does and displays a border.
- Replying to a post shouldn't render the extra border at the bottom
- If you add an image to the post, it should render and the "Label" button should appear
- Creating a new post should always render pill container

Don't render `ComposerPills` when unnecessary

---

src/style.css
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx

There's a web-only min height on the composer, but having it always be on (even when there's attachments) is annoying. Twitter doesn't do that. This is the easiest way I found to adjust the behavior.
I've also adjusted the padding on mobile to be consistent between different attachment types.
https://github.com/user-attachments/assets/820ce96d-0c5e-4ecd-9af1-d8aa7b288518
https://github.com/user-attachments/assets/5d624a8a-736b-4aca-8f15-c20c84bf362b
https://github.com/user-attachments/assets/425f3c60-25ef-4518-bdea-d99c203035d5
https://github.com/user-attachments/assets/dc18cb6e-81fa-4667-81c1-8267e4b62142
Try all types of attachments on all platforms. (Including links, post embeds, list embeds, starter pack embeds.)
On the web, the expectation is that min-height is only enforced when …

Make composer min height conditional and align attachments

---

src/locale/locales/en/messages.po

Cleaned up en/messages.po to reduce size of messages.po for new language translators
- Removed old entries
- Removed one "translated" entry
- Added new messages since 1.92.1

Clean up English messages.po

---

src/view/com/composer/ExternalEmbedRemoveBtn.tsx
src/view/com/composer/GifAltText.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2024-10-28 at 23 19 22" src="https://github.com/user-attachments/assets/a5998276-e6f7-4ecb-90ec-3dbec50aaa90" /></td>
<td><img width="400" alt="Screenshot 2024-10-28 at 23 15 15" src="https://github.com/user-attachments/assets/88cd2bbc-74ad-4138-8cd8-8304f4cad163" /></td>
</tr>
</tbody>
</table>

Fix alt position

---

src/view/com/composer/Composer.tsx

This in preparation for the threaded composer. It doesn't quite make sense to treat this as an error — we should just prevent you from posting, same as we do in other invalid cases (like too long post or missing ALT).
In the second commit, I'm also replacing ad-hoc grey disabled styling with our normal disabled button. We've already been using the disabled button for the case when you _pressed_ post so let's use it here too.
Observe the initial state.
Verify that typing makes the button enabled.
Verify existing flows (adding image, filling alt, adding video, posting before it's uploaded) work like before.

Disable Post button when empty

---

src/lib/api/index.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/photos/Gallery.tsx
src/view/com/composer/state/composer.ts

Stacked on https://github.com/bluesky-social/social-app/pull/5953
---
This prepares the composer state structure to handle multiple posts in a thread. Previously we just had the `draft`. Now we have a `thread` made of `posts`.
Most of the reducer logic is now in `postReducer` which updates `PostState` in response to `PostAction`. The `postReducer` is being called for the current post from the outer `composerReducer`.
We're not actually taking advantage of this in the UI yet. The UI is the same and it only reads the current post's state (which is always the first post because we don't have any logic to add/remove posts yet).
Also, the publishing code only looks at the first post at the moment. That will be changed later.
Same as usual, verify different composer features work.

Refactor composer state for threads

---

src/view/com/composer/Composer.tsx
src/view/com/composer/state/composer.ts

Stacked on https://github.com/bluesky-social/social-app/pull/5953 and https://github.com/bluesky-social/social-app/pull/5945
---
Continues refactoring to prepare for threads.
This is a refactor to remove some intermediate variables that no longer serve us well. We want to read from `draft` directly so that we can later adjust the conditions to deal with multiple posts.
The last commit moves a grapheme length calculation to the reducer because we won't be able to memoize it in the component anymore (since it will be per-post).
Verify the discard prompt shows up when the post is non-empty (note that just a quote is considered empty).
Verify the grapheme calculations works like before, including with long URLs.
Verify missing ALT detection still works for images and for GIFs.
Verify Post …

Remove indirection when rendering composer state

---

src/screens/Profile/Header/Shell.tsx
src/state/lightbox.tsx
src/view/com/lightbox/Lightbox.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/post-embeds/index.tsx

This starts a stack of refactors to get the image open animation working.
In this PR, I'm just changing the model to be a plain object. There is no need for it to be a class. This aligns a bit better with the rest of the codebase and also fixes the unsound `as` casting in some of the code.
- Verify can click on avatar to view it full screen
- Verify can click on an image in a post
- Verify can click on one of multiple images
- Verify the gallery opens at the index that was clicked
Also, types.

Refactor lightbox model to plain object

---

src/components/SubtleWebHover.tsx
src/components/SubtleWebHover.web.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/Link.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx

Posts and notifications are interactive but we're currently not providing a clue.
This adds a very slight hover to the interactive tap target, similar as on Twitter. Our existing contrast options are too hard so I used a half opacity. Didn't want to add another color value.
[Review with no whitespace](https://github.com/bluesky-social/social-app/pull/5989/files?w=1)
https://github.com/user-attachments/assets/5b6f09e7-b0d9-4bf4-ba0b-45efcf40ca82
https://github.com/user-attachments/assets/2be88db9-10b1-478f-a2c3-144a866ed5af
https://github.com/user-attachments/assets/047aeb23-a01d-46dc-b448-0809d976446d
Web-only.
Verify posts in feed, posts in threads, posts in search, and different types of notifications.
Verify quotes get nested hover. Highlighted thread post should _not_ get hover.
Note …

Add subtle web hover to interactive rows

---

bskyweb/templates/base.html
src/screens/Deactivated.tsx
web/index.html

There were some crossed wires in the Deactivated screen, causing it to overflow mobile web. Mostly the fix here is ensuring the `#root` el that wraps our app has a width defined.

Fix width handling for deactivated screen

---

src/screens/Profile/Header/Shell.tsx
src/state/lightbox.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/lightbox/Lightbox.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx
src/view/com/util/post-embeds/index.tsx

Stacked on https://github.com/bluesky-social/social-app/pull/5999 and https://github.com/bluesky-social/social-app/pull/6000
---
When you click on an image preview in a feed, we need to know the screen coordinates of the image you clicked. This will later allow us to animate the image expanding into the lightbox.
In this PR, I'm measuring the screen coordinates for solo images and galleries in the feeds. The coordinates become a part of the lightbox state object and get plumbed into the lightbox component. The lightbox component doesn't use it yet.
Add `console.log(_thumbDims)` in `ImageViewing/index.tsx` and verify that the coordinates make sense. Do it on iOS and Android.
It should be `null` for profile images cause I haven't bothered hooking it up there. In general the code is supposed …

Measure tapped image coordinates before opening lightbox

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx

Not sure what's up with that and whether it's a regression. But I started seeing these warnings:
This marks all gesture handlers as worklets, which they should be.
Warnings are gone.
I am able to perform all gestures (pinch, pan, tap, double tap) on all platforms.

Explicitly mark lightbox worklets

---

src/screens/Settings/ExternalMediaPreferences.tsx
src/screens/Settings/Settings.tsx
src/screens/Settings/components/SettingsList.tsx
src/view/screens/PreferencesExternalEmbeds.tsx

[Settings] External media prefs revamp

---

src/screens/Settings/LanguageSettings.tsx
src/view/screens/LanguageSettings.tsx

Lazy restyling of existing components. I'd like to come back to this and make some nice universal <Select> components, but that's a fairly big job I'll leave for another time

[Settings] Languages revamp (partial)

---

src/components/forms/TextField.tsx
src/lib/strings/handles.ts
src/screens/Settings/AccountSettings.tsx
src/screens/Settings/components/AddAppPasswordDialog.tsx
src/screens/Settings/components/ChangeHandleDialog.tsx
src/screens/Settings/components/CopyButton.tsx
src/state/queries/handle.ts

https://github.com/user-attachments/assets/35284427-db0c-4732-a7ba-08bc40f05aa5

[Settings] Change handle dialog

---

src/screens/Settings/PrivacyAndSecuritySettings.tsx
src/screens/Settings/components/Email2FAToggle.tsx
src/view/screens/Settings/DisableEmail2FADialog.tsx

Tweak the copy when 2FA is enabled. No change to the disabled state
Happy to change the wording, unsure if "Change" is the right word

Tweak 2FA enabled state

---

bskyweb/templates/post.html
bskyweb/templates/profile.html

> [!NOTE]
> I'm not sure how to test this or if this is where the change needs to actually go. I've pattern matched against the received HTML in prod and found these files, so let me know if it's incorrect and I'll rework this!
See https://github.com/likeandscribe/frontpage/pull/172 for the description of why I'd like to make this change.
Some extra discussion here: https://bsky.app/profile/did:plc:2xau7wbgdq4phuou2ypwuen7/post/3l7esaih44s2s

Add AT URIs as alternate links

---

bskyweb/templates/profile.html

re: #6033
what do we think chat? this disambiguates Bluesky profiles from ATProto identities. 
after writing this, I've just seen [mary's comment](https://github.com/bluesky-social/social-app/pull/6033#issuecomment-2451109988) raising the same issue

Link to app.bsky.actor.profile record in link rel=alternate

---

src/view/com/composer/Composer.tsx
src/view/com/composer/state/composer.ts
src/view/com/composer/state/video.ts

Stacked on https://github.com/bluesky-social/social-app/pull/5953, https://github.com/bluesky-social/social-app/pull/5945, https://github.com/bluesky-social/social-app/pull/5954, and https://github.com/bluesky-social/social-app/pull/5955
---
Same as https://github.com/bluesky-social/social-app/pull/5955 but for videos.
Go through the usual flows with a single video. Upload it, change dimensions, post while uploading too, etc.
Also verify error path works too. And clearing errors.

Check video state for the entire thread

---

src/view/com/composer/Composer.tsx
src/view/com/composer/state/composer.ts

Stacked on #5962 
---
Easier to review the whole diff.
Does a couple of things:
- Turns off `input.focus` into previous post after deleting a post on Android. This unfortunately risks doing something weird with the keyboard where the input ends up behind it and the scroll view becomes unaware there is more to scroll. I.e. it breaks `KeyboardAvoidingView`. I found no other fix than to disable the behavior.
- <s>Replaces `ScrollView` with `KeyboardAwareScrollView` which on its own (even without the above fix) seemed to significantly reduce how often the above issue occurred. Although I did disable the `focus` calls, I suspect they're not the only cause, so I've left this fix in too.</s>
- Actually removed this — caused issues on iOS and didn't seem necessary after the fix above.
- Changes …

Fixes for thread composer on Android

---

src/lib/api/feed/utils.ts

For convenience when trying new flags.
Not sent to non-bsky feeds:
Bsky feeds still normally receive the topics header:
But http://localhost:19006/?debug_topics=1234 overrides it:

Override X-Bsky-Topics with a debugging param

---

src/view/com/post-thread/PostThreadFollowBtn.tsx

For consistency with other Follow buttons and for general legibility.
https://github.com/user-attachments/assets/6a323bd7-bc6d-49de-b024-173c783c53b1
https://github.com/user-attachments/assets/9ec6bc6b-c301-4f19-8fdf-de341297a7e0
https://github.com/user-attachments/assets/1ddae2bc-519a-4259-96d5-85b7da630caf
https://github.com/user-attachments/assets/4665c5b3-250c-4e43-a307-791eba791c82

Change post Follow button color on toggle

---

src/screens/Profile/Header/Handle.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

fix text clipping around external embed's domain

---

src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx

Due to multiple subscriptions to the same global emitter, things were getting duplicated on the web.
Now there is only one active subscription, corresponding to the active input.
- Draft a thread and press Cmd+Enter.
- Before: Thread gets posted N times.
- After: Thread gets posted once.
- Drag an image from desktop.
- Before: Image gets inserted into each post N times.
- After: Image gets inserted into the current post once.
- Paste an image from clipboard.
- Before: Image gets pasted into each post.
- After: Image gets pasted into the current post.
- Choose an emoji in the web picker.
- Before: Emoji gets added to every post.
- After: Emoji gets added to the current post.

Fix duplicates in thread composer

---

src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx

- Fix overlapping "X" button. Now the input will have a right padding if you have >1 post. Same as Twitter does.
- Make the bottom toolbar sticky on web. This ensures it's visible when you start squeezing the window vertically.
- Change toast message to imply all posts are posted.
- Sticky bottom autoscroll now only activates if the last post is active. (It was confusing/annoying otherwise.)
https://github.com/user-attachments/assets/341adea3-99c0-4d99-9e62-5f3bb74f2cbd
https://github.com/user-attachments/assets/0ee0484b-9050-48d9-a68f-0518a349aac5
https://github.com/user-attachments/assets/f1cc57e0-070f-4584-bd45-4d73f79e6556

Composer UI fixes

---

src/alf/atoms.ts
src/components/Button.tsx
src/view/shell/desktop/LeftNav.tsx

I noticed focus outlines on buttons are overflow most of the time.
The behavior replicates in currently deployed app on all browsers I tried (Safari, Firefox, Chrome)
Tried to improve it by adding `outline-offset`.
`outline-offset` do not seem supported by the Atoms convention, yet it seem [widely available](https://developer.mozilla.org/en-US/docs/Web/CSS/outline-offset).
Here is tab navigation before the PR:
You can notice almost all outlines overflows their parent container.
And here it is after the changes:
I think we could also improve the outlines for avatar/collapse button by using `tabIndex` prop, the TypeScript errors made me question it.

Improve focus-visible outlines in navigation

---

src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/components/Menu/types.ts
src/view/com/pager/TabBar.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

This PR improves accessibility by turning skeet controls (Translate, Reply, Reskeet, Like, Share, More) actual buttons instead of `div`s with an event handler.
Same with tabs such as on profiles, they are now properly marked as tabs for assistive technologies to pick up.
Closes #4409

fix(a11y): avoid plain `div`s as button or tabs

---

src/screens/Profile/Header/Shell.tsx
src/state/lightbox.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/lightbox/Lightbox.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/post-embeds/index.tsx

Stacked on #6047
---
No changes to behavior.
This may be easier to read commit by commit.
- I get rid of the `cloneElement` and the weird data flow where the footer reads data via the hook. A more natural way to express this is to have the parent component pass a render prop to the child, closing over the lightbox data.
- Then I get rid of the two lightbox types. As far as the lightbox is concerned, everything here is images. It shouldn't be thinking about profile pictures etc. This makes it annoying to evolve the code. So I unified the types.
- Then I refactor `LightboxFooter` to take all `images`. This is a bit cleaner and allows it to make its own decisions about how to deal with them (right now it just reads the current one, but it doesn't have to).
- Finally, I decide to move …

Refactor lightbox prop drilling

---

src/screens/Settings/ThreadPreferences.tsx

#6051, except using `<Trans>` instead of `_(msg``)`

Translate sort replies

---

src/view/com/notifications/FeedItem.tsx

#5550 switched the spacing around the middot from whitespace characters to margins. Unfortunately this does not work, I'm unsure why - but it would definitely not work with text scaling, so probably best not to use it even if it did work.
This reverts it to just use whitespace again

Fix notification time spacing

---

src/screens/StarterPack/StarterPackScreen.tsx

Spotted a minor layout misalignment, when processing "Follow All" action on the Starter Pack screen.
https://github.com/user-attachments/assets/d98bb3ae-3d30-4a73-a4f3-f533b58895e6
Move activity indicator out of Text node, apply simple layout to the Button container.
https://github.com/user-attachments/assets/32568f01-ca72-43da-91b3-7511783809f1
https://github.com/user-attachments/assets/f2abf704-41fb-4395-a98f-d2fe2f1fc119

StarterPack: fix "Follow All" processing layout

---

src/lib/media/video/compress.web.ts

Backend uses 50 megabytes (1000 * 1000 * 50) but frontend was using 50 mebibytes (1024 * 1024 * 50)

Use megabytes rather than mebibytes for video limit

---

src/components/forms/SearchInput.tsx

This PR resolves issue #5845 by increasing the `zIndex` of the clear button in the search bar from 10 to 20

Fixed issue where X in search bar does nothing

---

src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarWeb.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/desktop/LeftNav.tsx

- use correct accessibility properties and fix up labels
- hide the icons
- group screen content into a `<main>`  - DANGER: this adds a wrapping element to the whole page. Unfortunately React Navigation doesn't do this for us. I recommend checking around the app to see if this breaks any screens. The React Navigation element I'm wrapping appears to just have `flex: 1` on it, so it should be fine to add the same
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2024-11-05 at 16 22 02" src="https://github.com/user-attachments/assets/8856d687-f184-4511-b353-5d271f851a61" /></td>
<td><img width="400" alt="Screenshot 2024-11-05 at 16 22 25" src="https://github.com/user-attachments/assets/28b9b0bb-a699-42af-b971-085d9678c66c" …

Improve accessibility for navigation on web

---

src/state/feed-feedback.tsx
src/view/com/util/List.tsx
src/view/com/util/List.web.tsx

We have quite enough content now, repetition is a bigger problem. Let's consider an item "seen" if it's onscreen for 0.5s (down from 1.5s). Let's also send stats a bit more often (10s, down from 15s).
Log `interactions.length` in `sendToFeedNoDelay` on each platform. Verify that a relatively fast-paced casual scroll now registers ~2x items.

Lower feedfeedback seen threshold to 0.5s

---

src/state/lightbox.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/lightbox/Lightbox.tsx

I want to get rid of these constants. They're subtly wrong in some cases, and it's very hard to think about the discrepancies due to safe insets. I want to change the code so that we rely on `SafeAreaView` and then everything is derived from its size.
I'm not entirely _sure_ this approach is the way to go, but this constant just sucks so I think it's a step forward.
The approach is to use alternatives to hardcoding `SCREEN`:
- On UI thread, use `measure(safeAreaRef)`. This always gives the height matching the area where we draw the image.
- Curiously this _seems_ fine to do on every frame. So I'm just doing that unless proven wrong.
- We might have to do something more fancy when adding orientation handling. But still better than before.
- On JS thread, prefer to use `<SafeAreaView>` …

Remove SCREEN from lightbox layout

---

src/lib/custom-animations/CountWheel.tsx
src/lib/custom-animations/LikeIcon.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

Fixes #6118 
Summary: We display an animation when the post is liked on the Post screen around `Like` button. However, when the post is already liked, we still display the animation UI with 0 opacity without an animation. That seems problematic on iOS because there is a noticeable thin red circle displayed even though its opacity is set to zero. I think it has something to do with how iOS handles UI rendering or how `react-native-reanimated` library handles keyframes.
Solution: The animation is completely removed from DOM tree when unnecessary. When necessary, it gets mounted and displays the animation as usual. It results in the reported issue being fixed while not impacting the current animation implementation.
Updated behavior: …

Fix thin red circle around Like button on iOS

---

src/screens/Settings/AccountSettings.tsx
src/screens/Settings/components/SettingsList.tsx

Forgot to do this in the main PR! Verify email button didn't do anything lol
Also made the blue button be the verify email prompt (I think that was the intention in the design) but I made the wording clearer
<table>
<thead>
<tr>
<th>Not Verified</th>
<th>Verified</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" alt="Simulator Screenshot - iPhone 16 - 2024-10-31 at 20 55 53" src="https://github.com/user-attachments/assets/3698677c-9112-42e5-9ea2-6db69a61d5e4" /></td>
<td><img width="300" alt="Simulator Screenshot - iPhone 16 - 2024-10-31 at 20 56 21" src="https://github.com/user-attachments/assets/7cea36c1-ca13-4993-b029-e440c32b0015" /></td>
</tr>
</tbody>
</table>
Also fixed truncation for large text/long emails

[Settings] Link up verify email dialog

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx

If the image resolution is low, both iOS and Android lightboxes didn't let you pinch it at all, and double tap would zoom it _out_. This fixes the issue by ensuring the max zoom scale we pass to the scroll view is always positive. I set it to allow at least 2x magnification (for small images — for highres images it would magnify more, as before).
Try this post: https://bsky.app/profile/neoxperson.bsky.social/post/3kaxlxr5tv622
Previously, the lightbox would zoom out on double tap. Now it slightly zooms in (and pinching also works).

[Lightbox] Set 2 as minimal allowed zoom level

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx

Previously, iOS used a scroll listener on the ScrollView to determine the "swipe the image away" gesture. On Android, we had a gesture recognizer. This setup had a few downsides:
- The thresholds felt inconsistent between platforms
- The "fly away" gesture animation didn't really make sense
- It was not "flying away" on iOS at all, just abruptly disappearing
- We were changing the image opacity against a black background, whereas usually an animation like this changes the _backdrop_ opacity against the app itself
- The way the ScrollView was laid out on iOS caused dark bars to be part of the scrollable area when zoomed in
This is a rewrite of that gesture. I'm lifting it up to the parent component (which lets me animate the backdrop and controls based on it). I'm also adding a "flying …

[Lightbox] New dismiss gesture

---

src/components/dms/ActionsWrapper.tsx
src/screens/Messages/Conversation.tsx
src/screens/Messages/components/MessagesList.tsx

Incorrect use of worklet functions in gestures was causing upwards of 7 seconds of delay when rendering chat items
Also fixed accessing UI thread values in render (in hook deps)
Confirm chats open 2x as fast
Confirm gestures still work (long press + double tap)

Improve chat performance

---

src/view/shell/desktop/Feeds.tsx

On desktop, when the current feed is selected from the right nav, that performs a soft reset of the current screen. This behavior is expected when the current screen is Home, but it's unnecessary on every other screen since the app will immediately navigate to Home anyway.
In fact, this soft resetting manifested as a bug where selecting the "current" feed (the feed that was last accessed) while on the Search screen will fail to navigate to Home, since soft resetting the Search screen involves a navigation, which cancels the navigation to Home.
I just made it so that it only soft resets on Home, since that's the only place where we want that, I think

Fix non-home screen soft resetting when feed is selected from right nav

---

src/view/com/lightbox/ImageViewing/index.tsx

Fixes a regression I introduced in https://github.com/bluesky-social/social-app/pull/6135.
See commit by commit.
This is tricky to reproduce, but if we got `onEnd` (which "flying away") while `dismissSwipeTranslateY.value === 0`, the decay animation ("flying away") would not even start. This looks like a Reanimated bug. Simply shifting the initial value by pixel does the job.
Other commits are minor improvements.
The easiest way to repro is to actually comment out `dismissSwipeTranslateY.value = e.translationY` in `onUpdate` or to hardcode it to `dismissSwipeTranslateY.value = 0`. Before the hack/fix, this would freeze up the lighbox. Now, it works.

Fix stuck lightbox

---

src/view/com/util/images/ImageLayoutGrid.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" alt="Screenshot 2024-11-08 at 12 10 54" src="https://github.com/user-attachments/assets/a0efe04c-fdb7-44b3-bedc-bbf260d20c72" /></td>
<td><img width="300" alt="Screenshot 2024-11-08 at 12 10 32" src="https://github.com/user-attachments/assets/473cf6d5-94a5-4c08-b601-f47c870acfda" /></td>
</tr>
</tbody>
</table>

Fix 3 image grid in DMs

---

src/view/com/composer/text-input/TextInput.tsx

Fixes #5917 
1. Recording (before & after)
before: [android-before.webm](https://github.com/user-attachments/assets/069569a9-96bd-4ac4-a754-d1043f4f1591)
after: [android-after.webm](https://github.com/user-attachments/assets/90689fe9-4924-43b3-b58b-6f4caa3f48a1)
2. Summary
This issue is cosmetic and happens only on Android. The problem is that when users enter a new line and start typing, the height of the TextInput slightly increases for some reason. It can be annoying to sensitive users because the position of the entire text keeps going up and down.
I did some research, and it seems setting `includeFontPadding` to false fixes the issue. This style is specific to Android and has no implications for iOS. I tested and confirmed this change doesn't affect iOS or other functionalities. …

Fix: Text keeps going upward and downward when entering a new line on Android

---

src/screens/Settings/ThreadPreferences.tsx

The new Settings screens look great, but when trying them out I just noticed one tiny thing. In my opinion it looks a bit strange to have a `.` at the end of the Prioritize your Follows label string:
This tiny PR removes it so that it becomes simply:
`Show replies by people you follow before all other replies`

Tiny tweak to Thread Preferences string

---

src/view/com/util/images/AutoSizedImage.tsx

Broke this in https://github.com/bluesky-social/social-app/pull/6159.
## After

Fix web image layout

---

modules/bottom-sheet/ios/SheetViewController.swift

Fix Retain Cycles in `SheetViewController.swift`
This pull request addresses potential retain cycles in `SheetViewController.swift` to improve memory management. Key changes include:
- Added `[weak self]` in the closure of `sheet.animateChanges` in the `updateDetents` method to prevent `self` from being strongly captured.
- Also captured `sheet` weakly in the closure to avoid any potential strong references retained by `animateChanges`.
These changes ensure the `SheetViewController` and its `UISheetPresentationController` are properly deallocated when no longer needed, preventing memory leaks while maintaining the functionality of the class.
**Reference**
- [**Apple Documentation on Memory Management**](https://developer.apple.com/library/archive/documentation/Swift/Conceptual/Swift_Progra …

Fix Retain Cycles in SheetViewController

---

src/components/Error.tsx

Error screen height collapsed due to some sort of flexbox issue. I would love to know the root cause, but changing `flex_1` to `w_full` fixes it for now
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot 1" src="https://github.com/user-attachments/assets/996db362-40d7-4ab4-aa29-d4be90ed412b" /></td>
<td><img width="200" alt="Simulator Screenshot 2" src="https://github.com/user-attachments/assets/df22d067-4246-4d7d-a0a1-fae5664ebe13" /></td>
</tr>
</tbody>
</table>
- Get to the screen by finding a post with one repost, blocking that person, and then going back to the screen (or edit code to make the query return [])
- Check it now works on all platforms
- Confirm that the component still works in other places (i.e. …

Fix error screen

---

src/view/shell/index.web.tsx

So, this PR is related to this issue: #6200. Currently, BlueSky blocks the body scroll when the navigation drawer is opened: https://github.com/bluesky-social/social-app/blob/89c93313a3fc3123a2e53856f53cc8cea8e693fa/src/view/shell/index.web.tsx#L36
The problem is that when users switch to mobile mode, open the drawer, and then switch back to desktop mode, the navigation drawer is still considered open, which is incorrect. I’ve implemented a quick fix here to automatically close the drawer whenever the user exits mobile mode.

Fix unscrollable body when returning to desktop mode from mobile mode with navigation drawer open.

---

src/components/dms/MessagesListHeader.tsx
src/screens/Messages/components/ChatListItem.tsx

Enables translation of the "Deleted Account" string displayed on the Chat page.

Enable translation of "Deleted account"

---

bskyweb/cmd/embedr/server.go

Allow more spikiness in embedr rate limits to service pages with many embeds.

Embedr: increase rate limits for short spikes

---

.github/workflows/build-and-push-embedr-aws.yaml
Dockerfile.embedr
bskyweb/cmd/embedr/server.go

A recent change to the supported node version needed to be synced-up in embedr's dockerfile.

Embedr: fix build / node version

---

src/view/com/util/MainScrollProvider.tsx

This was a major WTF moment for me and I'm still not sure to what extent this is actually useful. However, the [Android GPU profiler](https://developer.android.com/topic/performance/rendering/profile-gpu) seems to be happy about this change.
There is some information about how Reanimated closures work here: https://github.com/software-mansion/react-native-reanimated/issues/3670#issuecomment-1303388096
We're closing over `withSpring` which I assume means that [this clone function](https://github.com/software-mansion/react-native-reanimated/blob/66137a6b084d787e5d98aa496d66b83cbd204d71/packages/react-native-reanimated/src/shareables.ts#L103-L291) will have to go into `withSpring` itself, deal with _its_ closures over top scope, and so on. I haven't tried logging what's going on there but I …

Reduce Reanimated serialization traffic

---

src/view/shell/bottom-bar/BottomBarWeb.tsx

Fixes #6253 
1. Summary
Bottom padding is 2px whereas the top padding is 14px for the login/signup footer on mobile web view
2. Solution
I am not sure which value will make it look best aesthetically, but I went with 14px for both top and bottom paddings for now.
3. Screenshot

Fix login footer not being vertically centered on mobile web view

---

src/components/SubtleWebHover.tsx
src/components/SubtleWebHover.web.tsx
src/view/com/posts/FeedSlice.tsx

>[!NOTE]
>I had to actually fake the position of the highlight, since the actual box is a weird shape. Not really noticeable when mousing over imo but feels a lot better than the real shape
>for comparison, this is what it looks like if we don't fudge the position
><img width="657" alt="Screenshot 2024-11-12 at 15 15 41" src="https://github.com/user-attachments/assets/c2d2c7ce-50da-408f-abed-bff3b8d18017">

Add subtle web hover to "View full thread"

---

src/view/com/util/PostMeta.tsx

very minor, but since this is in the hot path there's no point calling the same function twice

Dedupe date parsing in PostMeta

---

package.json
yarn.lock

Fixes: #6269 
1. Summary
The issue is related to the drawer from `react-native-drawer-layout` library. I confirmed that by removing the drawer in the code.
2. Solution
I upgraded `react-native-drawer-layout` to the latest version(v4.0.1) to see if that fixed the issue, and apparently, it did. I tested the app on Android, iOS, and desktop, and it seemed it didn't introduce any additional bugs/issues.
3. Recording
https://github.com/user-attachments/assets/32300a0b-a86b-45e0-8ccb-18ef3e508492

Fix exiting video player from full screen in the landscape mode shifts UI up

---

src/view/com/post-thread/PostThreadItem.tsx

Add subtle web hover to treeview replies

---

src/components/forms/ToggleButton.tsx

Fixes #6185 
1. Summary
`Show badge` label is cut off on the developer labels page.
2. Solution
Before: 
After: 
The fix looks better than being cut off, but I am unsure if it is the best solution to the problem. I can think of different ways of solving it, and here are some of them
- Updating the label to say `Show` instead of `Show badge`
- Increasing the button width for all 3
- Put the toggle group underneath `title/description` section like on mobile devices
I guess, I need some design inputs here on what is the desired behavior aesthetically.

Fix 'Show badge' button label being cut off

---

src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/util/List.tsx

- Tweak lightbox animations to have smaller durations
- Smaller velocity threshold for the dismiss gesture
- Disable iOS "scroll to top" while lightbox is active to prevent unintentional feed scrolls

[Lightbox] Small tweaks

---

src/components/forms/ToggleButton.tsx
src/components/moderation/LabelPreference.tsx

Can't find a perfect way to handle these in all cases, so to retain flexibility and not break layouts, let's just make these full-width. We may also investigate a different pattern for mod settings in the near future.

Make `ToggleButton` full width everywhere

---

src/components/dms/dialogs/SearchablePeopleList.tsx

Spotted that "New Chat" dialog container includes an extra padding on the web, which seems unintended. It also causes a visual clipping at the end of the users list.
Modify the default inner container style for web by `webInnerContentContainerStyle` prop.
This fix also applies to `SendViaChat` dialog.
Tested the changes by running app locally, made sure that the new styles does not affect native platforms.

NewChatDialog: remove extra padding on web

---

src/view/com/lightbox/ImageViewing/index.tsx

It always felt off to me, so I wanted to change it. lmk ur thoughts on this PR.
<table>
<tr>
<th>After</th>
<tr>
<td>
https://github.com/user-attachments/assets/991013cd-68ad-4bd6-8d24-25f42fb11f56
</td>
<td>
https://github.com/user-attachments/assets/8d13a4ca-917c-4e2d-af11-df414f21801f
</td>
</tr>
<tr>
<td>
https://github.com/user-attachments/assets/5671fb47-1576-40d1-9db0-56790380c062
</td>
<td>
https://github.com/user-attachments/assets/0a19d2bb-33ba-4bf1-b7b9-ee4c8770418e
</td>
</tr>
</table>
sorry I'm a bit perfectionistic when it comes to animations.

Tweak shared element animation to make it much smoother

---

src/state/messages/convo/const.ts

Stacked on #6378
Reduces poll interval for active chats from 3s to 4s, and polling on the messages list screen from 10s to 30s. Background polling doesn't matter here, all platforms pause polling when backgrounded atm.

Reduce calls to getLogs

---

src/lib/strings/errors.ts

- Added `NotEnoughResources` and `pipethrough network error` to the generic server error message
- Translated errors
imo it's fine to use the `t` macro here, since error messages should not be sticking around in the tree, and imo it's an acceptable tradeoff if maybe you see one in the wrong language immediately after switching langs, vs current behaviour
Potential problems might arise from checking against the output of `cleanError` and expecting one of the now-translated strings to still be in english. however I did a cursory check of the references and it seems fine

Better error message (+ translations!)

---

src/view/shell/index.tsx

Seems like when upgrading react-native-drawer-layout there was a regression where `drawerType` is always `front` despite what the docs say. It should be `slide` on iOS
Confirm that it is indeed broken on iOS without this change
Confirm this change fixes it

Manually implement `drawerType` logic

---

src/locale/locales/fr/messages.po

It's been a few months (and the 10 million followers celebration 🥳) that we didn't update the French translations!
Two million more accounts later, there are a mere 86 strings to translate, so it was quick. It was pretty easy to do, although I did spot a mistake we'd made earlier (`Display name` translated as `Afficher le nom`, when it should read `Nom d’affichage` — damn you, English terseness!).
@surfdude29, could you please try to review those translations? Even though we are used to the reverse, I am sure your pair of eyeballs could help catch a weird thing or two :)
✍️ **Edit:** Just did a last-minute self-review and [pushed a few changes](https://github.com/bluesky-social/social-app/compare/0818c6d0c4d48960f217578dbb3cd55777ffb6cf..f471458331fe732f76d108651f5d1963c175568f), but that …

Update French translations (November 9th, 2024)

---

src/locale/locales/ga/messages.po

Back in sync with the msgid's in src/locale/locales/en/messages.po.  The command-line (gettext) tools that I use drop the #~ messages... I assume that this isn't a problem. Thanks!

Update Irish localization

---

src/locale/locales/es/messages.po

Minor things I've seen while using the app and then reviewing some of the texts:
- Use 'pack de inicio' instead of 'paquete de inicio'
- Use 'Inténtalo' instead of 'Intenta'
- Fix 'Por favor'
- Do not use 'una' as article for 'posts'
- Use 'Eliminado' instead of 'Removido'

Fix minor localization issues in Spanish:

---

src/locale/locales/it/messages.po

The word "open" can be a verb like in "Open avatar creator" or an adjective (e.g. "Bluesky is open"). This commit replace the verb "Apri" with the adjective "Aperto".

Fix the translation of the adjective "open"

---

src/state/queries/post-thread.ts

Only affects non-self posts. Own posts are still bumped to the top.
https://github.com/user-attachments/assets/719cf1ad-ccd7-4cf1-877e-69476f77f9c2
https://github.com/user-attachments/assets/b50c5c91-ef24-473f-aa5e-9c69bafe802f

Sort pins last in thread view

---

src/view/com/util/Link.tsx

This adds the "soft reset" behavior to the web version of the `Link` component used by the bottom tab bar, bringing it in correspondence with [similar native logic](https://github.com/bluesky-social/social-app/blob/3c30bb1d358c6544170b8d334c5ee0530020a566/src/view/shell/bottom-bar/BottomBar.tsx#L91-L94). As a result, tapping on bottom bar icons on mobile web _while already in that tab_ finally refreshes the content. Previously, the content would not refresh, which was both inconsistent with the mobile apps and misleading. (Previously you had to tap the "show new" button to make any new notifications show up, for example.)
I initially thought I would add it to `BottomBarWeb.tsx` but this wasn't feasible because of how the decision to handle new tab vs same tab links is structured. This …

[Web] Clicking root link twice refreshes the screen

---

src/view/com/composer/Composer.tsx
src/view/com/composer/videos/VideoTranscodeBackdrop.tsx
src/view/com/composer/videos/VideoTranscodeBackdrop.web.tsx

Replaced a very bad and probably broken asymmetrical useEffect with a proper cleanup function that gets called when the composer closes
Make sure video compression still has the thumbnail
Try adding a video, closing the composer, then adding the same video again

Fix video thumb cleanup

---

src/Splash.tsx
src/components/Loader.tsx
src/components/ProgressGuide/Toast.tsx
src/components/anim/AnimatedCheck.tsx
src/components/dms/ActionsWrapper.tsx
src/components/dms/ChatEmptyPill.tsx
src/components/dms/NewMessagesPill.tsx
src/lib/custom-animations/GestureActionView.tsx
src/lib/custom-animations/PressableScale.tsx
src/lib/hooks/useMinimalShellTransform.ts
src/screens/Messages/components/MessageInput.tsx
src/screens/Messages/components/MessagesList.tsx
src/screens/Profile/Header/GrowableAvatar.tsx
src/screens/Profile/Header/GrowableBanner.tsx
src/state/shell/minimal-mode.tsx
src/view/com/composer/Composer.tsx
src/view/com/home/HomeHeaderLayout.web.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/util/BottomSheetCustomBackdrop.tsx
src/view/com/util/List.tsx
src/view/com/util/MainScrollProvider.tsx
src/view/shell/bottom-bar/BottomBar.tsx

Manually went through our codebase and fixed up all cases. I used find-all search for `useSharedValue`, `useDerivedValue`, and `.value` accessors.
Ran into a Reanimated bug with `set()` functions, but it was easy to work around: https://github.com/software-mansion/react-native-reanimated/issues/6613#issuecomment-2479870214. You just have to add `() =>` when setting it to animations, like `set(() => withStuff())`.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/6391/files?w=1)
Tried to find each of these components on iOS, verified common interactions work. Tried most of these Android, wouldn't expect platform differences with this API switch.
Look closely through the code: `set(withFoo())` would fail. It has to be `set(() => withFoo())`. However, `set(x)` is …

Use compiler-safe Reanimated get/set APIs

---

src/view/com/util/forms/PostDropdownBtn.tsx

Reverts bluesky-social/social-app#6437
I missed that this breaks the dialogs. I'm struggling to figure out a way to split the component in a way that the current `useDialogControl` / `<Dialog>` abstraction still works so let's revert for now.
Dialogs in the sheet work again.

Revert "Render dropdown menu items lazily"

---

src/components/moderation/ContentHider.tsx

Currently inside the `ContentHider` we're running a lot of Hooks (which read context, loop through stuff, create intermediate object, memoize them, and so on). However, none of those values are used if there's no actual blurring.
I'm splitting the component in two. The top part is a fast path if there's no blurring.
Note that this means that if the "has blur" condition flips somehow while the component is onscreen (is this possible?), the state of the inner component will reinintialize from scratch. I'm not sure whether this is an issue.
Verify both blurred and non-blurred posts show up. (You'll need to find some posts that are blurred under your settings.)
The `ContentHider` self-time shows up in traces:
The `ContentHider` self-time doesn't show up in traces:

Optimize ContentHider

---

src/view/com/util/images/AutoSizedImage.tsx

I've noticed the `aspectRatio` value here fluctuates between user-submitted measurement vs measurement on fetch. The fluctuation is small but this leads to an extra setState and potentially to tiny layout jumps. And if the aspect ratio was not specified at all, the layout jump can be significant — per each such image.
We should *never* layout jump in feed. So let's either use the provided aspect, or assume it's a square.
Also lets us avoid a setState.
Verify images show up appropriately sized, as before (try tall, wide, square images).
Comment out the `= image.aspectRatio` part and verify that missing measurements are handled gracefully.
Verify lightbox works in all cases.

Fix layout jumps for images

---

src/view/com/util/post-ctrls/RepostButton.tsx

The usual refactor to avoid creating JSX eagerly.
Repost button and dialog still works on iOS, Android.

Extract RepostButton inner dialog

---

src/view/com/util/post-embeds/ExternalGifEmbed.tsx

We should consider layout jumps in the feed unacceptable. Since we don't know the height here, let's just hardcode it. There aren't a lot of Giphy gifs. Going forward (especially with custom upload) we might remove this player altogether.
NB This only affects _Giphy_ gifs.
Find some posts with Giphy gifs (e.g. https://bsky.app/profile/ladykalana.bsky.social/post/3lakrc2au3k2y). Verify they look reasonably decent and that there is no layout jump on load.

Hardcode Giphy embed height

---

app.config.js

Help Siri to correctly pronounce Blue Sky. Instead of pronouncing it like “Lebowski”, i.e. “bluski”.

Help Siri to correctly pronounce Blue Sky.

---

src/components/Dialog/index.tsx
src/components/TagMenu/index.tsx

It is expensive to run all these `useMutation` hooks and construct all this JSX, only for it to be thrown away / needed on tap.
At least it's expensive on low-end Android. (In dev mode, but it would be bad in prod too.)
Instead, we want this:
How? Move all the logic down to the case where the menu is actually shown.
One quirk is that `useNavigation` stays above because we don't use real portals on native. So the context would be wrong otherwise.
I've also fixed a place where we swallow an error message which made debugging hard.
[Review sans whitespace](https://github.com/bluesky-social/social-app/pull/6483/files?w=1)
Native only change.
https://github.com/user-attachments/assets/eed139c2-e1a3-40fe-af17-0a176fd960b0
https://github.com/user-attachments/assets/d9ebaa76-6c7a-4d90-a9aa-7061958 …

Fix TagMenu initial render perf

---

src/lib/hooks/useHandleRef.ts
src/screens/Profile/Header/Shell.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx
src/view/com/util/post-embeds/index.tsx

We use `useAnimatedRef` in a bunch of places just to get the measurements with `measure`. This is unfortunate because it contains [two shared values](https://github.com/software-mansion/react-native-reanimated/blob/36c291a15880c78a94dd125c51484630546ceb7c/packages/react-native-reanimated/src/hook/useAnimatedRef.ts#L46-L47), one of which stores an internal React node. I'm not sure whether that node goes through the serialization mechanism but the profiler was showing some overhead associated with each `useAnimatedRef` component.
In this PR, I'm taking just the part that we actually need — reading the component's internal handle. I'm doing the same thing [`findNodeHandle` does](https://github.com/facebook/react/blob/4beb1fd8bacacd3f4faeb180bca00ea0edcf27e4/packages/react-native-renderer/src/ …

Add useHandleRef as a lighter alternative for useAnimatedRef

---

metro.config.js
package.json
src/App.native.tsx
src/AppProfiler.tsx

This adds `yarn android:profile` which produces a prod-like build that logs each React render phase. To read the log output, you'll need to connect with Android Studio and open logcat.
Example output:
Verify `yarn android:prod` does not produce these logs.
Verify `yarn android:profile` does.
<s>Verify that these two modes are independent and nothing's cached between them.</s> I'm actually having trouble with caching here, but assuming we always build real production builds from CI, this should be fine. I've asked Expo folks to look at this. It seems like editing the `metro.config.js` file is enough to bust the cache manually.
Does not affect iOS or web (on iOS, we don't set `BSKY_PROFILE`, and for web we don't use Metro).

Add Profiler build for Android

---

src/view/com/util/post-embeds/VideoEmbed.tsx
src/view/com/util/post-embeds/VideoEmbedInner/TimeIndicator.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerNative.tsx

- Remove unused layout animations
- Unmount spinner/play btn when not shown
- Use native ActivityIndicator rather than Loader
Profile while scrolling down a video-heavy feed with autoplay enabled (left is with changes)

Attempted video perf improvements

---

src/screens/SignupQueued.tsx

The signup queue has slightly broken styles - no top inset, and the log out button is overlaid on top of the bottom bar, which shouldn't be visible at all
We can fix this by using a nice native modal, which also makes it feel a lot nicer - it includes entry/exit animations and feels more like a "gate"
Also includes minor style tweaks like a border on the gray box
https://github.com/user-attachments/assets/b028b8fc-dd6d-4e4a-a0b4-bf233d8382b6
https://github.com/user-attachments/assets/dc0379e1-13d7-4e63-8ac8-56fededf6cac
in `src/state/session/util.ts` replace `isSignupQueued` with
```
let temp = true
export function isSignupQueued(accessJwt: string | undefined) {
if (accessJwt) {
setTimeout(() => {
temp = false
}, 10000)
return temp
}
return false
}
```
This will show the gate initially …

Use native modal for signup queue screen

---

package.json
yarn.lock

I removed a dependency I thought wasn't used, but turns out Expo uses it to theme the android status bar background
<table>
<thead>
<tr>
<th>Before (black status bar)</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="image" src="https://github.com/user-attachments/assets/abb49c2d-9db3-45fc-8a04-0fa3c87c94ae" /></td>
<td><img width="400" alt="Screenshot 2024-11-19 at 18 56 57" src="https://github.com/user-attachments/assets/8f40b659-3147-4c8c-82d3-f82c0c62cd84" /></td>
</tr>
</tbody>
</table>

Add back expo-system-ui

---

src/components/dialogs/PostInteractionSettingsDialog.tsx

Fixes https://github.com/bluesky-social/social-app/issues/6438
This allows the text to expand the container when needed but keeps the minimum size for consistency. I've also removed a random empty list element.
**Before:**
**After:**

Fix post interaction selectable text being cut off

---

src/locale/locales/hu/messages.po

I have updated the Hungarian localisation for 1.93.
I also have some feedback:
I would like to reiterate my question from the original PR: Is there a way to be notified when modifications are made to the strings? Since my last update, 113 strings were modified or added, none of which I was able to translate in time before the build was published. With all due respect, I would like to avoid making a habit of having to check for new strings each and every day, lest a new version be made public with an unfinished translation.
I wonder if moving the translation efforts to a service like Crowdin could be done? That way, the system itself would be able to send out notifications about newly-added strings. I believe they have a free tier for open-source projects.

Update Hungarian translation for 1.93–94

---

src/view/com/util/post-embeds/VideoEmbed.web.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx

Closes #6035 (see issue for video showing old behavior)
Based on @mozzius' comment on #6037: 
>I'd be open to a solution that caches/restores the play position but still unmounts the player when scrolling away.
New behavior (play position is restored when scrolling back to video):
https://github.com/user-attachments/assets/a6536f47-1663-4946-8f72-7bda22a8f6e8

preserve video's last known time when scrolling away

---

package.json

I don't believe we're using `he` anymore

Remove unused typedef dependency

---

src/screens/Profile/Header/Handle.tsx

**What changes?**
Sets a max width of 100% for the `ProfileHeaderHandle` component to prevent it from overflowing in views like Settings.
Fixes #6569.
**How to test**
The easiest way is to clone the branch, replace this line with a very long handle and visualize the changes:
https://github.com/HorusGoul/bsky-social-app/blob/a7aaeaec11dba45d1c1654b2cd6c5ed344d669bc/src/screens/Profile/Header/Handle.tsx#L52
I used this handle: `@verylonghandlewithsomanycharacters.thatitmightbreaktheblueskyimplementationforhandles.orletsseehowthisshowsupintheuilol.hibtwandimsosorry.therearestillsomanymorecharacterstofillidk.imightaswellgototwohundredorsomethinglikethat.bye.horus.dev`
**Screenshot showing the fix**
The issue seems to be present on Web but not on Android. I can't check iOS at the moment.
| …

Prevent <ProfileHeaderHandle /> from breaking out of its parent view

---

src/components/Link.tsx
src/components/RichText.tsx

Underlining links on hover doesn't make sense on native because you can't see it under the hover anyway. iOS already applies a selected style anyway. And on Android we'd like to avoid extra work during touches.
Let's remove these handlers.
Verify links still get underlined on web, but don't on native.

Don't underline links on native hover

---

bskyembed/yarn.lock

This pull request updates the bskyembed/yarn.lock file so that only one version of Zod is included in the Bluesky embed bundle. This seems to reduce the resulting bundle size by about 9% (from 156kB to 142kB, gzipped).
While looking at the Bluesky embed code with @marvinhagemeister we spotted two versions of Zod in the bundle visualization treemap:
This could be solved by updating the embed bundle's lockfile. Previously both Zod 3.22.4 and 3.23.8 were included and the bundled code took around 156kB gzipped:
```
dist/static/post-BtQoyJ24.js   763.87 kB │ gzip: 156.07 kB
```
Updating the lockfile to only incldue Zod version 3.23.8 reduces the gzipped bundle size by about 9%:
```
dist/static/post-DOc5yEa0.js   700.56 kB │ gzip: 142.04 kB
```

Update bskyembed/yarn.lock to include only one Zod version

---

bskyembed/src/components/embed.tsx

I've updated the `Embed` component to reuse the `getRkey` function instead of relying on `AtUri`. This change enhances reusability and helps reduce the bundle size slightly.
I came across this improvement while working on https://github.com/rhinobase/react-bluesky and thought it would be a helpful optimization.

fix: reused getRkey function in embed component

---

src/view/com/composer/text-input/hooks/useGrapheme.tsx
src/view/com/composer/text-input/mobile/Autocomplete.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx

Fixes a few issues with the autocomplete
- Fixes overflow issue on iOS (ripped out a dumb system based on number of characters and just figured out how to do the same behaviour with flexbox)
- Fixes missing display name issue on web (search for @zed.dev to see this)
- Remove use of reading refs in render in favour of the built-in flag on the hook
- Use unicode symbol for ellipsis instead of `...` (since this looks weird next to `numberOfLines`)
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2024-11-21 at 20 50 51" src="https://github.com/user-attachments/assets/ed94a94f-bd96-4cc5-a0e5-c4fb1400a62c" /></td>
<td><img width="400" alt="Screenshot 2024-11-21 at 20 49 29" …

Fix overflow issue on iOS autocomplete, among other things

---

patches/react-native-svg+15.3.0.patch

Kind of a hackfix. See https://github.com/software-mansion/react-native-svg/pull/2548.
We don't want to parse these icons' paths every time we create a view with them — this is downright silly.
This caches them forever but it's ok because our SVGs are not dynamic and we have a limited number of them.
Verify we're hitting the cache as expected. As you scroll feed, you have fewer cold parses and soon run out of them.
https://github.com/user-attachments/assets/b8b378d0-9898-441a-9406-5617887ca430
This function is a significant part of the `createViewInstance` trace.
It's a smaller part of the overall picture.
This doesn't fully solve the issue — this library is still showing up in `onDraw`, for example. I think ideally we'd move to https://github.com/zamplyy/react-native-vector-image-plugin …

[Android] Patch react-native-svg to cache parsed paths

---

bskyembed/src/components/embed.tsx

It got broken in https://github.com/bluesky-social/social-app/pull/6591. For some reason the CI didn't run on the PR. On main it shows a type error. The fix is easy.
Read the code

Fix embeder

---

src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/shell/index.tsx

This probably isn't very important but I figured we might as well do it.
These don't need explicit backgrounds because there's a background above.
Walk around the screens, everything looks the same visually. The home/profile tabbar still has a solid background. Same for the bottom bar.
(The bottom bar isn't actually transparent, it's just how "Debug GPU Overdraw" visualizes it.)

Reduce overdraw

---

src/view/com/posts/Feed.tsx

These batches can drop frames really hard since each row is a feed story (which may have embeds etc).
Let's just be conservative on Android and try to unblock as much as possible. I'm not seeing a lot of blank spaces in practice unless I scroll super hard. Whereas the frame-by-frame improvement is quite noticeable, especially on embed-heavy feeds like the News feed. And I assume on higher end it'll work even better.
Scroll up and down different feeds.
Also try "scroll to top" and scrolling down after to try to trigger blanks.
This was captured with the News feed (which has embeds and is consistently ordered). Five scrolls down with momentum.
Same, five scrolls on News feed.
And it just _feels_ better, you know.

[Android] Lower Feed maxRenderPerBatch

---

src/locale/deviceLocales.ts

In web development, language codes generally follow the [RFC 1766](https://learn.microsoft.com/en-us/windows/win32/wmformat/language-strings) standard. In this standard, the language tag for Chinese is typically written as: `zh-CN`, `zh-TW`, `zh-HK`.
However, in Android and iOS, language codes follow the [RFC 4646](https://www.iana.org/assignments/language-tags/language-tags.xhtml) standard, which further distinguishes Simplified Chinese (Hans) and Traditional Chinese (Hant). The language tags in this standard look like: `zh-Hans-CN`, `zh-Hant-TW`, `zh-Hant-HK`
When using `getLocales().languageTag` from [expo-localization](https://docs.expo.dev/versions/latest/sdk/localization/#locale) on an Android device (with system language set to Simplified Chinese), it will return this output:
``` …
```

Fix display language not switching correctly to Chinese on native.

---

src/locale/i18n.web.ts
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx

Closes #6499 
This is the first time I have ever worked with Expo, React Native, and even used native-esque debug in Xcode. So I apologize if anything I saw here is grossly misconstrued. I am hoping to continue learning the next few months and I thought this might be a good issue to tackle.
I observed a few days ago that we had a redundant logic condition in the image item components are what I believe is loading logic:
Here is what I think this code intends to do [reference to docs for this OSS](https://docs.swmansion.com/react-native-reanimated/docs/2.x/api/hooks/useAnimatedReaction/)
The first function "prepare" calculates some value (in this case a boolean) based on whether in the current state of the app the view has finished animating and the image **has not** loaded yet. This …

Fix lightbox spinner

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx

Currently, we disable bounce when the image is 1:1. This is to allow it being swiped away (instead of bouncing). However, this actually introduces a problem: if you start pinching in _first_, and _then_ pinch out, the image will jump as you cross the 1:1 threshold. That's because the `bounces` prop would change while dragging, and disabling bouncing would force-center the image. The fix is to only disable bouncing while both 1:1 _and_ at rest.
Implementation-wise, I wanted an excuse to try `useAnimatedProps`, so this is it. Seems like a convenient way to toggle native props without leaving the UI thread. An alternative would be to call `setNativeProps` imperatively.
Verify you still can swipe away images when at rest.
Verify you still _cannot_ swipe away images while zoomed in.
Verify …

[Lightbox] Fix jump when zooming out on iOS

---

src/state/queries/post-feed.ts
src/view/com/posts/FeedErrorMessage.tsx
yarn.lock

When viewing a feed as a signed-out visitor to our web app, we check pages of posts to see if any posts _pass_ the default signed-out moderation settings. If none pass, we show an error screen in place of an entirely empty feed. We do this to prevent endless frontend fetching, trying to find a full page (30) posts that pass moderation and can be shown to the public.
Important to note: `no-unauthenticated` labels on users are also caught by this moderation check, meaning if a feed is full of folks who have opted out of public views, we will also show this error screen on the feed.
The previous error name and copy was a little misleading, and maybe concerning to some users. This PR aims to make it a little more clear what's happening. In the future we should revisit how we handle this …

Improve error name and message for signed-in only feeds

---

src/view/com/util/post-embeds/VideoEmbedInner/TimeIndicator.tsx
src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/ControlButton.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/Scrubber.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/VideoControls.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/VolumeControl.tsx

Fixes https://github.com/bluesky-social/social-app/issues/6306
Turns out `accessibilityHint` doesn't work on web, so we need to use `accessibilityLabel`. Also tweaked things slightly, such as labelling the entire video player as such
It's very odd that the eslint rule disallows label without a hint, when the other way around is much worse.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2024-11-22 at 14 28 38" src="https://github.com/user-attachments/assets/4fcbd42e-c06e-4b35-9e14-0f777f8a5b24" /></td>
<td><img width="400" alt="Screenshot 2024-11-22 at 14 28 28" src="https://github.com/user-attachments/assets/662223b4-7778-46db-a738-b723fb8b4c84" /></td>
</tr>
</tbody>
</table>

[a11y] Video - fix labels and make more detailed

---

src/view/com/util/Toast.tsx
src/view/com/util/Toast.web.tsx

Swipe to dismiss toasts. Also means you can keep it alive to read if you tap and hold
+ a11y improvements!
https://github.com/user-attachments/assets/fe649fce-8924-4617-a71a-8b51484fba2e

Dismissable toasts

---

src/view/com/posts/AviFollowButton.tsx

Before/after: where red is the deadzone and green is the actual touch target
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Screenshot 2024-11-22 at 18 42 35" src="https://github.com/user-attachments/assets/8aa9d64d-faab-4769-ad09-a7c77ab112d4" /></td>
<td><img width="200" alt="Screenshot 2024-11-22 at 18 41 05" src="https://github.com/user-attachments/assets/a055b53f-2e9e-4de7-8af3-f153486d611b" /></td>
</tr>
</tbody>
</table>
Confirm there's no deadzone on iOS + Android

Fix avi follow deadzone

---

src/components/video/PlayButtonIcon.tsx

This solves a few things:
- The shadow was almost invisible on light theme because the `shadowColor` was theme-dependent (which doesn't make sense when overlaying a video).
- We were getting `Raised button causing error: View #... of type RCTView has a shadow set but cannot calculate shadow efficiently` which is only solveable by putting a solid background color on the element _with_ the shadow.
Should overall look the same-ish. Here it is against different backgrounds:

Simplify play icon shadow

---

src/lib/statsig/gates.ts
src/view/com/posts/Feed.tsx

I regressed on this in https://github.com/bluesky-social/social-app/pull/6507. We never want to put an interstitial in between two items of the same slice. To fix this, I'm moving the logic to where we enumerate over the slices. While we're at it, I'm also ripping out a bit of abstraction that hasn't proven out to be useful and was making my mistake harder to spot. (Plus removing the experiment we didn't ship.)
Reset onboarding state, observe the progress bar on Discover:
Discover still shows suggestions:
They change after Discover invalidation.
Profiles still show suggestions:

Fix interstitials to not interrupt feed slices

---

package.json
src/screens/Settings/ThreadPreferences.tsx
src/state/queries/post-thread.ts
src/state/queries/preferences/const.ts
src/state/queries/preferences/types.ts
yarn.lock

Soft-depends on https://github.com/bluesky-social/atproto/pull/3082
---
This adds a new sorting mode ("hotness") and makes it a default for people who never updated their Thread Preferences (needs package bump). If you previously explicitly expressed a different preference, your old choice will be respected.
Currently, the default thread setting is "oldest first". This means that whoever comments first effectively owns the space above the fold, and there isn't much incentive to reply later — after a certain cutoff, unless you *already* have an existing follower base for whom your posts is prioritized, your reply will be seen by very few people.
The "hotness" ranking tries to fix this. It is not ideal (and we'll be tweaking it with time), but the goal is to give a chance to *recent* …

Add a hotness thread sort

---

package.json
yarn.lock

The `@atproto/api` version was updated in https://github.com/bluesky-social/social-app/pull/6649 to add hoteness thread sort.
But the equivalent version of `@atproto/dev-env` was not updated from https://github.com/bluesky-social/atproto/pull/3083.
This updates the `@atproto/dev-env` to remove some duplicate dependencies.

Bump @atproto/dev-env to align with @atproto/api

---

src/view/com/post-thread/PostThreadItem.tsx

Based on #6289
Fix #6287
Fix #6446
Sorry I know this is a bit repetitive, but I’m trying to provide more explanation in this PR. I've encountered this issue frequently over the past few days.
Thanks to @surfdude29’s [comment](https://github.com/bluesky-social/social-app/issues/6287#issuecomment-2487721453), made me realize that there is a behavioral difference between clicking "Translate" in the post context menu and directly clicking the translate button under the post, so I started investigating this.
In #6084, to fix the a11y issue, we replaced `<NewText>` with `<InlineLinkText>`, which introduced `to="#"`. But this breaks the translation and redirects the user to the homepage.
I absolutely respect the a11y fix, so I won’t revert this change. Replacing `onPress={onTranslatePress}` with …

Fix translate button not working

---

src/view/com/composer/text-input/TextInput.web.tsx

Fixes copying and pasting text that includes line breaks (`\n`) in the Web Composer.
Tiptap doesn't maintain newlines because this is a default from Prosemirror. Context: https://github.com/ueberdosis/tiptap/issues/775#issuecomment-920684174
Fixes #6365.
**Changes:**
- Setting the `blockSeparator` to `\n` instead of the default `\n\n`. Fixes the copying behavior.
- Adding a custom `clipboardTextParser`. The same as the code provided by @glavdir in https://github.com/ueberdosis/tiptap/issues/775#issuecomment-762971612, but with type annotations.
https://github.com/user-attachments/assets/b3c6e4c1-0b5e-4805-aeae-72a5a13152cb

Fix Newline handling in Web's Composer

---

src/view/com/posts/AviFollowButton.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/NativeDropdown.tsx

We're trying to fix the avi button hitslops on Android. Currently, Android has significant dead zones where you can't click:
https://github.com/user-attachments/assets/15f4b502-211f-4ce2-a5ef-d59bae9cfa3d
https://github.com/bluesky-social/social-app/pull/6639 seemed like it would work but it did not. We're doing some wonky stuff with pressables and positioning so I tried to simplify it. See commit by commit.
In short:
- Remove `hitSlop` on a wrong Pressable that was swallowing taps (but not handling them) on Android
- Fix a clipping issue that caused touches outside the avi "column" layout getting dropped on Android
- Adjust hitslops for the avi button to get out of the way for pressing the pic (nudge them bottom-right)
Tested on a real device on Android and iOS.
- Verify there are no …

Fix avi button hitslops

---

src/view/com/util/post-ctrls/RepostButton.web.tsx

On the web, the logged-out variant of the repost button sets a white background with `variant="ghost"`, which conflicts with the background applied when a post is hovered:
Removing the button styling seems to make this button render like the others on the page:

Fix repost button styling when logged out

---

src/screens/Messages/components/MessageInput.web.tsx

I imagine this was always supposed to be `!isTabletOrDesktop` or `isMobile`.
Fixes #6667, tested on Android Chrome

Fix media query used to prevent enter sending DM on mobile web

---

src/components/StarterPack/Main/ProfilesList.tsx

Fixes: #5961 
- Summary
The issue was the profiles list being cut off on some devices with specific starter packs. Actually, It is not specific to the devices, but it occurs whenever the starter pack header section is tall enough. So, in the current code, the bottom padding of the list is derived from an arbitrary number (300), which means it can be either bigger or smaller than necessary.
- Solution
I updated the code so that the bottom padding is derived from the header height rather than an arbitrary number like 300. This ensures that the profiles list always has a consistent bottom space across all devices(30px). 
- Before
Android - 
[android-before.webm](https://github.com/user-attachments/assets/f8bb5535-4eae-462e-91d8-a1fb7b28f64c)
iOS - …

Fix starter pack profiles list being cut off

---

src/components/Dialog/index.web.tsx
src/components/ProfileHoverCard/index.web.tsx
src/style.css

We need to stop trying to use Reanimated layout and enter/exit animations on web. They just don't work well. There's no point to trying. We keep getting affected by their glitches and there's no benefit because CSS works much better. Let's avoid them (on web) going forward.
I reused an existing animation name.
Modal backdrops are no longer glitching on web.
https://github.com/user-attachments/assets/69a514f3-19ca-49b9-8e0c-0e61a6502afc
https://github.com/user-attachments/assets/46eda01e-408c-4417-8c5b-f4d97aaf6c4d
https://github.com/user-attachments/assets/b66a1f1a-3f7c-414a-ad4f-1f469faf3b49

Fix jumpy web animation for modal backdrop

---

src/locale/locales/fr/messages.po

here's a rundown of what i did
* filled in every missing instance of `msgstr` while respecting #2425 wherever possible
* i'm not fully aware of modifications made to keep french neutral/inclusive, so i haven't applied to verbs conjugated in passé composé
* replaced instances of "**Pack de Démarrage**" with "**Kit de Démarrage**", as the use of both of these terms simultaneously might cause confusion
* replaced instances of "**Like**" with "**J'aime**" or "**Mention « J'aime »**" 
* my reasoning is that the government of Québec is infamously strict about its french language charter, and bluesky using "Like" instead of a french equivalent may get bluesky in trouble. i also think that this sounds better in french than "Liké"
* i thought of using "cœur", but "`user` a aimé votre post" is …

updated & added missing strings in FR locale

---

src/locale/locales/it/messages.po

I've added some missing translations, as well as fixed some ugly translations, and used always the same translation terms for some original translation terms (eg "handle" is now always "nome utente").

Update Italian translations

---

src/view/com/util/numeric/format.ts

Fixes the test that started failing on main with https://github.com/bluesky-social/social-app/pull/6463.
cf. https://unicode.org/cldr/charts/42/verify/numbers/gl.html

Fix format number polyfill for gl locale

---

src/state/queries/post-thread.ts
src/view/com/post-thread/PostThread.tsx

This took me a little bit to figure out but I think the result works well.
Might be easier to review the entire thing than commit by commit.
Currently, if your thread sorting preference is anything other than "oldest first", the sort order between refetches is not guaranteed to be stable. As a result, you'll often get layout shifts:
1. Start replying to somebody's reply from the parent post thread
2. The thread refetches
3. The order may be different, and now you're looking at a random comment
This is very easily observable with the "random" sort order:
https://github.com/user-attachments/assets/9d3ab603-0b1e-4eb3-9c2f-c6d54f6e948d
Although this was _most_ severe with the "random" sort order (where every attempt to reply reorders everything), it was also an issue with the "newest" or …

Don't re-sort already fetched post thread items

---

src/components/dialogs/PostInteractionSettingsDialog.tsx

Fixes https://github.com/bluesky-social/social-app/issues/6687
Switches should not change text to reflect state as the state is already reflected in the switch itself; changing the text makes it more confusing to the user.

Make quote post enabled switch label text static

---

src/components/Dialog/index.tsx
src/screens/Messages/components/MessagesList.tsx

The array of dependencies is needed to prevent frequent re-attaching handlers. Internally `useKeyboardHandler` is based on `useEffect` and without dependencies `useEffect` will be fired on each re-render (which may affect performance).

fix: keyboard handler memoization

---

src/screens/StarterPack/Wizard/StepFeeds.tsx
src/screens/StarterPack/Wizard/StepProfiles.tsx

Dismisses the keyboard from List component embedded within `StepProfiles` and `StepFeeds` with the `on-drag` mode provided by the native `ScrollView` component.
Prior to this PR, users would have to click a user to add them and then unclick, or hit the back button and come back to the screen in order to dismiss the keyboard as other controls are hidden behind the keyboard in a `BottomSheetDialog`.
- Follows pattern established in the `Explore` screen to dismiss keyboard on drag from the List component. -

Dismiss keyboard on drag in starter pack screens

---

patches/react-native-image-crop-picker+0.41.2.patch

Fixes a bug where using the camera button would produce a stretched image on Android. The issue was that the `width`/`height` were misreported by not taking the EXIF tags into account. The iOS version does this correctly.
Upstream PR: https://github.com/ivpusic/react-native-image-crop-picker/pull/2110
Try taking a camera image in all orientations (landscape/rotate with both front/back camera), verify it appears correctly both before posting (in the composer preview) and after posting.

Fix camera orientation on Android

---

src/screens/Messages/components/MessagesList.tsx

On Android, opening a menu in DMs would cause the keyboard input to enter a strange state. This attempts to fix it by setting the keyboard height on the `onEnd` event and reimplementing KeyboardStickyView manually (turns out it's a very simple component, and we basically are already doing same the logic anyway for the scrollview)
https://github.com/user-attachments/assets/f53e9374-1d81-48ce-8d0e-63401604825f
https://github.com/user-attachments/assets/91940a5a-b1df-46bd-8c18-f54aa9b540ce

Fix Android keyboard bug when opening a sheet

---

src/state/shell/minimal-mode.tsx
src/view/com/util/MainScrollProvider.tsx

This was originally added in https://github.com/bluesky-social/social-app/pull/4386. I don't think we ever truly established that it was necessary. It does, however, definitely cause problems now so I think we should rip it out.
To reproduce the issue, swipe to another feed while the header is not visible.
The animation effectively happens twice and interrupts itself. (Due to multiple identical calls to `setMode`.)
https://github.com/user-attachments/assets/d67c110f-8aee-480c-8dec-61b5318cd121
The animation doesn't interrupt itself.
https://github.com/user-attachments/assets/b5113c02-4090-46d0-afa2-36711dfc7950
I verified it works well on the device too.

Fix stutter when swiping feeds on Android

---

src/components/hooks/dates.ts
src/locale/languages.ts

[date-fns](https://www.npmjs.com/package/date-fns) does not define `ast`, we should remove the import, and set `ast` to `undefined`.
Although `ast` is a Code3 language code, the subsequent code requires a Code2 language code. Let's assign it as Code2 (even though it is not correct) so it can passes the check. This should not affect Post Language or other processing, as it is only related to the App Language.

Fix ast localization

---

src/view/com/post-thread/PostThread.tsx

Mobile web only.
Does not affect native (it has a bottom safe inset that's larger), does not affect tablet or desktop.

Fix gap between Write Your Reply and bottom bar on web

---

src/screens/Settings/AppIconSettings.web.tsx
src/screens/Settings/AppearanceSettings.tsx

Tested web works, verified setting still shows up on iOS.

Fix web build by removing app icon settings

---

src/components/AppLanguageDropdown.tsx
src/screens/Settings/LanguageSettings.tsx
src/view/screens/Search/Search.tsx

Fixes: #6803 
I don't have any Android devices nor can successfully test it with emulator so the picker in Android should still in wrong style under dark mode
| Splash Screen  | Sign Up Page | Languages Setting Page  | Search |
|---|---|---|---|
| <img src='https://github.com/user-attachments/assets/661c257f-7e82-41ec-8699-6bbd7d3b6d6c' width = 450 />  | <img src='https://github.com/user-attachments/assets/bdce127e-20a9-4505-b0d5-f56a746c5f3d' width = 450 />  | <img src='https://github.com/user-attachments/assets/25724447-2c83-4c35-bbee-be0c723f1b64' width = 450 />  | <img src='https://github.com/user-attachments/assets/52793d8b-0620-46f8-96f9-d1621aad7ae0' width = 450 />  | 
| Splash Screen  | Sign Up Page | Languages Setting Page  | Search |
|---|---|---|---|
| <img …

Fix language picker style in dark mode

---

src/App.native.tsx

Seems like some people are getting white root views. Let's force it to be black. 
According to the docs, `setBackgroundColorAsync()` is supposed to be called outside of the component, so I put it next to `SplashScreen.preventAutoHideAsync()`

Ensure black root view on iOS

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/util/images/AutoSizedImage.tsx

Addresses https://github.com/bluesky-social/social-app/issues/6800
As noted in https://github.com/bluesky-social/social-app/pull/6474, we don't want to use dynamically fetched dimensions on the client because it causes layout shifts for any post(s) after the image. In the worst case this can cause an entire cascade of relayouts which is absolutely terrible for performance.
However, as discussed in https://github.com/bluesky-social/social-app/issues/6800, cropping can feel pretty disruptive. Instead, let's try "containing" when the aspect ratio is unknown.
This only affects images with missing dimensions. (Currently, it's up to the client to specify the dimensions.) In longer term it would be nice if the server could somehow fill out the missing ones, but fixing that is out of scope of …

"Contain" images with missing dimensions instead of cropping them

---

package.json
src/Splash.tsx
yarn.lock

This library causes pain when upgrading or using Fabric. It doesn't actually seem necessary at all, so lets maybe rm. It was already not being used on Android anyway because of a separate bug.
Build for both iOS and Android. See that the splash screen still works the same as before.

remove masked view dependency

---

src/view/com/feeds/FeedPage.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

Enables prefetching for adjacent Home tabs. This is similar to what would happen today if you just navigated around the tabs (thus warming them up). Prefetching only happens once and there is no continuous polling until you focus. 
Add `console.log` to `post-feed` fetch, verify it is being hit for adjacent tabs.
Verify that `checkForNew` in `Feed.tsx` exits early for all non-focused tabs (even adjacent ones), like before.
Verify that the effect computing `const timeSinceFirstLoad = ...` in `Feed.tsx` still always gets triggered on tab focus — i.e. it doesn't get "stuck" for adjacent tabs. In other words, verify the focused tab always gets into this check's body. In practical sense, we want to ensure that continuously switching between two tabs will eventually trigger the …

Prefetch adjacent Home pages

---

src/lib/statsig/events.ts
src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/com/pager/TabBar.tsx
src/view/com/pager/TabBar.web.tsx
src/view/screens/Home.tsx

The goal is to resurrect https://github.com/bluesky-social/social-app/pull/1696. I've learned a bunch of things since I made that version, and I'm pretty sure I can get the indicator to work fast on Android now. Scrolling on demand may still be tricky but we'll see. Could be iOS-only.
In this PR, I'm just starting to clean things up a bit:
- `TabBar` is going to diverge even more between web and native, so I'll just fork it now.
- Remove `Pager`'s `onPageSelecting` event. It's kind of ill-defined (what does "selecting" mean exactly?), and the implementation encourages putting heavy work just as the deceleration is starting. This is not great for performance, especially if we start adding more visual flourishes to it. I believe the goal was to optimistically start some work earlier (maybe …

[Nicer Tabs] Fork TabBar, simplify Pager

---

src/view/com/home/HomeHeader.tsx
src/view/com/pager/Pager.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/com/pager/TabBar.tsx
src/view/screens/Home.tsx

This revives https://github.com/bluesky-social/social-app/pull/1696 but in a performant way.
Try different interactions on iOS and Android:
- **Initial load:** The pager should autoscroll to the initially selected tab on reload. (Ideally this would not be animated, but since I couldn't figure out a reliable way to do it on the first frame on both platforms, I have to animate it.)
- **Swiping the pager drives tabbar scroll:** The swiping gesture should stay in sync with the tabbar scroll. A full page swipe should bring you to the same position as tapping the next item. Note that if you continuously swipe page after page, by the time you arrive at the last page, the blue line should naturally be at the right edge of the screen. This also means that by the time you're halfway through the …

[Nicer Tabs] New native pager

---

src/view/com/util/MainScrollProvider.tsx

Fixes a gap that happens when you:
1. Starting pulling to refresh
2. Quickly release and "catch" the scroll view
3. Move finger up and down
The bad behavior is that it scrolls up and down with a "gap" due to pull refresh. What it _should_ do is normalize the anchor point to be outside the rubber banding.
Easier to see on video.
https://github.com/user-attachments/assets/1c970574-ab3b-4943-92a7-25a2d6e980ef
https://github.com/user-attachments/assets/bc28649c-8b0b-4eff-a7ce-c822d5b562d4

Fix scroll gesture alignment

---

package.json
src/components/forms/DateField/index.android.tsx
yarn.lock

This issue initially hard blocked me from registering a Bluesky account in the Android app because I couldn't see that this dialog had any buttons at all because of the incorrect theming:
The title color is fixed automatically by upgrading to the latest version of `react-native-date-picker`. However, it doesn't fix the buttons. These buttons seem like they should switch to white in dark mode too (and I have another [PR](https://github.com/henninghall/react-native-date-picker/pull/871) up against react-native-date-picker to change that), but in the meantime I've just specified the correct colours depending on theme to the `buttonColor` property. 
The reason I'm using hard-coded hex values instead of getting colours from the theme is that the theme has the colours in hsl format, which the …

Fix title/buttons in age date picker not being visible on Android in dark mode

---

src/view/com/pager/TabBar.tsx
src/view/com/pager/TabBar.web.tsx

Should broadly be the same as before, except I've reduced the height of the indicator by 1px (so it's now 2px tall)
Check it still all works on web and on native

ALF TabBar

---

src/components/Layout/Header/index.tsx
src/view/com/notifications/Feed.tsx
src/view/screens/Notifications.tsx

Only notable changes here:
- When a soft-reset occurs, the gear icon is replaced with a loader icon (onPress unchanged)
- On mobile, the title is pressable as well — a11y is good, double checked on iOS/Android
- This new header has a bottom border, so I disabled on the notifications items and skeleton state first items

[Layout] Notifications Header

---

src/screens/Hashtag.tsx

Simple one. Only changes:
- back button exists on desktop now too
- share button exists on desktop now too (just copies to clipboard)

[Layout] Hashtag header

---

src/screens/Messages/ChatList.tsx
src/screens/Messages/Settings.tsx

[Layout] ChatList header

---

src/components/LikedByList.tsx
src/components/Lists.tsx
src/screens/Moderation/index.tsx
src/screens/Post/PostLikedBy.tsx
src/screens/Post/PostQuotes.tsx
src/screens/Post/PostRepostedBy.tsx
src/screens/Profile/KnownFollowers.tsx
src/screens/Profile/ProfileLabelerLikedBy.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostQuotes.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/util/ViewHeader.tsx
src/view/com/util/error/ErrorScreen.tsx
src/view/screens/ProfileFollowers.tsx
src/view/screens/ProfileFollows.tsx

An attempt to go through every instance of `<ViewHeader>` and make sure there's no double borders. Most of the time it was just setting `topBorder={false}`, sometimes I needed to change the screen to use `<Layout.Center>` or something.
ctrl+f `<ViewHeader` and check every single one out, esp. on different web breakpoints

[Layout] Every other screen

---

src/view/com/util/List.tsx

iOS only, add top offset to the feed scroll bar so the scroll bar won't cover by the tab bar
|----|----|
| <video src='https://github.com/user-attachments/assets/ce7d4165-cbdc-4eb7-9d04-fb147383ae71' /> | <video src='https://github.com/user-attachments/assets/41fcb5f2-9d2d-4f5e-84a1-d55d3402950b' /> |

Adjust feed scroll bar top offset

---

src/components/Layout/Header/index.tsx

Very slight adjustment on native due to the safe area already providing some visual padding

[Layout] Asymmetric header on native

---

src/view/com/composer/state/composer.ts
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/text-input-util.ts

Some news publications have reached out and notified us that link cards don't automatically show up when opening the composer via an `/intent` link. This PR does the link parsing on composer state creation, and pre-fills any links that might exists so that the card can be rendered.
Tested on web and iOS with no issues. On Android, the post link doesn't resize the `PasteInput` correctly, discussing in Slack.
URL
```
localhost:19006/intent/compose?text=Canned%20Cocktails%20in%20Quarantine%20Make%20Mixing%20a%20One-Step%20Process%20%0D%20%0A%20%0D%0A%20https%3A%2F%2Fwww.nytimes.com%2F2020%2F05%2F14%2Fdining%2Fdrinks%2Fcanned-cocktails-coronavirus.html%3Fsmid%3Dbs-share
```
Post
```
localhost:19006/intent/compose?text=Hello%20world%20https%3A%2F%2Fbsky.app%2Fprofile%2Fesb.lol%2Fpost%2F3l5arskd …
```

Immediately parse pre-filled links in composer state

---

src/view/screens/Feeds.tsx
src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx

These were load-bearing `flex: 1`. Added back old padding for good measure.
Both these screens and the `Lists` screen use RN's `FlatList` directly, which we should probably swap for our wrapped `List`. All three screens have flex styles to grow to fill screen.
Test: on mobile and web

Fix squashed content on mod screens

---

src/view/com/post-thread/PostThread.tsx

Noticed this got dropped in the layout refactor. This keeps the logic, but doesn't gate it based on breakpoint.

Add back button to desktop threads

---

bskyweb/templates/error.html

Fixes #6989: in Go-Server templates/error.html `super()` used instead of pongo2 `block.Super`.
It's the only place in Go-Server where `super()` is used and it's limited to 404 error handling only.
https://github.com/user-attachments/assets/d7c7a605-d1aa-4053-a5da-69c3fabfdc86
As you can see from the video above there is a redirect from 404 to homepage happening automatically. It happens in `@react-navigation/native/src/useLinking.tsx` in a useEffect this code is executed: `history.replace({ path, state });`

Fix 404 error handling for Web

---

patches/react-native-drawer-layout+4.0.4.patch
src/screens/Hashtag.tsx
src/view/com/pager/Pager.tsx
src/view/screens/Home.tsx
src/view/screens/Profile.tsx
src/view/screens/Search/Search.tsx
src/view/shell/index.tsx

See main insight in https://github.com/software-mansion/react-native-gesture-handler/issues/3266#issuecomment-2525301903.
New approach relies on https://github.com/react-navigation/react-navigation/pull/12326 which I expect to get merged soon.
- Try swiping between tabs on Home and Profile
- Verify the drawer gesture only activates on the first page, and that the pager takes over on other pages
- Verify the drawer gesture doesn't steal vertical scrolling
- Try to switch pages fast, in different ways, spam the left/right gesture
- Note that it won't immediately open the drawer if you just arrived to the first tab without resting. That's kind of intentional to disambiguate pager swipes and intentional drawer swipe. Maybe fixable but let's not fix that yet.
- Switch between Home and Profile, …

Fix drawer swipe

---

src/view/com/feeds/FeedPage.tsx

Adjust https://github.com/bluesky-social/social-app/pull/6904 to only do this for native. On web it causes too many requests that aren't being used due to opening in new tab.
On web, there's a noticeable loading state when switching Following -> Discover. Which confirms the change.
On native, the switch feels instant like before.

Limit feed prefetching to native

---

src/alf/breakpoints.ts
src/alf/index.tsx
src/alf/util/useGutterStyles.ts
src/alf/util/useGutters.ts
src/components/Layout/Header/index.tsx
src/components/Link.tsx
src/components/ProgressGuide/List.tsx
src/view/com/home/HomeHeaderLayout.web.tsx
src/view/shell/desktop/Feeds.tsx
src/view/shell/desktop/RightNav.tsx
src/view/shell/desktop/Search.tsx

Extracted from subs branch. This cleans up the right nav to look better and fit incoming NUXs better. Looks especially better on the search page.
In the process, I made an improvement to the new `useGutters` hook so it's more ergonomic. 
(illustrating overflow with lots of feeds, works fine)

Refactor sidebar

---

src/screens/Login/LoginForm.tsx

This should (fingers crossed) work in Safari, at least.

LoginForm: enable autocomplete on 2FA code field

---

src/state/shell/composer/index.tsx

Fixes https://github.com/bluesky-social/social-app/issues/6951
1. Start typing a reply
2. Focus outside the text field
3. Press N
Before, it would detach the reply.
After the fix, it doesn't.
The fix itself is a bit more generic — basically, never auto-dismiss a reply in progress without a manual user action. This might apply to other cases (intents?) but I think the principle still holds. Dismiss the composer manually first, then something new can appear in there. If some piece of code wants to intentionally close the composer, it can call `closeComposer`.
https://github.com/user-attachments/assets/5f65d75a-56b7-4945-b92e-63f2e84c19a2
https://github.com/user-attachments/assets/66d76769-2232-4d9d-af1c-63fc9e9cecd3

Fix composer shortcut detaching a reply

---

bskyembed/snippet/embed.ts
bskyembed/src/color-mode.ts
bskyembed/src/components/container.tsx
bskyembed/src/components/embed.tsx
bskyembed/src/components/post.tsx
bskyembed/src/index.css
bskyembed/src/screens/landing.tsx
bskyembed/src/screens/post.tsx
bskyembed/tailwind.config.cjs
bskyembed/tsconfig.json

- Added support for dark mode by using tailwindcss `dark:` modifier.
- Dark mode is also supported on the landing page.
Fix #5119 
Fix #5966 
Close #6842 *(I should have said in either of the 2 issues above that I'm working on the patch, sorry for duplication)*
↓ This image is outdated ("Want more customize?" section is not present in the latest code)

feat(embed): Add support for dark mode

---

src/screens/Profile/Header/Metrics.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx

We had a structure like this:
- Parent view with `paddingBottom`
- Metrics with `paddingBottom`
- Conditional bio with no padding
- Conditional social proof with `paddingTop`
- Tabs 
As a result, when something conditional is missing, the padding were getting combined in an awkward way. For example:
- No bio or social proof: The metrics' `paddingBottom` was getting combined with the parent view's `paddingBottom`, resulting in double padding
- No bio, but has social proof: The metrics' `paddingBottom` was getting combined with the social proof's `paddingTop`, resulting in double padding
The fix is to treat these as three items with a gap, and to remove those paddings.
Check that these cases now work well:
- No bio, no social proof (this used to be too spacey)
- No bio but has social proof …

Reduce excessive empty space on profile with no bio

---

src/view/com/post-thread/PostThread.tsx

The way "Continue thread" works today is confusing even if technically correct. Currently, if we detect a thread, we'll replace the last known self-item in the thread with a link that points to the next post. The problem is that this jump loses context. When the link loads, it shows a post *you've never seen before*. What I believe we should do instead is to point you *at the last post you've seen* so you can scroll down from it without loss of continuity.
You jump from post 9 directly to post 10:
https://github.com/user-attachments/assets/3b165431-ca6c-4537-9c52-9784b6ab8581
If you thought about something for a moment or the link took a while to load, you'll be disoriented because no context is being explicitly carried forward in the transition. You're looking at a completely different …

Point "Continue thread" at last shown post

---

src/screens/Profile/components/ProfileFeedHeader.tsx

Let's keep Pin the primary CTA without choosing between Pin/Save.
If it's already pinned, then you get the choice (unpin or remove completely).
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/7061/files?w=1)
https://github.com/user-attachments/assets/1c7ccb76-09cb-43e7-b726-278fec10a3a7

Keep Pin primary CTA

---

src/screens/Post/PostRepostedBy.tsx

Maybe it's a typo, but `repost` should be the correct singular word, not `reposts`.

Fix singular words in translated strings

---

src/components/FeedCard.tsx
src/components/LabelingServiceCard/index.tsx
src/components/moderation/LabelsOnMe.tsx
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/screens/ProfileFeed.tsx

* Refines plural marks to reduce the length of strings used for translation.
* Translations are still free to rearrange words.
* `NotificationFeedItem.tsx`, `src/screens/StarterPack/Wizard/index.tsx`, etc. are already written this way.
* In `src/components/LabelingServiceCard/index.tsx`, replaces `count` with `likeCount` to consolidate the translation string.
* In `src/view/com/util/post-ctrls/RepostButton.tsx`, provides the full string to the translation so it can be contextualized.

Refine plural marks

---

src/screens/Hashtag.tsx
src/view/com/pager/TabBar.tsx
src/view/com/pager/TabBar.web.tsx

This changes the pager to always fill the entire screen width by spacing out the items. If there are _many_ items (more than a screen's worth), then they are placed like before.
Easier to understand from a demo:
https://github.com/user-attachments/assets/7c28141f-c2c1-4be0-9b61-61c48a24f5c8
Try these on iOS, Android, and web.
- Check Home the new user experience (Discover, Following)
- Check Home for a user with a lot of feeds
- Check profile tabs (own and others')
- Check hashtag and search screens
- Try it on top of https://github.com/bluesky-social/social-app/pull/7044
Centered item looks a bit weird when there's a single tab but the only case of that is being solved by https://github.com/bluesky-social/social-app/pull/7056.

Make the pager take full width

---

package.json
src/lib/hooks/useNotificationHandler.ts
src/lib/routes/types.ts
src/screens/Settings/NotificationSettings.tsx
src/state/queries/notifications/feed.ts
src/state/queries/notifications/settings.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/state/queries/util.ts
src/view/com/notifications/NotificationFeed.tsx
src/view/com/notifications/NotificationFeedItem.tsx
src/view/com/pager/Pager.tsx
src/view/screens/DebugMod.tsx
src/view/screens/Notifications.tsx
yarn.lock

This adds a new Mentions tab to the Notifications screen. This tab is equivalent to the Mentions tab on Twitter. It filters out non-post notifications (follows and likes) but displays every post in your notifications (including replies, mentions, and quotes). The previous behavior is now a tab called *All* (which remains the default on the Notifications screen).
Note that _this does not filter out any posts_. On the contrary, it lets you read *only* notifications that are posts. The *All* tab did not work very well for that because it fetches likes and follows, causing posts (including quotes, mentions, and replies) to be easily lost behind the pagination boundary. Unlike *All*, the *Mentions* tab will *only* display posts (including quotes, mentions, and replies) so it should reduce the …

[Notifications] Add a Mentions tab

---

src/App.native.tsx
src/App.web.tsx
src/components/Layout/Header/index.tsx
src/screens/Profile/Header/GrowableBanner.tsx
src/screens/Profile/Header/Shell.tsx
src/screens/Profile/Header/StatusBarShadow.tsx
src/screens/Profile/Header/StatusBarShadow.web.tsx
src/screens/Profile/Header/index.tsx
src/state/shell/light-status-bar.tsx
src/view/com/pager/PagerHeaderContext.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/screens/Profile.tsx
src/view/shell/index.tsx

Best demonstrated via video
https://github.com/user-attachments/assets/158af9fb-d778-4f29-abb5-cad173559f90
https://github.com/user-attachments/assets/0bc576bc-1806-42f8-9ec5-21a54684884b
Check it works good iOS and Android. Particular things to look for:
- Accessibility - is the minimal header accessible? is it correctly hidden from voiceover when invisible?
- Performance on low-end android. compare to current situation
- Check loading states, network conditions etc
Also check no regressions on web, other than adding in the back arrow on desktop

[Layout] Bleed profile banner into safe area

---

src/components/Menu/context.tsx
src/components/Menu/index.tsx
src/components/Menu/index.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/5719
This is one that I was unable to reproduce for some time, but was finally able to "accidentally" discover. If you press too long on the "share" button, the dialog actually ends up staying open a tad bit longer. It seems like when that happens, the app isn't able to present the share dialog because the menu sheet is still presented and animating away.
Notably here, we were not calling our menu item `onPress` inside of the `close()` function's callback, but rather in parallel. We've seen in the past where its pretty essential to do that, and it seems like this is another one of those cases.
Before this PR, open the share sheet and take a bit longer on pressing the "Share" button. It shouldn't open the share sheet. Then, test …

Fix share button not working for some users

---

src/components/FeedInterstitials.tsx
src/view/com/posts/PostFeed.tsx

Previously, the progress bar was throwing off the `hideTopBorder={index === 0}` condition on the top feed item because the progress guide was always getting rendered as a row (even if returning `null`). To fix this, a couple of things:
- The condition for whether to show the guide has moved into where we create rows rather than in the progress guide component itself.
- I've also removed the top border from the progress guide itself for consistency.
https://github.com/user-attachments/assets/c43232a6-0126-4a1a-b65e-a1cbdd6c0647
Also check it works as expected on mobile web, tablet and desktop (where this widget is in the right pane).

Fix double border due to progress guide

---

src/components/hooks/useHeaderOffset.ts
src/view/com/home/HomeHeaderLayout.web.tsx
src/view/com/pager/TabBar.web.tsx

We accidentally broke Home header on the web so that a child scrolls away but its parent is still there taking space. We *could* fix that but tbh on desktop it's good to remind that the tabbar exists. So this PR just keeps the bottom part of it always visible and sticky, just like already in prod (which was borked but for a different reason).
I've additionally adjusted the header offset calculation so that the top post doesn't appear cut off. And the border in tablet/mobile web mode is a bit thicker to match desktop and native.
Web:
https://github.com/user-attachments/assets/bedc86b1-e31b-4cd6-b234-61914aa7670d
No changes in native files.

Fix web Home header

---

src/screens/Login/LoginForm.tsx

The 2fa token is uppercase in the email sent to users. This PR just adds `text-transform: uppercase` to the input element on the app to match the casing in the email. 
A boolean state is needed to only set the input to uppercase when there is an input, otherwise the placeholder gets uppercased as well.

Uppercase the auth factor token input value to match the email casing.

---

.github/workflows/lint.yml
Makefile
index.js
src/App.native.tsx
src/env.ts
src/lib/bitdrift.ts
src/lib/statsig/statsig.tsx
src/logger/README.md
src/logger/__tests__/logger.test.ts
src/logger/index.ts
src/state/session/__tests__/session-test.ts
src/view/com/util/Toast.tsx

- Moves Statsig initialization much earlier — we'll now initialize unconditionally _before_ we know your user ID and then initialize again. In practice this means that we're able to check cached gates based on StableID almost on startup.
- Makes the Bitdrift integration conditional on an `enable_bitdrift` gate to derisk it.
Our test setup was getting borked by the changes in the init code. I tried to unbork it but something about `env.ts` was not doing it correctly. I ended up ripping out the custom `IS_TEST` thing and doing a raw `process.env.NODE_ENV` inline environment check. I think we should change the rest of the code to match that pattern (for `IS_DEV` and `IS_PROD`) to guarantee dead code elimination but that's out of scope of this PR.
Verify that allowlisting your StableID for …

Gate bitdrift integration

---

src/view/com/pager/TabBar.tsx
src/view/com/pager/TabBar.web.tsx

Fixes https://github.com/bluesky-social/social-app/pull/7066#issuecomment-2540409035
Instead of giving min width to the tab item itself, instead give it to the indicator line. Also constrain it by the parent size so that it never extends beyond the tab item. As a result, the blue line will be 45px min, but won't inflate the tab bar item.
Verify "All" in notifications still has some extra minimum width.
Verify profile tab bar items are not inflated anymore.
https://github.com/user-attachments/assets/58a6b313-588c-47a1-877a-195cb9edc4e3
https://github.com/user-attachments/assets/65f277b3-d307-439b-9327-11a9584092c3

Give minWidth to tab indicator only

---

src/screens/StarterPack/StarterPackScreen.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/screens/ProfileList.tsx

This makes List and Moderation List screens closer in design to the Starter Pack screen:
- The description is moved inline into the header.
- Also killed the "No description" label. If it has no description, it has no description, duh.
- The "About" tab is now just called "People" (for Lists) because it is now just a list of people.
- For mod lists, there's no tab header at all to avoid showing a single tab (which looked worse since #7066).
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/7100/files?w=1)
- Check lists, mod lists, starter packs
- Check lists with description and with no description
https://github.com/user-attachments/assets/0aa0b851-c50e-489e-a64d-495d1cb3bbe1
https://github.com/user-attachments/assets/952ff263-d063-40dd-ae1f-34f1d59efb9a

Tweak ProfileList design

---

src/screens/Hashtag.tsx
src/view/com/pager/Pager.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/screens/Notifications.tsx
src/view/screens/Search/Search.tsx

Reverts this change: https://github.com/bluesky-social/social-app/pull/7044/commits/b3381b5180e5eff33342dde009d0918056e80df2#diff-65932679e7a40da6746980329ec9b70b756d28bfc7980c1ffe03c2e49f7a5bb3
I did it to make sure the tabbar is always drawn on top of the content (so the Notifications glimmer doesn't obscure the tabbar's bottom border) but this zIndex being there causes Android to break horizontal scroll on the tabbar itself (it is interpreted as a pager swipe).
This alternative set of changes (just plumbing zIndex through) seems to work.
Dragging the tabbar works again on Android:
https://github.com/user-attachments/assets/b6a101aa-47b6-45ec-8b5a-5f171d82ffe5
On iOS, while Notifications are loading, the border is visible:
https://github.com/user-attachments/assets/c790ce25-b3b8-423c-9d0 …

Fix z-indexes to make tabbar scroll on Android

---

patches/expo-image-manipulator+13.0.5.patch
src/lib/api/upload-blob.web.ts

Fixes https://github.com/bluesky-social/social-app/issues/7097
If this isn't enough or we find some other issue, we'll fork the package by version instead, but let's try this first.
There were two issues:
- The library we use now emits `blob:` URIs rather than `data:` URIs
- It also accidentally lost support for the `compress` option on web, so it became a no-op
So this fixes both problems.
Verify you can upload both _small_ images and _large_ images.
For small image, just use something small.
For large image, I was testing with https://apod.nasa.gov/apod/image/2412/M51_HaLRGB_APOD2048.jpg
No changes on native.

Fix posting images on web

---

src/components/forms/TextField.tsx

system fonts were leaking. i'm sure there's a better way to apply this without duplicating but idk it works

apply fonts to TextField

---

src/screens/Profile/ProfileFeed/index.tsx
src/screens/Profile/components/ProfileFeedHeader.tsx

Removes the loading state from the feed info dialog to fix sizing, and adds a counterpart `ProfileFeedHeaderSkeleton` component, and uses the pre-existing `PostFeedLoadingPlaceholder` to create this new load screen (no loading spinners at all):

`ProfileFeed` cleanups

---

patches/expo-image-manipulator+13.0.5.patch

Follow-up to https://github.com/bluesky-social/social-app/pull/7105.
https://github.com/bluesky-social/social-app/pull/7105 broke uploads on native because RN doesn't like when you pass an argument that wasn't declared on the native side. So instead of passing that argument inside `ImageManipulatorContext.ts`, I forked `ImageManipulatorContext.ts` completely into `ImageManipulatorContext.web.ts` and only pass it in the web version.
- I'm able to post images on web (same as https://github.com/bluesky-social/social-app/pull/7105)
- I'm also able to post images on mobile (iOS and Android)

Fix image upload on native

---

src/App.native.tsx
src/App.web.tsx
src/lib/statsig/gates.ts
src/state/home-badge.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx
src/view/shell/bottom-bar/BottomBarWeb.tsx
src/view/shell/desktop/LeftNav.tsx

Fixes (eventually) https://github.com/bluesky-social/social-app/issues/7002, https://github.com/bluesky-social/social-app/issues/6902, https://github.com/bluesky-social/social-app/issues/6319, https://github.com/bluesky-social/social-app/issues/6443
In this experiment, I'm removing the "Load latest" floating button.
- On the Notifications tab, the tabbar item completely duplicates its functionality. So it was superfluous there.
- On the Home tab, the tabbar item was duplicating its functionality except for lack of a badge. So I added a badge.
- In other places, we don't always have a direct replacement (yet?)
- You can always pull-to-refresh on mobile.
- On profile, tab headers themselves act as a way to refresh. This is maybe not very discoverable.
- On a standalone feed page on the web, …

[Experiment] Remove "Load Latest" button

---

package.json
patches/expo-modules-core+2.1.1.patch
yarn.lock

Video uploads got broken by the Expo upgrade. I'm patching https://github.com/expo/expo/pull/33621 to fix it. That fix hasn't made it into a release yet but it's pretty trivial.
I'm additionally bumping the dynamic icon package because it was pulling in old `expo-modules-core`. Doesn't matter (maybe?) but this seems safer.
Verify you can again upload videos on iOS and Android.
Verify web still works.
Verify dynamic icon still works.

Fix video uploads on native

---

src/view/screens/Search/Search.tsx

Hi,
In response to issue #7111, I prepared a solution to set width of profile links' text in "Recent Searches" to 100% for mobile devices. Change does not affect current profiles layout. Below I place before and after screenshots.
I tested it on Chrome 131.0.6778.140 and Firefox 133.0.3 as problem appeared on web version for screens with width smaller than 900px.
Before:
After:
Greetings
Karol

feat: widen recent search profile link for mobile devices

---

src/view/com/util/List.tsx

iOS automatically adds in the safe area to the scroll indicator insets, even though the overwhelming majority of our ScrollViews do not stretch from edge to edge. we should just disable this behaviour by default
Can't take screenshots rn but you can see on the testflight that the scroll indicators on the post thread screen doesn't go all the way to the top. this PR fixes that

Disable automaticallyAdjustsScrollIndicatorInsets

---

src/lib/constants.ts
src/lib/statsig/gates.ts
src/screens/Settings/AppIconSettings/index.tsx
src/screens/Settings/AppearanceSettings.tsx
src/state/queries/post-feed.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

A few things:
- Remove the hardcoded `DISCOVER_DEBUG_DIDS` stuff. It sucks because it's not visible in production.
- Instead, reintroduce two different gates: `debug_subscriptions` and `debug_show_feedcontext`
- They don't have Metric Lifts enabled so they're free to check
- Narrow down the build conditions
- Only enable the app icon stuff when `IS_INTERNAL` is _also_ true (we never want it in public builds)
- Enable the debug context if the gate is true _or_ we're in TestFlight (where we always enable it)
Basically the goal is to get rid of this hardcoded list.
Probably easiest to test by going to an alt, verifying it has no feed feedback or app icon, then allowlisting it in each gate, and verifying both things show up. Note that feed context _also_ shows up for `IS_INTERNAL` so you'll …

Adjust gates

---

src/view/com/util/error/ErrorScreen.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-17 at 00 00 38" src="https://github.com/user-attachments/assets/846d2fcb-50c0-48cf-9faa-fc3f8f5721a1" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-16 at 23 59 16" src="https://github.com/user-attachments/assets/7745d3eb-9aea-49ba-b6ab-5aaa0e03c357" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-17 at 00 00 52" src="https://github.com/user-attachments/assets/3ec2ee3e-2a76-477c-a9b5-190e812ea967" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-16 at 23 …

ALF error screen

---

src/locale/locales/an/messages.po
src/locale/locales/ast/messages.po
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en-GB/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/gl/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/hu/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/nl/messages.po
src/locale/locales/pl/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/ru/messages.po
src/locale/locales/th/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/vi/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-HK/messages.po
src/locale/locales/zh-TW/messages.po
src/screens/Signup/StepHandle.tsx
src/screens/Signup/index.tsx

People get confused here unsure what "handle" is. "Input your handle" is also confusing.
The first commit replaces the wordings.
This matches our usage of "username" on the login screen.
The second commit is a bit unusual — I'm updating all translations as if this was the wording all along. That's to avoid regressions to translations just before the release. It's fine to update them later (if needed per language) since conceptually the phrasing is the same and the meaning has not changed.
It's a little inconsistent with what we have in Settings. Maybe in the future we'll change it there too. But for now let's make sure people are able to create an account.
Verify above for English.
Then `yarn intl:build` and verify translations have not regressed and show old strings:

[ELI5] Tweak wording on the signup screen

---

src/state/persisted/index.web.ts

This fixes an issue @estrattonbailey discovered. `BroadcastChannel` is arriving sooner than `localStorage` flushes the write to disk so we'd often read the storage data prematurely. This results in tabs failing to sync. This is most noticeable if you open two Settings screen in different windows and try to toggle some settings.
The fix I'm suggesting here is to rely on the window `storage` which fires when another document (i.e. another tab/window) has changed the storage. In either case we would bail if the contents of the storage is the same as before so it doesn't hurt to add an extra check like this.
https://github.com/user-attachments/assets/41914c86-c2b1-4d11-b609-59919507dcca
https://github.com/user-attachments/assets/9dd66721-ebea-4353-9fc7-d7108273ab04 …

Read storage on window.onstorage

---

src/view/com/posts/PostFeed.tsx

Previously, if the feed is empty, you'd only see it refreshed on pull-to-refresh. For example, if you have a new account, and you follow someone on Discover, your Following tab would remain empty until you pull (but it would have a polling indicator after a while).
After the fix, an empty Following would auto-refresh on focus.
https://github.com/user-attachments/assets/ad310a89-e654-4fba-982b-12977e151d20
Confirm this only happens on empty feed. It shouldn't auto-refresh a feed on _every_ focus.

Refetch empty feed on focus

---

src/view/com/notifications/NotificationFeed.tsx
src/view/com/pager/TabBar.web.tsx

Fixes the layout shift when marking notification as read. I regressed on this in #7044. Also fixes the web border being off by 2 pixels on the right (might be post layout refactor).
No longer shifting layout:
https://github.com/user-attachments/assets/e6056f52-fda4-42ac-a0f9-61719a650c15
Note that this makes a solo highlighted notif have no top border on PTR:
https://github.com/user-attachments/assets/5d6a67d3-cc0a-4c0a-b8fe-6e370d868fc5
I think that's fine personally. We could maybe special case it to add border but meh.

Fix notifications borders

---

jest/jestSetup.js
src/lib/bitdrift.ts
src/lib/bitdrift.web.ts
src/lib/statsig/statsig.tsx
src/logger/bitdriftTransport.ts
src/logger/bitdriftTransport.web.ts
src/state/session/__tests__/session-test.ts

This has two purposes:
- Make them more visible in the console so we can spot mistakes (like we used to do with Mixpanel)
- Have them also go into Bitdrift local buffer (so that they're queryable on demand automatically)
I've revamped the way Bitdrift is wired up so that our `logger` still logs into it but you can also log into it directly. So that you can push record maps too. I've noticed Bitdrift crashes with non-string values (it's strict about `Record<string, string>`) so I took the opportunity to clean up how we send Statsig metadata as well (since it also _wants_ `Record<string, string>`). I verified the serialization result is the same to how Statsig currently handles it in practice.
You'd need to use the JS debugger to see this for native: …

Pipe statsig events to logger

---

src/view/com/composer/text-input/web/EmojiPicker.web.tsx

Just needed to be wrapped in a Portal, otherwise it was being positioned relative to the center column. Floating elements like this should always be moved out to the root so they never conflict with other UI.
Test: chat and composer on web
After, before

Fix emoji picker position

---

src/components/Layout/Header/index.tsx
src/view/com/post-thread/PostThread.tsx
src/view/screens/Notifications.tsx

Makes headers sticky on web, except for:
- Notifications (not needed for root tabs, the others don't use the header component anyway)
- Post thread (maintaining content position when loading replies puts the header on top of content)
https://github.com/user-attachments/assets/9573671f-5bac-45ea-8aca-124f449e8510
Look at all screens with headers, see if there's any where scrolling down looks janky

Web sticky headers for most screens

---

src/components/StarterPack/ProfileStarterPacks.tsx
src/view/com/lists/MyLists.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/util/EmptyState.tsx
src/view/screens/Lists.tsx
src/view/screens/ModerationModlists.tsx

<table>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot 1" src="https://github.com/user-attachments/assets/82db7939-37a8-4275-baa5-7398bff43cc3" /></td>
<td><img width="200" alt="Simulator Screenshot 2" src="https://github.com/user-attachments/assets/1ffb718a-d5f6-4d1d-9135-02739c360183" /></td>
</tr>
</tbody>
</table>

Remove header subtitle from list-related screens

---

src/view/com/lists/ListMembers.tsx
src/view/com/util/EmptyState.tsx
src/view/screens/ProfileList.tsx

Moves add button into the empty state itself
<table>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot 1" src="https://github.com/user-attachments/assets/b783c8d7-9e67-4f38-a94c-9134b1190aac" /></td>
<td><img width="200" alt="Simulator Screenshot 2" src="https://github.com/user-attachments/assets/b5faf39d-6aa1-4933-b3ec-036f388c9f53" /></td>
<td><img width="200" alt="Simulator Screenshot 3" src="https://github.com/user-attachments/assets/a1944ab9-b133-4dcf-bf6a-ade8aa353de1" /></td>
</tr>
</tbody>
</table>
<table>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot 1" src="https://github.com/user-attachments/assets/6abaf9ef-7f57-4022-bcc0-f7d437aaa5e5" /></td>
<td><img width="200" alt="Simulator Screenshot 2" src="https://github.com/user-attachments/assets/19aafbeb-1659-4 …

Better list empty state

---

src/components/TrendingTopics.tsx

Native only. There's no pressable feedback otherwise

Make trending buttons `PressableScale`

---

src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/screens/Settings/ThreadPreferences.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/util/forms/RadioButton.tsx

Now that the header is always visible on all platforms, it seems like a nice place to put the sorting options.
The behavior is not perfect (e.g. it's a bit slower than I would have liked) but seems like we can ship and iterate.
https://github.com/user-attachments/assets/15424c68-9d71-44b2-9067-5401eb4e4a35
https://github.com/user-attachments/assets/3df43707-d3fd-4508-a3b0-b5914973c725

Add reply sorting in-thread

---

src/locale/locales/es/messages.po

I have corrected the word "Agregar" (previously "Aregar") in the sentence "Agregar otra publicación".

Fix spanish translation

---

src/locale/locales/fr/messages.po

It may be too early for the next version, but at least the pull request is already open, and we will be able to update it here.
- Bumped the strings;
- Translated the 18 new strings;
- Fixed a few typos / rewrote a few translations (got rid of `Feedback`, replacing it by `Commentaires` instead as I've seen this term used in other software for this matter);
- Deleted all the old, legacy strings that accumulated from a few versions now.
@surfdude29 Feel free to review! _Be careful to do it on a commit-by-commit basis_, as I took the opportunity to remove all the legacy commented strings, so it could be noisy to review it all at once. Those removals all take place in the last commit.

French translations (for v1.96)

---

src/view/com/modals/DeleteAccount.tsx

Our old `Modal` and new `Dialog`s don't play well together. This is currently broken on all platforms, so let's rm for now and replace the delete modal with new code next.

Remove deactivate dialog link from delete modal

---

app.config.js
package.json
src/lib/bitdrift.ts
src/lib/statsig/statsig.tsx
yarn.lock

The package registry it's using is down so we can't get Android to build.

Temporarily remove Bitdrift

---

app.config.js
plugins/withAndroidNoJitpackPlugin.js

We were getting some errors because this repository was down. We don't have anything that uses it, so let's remove it out of the chain to improve predictability. Then, if something upstream fails, we'll have a correct source of error.
I'm not sure where the upstream setup is. I've seen this line in RN (https://github.com/facebook/react-native/pull/25987) and in many places in Expo. But it's pretty easy to remove downstream which I'm doing here.
Android builds.
Before:
After:

Remove unreliable repository

---

src/screens/Onboarding/StepProfile/index.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

Try to work around https://github.com/ivpusic/react-native-image-crop-picker/issues/1631 which for some reason we started hitting. The delay is a bit long but should hopefully be enough for most images.

Add iOS hack to fix cropper failing to show

---

patches/react-native-image-crop-picker+0.41.6.patch
src/screens/Onboarding/StepProfile/index.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

Reverts https://github.com/bluesky-social/social-app/pull/7191 and adds a proper fix.
The root problem is hinted at in the error message in https://github.com/ivpusic/react-native-image-crop-picker/issues/1631:
>[Presentation] Attempt to present <TOCropViewController: 0x10d126a00> on <PHPickerViewController: 0x10be14b80> (from <PHPickerViewController: 0x10be14b80>) whose view is not in the window hierarchy.
We're trying to present the cropper _from_ the picker but the picker is being dismissed — so it's not valid to present _from_. I'm not sure why this wasn't hitting us before but the problem makes sense.
The issue is how the cropper determines the controller to be presented _from_. It currently looks for the innermost controller, but it doesn't take it into account that the innermost …

Proper fix for iOS cropper being stuck

---

src/view/com/util/forms/NativeDropdown.web.tsx

Web-only.
We have hundreds of these listeners at any moment in time but usually they're not doing anything:
They're only relevant when `open` is `true`, as seen in the code of the handlers.
So let's attach these listeners only if `open` is true.
Place `console.log` into the listeners. Verify they run on every keystroke across the app.
Apply the fix.
Verify they no longer run.
Verify the hashtag link web dropdown menu still responds to "Escape".

Don't add unused keydown listeners

---

src/screens/Messages/components/MessageInput.web.tsx
src/screens/Messages/components/MessagesList.tsx
src/state/shell/composer/index.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/web/EmojiPicker.web.tsx
src/view/shell/Composer.web.tsx

The emoji picker within the composer wasn't allowing users to focus the input, although the individual buttons still worked. This was due to the `FocusScope` wrapping the `Composer`, which prevents focus from leaving the composer dialog.
In #7146, I wrapped the picker in `Portal` so that its positioning was independent of wrapping elements and their styles. This had the unintentional result of portal-ing the picker _outside_ the `FocusScope`, meaning focus couldn't be applied to the picker's search input.
<s>The fix here is to wrap the picker in `Portal` only when needed, which is currently just on the `Conversation` screen. Instead of doing this in situ (first commit), I've added a `portal?: boolean` prop to the picker that optionally wraps it in a `Portal`.</s> We fixed this an explicit …

Emoji picker portaling

---

src/view/com/lists/MyLists.tsx

New empty state was missing a message for certain kinds of filters

Lists - default empty state text

---

src/view/com/lightbox/ImageViewing/components/ImageDefaultHeader.tsx
src/view/com/lightbox/ImageViewing/index.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Before Screenshot 2024-12-20 at 19 16 29" src="https://github.com/user-attachments/assets/441268fa-7184-4ad3-91f9-f98823da1cc8" /></td>
<td><img width="200" alt="After Screenshot 2024-12-20 at 19 28 37" src="https://github.com/user-attachments/assets/61792b82-4a63-431b-803f-83c03ac19b3d" /></td>
</tr>
</tbody>
</table>

Fix lightbox on android 15

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx

Avatars in quote posts are not blurred according to moderation.
The `avatarModeration` was introduced in #2325. Later the more general `moderation` attribute was introduced in #2550, which makes `avatarModeration` obsolete.
Fixes #7117.

Apply avatar moderation to quote post

---

src/locale/locales/en/messages.po
src/screens/Messages/ChatList.tsx

The Retry button on https://bsky.app/messages is not translatable. The button is shown when logged in with an app password.
(change originally included in [PR #7220](https://github.com/bluesky-social/social-app/pull/7220#discussion_r1894612488))

Make "Retry" button label translatable

---

src/style.css

On web, if the text input looses focus, e.g. because you have used the media buttons in the composer footer, it is a bit tricky to refocus the text input in order to continue writing on the post text, because only a small strip at the top of the big white area of the compose dialog is clickable.
The green line shows the current clickable area. This PR extends the clickable area to the one indicated by red line.

Extend clickable area to height of container

---

src/alf/atoms.ts
src/view/screens/Search/Search.tsx

Cheeky bit of negative margin
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-23 at 14 45 47" src="https://github.com/user-attachments/assets/26e06492-1cfc-4ac0-97c8-0c70c4b24e9b" /></td>
<td><img width="200" alt="Simulator Screenshot - iPhone 16 - 2024-12-23 at 14 42 26" src="https://github.com/user-attachments/assets/7c5ffac5-423a-4f57-8389-cc4efe44c18a" /></td>
</tr>
</tbody>
</table>
Check it works crossplatform

Fix clipping on horizontal scrollview on search screen

---

bskyweb/templates/base.html

Missed these updated from #6993.
This means the font is still being loaded twice:
https://www.webpagetest.org/result/241222_BiDcC9_64Z/1/details/cached/#waterfall_view_step1
Down from four times (as Italic is no longer preloaded), and smaller (as woff2), so it’s better, but still double what’s needed!

Correct font preload

---

src/view/screens/ProfileList.tsx

Fixes #7246 
Checking for list ownership when displaying 'Start adding people' button
**Before:**
**After:**

Validate list/feed ownership before prompting to add users in empty list state

---

patches/react-native-image-crop-picker+0.41.6.patch

Breakdown of changes:
1. Changed theme to custom `UCropNoEdgeToEdge`
2. Added new theme which just extends the old theme
3. For API level 35+ (Android 15), add `<item name="android:windowOptOutEdgeToEdgeEnforcement">true</item>` to the theme
Test main on Android 15 with 3-button navigation - observe overlap
Test this PR - overlap should be fixed
Test this PR on Android 14 or lower to check no regressions

Cropper - opt out of edge-to-edge enforcement on Android 15

---

app.config.js
package.json
src/App.native.tsx
src/alf/util/navigationBar.ts
src/view/com/lightbox/ImageViewing/index.tsx
yarn.lock

Fixes https://github.com/bluesky-social/social-app/issues/624
Unlocks device rotation when lightbox is open
Details:
- Screen orientation is locked to portrait normally. on iOS this is acheived via the config plugin, on Android we just have to call `lockAsync` as soon as it starts up
- Locking/unlocked achieved via an effect in the lightbox component
- Safe area for iOS/Android 15 was changed to not include the sides either - this was 0 anyway for portrait mode, and now allows it to be full-screen when rotated
- Lightbox state (so zoom, position etc) is cleared via key whenever an orientation change happens to ensure that it doesn't get into a wonky state
- There's some sort of double nav bar inset when sideways on Android <15. It's entirely outside of the app, not anything we're doing as …

Unlock orientation when lightbox is open

---

src/state/queries/trending/useTrendingTopics.ts

Fixes #7284
Moves mute word filtering into the `select` handler. This matches other queries in the app.

Fix mute words in trending

---

src/components/hooks/useHeaderOffset.ts
src/components/interstitials/Trending.tsx
src/view/com/posts/PostFeed.tsx

Issues with the Trending discover interstitial currently:
- The variable-height interstitial has the ability to cause scroll-position glitches.
- It is overly large.
- It isn't reliably above-the-fold, making it a somewhat rare thing to see.
This PR shrinks it down to one line, making it easier to digest, then puts it underneath the tab bar of the home screen. It retains the X button at the far right.
|Before|After|
|-|-|
|![CleanShot 2024-12-30 at 18 02 42@2x](https://github.com/user-attachments/assets/e254b7e1-4ed0-4add-be1b-3e1bef3dcc66)|![CleanShot 2024-12-30 at 22 23 08@2x](https://github.com/user-attachments/assets/9d7a718b-a725-49bf-97dd-f1d8a136ff19)|
https://github.com/user-attachments/assets/1411d59b-a826-406b-b625-0597d3195a7b

Rework discover-feed trending interstitial

---

src/locale/helpers.ts
src/locale/languages.ts
src/screens/Settings/LanguageSettings.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/composer/select-language/SuggestedLanguage.tsx
src/view/com/modals/lang-settings/ContentLanguagesSettings.tsx
src/view/com/modals/lang-settings/PostLanguagesSettings.tsx
src/view/screens/Search/Search.tsx

There are two main things that are not yet translatable in Bluesky's UI:
- Default feed names and descriptions (but this may be a can of worms to open, apart from the specific case of _Following_);
- Language selectors, in the composer and in the settings screens.
As the second one is quite ironic (don't you think? 🎶) and quite visible on a daily basis, nagging at me as the main translator of Bluesky's app into French with @surfdude29, I thought it would be great to help you out and fix it myself, so you don't have to take time away from your heavy roadmap 😅
---
In this pull request, I use `Intl.DisplayName` to offer a _best-effort_ translation of the language names, if the browser or target provides it.
:arrow_up: _Here, notice the **Français** language name. It would show **French** on …

Localize lang selectors according to the app language

---

src/components/interstitials/Trending.tsx

Ez fix. The key is on the inner element so it isn't being used. This removes the unnecessary wrapper.
Trending still works. No key warning.

Fix key issue in trending topics

---

.github/workflows/golang-test-lint.yml
Dockerfile
Dockerfile.embedr
bskyweb/README.md
bskyweb/go.mod

This is just periodic maintenance and a small increment, not any big change.
This doesn't require coordination across repos. Eg, doesn't matter if this is merged before/after the same change to `indigo`.

bump golang version to v1.23

---

package.json
patches/@mattermost+react-native-paste-input+0.8.1.patch
yarn.lock

We've got an issue with the paste input - there's two paste inputs being created, and for some reason the other one is now selectable/editable.
We can fix this by patching the library to remove the default one created by the React Native class we're inheriting from, so the real one created by `react-native-paste-input` is the only one used
https://github.com/user-attachments/assets/5b89cdd5-eac6-47b9-9387-8923b866b2cc
Try and repro the bug - involves clicking around at the very start of the composer text. Should be fixed 🤞
Check the input still works as it did
Check pasting still works

Fix double text input in composer

---

src/view/screens/Search/Search.tsx

Currently, the space available to the search input is at its smallest when focused. Let's remove the menu btn when focused to give it more space
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Screenshot 2025-01-06 at 15 32 55" src="https://github.com/user-attachments/assets/dd9ea008-5746-4ade-88d7-cbcdd83754c8" /></td>
<td><img width="200" alt="Screenshot 2025-01-06 at 15 27 35" src="https://github.com/user-attachments/assets/bb0870b7-6a01-4f95-a2e4-caf2bba69684" /></td>
</tr>
</tbody>
</table>

Hide menu button when search is focused

---

src/screens/Settings/components/PwiOptOut.tsx

Instead of mutating the existing object directly, it made types easier and was more concise to create a new value and apply it later on if needed.

[@next] PwiOptOut

---

src/view/com/util/List.tsx

Fixes #7339 
Currently, the pull-to-refresh spinner can remain the wrong color after the theme changes. I don't know enough about React Native to understand why the existing `RefreshControl` doesn't get invalidated when its `tintColor` and `titleColor` props change, but setting a key seems to fix this.
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>
https://github.com/user-attachments/assets/44b952a3-c863-4812-966d-f8cddadb8713
</td><td>
https://github.com/user-attachments/assets/654db4d6-db4b-4f98-acb6-b60c7a3dcea1
</td></tr>
</table>

Invalidate existing pull-to-refresh spinner when theme changes

---

bskyembed/index.html
bskyembed/post.html

Speed loading up the embed widget a tiny bit by pre-connecting to public.api.bsky. (like #2847).

Preconnect to public.api.bsky.app in embedr

---

src/components/AccountList.tsx
src/components/AvatarStack.tsx
src/components/KnownFollowers.tsx
src/components/Pills.tsx
src/screens/Settings/Settings.tsx
src/view/com/post-thread/PostThreadLoadMore.tsx
src/view/com/util/UserAvatar.tsx
src/view/screens/Search/Explore.tsx

Prop was missing in a couple of places, so labellers were showing up as circles

Fix avatar shape in Account switch menu

---

package.json
patches/@mattermost+react-native-paste-input+0.7.1.patch
yarn.lock

v0.8.1 causes crashes on Android. To be figured out in future.

Downgrade paste input dependency

---

src/view/shell/Drawer.tsx

Buttons at the bottom of the drawer are too close to the bottom on Android 15 with button navigation
Solving this:
Tested:
- Android 15 (gesture/buttons)
- Android 11
- iOS
- Web

Fix drawer bottom padding on android 15

---

src/view/com/composer/Composer.tsx
src/view/shell/Composer.tsx
src/view/shell/Composer.web.tsx

Supercedes https://github.com/bluesky-social/social-app/pull/7228
As far as I can tell, `KeyboardAvoidingView` is adding too much padding when the keyboard is closed on Android 15. We add a negative offset to the `KeyboardAvoidingView`, then remove the containing padding when the keyboard is open - seems to do the trick. We already do something similar for iOS.
<table>
<thead>
<tr>
<th>After</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" alt="Before" src="https://github.com/user-attachments/assets/0c330ac0-de42-427e-b857-a246b4913e4c" /></td>
<td><img width="200" alt="Before" src="https://github.com/user-attachments/assets/72f8cdac-a845-45b7-91b0-d23dae7e5d94" /></td>
<td><img width="200" alt="After" …

Fix Android composer padding: Director's Cut

---

src/App.native.tsx
src/App.web.tsx

Noticed that the verify email intent dialog was not themed correctly and was defaulting to the default light theme. This was because the dialogs were not nested within the `Alf` provider.
These providers can safely be nested much further down. They just need to wrap the `Shell`, which is where intent handling actually takes place.

Fix intent dialogs theming

---

src/components/interstitials/Trending.tsx
src/view/shell/TrendingGestureContext.tsx
src/view/shell/index.tsx

Not sure this is a full solution because it still triggers for me sometimes. But this seems to improve the situation on iOS. I'm not sure it has any effect on Android.
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/7417/files?w=1)
https://github.com/user-attachments/assets/0ce1e75a-6c45-4022-926e-120f98b2c0e4
https://github.com/user-attachments/assets/d6586ee7-fd0d-4f8e-b988-e342fead29f4
See videos above. On Android this fix doesn't seem to make it better or worse but on iOS, anecdotally, it does seem to help quite a bit. At least on the simulator.
I've also prepared a minimal repro case:
```js
import {ScrollView, Text, View} from 'react-native'
import {
Gesture,
GestureDetector,
GestureHandlerRootView,
} from 'react-native-gesture-handler'
import Animated, …
```

Partially fix trending/drawer gesture conflict

---

src/lib/strings/handles.ts
src/screens/Settings/components/ChangeHandleDialog.tsx
src/screens/Signup/StepHandle.tsx

Checks if a handle is too long in the signup flow. Handles can be up to 253 chars normally, but for PDS service handles the max is 30, including domain. I added an additional flag to the `validateHandle` function to lower the length check appropriately. I made it generic for other PDSes, rather than hard-coding 18 chars. I also corrected the logic in the change handle screen since that was hardcoded to 18.
1. Confirm that the limit really is 30 chars - go through the signup process on main with a 19 char username and confirm it fails
2. Check that the PR change catches it, and check that the error message is correct

[ELI5] Validate too long handles in signup

---

patches/react-native-gesture-handler+2.20.2.patch
src/components/interstitials/Trending.tsx
src/view/shell/TrendingGestureContext.tsx
src/view/shell/index.tsx

A simpler solution than https://github.com/bluesky-social/social-app/pull/7417.
Relies on patching in https://github.com/software-mansion/react-native-gesture-handler/pull/3322.
On iOS, this is equivalent to https://github.com/bluesky-social/social-app/pull/7417 (but simpler in code).
On Android, this seems to actually _fully fix_ the gesture conflict. I can't repro it anymore.

A simpler fix for trending swipe issue

---

src/components/interstitials/Trending.tsx
src/view/com/pager/Pager.tsx

Oops. In the copypaste, the component was shared between web and native, so it didn't work. Let's just not override types here and provide a fallback.

Fix web crash

---

src/components/ReportDialog/SelectReportOptionView.tsx
src/components/dms/ConvoMenu.tsx
src/components/dms/MessagesListHeader.tsx
src/components/dms/ReportDialog.tsx
src/screens/Messages/components/ChatListItem.tsx

Allows conversation-level reporting by reporting the most recent message available. In the chat list screen, this is the latest message that we get for the little preview, and in the chat screen itself we use the most recent message from the other person. Comes with a little note indicating that only the last few messages in the convo will be reported.
If it can't find a message to report, it falls back to the old prompt - for example if you're reporting from the chat list screen and you sent the last message
https://github.com/user-attachments/assets/eefa6cbf-94d1-48f1-91ab-e63aa230430e
Report different conversations from different menus. It should always only report the most recent message from the other person in the convo.

Conversation-level reporting by reporting most recent message available

---

src/screens/Login/SetNewPasswordForm.tsx

Supercedes https://github.com/bluesky-social/social-app/pull/6447 - CI didn't run
the error reporting currently shows `You have entered an invalid code. It should look like XXXXX-XXXXX.` even if you enter the right code but leave the password blank.

add correct error reporting for blank password

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx

**useVideoElement** repeatedly adds listener for **volumechange** event. We already add that listener [here](https://github.com/bluesky-social/social-app/blob/main/src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx#L128)
Removed call to **addEventListener** that's not needed

Remove unnecessary addEventListener call for video

---

src/view/com/pager/Pager.tsx

Hackfix for https://github.com/callstack/react-native-pager-view/issues/960.
Alternative to https://github.com/bluesky-social/social-app/pull/7312 but doesn't require copy paste and also seems to work more reliably.
Comments explain how it works.
Will need some testing.

[Android] Try to disambiguate taps from swipes

---

webpack.config.js

Webpack produces chunk and static files with references that aren't pointing to where the browser loaded the script from. When we serve the main script from a static asset CDN, the references to chunkfiles don't share the path of the CDN.
To fully leverage a static asset CDN, we should fix that hopefully with this patch.

Set webpack public path to auto to load from CDN (hopefully)

---

src/components/FeedInterstitials.tsx
src/components/interstitials/Trending.tsx
src/view/shell/BlockDrawerGesture.tsx

Makes sure this gesture doesn't conflict with the drawer:
https://github.com/user-attachments/assets/6377b9bc-330a-4f5d-9b1b-a2b50f411085
Previously the behavior was not consistent (particularly on Android) and scrolling left could make the drawer appear out of the blue. Not anymore.
Implementation-wise, this reuses the approach from https://github.com/bluesky-social/social-app/pull/7424. It's not perfect (ideally the drawer would take precedence on a swipe left when the scroll view is resting at x = 0) but we're not going to bother with that.
See video above. This was previously sometimes getting stuck on Android. Particularly on device.
Try Android (verified works on device), iOS (I only tried sim but will test on TF).
No changes on web.

Prevent Drawer gesture conflicting with Suggestions scroll

---

patches/react-native-pager-view+6.6.1.patch
src/view/com/pager/Pager.tsx

A more proper, native-level fix for the issue described in https://github.com/bluesky-social/social-app/pull/7312.
The root of the issue was https://github.com/callstack/react-native-pager-view/issues/954, ie. a cancel event wasn't dispatched to the pager's children when it started scrolling. The patch uses [notifyNativeGestureStarted](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/NativeGestureUtil.kt) to take care of that. It also disables the requestDisallowInterceptTouchEvent calls because they mess with the Drawer

[Android] Fix taps triggering while swiping

---

src/view/com/posts/PostFeed.tsx

When we run out of posts in Following, we fall back to showing posts from Discover.
This shouldn't generally happen unless you run out of posts from your follows. However, a few days ago we had a backend migration that caused the timelines to restart. So we were falling back into this mode even for who folks who follow people.
Unfortunately the conditions that caused the UI to show up got lost with one of the refactors so they were showing up without explanation. This restores the explanation.

Fix Discover posts showing up in Following with no explanation

---

src/view/com/pager/TabBar.tsx

Fixes https://github.com/bluesky-social/social-app/issues/7494
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/7501/files?w=1)
Repro:
- Open profile
- **Do not** change tabs, just scroll the tabbar a bit to the right
- Then scroll it to the left
Before the fix, it wouldn't scroll left.
After the fix, it does.
This is only strictly necessary on Android, but seems fine to do on iOS. We can later do another pass at making these exclusions smarter but ideally I'd like to make it work on both platforms then.
https://github.com/user-attachments/assets/f16bc9b6-4d11-4b8c-a824-c1da0996e8eb

Fix tabbar swipe conflicting with drawer

---

src/screens/VideoFeed/index.tsx

Performance improvement - by having the players available immediately, it starts playing instantly
Ideally, we'd enable this on android too, but it's too much for low-end android phones to render 3 video players at once. We should consider keeping a list of android phones and their performance class so we can switch behaviour based on this. **This would fix the black frame issue**
Test on device pls
- Test iOS, confirm it feels snappier
- Test Android, confirm it's the same

Render adjacent players on iOS

---

app.config.js
package.json
src/lib/bitdrift.ts
src/lib/statsig/statsig.tsx
yarn.lock

This reverts the PR to remove bitdrift and updates it to the latest version 0.6.1
Notable changes:
- The session management strategy has been exposed in the API. We configure it as activity-based which means that sessions will span multiple process lifetimes if they happen close together, and time out if the app is inactive for too long.
- `addField` has been added, which allows adding global fields that will be present on all logs going forward
- Network integration has been enabled for Android, which should automatic logs for every HTTP call made by the app. The iOS integration does not currently work with Bluesky due to some timing issues related to the bitdrift SDK being behind a feature flag, so this is disabled until we can implement a known fix.

update and re-enable the bitdrift SDK

---

src/lib/constants.ts
src/lib/statsig/gates.ts
src/screens/Onboarding/StepFinished.tsx

If you pass the gate, we'll add it as the third tab. If you don't, we won't.
Create a few accounts. Verify that, if you're in the gate, you get this after signup:
Ofc it can be removed later as usual.

[Experiment] Add Video feed on signup

---

app.config.js

In #6835 the language tag for Cantonese in the `CFBundleLocalizations` key was changed from `zh_HK` to `yue-Hant` in an effort to get Cantonese listed as one of the supported languages on the App Store page.
Unfortunately, that doesn't seem to have worked:
So as discussed in https://github.com/bluesky-social/social-app/pull/6835#issuecomment-2507264652, this follow-up PR tweaks the language tag to simply `yue`.
Pinging @auroursa for feedback.

Tweak Cantonese language tag in `CFBundleLocalizations` key

---

src/state/queries/post-thread.ts

This hasn't landed into an `@atproto/api` release yet but it's a one-liner so I figure we can `@ts-ignore` and fix later. The actual backend change is already deployed.
This tweaks the ranking formula for Hotness so that replies liked by the thread author (OP) decay a bit slower. In practice, this means that they'll stay closer to the top (but fresh comments will still get their fair chance).
I've considered solutions like bumping the like count by a fixed number, but this doesn't work well for threads of different size. Slowing down the decay exponent ensures that fresh posts still get good visibility, the effect compounds over time, it works for any like counts, and that the boost stays meaningful but not overwhelming. 
I also considered strictly prioritizing them above other posts but …

Adjust the decay formula

---

src/screens/VideoFeed/index.tsx

Just tidying up the code:
- Avoid extra runtime checks by tightening the types
- Remove default argument, be explicit in the calling code
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/7536/files?w=1)
Can still swipe up and down. Can still start in the middle. Can still navigate away to author and back.

Minor video feed refactor

---

src/view/com/util/UserBanner.tsx

Very simple, does what the warning has been telling us to do
Look at banner. it should be the same

Fix "resizeMode is depreciated" depreciation warning

---

src/lib/api/feed/author.ts

Just moving to an allowlist which solves the problem for Videos tab (currently it shows non-video pins on the web).
In the future we might make pins per-tab but that future is not now.
Not seeing the pin here anymore.
Posts and Replies retain the pin.

Only show pins on Posts and Replies

---

package.json
src/state/queries/post-thread.ts
yarn.lock

Follow-up to https://github.com/bluesky-social/social-app/pull/7535 adjustments in Hotness formula. I'm tweaking based on first impressions after living with this for a day. It didn't feel strong enough in my testing so I'm bumping it up a bit.
- Changing the OP-liked decay from `0.85` to `0.8` to make it slightly more pronounced
- Adding a fixed linear score boost (setting it to `1.45`), which makes them stickier
Also drive-by removal of `ts-ignore`.
Verify OP like is a bit stronger now, e.g. on Jay's swords post.

Tweak adjustment in the formula

---

src/lib/api/index.ts

This adds trimming of *leading whitespace-only lines* to posting.
The goal is to reduce cases where people accidentally linebreak before their replies.
This doesn't break ASCII art — we don't trim whitespace on leading lines that contain non-whitespace characters.
Read the regex, convince yourself it's correct.
Try cases like this:
```
test
test
test  
```
Expected output:
```
test
test
test
```

Trim leading whitespace-only lines

---

bskyweb/templates/base.html
web/index.html

Since the migration to the mushroom PDS's the app no longer needs a pre-established connection to `bsky.network` which should no longer be used by the App.

Remove "bsky.network" from preconnect

---

.eslintrc.js

I'm strongly in favour of adding this rule to our eslint config.
Using `@ts-ignore` over `@ts-expect-error` leads to sloppy typing, and we have many cases across our codebase where a formerly bad type has since been fixed but typechecking is still disabled. For example `desktopFixedHeight` in the `List` component. This has actually bitten me in the past, since it can let type breakages slip though unexpectedly.
Unfortunately, we have about 180 uses of `@ts-ignore`, so we can't just do it all at once. Let's turn the rule on as `warn`, incrementally fix up commonly touched files as we touch them, then change to `error` later down the line

Add ban-ts-comment rule as warn

---

package.json
src/components/Link.tsx
src/components/dms/ReportDialog.tsx
src/lib/constants.ts
src/lib/statsig/events.ts
src/screens/SignupQueued.tsx
src/screens/Takendown.tsx
src/state/session/agent.ts
src/state/session/index.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
yarn.lock

<table>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/b26a90f3-3515-496f-8fc9-a7790f2153ca" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/2480f573-46ca-4e41-a99e-bba80f73dead" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/09a4748e-ee8e-4441-8864-ae34d0289d1e" /></td>
</tr>
</tbody>
</table>
<table>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/3545a4fb-4f41-4b12-a9e4-9a22e80bf47c" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/5a83f5ac-af19-4e44-8eb6-a8b2f257af63" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/8e0494c7-ba5a-4338-9f1c-8f7ab8cc6f6e" /></td>
</tr>
</tbody>
</table>
<table>
<tbody> …

Takendown state + in-app takedown appeals

---

src/screens/Signup/StepCaptcha/index.tsx

The containing element had a fixed height, but also extra padding. There is already spacing between elements, so this is unnecessary. I also increased the height by 10px to be safe.
Testable on native. The image grid is the tallest hcap test I was able to get, so you might need to go back and forth a couple times. I cannot test on web but theoretically, it should be exactly the same.
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/3a54c065-e9af-4379-92f2-e19181c8d5d8" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/bb4d2435-ace4-4430-aaf9-85b3aa9b37c3" /></td>
</tr>
</tbody>
</table>

Fix hcap clipping

---

src/locale/locales/fr/messages.po

Thanks to @pfrazee's new Bat-Signal 🦇 (i.e. #7542), here are 50 new translated strings in French for the upcoming v1.97. ✨
Some of them are not new translations, but simply a copy and paste of an old translation whose variable placeholder names have been changed (it happens sometimes...).
Ping @CerryTsuki and @surfdude29, as usual, for a review.  🙇

French localization for v1.97

---

src/locale/locales/ru/messages.po

Problem:
Phrase "Начните одну!" is a word-by-word translation of "Start one!" which is not something that we usually say in Russian language, it _doesn't sound right_.
Solution:
A more appropriate ways to translate it would be:
1. Создайте первую!
2. Начните новую!
3. Создайте новую!

Update Russian phrase

---

src/screens/VideoFeed/index.tsx

Currently it's awkwardly narrow compared to the reply prompt

Reduce padding on video overlay

---

src/view/screens/Search/Search.tsx

Before: cancel closes the input and restores previous search input (i.e. search "hello", delete input, press cancel restores input to "hello")
After: cancel clears input and returns to explore page
It is currently frustrating to return to the explore page from the search page. This change aligns behaviour with iOS search inputs (see apple music or whatever)

Change search cancel behaviour

---

src/view/screens/Search/Search.tsx

Should have zero functionality change, but fixes up bad React code
Confirm it works the same. I am pretty sure this case occurs when the query string is modified - i.e. when the search input is cleared

Search - clean up refs in render

---

src/components/dms/ConvoMenu.tsx

An easy optimisation to make the chat list faster. Nesting the contents of the convo menu inside `Menu.Outer` makes it lazy, so it only renders once the dialog opens.
Ensure all the buttons work
Add a console log to `MenuInner` to confirm it's now lazy

Make convo menu lazy

---

src/components/forms/HostingProvider.tsx
src/view/com/auth/server-input/index.tsx

Refactors the hosting provider dialog - it fell into the trap of the cross-portal state changes being really slow. Most state is moved down into the dialog
Confirm no functionality changes

Fix slow Hosting Provider dialog

---

src/lib/media/util.ts

Allow .webp thumbnail preview when pasting urls
https://github.com/user-attachments/assets/8d7dbe3b-94d7-4e4e-b237-6ae855b9888b
https://github.com/user-attachments/assets/bdd0702c-b17e-4342-805f-9ba39a7997ed

Allow .webp thumbnail preview when pasting urls

---

src/locale/locales/da/messages.po

Add missing strings to Danish (da) locale for v1.97.0.
While waiting for #7220 to be merged, I was monitoring the commit log of [src/locale/locales/en/messages.po](https://github.com/bluesky-social/social-app/blob/main/src/locale/locales/en/messages.po) to see if any new strings were added, but it seems this was not a good way to check for that :-)

 Update Danish localization for 1.97.0 

---

package.json
src/Navigation.tsx
src/components/dialogs/PostInteractionSettingsDialog.tsx
src/lib/routes/types.ts
src/routes.ts
src/screens/Moderation/index.tsx
src/screens/ModerationInteractionSettings/index.tsx
src/screens/Settings/components/ExportCarDialog.tsx
src/state/queries/post-interaction-settings.ts
src/state/queries/preferences/const.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/state/composer.ts
yarn.lock

This PR adds a new screen, accessible via the Moderation screen, that allows users to set default post interaction settings (postgate and threadgate settings). These settings are then used to pre-fill the interaction settings dialog in the composer.
The new screen actually uses the same components as the dialog itself. To accomplish this, I had to break out the `Header` from the `Form` component, but other changes were not necessary to the interaction settings form itself.
The new screen is pretty straightforward, basically just the form and a call to set these values in user preferences.
1. Out of the gate, test that the interaction settings dialog works as normal. No defaults to pre-fill, works as before.
2. Then go set some default settings, and test that those are reflected in the …

[APP-1013] Configure and apply default post interaction settings from user preferences

---

src/state/queries/profile.ts
src/storage/index.ts
src/storage/schema.ts
src/view/screens/Search/Search.tsx

Refactors the search history to partition the history by DID, so that history is unique to the logged-in account
I also changed it to use ~~react-query, since that's better for handling async state~~ the new MMKV storage!
Generate some search history
Switch to and from accounts to confirm it's partitioned

Per-user search history

---

src/view/com/modals/Modal.tsx

Currently, some bottom sheets in the app use @discord/bottom-sheet. There is a visual bug where in dark mode, if you drag the handle, the background is white.
This fixes it by adding the `backgroundStyle` prop to the BottomSheet component and setting the background using that.
Before:
<video src="https://github.com/user-attachments/assets/db91aeed-1dac-487b-a306-56ac8e110d12" />
After:
<video src="https://github.com/user-attachments/assets/1b93fccc-8f00-45f9-84ea-f60a2232891b" />

Fix bottom sheet styling in dark mode

---

src/screens/Settings/Settings.tsx

There's a string in Settings which is currently marked for translation but it consists only of the user's handle:
https://github.com/bluesky-social/social-app/blob/b12d39b4cff0fe1b91fb16496c3fea1ed22de5cf/src/screens/Settings/Settings.tsx#L423-L425
And thus it contains no translatable text:
https://github.com/bluesky-social/social-app/blob/b12d39b4cff0fe1b91fb16496c3fea1ed22de5cf/src/locale/locales/en/messages.po#L103-L105
So this PR removes the translation tags.

Unmark string for translation

---

src/components/WhoCanReply.tsx

If the app doesn't know about a threadgate, it'll crash when clicking on the threadgate detail modal. not great.
See it in action here: https://bsky.app/profile/samuel.bsky.team/post/3lhmnrxyppc2j
(will stop working once we release https://github.com/bluesky-social/social-app/pull/7681)
Click on the threadgate details on this post
https://bsky.app/profile/samuel.bsky.team/post/3lhmnrxyppc2j

Fix unknown threadgates causing crashes

---

.github/workflows/nightly-update-source-languages.yaml
docs/localization.md
package.json

This update automates the extraction of source-strings into the english `messages.po` file. It runs using a GitHub action every night, which should subsequently sync to Crowdin.

More i18n process updates

---

package.json
src/components/WhoCanReply.tsx
src/components/dialogs/PostInteractionSettingsDialog.tsx
src/state/queries/threadgate/types.ts
src/state/queries/threadgate/util.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
yarn.lock

Adds `followersRule` support to interaction settings. App view and dataplane are already deployed and working, so all that's left is the UI.

[APP-1031] Add new followerRule to threadgate settings

---

package.json
src/lib/bitdrift.ts
yarn.lock

This updates the bitdrift library to 0.6.7, which brings in a new version of the Capture SDK that addresses the limitations with the iOS networking integration that caused it to not play well with the bluesky app.

update bitdrift to 0.6.7 and enable iOS network integration

---

package.json
yarn.lock

This PR supersedes https://github.com/bluesky-social/social-app/pull/7575, the PR that added network instrumentation. 
It's important this PR is merged before adding `enableNetworkInstrumentation:true` to the bitdrift .init config since versions before 0.6.8 had a permission issue that caused the app to crash when backgrounded.
It may make sense to add the value of `enableNetworkInstrumentation` behind a feature flag. I'm going to leave that up to the maintainers if they want to enable the instrumentation, and if it should be feature flagged.
Take care :—)

deps: Bumps bitdrift to 0.6.8 & fixes iOS network instrumentation bug

---

src/components/ListCard.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Quote & list embeds have a problem with their padding, in that the pressable link area is contained within the padding, meaning the padding area is not clickable. Easiest to understand by just looking at the before/after of the pressable area
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/b71405f3-432a-496a-884e-3d71ccded277" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/530f6f18-2fe9-4fed-b16d-bbeec9329046" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/068deaf1-fba1-473c-9dbd-5bf54942e222" /></td>
<td><img width="300" …

Fix quote & list padding not being pressable

---

src/alf/atoms.ts
src/components/Dialog/index.web.tsx
src/style.css
src/view/shell/Composer.web.tsx

Adds new animation atoms with some preset animations, and animates dialogs (including the composer) with a combined fade/zoom animation. Respects prefers-reduced-motion
It'd be nice to have exit animations on these, but the elements are unmounted on hide so would require deeper reworking to get that functional
https://github.com/user-attachments/assets/582de7a3-6f45-486d-8459-1d51b22094e6
Test different browsers, check that all the animations look good and don't impede functionality

Better animations for dialogs, animate web composer

---

src/components/Menu/index.web.tsx
src/style.css

Animates dropdown menus with a fade/zoom, with the origin being towards the direction of the trigger. Works in both directions thanks to a special radix css variable. Respects prefers-reduced-motion
https://github.com/user-attachments/assets/6caa5372-6772-4fee-95f5-0e5fa66d5da4

Animate dropdown menus

---

src/lib/statsig/gates.ts
src/screens/Onboarding/StepFinished.tsx

I want to keep this gate around because I still want to run the experiment to see how effective it is.
However, on the assumption it's a good change, we need it to fail open, since if statsig fails (adblock etc) they'll get the rubbish old one. Therefore, we invert it from a 100% rolled out gate to enable the new onboarding to a 0% rolled out get to disable it

Invert new postonboarding gate

---

src/components/StarterPack/StarterPackCard.tsx
src/components/TrendingTopics.tsx
src/screens/Search/components/ExploreRecommendations.tsx

Given that the content will (for the time being) usually mostly be all feeds, we should give starter packs a special treatment using the starter pack icon
I also changed the wording of the subheader when there's non-feed content in there

Special treatment for recommended starter packs

---

src/alf/atoms.ts
src/style.css
src/view/shell/index.web.tsx

Animates both ways. Animating in uses an exponential easing function
https://github.com/user-attachments/assets/a027ee65-3612-400d-8084-19ef7b537e20

Animate drawer menu on mobile web

---

src/components/Layout/Header/index.tsx
src/components/forms/TextField.tsx
src/view/screens/Search/Search.tsx

Redesigned search input - it now sits below the header, and moves into place when focused. The language select has been moved to the top right
https://github.com/user-attachments/assets/f9f0f330-178d-4fcc-9302-c2840670e674

Improved search page

---

src/state/queries/feed.ts

In #4818 we added filtering for labels on feeds, but in most cases it was not effective. This PR opts to use `contentMedia` view for feeds, which is technically not correct for this use case, but does the job it should be doing for now.
We will follow-up with improvements to make this more sound in the near future.

Use effective filtering for feeds

---

package.json
src/lib/bitdrift.ts
src/lib/statsig/statsig.tsx
src/screens/Settings/AboutSettings.tsx
yarn.lock

Includes two PRs relating to version bumps, which puts us at the latest version.
This PR then integrates two new feature flags:
- `enable_bitdrift_v2` which replaces the initial flag
- `enable_bitdrift_v2_networking` which conditionally enables network logging (which caused a bug previously)
Decided to replace the initial flag so that as we ramp this new version, we don't ramp older clients that are still using the old version of the Bitdrift library.
Tested on TF and APK. Web should have no changes.

Bitdrift integration

---

src/lib/statsig/events.ts
src/screens/Login/LoginForm.tsx
src/screens/Login/SetNewPasswordForm.tsx
src/screens/Login/index.tsx
src/view/com/auth/server-input/index.tsx

Adds the following new events
- `signin:hostingProviderPressed`
- `signin:hostingProviderFailedResolution`
- `signin:success`
- `signin:backPressed`
- `signin:forgotPasswordPressed`
- `signin:passwordReset`
- `signin:passwordResetSuccess`
- `signin:passwordResetFailure`
Filter console logs for `signin:`, observe the logs happening. Check they look correct.

[Instrumentation] Signin

---

bskyweb/cmd/bskyweb/server.go
src/Navigation.tsx
src/lib/routes/types.ts
src/routes.ts
src/screens/Profile/ProfileSearch.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/screens/Search/Search.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2683, https://github.com/bluesky-social/social-app/issues/2684, https://github.com/bluesky-social/social-app/issues/7018.
https://github.com/user-attachments/assets/1d9205cb-a96d-4a7a-ba52-51843380a3b7
- Test new screen on iOS/Android/Web (web especially)
- Ensure no regressions on the primary search page

Screen for searching user's posts

---

src/App.native.tsx
src/App.web.tsx
src/components/AccountList.tsx
src/components/dialogs/Signin.tsx
src/screens/Deactivated.tsx
src/screens/Login/LoginForm.tsx
src/screens/Settings/components/AddAppPasswordDialog.tsx
src/screens/Settings/components/DeactivateAccountDialog.tsx
src/screens/Settings/components/Email2FAToggle.tsx
src/screens/SignupQueued.tsx
src/screens/Takendown.tsx
src/state/queries/list-memberships.ts
src/state/queries/list.ts
src/state/queries/messages/actor-declaration.ts
src/state/queries/pinned-post.ts
src/state/queries/starter-packs.ts
src/view/com/auth/SplashScreen.tsx
src/view/com/auth/SplashScreen.web.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/com/util/forms/PostDropdownBtnMenuItems.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/screens/DebugMod.tsx

Fixes "log in", "log out" to "sign in", "sign out". Since most of the inside of the app uses "sign", it made sense to unify it to "sign".
Please let me know if "sign" and "log" are used interchangeably.
And based on multiple search results, fixes "sign into" to "sign in to".
https://linguix.com/english/common-mistake/sign_into
https://www.scribbr.com/frequently-asked-questions/log-into-or-log-in-to/

Fix "log in", "log out" to "sign in", "sign out"

---

src/components/moderation/LabelsOnMeDialog.tsx
src/components/moderation/ModerationDetailsDialog.tsx
src/lib/hooks/useTimeAgo.ts
src/lib/moderation/useModerationCauseDescription.ts

Show's label expiration (if set) on labels, for both the labeled user and viewers.
I also opted to align the UI a bit here from where it was, since I think the `LabelsOnMe` dialog treatment is more attractive and succinct, and works well for the expiry handling.
Also, `useGetTimeAgo` is really just a date diff, so tbh we could rename that to make it more obvious that it can be used for future dates too.
We should really build a real tooltip too for web hovers e.g. to show the precise expiry on hover.

[APP-1049] show label expiration in frontend

---

src/view/com/util/post-ctrls/PostCtrls.tsx

This handling was supposed to use the profile shadow cache to check if the viewer was following the root post author, but instead it was checking only the highlighted post and not the root.
Unfortunately, we do not have the root `PostView` available to us in all post contexts e.g. reply notifications. This means we can't pull a profile out of the cache, and therefore we can't optimistically handle follows when calculating reply disablement.
We _can_ do this in some contexts, namely threads and feeds, but a closer eye needs to be given to this problem to ensure that we accurately compute `replyDisabled` overrides on the client.
So this PR opts to leave this logic entirely up to the server, and we'll follow up with improvements.
What this means for an end user is this:
- OP adds the `Your …

Remove shadowed follow gate handling

---

src/screens/Settings/components/ExportCarDialog.tsx

Improve car dialog styles

---

package.json

We suspect that the reason OTA is dropping translation strings is because the extract call isn't running on all languages.

Update intl:build to extract for all languages

---

.github/workflows/nightly-update-source-languages.yaml
crowdin.yml

With the switch to the crowdin enterprise, I'm going to make two updates:
1. Gotta update the core config file
2. Change the nightly action to push directly to crowdin after extracting source strings. Previously this was handled by the GitHub integration in crowdin, but that tool only supported bidirectional sync. All we want to do is regularly sync the source strings to crowdin.

Add crowdin nightly push

---

modules/bottom-sheet/android/src/main/java/expo/modules/bottomsheet/BottomSheetView.kt
modules/bottom-sheet/src/BottomSheetNativeComponent.tsx
src/components/Dialog/index.tsx
src/components/Menu/index.tsx

This resolves a longstanding bugbear I've had with our sheets for a long time and is a cluster of issues that we were fixing with horrible magic numbers in the bottom padding.
**iOS**:
We were setting the height of the sheet as screen height, but actually the sheet presentation does not include the top safe area. so all our sheets were <top inset> too tall with content going off the screen below, invisibly. This was forcing us to add extra padding, which meant that the behaviour to switch to the full-height mode was triggering way too early (which is why I set about fixing all this).
**Android**:
I haven't totally resolved this one yet, but I *think* the issue is that the half expanded ratio calculate isn't accurate. I tried to patch it, but ended up not being able to completely remove …

Get sheet padding working consistently

---

src/components/dialogs/BirthDateSettings.tsx
src/lib/strings/time.ts

Sets the minimum birthday you can set your birthday to to 13 years ago from today. Accounts cannot be created with an earlier birthday than that anyway
Confirm the min date is correct, and that the date picker limit works

Set minimum birthday to 13 years ago in birthday edit dialog

---

src/view/com/profile/ProfileMenu.tsx

Unlike all other menus, the profile menu uses Title Case. Changes it to use Sentence case ~~This is a find-and-replace to change it to Sentence case, including translations to prevent churn~~

Consistent capitalisation on profile menu

---

src/components/forms/DateField/index.shared.tsx
src/components/forms/TextField.tsx

At some point, our android text inputs got shorter, but the datefield didn't follow suit. this aligns the height properly and cleans up a bit of the conditional logic
Also fixes a clipping issue with `SuffixText` on web
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/d4382f3d-ccff-41d4-af38-33627de5e0d1" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/74ecfc9f-5ee7-46d0-9957-c0cfd179c479" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/ecdcbf46-f9d4-40d8-a40f-88a23e0883b3" /></td>
<td><img width="400" …

Fix android datepicker height

---

src/components/StarterPack/ProfileStarterPacks.tsx
src/state/queries/actor-starter-packs.ts
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/screens/Profile.tsx

We have a mechanism for precaching profile data before you navigate to it - however, this mechanism is broken, because we hold up rendering by waiting for the starter pack query to come in. However, we already know if they have starter packs. because it's in the `profile.associated` object, so we can just render the tab based on that like we do with feeds and lists. Navigation is thus instant again 🚀
This hack also mean that the starter pack query was run eagerly rather than lazily. I moved it down into the list component, so it only fetches lazily like the other tabs - this meant patching up the pending states, since they were broken due to the data typically being already available. While here, I also fixed the pending states for the feed list and list list. …

Fix optimistic rendering of profile page

---

src/view/screens/Search/Search.tsx

Uses a custom `<Link>`, so needs manual precaching

Precache recent profile click

---

src/screens/Signup/StepInfo/index.tsx
src/screens/Signup/state.ts
src/view/com/modals/ChangePassword.tsx

First and foremost: passwords are now minimum 8 characters.
Signup form errors can now be specific to a field, and go away once once the field passes the validity check so that the user knows when it's good.
Also rearranged the email validity check, because it would do the double check confirm then reject anyway if it failed the regex. Now it eagerly rejects really bad emails, doing the TLD check last
https://github.com/user-attachments/assets/6417c713-f707-45b4-b232-e618c7647313
Stress test the signup form. Enter errors in different orders etc, see that they clear properly

Basic minimum password requirements, plus field-specific errors

---

src/screens/List/ListHiddenScreen.tsx

Following [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-engb/9#3577):
> It's a really really bad idea to use pronouns for concatenation because they are heavily inflected in many languages depening on the context. For example, while you as the subject may be _thu_ in ScG, _from you_ becomes _uat_ and _to you_ _dhut_ or _thugad_ depending on context. UI strings with pronouns are best hard coded. Or need a detailed explanation of context.
I used ChatGPT and trial and error to put together this PR. Instead of the current combined string, where either `you` or the handle is used:
https://github.com/bluesky-social/social-app/blob/7a3a1a2bd07ba6a38c7886105491bb96df2ebd62/src/screens/List/ListHiddenScreen.tsx#L145-L156
This PR creates separate strings that can be fully …

Separate strings for translation in `ListHiddenScreen.tsx`

---

src/screens/Signup/StepHandle.tsx

Following [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/9#3751):
> This needs a place holder for languages where the {0} does not come last in this phrase
This PR moves the translation tags on the `Choose your username` screen from where they are currently:
https://github.com/bluesky-social/social-app/blob/7a3a1a2bd07ba6a38c7886105491bb96df2ebd62/src/screens/Signup/StepHandle.tsx#L127-L134
to include the username as well, so that it can be positioned appropriately in all translated strings:
https://github.com/bluesky-social/social-app/blob/b0c4844290c26c1eeb25474f59f862b9cd20c795/src/screens/Signup/StepHandle.tsx#L127-L136
[Link to review without whitespace](https://github.com/bluesky-social/social-app/pull/7823/files?diff=unified&w=1)

Move translation tags on `Choose your username` screen

---

docs/localization.md

This PR suggests a few updates to the first sections of the localization doc (all dealing with translation):
- Most importantly, it updates the Crowdin links from the deprecated project to the current Crowdin Enterprise project.
- It removes the reference to opening a discussion on Crowdin because that feature isn't available on Enterprise unfortunately.
- It adds a reference to requesting a new language directly on Crowdin by clicking the **Request New Language** button.
- A few minor wording tweaks.
The suggested update can be previewed [here](https://github.com/surfdude29/social-app/blob/update-localization-doc/docs/localization.md).

Suggested updates to localization doc

---

src/components/dialogs/MutedWords.tsx
src/screens/Login/LoginForm.tsx

Following feedback on Crowdin, this PR suggests tweaking a few accessibility strings to make them clearer:
- [`Retries sign in` `accessibilityHint`](https://bluesky.crowdin.com/editor/1/11/en-gd/9#2531) on Crowdin:
Tweaks the `accessibilityHint` for the `Retry` button when there's been an issue signing in from:
`Retries sign in` ➡️ `Retries signing in`
https://github.com/bluesky-social/social-app/blob/7a3a1a2bd07ba6a38c7886105491bb96df2ebd62/src/screens/Login/LoginForm.tsx#L321-L332
- [`Add mute word for configured setting` label](https://bluesky.crowdin.com/editor/1/11/en-gd/9#219) on Crowdin:
Tweaks the `label` for the button which adds a mute word from:
`Add mute word for configured settings` ➡️ `Add mute word with chosen settings` …

Tweak accessibility strings

---

src/screens/Messages/components/MessageInput.tsx
src/view/screens/Storybook/Forms.tsx
src/view/screens/Storybook/index.tsx

Explained in a comment:
```
// bit of a hack: iOS automatically accepts autocomplete suggestions when you tap anywhere on the screen
// including the button we just pressed - and this overrides clearing the input! so we watch for the
// next change and double make sure the input is cleared. It should *always* send an onChange event after
// clearing via setMessage('') that happens in onSubmit()
```
Basically, pressing a button will always accept the autocomplete suggestion on iOS - including the send button! and for some reason this takes priority over our code trying to clear the input.
Solution: wait for the next change event and clear it then.
Also includes storybook cleanup
- Type something that'll get autocomplete suggestions like "Hel" and confirm that this PR correctly clears the …

Fix DMs input automatically accepting autocomplete suggestion instead of clearing

---

src/components/FeedCard.tsx
src/view/com/feeds/FeedSourceCard.tsx

[Feedback was raised on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/9#2383) that the title text in the prompt shown when removing a feed is confusingly worded.
This PR tweaks the prompt title text from:
`Remove from my feeds?` ➡️ `Remove from your feeds?`
and thus aligns the title text with the description text.
https://github.com/bluesky-social/social-app/blob/7a3a1a2bd07ba6a38c7886105491bb96df2ebd62/src/components/FeedCard.tsx#L308-L317

Tweak prompt title text when removing a feed

---

src/screens/Settings/LanguageSettings.tsx

Following [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/9#2667):
> This is a rather tortured English sentence for selecting the UI language and should be revisited. Something like "Select a language for the apps user-interface" would be much easier to understand. The way it's now, it first made me wonder if this was a language selector for some sort of dummy text in certain fields until I found it in the UI language selection menu.
This PR proposes slightly different wording, changing the text from:
`Select your app language for the default text to display in the app.`
to
`Select which language to use for the app's user interface.`

Tweak app language string in Settings

---

src/view/com/util/post-embeds/VideoEmbedInner/TimeIndicator.tsx

Following [feedback raised on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/9#3175), this PR adds plural formatting to the `accessibilityLabel` for the video time indicator.

Plural formatting for `TimeIndicator` `accessibilityLabel`

---

src/lib/api/feed/likes.ts

Fixes #4879 #4931 #6179
I believe this is an error on the server side - it returns a cursor even when there are no more results. This is easy enough to detect and fix clientside, so let's do that.
Check the likes tab on an account with no or few likes

Fix likes tab endlessly pagniating

---

src/components/Dialog/index.web.tsx

Also noticed the `Close` button looked wack, and realized I had a wrapper around dialog content that is no longer needed with top-aligned dialogs.

Fix max height of dialog flatlists

---

src/alf/breakpoints.ts
src/components/Dialog/context.ts
src/components/Dialog/index.tsx
src/components/Dialog/index.web.tsx
src/components/Dialog/types.ts
src/components/Layout/Header/index.tsx
src/components/Layout/index.tsx
src/screens/Deactivated.tsx
src/screens/Profile/Sections/Labels.tsx
src/view/com/auth/SplashScreen.web.tsx
src/view/com/posts/PostFeed.tsx
src/view/com/util/Views.web.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx
src/view/screens/Home.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/desktop/LeftNav.tsx
src/view/shell/desktop/RightNav.tsx

Fixes https://github.com/bluesky-social/social-app/issues/3578
Adds new breakpoints for web:
1. 1075px to 1200px - right nav visible, main content offset to side
2. 800px to 1075px - no right nav
I also moved the left nav on the tablet breakpoint to sit next to the content, rather than being stuck to the far left edge
Check all the screens at the new breakpoints. I have tested:
1. All the common ones I can think of (timeline, feeds, profile, thread, settings etc)
2. Logged-out view
3. Signup queued
4. Deactivated
5. Takendown
6. Onboarding
7. Auth flow
And make sure there's no regressions on the mobile/desktop breakpoints

Better tablet layout

---

src/screens/Messages/ChatList.tsx
src/view/com/notifications/NotificationFeed.tsx

Realised this was missing. Now works like other tabs
Check that chat list scrolls to top when pressing the tab

Add soft reset to chat list

---

src/components/moderation/LabelPreference.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="680" src="https://github.com/user-attachments/assets/61babede-d322-45a6-a621-5bfb9cf62ec6" /></td>
<td><img width="645" src="https://github.com/user-attachments/assets/9f0ce8a9-6b09-4656-8fd5-5afb24624244" /></td>
</tr>
</tbody>
</table>

Fix label preference alignment

---

src/components/AvatarStack.tsx
src/screens/Settings/Settings.tsx

AvatarStack now has two versions, rather than squishing both use cases into one
1. AvatarStack takes an array of AnyProfileViews
2. AvatarStackWithFetch takes an array of DIDs and performs a fetch first

[Inbox] Separate avatar stack into two components

---

src/components/forms/HostingProvider.tsx

I moved the `<Button>` to inside the `<Trans>` because some languages need to be able to move the position of the hosting provider name.
Also modified the margin style to eliminate line height differences.

Modify hosting provider text for better localization

---

src/screens/Profile/components/ProfileFeedHeader.tsx
src/view/com/auth/SplashScreen.web.tsx

Following [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-ia/9#1651) that the `Like feed` label is ambiguous and was being misinterpreted by translators:
> Does this message refer to a feed of likes, or to the action to like a feed? […]
>
> Under "Other languages", most of the languages I can read have translations that assume the first, not the second, so they would be wrong - e.g. Dutch, Spanish, Portuguese, Italian, Catalan, Aragonese are all wrong, and probably many others.
This PR tweaks the label to `Like this feed` which is hopefully clearer and less ambiguous.
Concern was also [raised on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-ia/9#1573) about the `Jobs` string:
> What type of "jobs" are we talking about here? […]
>
> Here too, many of the existing …

Tweak accessibility label and add translation comment

---

src/components/dms/MessageProfileButton.tsx
src/state/queries/messages/get-convo-availability.ts
src/state/queries/messages/get-convo-for-members.ts

Should cut down on "ghost convos" when visiting people's profiles
Check profile DM button still works as before, with pending state, different declarations, and still being able to DM someone you already have a convo with even if they have since closed their DMs

[DMs] Use new convo availability API

---

src/screens/Profile/Header/ProfileHeaderLabeler.tsx

I noticed that in `src/screens/Profile/Header/ProfileHeaderLabeler.tsx` the label for the heart icon mistakenly reads `Like this feed`. This PR fixes that by changing it to `Like this labeler`.

Fix accessibility label

---

bskyweb/cmd/bskyweb/main.go
bskyweb/cmd/bskyweb/server.go
bskyweb/static/robots-disallow-all.txt

NOTE: it is critical to enable the "canonical" flag for our prod deployment before merging/deploying this branch.
Adds two config/envvar flags:
- one to allow swapping in a blank "Disallow: *" robots.txt to prevent crawling (eg, in dev/staging/informal deployments)
- another to only serve some endpoints in the "canonical" deployment (eg, bsky.app)
Normally we might try to detect what "environment" we are in and change these behaviors based on that, but we have kind of a sprawling menagerie of environments, and folks also might be forking this repo for their own use, so made these more granular flags. Open to changing path and doing this the traditional `ENVIRONMENT` variable way though.

bskyweb: add robots disallow and 'canonical' config flags

---

src/screens/StarterPack/StarterPackLandingScreen.tsx
src/screens/StarterPack/StarterPackScreen.tsx
src/screens/StarterPack/Wizard/index.tsx

Easy fix - just use new `Layout` components instead of `CenteredView`
<table>
<tbody>
<tr>
<th>After</th>
</tr>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/0eebb2ed-4a6e-413a-8b37-17836d3b22d9" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/4ae62c0e-3e0d-49b4-9373-2697258cddb1" /></td>
</tr>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/68efdc69-5fff-47a9-bc79-e7db46b3554d" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/a89b1a07-d996-459e-ad65-7202405ed4fd" /></td>
</tr>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/8e1ecdb8-ed3d-4c46-bbc7-a070bc835dcb" /></td>
<td><img width="400" …

Fix starter pack layout

---

src/Navigation.tsx
src/lib/statsig/statsig.tsx
src/logger/index.ts
src/logger/metrics.ts
src/logger/transports/bitdrift.ts
src/logger/transports/sentry.ts
src/logger/types.ts

Adds a `logger.metric()` method for more convenience emission of metrics. By default, this new method sends events to the datalake and _not_ to StatSig. This method also calls all configured logger transports e.g. Bitdrift and relays the same information.
```typescript
logger.metric('router:navigate', {from: <route>})
// also send to StatSig
logger.metric('init', {...}, {statsig: true})
```
This is powered by our existing `logEvent` from StatSig. However, I made a small update there to replace the manual `lake:` prefixing with an additional param:
```typescript
logEvent('lake:router:navigate', {from: <route>})
// becomes
logEvent('router:navigate', {from: <route>}, {lake: true})
```
Notable change here: event types no longer have the explicit `lake:` prefix, but I don't anticipate that …

Logger metrics

---

src/state/messages/events/agent.ts

Fixes #7882
Currently we init log polling using `listConvos?limit=1` and use the `rev` of the most recent convo. however, we have loads of "non-embodied" log events now, so starting the tail from the most recent message can often result in hundreds of logs at startup. Instead, we should just call `getLog` initially with no cursor, and use the cursor it returns.
Look at `getLog` in the network request. The getLog calls at startup should have no logs inside them

Init log using `getLog`

---

.eslintrc.js
bskyembed/.eslintrc
bskyembed/snippet/embed.ts
bskyembed/src/color-mode.ts
bskyembed/src/index.css
bskyembed/src/screens/landing.tsx
bskyembed/src/screens/post.tsx

Supercedes https://github.com/bluesky-social/social-app/pull/7074
- Improves styles
- Changes default theme to `light`
- You can now enforce the color mode to dark or light at the embed code author choices (of course you can choose `system` too).
- Added an interface to the landing page that allows users to select a color mode.
- `data-bluesky-color-mode` attribute is added for embed code (optional, default is `system`)
Fix #7063

enhance(embed): add ability to pin color mode

---

src/components/dialogs/Embed.tsx

Following on from #7186, this adds the option to select a colour mode in-app. Defaults to `system`
<table>
<tbody>
<tr>
<td><img width="400" alt="Screenshot 2025-01-06 at 22 16 57" src="https://github.com/user-attachments/assets/11aa6756-5b5e-4557-b17e-287647b946cb" /></td>
<td><img width="400" alt="Screenshot 2025-01-06 at 22 17 03" src="https://github.com/user-attachments/assets/3f44b835-4817-46da-896f-617425a5c8f9" /></td>
</tr>
</tbody>
</table>
- Confirm snippet matches output from base PR (vibe checking snippet is fine)
- Check my American English spelling is correct

Add dark mode option to in-app embed snippet dialog

---

src/screens/Messages/ChatList.tsx
src/screens/Messages/Inbox.tsx
src/view/com/util/LoadingPlaceholder.tsx

Self-explanatory. Necessary now that we're not prefetching the first page of results in the background. Also used in inbox
<table>
<tr>
<th>iOS</th>
<th>Comparison</th>
<th>Web</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/f432a16b-c541-4586-9c00-a8104f3953a9" width="200" alt="iOS Screenshot 1" /></td>
<td><img src="https://github.com/user-attachments/assets/2d49353d-de94-45b4-873b-3214f2f345bc" width="200" alt="iOS Screenshot 2" /></td>
<td><img src="https://github.com/user-attachments/assets/d7a71bbe-ac0b-4b78-ad4c-ecac6a89c31d" width="400" alt="Web Screenshot" /></td>
</tr>
</table>

Skeletons for chat list

---

src/components/dialogs/Embed.tsx

I noticed a label in the embed dialog isn't marked for translation, this PR does that.
https://github.com/bluesky-social/social-app/blob/a62fe855c3625a1798eae38cca08bc6c1686c863/src/components/dialogs/Embed.tsx#L104

Mark label for translation

---

src/screens/Messages/components/RequestButtons.tsx
src/screens/Settings/AppIconSettings/useAppIconSets.ts
src/screens/StarterPack/Wizard/StepDetails.tsx
src/view/com/composer/videos/SubtitleDialog.tsx
src/view/com/composer/videos/SubtitleFilePicker.tsx
src/view/com/profile/ProfileMenu.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

There are around twenty strings that are currently untranslatable because they are not picked up by Lingui's string extraction script, because the `msg` macro wasn’t used.
Here is a very simple PR that resolves that by adding those calls. To catch them in the future, you can search for `_\(['"`]` in your code editor (with regexp search enabled).

Add missing msg macro calls for i18n

---

src/lib/constants.ts
src/lib/media/video/compress.web.ts
src/view/com/composer/videos/SelectVideoBtn.tsx
src/view/com/composer/videos/pickVideo.ts

Touches several areas:
- Moving constants to `#/lib/constants`
- Bumped to 3 minutes / 100mb
- Set a video max duration on the picker (unclear why we weren't doing that before? doesn't seem to cause issues)
- Upload 2 minute 59 second video from all platforms
- Test >3 minute videos
- Confirm no regressions on 60 second videos

[TOP SECRET] Enable 3 minute videos

---

src/alf/atoms.ts
src/components/KnownFollowers.tsx

Tested iOS, Android, Web
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/f28d1daa-eccd-418d-b21c-1ed212a79e40" width="200" alt="Screenshot 1" /></td>
<td><img src="https://github.com/user-attachments/assets/bc37bc74-01e0-4ffc-a6b8-168f20f6ebfd" width="200" alt="Screenshot 2" /></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/33282d9d-4e6b-4d13-b866-85ec1128e6c8" width="200" alt="Screenshot 3" /></td>
<td><img src="https://github.com/user-attachments/assets/5f6a7569-25de-46b0-bb4d-504bd65d082d" width="200" alt="Screenshot 4" /></td>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/e05f0209-3b5c-4f04-ae75-0e6900c78646" width="200" alt="Screenshot 5" /></td>
<td><img …

Fix text not wrapping in social proof

---

src/view/com/util/post-embeds/VideoEmbedInner/web-controls/utils.tsx

Handling failed autoplay in Safari. If the error is anything other than what we're aware of, let it throw.

Catch thrown error for autoplay in Safari

---

src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/mobile/Autocomplete.tsx

https://github.com/user-attachments/assets/d2838f6c-342d-43d4-bb62-7e0f2fb99c61
https://github.com/user-attachments/assets/74c13342-3187-43c1-a7a1-f109c6a7dc40
Confirm these are working on iOS and Android:
1. Autocomplete list is visible, with and without embeds/images/quotes
2. Tapping anywhere on the sheet focuses the input (open gif menu to blur the input)

Fix mention autocomplete

---

src/screens/Messages/components/MessageInput.tsx

Did not read the docs closely enough. Changing `blurOnSubmit={false}` to the new `submitBehavior` prop for multiline text inputs needs to go to `"newlines"`, not `"submit"`

Fix DMs input not being able to type newlines

---

bskyembed/snippet/embed.ts

Two problems:
1. Color theme was defaulting to system - it should just not add the param if missing
2. String did not match what is passed to embeds
Spot check confirm that `data-bluesky-embed-color-mode` is the right string

Fix color theme for embed

---

bskyembed/src/index.css

This was a rabbit hole...
Iframes were rendering with opaque backgrounds, causing them to look square:
Thanks to [this blog post](https://fvsch.com/transparent-iframes), I learned that if a parent page and a child page have conflicting `color-scheme`s, the browser will give the iframe an appropriate background. We don't want this behaviour, so we need to remove the `color-scheme` from `:root` and only apply it the containing element of the app.
After:
Paste an embed into a codepen, with your OS in dark mode. Observe opaque background. Now, edit `:root` of the iframe content with your dev tools to remove color-scheme and observe the corners fixing themselves

Fix embed iframe transparency by unspecifying color-scheme

---

src/screens/Messages/components/MessagesList.tsx

#7778 accidentally introduced a bug - scrolling up and loading old messages would cause the scroll position to reset back to the bottom. The cause was overly complex conditional logic in rendering the message input / accept buttons accidentally caused the message input to hide whenever message history was loading, causing a scroll.
> Spot the bug!
```tsx
isConvoActive(convoState) &&
!convoState.isFetchingHistory && (
<>
{convoState.items.length === 0 ? (
<>
<ChatEmptyPill />
<MessageInput
onSendMessage={onSendMessage}
hasEmbed={!!embedUri}
setEmbed={setEmbed}
openEmojiPicker={pos =>
setEmojiPickerState({isOpen: true, pos})
}>
<MessageInputEmbed
embedUri={embedUri}
setEmbed={setEmbed}
/>
</MessageInput>
</>
) : convoState.convo.status === 'request' &&
!hasAcceptOverride ? (
<ChatStatusInfo …
```

Clean up logic for showing message input

---

src/lib/media/video/errors.ts
src/view/com/composer/state/video.ts

Following #7916, I think these two strings about the maximum size for videos probably need updating too?

Update `VideoTooLargeError` strings

---

.github/workflows/build-submit-android.yml
.github/workflows/build-submit-ios.yml
.github/workflows/bundle-deploy-eas-update.yml
Dockerfile

Lingui [does not support failing](https://lingui.dev/ref/cli#extract) if there is invalid syntax in the translation files ([callsite here](https://github.com/lingui/js-lingui/blob/main/packages/cli/src/api/compile.ts#L141-L143)). In lieu of multiple patches on the dependencies themselves, I've opted here to output i18n builds to a log file and grepping for known failures. If failures are detected, it'll `exit 1`.
Example failure: https://github.com/bluesky-social/social-app/actions/runs/13726616350/job/38394470053

Add checks for invalid syntax post-i18n builds

---

src/components/moderation/PostHider.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadShowHiddenReplies.tsx

Fixes some line height based cropping
<table>
<tr>
<th>Before 1</th>
<th>After 1</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/1530ea7a-ae62-4be4-8707-b4ea1fa1b5e5" width="400" alt="Before Screenshot 1" /></td>
<td><img src="https://github.com/user-attachments/assets/f320cd3f-f7e4-40af-bcf2-246a0da7a4d9" width="400" alt="After Screenshot 1" /></td>
</tr>
<tr>
<th>Before 2</th>
<th>After 2</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/072f0b1c-4ebe-49bc-9923-ebb6d07c2344" width="400" alt="Before Screenshot 2" /></td>
<td><img src="https://github.com/user-attachments/assets/6dcc1515-992a-430c-b3db-6b07f1f0389d" width="400" alt="After Screenshot 2" /></td>
</tr>
</table>

Fix post thread item hider line height crop

---

.eslintrc.js
package.json
yarn.lock

Adds eslint type import rules - i.e. type imports must be marked as such, preferring the inline style.
Just set to warn, the rule autofixes so we can just let it fix things incrementally
Also set an exception to the unused variable rule, you can now prefix unused vars with `_`. It's also now using the typescript version instead of the base eslint version, so that it's aware of types etc.

Add eslint consistent type import rules

---

src/App.native.tsx
src/App.web.tsx
src/components/ContextMenu/Backdrop.ios.tsx
src/components/ContextMenu/Backdrop.tsx
src/components/ContextMenu/context.tsx
src/components/ContextMenu/index.tsx
src/components/ContextMenu/index.web.tsx
src/components/ContextMenu/types.ts
src/components/Menu/context.tsx
src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/components/dms/ActionsWrapper.tsx
src/components/dms/ActionsWrapper.web.tsx
src/components/dms/MessageContextMenu.tsx
src/components/dms/MessageItemEmbed.tsx

Motivation: add a place to add emoji reactions (will be stacked on top of this PR)
This is a new kind of menu, similar to `Menu` on web (and in fact is just a `Menu` on web). On native, it presents a long press menu where the trigger is highlighted and a compact menu presented beneath. 
Double tap will eventually be used to _just_ show the reaction bar, but for now it also opens the menu.
https://github.com/user-attachments/assets/35ce98d5-d3e9-4b70-95e9-f08a877ed9d6
https://github.com/user-attachments/assets/29347f05-78af-4d18-99a3-02b6ce608779
The trigger has a RNGH gesture detector on it. When the gesture triggers, it measures the size/position of the trigger element, and renders a PNG of the element using `react-native-view-shot`. This image is then portal-ed to root, along with the …

New `ContextMenu` menu type for DM messages

---

src/lib/browser.ts

Using `navigator.maxTouchPoints` to check whether a device is a "touch device" also matches laptops with touch screen support. Checking for [`pointer: coarse`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer#coarse) instead should only detect whether the primary input mechanism is touch (e.g. smartphones and tablets but not laptops with touch screens).
It's not perfect though. No combination of `(any-)pointer` and `(any-)hover` seems to work for detecting when I plug a physical mouse into my Android phone for example. Might have to rely on the `touchstart` event for that.
Checking `pointer: coarse` is better than the current method at least as it does properly distinguish between mobile/tablet and pc, which the current method doesn't.
Resolves #5856 (hover cards and video …

Change touch device detection method

---

src/screens/Search/Explore.tsx
src/screens/Search/modules/ExploreRecommendations.tsx

Disabled, but not deleted (for now)

[Explore] Disable Recommendations module

---

src/components/ContextMenu/context.tsx
src/components/ContextMenu/index.tsx
src/components/ContextMenu/types.ts

Stacked on #8014
If the context menu is opened via a long press, you can now keep your finger down, move it over a menu item, and release to select.
https://github.com/user-attachments/assets/4ca58633-de0c-488b-8fb6-ef90e8b375f0
Test long pressing to select stuff. Ensure other functionality is not impacted
Ensure it works when the menu moves around, ensure hover zone locations are accurate

Allow selecting `ContextMenu` options via press-and-hold

---

src/alf/atoms.ts
src/components/FeedCard.tsx
src/components/ProfileCard.tsx
src/components/ProgressGuide/FollowDialog.tsx
src/components/icons/common.tsx
src/lib/statsig/gates.ts
src/logger/metrics.ts
src/screens/Search/Explore.tsx
src/screens/Search/Shell.tsx
src/screens/Search/components/ModuleHeader.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx
src/state/queries/actor-search.ts

Allows dynamic reordering of modules, depending on the state of the progress guide/feature gate. Suggested feeds are gated, trending/suggest accounts order swaps if the follow-10 progress guide isn't completed yet
<table>
<tr>
<th><10 follows</th>
<th>>10 follows</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/fbb9babe-ad51-40e8-8038-0176c98ca037" width="200" alt="Before Screenshot" /></td>
<td><img src="https://github.com/user-attachments/assets/6089d2d0-113a-44bc-a5fb-427dfa87c060" width="200" alt="After Screenshot" /></td>
</tr>
</table>

[Explore] Dynamic module ordering

---

bskylink/src/routes/redirect.ts

At this point the URI is already decoded and decoding again will alter the uri 
```
let link = req.query.u
```
example  of a link that has `%` encoding... the initial redirect link is properly encoded.
```
curl -vv "https://go.bsky.app/redirect?u=https%3A%2F%2Fsurf.social%2Ffeed%2Fsurf%252Fcustom%252F01jpz5vyjwvw5yaa8bfkha5xn4" 
```
The result is "double decoded", the proper link in this case should be `https://surf.social/feed/surf%2Fcustom%2F01jpz5vyjwvw5yaa8bfkha5xn4`
```
<html><head><meta http-equiv="refresh" content="0; URL='https://surf.social/feed/surf/custom/01jpz5vyjwvw5yaa8bfkha5xn4'" /><style>:root { color-scheme: light dark; }</style></head></html>
```
After changes:
```
curl -s "http://localhost:3000/redirect?u=https%3A%2F%2Fsurf.social%2Ffeed%2Fsurf%252Fcustom%252F01jpz5vyjwv …
```

Remove double decode of URI

---

src/components/FeedInterstitials.tsx

We received a report that this section was not scrollable whatsoever on Android. This appears to fix that, just simply by wrapping the section in an additional `View`.
Additionally, in our prod app on iOS, it's possible to trigger the drawer gesture if you press, wait a sec to being you swipe, and then swipe. Immediate swipes work fine. This additional `View` also appears to fix that 🤔 
I haven't investigated why. Let's verify this works. To test, check out the tip of this branch (the fix), or the commit just prior (failure).
Fixes https://github.com/bluesky-social/social-app/issues/8019

Fix suggested follows scrolling

---

package.json
src/components/dms/EmojiReactionPicker.tsx
src/screens/Messages/components/ChatListItem.tsx
src/state/queries/messages/list-conversations.tsx
yarn.lock

For backwards compatibility, we removed `messageAndReactionView` from the union in `lastMessage` and added a new field `lastReaction`. We now have to compare the sentAt/createdAt dates to decide which one to show.
Also includes a minor android style fix on the reaction palette
Send messages and add/remove reactions in various orders and confirm the chat list is looking as it should
Confirm the log updates work correctly - esp. removing reactions

[Reactions] Get reactions in chat list working again with new lexicon

---

src/screens/Profile/Header/EditProfileDialog.tsx

In response to feedback for [two](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#891) [strings](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#949) on Crowdin, this PR adds plural formatting for the `Display name is too long` and `Description is too long` error messages that can be shown when a user is editing their profile info.
Similar to #7984, #7994 and #7997, only the `other` prop is included as that is the only plural form relevant in the source locale, English. That will also be the only relevant plural form for translations in most other locales. However, adding plural formatting here means we can ensure that the string can be correctly localized by translators in all supported locales.
> [!NOTE]
> **I put this PR together partly using ChatGPT …

Add plural formatting for "too long" error messages when editing profile info

---

src/screens/Signup/StepHandle.tsx

In response to [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#7543), this PR adds plural formatting for the `No longer than {MAX_SERVICE_HANDLE_LENGTH} characters` error message which is shown on signup if the user types in a username longer than the constant (currently 18 characters).
Similar to previous recent PRs from me adding plural formatting, only the `other` prop is included as that is the only plural form relevant in the source locale, English. That will also be the only relevant plural form for translations in most other locales. However, adding plural formatting here means we can ensure that the string can be correctly localized by translators in all supported locales.
> [!NOTE]
> **This PR passes CI but I haven't tested it.**
cc: …

Add plural formatting for handle too long error

---

src/screens/StarterPack/Wizard/State.tsx

In response to [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#3651), this PR adds plural formatting for the `You may only add up to ${STARTER_PACK_MAX_SIZE} profiles` toast which is shown when a user tries to add more than the maximum number of profiles to a starter pack.
Similar to previous recent PRs from me adding plural formatting, only the `other` prop is included as that is the only plural form relevant in the source locale, English. That will also be the only relevant plural form for translations in most other locales. However, adding plural formatting here means we can ensure that the string can be correctly localized by translators in all supported locales.
> [!NOTE]
> **I put this PR together using ChatGPT and it passes CI but I haven't …

Add plural formatting for `STARTER_PACK_MAX_SIZE` toast

---

src/components/forms/HostingProvider.tsx

| Before (#7847) | After |
|-|-|
| ![Simulator Screenshot - iPhone 16 Pro - 2025-03-07 at 20 33 16](https://github.com/user-attachments/assets/7372816c-302f-4dc0-bac8-26ce9262af68) | ![Simulator Screenshot - iPhone 16 Pro - 2025-03-07 at 20 47 54](https://github.com/user-attachments/assets/a4ac24be-ed81-47be-a07b-7db38ed65a01) |
Changes `marginHorizontal` to `margin` again.

Reapply "Modify hosting provider text for better localization"

---

src/view/com/composer/GifAltText.tsx
src/view/com/composer/photos/ImageAltTextDialog.tsx

Following [feedback raised on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#287), this PR adds plural formatting for part of the string shown when alt text will be truncated.
As in #7984, only the `other` prop is included as that is the only plural form relevant in the source locale, English. That will also be the only relevant plural form for translations in most other locales. However, adding plural formatting here means we can ensure that the string can be correctly localized by translators in all supported locales.
> [!NOTE]
> **I put this PR together partly using ChatGPT and it passes CI but I haven't tested it.**
cc: @akerbeltz

Add plural formatting for alt text truncated string

---

src/components/dms/EmojiReactionPicker.tsx

Forgot dark mode had a different bg color when fixing an android bug
Before
After

Fix background color in emoji reactions

---

src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx

In response to [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/7?view=comfortable#675), this PR adds plural formatting for the `accessibilityHint` for the text input in the composer.
Similar to #7984 and #7994, only the `other` prop is included as that is the only plural form relevant in the source locale, English. That will also be the only relevant plural form for translations in most other locales. However, adding plural formatting here means we can ensure that the string can be correctly localized by translators in all supported locales.
Also, I noticed that there were a few untranslatable accessibility strings nearby so I marked those for translation.
I also tweaked two of them to take into account the case where several posts or replies are being published at …

Add plural formatting, translate and tweak some accessibility strings in composer

---

src/state/queries/trending/useGetSuggestedFeedsQuery.ts
src/state/queries/trending/useGetTrendsQuery.ts
src/state/queries/useSuggestedStarterPacksQuery.ts

We need to delay these loads until we have user interests back from the prefs API. This is only a delay on a cold load of this screen. Otherwise, prefs will be already loaded by the time the user lands here. So this is not a significant performance hit.

Wait for preferences before fetching trending data

---

src/screens/Search/Explore.tsx
src/state/queries/explore-feed-previews.tsx

FlatList's sticky header implementation seems to struggle with having multiple sticky items onscreen at once. Removing use of `topBorder` from between feeds, which was only intended to be used at the very top of the Explore page, cuts down on scroll glitchiness significantly.
# Test plan
Compare to main:
- General scroll perf on iOS
- Whether it does the whiteout when fast scrolling
- Whether it gets jumpy when you manually drag the scrollbar
- Layout (I tried to get it looking the same as before)

[Explore] Reduce scroll glitchiness on iOS

---

src/components/ProfileCard.tsx

Profile card skellies was `contrast_50`, whereas all others are `contrast_25`

[Explore] Match placeholder color with other skeletons

---

src/screens/Settings/SettingsInterests.tsx
src/state/queries/trending/useGetSuggestedFeedsQuery.ts

Realized there was a race here between refetching preferences and getting that data back into the subsequent query re-fetches. Since this is very simple data, I think we can just optimistically insert into the query cache and then refetch.
Not terribly worried about remote data getting out of sync since that would require the user to be editing these interests simultaneously on separate devices, and our goal here is to get the user fresh data after they make edits.
And since these queries have `staleTime` set, we need to fully `reset` them, not just invalidate.
Leaving this open bc we need to refetch:

[Explore] Invalidate queries post-interests edit

---

src/screens/Search/Explore.tsx
src/state/queries/explore-feed-previews.tsx

1. Have to use `onItemSeen` instead of `onViewableItemsChanged` for Web support
2. The sticky headers dont seem to get surfaced on mobile by the viewable items API, so just put the feed info into the individual posts and watched for them instead

Fix the 'seen' metric in explore

---

src/screens/Settings/SettingsInterests.tsx

Supersedes #8136
As a follow-up to #8114, this PR updates the copy in two toasts to align them with the `Your interests` language used in other strings:
`Content preferences updated!`
⬇️
`Your interests have been updated!`
`Failed to save content prefefences.`
⬇️
`Failed to save your interests.`

Align copy in `Your interests` toasts

---

src/screens/Search/Explore.tsx

In general, the approach I'm taking here is to prioritize responsiveness over preventing blank sections. At a reasonable scrolling speed, I'm getting hardly any blank sections, and scrolling does not glitch.
- `maxToRenderPerBatch` lowered this to prioritize responsiveness
- `updateCellsBatchingPeriod` with a lower `maxToRenderPerBatch`, halving this value seems to make renders snappier
- `windowSize` dropped this to 5 above, 5 below, with one in the middle (the active one), seemed to help with blank screens
- `onEndReachedThreshold` doubled this — with the smaller values above, my intention here is to have the data ready once the `List` renders those components to avoid the loading state rendering and flashing
- `initialNumToRender` the hook we have is designed for posts — this screen …

[Explore] Tweak performance settings on Android

---

package.json
src/screens/Search/Explore.tsx
src/screens/Search/modules/ExploreSuggestedAccounts.tsx
src/screens/Search/util/useSuggestedUsers.ts
src/state/queries/actor-search.ts
src/state/queries/explore-feed-previews.tsx
src/state/queries/feed.ts
src/state/queries/trending/useGetSuggestedFeedsQuery.ts
src/state/queries/trending/useGetSuggestedUsersQuery.ts
src/state/queries/useSuggestedStarterPacksQuery.ts
yarn.lock

Unfortunately our facilities for powering trends and suggestions for non-English-understanding users are not ready yet. This PR aims to provide at least some utility to these users, as opposed to the English-focused featureset of the existing Explore page, as well as the new one.
To that end, this PR disables all modules except the "Suggested Accounts" module. This module then attempts to use the translation of the selected interest (powered by the "App Language" setting) as the search query for user results.
We will work to improve this in the future.

[Explore] Reduced experience

---

src/screens/Profile/Sections/Labels.tsx

I haven't determined _when_ this started breaking, but currently scrolling on the labels section of a labeller profile is completely broken on Android. It appears to be due to a `flex:1` on the containing element
Test scrolling the label section on _all_ platforms. Test a labeller with a lot of labels, like bsky mod service, and one with few, like kiki-bouba. Confirm scrolling works on all of them

Fix labels section not scrolling at all on Android

---

src/components/Layout/index.tsx
src/screens/Profile/Sections/Feed.tsx
src/screens/Profile/Sections/Labels.tsx

Scrolling was broken in the header primarily because I forgot to forwardRef `Layout.Content`. However, the reason it was inconsistent even before I broke it was due to a race condition - it was conditionally rendering the scrollview, but was getting the tag in an effect in the parent component, which obviously failed half the time because it would run while showing the spinner instead of the scrollview.
My initial fix was to move the useEffect down into the child component, but I noticed the loading/error states were overlapped by the header, so instead I moved the scrollview up to the parent and wrapped all three possible children, so now all of them are scrollable and aren't overlapped
Test scrolling in header
Confirm you can now see the loading spinner
Induce the error state and …

Fix labeler header scroll and loading/error states

---

src/screens/Messages/ChatList.tsx

I don't think the sliders icon is obvious enough - a lot of people are missing it. Hopefully this is clearer? Along with consistency with the notifs page

Change chat settings icon to a gear icon

---

src/components/forms/HostingProvider.tsx

Inputs used to be taller on Android for some reason. No longer, so let's make the hosting provider button consistent
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/a2bab8f3-60a9-4bd6-906b-4dccf83b1fcc" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/ff0cdda6-fac0-4405-9d12-86feec0de12f" /></td>
</tr>
</tbody>
</table>

Fix Hosting Provider button height on Android

---

src/screens/Settings/Settings.tsx

Only thing missing in this refactor is a specific style for invalid handles, but that's just a "pill" shape that kinda mimics the "Follows" you pill, and I don't think we're losing anything by omitting that here.
No visual change otherwise, on any platform.

Don't re-use profile-specific components in Settings

---

src/state/session/additional-moderation-authorities.ts

Fixes #8206
As @imax9000 points out in that issue, the [ISO-3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code for the United Kingdom is `GB` rather than `UK` (although we only use `.uk` for domain names...)
It might also be a good idea to rename the [labeler account](https://bsky.app/profile/did:plc:gvkp7euswjjrctjmqwhhfzif) handle, to avoid any potential for confusion.

Change `UK` country code to `GB` in additional-moderation-authorities.ts

---

src/components/verification/VerifierDialog.tsx

Decided to keep the outer one, since the inner one overlaps with the content

Remove double close button

---

src/view/com/composer/ComposerReplyTo.tsx

Follow up from #8226 
<table>
<thead>
<tr>
<th>Pre verification change</th>
<th>Currently on `main`</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="600" src="https://github.com/user-attachments/assets/f36805f8-b8af-4f61-b330-eb9d65afa8cb" /></td>
<td><img width="600" src="https://github.com/user-attachments/assets/0b7fc7c1-0d82-4eb9-9507-79ab58337a7c" /></td>
<td><img width="600" src="https://github.com/user-attachments/assets/5695d1d6-fd16-42c4-82b1-632a5a163aa1" /></td>
</tr>
</tbody>
</table>

Fix composer reply line height

---

src/screens/Settings/Settings.tsx

This improves the rendering so that long display names don't overflow the container on web, but does not resolve why on Android, _some_ display names are truncated more than necessary.
No change to verification checks if they exist.

Improve display name in Settings

---

modules/bottom-sheet/ios/SheetView.swift
modules/bottom-sheet/src/BottomSheetNativeComponent.tsx
modules/bottom-sheet/src/BottomSheetNativeComponent.web.tsx

Shout out to Claude who spotted this error state
This fixes an issue on iOS where the dialogs would not respond to content size changes - as it turns out, this was happening every time on the _second_ render.
The issue occurred because the initial detent identifier check blocked updates when identifiers didn't match, which always happened on first meaningful render. Now we properly allow updates during this initial transition phase while maintaining existing behaviour for subsequent updates.
https://github.com/user-attachments/assets/e7709865-bc4c-4c28-af2d-3b6da4952b02
https://github.com/user-attachments/assets/97b98c3f-a450-4822-b5e2-14381a6ff930
Test sheets where the content size changes - good ones are the Starter Pack share dialog, and the report post dialog

Fix first sheet height change not registering (iOS)

---

src/Navigation.tsx
src/components/dialogs/VerifyEmailDialog.tsx
src/screens/Settings/Settings.tsx

We already have a refreshed verify email dialog, but we weren't using it for the daily reminder. This fixes that.
- Uses the new dialog
- Adds an extra step to the dialog so it can replace the old one
<table>
<thead>
<tr>
<th>iOS</th>
<th>Web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/77417a32-fc07-495f-b687-c1f247d95c63" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/9d46d91f-3cba-4d5b-97f6-370a2599dca7" /></td>
</tr>
</tbody>
</table>
Use an account with an unverified email. I added a button to the bottom of settings to unsnooze the reminder

Use ALF verify email dialog for reminder

---

src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx

Muted Accounts and Blocked Accounts are two very unloved screens. This cleans them up a little - info section at the top now scrolls with the content, and looks nicer. Also using `List` and `ListFooter`
<table>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/ec47fa83-a636-4bdd-b8cc-e36f2006de63" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/80fe280d-bd86-49ba-ac1d-d439385ac2d8" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/5a14e4eb-5d67-447e-987c-a8bdb4c1228d" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/4d21ff67-7c7b-4ec1-aea8-0f16242cadef" /></td>
</tr>
</tbody>
</table>
Test both screens. Confirm empty state works.

Clean up moderation screens

---

src/lib/media/manip.ts
src/lib/media/manip.web.ts
src/state/gallery.ts

I've been waiting for https://github.com/bluesky-social/social-app/pull/6137 to get merged for a while, but it seems to have stagnated after the contributor was asked to apply the same optimization to `src/state/gallery` back in November.
This PR simply implements the same binary search optimization to the compressImage method in gallery.ts as well.

Optimize compressImage method to also use binary search

---

src/state/gallery.ts

They get bulk deleted when the composer closes, so it just slows down the loop

Don't await deleting temp files

---

src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/pager/PagerWithHeader.tsx

**Stacked on #8295**
The culprit of the slow perf on the profile pages was this mechanism for keeping the scrollviews in sync:
This syncs the other scrollviews in the pager every 80ms while the header is visible.
It seems like Reanimated's `scrollTo` is much much slower on Fabric. On Paper, we were able to do this 6x every 80ms. Now, it absolutely tanks performance.
This fixes it by changing the approach for keeping the scrollviews in sync. Rather than polling, we instead just sync on demand - either when the pager beings dragging, or when a tab is pressed
https://github.com/user-attachments/assets/e9c39c55-b687-4bc0-82c7-a831b186edb3
https://github.com/user-attachments/assets/0c9507b6-7011-49e9-8f43-db3f0a71e1be
- Test perf on new arch.
- Confirm scrollviews are still synced properly
You …

[new arch] Fix profile perf

---

src/components/StarterPack/ProfileStarterPacks.tsx
src/components/dms/MessageProfileButton.tsx
src/components/dms/dialogs/NewChatDialog.tsx
src/lib/hooks/useIntentHandler.ts
src/lib/hooks/useOpenComposer.tsx
src/lib/hooks/useRequireEmailVerification.tsx
src/screens/Messages/ChatList.tsx
src/screens/Messages/Conversation.tsx
src/screens/Messages/components/RequestButtons.tsx
src/screens/Messages/components/RequestListItem.tsx
src/screens/Profile/ProfileFeed/index.tsx
src/screens/VideoFeed/index.tsx
src/state/shell/composer/index.tsx
src/state/shell/composer/useComposerKeyboardShortcut.tsx
src/state/shell/index.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/videos/SelectVideoBtn.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/PostFeedItem.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/screens/Feeds.tsx
src/view/screens/Lists.tsx
src/view/screens/ModerationModlists.tsx
src/view/screens/Notifications.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileList.tsx
src/view/shell/desktop/LeftNav.tsx

Adds a new hook similar to `useRequireAuth` called `useRequireEmailVerification` which will similarly block the action until email verification has been completed. This hook uses the new `EmailDialog` added in #8296.
```ts
import {useRequireEmailVerification} from '#/lib/hooks/useRequireEmailVerification'
const requireEmailVerification = useRequireEmailVerification()
// The resulting callback inherits the types so it can be used pretty much anywhere.
const onPress = requireEmailVerification((e: GestureResponderEvent) => {...})
```
In this PR I've used this hook to wrap everything that we currently have gated using the existing `VerifyEmailDialog`, with a couple exceptions:
- for the composer, I opted to gate all calls to `openComposer` instead of doing it implicitly when the composer …

[APP-1158] Gate features by email verification state

---

src/view/com/util/forms/PostDropdownBtnMenuItems.tsx

Opens the topic misclassification report form. Internal only, and the form is private

Add internal discover debug topic misclassification report button

---

modules/bottom-sheet/ios/SheetView.swift

We should be dismissing sheets from the main thread, however right now we are not!
- use an account with an unverified email
-  send yourself an email verification link
- open any dialog e.g. post dropdown menu
- click on link in email
- app will not crash

fix crash when closing open dialogs

---

src/components/StarterPack/ShareDialog.tsx
src/lib/media/manip.ts
src/view/com/lightbox/Lightbox.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1360
Saves images on android to a "Bluesky" folder, rather than DCIM.
Save 2 or more images. The first image will create the album, the second will be placed directly into the album.
Confirm there are no annoying permission prompts when saving.
---
Works fine, except it pops up a permission prompt every time, which is probably a deal-breaker. ~~Looking into workarounds.~~ ~~Waiting on upstream fix 🎉~~ ~~Need these PRs for `expo-media-library` to land (will be SDK-53)~~ Lets goooo:
- https://github.com/expo/expo/pull/35686
- https://github.com/expo/expo/pull/35692

[Android] Save photos to "Bluesky" folder

---

src/components/dialogs/nuxs/index.tsx
src/components/dialogs/nuxs/utils.ts

Adds a reusable util to gate NUXs to accounts older than `n` days old.

Don't show NUXs to brand new users

---

src/components/ProfileHoverCard/index.web.tsx

There were a couple issues here. One was it was dependant on the intrinsic size of the content, but the spinner is obviously much smaller - thus the offset was wrong once the content loaded. the other is that the live version max size was much too big.
Solution is to just set a fixed size.
# Before
https://github.com/user-attachments/assets/45d6b7ef-0dd9-4cee-88dd-de18577b0821
https://github.com/user-attachments/assets/93c0d106-c589-4bf0-9332-5d806d9a6066

Fix hover card width

---

.github/workflows/build-and-push-bskyweb-aws.yaml
.github/workflows/build-submit-android.yml
.github/workflows/build-submit-ios.yml
.github/workflows/bundle-deploy-eas-update.yml
Dockerfile
src/logger/sentry/setup/index.ts

Disables Sentry in dev to prevent accidental reporting by contributors who fork this repo, and moves the Sentry DSN into an environment variable to better avoid abuse or accidental misuse.
A new DSN will need to be populated here in GitHub for CI.

Move SENTRY_DSN to secrets

---

src/components/PostControls/index.tsx
src/logger/metrics.ts
src/screens/Profile/components/ProfileFeedHeader.tsx
src/screens/Search/modules/ExploreTrendingVideos.tsx
src/screens/VideoFeed/index.tsx
src/state/queries/post.ts

Adding some feed metrics for 
- Post likes (feed context)
- Post reposts (feed context)
- Feed pins/unpins/saves/unsaves (feed uri)
Do the events above, and watch to see what gets sent in events.

add metrics

---

src/components/FeedCard.tsx
src/logger/metrics.ts
src/screens/Search/Explore.tsx
src/state/queries/trending/useGetSuggestedFeedsQuery.ts

This ended up a little chonkier than expected, so here's what all we're doing:
- Removing the "new user" special ordering. We didn't see that change much
- Moving the "Discover Feeds" module directly under the "Trending" module for all users
- Bumping the number of feeds shown here to 6 from 3 _if they are eligible_
- Switching to use the unspecced `getSuggestedFeeds` _if they are eligible_
- Recording exposures to each various feed in the list
- Recording presses into individual feeds from the list

tweak ordering of explore components

---

src/components/PostControls/ShareMenu/ShareMenuItems.tsx

`Clipboard.setUrlAsync` is iOS only whoops

Fix copy url on Android

---

src/components/PostControls/PostControlButton.tsx
src/lib/custom-animations/CountWheel.tsx
src/lib/custom-animations/CountWheel.web.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/b48e4863-904f-4a8c-bbd6-00ec1a2eb099" width="400" alt="Screenshot 1" /></td>
<td><img src="https://github.com/user-attachments/assets/e07d3d57-744f-4cb6-87b5-a8a51a6a8fc9" width="400" alt="Screenshot 2" /></td>
</tr>
</table>

Reduce post control font size

---

src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/components/PostControls/PostMenu/PostMenuItems.tsx
src/components/PostControls/ShareMenu/ShareMenuItems.tsx
src/components/PostControls/ShareMenu/ShareMenuItems.web.tsx

No longer triggers the annoying prompt - just shows an inline notice instead
<table>
<tr>
<th>iOS</th>
<th>Android</th>
<th>Web</th>
</tr>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/c8b75161-70a5-4b9b-8183-2a6461aa6bdb" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/30a3502e-918c-4224-8091-51fadc92305c" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/54752ecc-e403-4b4c-b61e-ec165a1f2cbe" /></td>
</tr>
</table>
Also fixed PWI post menu - currently there's zero items that show up there since we moved everything to the share menu, so it looks broken. just added a simple item that triggers the sign in prompt
<table><tr>
<th>After</th>
</tr>
<tr>
<td><img width="300" …

Replace "Note about sharing" prompt with an inline hint

---

src/screens/Login/SetNewPasswordForm.tsx

Makes “Reset code”, “New password” on the password reset page translatable.

Add missing <Trans> to SetNewPasswordForm.tsx

---

src/App.native.tsx
src/App.web.tsx
src/logger/types.ts
src/state/feed-feedback.tsx
src/state/unstable-post-source.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/PostFeedItem.tsx

In testing this with v2, I realized that we weren't tracking reply interactions originating from the reply composer list item itself, only the reply button in `PostControls`. I started implementing that and quickly realized that consuming the post source data in the outer component won't work, because the component can re-render and evacuate the previously cached post source value from state. Also, from the outer `PostThread` component, the URI generated from the URL path params is going to contain a handle (if we nav to a thread via any of our flows e.g. feeds).
So I set about making the post source cache stable between renders, and keying it off the handle.
These commits are in rough order, and essentially what they contain is:
- some debug logs which only appear if you have your …

Post source handling updates

---

src/view/com/util/post-embeds/VideoEmbedInner/VideoEmbedInnerWeb.tsx
src/view/com/util/post-embeds/VideoEmbedInner/web-controls/VideoControls.tsx

There's a border around the video when in fullscreen. Whoops. We can simply move it outside of the div that gets fullscreened

Video - remove `MediaInsetBorder` when fullscreen

---

src/view/com/composer/Composer.tsx

There's a bug introduced when we upgrade RN where switching between apps with the post composer open would cause the composer to be scrolled to a weird position when focusing the app. Usually it would immediately fix itself but not always.
This seems to be caused by the keyboard being open, so let's just close the keyboard on background
https://github.com/user-attachments/assets/09f9decc-58cd-400a-b4ec-89134ee80442
https://github.com/user-attachments/assets/e773e289-6bc3-46c0-8f0c-c0a63d425e1c

Fix composer scroll position when switching apps

---

src/state/cache/post-shadow.ts
src/state/queries/profile.ts

This PR #8463  results in muted people having all their posts appearing as deleted. Needs a different approach

Revert "Instant Feed Update on Mute or Moderation Action"

---

src/logger/sentry/setup/index.ts

These auto stack traces are causing the same issue to be reported separately instead of as a group. Disabling this does not affect our error handling otherwise.

Disable default stack traces that are causing issues

---

.husky/pre-commit

Run `prettier` _after_ `eslint --fix` by forcing `lint-staged` to run linearly.

Run lint-staged without concurrency

---

src/screens/Search/Explore.tsx

The PTR mechanism has a Promise.all, but it accidentally awaits each of the promises, so it runs sequentially. Removing the awaits runs them in parallel

[Explore] Run refresh queries in parallel

---

src/screens/Settings/InterestsSettings.tsx

```diff
await Promise.all([
-          await qc.resetQueries({
-            queryKey: createSuggestedStarterPacksQueryKey(),
-          }),
-          await qc.resetQueries({queryKey: createGetSuggestedFeedsQueryKey()}),
-          await qc.resetQueries({
-            queryKey: createGetSuggestedUsersQueryKey({}),
-          }),
+          qc.resetQueries({queryKey: createSuggestedStarterPacksQueryKey()}),
+          qc.resetQueries({queryKey: createGetSuggestedFeedsQueryKey()}),
+          qc.resetQueries({queryKey: createGetSuggestedUsersQueryKey({})}),
])
```

Fix other case of `Promise.all` misuse

---

src/components/Link.tsx
src/lib/hooks/useNavigationDeduped.ts
src/lib/strings/url-helpers.ts

Fix #1384, #4749
Part of it is stopping `convertBskyAppUrlIfNeeded` from stripping the search param. this is all that's needed for web
However, for native, the search screen is only available in the search tab. so we need to add some custom logic to the link component to support switching to a child route in a different tab, which is used if `screen` is not in `routeNames`.
I opted to only add this to the new link component since that's what we use within posts.
Test web + native. I can't think of any scenario where this code would run other than a link to another tab? so links to `/notifications` or `/chat` should also hit it, but that should be fine.
https://bsky.app/profile/samuel.bsky.team/post/3lruzfzrios2u

Fix linking to specific search results

---

src/screens/PostThread/index.tsx

Since #8477 is a little stuck, there's a simpler heuristic for the footer in some cases - if there's no parents, the anchor post won't get pushed down so we don't need to prop it up.
Will help with #8543, which causes *even more* footer height
# Test plan
Test with different amounts of parents/children

Add simple heuristic for reducing footer height in thread

---

package.json
yarn.lock

#8295 broke the global back swipe gesture on profile pagerviews, because `react-native-pager-view` was changed from `6.7.1` to `^6.7.1`, which resolved to `6.8.1`. `6.8.1` includes https://github.com/callstack/react-native-pager-view/pull/933 which appears to be the culprit. Pinning the version to exactly `6.8.0` appears to fix it 
Upstream issue: https://github.com/callstack/react-native-pager-view/issues/1006

Fix pager back gesture

---

src/lib/constants.ts
src/lib/notifications/notifications.ts
src/platform/detection.ts

Fixes a small issue of the push token registration endpoint being called 2x, as well as clarifies the token update callback handling. I refactored this into hooks in anticipation of upcoming needs, and left a ton of comments to make it even more clear what's going on in here.
Assuming you allow notifications (if you don't, then obviously the token won't be registered), these are the flows that can test call cases. You'll need to set your `LOG_LEVEL=debug` and `LOG_DEBUG=notifications` before running the build process (no need to prebuild).

Notifications registration

---

src/screens/Profile/Sections/Labels.tsx
src/state/queries/labeler.ts

The labeller profile list of labels is a ScrollView, rather than a FlatList. [Some labellers](https://bsky.app/profile/sonasky.app) define thousands of labels, which is problematic.
This PR switches it to a FlatList. This should see an increase in perf, especially for labelers with a lot of label definitions. This can be seen in the time it takes in initial load, but on android this'll almost certainly improve scroll perf quite significantly.
https://github.com/user-attachments/assets/8a4820d8-cbb9-4f36-8c1b-6343febe6541
https://github.com/user-attachments/assets/2212ae93-6cc4-45b0-881c-12b94f2808de
Ensure all functionality is the same, including loading and error states.

Virtualise labeler list

---

src/lib/api/index.ts
src/view/com/composer/videos/pickVideo.ts

Fix https://github.com/bluesky-social/social-app/issues/5753
Sometimes the video picker appears to return a width or height of 0. This breaks lexicon validation, so it's unable to post - better to just leave the aspect ratio off instead and just log an error

Fix video aspect ratio error - "Record/embed/aspectRatio/width cannot be less than 1"

---

src/components/WhoCanReply.tsx

Currently the dialog has a few issues
- No close button (especially weird on web)
- You can swipe up on native
- It can be super small on native  
Fixed by adding a close button
<table>
<thead>
<tr>
<th>Native</th>
<th>Web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/ea82d39d-a157-439c-a8cf-63dd280b4060" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/6526d6a2-a18b-41f6-a986-3877f049caf8" /></td>
</tr>
</tbody>
</table>
# After
<table>
<thead>
<tr>
<th>Native</th>
<th>Native</th>
<th>Web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="200" src="https://github.com/user-attachments/assets/1f300494-7a6d-4353-8bc6-8bb167479428" /></td>
<td><img width="200" …

Tweak Who can reply dialog

---

src/view/com/modals/lang-settings/ContentLanguagesSettings.tsx

As [mentioned on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-gd/9?view=comfortable#1629), the current string shown in the **Content Languages** modal could perhaps be a little clearer, as even on web they are toggle switches rather than checkboxes:
This PR proposes tweaking it from `unchecked` ➡️ `unselected`
cc: @akerbeltz

Tweak string in Content Languages modal

---

src/components/PostControls/index.tsx
src/screens/PostThread/components/ThreadItemTreePost.tsx
src/view/com/posts/PostFeedItem.tsx

- Added top padding to PostControls
- Reduced padding between PostMeta and content in treeview by only adding gap to line, not whole row (avi was pushing content down)
- Line up content with display name (6px gap between avi and name)
- Reduce top padding of feed posts (currently 12px, which is far bigger than the other sides. changed to 10px)
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/c9493a2a-735b-4a1f-8358-91a708f4d095" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/58eb0d29-b9c8-45af-81d7-011b73e1a6fb" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" …

Improve post spacing

---

src/components/Divider.tsx
src/components/Post/Embed/FeedEmbed.tsx
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/feeds/MissingFeed.tsx
src/view/com/util/LoadingPlaceholder.tsx

Currently we just show a perma-loading state for dead feeds, which sucks. This adds a little info popup so you can actually find out what the feed is
"click for information" is a bit awkward but since it's an edge case it's probably best to be clear and awkward rather than stylish and obtuse
<table>
<thead>
<tr>
<th>Web</th>
<th>Web</th>
<th>Native</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/fe749062-ba63-45bc-acf5-cae7e4d49ab5" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/17c3754f-239f-4bf9-9cfe-0b2d0b7f6c99" /></td>
<td><img width="200" src="https://github.com/user-attachments/assets/705eba95-3cd0-44f3-ba40-6f5a429785fd" /></td>
</tr>
</tbody>
</table>
Also includes handling of deleted lists

Better dead feed handling

---

src/App.native.tsx
src/Navigation.tsx
src/lib/hooks/useNotificationHandler.ts
src/lib/notifications/notifications.ts
src/lib/notifications/util.ts
src/lib/routes/links.ts
src/logger/metrics.ts

Rather than using `getInitialURL`, we actually want to read the latest notification (i.e. the notification that caused the app to open) in `onReady`, then push to it. `getInitialURL` meant that you couldn't swipe to go back to home, because it becomes the root screen of the stack.
This _should_ also fix notification handling (for both cold start and backgrounded notifs) on android, as apparently the shape of the object changed at some point. Let's get it into prod and verify - no harm if it doesn't work since the current approach doesn't work either lol
This also now handles all types of notification properly!
- like, repost, *-via-repost: takes you to the subject post
- reply, mention, quote, activity notif: takes to the post
- follow, join via starterpack: takes you to the profile
- …

Handle notifications on first load

---

src/components/WhoCanReply.tsx

The globe icon for "everyone" was determined incorrectly - was checking for an empty array rather than `{ type: 'everyone' }`

Fix who can reply icon for "everyone can reply"

---

src/components/Link.tsx
src/components/StarterPack/StarterPackCard.tsx
src/lib/hooks/useNavigationDeduped.ts
src/view/com/util/Link.tsx
src/view/shell/desktop/LeftNav.tsx

Fixes https://github.com/bluesky-social/social-app/issues/8632
React Navigation v7 includes this change:
https://reactnavigation.org/docs/upgrading-from-6.x#the-navigate-method-no-longer-goes-back-use-popto-instead
> The `navigate` method no longer goes back, use `popTo` instead
Since our web version is a giant stack navigator, this means that switching away from a tab and back used to `pop` back to the previous screen. This awkwardly means you lose the ability to use the back button, since technically it was a back action. However, this correctly reused the same screen that you're going back to, so it doesn't need to render the screen again from scratch.
However, since the new version _always pushes_, switching to and from tabs would add a new screen _every single time_. Not only does …

Fix perf issue on web - restore pop behaviour to tabs

---

src/Navigation.tsx

Ensures that you can go back to the chat list screen if opening the app from a chat message push notif
Hailey had figured this all out before - it now reuses the logic from here: https://github.com/bluesky-social/social-app/blob/main/src/lib/hooks/useNotificationHandler.ts#L235-L240
We don't need the rest of the handling there btw because that's only if you're already on the messages tab - obviously not the case at startup

Use push to convo mechanism in startup notification handling

---

src/screens/Profile/Header/Metrics.tsx

The intention is to expose the precise number of followers somewhere. Currently I have "1.1K", but until that drops to "1K" or rises to "1.2K", i'll have no idea where in that hundred-range the number falls.
I'm sure I'll need to do something with tests, and maybe still format the count in a less-approximate way - please give me some pointers since I'm very unfamiliar with the codebase.
I'd also like to expand this PR to show the full count on the `/follows` and `/followers` pages so it's easily visible on mobile, but i thought i'd start here :-)

show precise count in label/hover text

---

src/components/ageAssurance/AgeAssuranceRedirectDialog.tsx
src/state/ageAssurance/index.tsx

Refetch user's status on window focus if (1) they've initiated a flow before and (2) their `status = pending`.
Also adds a success state to the polling dialog they see after a successful deeplink. Before the state updates and closing dialog was kinda janky. This updates state in the bg and lets the user close the dialog.

Age assurance tweaks

---

src/lib/api/resolve.ts
src/lib/link-meta/link-meta.ts

Allows embed card to work for their shortlinks
Post https://on.soundcloud.com/AgZAAwLT3iRjNrhqp3 and confirm the player now appears

Follow redirects for soundcloud shortlinks

---

src/view/com/composer/state/video.ts

The error message from the backend if the file is somehow too large is always `file size (100000001 bytes) is larger than the maximum allowed size (100000000 bytes)`, so we should show a nicer message

Nicer error message for backend video too large error

---

src/components/PostControls/RepostButton.web.tsx

This PR adds `action` context for translators for the `Repost` strings in `RepostButton.web.tsx`, to align them with the corresponding strings in `RepostButton.tsx`:
https://github.com/bluesky-social/social-app/blob/bc42d26bc519a26bb94bddc21fa1001b74afea25/src/components/PostControls/RepostButton.tsx#L141
https://github.com/bluesky-social/social-app/blob/bc42d26bc519a26bb94bddc21fa1001b74afea25/src/components/PostControls/RepostButton.tsx#L152

Add `action` context for `Repost` string in RepostButton.web.tsx

---

bskyembed/src/components/post.tsx

Fixes #8678
This PR implements the fix suggested in that issue by @PaulCapron. It passes CI but I haven't tested it.

Use correct URLs for hashtag pages in embed code

---

src/components/VideoPostCard.tsx

Summary
---
Hide the like count on trending videos. Implemented as a hardcoded feature flag so that we can toggle it back on if desired.
Based on feedback and discussion in the linear ticket, I've included some minor adjustments to hide the gradient (where the like count was) and update the profile picture to be slightly bigger and have a small dropshadow.
Linear: https://linear.app/blueskyweb/issue/APP-965/remove-like-count-from-trending-videos
Copilot Generated
---
This pull request introduces a minor change to the `CompactVideoPostCard` component in the `src/components/VideoPostCard.tsx` file. The change involves adding a `showLikeCount` flag to control whether the like count is displayed.
* Added a new constant, `showLikeCount`, initialized to `false`, to determine whether the like …

feat(ui): remove like count from trending videos

---

src/lib/statsig/statsig.tsx

`nativeApplicationVersion` from `expo-application` only works on native. Importing `package.json` should work on all platforms afaik.

Include app version in metrics

---

src/components/dialogs/EmailDialog/data/useAccountEmailState.ts
src/components/dialogs/EmailDialog/data/useConfirmEmail.ts
src/components/dialogs/EmailDialog/data/useManageEmail2FA.ts
src/lib/api/feed/home.ts
src/state/session/index.tsx
src/state/session/reducer.ts
src/state/session/types.ts

Alternative fix to https://github.com/bluesky-social/social-app/pull/8667 - fixes https://github.com/bluesky-social/social-app/issues/8493
`resumeSession` updates root session state in the app via `persistSessionHandler`. While this worked for the purposes of the email dialog, it's not ideal, because if `resumeSession` fails with a network error or other issue, our handling of `persistSessionHandler` will bump the user back out to log in again.
Admittedly, this fallback is poor UX. But it's not new, it has existed for over a year. And by re-running `resumeSession` on window focus via RQ, the frequency that users hit this fallback has increased recently.
This PR replaces `resumeSession` with a new method `partialRefreshSession` which does almost the same thing: calls `getSession` and …

Replace `resumeSession` with `getSession` in the email check

---

src/lib/custom-animations/GestureActionView.tsx

For example, this PR makes it so that if the user swipes right on a GestureActionView with no right actions, GestureActionView will ignore the swipe. This allows the swipe to bubble up and be handled by a parent instead of being swallowed.

[APP-1291] prevent GestureActionView from hijacking swipe in a direction which no actions are specified

---

src/screens/Messages/ChatList.tsx

This PR addresses this [linear ticket](https://linear.app/blueskyweb/issue/APP-1317/chat-request-ui-is-confusing) about hiding `chat requests` when there are no messages in the inbox. This implementation updates the logic to only render the "Inbox" request types if at least 1 request is present.
Before:
After:

[APP-1317] update: chat request ui to hide chat requests when there are no messages

---

src/components/FeedInterstitials.tsx
src/components/ProfileCard.tsx

Summary
---
- interstitial padding top `16 -> 12`
- replace right side icon (follow person) to be See all
- text Suggested for you color `contrast_medium -> text-default`
- small drop shadow on profile card
- profile card padding all sides `16 -> 12`
- profile card border radius `10 -> 16`
- vertical flex for profile card elements
- remove profile handle
- profile avatar size `40 -> 88`
- profile description text size `sm -> xs`
- replace round follow icon button with standard follow button pill 
Linear: https://linear.app/blueskyweb/issue/APP-1330/new-design-for-suggested-for-you-interstitial
Pictures
---
Old web
New web
Old mobile
New mobile
Final card on mobile (never on web)

feat: new design for "Suggested for you" interstitial

---

src/view/com/util/Link.tsx

In #5967, I made a change to the link component to fix some suspicious-looking prop mutation of `dataSet`. However, I neglected to notice that props gets spread into two possible components, so if a link has `noFeedback` it wouldn't get passed the `dataSet`. Easy fix - just need to pass the prop.
This fixes feedContext not showing in Discover
Also while I'm here, the useMemo is completely useless since dataSet is almost certainly not stable. Replaced with a simple ternary.

Fix dataSet for noFeedback links

---

src/view/com/util/Toast.style.tsx
src/view/com/util/Toast.tsx
src/view/com/util/Toast.web.tsx

A bad typecast hid the fact that old usages of `Toast.show()` that used the fontawesome icons were not actually valid and broke at runtime. This PR:
1. Splits the type into `ToastType` and `LegacyToastType`, allowing both
2. Maps legacy types into the new ones
3. Removes the bad typecasts, making it typesafe
4. Shows deprecation warnings for usages of the legacy types

Convert old toast types to new ones, mark as deprecated

---

src/components/Button.tsx
src/screens/Settings/components/SettingsList.tsx

The code comment kinda says it all. This stray `color` prop might be applying colors to its children, and we really should avoid that level of inheritance as much as possible. Really, the use of `Button` and `ButtonText` in `SettingsList` components isn't ideal either, since `SettingsList` styles here are completely unrelated from our normal buttons, but there's no particular harm atm either.
No visual changes here afaict.

Make proper extension of `Button` more clearly defined

---

src/components/Toast/index.web.tsx

@nilaallj raised the following issue [on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-sv/7#8734):
> This is an accessibility label, right? I’m not sure if “toast” is a good term to use outside of a developer context. A blind user might not understand what is being dismissed here. Wouldn’t it be better to use something like “message” and maybe “alert” for important toasts?
I'm not too familiar with accessibility guidelines and practices, so I decided to ask Claude, and he did [some helpful research](https://claude.ai/share/99264d01-077f-4ee4-ab28-b2a795e76348).
Given what Claude found, I think referring to a toast as an `alert` might be the most user-friendly option. While either `message` or `notification` could work, given that we already use those words extensively in the UI (and …

Tweak accessibility label

---

package.json
src/components/Post/Embed/VideoEmbed/VideoEmbedInner/VideoEmbedInnerNative.tsx
src/components/Post/Embed/VideoEmbed/index.tsx
yarn.lock

https://github.com/bluesky-social/social-app/pull/8754 caused a background to be added to the overlay button. Simply adding `a.bg_transparent` fixes it.
While I'm here, I removed the `forwardRef` (React 19 wooo) and removed an unnecessary `useEffect`.
I also bumped `expo-image` while figuring out the fix - not necessary as it turns out, but it seems to have some good fixes as per the [changelog](https://github.com/expo/expo/blob/main/packages/expo-image/CHANGELOG.md). Feel free to revert that commit if you're rather not
https://github.com/user-attachments/assets/d57e7591-972a-40d8-b15a-ac1917730cc5

Fix video thumbnails on native

---

src/lib/hooks/useNotificationHandler.ts

Not tested, because I can't repro, but we're getting reports of something similar to https://github.com/bluesky-social/social-app/pull/8657
The cause last time was deep links showing up as "notification" when fetching them at launch. Clearly, some devices have something similar going on, where it shows some sort of notification at boot. Our fallback behaviour is to redirect to `/notifications` by default, but clearly this is a bad default. Let's redirect to `/notifications` only if it seems to be one our _our_ notifications, by checking for `uri` in the payload
If your android device launches to the notif screen, confirm this fixes it. Otherwise idk. yolo i guess

Fix android starting at notif screen

---

src/components/Post/Embed/VideoEmbed/index.web.tsx

Reverts #8692 
Deeper investigation reveals that when we changed the video cropping logic, we were cutting off the "sensor" div that sticks out of the post. This is the root cause of #8692, so we can revert.
Code to review is https://github.com/bluesky-social/social-app/pull/8776/commits/86757f004e43c72009a8d101f2ffdaf719794487
Position only updates when the video touches the edge of the screen
https://github.com/user-attachments/assets/3cb96857-d256-4d70-8c5d-7e82193ee523
https://github.com/user-attachments/assets/cf2a11da-300e-4add-9fbd-4f45e92dc344

Fix web video ViewportObserver component

---

src/components/Toast/Toast.tsx

This PR addresses this [linear ticket ](https://linear.app/blueskyweb/issue/APP-1365/ensure-toast-text-meets-a11y-guidelines) to ensure toast text meets a11y guidelines as well as improves the success icon to match other icon styles in the toast module. 
The latest toast design in Figma:
https://github.com/user-attachments/assets/d6bee570-4c48-404d-9970-4bd2dc118a84
`Note` in Figma the borderWidth is 0.5px but according to @mozzius , since we are using a variable that is platform specific, it’s 0.333px width on native, but that’s not possible to achieve on web so it’s 1px instead.

[APP-1365]: Ensure toast text meets a11y guidelines

---

src/lib/hooks/useNotificationHandler.ts

A compliment to #8775, but I realised that would still trigger the metric log even if the notification is invalid
If we don't recognise the shape of the payload, it probably wasn't sent from our notification service. Ergo we should completely ignore it and not log anything

Only parse notifs with a reason

---

src/alf/atoms.ts
src/components/ProfileHoverCard/index.tsx
src/components/ProfileHoverCard/index.web.tsx
src/components/ProfileHoverCard/types.ts
src/view/com/notifications/NotificationFeedItem.tsx

Fixes https://github.com/bluesky-social/social-app/issues/8587
Adds profile hover card to the author name in the grouped notification card
I had to add an `inline` prop to get it to work, which adds `display: inline` to both of the wrapper elements (didn't want to do it universally due to risk of breaking other places accidentally). This ensures it wraps properly:

Add profile hover card to notification item author names

---

src/components/Select/index.web.tsx

Recently I have spotted a small visual issue with the Radix select on the web. When options list does not fit on the viewport and scroll buttons are visible they stick out outside of the select content container.
Add overflow style to the wrapper view used in web variant of the component.

Fix web scrollable select unwanted overflow

---

src/components/ageAssurance/AgeAssuranceAdmonition.tsx

<table>
<thead>
<tr>
<th>Web</th>
<th>iOS</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/3169dd35-9e58-4e78-8ba9-1c70ba625543" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/edfa3562-0ebd-4ddb-a7c0-f7212e8843a1" /></td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr>
<th>Web</th>
<th>iOS</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/b22b400d-5bd1-40e9-a9f8-9d650128c8fb" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/c5ee1709-09eb-4d7c-9271-36e229c503a9" /></td>
</tr>
</tbody>
</table>

Make sure AA admonition text doesn't touch button

---

src/screens/Search/Explore.tsx

I don't know why it was restricted to native only. It looks broken without them imo since the top post will then be missing a border

Add bottom border to feed headers in Explore on web

---

src/components/PostControls/DiscoverDebug.tsx

<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/152e7e80-aa3e-4342-8274-1e7749cd831a" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/d2c3f4a7-91e2-4c6d-b1b7-3757232c897a" /></td>
</tr>
</tbody>
</table>

Set max width on feed context string

---

src/view/com/lists/ListMembers.tsx

Just prevents default on the edit button to avoid activating the link when clicked.

fix: don't open user profile when clicking edit button in user list

---

src/components/dms/MessageProfileButton.tsx

Button size changed by 1px, so the load state of the chat button was causing layout shift
https://github.com/user-attachments/assets/db0da504-3b6a-43e5-904a-2b34bfda61e1
https://github.com/user-attachments/assets/4aeb0283-644e-4b3f-80ca-3e15dd32d7fc

Fix chat button placeholder size on profile

---

.github/workflows/pull-request-commit.yml
package.json

Skips `intl:compile` if:
- is CI since that is typically its own step, or
- if the `messages.js` file exists, at least for english

Skip `intl:compile` if not needed

---

bskyweb/templates/base.html
web/index.html

Might make the link proxy service a little bit faster?
Also, should we use `preconnect` or `dns-prefetch` here? I don't know

Preconnect to go.bsky.app

---

src/state/dialogs/index.tsx
src/view/shell/index.tsx

**This PR is not stacked on anything**
This is the primary driver of the composer being so slow to open. Because we'd stuffed `fullyExpandedCount` into the dialog control context, every consumer of the context (i.e. every single `useDialogControl`) would rerender when `fullyExpandedCount` changed, such as when the composer opens on iOS, or when a full-height dialog opens.
On the profiler the commits are the following:
Commits 1 & 2: debug toast, ignore
Commit 3: actually rendering the composer. This takes ~30ms
Commit 4: by far the largest one, this is updating the `fullyExpandedCount` from 0 -> 1. This causes a rerender of every component with a dialog control, of which there are multiple in every post. In the simulator this takes 180ms.
There is only one spike, which is the composer …

[Perf - part 3] Stop every dialog control in the entire app rerendering when opening a dialog

---

src/screens/Moderation/index.tsx

This is a small bug left over from Age Assurance. For underage users, we hide adult content settings entirely. However, some adults may mistakenly entered the wrong birthdate, which previously left them in a "underage" state with no instructions on how to fix this. This adds a little admonition to the top of the screen for this case.

Add underage notice to Moderation screen

---

src/view/com/lightbox/Lightbox.web.tsx

Some browsers exit fullscreen when the escape key is pressed without `preventDefault()` being called; we don't want that when we're handling the press ourselves.

[Lightbox] prevent browser-default escape key behavior

---

src/state/queries/usePostThread/traversal.ts
src/state/queries/usePostThread/types.ts

Fixes a bug where `isPartOfLastBranchFromDepth` was not updated if further replies down the tree were in fact _also_ "the last branch from `depth`".
See screenshot, where the posts should have the following values:
A. `isPartOfLastBranchFromDepth: 1`, since it's the last sibling, and its depth is `1`
B. `isPartOfLastBranchFromDepth: undefined` since it's not the last sibling (there's a post further down)
C. `isPartOfLastBranchFromDepth: 3` since it's a last sibling and its depth is `3`
D. `isPartOfLastBranchFromDepth: 4` since it _itself_ is also a last sibling and its depth is `4`
E. `isPartOfLastBranchFromDepth: undefined` since it's not a last sibling (it's the first)
Case `D` is what this PR fixes.

Fix `isPartOfLastBranchFromDepth` assignment

---

src/screens/PostThread/components/ThreadItemReadMore.tsx

This [feedback on Crowdin](https://bluesky.crowdin.com/editor/1/11/en-sv/9#8330) was left by @nilaallj for the `Read 1 more reply`/`Read x more replies` string that's shown in threads:
> Maybe the reply count could be included in the plural formatting? For example: {0, plural, one {# more reply} other {# more replies}}. It’s not strictly needed for Swedish, but it would allow a more natural translation by leaving out the number in the singular form. I think other languages might benefit from this too in different ways. :)
So this PR suggests adjusting the plural formatting here to give translators more flexibility.

Tweak plural formatting in `ThreadItemReadMore.tsx`

---

src/components/FeedInterstitials.tsx
src/components/ProfileCard.tsx
src/lib/custom-animations/AccordionAnimation.tsx
src/lib/statsig/gates.ts
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/screens/Profile/Header/Shell.tsx
src/screens/Profile/Header/SuggestedFollows.tsx
src/state/queries/suggested-follows.ts

Fixes https://github.com/bluesky-social/social-app/issues/8849
Summary
---
Add a new feature to show suggested follow recommendations when you follow an account.
New components:
- `ProfileHeaderSuggestedFollows` is the main component that implements the layout of the suggested profiles.
- `AnimatedProfileHeaderSuggestedFollows` is a wrapper that uses `AccordionAnimation` to wrap the `ProfileHeaderSuggestedFollows`, also handles the gated feature for A/B testing (prevents any data loading or component rendering early to avoid extra work).
- `AccordionAnimation` is a generic animation component that is reusable should we need to re-use the same animation somewhere.
Other changes:
- Add new `statsig` gate name, `post_follow_profile_suggested_accounts`
- Some changes were cherry-picked from …

[APP-1357] profile header follow recommendations

---

src/components/ProfileCard.tsx
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/view/com/post-thread/PostThreadFollowBtn.tsx
src/view/com/profile/FollowButton.tsx

Summary
---
When a user already follows you, the profile cards "Follow" button now shows "Follow back" instead. This helps keep the follow button consistent across the app.
In addition, I noticed that since this component is used in a few other places among the app we also have it updated there for free. Such as on the search page under the "Suggested Accounts" section.
Edit: updated all uses of "Follow Back" through out the app (only a handful of spots) to be "Follow back"
Screenshots
---
_Note: I manually swapped the "Follow" and "Follow back" to get these screenshots, as it's tricky to find it naturally._
**Profile header suggested accounts**
**Search page suggested accounts section**

[APP-1406] follow suggestions card to show follow back

---

src/components/ProfileCard.tsx

As a follow-up to #8875, this PR suggests rearranging the translation logic for `followLabel` in `src/components/ProfileCard.tsx`.
Currently, Lingui shows these messages:
The explanation of the issue and how to fix it which follows is from Claude.
___
The issue is that Lingui's extraction process cannot handle dynamic expressions in the `message` field. The ternary operator `profile.viewer?.followedBy ? 'Follow back' : 'Follow'` depends on runtime data, but Lingui needs to extract all translatable strings at build time.
Here's how to fix it:
Replace the problematic code (lines 516-521) with:
```typescript
const followLabel = profile.viewer?.followedBy
? _(
msg({
message: 'Follow back',
comment: 'User is not following this account, click to follow back',
}),
)
: _(
msg({
message: 'Follow', …
```

Rearrange `followLabel` translation logic

---

src/components/Post/Embed/index.tsx

Haven't checked all cases, but hoping this fixes the padding issue
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/8df6a6b7-892c-479d-9c39-81a05c165847" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/32c675ab-c969-40e5-9c60-1fde28969a27" /></td>
</tr>
</tbody>
</table>

Add margin to content hider

---

src/lib/strings/helpers.ts

Alternative to #4876 - decided I wanted a more precise fix by just swapping out the quotes
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/b363d411-c163-4c4f-be1a-6ae4cc92f14e" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/4635598d-4b4c-4bc7-b339-82be2b1a72a4" /></td>
</tr>
</tbody>
</table>
Search for a phrase on iOS

Fix searching for phrases by replacing smart quotes with normal ones

---

src/components/FeedInterstitials.tsx

Summary
---
- Redesign the "See more" suggested profiles card with improved styling, proper Button components, and consistent theming
- Rename Arrow icon to ArrowRight throughout the codebase for better clarity and naming consistency
Screenshots
---

feat(ui): redesign suggested profiles 'See more' card

---

src/screens/Search/Explore.tsx

I don't have any actual evidence that this is happening, but I wonder if the `Discover Feeds` heading on the **Explore** tab might be a little confusing for some users, given that the default feed is called **Discover**.
E.g.: "There's a Discover feed on my home tab when I open the app, but when I go to search for something on the Explore tab there are also other Discover Feeds on all these different topics, what's that about?"
___
So this PR proposes changing the heading on the **Explore** tab from `Discover Feeds` ⮕ `Discover New Feeds`, using the same heading that's used on the **Feeds** screen:

`Discover Feeds` ⮕ `Discover New Feeds` on Explore tab

---

src/components/Dialog/index.web.tsx
src/components/Dialog/types.ts
src/screens/Profile/Header/EditProfileDialog.tsx

I have spotted that Edit Profile dialog close warning on "dirty" state only works when clicking "Cancel" button directly, but not when interacting with dialog backdrop.
The abort controller was hooked up to the window, so the alert was popping out on page navigation, when edit profile changes has already been discarded.
Expose via web-only options `onBackgroundPress` handler and hook up the logic to it, instead of relying on AbortController.
https://github.com/user-attachments/assets/65590698-9fac-4eaa-b707-222b5a5dd916

Web: fix Edit Profile discard warning when pressing backdrop

---

src/components/LoggedOutCTA.tsx

As a follow-up to #8906, this small PR marks the `Create account` label in `LoggedOutCTA.tsx` for translation.

Mark label for translation in `LoggedOutCTA.tsx`

---

src/components/ProgressGuide/FollowDialog.tsx

This tiny PR fixes an error I made in #8879 where a quotation mark got left off the end of a label (oops).

Tweak label in `FollowDialog.tsx`

---

src/components/dialogs/BirthDateSettings.tsx

https://linear.app/blueskyweb/issue/APP-1402/update-birthdate-dialog-wvalidation-and-copy
- Set max width of the dialog to 400px on the web
- Updating the text and spacing inline with the UpdateEmail dialog
- Default to 18 years ago if the birthday is not set
- Show warning for users between 13-18
- Show error for users under 13, disable saving button

Update birthday setting dialog

---

src/screens/Search/Explore.tsx

Prevent double border on web explore page

---

src/components/InterestTabs.tsx

Spotted that on web "Suggested Accounts" tabs always display right scroll button, even when end of list has been reached.
https://github.com/user-attachments/assets/41e6e2f2-204f-4b42-a55f-c6647e24bdc5
After debugging, it looks like `scrollX` was set to sub-pixel (float) value which made the check never fulfilled.
I have added the scroll value ceiling to circumvent that, which lead to existing logic properly hiding the right scroll button when the end of list has been reached.
https://github.com/user-attachments/assets/21b74837-3929-441a-899a-56b9b09140df

Web: fix Suggested Accounts tabs end of scroll detection

---

src/components/dialogs/StarterPackDialog.tsx

- Use `primary_subtle` color like designs
- Remove pull-to-refresh behaviour - it wasn't implemented properly and is weird in a dialog like this because then you can't swipe to close

Tweaks to add to starter pack dialog

---

src/components/ageAssurance/AgeAssuranceAppealDialog.tsx
src/components/dms/ReportDialog.tsx
src/lib/constants.ts
src/screens/Messages/components/ChatDisabled.tsx

We were missing the proxy header, which then broke when we started setting it explicitly
Report a chat message

Ensure headers are set when sending reports (i.e. DMs)

---

src/state/persisted/schema.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/select-language/PostLanguageSelect.tsx
src/view/com/composer/select-language/PostLanguageSelectDialog.tsx

Fixes #8971 
With the revamp of the language select, we lost the language quick switcher. On consideration, the full multi-language picker is many more taps than the old one
This PR restores this functionality using modern components
This showcases what happens if you have no languages in your language history
https://github.com/user-attachments/assets/b96bd9a2-f8e2-4da1-94fd-9f071093b8cc
https://github.com/user-attachments/assets/0a5c7360-4ee4-419e-b705-3c78936949db
https://github.com/user-attachments/assets/8f26fb2c-3535-43ef-8d2f-b617fec491e9
Test the case of having no languages in your history, and then lots of languages

Restore quick language select

---

src/components/NewskieDialog.tsx
src/components/StarterPack/QrCode.tsx
src/components/StarterPack/QrCodeDialog.tsx
src/components/StarterPack/ShareDialog.tsx
src/components/dialogs/EmbedConsent.tsx
src/screens/Settings/components/ExportCarDialog.tsx

- Add `preventExpansion` to a bunch of forgotten-about dialogs
- Make the starter pack share dialogs more appealing by making the buttons bigger and adding icons
<table>
<thead>
<tr>
<th>iOS</th>
<th>Web</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="250" src="https://github.com/user-attachments/assets/ee8b3430-489a-408a-b9cf-b2dd9c8709d3" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/b29ffb2b-7191-4fce-84cd-c0e219821785" /></td>
</tr>
<tr>
<td><img width="250" src="https://github.com/user-attachments/assets/45b94fe7-b79a-4293-83bf-4096e5520b21" /></td>
<td><img width="400" src="https://github.com/user-attachments/assets/b9860b24-1545-4ba2-82ea-a264ccfa9344" /></td>
</tr>
</tbody>
</table>

Clean up dialogs

---

src/components/verification/VerificationCheckButton.tsx
src/screens/PostThread/components/ThreadItemAnchor.tsx

It was looking a little large at 16px. `ProfileCard` has the same font size and uses 14px, so switched it to that. It's the only case that uses `md`

Reduce checkmark size in thread anchor

---

src/components/verification/VerificationCheckButton.tsx

Another nested link/button issue, this time on the checkmark button in the thread anchor. Currently clicking on it on web reloads the page.
Click on a checkmark and confirm it no longer causes a page reload

Add preventDefault() to thread anchor checkmark

---

src/components/Post/Embed/VideoEmbed/VideoEmbedInner/VideoFallback.tsx
src/components/Post/Embed/VideoEmbed/index.web.tsx

This is a "perceived speed" improvement. Because the video element is not loaded until it's within 100vh of the screen, the thumbnail often doesn't have enough time to load before you can see it.
Fix is to always display the thumbnail whether or not the player is mounted. I opted to do this via putting a background image on the containing div, then trust the browser to cache the image when it then loads it for the video `poster` prop when the player mounts
https://github.com/user-attachments/assets/9ac95cec-af96-4893-b013-4f43a443d483
https://github.com/user-attachments/assets/ac689744-7559-49b6-9c76-837f14ecf49a
and for good measure, here's the network calls - each page load fetches every thumbnail, and then you can see the additional request made as you scroll for the `poster` is simply …

Ensure there is a thumbnail for videos on web

---

src/lib/media/video/util.ts

Sometimes file extensions are uppercase

Fix `extToMime` function

---

patches/react-native-screens+4.16.0.patch

Patch of https://github.com/software-mansion/react-native-screens/pull/3173
Seems to work good. You can see the new system-native back gesture where the corners are rounded, and the scrolling bug is fixed:
https://github.com/user-attachments/assets/00a02ffa-bcad-4727-b5e8-015135c76894
~~I'm going to put this in draft. If for whatever reason we need to do a release before RNS releases their next version, we can merge this as a stopgap.~~

Patch react native screens with back gesture bugfix

---

src/App.native.tsx
src/alf/util/systemUI.ts

Seeing a lot of these in Sentry
`Call to function 'ExpoSystemUI.setBackgroundColorAsync' has been rejected. → Caused by: The current activity is no longer available`
`Call to function 'ExpoScreenOrientation.lockAsync' has been rejected.
→ Caused by: The current activity is no longer available`
If the current activity is not available that's fine, we can just ignore these errors I think. Saves 500k events of our statsig quota

Don't send some "activity no longer available" errors to Sentry

---

jest/test-utils.tsx
package.json
src/App.native.tsx
src/App.web.tsx
yarn.lock

We don't use it anymore, and it has been replaced by `Portal`

Remove root sibling library

---

src/state/geolocation/useSyncedDeviceGeolocation.ts

We're seeing [a lot of errors on sentry](https://blueskyweb.sentry.io/issues/6895909008/?project=4508807082278912) about the `navigation.permissions` API being unavailable.
Since failing to request/query permissions is effectively the same as them being denied, we should just catch this error and act if it's been denied - better than an unhandled error
I have reimplemented `useForegroundPermissions` and just added a `.catch()` to the get/request calls. [Here is original code from `expo-location`](https://github.com/expo/expo/blob/main/packages/expo-location/src/Location.ts#L290-L293)

Catch errors on geolocation request, reduce Sentry logs

---

src/components/moderation/LabelsOnMeDialog.tsx
src/components/moderation/ModerationDetailsDialog.tsx
src/components/moderation/ProfileHeaderAlerts.tsx
src/screens/Profile/Header/Shell.tsx

When a profile has no labels, there's a gap between the description and the tabs. This is because the containing View for the labels is always present, even if there's no content. Simple fix - move padding to the actual label components, remove wrapping View.
We can also move the `pointerEvent` prop to a style, so we can pass it down with the other style thing. I opened a PR to add the missing atoms for this: https://tangled.org/@esb.lol/alf/pulls/1 - in the meantime I just inlined the `box-none` one
<table>
<thead>
<tr>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><img width="300" src="https://github.com/user-attachments/assets/3a5587b0-1708-4c71-a7df-6f0eeac0741c" /></td>
<td><img width="300" src="https://github.com/user-attachments/assets/7276e798-897a-457f-a923-05c3b3 …

Fix gap on profile

---

src/logger/metrics.ts
src/state/feed-feedback.tsx

Since #8672, we now allow show more/show less on third party feeds. However, we didn't update the metrics and thus that's all being logged as `discover:showMore`/`discover:showLess`.
I've added some metrics - generic `feed:showMore` etc for all the previously `discover:`-prefixed events, which now includes the feed descriptor. ~~I've opted to still send `discover:` ones when using discover for backwards compatibility, but not to statsig~~. For forwards compatibility I have made sure to include seen/interacted events in case we merge #9094 
look at logs, confirm new events are being sent. confirm `discover:` ones are only sent when on discover

Fix feedfeedback metrics not distinguishing which feed it's from

---

package.json
src/state/session/agent.ts
yarn.lock

Once https://github.com/bluesky-social/atproto/pull/4238 is merged, this removes the hackfix working around it. That resolves one of the potential issues that @mackuba identified in https://github.com/bluesky-social/social-app/issues/8695#issuecomment-3103433871, namely the `lastSession` variable getting stale.
I don't know if there's an actual repro case for that problem, but removing clearly buggy code in favor of upstream fix seems like a good idea anyway.
Apply this PR first. We should see bad behavior on network errors, same as before the hackfix was added in https://github.com/bluesky-social/social-app/pull/4911.
Then apply https://github.com/bluesky-social/atproto/pull/4238. The test plan from https://github.com/bluesky-social/social-app/pull/4911 should pass although the hackfix …

[Fix Logouts] Remove buggy hackfix
