bluesky-social/social-app

LICENSE
README.md

Creates a LICENSE file so GitHub's UI doesn't lie and say this is unlicensed. Also points to that LICENSE file from the README rather than duplicating the text.

Create LICENSE file and point to it from README.md

---

src/state/models/media/gallery.ts
src/state/models/media/image.ts
src/view/com/modals/EditImage.tsx

This PR:
- Updates the layout for the web image editor
- Refactors the image code to be simpler
- Bumps up max size and compression factor
**Note:** this could continue to use improvement but will revisit at a later point
Desktop:
Mobile web:

Image editor mobile layout update

---

src/view/com/modals/InviteCodes.tsx

This removes the surrounding spaces inside the parentheses in the invite code dialogue, which just bugs me. If they bug you too, feel free to merge. Tested on localhost.

Remove surrounding spaces in parentheses.

---

__e2e__/util.ts

Without this, all `yarn e2e:run` tests get hung on the "input custom service" step when logging in.
Only used one machine to repro (tested all tests pass after this change and all fail before the change), so an additional repro could be useful.

test: `detox` needs `tapReturnKey` after `typeText`

---

src/Navigation.tsx
src/lib/hooks/useSetTitle.ts
src/lib/hooks/useUnreadCountLabel.ts
src/lib/strings/display-names.ts
src/lib/strings/headings.ts
src/view/com/post-thread/PostThread.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileList.tsx

For any `Screen` that shows on desktop, `title` is "(1) ... - Bluesky" where "(1)" is the unread notification count.
The titles are unlocalized and the string "Bluesky" is hardcoded, following the pattern of the rest of the app.
Display names and post content are loaded into the title as effects. Tested:
* all screens
* screen changes / component mounts/unmounts
* long posts with links and images
* display name set/unset
* spamming myself with notifications, clearing notifications
* /profile/did:... links
* lint (only my changed files), unit, e2e.
New utilities: `useUnreadCountLabel`, `bskyTitle`, `combinedDisplayName`, `useSetTitle`.
resolves: #626 #599

feat: Update HTML `title` on web (resolve #626 #599)

---

package.json
src/lib/media/picker.tsx
src/state/models/media/gallery.ts
src/state/models/media/image.ts
src/view/com/modals/EditProfile.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx
yarn.lock

This PR:
- Replaces `openCropper` from [react-native-image-cropper](https://github.com/ivpusic/react-native-image-crop-picker) with [expo-image-picker](https://docs.expo.dev/versions/latest/sdk/imagepicker/)'s `launchImageLibraryAsync`
- Is intended to [address performance issues](https://github.com/ivpusic/react-native-image-crop-picker/issues/1382) that corroborate a report we have received
- Allows access to the Favorites album

Replace image picker with expo-image-picker

---

src/view/shell/desktop/LeftNav.tsx

This fixes a line break in the "New Post" button on Firefox.
**Before**
**After**

Fix line break in New Post button

---

src/view/com/util/BlurView.web.tsx

Fixes https://staging.bsky.app/profile/favreau.bsky.social/post/3jvujbuvwnb2j by adding a webkit vendor prefixed version of `backdrop-filter` to BlurView.web.tsx.
Previously in Safari: 
Fix in Safari:

fix: Make BlurView blur things in Safari

---

package.json
yarn.lock

Update expo-image to 1.2.3
Issue: https://github.com/expo/expo/pull/22491

fix: expo-image build issue on ios 

---

src/view/screens/SearchMobile.tsx

Looks like `isInputFocused` wasn't being passed to `HeaderWithInput`, this PR fixes and expected functionality is returned :~)
Just to make it clear, the "Cancel" button was always visible on the Search tab, even if there was nothing to cancel. This change fixes that
|--------|-------|
| ![CleanShot 2023-05-16 at 09 57 22@2x](https://github.com/bluesky-social/social-app/assets/8293444/41e195b7-b1ae-488f-8b51-f89663d3aafd) | ![CleanShot 2023-05-16 at 09 57 34@2x](https://github.com/bluesky-social/social-app/assets/8293444/9effc687-642e-4c02-a9df-f1ad6b723d6a) |

Fix "Cancel" button always showing on Search tab

---

src/view/com/util/forms/DropdownButton.tsx

this will hide "report post" option for viewing posts where you are the author (similar to delete post functionality but only shows if you are NOT the author as oppose to if you are)

hide "report button" on own post

---

src/view/com/lightbox/Lightbox.web.tsx
src/view/shell/index.web.tsx

This PR:
- Closes modals / lightboxes when a user swipes back in browser
Known issues:
- [`beforeRemove` event not fired on browser back button](https://github.com/react-navigation/react-navigation/issues/9031)
- Modals and lightboxes precede introduction of `react-navigation` into the codebase, hence going back from a modal does not return the user to what is, by their definition, the previous screen. [This is likely the desired approach moving forward](https://reactnavigation.org/docs/modal/#creating-a-stack-with-modal-screens) but the changes in this PR are sufficient for now.

Close active elements on state change

---

src/view/com/util/forms/Button.tsx
src/view/shell/desktop/RightNav.tsx

Supercedes  #701
Adds visual feedback to the hover & press state of buttons. This PR uses a single callback instead of a state hook which should be a little more efficient.

feat: add basic visual feedback on Button interactions

---

src/lib/labeling/const.ts

Overlooked this when the label was added earlier.

labels: add 'corpse' to 'violent' category

---

src/view/screens/Profile.tsx
src/view/shell/desktop/LeftNav.tsx

Hi
1. There's a problem with the Profile link Active style, when you're visiting other profiles, the Profile link will be active too!
2. When the profile page is not loaded, and the user is visiting other profiles, the Profile page (because of isCurrent issue doesn't work, which I fixed in the first bullet) will get stuck at the skeleton view.
related issue: https://github.com/bluesky-social/social-app/issues/722
To Reproduce:
1. Without loading your profile, Go to someone else's profile
2. Click on the "Profile" button
To Reproduce:
1. Without loading your profile, Go to someone else's profile
2. Go to the Settings page
3. Click on the "Profile" button

Fix profile load issue + enhancement of profile isCurrent style

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

This PR:
- Updates the Google translate link so that pipe operators don't cause text to get dropped
Thank you to @mozzius for catching this!
Before:
After:

Use non-pipe translation link

---

src/view/com/auth/login/Login.tsx

Currently, logging in requires mouse interaction on web and an additional finger movement on mobile.
This process can be improved by adding `onSubmitEditing` prop to the password field, which on web allow to simulate form submit event when pressing <kbd>Enter</kbd> on the password field and on mobile pressing <kbd>return</kbd> key will attempt to perform login.
https://github.com/bluesky-social/social-app/assets/719641/fa4982c5-3cbd-46e3-94ab-da4186388408

feat(Login): allow submitting on password field

---

src/locale/en/community-guidelines.tsx
src/locale/en/copyright-policy.tsx
src/locale/en/privacy-policy.tsx
src/locale/en/terms-of-service.tsx

The community guidelines, copyright policy, privacy policy and terms of service currently uses the YYYY/MM/DD format for their "last updated" note. To avoid ambiguity, I think a full "Month DD, YYYY" format is better. This updates all four in line with that suggestion.

Make terms and notices dates less ambiguous.

---

bskyweb/Makefile

Small, low-impact, but when doing local dev probably want to load assets fresh off the disk every time.

bskyweb: run-dev-bskyweb in debug mode

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

This PR:
- Uses the user's `contentLanguages` to determine which language to translate to when opening Google Translate. Uses the first element in the languages array, falls back on `en`.
Shout out to @renahlee :)

Translate to primary language rather than just english

---

src/state/models/feeds/posts.ts
src/state/models/me.ts
src/state/models/ui/preferences.ts
src/state/models/ui/saved-feeds.ts
src/view/screens/DiscoverFeeds.tsx

This PR:
- Removes some extraneous requests (feed health check, constant background feed-info sync calls)
- Updates the preferences sync to only update the values if there has been a change, reducing needless re-renders
- Modifies the saved-feeds model to reduce the amount of state management handled there, instead deriving more canonical state from the preferences model (as the saved-feeds model is essentially an API wrapper around the feeds preference)
- Updates the preferences model to use lock-regions to avoid potentially clobbering changes that are in-flight
- Updates the preferences model to clean out duplicate feed-preferences entries if they ever occur

Fixes to feed preference and state sync [APP-678]

---

src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

Conditionally showing the "Remove" button only if there is an existing avatar/banner on the user's profile. Closes #832.
Screenshot of new behavior:

Don't show Remove button for nonexistent avatar/banner

---

app.json

Fix dark mode detection on mobile by setting `userInterfaceStyle` to `automatic`,  per [these instructions](https://docs.expo.dev/develop/user-interface/color-themes/#configuration). Closes #845.
From my local Android emulator:

Fix dark mode detection on mobile

---

bskyweb/templates/base.html
bskyweb/templates/home.html

`<meta>` & `<link>` tags are [void elements](https://html.spec.whatwg.org/multipage/syntax.html#void-elements) which means they are self closing, and do not require a closing tag, nor a trailing `/`.
The trailing `/` is something that was required in XHTML but [is ignored in HTML](https://html.spec.whatwg.org/multipage/syntax.html#start-tags). Quoth the spec:
> On void elements, [the trailing slash] does not mark the start tag as self-closing but instead is unnecessary and has no effect of any kind. For such void elements, it should be used only with caution — especially since, if directly preceded by an unquoted attribute value, it becomes part of the attribute value rather than being discarded by the parser.

remove trailing / on meta tags

---

src/lib/media/picker.shared.ts
src/lib/media/picker.tsx
src/lib/media/picker.web.tsx
src/state/models/media/gallery.ts
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

`expo-image-picker` was introduced for mobile in #649, but the web picker code remained custom. From local testing, the Expo picker works just as well on web, and it means less custom/platform-specific code to maintain. I've modified the code accordingly to share this function between the platforms (and removed the unnecessary store parameter in the process).

Use expo-image-picker on Web

---

src/view/com/feeds/CustomFeed.tsx

Prevents this behavior and instead pushes a new screen onto the stack.
https://github.com/bluesky-social/social-app/assets/8207733/4118d53e-7b16-48e7-9467-c1e271d19546

[APP-683] Go to another custom feed from within a custom feed

---

src/view/screens/Settings.tsx

You can click on the app/build version info in the bottom of settings to copy it.

[APP-679] Make app version info copy-able

---

docs/build.md

Updating `build.md` to link to [the Expo instructions for creating a Sentry auth token](https://docs.expo.dev/guides/using-sentry/#sign-up-for-a-sentry-account-and-create-a-project) so that it's clearer for people who want to contribute.

Link to instructions for creating Sentry auth token

---

src/lib/hooks/usePermissions.ts

Right now, if you deny permissions for e.g. your photo library when browsing a photo for your post, the app shows a modal that you need to grant permissions to the application that is supposed to link to the app settings. However, that link (using the `app-settings:` URL) only works on iOS, not Android (nothing happens there).
To fix this, I've changed it to use [`Linking.openSettings()`](https://reactnative.dev/docs/linking.html#opensettings), which was made for this purpose/to use across platforms. Verified that it now works properly in an Android emulator.

Use Linking.openSettings() so it works on Android

---

src/view/screens/Search.web.tsx

I encountered an error while using Bluesky on Web, where the search page wouldn't render if I loaded user search results, navigated away, and then loaded the page again. This is due to a difference in the number of hooks called when rendering the page depending on whether there are user search results or not (which violates [the hooks rules](https://legacy.reactjs.org/docs/hooks-rules.html)). I've modified the code to always call `useWebMediaQueries()` before any return happens accordingly.

Move useWebMediaQueries() above return

---

package.json
src/view/com/util/Html.tsx
yarn.lock

Using [the native heading elements from [`@expo/html-elements`](https://github.com/expo/expo/tree/main/packages/html-elements), which will output e.g. `<h1>` tags on Web (and extra properties across platforms) that should help with accessibility. Verified through local testing of the privacy policy and other pages that the styling remains the same.

Use native heading elements

---

src/lib/api/debug-appview-proxy-header.ts
src/state/models/root-store.ts
src/view/screens/Settings.tsx

The backend bois need to test a change to the architecture, so this PR adds a toggle to the settings for doing that. It's only enabled on web.

[APP-700] Add temporary appview-proxy header toggle

---

src/state/models/ui/saved-feeds.ts

Diagnosis:
It seems as though there was not proper error handling when fetching feedGenerators while updating cache in the SavedFeedsModel. This led to one bad feed corrupting all the feed items. 
Fix:
Add error handling to catch errors so that it does not break out out of the function/loop

[APP-681] Pinned feeds not showing up bug

---

src/lib/api/debug-appview-proxy-header.ts

Repro steps:
- `git checkout main`
- `git pull`
- Run app on Android
- Open sidebar, go to settings
- App will crash with the following error
- Only happens on Android (iOS is totally fine)

Hotfix: Android app crashed when opening settings with Appview debug

---

__mocks__/@gorhom/bottom-sheet.tsx
package.json
src/Navigation.tsx
src/lib/ThemeContext.tsx
src/state/models/feeds/posts.ts
src/view/com/composer/Composer.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/util/ViewSelector.tsx
src/view/com/util/forms/Button.tsx
src/view/screens/DiscoverFeeds.tsx
src/view/screens/SavedFeeds.tsx
yarn.lock

I noticed that `@types/react` was pinned to ^17, which is out of sync with the version of React being used (18). I've bumped the resolution to `^18` and adjusted the types (and logic in some cases) accordingly. I've also fixed the typing regression introduced in #885 and simplified the code.

Bump @types/react to ^18 and adjust types

---

app.json
package.json
src/lib/api/feed-manip.ts
src/lib/api/index.ts
src/lib/functions.ts
src/platform/detection.ts
src/state/models/ui/preferences.ts
src/state/models/ui/shell.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/modals/lang-settings/ConfirmLanguagesButton.tsx
src/view/com/modals/lang-settings/ContentLanguagesSettings.tsx
src/view/com/modals/lang-settings/LanguageToggle.tsx
src/view/com/modals/lang-settings/PostLanguagesSettings.tsx
src/view/com/util/forms/ToggleButton.tsx
yarn.lock

To test, make sure you are on the `post-languages` branch on `atproto`

[APP-690] better handling of post languages language filtering

---

src/view/screens/Profile.tsx

This adds accessibility role, label and hint to the compose button on profile pages, to match the same button in all other views. Fixes https://github.com/bluesky-social/social-app/issues/695.

Add a11y details to profile page compose button.

---

patches/react-native+0.71.8.patch

Applies a patch to react-native to revert https://github.com/facebook/react-native/commit/a804c0f22b4b11b3d9632dc59a6da14f6c4325e3 which is being tracked at https://github.com/facebook/react-native/issues/37991. When that issue resolves we can drop this patch.
Fixes https://github.com/bluesky-social/social-app/issues/891

Fix Voice Control input on iOS (closes #891)

---

package.json
src/view/com/composer/photos/Gallery.tsx
src/view/com/modals/AltImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/index.tsx
yarn.lock

- Adds an info tooltip about what alt-text is, (hopefully) encouraging people to use it
- Adds a green checkmark when you add alt-text
- Increase the tappable region for going to the alt-text editor (now just pressing the image does it)
- Alt-text modal now shows the image
- Reduced the size of the "ALT" labels on images to avoid covering the image
|Composer|Alt Text Editor|In the feed|
|-|-|-|
|<img width="397" alt="CleanShot 2023-06-26 at 17 45 02@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/b42b714a-52d6-4732-a1b2-3fa331efee09">|<img width="392" alt="CleanShot 2023-06-26 at 17 45 16@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/9afefc80-39eb-4bee-ab69-084db3a59c10">|<img width="384" alt="CleanShot 2023-06-26 at 17 45 42@2x" …

Improvements to the alt text behaviors in the composer

---

src/view/com/composer/Composer.tsx

I misunderstood the scope of https://github.com/bluesky-social/social-app/pull/912
The bulk of that PR was clearing up the copy around the confirm modal, which switched it to this (I'm good with this):
However it also changed the cancel button to this:
And this PR changes the cancel button back to this:
There are two concerns about the red discard label:
1. Color: we have to be really conservative about button/link colors because visual divergence draws focus. Red is, in particular, extremely attention-grabbing and we don't want to use it unless it's the primary action.
2. Label: I'm more flexible on this but generally I try to use "Cancel" as the standard way to stop an action because folks are trained around it and it therefore scans quickly. The discard modal was previously botching …

Revert change to the cancel button in the composer

---

src/lib/media/manip.ts
src/lib/media/manip.web.ts
src/view/com/lightbox/Lightbox.tsx
src/view/index.ts

Android's share menu doesn't include a way to save images, so this PR updates mobile's lightbox with a "Save" button that adds the image to your "Bluesky" album.

[APP-716] Add 'save image' button to the lightbox

---

src/view/com/util/post-ctrls/RepostButton.web.tsx

This fixes a web UI bug where the repost count is rendering with `font-weight: 500` (the `md-medium` style) while the reply and like counts get `font-weight: 400`.

Use consistent font weight for repost count

---

src/view/shell/desktop/LeftNav.tsx

This is a fix for https://github.com/bluesky-social/social-app/issues/641 which simply adds `asAnchor` to the sidebar avatar link, making it an `a` element instead of a div, and thus also keyboard-clickable.

Make sidebar avatar keyboard-clickable.

---

src/view/screens/Settings.tsx

This fixes https://github.com/bluesky-social/social-app/issues/644. All items are keyboard-clickable with this fix, by changing previously unclickable items from `Link` to `TouchableOpacity` button elements with event handlers.
On top of the mentioned "App passwords," "System log" and "Storybook" items, it also fixes the "Saved Feeds" item which I think did not exist at the time the issue was opened, and the "Reset preferences state" item which is not visible to regular users.
I put all press events in separate callbacks in case something else needs to happen except the navigation and because it follows the format of the rest of this component. If this is too convoluted, I guess the navigation could go directly in the `onPress` property on each item.
I'm also unsure if …

Fix keyboard navigation on settings page.

---

src/view/com/util/post-embeds/index.tsx

Our max height for post images currently seems to work for most cases on mobile, but is clipping on Web. This PR just bumps the max height on desktop so that clipping happens less frequently.

Fix: let images on desktop web take more vertical space

---

src/view/com/composer/photos/Gallery.tsx
src/view/com/lightbox/ImageViewing/@types/index.ts
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/Lightbox.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/Link.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/PostSandboxWarning.tsx
src/view/com/util/forms/DropdownButton.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/moderation/PostHider.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/com/util/post-embeds/index.tsx

- Adds alt text labels to the "zoomed in" (lightbox) images
- Hides the "ALT" ui element from the screen reader
- Removes a11y wrapper from posts (see 844e3dd342587ce1af182a0afc55bf2b8cc6162f commit message for details)
- Improves alt-text label assignment
- Updates the `<Link>` element to use the `title` attribute if `accessibilityLabel` is not set (improves PFP labeling)
- Improves the post meta to skip ui elements and read the dates as actual dates
- Improves the post controls (reply, like, etc) to be more clear and to include the current counts in the labels
Closes https://github.com/bluesky-social/social-app/issues/947

[APP-724] Collection of accessibility fixes

---

src/state/models/media/gallery.ts
src/state/models/ui/preferences.ts
src/view/com/composer/Composer.tsx
src/view/com/util/forms/ToggleButton.tsx
src/view/screens/Settings.tsx

Supersedes #913. Closes #907 
Builds on the PR by updating the UI of the toggle

Add alt text validation option to user preferences (supersedes #913)

---

src/state/models/content/post-thread-item.ts
src/state/models/feeds/post.ts

Turns out we got the reply root URI reference wrong, which caused the thread mute button to apply to the current post instead of the root of the thread. This fixes that.

[APP-728] Fix reply-root reference (fixes thread muting)

---

src/lib/hooks/useOnMainScroll.ts

In https://github.com/bluesky-social/social-app/pull/942 we changed thresholds depending on the platform to avoid the dancy header issue with minimal shell mode. The minimum `y` threshold also got dropped, but this fails with iOS because the scroll bounce causes a `dy` that retriggers minimal shell mode.
This PR restores that minimum `y`

Fix: re-add the scroll boundary to avoid minimal shell at top of screen

---

src/view/com/pager/TabBar.tsx

The tab bar items need `justify-content: center` on them or else they can appear unaligned when a feed name has an emoji character in it.
Please test this before deploying, this was an off-the-cuff PR I made by playing with Chrome Dev Tools, I haven't run the webapp locally.
See also: https://bsky.app/profile/aendra.bsky.social/post/3jzpdnkpmss2t

Fixes vertical alignment in feed tab bar when emoji present in feed names

---

src/lib/analytics/types.ts
src/lib/constants.ts
src/view/shell/Drawer.tsx
src/view/shell/desktop/RightNav.tsx

This PR:
- Updates the "Send Feedback" link to a new zendesk form
- Adds a help link
- Modifies the sidebar to not overflow on display names or handles so there's less content getting pushed down

Update support links

---

bskyweb/templates/post.html

The Go generated post page is missing the post text due to an incorrect variable name. The variable is correct in the meta tags.

Fix missing post text in noscript post view

---

src/lib/labeling/const.ts

Changes the "Hate Group" content filter to be more clear about how we're using it:

[APP-736] Clarify hate-group moderation as it's currently used

---

src/view/com/util/moderation/ImageHider.tsx

The existing ImageHider is using a blurring effect which has some issues
- On firefox it's inconsistent about actually covering the full image
- It's kind of an eye-grabbing visual that draws attention when viewed over the shoulder
- The way it's applied causes the element to be rather large
- The "Hide" element is often mispositioned
This PR replaces it with something much simpler and more reliable
|Before (covered)|Before (uncovered)|After (covered)|After (uncovered)|
|-|-|-|-|
|<img width="597" alt="CleanShot 2023-07-03 at 17 56 08@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/4ceaac7f-4609-4068-8a5a-f4f49cf47544">|<img width="604" alt="CleanShot 2023-07-03 at 17 56 29@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/f353abf4-d50e-4c2d-8999-a46 …

[APP-729] Replace the ImageHider blurring effect with a simpler and more reliable card

---

src/lib/analytics/types.ts
src/state/models/ui/shell.ts
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/modals/ProfilePreview.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/com/posts/MultiFeed.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/Link.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/UserAvatar.tsx
src/view/screens/Feeds.tsx
src/view/screens/Home.tsx

- Gets rid of the "two line" PostMeta behavior
- Fixes the android issue with post headers getting weirdly truncated
- Adds a new "Profile Preview" modal which triggers when you tap a PFP in the skyline or a thread
- Unifies the theming of the profile header follow button with everywhere else in the app
https://github.com/bluesky-social/social-app/assets/1270099/0cd5520b-d436-4f56-9b8f-be48c21a1c90

Post UI updates (Profile Preview on mobile)

---

src/view/screens/Home.tsx

Noticed that if the `getFeed` method throws an exception, or doesn't return data, the `isEqual` check will fail and the `useEffect` hook will run indefinitely. I was getting a max stack size error in dev, and I assume this would cause issues in production though I haven't replicated.
Since we don't await `model.setup()` here, I'm using `isInitialized` to note just that we've set up the models and don't need to run the effect again.

handle failed custom feeds on home screen

---

src/view/com/modals/report/ReportAccount.tsx

After spelunking in the code a bit, this seems like an existing solution to the app UI that allows people to submit offensive accounts ( handles, display names, etc ) for moderation.
This does not handle the separate issue of when users initially create a seemingly inoffensive account and then change it later, etc. This just enshrines offensive account-specific language as a reason for reporting an account.

adds additional reason for reporting an account profile

---

src/view/shell/Composer.web.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx

Fixes #1001 
Seemed to me like based on original the styles that the mobile version here was supposed to fill the screen, so that's what I did. I tried an option with a gutter all the way around the `Composer`, but decided on small devices that it was too scrunched atm.
On desktop, I chose an arbitrary gutter of 40px, lmk if we've got more specific values for this.
Screenshots ordered by increasing screen size:

#1001 Modal content overflow

---

src/state/models/ui/shell.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/TimeElapsed.tsx

Fixes #984
This PR provides a little util component that updates a "time ago" value based on an initial starting timestamp.
I also considered using a single global `setInterval` in a mobx store — or using an event emitter — and subscribe to tick events, but decided this was simpler. I'm not sure of the perf difference between 100 `setIntervals` and 100 event subscribers, but I'd guess it's not a significant difference. Lmk if y'all disagree ✌️

#984 Updating `indexedAt` timestamps

---

src/view/com/pager/TabBar.tsx
src/view/shell/Composer.web.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx

Two fixes:
1) Bottom bar size changed:
2) Feeds tab bar was overflowing on mobile web

Hotfix mobile web styling issues

---

src/view/com/util/Link.tsx
src/view/com/util/post-embeds/index.tsx

Fixes #995 
We were missing `asAnchor`, which adds an `href` and is converted to a link by `react-native-web`. Also, `TouchableWithoutFeedback` doesn't appear to pass down the `href` prop, but it works when applied to its immediate child, [as suggested here](https://github.com/necolas/react-native-web/issues/1692#issuecomment-668721415).
Looks like there is some prior work done in #750 (reported in #752). I believe this should work for the case of no-feedback-and-cursor-pointer, which mirrors what we have right now. Will follow up on the related work soon 👍

#995 use `asAnchor` on external embeds

---

package.json
patches/@mattermost+react-native-paste-input+0.6.4.patch
src/view/com/composer/Composer.tsx
yarn.lock

Bumping `react-native-paste-input` to 0.6.4 to pull in [my fix for the blur issue on unmount](https://github.com/mattermost/react-native-paste-input/pull/20), which had led to a hack that's no longer needed.

Bump react-native-paste-input; remove hack

---

src/view/com/profile/ProfileHeader.tsx

At least right now, the only type of lists we have is `Mute List` and IMO it doesn't make a lot of sense to allow my ownself to be added to a mutelist.
> On other user profile
> On my own profile

:lipstick: Hide Add to List option on own profile

---

src/view/screens/CustomFeed.tsx

Fixes #1088
The `Feed` component has a nice skeleton loading state, but handling DID resolution in the main body of the inner component results in a lot of conditionals and updates to allow undefined values (see `PostsFeedModel` and `useCustomFeed` params for example).
Handling it before this component even renders is a simpler data flow, but with the drawback of a small loading state prior to the main feed loading state.
Both loading and error state were lifted from the main post screen.
https://github.com/bluesky-social/social-app/assets/4732330/e0343a39-0bf8-4b1a-8237-7568681e876d

resolve did before loading feed

---

src/state/models/feeds/posts.ts
src/view/com/composer/Composer.tsx

Manipulating the feed's previous posts can trigger runaway scrolling. This PR changes the after-post logic to prompt the user to load rather than immediately showing the post.

Simplify the after-post logic to avoid a UI bug (the "zoomies")

---

src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx

Noticed some mis-alignment of feed item components the other day and decided to fix it quickly. Screenshots below, iOS looks good too, have not tested on Android (need to fix my env apparently).
To fix these, I basically rearranged the components to create new layout containers. That way, instead of `absolute` positioning, we can let things flex and move based on the height of surrounding content.
For review, have a quick scroll through some of your feeds and confirm there aren't any edge cases I missed.
Before -> After

fix feed UI alignment issues

---

src/view/com/post-thread/PostThreadItem.tsx

This [was previously](https://github.com/bluesky-social/social-app/commit/b154d3ea2#diff-0980d61e6f9f147f46edbf4f397b45ec438ae46571a0f1e3cf39748ca9061f0fL162) `PostHider`, which has `noFeedback` and `accessbility={false}`, so I added that back.

fix post thread feedback regression

---

src/view/com/util/UserPreviewLink.tsx

The profile preview modal now depends on a swipe gesture which web doesnt support. This PR just disables it on mobile web.

Fix: dont use profile preview modal on mobile web

---

src/state/models/content/post-thread-item.ts
src/view/com/post-thread/PostThreadItem.tsx

Noticed this last week too, decided to just knock it out using the same styling changes I made in #1106. In addition to reply line alignment, some replies were not styled as replies (no reply line), and some posts were missing borders between them. 
Part of the issue here was a bug in how we set `_showParentReplyLine`. I've edited that here and I believe it's correct now, but @ansh should have a look to confirm.
Note for reviewers: turn off whitespace to more easily see the actual changes.
Before and afters:

fix thread spacing and reply lines

---

src/lib/api/feed-manip.ts
src/state/models/feeds/posts-slice.ts

Turns out the react key I chose for https://github.com/bluesky-social/social-app/pull/1113 wasn't unique enough (it shows up in profile pages when people repost themselves). This fixes that, unless somebody manages to repost themselves with the exact same timestamp.

Fix to react-key uniqueness in feeds

---

src/view/com/util/post-embeds/index.tsx

Bug introduced by the switch to the `<MaybeQuoteEmbed>` component which didn't account for the fact that feeds and lists use the same record embed type. This PR restores the rendering of feed and list cards

Fix rendering of feed and list post-embeds (close #1131)

---

__e2e__/mock-server.ts
jest/test-pds.ts
src/lib/moderation.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Embeds currently don't have alerts when they should:
This PR fixes that:
This also applies to a "downgrading" behavior† which applies to self quote posts:
† Moderation UI "downgrades" from filters & blurs to just alerts for your own content. This is to avoid confusingly absent content, but it's currently a little inconsistent -- it correctly downgrades on quote posts but not on images. I'm going to tweak this behavior a bit, but for now it's useful to get this fix done.

Add alerts to embeds

---

src/view/com/lists/ListsList.tsx
src/view/com/modals/ListAddRemoveUser.tsx

A small improvement to help address #1081 until we have time to improve the performance of this data fetching.
Adds an improved loading spinner and grays out interactive elements until everything has loaded.
This _removes_ the spinner from the `ListsList` component, which means `ModerationMuteListsScreen` loses it too (the component is reused there). However, the `FlatList` skeleton UI state already obscures the loading spinner and the spinner's disappearance was a little jumpy sometimes anyway. I actually think it's better off without it, but I may be missing an edge case.
https://github.com/bluesky-social/social-app/assets/4732330/28bac020-97a9-4c41-89a5-5eff8fb8689d
For reference, here's what the other load state now looks like: …

wait for list memberships to load before becoming interactive

---

src/view/com/modals/SelfLabel.tsx

Replaces the emojis "describing" the labels (#1141) with a button to remove the label (which you can do by tapping again but that's not 100% obvious).
https://github.com/bluesky-social/social-app/assets/1270099/b9723028-62ee-414e-86f0-856a1f91f662

Replace the emojis in the self-labeler with a remove button

---

package.json
src/lib/moderation.ts
src/view/com/modals/ModerationDetails.tsx
src/view/com/util/moderation/ContentHider.tsx
yarn.lock

This PR updates how blocks are handled with embeds to give more information about what's going on. It also pulls in an updated SDK which causes QPs with block-states to be filtered from feeds.
There are some active discussions about how aggressive blocking should be -- it is now _extremely_ aggressive, applying to everyone (the third state below) and essentially prunes replies by blocked users from the world. These behaviors are not resolved and will get another design pass in the near future.

More useful block-state information in embeds

---

src/view/com/util/ViewSelector.tsx

View selector in the profile wasn't covering the background fully. Easy fix.

Fix: set background color of the view selector

---

src/view/com/composer/labels/LabelsBtn.tsx

The modal was opening behind the keyboard. This fixes that issue.

Fix: close keyboard when viewing the self-label modal

---

src/state/models/me.ts

Fixes APP-802
`getSession` returns un-validated `user.handle`. `getProfile` on the other hand _does_ validate, and will return `handle.invalid` for un-resolveable handles.

use user.handle response from getProfile, not getSession

---

src/lib/moderation.ts
src/view/com/profile/ProfileCard.tsx

Was getting this error when `ProfileCardPills` was used
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `ProfileCardPills`. 
```
This just fixes that.

[APP-798] add key to `ProfileCardPills` render method

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/util/post-embeds/index.tsx

We switched to `expo-image` a few months ago in #452, and Expo provides its own [prefetch](https://docs.expo.dev/versions/latest/sdk/image/#prefetchurls) handling. Calling `react-native`'s built-in prefetch may be causing unnecessary calls to our CDN.

fix prefetching lightbox images

---

src/state/models/me.ts

Closes #1177
Ensures profile and post caches clear on session change to avoid carrying over session-specific state

Clear caches on session change (close #1177)

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/NativeDropdown.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/com/util/post-ctrls/RepostButton.web.tsx

Closes #1176 
https://github.com/bluesky-social/social-app/pull/988 switched us to a dropdown-menu library (which is actually a wrapper around multiple libraries) that doesn't support hit slops. The only way to expand the tap target is to add padding to the control, which required multiple updates to layout. This PR does that.

Fix tap target size of post dropdown menus (close #1176)

---

.github/workflows/build-and-push-bskyweb-aws.yaml
.github/workflows/build-and-push-bskyweb-ghcr.yaml

Counterpart: https://github.com/bluesky-social/atproto/pull/1460
This PR runs the actions only for the original `bluesky-social/social-app` repository.
Do not merge if you wish to build and push main branches from other repositories.

Require bluesky-social/social-app for .github/workflows/build-and-push-*

---

src/lib/api/feed-manip.ts
src/state/models/feeds/posts.ts

Closes #1028 
Just needed to run filtering logic on the server response
NOTE: The server is sometimes returning an empty array for the feed. Need to look into why because that should never happen.

Fix to "Load new posts" showing sometimes when there's nothing new to show

---

__tests__/lib/string.test.ts
src/lib/api/index.ts
src/lib/strings/rich-text-manip.ts
src/lib/strings/url-helpers.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.web.tsx

Adds link shortening to the composer so that the character count doesn't get spent on URLs. Previously we did this shortening only on render, but this update does it on publish as well.
https://github.com/bluesky-social/social-app/assets/1270099/81a2b6cf-6225-4594-b340-0976883e7562

Shorten links in composer to reduce char usage

---

package.json
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.web.tsx
yarn.lock

The tiptap `useEditor()` hook creates an awkward challenge for passing event handlers into its plugins and native events. By introducing a memoized editor, we should be able to shuttle events out of tiptap without retriggering the useEditor hook. The emitter can then change its registered handlers with each state update.
This closes #1193 which was caused by stale state getting captured in the `onPressPublish` closure.

Fix to the web composer's state management (close #1193)

---

package.json
yarn.lock

Sentry Reports have suggested this is a bug in in `react-native-reanimated`
This PR upgrades `reanimated` to the latest version to hope the issue is fixed.
Hopefully fixes #1146

Fix #1146 Android fatal crash

---

src/view/com/post-thread/PostThreadItem.tsx

Tested on all platforms.
Before:
After:

Fix to post meta overflow in highlighted post

---

src/state/models/feeds/posts.ts
src/state/models/ui/profile.ts

Fixes #1212 
Adds an options object to the `PostsFeedModel` so that we can specify feeds that should display as a flat array of posts and not be threaded in situ into replies.
This will be useful for the upcoming Likes tab as well.

do not thread author media filtered feed

---

src/view/screens/SearchMobile.tsx

Right now if you submit the search field on the Discover page with no content it submits an empty result, which shouldn't happen and rightly returns zero results. This PR fixes that.
| Posts | Users |
| --- | --- |
| ![Screenshot 2023-08-22 at 4 28 36 AM jpeg](https://github.com/bluesky-social/social-app/assets/8293444/51c64949-bc19-4b16-9325-d6d85b93769f) | ![Screenshot 2023-08-22 at 4 28 38 AM jpeg](https://github.com/bluesky-social/social-app/assets/8293444/7fe77a69-fef8-41e9-b349-03388eaa394a) |

Don't submit search if query is empty

---

src/lib/link-meta/link-meta.ts

Fix to a small bug introduced a bit ago that drops the timeout for link meta fetches (thanks @mozzius!)
Closes #1214

Fix: include link-meta abort signal for timeout (close #1214)

---

src/state/models/feeds/notifications.ts
src/view/com/post/Post.tsx

Closes #1196 
Ensures that the posts in the notifications re-render upon fetch

Fix: update posts rendered in notifs on refresh (close #1196)

---

src/view/com/modals/ChangeHandle.tsx

Close #1004 by removing a (potentially) confusing period in the domain instructions
Close #1087 by giving a bit more info about the target domain (the line about "This should create a domain record at:")
+1?

Change Handle modal DNS instruction tweaks for clarity

---

src/state/models/ui/preferences.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/modals/lang-settings/PostLanguagesSettings.tsx
src/view/com/util/forms/DropdownButton.tsx
src/view/index.ts

Fixes #1075 
Revised approach after discussion in Slack, so deleted my previous description.
New approach is to store the post language as a comma separated string of 2-character language codes on the `postLanguage` prop. This string is split and still accessible by the previous `postLanguages` prop via a getter.
Also added here is a rolling history of the language combinations the user has selected.
https://github.com/bluesky-social/social-app/assets/4732330/602db981-b606-4af5-bf70-ea285718c5cd
Also updated to use a Radio icon at Ansh's recommendation:

Improve handling of unselecting languanges in composer language menu

---

bskyweb/cmd/bskyweb/main.go
bskyweb/cmd/bskyweb/server.go
bskyweb/example.dev.env
bskyweb/example.env

Removes XRPC client auth stuff, and just connects to AppView backend, which serves up both profile views and thread views without auth. This is in contrast to the PDS, which requires auth for those endpoints. This will also make stuff Just Work Right with federation.
This fixes part of https://github.com/bluesky-social/social-app/issues/983, though not the labeling part.
Tested locally, against prod appview, and seems to work. Should test in staging as well.
Deploy checklist:

bskyweb: switch from PDS backend to AppView backend

---

src/state/models/feeds/posts.ts
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

Should help #1233
Each of the tab screens renders when you open the app, so this relies on `isPageFocused` to trigger a first load of the feed itself. And since loading happens lazily, we need a loading state ready for the user on each swipe, hence the change to loading logic to show a default loading state only if `isInitialLoading = true`.
`isInitialLoading` is named after the [same feature](https://tanstack.com/query/v4/docs/react/guides/disabling-queries#isinitialloading) in React Query.

defer loading of feeds until visible

---

src/view/com/feeds/CustomFeed.tsx
src/view/com/util/Link.tsx
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/images/Gallery.tsx
src/view/com/util/post-embeds/YoutubeEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Relates to #752, basically removes pressed styles for links/embeds.
This PR moves to using `Pressable` for interactive elements. Essentially the following is true:
- Links have a `pointer: cursor` and do NOT have a pressed style (yet)
- Links with `href` (sometimes via `asAnchor`) render as `<a>` on the web
- `noFeedback` behaves as it was
`Pressable` is RNs successor to the `Touchable*` components. We _should_ add pressed styles to some elements, but this PR does not include that, since we'll want to consider case-by-case with some of these.
A11y properties and keyboard nav still works the same afaict.

Use `Pressable` for most links/embeds

---

src/view/com/notifications/FeedItem.tsx
src/view/com/post/Post.tsx
src/view/com/search/SearchResults.tsx

The `<Post>` component had old logic for passing in a `uri` to load from as an alternative to using the supplied view. This was a pretty poorly thought-out piece of code (by me) to begin with, but I made it worse when I modified it in #1243. Since it's not actually used now, it's good to remove.
I didn't create a repro to confirm this caused #1302 and I can't quite find the logical pathway for for non-termination. I assume the issue arises if `initView` is ever undefined or if `uri` ever changes.

Remove ability for Post component to load from URI (close #1302)

---

src/lib/api/feed-manip.ts
src/state/models/feeds/posts.ts

The first commit is not strictly necessary but wise to do -- the feed tuner is stateful and the `checkForLatest()` call was modifying that state. That state resets whenever "load new posts" is pressed so it didn't manifest as a bug, but it's still smart to avoid issues.
The second commit is a somewhat gross sanity check to ensure that we never let a duplicate react-key through. Because a duplicate react key is _disastrous_ to rendering, I think this is worth doing.

Improvements to feed assembly to avoid possible state issues

---

src/view/shell/desktop/LeftNav.tsx

Left nav profile picture flashes for a second as a default avatar and it links to /profile (broken link) before your profile data fully loads in the store.
Make the avatar be a placeholder like in the profile view and don't link it before the data loads.
Before:
https://github.com/bluesky-social/social-app/assets/6214736/c52de5fd-82ad-42ae-9b84-ebc88239f631
Fixed:
https://github.com/bluesky-social/social-app/assets/6214736/c06b5114-b1cf-4e40-80da-43798540aa35

Fix: Don't flash default profile avatar and broken profile link in nav

---

bskyweb/templates/base.html
package.json
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/web/LinkDecorator.ts
web/index.html

Closes #1293
Closes #1292
This PR replaces tiptap's link plugin with a simple "decorator" plugin. The multiline comment at the top explains the situation pretty well:
> TipTap is a stateful rich-text editor, which is extremely useful when you _want_ it to be stateful formatting such as bold and italics. However we also use "stateless" behaviors, specifically for URLs where the text itself drives the formatting.
> This plugin uses a regex to detect URIs and then applies link decorations (a <span> with the "autolink") class. That avoids
adding any stateful formatting to TipTap's document model. We then run the URI detection again when constructing the RichText object from TipTap's output and merge their features into the facet-set.

Replace web editor link behavior

---

src/lib/hooks/usePermissions.ts

Fixes [an issue](https://bsky.app/profile/hugelgupf.bsky.social/post/3k5xf4hh5v52y) where Android 13 users would get into a stuck state with partial permissions. Expo will probably handle this differently ([open Issue](https://github.com/expo/expo/issues/24122)) in the future, but for now this is a pretty good solve I think.
No changes to iOS or web.
See here how partial permissions will result in `undetermined` status, and once we can't ask again we push them to settings instead of doing nothing.
https://github.com/bluesky-social/social-app/assets/4732330/426e2351-63fd-4f83-835a-ace2e63665b0

handle stuck state with granular android permissions

---

src/view/screens/Search.web.tsx

On views that use the `Feed` component and therefore `FlatList`, we have `desktopFixedHeight` that applies `height: 100vh; overflow-y: auto`. On the search page, we only load 30 posts, and so don't use the `FlatList`. The reason it's 100vh and not 100% is because it's nested deep enough in the tree that our wrapping containers that ARE 100% aren't direct parents.
I think the preferable way to fix this is to use do it as high up the tree as possible so that we can use a relative height of 100%. This PR also only applies these styles to web, which is a little nicer than having to conditionally apply them when `isWeb` within the `SearchResults` components.

fix lightbox on search page

---

__mocks__/@miblanchard/react-native-slider.js
bskyweb/cmd/bskyweb/server.go
package.json
src/Navigation.tsx
src/lib/routes/types.ts
src/routes.ts
src/state/models/ui/shell.ts
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/screens/PreferencesHomeFeed.tsx
src/view/screens/Settings.tsx
yarn.lock

Fix #1014 forever (it is a non-deterministic bug so moving to a screen was the best option)
web

Move `PreferencesHomeFeed` to a screen instead of a modal

---

src/view/com/util/layouts/Breakpoints.tsx
src/view/screens/Notifications.tsx

Fixes #1338 
Fixes #1090 
- Marks notifications as read if user spends 5 seconds (can be adjusted) on the Notifications Screen
- Marks notification read if the user suspends the app while in the notification tab then opens the app into the notification tab and then closes the app again
Also fixes a small type regression introduced in the Onboarding PR

Fix 1338 mark notifications read with timeout and on app state change

---

src/locale/helpers.ts

Addresses #1312
We weren't encoding `#` (and maybe other characters) while constructing the translate URLs. In the case of `#` it was simply being interpreted by the browser as a hash anchor and not part of the `text` query param.

encode all unsafe characters in post text for translate URL

---

src/lib/embeds.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/moderation/PostAlerts.tsx

When viewing a post by a muted user, we want to show that they're muted but what currently happens is intense. Not only is the alert overkill, it treats self-QPs as something to mask:
This PR gives a more suitable UI warning and also stops the self-QP scenario:

Improved mute alerting

---

src/view/com/composer/text-input/TextInput.web.tsx

- Fixes https://github.com/bluesky-social/social-app/issues/1300
- Fixes caret jumping to the end when inserting an emoji in the middle of the post using our picker 
- Fixes caret jumping to the end when blurring out of the composer and focusing it back again (maybe controversial)
---
See https://github.com/bluesky-social/social-app/issues/1300#issuecomment-1705753534 for an explanation. TLDR:
- We shouldn't be jumping the caret when the user picks an emoji. They might be in the middle of the post anyway.
- We should not be reading mutable `.length` in order to "jump" the caret to the end — it appears that our text editing library does not guarantee whether the new value is flushed yet by the time `onFocus` fires.
- Although we *could* have fixed that by using `focus('end')` instead of …

Fix caret jumps for web composer

---

src/view/screens/CustomFeed.tsx
src/view/screens/Feeds.tsx
src/view/screens/Home.tsx
src/view/screens/Profile.tsx
src/view/shell/desktop/LeftNav.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1298 based on @ashleemboyer's suggestion. Thanks @ewaccess for extra repro and testing tips.
The first commit changes left sidebar "Compose post" desktop web a11y label to "New post", resolving the original issue:
https://github.com/bluesky-social/social-app/assets/810438/9ea7be2a-6cec-4772-8153-7fa2c230564c
I opted to keep the explicit label though happy to remove it too.
In the second commit, I update other compose buttons (which don't have text labels) to also use "New post". This is to ensure it works on mobile layouts on the web, as well as to have consistency in the voice control wording between the platforms. (Note this may be disruptive to people already used to "compose". Alternatively, we could change the desktop label to …

Fix mismatching button label for speech recognition

---

package.json
webpack.config.js
yarn.lock

React has a feature (Fast Refresh) that applies code edits in-place without reloading the entire app.
This feature is turned on for Android and iOS by default, but it wasn't enabled by Expo for web. In this PR, I followed [this guide](https://forums.expo.dev/t/enabling-fast-refresh-with-expo-web-in-2022/63102) to turn it on.
Here's a demo. The key thing is that editing code no longer reloads the entire page on the web:
https://github.com/bluesky-social/social-app/assets/810438/e323f4c2-06d1-47c6-b1f8-b71ea0bf23f3
In the future Expo will have this by default, but Evan says it would require moving to Expo Router V2 (and Metro). For now I think this will do.

Enable Fast Refresh for web

---

src/view/com/post-thread/PostThread.tsx

This affects the positioning of posts when viewing a thread
- Fixes the minimum index to match some changes to rendering
- Updates android to use the RN tool now that support has landed
In general this will greatly improve the thread scroll-positioning so that things dont jump around after load

Fix thread positioning on load

---

.github/workflows/lint.yml

Currently, running `yarn` on main produces a change in `yarn.lock`. This means that our CI doesn't check whether the lockfile is matching what's in `package.json`.
I think this flag is supposed to do that. I'd like to add it, <s>verify it'll fail the CI</s> (it doesn't, maybe due to https://github.com/yarnpkg/yarn/issues/5840, but it's still right to have it on), and then merge https://github.com/bluesky-social/social-app/pull/1393 with the fix.

Use frozen lockfile for CI workflows

---

package.json
yarn.lock

Running `yarn` on main produces a change in lockfile now, presumably after the Expo upgrade.
Rather than updating the lockfile I just removed unnecessary overrides.
Verified error box still works.

Remove unnecessary deps from package.json

---

src/view/com/modals/Waitlist.tsx

The text was not visible before so it was hard to know when you joined a waitlist successfully on dark mode.

Fix text color on waitlist join

---

src/view/com/profile/ProfileHeader.tsx

Fix #1388.
Change the spacing of the FollowersButton and FollowsButton to be the same as postsCount.

Unify spacing of FollowersButton and FollowsButton of ProfileHeader

---

package.json

We already leave `android/` and `ios/` gitignored. This means we can use the [clean](https://docs.expo.dev/workflow/prebuild/#clean) workflow ("generally recommended in most cases" per the docs) where `prebuild` _always_ regenerates stuff from scratch. In practice I've run into weird errors that I couldn't resolve otherwise, and this would have caught that. In general it's nice to enforce clean predictable builds.
The downside is that _if nothing has actually changed_ and you ran `yarn prebuild`, it'll take an extra minute for next `yarn prebuild + yarn ios`. If this gets really annoying in practice we can add another script that just does `expo prebuild` but for now I didn't cause I don't know if we'll actually need it.
Let's give this a try?

Use expo prebuild --clean

---

.eslintrc.js
package.json

I tried editing `docs/build.md` but committing it didn't work. Our lint-staged setup calls ESLint on a Markdown file, which breaks it. I've tweaked it so that we only run ESLint on the files that actually can be linted.
As a drive-by fix, noticed a seemingly unnecessary `overrides` option. I've folded it into the main config.

Fix lint-staged not allowing edits to Markdown files

---

bskyweb/templates/base.html
src/view/com/pager/FeedsTabBar.web.tsx
src/view/com/util/Views.web.tsx
web/index.html

This got broken with a "fix" I snuck into the responsive layout, but this finally fixes it for real. (See the comment for an explanation.)
Before:
After:

Fix scrollbar gutters on web

---

.eslintrc.js
package.json
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx
src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/search/Suggestions.tsx
src/view/com/util/PressableWithHover.tsx
src/view/com/util/ViewSelector.tsx
src/view/com/util/Views.web.tsx
src/view/com/util/anim/TriggerableAnimated.tsx
src/view/com/util/layouts/withBreakpoints.tsx
yarn.lock

This adds `eslint-plugin-react` with the recommended rules:
- https://github.com/bluesky-social/social-app/commit/a27c22428e4e3b715ba8441b533f4c3a14364b55 adds the plugin and disables the rules that fail.
- https://github.com/bluesky-social/social-app/commit/a278839c3f47c1d253fb3a93cd59a494261b58ee ([review without indentation changes](https://github.com/bluesky-social/social-app/pull/1412/commits/a278839c3f47c1d253fb3a93cd59a494261b58ee?w=1)) enables [`react/display-name`](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/display-name.md) and fixes the violations. I chose `*Impl` suffix for inner functions so we don't accidentally change the behavior. E.g. if there's a recursive component, you pretty much always want the outer function.
- The purpose here is to …

Add ESLint React plugin

---

src/view/com/posts/FeedItem.tsx
src/view/com/util/moderation/ContentHider.tsx

Fixed an issue where Posts could overflow outside their content box
Adds `overflow: hidden` to Posts and post content
Previous behavior:
Fixed behavior:

💅 disallow overflow outside of post content area(s)

---

src/state/models/media/image.ts

Fixes #1263
Previously, opening the crop tool had 1:1 selected by default. So if you opened it and pressed Done without changing anything, it would format the image as 1:1.
After this change, None is selected by default. So if you open the crop tool and press Done without changing anything, nothing will change.

Set crop mode to None by default

---

__tests__/lib/string.test.ts
src/lib/strings/time.ts

Right now, posts can appear to be from the future with a negative time difference (i.e. -3s appears). This change defines 'NOW' as less than 5 seconds old, and returns 'now' in that case.
It's not clear how localisation is handled - this may need translation.

Update time.ts to handle very small or negative time differences

---

src/view/com/composer/text-input/TextInput.web.tsx

Hi, something I’ve found quite jarring in the implementation of the post composer is that pressing Cmd-Enter (or Ctrl-Enter) causes a newline to be entered into the input area, which always makes me double-guess if that newline has made it into the post I’ve just posted. (It never does, but the visuals speak to me otherwise.) So here I return `true` in the event handler to prevent this from happening :)
(PS. I’ve read your contribution guidelines but thought this was a small enough patch that I should be fine submitting it as-is.)

post composer: inhibit Cmd-Enter from inputting newline

---

package.json
yarn.lock

Some users reported that their moderation settings were refusing to change. We looked into the accounts and found duplicate preference values.
This PR bumps @atproto/api@0.6.12 which includes https://github.com/bluesky-social/atproto/pull/1575 an update that should correctly handle conflicts in user preferences

Fix to user preferences read/write

---

src/view/screens/Notifications.tsx

Reverts bluesky-social/social-app#1340
This change really hasn't been working, and I think it does the wrong thing relative to the request. I think what people want is for the notification _counter_ to clear. What 1340 did was clear the unread state entirely, making you lose track of new items.
I spent a couple minutes seeing if I could just update the counter, but it wasn't super easy. If you call `updateSeenNotifications` then any notifications you load during pagination will start to come in as "read" even if they're new. So the solution to this is going to have to be a new approach to the unread counter that divorces itself from the server state. It's doable, but not in time for today's release, so I want to revert this change.

Revert "Fix 1338 mark notifications read with timeout and on app state change"

---

src/state/models/content/list.ts
src/view/screens/ProfileList.tsx

Fixes #1359 
Right now I made it so that the share button shares the link of the mute list with the `did` instead of the `handle`
However, we should probably fix the `getLists` endpoint on the graph service to resolve when using handles as well as dids for a better user experience since some users might just copy the link from the address bar on browsers

Fix #1359 share mute list link with did not handle

---

src/view/com/util/moderation/PostAlerts.tsx

Fix 1365 wrap impersonation text

---

src/lib/api/feed-manip.ts
src/state/models/feeds/posts.ts
src/state/models/ui/preferences.ts
src/view/com/posts/FeedSlice.tsx
src/view/screens/PreferencesHomeFeed.tsx

Adds a preference for filtering replies to only show between followed users. Open to suggestions on code _and_ UI, this is a bit yolo.

Add a preference for showing replies among followed users only

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

This drops it down to the expanded view:
While for others you just use the menu:

Drop all the in-post translate links except when expanded

---

eas.json
package.json

Sets us up to build APK bundles for install on real Android devices.
Log into Expo, then run:
```
yarn build:apk
```
You can download the build artifacts from the Expo dashboard.

add build:apk and apk config

---

src/lib/api/feed-manip.ts

Fixes https://github.com/bluesky-social/social-app/issues/1371
Originally thought this was a backend thing, but actually we were just mistakenly threading the reposted `reply` if the feed response didn't also contain the plain-ol' `reply` itself. See below for example:
Whereas in the posts-and-replies view we get both the plain-ol' reply _and_ the reposted reply, so it doesn't get threaded.
So the fix looks like this (see last two posts in feed):

don't thread a self-repost of a self-reply

---

package.json
src/platform/polyfills.ts
src/platform/polyfills.web.ts
yarn.lock

Some users are on browsers that don't yet support `findLast`. This fixes that with a shim.
Closes  #1459

Add findlast shim for outdated browsers

---

src/view/shell/Drawer.tsx

Should help address #1297 and #1306
This PR wraps everything in the drawer in a scroll view except the footer section, and ensures that the footer buttons don't overflow the drawer and cover UI in the main feed view.

improve drawer reflow for large text

---

src/lib/hooks/useAuxClick.ts
src/lib/hooks/useAuxClick.web.ts
src/view/com/posts/Feed.tsx
src/view/com/util/Link.tsx
src/view/shell/index.web.tsx

Addresses https://github.com/bluesky-social/social-app/issues/650
This is a PoC that attempts to handle middle mouse click on post feed items and opens the post in a new tab. This is default behavior when using `a` tags but on non-a tags, links only open in new tab on safari (which is an anomaly and will probably be patched down the road on safari too).
I'd imagine the handler will have to be added on other wrappers where posts are rendered.
More details on the default web-supported handler for this event https://github.com/facebook/react/pull/11571
https://github.com/bluesky-social/social-app/assets/1919066/33a3ae5f-dcb6-4a2b-965b-b3fa5cd5eaa0

:bug: Handle middle mouse click on feed list items

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/hooks/useDoubleTapToZoom.ts
src/view/com/lightbox/ImageViewing/hooks/usePanResponder.ts

- Fixes #1275 for Android.
- Fixes [this TODO](https://github.com/bluesky-social/social-app/blob/859588c3f63949182acf3ca800b0229dd5e1d88e/src/view/com/lightbox/ImageViewing/hooks/useDoubleTapToZoom.ts#L39) for iOS.
On Android, we were zooming in way too hard (#1275). I tried to fix it by zooming in "less", but I wasn't sure what scale and how to calculate the new position in a way that would feel intuitive. I studied what different apps do using a variety of different image sizes ([test thread](https://bsky.app/profile/danabra.mov/post/3k7h5zss7bp2g)) and settled on the following principles that are mostly inspired by the iOS Photos app:
- Try to zoom in enough that black bars (if present) disappear, i.e. scale to fill.
- Try to avoid zooming in _too_ little. (I settled on 2x minimal …

Make "double tap to zoom" precise across platforms

---

src/state/models/ui/preferences.ts
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/index.ts
src/view/screens/PostThread.tsx
src/view/screens/PreferencesHomeFeed.tsx
src/view/screens/PreferencesThreads.tsx

Adds an experimental "Tree View" mode to thread rendering. If this is well-received, we can make this a toggle, perhaps even within the thread UI (not just buried in settings).

Tree view threads experiment

---

src/view/com/lightbox/ImageViewing/hooks/usePanResponder.ts
src/view/com/lightbox/ImageViewing/utils.ts

Follow-up to https://github.com/bluesky-social/social-app/pull/1482.
**Supposed to be no behavior changes.** Let's just get rid of this helper.
This makes it more obvious which methods exist and how we're implementing the existing ones.
(I suspect we'll want to mess with this recognizer more in the future, e.g. to fix the "stuck" pinching on Android).

Inline createPanResponder

---

src/view/com/composer/Composer.tsx

Small visual improvement that I've been wanting to get done forever. The information line is now anchored on the bottom (no more reflowing layout) and looks a smidge nicer

Nicer 'post processing status' in the composer

---

src/state/models/ui/my-feeds.ts
src/view/screens/CustomFeed.tsx
src/view/screens/Feeds.tsx
src/view/screens/Profile.tsx

- Bold the saved feeds on mobile (looked wrong to me)
- Better loading state of saved feeds (placeholders)
- Add soft reset to the feeds page (tapping on the # when already open now reloads)
- Show feed descriptions in profile listings
- Add an "About this feed" button to the dropdown to see the details
I'm not in love with the "about this feed" UI but it's enough for now.

Feeds tab fixes

---

src/view/com/lightbox/ImageViewing/components/ImageDefaultHeader.tsx
src/view/com/lightbox/ImageViewing/index.tsx

The lightbox top bar (which contains the close button) was eating touch even outside the close button tap area.
This was confusing because the top bar is invisible.
Let's fix it so that it doesn't eat touch.
Verified close button still works.
https://github.com/bluesky-social/social-app/assets/810438/f8039da1-341b-44e0-9d92-0e84b5b91432
https://github.com/bluesky-social/social-app/assets/810438/97fde8b3-5d30-4112-a4c9-f0ad0d717a7b

Allow touch at the top of the lightbox

---

package.json
yarn.lock

Assuming that there were no breaking/significant changes in `@atproto/api` between these minor versions.
This clears the old `@atproto/nsid`, `uri`, and `identity` packages out of the dependency tree here.

yarn: bump @atproto/api to remove redundant deps

---

src/view/com/lists/ListItems.tsx

Turns out the `RichText` constructor runs `sort()` on the facets parameter without slicing first (whoops) and this makes mobx mad, so this fixes that

Fix to the list header rich text rendering

---

src/view/com/composer/Composer.tsx

QAing the update in #1472, I still wasn't happy with the outcome. This update goes even less intrusive.
|Before|After|
|-|-|
|<img width="646" alt="CleanShot 2023-09-20 at 12 29 59@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/081e1241-7bef-44f4-96bf-68244f36284d">|<img width="627" alt="CleanShot 2023-09-20 at 12 29 00@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/08f061d1-4e53-4d20-9602-0a99397ba4be">|

Even less intrusive status line for posts

---

src/view/screens/PostThread.tsx

There's a standing issue where the "minimal shell mode" can sometimes get triggered when the thread screen is viewed. I've not been able to debug the cause of this. This can lead to an ugly situation where the "Reply prompt" hovers awkwardly above the bottom of the screen.
We should fix the root issue, but in the meantime let's at least not leave the ugly floating bar. Users can still reply by tapping the comment icon.

Dont show the reply prompt if minimal shell mode triggers (hackfix)

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx

Reduces the horizontal space usage (for mobile) and introduces borders between subthreads to help clarify the discussion
|Before|After|
|-|-|
|<img width="1202" alt="CleanShot 2023-09-20 at 11 59 07@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/11c10406-a54a-46d1-8ed2-4d900d7a7c20">|<img width="1200" alt="CleanShot 2023-09-20 at 11 57 43@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/43ed3812-d612-491a-afc6-8f3e44448c36">|
|Before|After|
|-|-|
|<img width="329" alt="CleanShot 2023-09-20 at 11 58 40@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/f48ac9ea-3338-4f45-a0e3-9fb83fa5f548">|<img width="323" alt="CleanShot 2023-09-20 at 11 58 16@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/3aa11d03-9e49-41ea- …

More narrow treeview and borders to separate new subthreads

---

src/lib/hooks/useFollowDid.ts
src/view/com/modals/ProfilePreview.tsx
src/view/com/profile/FollowButton.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx

Adds a section to `ProfileHeader` that displays the results of `getSuggestedFollowsByActor`.
- fetches fresh results each time you open this section
- section is opened and closed automatically upon follow/unfollow
- section can be toggled separately using new button
- not rendered on preview
- shows skeleton UI when loading
https://github.com/bluesky-social/social-app/assets/4732330/e3f874a3-e7b0-4b74-a800-fbe1b1e419d0

add suggested follow section to profile header

---

src/view/com/modals/InviteCodes.tsx

This PR introduces dynamic, responsive styles to the InviteCodes modal, improving its layout on tablet and desktop devices.
- Utilization of the `useWebMediaQueries` hook to detect the device type and adjust styles accordingly.
- Addition of a new style, `btnContainerDesktop`, which modifies the top margin when the device is a tablet or desktop.
These updates align the InviteCodes modal with the layout of the App Passwords page, providing consistency across different components.
Please see the attached before and after screenshots for a visual comparison of the changes.

Updates InviteCodes modal to use dynamic/responsive styles on web

---

.detoxrc.js
__e2e__/mock-server.ts
__e2e__/tests/composer.test.ts
__e2e__/tests/home-screen.test.ts
__e2e__/tests/invite-codes.test-skip.ts
__e2e__/tests/merge-feed.test.ts
__e2e__/tests/mute-lists.test.ts
__e2e__/tests/profile-screen.test.ts
__e2e__/tests/search-screen.test.ts
__e2e__/tests/self-labeling.test.ts
__e2e__/tests/shell.test.ts
__e2e__/tests/thread-muting.test.ts
__e2e__/tests/thread-screen.test.ts
__e2e__/util.ts
jest/test-pds.ts
src/App.native.tsx
src/lib/constants.ts
src/view/com/modals/ProfilePreview.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/search/HeaderWithInput.tsx
src/view/com/testing/TestCtrls.e2e.tsx
src/view/com/testing/TestCtrls.tsx
src/view/com/util/forms/ToggleButton.tsx
src/view/screens/PreferencesHomeFeed.tsx

- Adds a `<TestCtrls>` component which only renders in the e2e sim build and provides some fast actions, dramatically improving the execution time of tests.
- Disables the invite codes test temporarily due to the drawer crash issue.
- Adds mergefeed tests.

Test suite improvements & tests for the mergefeed

---

src/view/com/util/fab/FABInner.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx

The floating buttons were positioned inconsistently across platforms. This fixes that.
**Web**
|Before|After|
|-|-|
|<img width="622" alt="CleanShot 2023-09-20 at 19 00 03@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/c551801c-f559-4824-97a9-951f7c957643">|<img width="626" alt="CleanShot 2023-09-20 at 18 58 57@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/35ad7563-7d89-4310-9d6a-f5411afe9cb4">|
**iOS**
|Before|After|
|-|-|
|<img width="884" alt="CleanShot 2023-09-20 at 19 03 28@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/e2e7fc68-14e1-40b8-a637-04b45546512a">|<img width="888" alt="CleanShot 2023-09-20 at 19 04 56@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/2bfac664-b44e-421c-ba87-e35f893b8a01">| …

Improve consistency of floating button positioning

---

.detoxrc.js
__e2e__/mock-server.ts
__e2e__/tests/composer.test.ts
__e2e__/tests/home-screen.test.ts
__e2e__/tests/invite-codes.test-skip.ts
__e2e__/tests/merge-feed.test.ts
__e2e__/tests/mute-lists.test.ts
__e2e__/tests/profile-screen.test.ts
__e2e__/tests/search-screen.test.ts
__e2e__/tests/self-labeling.test.ts
__e2e__/tests/shell.test.ts
__e2e__/tests/thread-muting.test.ts
__e2e__/tests/thread-screen.test.ts
__e2e__/util.ts
jest/test-pds.ts
src/App.native.tsx
src/lib/api/feed-manip.ts
src/lib/api/feed/merge.ts
src/lib/constants.ts
src/state/models/feeds/posts.ts
src/state/models/ui/preferences.ts
src/view/com/modals/ProfilePreview.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/search/HeaderWithInput.tsx
src/view/com/testing/TestCtrls.e2e.tsx
src/view/com/testing/TestCtrls.tsx
src/view/com/util/forms/ToggleButton.tsx
src/view/screens/PreferencesHomeFeed.tsx

During QA I found that the merge feed was giving the wrong mix of following & custom feeds. This turned out to be because the sampling between these sources occurred prior to the client-side filters. With this PR, a prepass of the filtering is added, causing the sample rate to be much more accurate. I also bumped the following fetch count to offset the loss of posts due to that filter.

Prefilter the mergefeed to ensure a better mix of following and custom feeds

---

src/view/com/composer/Prompt.tsx
src/view/com/post-thread/PostThreadItem.tsx

Another iteration after a night of QA. We need to balance horizontal screen usage with overall visual clarity and appeal. With this update, I modified the immediate children to show as with normal linear posts, but then further children go into the thread mode. I think this feels more natural.
**Desktop**
|Before|After|
|-|-|
|![CleanShot 2023-09-21 at 10 56 05@2x](https://github.com/bluesky-social/social-app/assets/1270099/230f007b-854a-4a63-8700-9c118a43dc68)|![CleanShot 2023-09-21 at 10 55 22@2x](https://github.com/bluesky-social/social-app/assets/1270099/fdf7f8a0-78c6-4af5-a42c-973406544753)|
**Mobile**
|Before|After|
|-|-|
|![image](https://github.com/bluesky-social/social-app/assets/1270099/05952b05-d04a-40a8-8b79-648f1e216b70)|![image](https://github.com/bluesky-social/social-app/as …

Tune the treeview mode to use larger immediate-children

---

src/view/com/util/load-latest/LoadLatestBtn.tsx

Stupid bugfix, desktop doesnt use minimal shell mode so it shouldnt move the load latest btn around

Dont reposition load latest button on desktop

---

src/view/screens/PostThread.tsx

I noticed the fix in https://github.com/bluesky-social/social-app/pull/1495 was causing the reply prompt to disappear more often than I expected. That's due to a timing issue which this observer wrapper will correct by reacting to changes to minimal shell mode.

Wrap the post thread screen in an observer

---

src/view/com/util/forms/DateInput.web.tsx

Some users were struggling with the date localization of the freeform web input, so this switches us to using `<input type="date">`. Tested on FF, Chrome, and Safari on desktop. Caniuse gives good support for the element and for `valueAsDate` on all browsers (including mobile).
Dark mode doesnt show the date picker icon. Frustratingly that would require CSS changes and I don't really want to bother with that right now.

Switch the date input web version to the date-input web control

---

src/view/com/util/forms/PostDropdownBtn.tsx

Doesn't make a lot of sense for the author of a post to report their own post and with the dropdown growing ever so slightly, getting rid of an unnecessary item feels nice.

:lipstick: Remove report option on my own post

---

src/view/com/posts/FeedItem.tsx

(Extra "Reposted by" text just for testing)
Looks like this now:
Prev:

fix 'Reposted by' text overflow

---

src/view/screens/Profile.tsx
src/view/shell/desktop/LeftNav.tsx

I found that the behaviour of the composer where it prefills a mention when viewing a user's profile was producing incorrect behaviour when viewing a user with an invalid handle. This manifests in two bugs:
mobile: composer is prefilled with `@invalid.handle`
web: composer is prefilled with `@did:plc...`
This is because the compose button simply looks at the URL - this would happen when viewing a profile with a valid handle too if the DID URL is used
For the first bug, I simply added a check for `handle === 'handle.invalid'`. For the second one, I added a check for `handle.startsWith('did:')` - this is not a great solution because this does not handle accounts with valid handles viewed with their DID in the URL, but it's better than the current, broken behaviour.
Profile used for testing: …

Composer prefilled mention - handle edge cases with DID URLs and users with invalid handles

---

src/view/screens/Profile.tsx
src/view/shell/desktop/LeftNav.tsx

@mozzius pointed out two issues with our auto-mentioning of users when creating a new post:
- from the mobile new post button, if the user's handle was invalid we'd end up using `@handle.invalid`
- from the desktop nav, we didn't have profile UI state to check, so we ended up using the user's did
~The first is a real bug, the second technically works, but isn't a great experience.~ Edit: ope, for some reason I thought we did support linking to dids 🤔 
I pushed a commit to resolve the profile data from the cache within the desktop nav. This is just a hit to `AsyncStorage` so should typically be fast enough that users won't notice the await.
Invalid handle test profile: http://localhost:19006/profile/did:plc:3nqrhu5mthmias3zc4a2ovzj
Profile with did in url (Paul): …

Improvements to auto-mentioning users from their profiles

---

src/lib/api/index.ts
src/state/models/media/image.ts
src/view/com/util/images/AutoSizedImage.tsx
src/view/com/util/post-embeds/index.tsx

Closes #1392 
- Fixes an issue with image cropping on android that would stretch the image
- Adds the `aspectRatio` to images in posts and uses that in rendering as a hint

Improve image cropping on android and introduce aspect ratio field

---

src/view/shell/desktop/Feeds.tsx
src/view/shell/desktop/RightNav.tsx

Users with a lot of feeds were having their right nav overflow. This solves it by setting a max height and scrolling behavior

Handle long feed listings on the right nav with scrolling

---

package.json
src/lib/strings/helpers.ts
src/state/models/root-store.ts
src/state/models/session.ts
src/state/models/ui/reminders.ts
src/state/models/ui/shell.ts
src/view/com/modals/ChangeEmail.tsx
src/view/com/modals/Confirm.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/modals/VerifyEmail.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/Button.tsx
src/view/screens/Settings.tsx
yarn.lock

- Adds email verification flow
- Adds email change flow
- Adds a reminder on app load to verify email if not verified. Reminder only shows once a day and shards the users into 2 days of the week to get it, to avoid nagging too much and to avoid everybody running the flow all at once.

Email verification and change flows

---

src/view/shell/desktop/LeftNav.tsx

Aligns with back button when visible, and generally looks less wonky in my opinion.
Also just about lines up with the icons for each page.

Small PFP on desktop

---

docs/build.md
google-services.json.example

As an external contributor trying to build the app for the first time on Android throws a few errors due to a missing google-services.json.
This PR adds an example google-services.json file that users can use as a base to build the app on Android. We can't simply use an empty JSON since Google enforces validation on specific fields within it. 
Note: all values used in this file are mocked and are not related to any existing Firebase projects

Add example google-services file

---

src/lib/hooks/useOnMainScroll.ts
src/platform/detection.ts
src/view/com/auth/SplashScreen.web.tsx
src/view/com/composer/photos/OpenCameraBtn.tsx
src/view/com/composer/photos/SelectPhotoBtn.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/Html.tsx
src/view/com/util/Link.tsx

The creation of this Pull Request was motivated by the need to address a particular issue, as referenced in the issue https://github.com/bluesky-social/social-app/issues/1268. 
After further investigation, I found that when users adjust the size of their desktop browser, [a specific variable `isDesktopWeb` will erroneously return `false`](https://github.com/bluesky-social/social-app/blob/3c4899b3c4ae55285559215023a25e365c9f4e30/src/view/com/util/Link.tsx#L225). At the same time, I also noticed that `isDesktopWeb` is used in many places in the project, which may cause some style issues because `isDesktopWeb` does not perform responsive updates.
Then I found [`useWebMediaQueries` hook](https://github.com/bluesky-social/social-app/blob/764c7cd5694a41c98d8543b68d7791fa90db4291/src/lib/hooks/us …

Improve Device Detection For Better Responsiveness

---

src/view/com/modals/EditProfile.tsx
src/view/com/modals/Modal.web.tsx

Supersedes #1554 
- Stops the modal from going entirely to the top/bottom edges
- Widens to modal to match the width of the content area
- Gives a little more space in the profile editor description

Small sizing tweaks to the web modal

---

src/view/com/lightbox/Lightbox.web.tsx

A recent upgrade to react-native-web changed how `accessibilityRole` gets interpreted and turns it into a `<button>` when the value is `"button"` which then broke the selectability of the alt text in the lightbox. This fixes that.

Fix alt text selectability in lightbox on web (close #1548)

---

src/view/com/modals/VerifyEmail.tsx

The email verification reminder is annoying enough, we might as well make it look good when you get it. This PR adds an SVG illustration.
(Not as pretty IMO but it'll do)

Add an illustration to the email verification reminder

---

src/state/models/content/post-thread.ts
src/view/com/post-thread/PostThread.tsx

I was noticing some cases where quote posts would position incorrectly after tapping them and loading their thread screen. I believe this is because the index passed to `maintainVisibleContentPosition` is correct when rendering replies but not when rendering toplevel posts (you have to do some annoying component counting to establish the index).
When viewing a toplevel post you don't need to do any scroll repositioning, so this PR checks that and disables it for non-replies.

Fix: to post positioning after thread load

---

src/view/shell/bottom-bar/BottomBarWeb.tsx

React navigation's `useNavigationState()` doesn't adhere to its type signature. It will in some cases provide `undefined` to the closure it's given. Most of our code is written to defend against that -- except for the change in this PR.
Sentry REACT-NATIVE-9D reported that `getCurrentRoute` is being given an undefined. The stack isn't definitive given our usage but matches with this, the one place we're not defending against the undefined value.

Fix a reference error in bottombarweb

---

src/view/com/search/Suggestions.tsx

The search page's user discovery algorithm is currently a mix of two things:
1. Suggested follows from the server
2. A client-side crawl of the FOAFs
2 is temporary until we can get some better facilities in the server and it performs very poorly. We've been historically waiting for both to finish to render something. Breaking them up and rendering the server's suggestions first makes things much better.
https://github.com/bluesky-social/social-app/assets/1270099/e06cbd50-29a8-487d-a586-a4c7ccf1c331
https://github.com/bluesky-social/social-app/assets/1270099/2e23bcbf-0f7e-4975-9d45-352940637291

Improve time to content in the search page

---

src/lib/constants.ts
src/state/models/discovery/onboarding.ts
src/state/models/feeds/posts.ts
src/state/models/ui/preferences.ts
src/state/models/ui/reminders.ts
src/view/com/auth/onboarding/RecommendedFeedsItem.tsx
src/view/com/posts/Feed.tsx
src/view/com/posts/FollowingEmptyState.tsx
src/view/com/posts/FollowingEndOfFeed.tsx
src/view/com/search/HeaderWithInput.tsx
src/view/com/util/ErrorBoundary.tsx
src/view/screens/Home.tsx

Closes #1601. I started fixing issues and couldn't stop finding new ones, turning this into a bit of a bloated PR.
- Feed is now automatically refreshed after onboarding to ensure the content is loaded
- Following feed now has a CTA if the user reaches the end, which is more possible than you'd think because `getTimeline` only goes back a certain amount.
- Improved detection of the "end of feed" condition (no posts returned)
- Stop autofocusing the search input when going to that tab. This has been a long-standing request but it's important for the empty feed state, thus I'm rolling it into this.
- Fixes to preference management to optimize the behavior a bit and avoid inflight changes clobbering each other
- Small additional fixes
- Fixed the button to go to feeds on mobile from empty …

Onboarding & feed fixes

---

src/state/models/me.ts
src/view/com/modals/InviteCodes.tsx
src/view/screens/Settings.tsx
src/view/shell/Drawer.tsx
src/view/shell/desktop/RightNav.tsx

Invite codes flash an untrue value of "0" before they load. 
Instead display a loading placeholder before they get fetched. Make invite codes nullable in the store to represent unfetched state instead of defaulting to an empty array.
Before:
https://github.com/bluesky-social/social-app/assets/6214736/d9216c77-80fd-4162-8dd0-11472cbc0616
After:
https://github.com/bluesky-social/social-app/assets/6214736/fc7e21c2-0af5-4359-8254-1326c2374bdd
(The border-radius of the loading placeholder is now bigger than in the video to make it into a pill, matching loading placeholders in profile view:)

Fix invite codes flash on desktop, use loading placeholder

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/lightbox/ImageViewing/utils.ts

The way we use `Animated.Value` in the lightbox is wrong. I don't know if we have any cases where it immediately manifests in bugs, however it's hard to add code to the lightbox without breaking it. Specifically, the issue is with code like this:
```js
function SomeComponent() {
const value = new Animated.Value(0)
```
This is not correct because it will be recreated and destroyed on every render. So any state update within the same component will screw up the in-progress animation or gesture. One easy way to simulate it is to add code like this:
```js
const [x, setX] = useState(0)
useEffect(() => {
const id = setInterval(() => setX(x => x + 1), 50)
return () => clearInterval(id)
}, [])
```
This would force the component to re-render every 50 milliseconds.
This breaks the zoom gesture — …

Fix animations and gestures getting reset on state updates in the lightbox

---

src/lib/themes.ts

Closes #1590
Shrinks the font a bit on highlighted posts. This is a design decision, so we gotta just look at the before/after and decide if we want to make this move.
https://github.com/bluesky-social/social-app/assets/1270099/1525b7a4-7102-4aeb-85d3-58072f083cbe
https://github.com/bluesky-social/social-app/assets/1270099/e3cd131c-4477-4b9d-aa58-bdca106f2754

Slightly smaller highlighted post text

---

src/lib/hooks/useFollowProfile.ts
src/state/models/cache/my-follows.ts
src/state/models/content/profile.ts
src/state/models/discovery/foafs.ts
src/state/models/discovery/suggested-actors.ts
src/state/models/discovery/user-autocomplete.ts
src/state/models/feeds/posts.ts
src/state/models/invited-users.ts
src/state/models/lists/likes.ts
src/state/models/lists/reposted-by.ts
src/state/models/lists/user-followers.ts
src/state/models/lists/user-follows.ts
src/state/models/ui/search.ts
src/view/com/auth/onboarding/RecommendedFollowsItem.tsx
src/view/com/notifications/InvitedUsers.tsx
src/view/com/profile/FollowButton.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx
src/view/screens/SearchMobile.tsx
src/view/shell/desktop/Search.tsx

Uses a client-side cache of the followed users to prioritize the user's follows in autocomplete search (seach page, mentions).
Should replace this with serverside as the fetch of follows has to happen in pages (of 100) and stops at 1k, all of which adds more load than we want. Still, these results are much better
https://github.com/bluesky-social/social-app/assets/1270099/8abb6798-507d-4c56-a898-766684fa46e6
Notice how much I'm struggling to find ppl I know
https://github.com/bluesky-social/social-app/assets/1270099/3d0a2a2a-15ae-4af8-bfe7-431f6f4274f7
Eat viola, I'm immediately finding my friendos

Improve typeahead search with inclusion of followed users (temporary solution)

---

src/lib/api/index.ts
src/view/com/composer/text-input/TextInput.web.tsx

The richtext library runs a sanitization pass that reduces excess newlines. Trimming doesnt really add anything and sometimes breaks people's posts, so this PR stops doing that.
EDIT: tweaked to still trim end, the web composer sticks empty space on the end if we dont

Dont trim before posting (close #1621)

---

src/view/com/post-thread/PostThread.tsx

Recent UI change lost the bottom spacing during the loading state, which causes the UI to get covered by the bottom bar. This fixes that.

Fix: add padding to the spinner bottom while loading threads

---

src/view/com/lightbox/ImageViewing/index.tsx

This logic is inherited from https://github.com/jobtoday/react-native-image-viewing/blob/master/src/hooks/useRequestClose.ts.
I can't tell what this logic is for. I think it's not necessary so I'd like to delete it. If it turns out necessary, we'll learn something interesting (and then add it back).
Concretely, we were _first_ setting opacity to 0, then updating the state to hide the modal, then immediately setting opacity back to 1. This feels like the kind of code that would be there to trigger some kind of an animation — but we currently have none, and also setting opacity going "from 0 to 1" doesn't make sense on closing the lightbox. Another guess is maybe the author was hoping to flush the opacity change first (to quickly hide the modal) and then do potentially more expensive state …

Remove unnecessary opacity logic

---

src/state/models/ui/reminders.ts

Close #1657
> We have it at once a week right now. In hindsight I think that was the wrong call, because some people simply won't want to verify and nagging them endlessly won't fix that. I'm going to modify it to ask once, and store than in device storage. That'll still lead to multiple prompts (switching devices, account storage clearing) but it'll be better.
> Another downside to this approach to be aware of is that you won't get prompted when you create a second account. We'll ultimately want to move this server-side.

Only prompt users once to verify email (according to local storage)

---

src/view/com/lightbox/ImageViewing/hooks/useImageDimensions.ts
src/view/com/lightbox/ImageViewing/index.tsx
src/view/com/lightbox/Lightbox.tsx

No behavior change, just cleaning up before more significant changes.
- https://github.com/bluesky-social/social-app/commit/b274de6757aa86ed4e4102371c45b589fc6a6af1: Removes support for passing a number as image source. This used to be a lie in the types, and we don't use this feature anyway. (In the original library, this was used to support showing local images from disk.) Also removes the `keyExtractor` prop which we're not using anywhere.
- https://github.com/bluesky-social/social-app/commit/2464c8fca8ed84afd820913c82da0b69a30aa56a: Renames the prop to clarify it's only used to seed the initial state.
- https://github.com/bluesky-social/social-app/commit/bd7ef0cec5ed9c0c5b6be8ff69a9aa2ac0b5a513: Renames the state variable.

Drive-by lightbox refactors

---

src/view/com/lightbox/ImageViewing/index.tsx

We got one here already:
https://github.com/bluesky-social/social-app/blob/d47ff542dafdb691fd492845db956dd629122a9b/src/view/shell/index.tsx#L80
The layering there is correct because we need the lightbox to appear on top of modals. E.g. if you "preview" a profile by clicking on it in feed, and then you click on the avatar, the lightbox should appear on top of the profile preview sheet.
It's unclear what the duplicate modal container _inside_ the lightbox is for. Maybe it's in case we trigger a modal inside a lightbox. However, we don't seem to have any cases like this now. And it seems confusing to have two of the same modal open regardless — if we wanted to support that, we should do this with some stateful layering in the top shell instead.
For now let's remove this.

Remove duplicate modal container

---

src/state/models/cache/my-follows.ts
src/view/shell/desktop/Search.tsx

Noticed that the typeahead search improvements weren't working consistently on desktop's search. Turns out it's because the autocomplete setup call wasn't getting hit, meaning the fetch wasn't occurring in all cases.

Fix: fetch follows on desktop search for typeahead

---

src/view/com/modals/ChangeEmail.tsx
src/view/com/modals/VerifyEmail.tsx

The keyboard was causing a pad to obscure the inputs
Turns out this was a subtle dynamic with bottom-sheet. When we're using bottom-sheet (aka snappoints isn't set to 'fullscreen') then we want to use the bottom-sheet textinput and scrollview, as we were previously doing. However! Those components handle the keyboard visibility dynamic, so we _dont_ want to use `<KeyboardAvoidingView>` in those scenarios. The KAV was the cause of the extra padding.

Fix keyboard double pad issue in email change & verify modals

---

__tests__/lib/strings/url-helpers.test.ts
src/lib/strings/url-helpers.ts
src/state/models/root-store.ts

Closes #1652
Updates the link-warning interstitial to only trigger for `bsky.app` links if the richtext represents itself as another URL.

Only warn on links to bsky.app if it represents itself as another url

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx

This removes a bunch of hacks we've done before to make individual image gestures work with the wrapping scroll view.
The problem was that the wrapping scroll view was overly sensitive (e.g. picking up pinches) and there was no good way to control that or to coordinate gestures. Here I'm replacing `ScrollView` (which we used via `VirtualizedList`) with `react-native-pager-view` which we already use in the project.
In my experience testing the lightbox, `react-native-pager-view` feels a lot less flaky on Android and is much better resistant to "spamming" the gallery with swipes and other gestures. Previously the lightbox would sometimes still get "stuck" but I can't get it to do that anymore. It also recognizes pinches more reliably now.
One downside here is that this is also going to use …

Change lightbox to use Pager

---

src/view/com/lightbox/ImageViewing/index.tsx

This removes the last usage of Animated in the lightbox, replaced by Reanimated.
Should be no observable changes except maybe a slightly different spring formula.
I'll take a pass at making the UX itself nicer after, this just aims to preserve the behavior.

Port remaining lightbox code to Reanimated

---

src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx

This has been bugging me for a while.
When we encounter a post with a gallery in feed (or profile — anywhere we display posts), we try to render it without images first, then measure the container's width, and then relayout images based on that width. As a result, there is a noticeable layout shift after the first render — even though the actual layout is entirely dependent on its container and doesn't *even* depend on the image sizes.
This shift is very bad both because it's visually noticeable (the screen always paints first with empty images) and because it screws the perf — everything below has to relayout again.
The fix is to use flexbox instead of manual calculations. I don't actually _know_ flexbox so I had some help from ChatGPT with this. I *might* have uncovered a potential RN …

Fix layout shift for multi-image posts

---

src/lib/hooks/useMinimalShellMode.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/util/load-latest/LoadLatestBtn.tsx

This animation was too jumpy. I believe the reason is that we've set the distance pretty high, but the duration pretty low. So even if the device is powerful, each frame it has to travel "too much" resulting in jerkiness. Additionally, things "going offscreen" always feel jarring — usually this is solved by fading things out.
I've changed the animation to travel a smaller distance over a slightly longer time, plus added opacity.
https://github.com/bluesky-social/social-app/assets/810438/4a74aaa8-fecc-4d7f-a513-4d0c459a218b
https://github.com/bluesky-social/social-app/assets/810438/537f90dc-8bee-4669-995c-bec67afff5c2

Make shell hide/show animation smoother

---

src/view/com/util/load-latest/LoadLatestBtn.tsx

Fixes a crash I introduced in https://github.com/bluesky-social/social-app/pull/1683. The repro is to scroll down on the web in desktop mode. The crash was happening because the animation runtime was iterating over the transforms, and one of them was a string. The fix is to use the RN object style API (which works on the web too).

Fix crash when scrolling down on the web

---

src/view/com/util/ViewSelector.tsx

There's currently a jump whenever we navigate to profile because the tab selector initially renders with zero height.
This regression was initially added in https://github.com/bluesky-social/social-app/commit/e11168f76868daffff06ac2ccb202b83c21dcbfc#diff-94c6bb36a43b7684db3e0fba9c828d055f9c26101bf0837ef16ce8b7b9c1e945R178 as an attempt to use absolute positioning to hide scrollbars.
Later, https://github.com/bluesky-social/social-app/commit/6964382bad7d4d53b7b6f685190c873cda2d100f applied a better fix for that, but the original layout hack was not removed.
This removes the layout hack — fixing the jump.
Thanks to @estrattonbailey for a hint on how to fix this.
Observe the shift.
https://github.com/bluesky-social/social-app/assets/810438/d4484fd1-1bf4-43da-8ac4-3531a1b3c59e
Observe no …

Fix profile layout shift

---

src/view/com/pager/FeedsTabBarMobile.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx

Fixes a regression I introduced in https://github.com/bluesky-social/social-app/pull/1683.
Since we're keeping these in the viewport, we need to disable events on them in the hidden state.
Otherwise, they'd react to taps etc.
Verified they don't react to events anymore while hidden.

Disable events on hidden bars

---

src/Navigation.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/ProfilePreview.tsx
src/view/com/profile/ProfileHeader.tsx

Fixes a bunch of issues that caused the profile preview -> profile transition to be jumpy.
- We now prevent the sheet from being dragged higher than the safe area so that it aligns with the profile screen.
- Fixed the profile preview glimmer — it used to be very misaligned.
- Added an artificial delay during the transition to avoid flicker. (Couldn't find a more reliable way.)
The 200ms delay is consistently enough to avoid flashing the previous screen (fixing an existing bug). It also gives us a chance to load the images — but we should figure out why the images aren't being instantly available in the cache (this is clear if you remove artificial the delay). I wonder if this is also related to them being too large. Left a TODO for this. …

Fix profile preview jump

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx

Closes https://github.com/bluesky-social/social-app/issues/1265.
This makes the lightbox controls (including alt text) toggle on tap, similar to the Photos app behavior:
- Initially, controls are visible.
- A single tap toggles visibility (hide -> show, show -> hide).
- Zooming in (via pinch or double tap) immediately hides controls.
- Once controls are hidden, only tap shows them again (zooming out doesn't).
Note that, of course, two quick taps (double tap to zoom) should not toggle controls there and back.
I've also tweaked the animation to feel softer, similar to https://github.com/bluesky-social/social-app/pull/1683.
It seems like sometimes Reanimated scroll view events just stop working in the iOS simulator. I can't quite pinpoint the pattern. This doesn't seem to happen when I build …

Toggle lightbox controls on tap

---

patches/react-native-pager-view+6.1.4.patch

We have a patch that makes the drawer gesture coexist with feed pagers. However, this patch breaks the overdrag in iOS lightbox. We want to enable this patch only for feed pagers. We could've introduced a prop for this, but conceptually, we really just want to disable the hack when overdrag is on (because it breaks overdrag, and feed pagers don't use overdrag).
By default it's `false`. We only turn it on for the lightbox right now. So this fixes the lightbox.
This does that.
- Verified dragging the drawer still works for the feed pager
- Verified overdrag is fixed for the lightbox.
You'd need to `yarn prebuild` to get the new behavior.

Scope drawer drag workaround to feed pagers

---

src/view/com/util/images/ImageLayoutGrid.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1708.
This change is just for Firefox. I haven't seen any rendering differences on iOS, Android, Chrome, or Safari.

Fix four gallery images for Firefox

---

src/view/com/modals/CreateOrEditMuteList.tsx
src/view/com/modals/EditProfile.tsx
src/view/com/util/UserAvatar.tsx

We render a lot of avatar components. Especially as you navigate around.
All avatar components currently contain these Hooks:
```js
const store = useStores()
const {requestCameraAccessIfNeeded} = useCameraPermission()
const {requestPhotoAccessIfNeeded} = usePhotoLibraryPermission()
const dropdownItems = useMemo(
() =>
// ...
)
```
This seems like a bunch of unnecessary overhead since these are only used for editable avatars. And as the comment says, avatars are only editable when `onSelectNewAvatar` is passed. This only happens at two callsites.
I separate the avatar component into two: `UserAvatar` and `EditableUserAvatar`. See individual commits.
I don't expect this to have a noticeable perf effect so this is just a drive-by refactor for simplicity. That said we should generally try to …

Simplify the avatar component

---

src/view/com/util/Link.tsx

We should try to keep very commonly used components lightweight. E.g. avoid unnecessary Effects and subscriptions. Especially when they don't really "change" since this influences the init cost.
I don't see a reason for Link components to be MobX observers. They do reference the `store` but only to call `store.shell.openModal` and `store.shell.closeModal` so I don't think they require listening to `store` changes.
Clicked around. Links seem to work.
I set up a small logpoint tracking which observers exist on the page
Feed has ~160 observers:
Feed has ~100 observers:

Remove MobX from Link

---

src/view/com/modals/crop-image/CropImage.web.tsx

Fixed CropImage modal aspect ratio buttons visibility in dark mode

---

src/view/com/modals/Waitlist.tsx

Allow Return/Enter key to trigger text input in waitlist
Fixes #1692

1692: Allow Return/Enter key to trigger text input in waitlist

---

babel.config.js
metro.config.js

Inline requires are a (technically not entirely safe) optimization that defers module initialization until an export from that module is actually used in the code. For example:
```js
import { foo } from './foo' // DOES NOT trigger ./foo.js initialization
function doSomething() {
console.log(foo) // TRIGGERS foo.js initialization
}
```
It's enabled in FB apps and is crucial for performance. It's not entirely safe because it relies on modules with exports not having temporal order sensitive global side effects. However, that's best practice anyway.
<s>Not sure if this actually has perf impact for us. Measurements TBD.</s>
Measurements (PROD mid/lower-range Android):
- Logged out start time: 14s -> 9s
- Logged in start time: 16s -> 11s

Enable inline requires

---

src/App.native.tsx
src/Navigation.tsx
src/view/shell/index.tsx

Two separate problems here.
1. We need to provide `initialMetrics` for the `SafeAreaProvider`. Otherwise the first frame is empty. See [here](https://github.com/th3rdwave/react-native-safe-area-context#optimization).
2. Doing that isn't sufficient though because `NavigationContainer`, [for whatever reason](https://reactnavigation.org/docs/navigation-container/#onready), can't render in a single pass. So wait for `onReady` which, as the docs say, is a good place for "hiding your native splash screen". That's exactly what we're doing.
https://github.com/bluesky-social/social-app/assets/810438/794e7b57-0f08-4ba8-83fe-0e8b5c630aef
https://github.com/bluesky-social/social-app/assets/810438/302cd600-fb0f-4cdf-988f-f84c18fae31f
Verified there's no flash on iOS and Android. No behavior changes on …

Fix white flash on startup

---

src/App.native.tsx

This code was originally added in https://github.com/bluesky-social/social-app/commit/ed146a582c140b9a472298390dafbc07bd06cf60 which predates the move to React Navigation (https://github.com/bluesky-social/social-app/commit/56cf890debeb9872f791ccb992a5587f2c05fd9e).
The guide in https://reactnavigation.org/docs/deep-linking/ does not mention using RN `Linking` directly in the setup guide. It implies React Navigation already integrates with it by default (with ability to [override](https://reactnavigation.org/docs/deep-linking/#third-party-integrations) that).
In particular, [here](https://reactnavigation.org/docs/navigation-container/#linkinggetinitialurl):
>By default, linking integrates with React Native's Linking API and uses Linking.getInitialURL() to provide built-in support for deep …

Remove redundant linking listeners

---

src/Navigation.tsx

This builds on https://github.com/bluesky-social/social-app/pull/1756.
Normally, inline requires already ensure that components' modules only initialize when they actually get used in JSX. However, this navigation file references all the screens in its JSX even though only few of them are actually rendered at a time.
<s>To solve this, we create one level of indirection. Instead of referencing component functions during render, we wrap them into `React.lazy` that would immediately resolve (so there is no async gap). This gives us lazy module initialization.</s>
I'm a clown, React Navigation [already supports this](https://github.com/bluesky-social/social-app/pull/1763#issuecomment-1783260213) so I just changed to use their `getComponent` API.
As a result, we only load the modules that are …

Initialize screen modules lazily

---

babel.config.js
metro.config.js

We currently rely on ESM -> CJS being compiled by Babel. This comes with some downsides. 
I've tried using Metro's experimental built-in `import` / `export` setup and it seems to work.
Here's what this gives us.
In https://github.com/bluesky-social/social-app/pull/1756, we enabled inline requires. However, initialization logs show [all of these modules being prematurely initialized](https://github.com/bluesky-social/social-app/blob/6c11c0b81de34a486df9c67d8f04d0d2050ce9b3/src/view/com/modals/Modal.tsx#L13-L37) even though they're not being used. This is because Babel compiles `import *` to this:
```js
var ConfirmModal = _interopRequireWildcard(_$$_REQUIRE(_dependencyMap[9], "./Confirm"));
var EditProfileModal = _interopRequireWildcard(_$$_REQUIRE(_dependencyMap[10], "./EditProfile"));
var …
```

Let Metro handle import/export instead of Babel

---

src/view/com/util/images/AutoSizedImage.tsx

setting the alt tag on the parent component (the `Pressable`) won't apply to divs on web. the image should receive the alt tag.
additionally, [VoiceOver Recognition](https://support.apple.com/en-us/HT211899) uses on-device machine learning to detect what an image is depicting, so it's probably not necessary to state that it's an image (which is what the purpose of the role is). I don't think TalkBack has this functionality but I might be wrong there.

fix accessibility in AutoSizedImage

---

babel.config.js
patches/babel-preset-expo+9.5.2.patch

This simplifies the generated code to be closer to the code we actually write.
Concretely:
- Hermes already supports a bunch of features that we're currently compiling with Babel. Pass an option to target the subset needed by Hermes specifically, and let Hermes handle the rest.
- Although Hermes supports object spread, the Expo preset adds it back. Explicitly patch the Expo preset to disable it.
We will be able to remove both of these overrides when we upgrade Expo:
- The transform profile is being [auto-detected](https://github.com/expo/expo/blob/8156a6ff57353fc50f02537d0b6aefd1033c9f29/packages/babel-preset-expo/src/index.ts#L55) now.
- The object spread plugin is [conditional](https://github.com/expo/expo/blob/8156a6ff57353fc50f02537d0b6aefd1033c9f29/packages/babel-preset-expo/src/index …

Don't compile Hermes-supported features with Babel

---

src/view/com/util/Link.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1268.
This PR addresses the issue reported in https://github.com/bluesky-social/social-app/issues/1268. The current implementation of `DesktopWebTextLink` uses `useWebMediaQueries` to achieve conditional rendering, which is influenced by media queries that can cause inconsistent behavior when the browser window's dimensions change.
The core change is replacing `useWebMediaQueries().isDesktop` with `isWeb` within the `DesktopWebTextLink` component. This ensures a stable judgment for link displays not affected by the media query's constant fluctuations. 
With the modifications, the `DesktopWebTextLink` component will display as a link across all web platforms, including mobile web. While it is consistent behavior, it represents a …

Fix: Replace useWebMediaQueries().isDesktop with isWeb in DesktopWebTextLink component

---

patches/babel-preset-fbjs+3.4.0.patch

There's no benefit to treating Babel runtime helpers as lazy. With this change, we go back to eagerly importing them:
I sent a corresponding change upstream in https://github.com/facebook/metro/pull/1127.
If that PR doesn't survive, we can get rid of this patch. It's not super consequential in either direction but I want to remove these indirections from the render path since there's currently a lot of places where Babel generates calls to them.
Walked around the app. It works.

Don't inline-require Babel runtime helpers

---

src/view/com/auth/create/Step2.tsx

Fixed #1635.
- Imported `isWeb` from `'platform/detection'` to conditionally apply a pointer cursor style for web platforms.
- Wrapped the 'Join the waitlist.' text within a `View` component and applied a conditional style using `isWeb` to change the cursor to a pointer when hovered over on web platforms.
Currently, the changes are applied to the mentioned area in the issue. However, if deemed necessary, I am open to creating a wrapper around the `TouchableWithoutFeedback` component to handle cursor styling as a common component for broader use throughout the application.

Fix: Improved Accessibility and Interaction for Waitlist Link in Step2 Component

---

src/Navigation.tsx

The bundle produced by Metro always starts with capturing `__BUNDLE_START_TIME__`, so let's use this as the starting point. Then, let's use the moment we call `SplashScreen.hideAsync` as the end point. This gives us the actionable JS init time during which we're showing the splash screen. This is the time we can drive down by shifting and reducing module init code.
I opted to use `console.log` for simplicity, e.g. having dependency on the `store` or MobX-using `Log` doesn't feel right to me here since both of these might eventually get shifted down from the init path.
Note that to use this for production profiling, you still have to comment out the `transform-remove-console` in Babel config. That seems fair. Although we could evade the console call detection, I don't want to risk in case …

Log time to first paint

---

src/view/com/profile/ProfileHeader.tsx

The back button on profile header doesn't navigate back to home if there's no navigation history. 
Navigate directly to a profile on a new tab and click the back button on profile header.
We can check if we can go back (there's something to go back to), and if not, go home instead. 
A similar behaviour is currently [implemented here.](https://github.com/bluesky-social/social-app/blob/c6e28f88e5e96453005ff6f11194f3ccf091f4b6/src/view/com/post-thread/PostThread.tsx#L171)

Allow back navigation to home on profile header (on empty navigation history)

---

src/lib/strings/headings.ts

Bluesky currently uses a [hyphen](https://en.wikipedia.org/wiki/Hyphen) for separating the individual parts of its tab title in the web app:
As mentioned in the intro of the Wikipedia article above, hyphens are typically used for **connecting multiple words**, and therefore aren't an ideal choice for **separating multiple words** in a tab title.
I replaced the hyphen with a [dash](https://en.wikipedia.org/wiki/Dash), and more specifically an [em dash](https://en.wikipedia.org/wiki/Dash#Em_dash), which, in my opinion, is not only more typographically correct, but also looks much better:
Also happy to add an [en dash](https://en.wikipedia.org/wiki/Dash#En_dash) instead, which is still longer than a hyphen, but shorter than a [em dash](https://en.wikipedia.org/wiki/Dash#Em_dash).

Use more beautiful title separator

---

src/lib/api/feed/author.ts

Fixes #1166
Frontend component to https://github.com/bluesky-social/atproto/pull/1776. This logic walks the reply chain to ensure that all replies (available on this page of results, anyway) are by the `actor` and in reply to a post by the `actor`.
Example below. See the second image "Posts and replies" for the full picture. "Posts" shows ONLY if those replies that are (1) by the author you're viewing and (2) their reply root is a post by the author you're viewing.

Filter non-self threads from profile view

---

src/view/com/modals/EditProfile.tsx

- When user scrolls `EditProfile` screen to the bottom direction, there will be a cropped area as can be seen in the video below: 
https://github.com/bluesky-social/social-app/assets/61876765/95e28716-6503-4dac-8a1e-33a9af3e6e3b
- User is able to press cancel when there is an ongoing save process in `EditProfile` screen.
https://github.com/bluesky-social/social-app/assets/61876765/d6270217-b217-4cda-8633-de3b3834c059
- Adding `flex:1` to `KeyboardAvoidingView` component. There will not be any cropped area at the bottom of the screen.
https://github.com/bluesky-social/social-app/assets/61876765/f5d5f457-81f1-45cd-9f94-5cf89e8953cc
- We can hide the `Cancel` button in `EditProfile` screen when there is an ongoing process. Alternatively, we can utilize `react-native-reanimated`'s `FadeOut` …

UI/UX improvements in Edit profile screen

---

patches/metro-runtime+0.76.8.patch
src/Navigation.tsx

I end up hacking ad-hoc versions of this into the build all the time so let's just add it as a DEV-only patch. That Metro file barely ever changes so it shouldn't be a burden.
Change `shouldLog` to `true` locally. Observe the output:

Instrument module init in DEV

---

src/state/models/me.ts
src/state/models/ui/my-feeds.ts
src/state/models/ui/saved-feeds.ts
src/view/screens/Feeds.tsx

The "Feeds" screen needs to give the user quick access to their content or else users won't bother. Right now the load time is bad; this PR moves the saved-feeds state to the root store so that it can be loaded during session init.
https://github.com/bluesky-social/social-app/assets/1270099/badf1ec0-fc42-49b5-a689-927ccb59d7f7
https://github.com/bluesky-social/social-app/assets/1270099/ed2ee4e6-1a99-4e79-8654-3f99f150b19f

Improve feeds page load time

---

src/view/com/auth/login/Login.tsx

If you have more than ~10 logins, the Sign in as form fills up the screen and you cannot access "Other account" or "Back". This should be made scrollable

Make choose account form scrollable

---

patches/metro+0.76.8.patch
patches/metro-transform-worker+0.76.8.patch

This patches https://github.com/facebook/metro/pull/1130 to give us module names in Hermes initialization traces.
I'll delete this when we update to an upstream version with the patch.

Patch facebook/metro#1130 to profile module init

---

package.json
src/state/models/ui/saved-feeds.ts
src/view/screens/SavedFeeds.tsx
yarn.lock

The draglist component has begun to hit upstream errors on iOS (described https://github.com/computerjazz/react-native-draggable-flatlist/issues/496). It was not apparent how to fix this, so this PR replaces it.

Replace draglist due to upstream errors

---

src/view/com/util/UserAvatar.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx

There seems to be an issue in `expo-image` that blocks the UI thread on startup on low-end Android. As a result, we get stuck on the splash screen for 5 extra seconds if even one of those is rendered. As a temporary fix, let's render the startup-blocking images (own avatars in the drawer and the tabbar) as plain RN `Image`.
This lets us hide the splash ~4.5 seconds earlier. The final time to content seems to only improve by ~2.5s, but that's harder to measure reliably because it's network-bound. (We should optimize the load time too though.)
The proper fix is to get this reported to Expo and see if it can be fixed upstream. Maybe it's something like https://github.com/expo/expo/issues/21921.
(The measurements are taken with https://github.com/bluesky-social/atproto/pull/1790 patched in …

Work around a startup stall caused by expo-image on low-end Android

---

src/Navigation.tsx
src/view/screens/Profile.tsx

Users who tap the "Profile" footer button while loading sometimes receive an error message that can't be replaced. This is because the DID is being passed to the profile screen via the initial params in the navigator, and if they press the button before loading finishes then it may be undefined at time of press.
This PR solves that by looking up the DID within the screen. If they happen to press it early, they'll briefly get the error, then it will correct itself.

Lookup did for my profile at screen to avoid bad actor error

---

babel.config.js
tsconfig.json

Nothing PR, just didn't have an alias for the root `./src` and I think we could use one occasionally. In fact, we could really use this for all imports, but that's another thing and it's nbd.
Node introduced [subpath imports](https://nodejs.org/api/packages.html#packages_subpath_imports) a while back, which use `#` as a prefix.
I've see `@` and `~`, but both of those are overloaded by scoped npm packages and unix file system syntax, respectively.
With this PR, we can use simply `#/path/from/src` for all imports.

Add subpath imports

---

src/state/models/content/list.ts
src/state/models/feeds/posts.ts
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedErrorMessage.tsx
src/view/com/util/Views.d.ts
src/view/screens/ProfileList.tsx

- Improve the error state of feedgens to appear less frightening
- Fix the error state of profile lists
- Unsave lists when deleted
|||
|-|-|
|![CleanShot 2023-11-02 at 15 09 01@2x](https://github.com/bluesky-social/social-app/assets/1270099/fca2d31a-d709-41c6-9a90-db81b11971d6)|![CleanShot 2023-11-02 at 15 09 07@2x](https://github.com/bluesky-social/social-app/assets/1270099/61ef91cf-d4ad-49a2-8197-8ab411c7c8a0)|

Improved list and feed errors

---

src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

When user presses the "Posts" tab while scrolled down, it scrolls to top. This PR makes it refresh the content too so that the user gets the latest.

Refresh on scroll-to-top by active section press

---

src/lib/hooks/useIsKeyboardVisible.ts
src/state/models/discovery/user-autocomplete.ts
src/view/com/modals/ListAddUser.tsx

- Add loading state
- Improve hitslops
- Improve keyboard persistence behavior (wont annoyingly dismiss now when tapping things)
- Fix rendering issues that would cause weird relayouts (some kind of RN flexbox bug due to padding)

ListAddUser modal UX improvements

---

src/view/com/composer/ExternalEmbed.tsx
src/view/com/modals/ChangeHandle.tsx
src/view/screens/Feeds.tsx
src/view/screens/ProfileList.tsx

Noticed this on the list page on the web:
The issue is a pattern like `foo.error && <Bla />` where `foo.error` can be `0` or an empty string.
If it's an empty string, React no longer throws (it did in the past), so we actually "get away" with it. But `0` could still be an issue in theory, plus we don't want to see warning messages, so let's just write this explicitly.

Fix accidental unwrapped strings

---

src/state/models/content/feed-source.ts
src/state/models/content/list.ts
src/state/models/ui/saved-feeds.ts

Noticed that the remove button did not work for user lists. This updates the `unsave` handling to include `list` type sources. It also ensures that the unpin functionality in this view works the same as the unpin handling on `ProfileList` screen. Added TODO comments in both places.

Fix removal of old lists from saved feeds

---

src/lib/hooks/useMinimalShellMode.tsx
src/lib/hooks/useOnMainScroll.ts
src/state/shell/minimal-mode.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/screens/PostThread.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarStyles.tsx

Re-doing the fix from https://github.com/bluesky-social/social-app/pull/1691 which regressed in https://github.com/bluesky-social/social-app/pull/1676.
This time it's easier to fix at the source. Now that we've moved the shell state into React, I've changed the source of truth to be an Animated value. We can change it directly and make all animations derived from it.
In the future, we should also change this to update with scroll but for now I left it discrete.
```diff
// ReactNativeRenderer-dev.js
+let RENDERS = []
+setInterval(() => {
+  console.log('new renders:', RENDERS.join(', '))
+  RENDERS = []
+}, 1000)
function renderWithHooks(
current,
workInProgress,
Component,
props,
secondArg,
nextRenderLanes
) {
+  RENDERS.push(Component.name)
``` …

Hide/show header and footer without re-renders, take two

---

src/App.native.tsx

Adds `<i18nProvider>` to `App.native.tsx` which was lost in the merge
Tested on iOS and Android

Hotfix internationalization on mobile

---

src/view/com/pager/Pager.tsx
src/view/screens/Home.tsx

Follow-up to https://github.com/bluesky-social/social-app/pull/1855.
@ansh noticed that switching tabs in minimal shell mode shows blank space at the top initially (and you don't see where you're swiping). This fixes it by disabling the minimal shell as the swipe starts.
https://github.com/bluesky-social/social-app/assets/810438/0e08a9d8-9d8c-42d2-9a67-9e8bba8cf820
This one is pretty straightforward. Verified it works on iOS and Android. Doesn't affect web.

Show tabs when swiping feeds

---

src/view/com/pager/FeedsTabBarMobile.tsx

Fixes an issue @ansh pointed out in another PR.
This line seems to only affect web; I don't see any difference on iOS and Android.
It's pretty odd that none of these styles have changed in a while:
So I don't know how it could have regressed recently, but whatever.
Before:
https://github.com/bluesky-social/social-app/assets/810438/d245406b-e3f0-42da-ac9e-02a5b8afe7eb
After:
https://github.com/bluesky-social/social-app/assets/810438/4e9daf14-2464-4d2b-a296-8e18fd4b8c0b

Fix tab alignment on the web

---

src/view/com/pager/PagerWithHeader.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

Reverts https://github.com/bluesky-social/social-app/pull/1827 in favor of a simpler fix, which I need anyway for something else.
The fix is just to only pass a "real" `onScroll` handler to the current page. We only want to listen to the current page's scroll.
- https://github.com/bluesky-social/social-app/commit/370d219bbe09e3c0ba80f555118729a90ce12918: Revert of https://github.com/bluesky-social/social-app/pull/1827.
- https://github.com/bluesky-social/social-app/commit/b8c3cd478f2df3eee85bb217f677044febb22d82: The actual fix.
Verified the pager works like before on iOS and Android.

Pull useAnimatedScrollHandler back up

---

src/lib/hooks/useAnimatedScrollHandler_FIXED.ts
src/lib/hooks/useAnimatedScrollHandler_FIXED.web.ts
src/lib/hooks/useOnMainScroll.ts
src/view/com/pager/PagerWithHeader.tsx

Works around the "web" part of this bug: https://github.com/software-mansion/react-native-reanimated/issues/5360.
Concretely, Reanimated fails to update the event handlers, so we're going to proxy to the latest available version.
**I'm not touching the native side** because I don't know how I'd do this with worklets — also, it seems like we can avoid the bug on the native side by being careful and never passing the same handler to two views at the same time.
Notice that when you scroll back up, the button doesn't disappear. It's because `isScrolledDown` [here](https://github.com/bluesky-social/social-app/blob/487d871cfd89948f4db9944c4bb414d268a56537/src/lib/hooks/useOnMainScroll.ts#L52) forever stays `false` from the first render. …

Work around web stale closure bug in Reanimated

---

src/lib/hooks/useAnimatedScrollHandler_FIXED.ts
src/lib/hooks/useOnMainScroll.ts
src/view/com/lists/ListItems.tsx
src/view/com/notifications/Feed.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/posts/Feed.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx
src/view/screens/SearchMobile.tsx

It's not safe to use it anywhere except leaf components due to https://github.com/software-mansion/react-native-reanimated/issues/5364.
So we can't call it upwards and pass the result downwards. It "works" in some cases but we risk having stale props and state inside every handler, which is happening in my other refactors.
Since the functionality itself is extremely useful, I'm converting our code to a pattern where the thing we pass down is the config — i.e. the handlers. Then we wrap it at the lowest level.
There are effectively two sources of these handlers right now:
- `useOnMainScroll` handlers
- `PagerWithHeader` handlers
I've converted both sources and tightened up the types.
Walk around the affected screens:
- Home
- Notifications
- Search (when typing)
- Profile Feeds
- Profile …

Push useAnimatedScrollHandler down everywhere to work around bugs

---

src/view/com/lists/ListItems.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/posts/Feed.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

Currently the pager "jumps" the header translation if needed when you switch between tabs.
https://github.com/bluesky-social/social-app/assets/810438/97c8c2c5-0413-4bb7-b689-21d63becfa6e
Although that looks kinda cool on this screen, it becomes disorienting when you have multiple feed tabs, like on Profile.
This PR changes the pager to keep the tabs in sync by adjusting their *content* scroll positions instead:
https://github.com/bluesky-social/social-app/assets/810438/06d72dc3-51c9-491b-9ffa-0b914765ed24
This looks more boring which, with this kind of interface, is probably a good thing.
One concession I've had to make is that the scrollables now have to have a large enough height to make sure they can always be scrolled to the state where the header is collapsed. If there's a better way …

Make the pager non-jumpy

---

src/view/com/pager/PagerWithHeader.tsx

This fixes a bug in the new pager sync scrolling logic I've added in https://github.com/bluesky-social/social-app/pull/1863.
The previous code was saying: "sync scroll only if we didn't scroll past the header". The problem is that if we scroll fast, we're gonna have a large gap between the last event (which didn't reach the limit, but got synced) and the next event (which went over the limit, and didn't get synced).
Instead, let's track the last value that got synced. During every scroll, we'll calculate the new target, applying the limit. If we need to sync up the scroll, we'll do so and store the current value as the last one that got synced.
As a result, if we get an event that "overshoots" the header hiding threshold, we'll still adjust other pages to be exactly at that limit. …

Fix initial pager gap after fast scroll

---

src/view/com/lists/ListItems.tsx
src/view/com/posts/Feed.tsx
src/view/screens/ProfileFeed.tsx

For pager pages, we need to pad out enough space so that even if the pager is scrolled down, switching tabs does not cause a jump. The previous calculation I used didn't really make sense — it was too small in some cases.
I don't know the science behind which number to pick because it doesn't seem to actually correspond to the scrolled distance. Something's up with layout there. So I picked 1.5 screen heights which seems to be enough in my testing.
Also, it should be min height rather than bottom padding so that when the content is loaded, it doesn't stay at the tail.
¯\\_(ツ)_/¯

Use min height for pager lists and increase it

---

src/state/cache/profile-shadow.ts
src/state/queries/profile.ts
src/state/queries/resolve-uri.ts
src/view/com/posts/FeedErrorMessage.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/screens/PostThread.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileList.tsx
src/view/shell/desktop/LeftNav.tsx

- Updates profile screen to use the new `<PagerWithHeader>`
- Updates profile screen to use react-query
- Introduces a profile shadow cache, similar to the posts shadow cache
Still todo in followup PRs:

Refactor profile screen to use new pager and react-query

---

src/view/com/util/Views.web.tsx

Fixes the issue @estrattonbailey saw. I forgot to test web for https://github.com/bluesky-social/social-app/pull/1869.
The problem was that my `minHeight` style was being overwritten due to stylesheet ordering. I think custom passed props should take precedence so I swapped the order. I did some grepping and didn't find anything that would change behavior in a conflicting way.
No longer jumpy when switching tabs. Ignore the empty content — that's due to main being broken.
https://github.com/bluesky-social/social-app/assets/810438/a7d9e3c6-9e19-4856-abc9-aba508313a61

Fix jump for web pager

---

src/state/modals/index.tsx
src/state/models/ui/shell.ts
src/state/queries/profile-extra-info.ts
src/state/queries/profile.ts
src/view/com/lightbox/Lightbox.tsx
src/view/com/lightbox/Lightbox.web.tsx
src/view/com/lists/MyLists.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/modals/EditProfile.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/screens/Lists.tsx
src/view/screens/ModerationModlists.tsx
src/view/screens/Profile.tsx

- Update the avatar lightbox
- Update the profile editor
- Add dynamic tabs to profile
- Add lists tab to profile
Still TODO with profiles:
- Preview modal
- Feeds tab

More profile refactor updates

---

src/state/queries/profile-extra-info.ts
src/state/queries/profile-feedgens.ts
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/screens/Profile.tsx

Implements the feeds tab.
Notes:
- Using the term "Feedgens" when possible to add clarity (lots of things can act like feeds)
- UI of the feedgen items is a mess, will clean that up in the future

Add feedgens tab to profile (react-query refactor)

---

src/App.native.tsx
src/App.web.tsx

Noticed that the language selector in the composer broke bc of no access to i18n context. I moved any non-component-related providers higher up.

Fix root sibling context issue

---

src/state/cache/post-shadow.ts
src/state/cache/profile-shadow.ts
src/state/cache/types.ts
src/view/com/auth/onboarding/RecommendedFollowsItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

We use a "shadow cache" for profiles and posts to ensure synchronized state across views and to handle optimistic updates. As we've begun passing around the shadowed values, we noticed that it's easy to miss when a component depends on the shadowing. This is a problem because passing unshadowed posts/profiles will cause the component to break.
This PR adds a `Shadow<T>` type to help avoid that footgun.

Add Shadow type

---

src/App.native.tsx
src/App.web.tsx
src/state/queries/preferences/index.ts

In this case, `UnreadNotifsProvider` was calling hooks that were not pure state and relied on session data being loaded.

Fix notification provider order, add comments

---

src/view/com/util/images/ImageLayoutGrid.tsx

Fix image order in 4-image post embeds (close #1895)

---

package.json
src/state/queries/actor-autocomplete.ts
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/mobile/Autocomplete.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx
src/view/shell/desktop/Search.tsx
yarn.lock

- Updates the composer's web autocomplete to use the new hook
- Unifies the autocomplete hooks
- Drops the `fuse.js` usage. I did a side-by-side with the results and the fuzzy matching just added mostly-wrong guesses. We should let the backend do that behavior.
- Updates the mobile composer autocomplete to persist results while new ones are loading

Autocomplete updates (react-query refactor)

---

src/view/screens/Search/Search.tsx

- was previously checking for follows before searching so that the prev functionality would work as best it could, but Paul's changes make this unnecessary
- on cold load we should set an initial value for query so that you can see results right away

No need to await follows anymore, fix cold load search

---

src/state/queries/preferences/types.ts
src/view/com/post-thread/PostThread.tsx
src/view/screens/Home.tsx

We were [doing this before too,](https://github.com/bluesky-social/social-app/pull/1920/files#diff-e25b9c34f92225fd470d531409295da0a5a027efe4ff901922a25ed76974404bL14) but my new types should be optional since they're not part of the spec

Improve types

---

src/state/queries/post-feed.ts

The tuner handles de-duplication. If it doesnt maintain its state properly, it can result in duplicate react keys showing in the feed.
I noticed that and tracked down that the useMemo was being too loose with the dependency.

Fix memo params causing tuner to lose state

---

src/lib/hooks/useToggleMutationQueue.ts
src/state/queries/profile.ts
src/view/com/auth/onboarding/RecommendedFollowsItem.tsx
src/view/com/profile/FollowButton.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx

This introduces a helper that lets us run "toggle" mutations (e.g. Follow/Unfollow) without races.
Currently, our approach is to treat each mutation as independent. However, their optimistic updates can clobber each other — e.g. if you press Follow immediately after Unfollow, you can't predict in which order they'll get to the server, or in which order they will come back. Our existing code did not deal with that.
Additionally, our API treats Unfollow/Unblock/Unmute as deletions of a record and requires a record URI. However, if you press Follow immediately followed by Unfollow (haha), it's "too early" to send the Unfollow request because we don't have any record URI for it yet. Our existing code tried to deal with that by guarding event handlers so that you _can't_ Unfollow until Follow …

Add a mutation queue to fix race conditions in toggles

---

src/view/screens/Home.tsx

The issue was the feed tuner marking all feed items as stale because we've "seen" them. We've "seen" the initial feed fetch was immediately superseded by a second one. That happened because the pinned feeds (which are part of the parameters) were not immediately available, so loading them caused the query to refetch. The fix is to block on the prefs query.

Fix blank feed

---

src/view/com/notifications/Feed.tsx
src/view/screens/Notifications.tsx

1. Lack of visual feedback on notifs refetch was feeling off. This adds a spinner which could use visual improvements but does the job for now.
2. Turns out invalidation wasn't always triggering, you need `refetchType: 'all'` to ensure it happens

Notifs refresh improvement

---

src/state/queries/notifications/feed.ts
src/view/com/notifications/Feed.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/desktop/LeftNav.tsx

- Dont use the stale cache for notifications
- Add a delay before marking unread, as it was sometimes causing new notifs to show as read
- Choose some explicit times to refetch notifications optimistically
- Essentially: when going to the notifications tab *from another tab* but never when going back to the top of the notifications stack from within the tab

Improve notification load behaviors

---

src/view/com/posts/Feed.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/com/profile/ProfileHeader.tsx

We've lost some memoization when dropping MobX because its `observer` included `memo` inside.
Re-add some `memo`s in a few strategic places.
This should fix (most of) the profile scroll jank. The issue was that we were triggering some re-render up high which also re-rendered _all content in other tabs that were previously open_.
I'll do a closer pass to see what can benefit from memo'ing the most, but this is an easy fix.
I opted to wrap *after* definition because the extra indent level has been annoying.
This is a bit less obvious but reads cleaner IMO.

Add some memoization back

---

src/state/lightbox.tsx
src/state/modals/index.tsx
src/state/shell/composer.tsx

Opening the lightbox in profile no longer re-renders the profile header.
Opening the composer in feed no longer re-renders the feed.
Plus a driveby simplification.

Use non-reactive callbacks for some methods 

---

src/App.native.tsx
src/App.web.tsx

This enables https://github.com/software-mansion/react-freeze. Not sure if anything will break but if we're doing big changes anyway why not give it a try.
Essentially, this "pauses" screens that are inactive. There's a [manual API for it](https://github.com/software-mansion/react-freeze#quick-start---using-freeze-directly-react-and-react-native-) but it also integrates into React Navigation automatically, which is the part this PR enables. (For the manual part, we need to play with integrating it into the pager.)
Only screens "more than one nav pop away" get frozen by default, so it mostly helps when you push deeper into the stack. Concretely, "freezing" means React will deprioritize updates to them and will process their state updates after they're unfrozen (i.e. when you pop the nav …

Freeze inactive screens

---

src/state/cache/post-shadow.ts
src/state/cache/profile-shadow.ts
src/state/queries/preferences/index.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

Let's fix a bunch of regressions that crept in with the state refactor.
- We should [avoid `setState` in `useEffect`](https://react.dev/learn/you-might-not-need-an-effect#caching-expensive-calculations) like plague. To avoid recalculations, `useMemo`. 
- If we're calculating something just for the initial state, put `() =>` before it to [avoid running it again](https://react.dev/reference/react/useState#avoiding-recreating-the-initial-state).
- Don't recreate a bunch of objects that have the same content every time. Especially when they're being passed down later. Then add some memoization to take advantage of that.
https://github.com/bluesky-social/social-app/assets/810438/1df1513a-169c-410b-a388-2000067cbc4c
With 6x CPU throttling, scrolling a post thread stalls for two seconds: …

Do less work during rendering (part 1)

---

src/view/com/notifications/FeedItem.tsx

Scrolling notifications with 6x CPU throttling: 700ms stall.
Scrolling notifications with 6x CPU throttling: 30ms stall.

Optimize notifications rendering

---

src/lib/batchedUpdates.ts
src/lib/batchedUpdates.web.ts
src/state/cache/post-shadow.ts
src/state/cache/profile-shadow.ts
src/state/cache/types.ts
src/view/com/auth/onboarding/RecommendedFollows.tsx
src/view/com/auth/onboarding/RecommendedFollowsItem.tsx
src/view/com/lists/ListMembers.tsx
src/view/com/modals/ProfilePreview.tsx
src/view/com/notifications/Feed.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/posts/FeedSlice.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx
src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx
src/view/screens/Profile.tsx
src/view/screens/Search/Search.tsx

Small refactor to how shadows work. This isn't supposed to *significantly* change anything but might improve perf a bit.
- fa334350fb04d3ede175829cb9a2723155826bc6: This removes the `isShadowed` field from the runtime. This lets us avoid doing an extra object copy for each post (even before it gets shadowed). Theoretically this also might help with monomorphism (avoiding all the methods below from dealing with differently-shaped objects) though in practice probably not. To enforce that you can't can't make a shadow out of thin air, I used [this trick](https://evertpot.com/opaque-ts-types/).
- 0128feefd4012f16984f231235fb74a1d66a95d9: Just preventing creating a few unnecessary objects on every render.
- 67cf7a5824ae8fcdd7274a8949fe836da4d0a9ed: This applies [this …

Shadow refactoring and improvements

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileList.tsx

We've lost this in the refactor.
- Scroll to top
- Invalidate
- Handle the tabs being shown conditionally
[Review without whitespace](https://github.com/bluesky-social/social-app/pull/1973/files?w=1)

Implement "scroll to top" for profile tabs

---

__tests__/lib/strings/url-helpers.test.ts
jest/jestSetup.js
src/lib/strings/url-helpers.ts

Fixes #1731
We already effectively extract the host, but until the [polyfill fixes this](https://github.com/charpeni/react-native-url-polyfill/issues/462), we should compare using lowercase hosts.

Fixes 1731, compare URLs case-insensitive

---

src/view/shell/index.web.tsx

Random drive-by fix. I couldn't actually get a situation where this effect would re-run, but still worth cleaning up. Verified the listener itself fires like before on navigation.

Fix missing effect cleanup

---

src/state/session/index.tsx

This was clearly confusing because the query cache clearing wasn't happening on `logout`. Now it is.

[PWI] Clarify different ways of clearing current account/logout

---

src/view/screens/Search/Search.tsx

There was a double border when loading suggested follows on mobile. This fixes that, plus uses the proper loading placeholder.

Fix double border, improve load state

---

src/logger/__tests__/logger.test.ts
src/logger/index.ts

This only applies to errors sent as `extra` data. App exceptions are otherwise still captured by `captureException`, which will include the stack trace.

Make sure logger serializes errors

---

src/lib/api/feed-manip.ts
src/view/com/lists/ListMembers.tsx

- 5c14b36b07737c362f516c18d097c596ad6f2ef7 fixes the react keys in the ListMembers component (they were undefined)
- 5201ace6c4818c3945b8c1955e998a25239c095d fixes the react keys in the posts feed (sometimes produced duplicates)

Two fixes to react-key generation

---

src/view/com/util/Link.tsx
src/view/shell/bottom-bar/BottomBarWeb.tsx

When we explicitly use the `push` action, and our router config never specifies `getId` (it doesn't), pushing [always creates a new top-level screen](https://github.com/react-navigation/react-navigation/blob/99f00d2c89e3e46004303336543d2d3dba03fdf4/packages/routers/src/StackRouter.tsx#L292-L305). This causes a very bad memory leak because every tab button navigation creates a new screen:
https://github.com/bluesky-social/social-app/assets/810438/9d18d38a-2647-4fdd-8533-a42f9f620cba
I'm not sure what the idiomatic way to fix this is, but we can use the `navigate` action instead which will [check if the same route exists in the stack and reuse it](https://github.com/react-navigation/react-navigation/blob/99f00d2c89e3e46004303336543d2d3dba03fdf4/packages/routers/src/StackRouter.tsx#L358-L392) …

Fix memory leak on mobile web tab navigation

---

src/lib/react-query.ts

React Query has an optimization called [structural sharing](https://tkdodo.eu/blog/react-query-render-optimizations#structural-sharing). When RQ receives a response, it will by default [traverse both the old and the new response](https://github.com/TanStack/query/blob/f62e079a4ff92a1580910ede560610b86d34a316/packages/query-core/src/utils.ts#L322) and try to reuse parts of the previous response if they are deeply equal to the parts of the new response at the same key paths. This is particularly useful when the data refetches often but most items don't update.
In our case, this causes a problem. We're using an (arguably hacky) approach to [track whether a piece of data is stale](https://github.com/bluesky-social/social-app/blob/b778017000eeed028edc5cd8fa89d64d4d90dc32/src/state/cache/post-sh …

Disable RQ structural sharing

---

src/lib/api/feed/author.ts
src/lib/api/feed/custom.ts
src/lib/api/feed/following.ts
src/lib/api/feed/likes.ts
src/lib/api/feed/list.ts
src/lib/api/feed/merge.ts
src/state/queries/list.ts
src/state/queries/notifications/feed.ts
src/state/queries/notifications/unread.tsx
src/state/queries/post-feed.ts
src/state/queries/profile.ts
src/state/session/index.tsx

The `getAgent()` is a global method that gives the current session's agent. We want to make sure to never hold onto its return value because that would enable stale agent usage. We've seen a few surprise "missing jwt" errors that suggest that stale agents are being used, so this PR gets a bit more rigorous about it.

Get more rigorous about getAgent() consistency

---

src/lib/hooks/useAccountSwitcher.ts
src/view/com/auth/login/ChooseAccountForm.tsx
src/view/screens/Settings.tsx

Instead of clearing the current account, I just show the logged out view which allows a user to sign into a new account. When clicking on the currently signed in account, it simply hides the logged out view.
Swapped icon if account is already signed in.

Show logged out view when adding accounts

---

src/state/queries/notifications/feed.ts
src/state/queries/notifications/types.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/view/com/notifications/Feed.tsx
src/view/screens/Notifications.tsx

This PR:
- Improves the performance of loading notifs (by using a background cache)
- Fixes an issue on mobile where the feed would jump around while scrolling (by removing the loading spinner I added, which is no longer needed anyway)
The way this works is, it ties together the unread-notif syncing API with the feed query. The unread-notif checker has to periodically fetch a page to count unreads, so this just holds on to that first page to use in the notifs-feed query.
This video shows the performance. It could use a little more visual feedback about the loading state, as well as some better handling of some waterfall-effect behaviors, but it's still much snappier than before:
https://github.com/bluesky-social/social-app/assets/1270099/60b3d4e2-28d2-4814-8d08-ffc717cd12c5

Refactor the notifications to cache and reuse results from the unread-notifs checks

---

src/lib/notifications/notifications.ts
src/state/queries/notifications/unread.tsx
src/view/com/feeds/FeedPage.tsx
src/view/screens/Notifications.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/desktop/LeftNav.tsx

React-query has an enormously subtle behavior with infinite queries: If you `invalidate` the query, it will maintain the current page count and refetch *every page*.
RQ's logic is that you want to maintain the UI state and just update the items in place. For content-feeds, however, like post-feed and notifications-feed, this is a really bad behavior for two reasons:
1. If you've been scrolling for a while and then we invalidate (typically bc the user pressed load latest or soft reset) then it will fetch as many pages as you just looked at. This is a terrible issue with notifications.
2. Most of the content-feeds are non-deterministic, meaning this is an entirely pointless behavior.
This PR switches the `invalidate` calls on post-feed and notifications-feed to `reset`, which clears out the …

Fix infinite query reloading behavior (reset, not invalidate)

---

src/lib/api/feed-manip.ts
src/lib/api/feed/merge.ts
src/state/queries/post-feed.ts
src/view/com/posts/Feed.tsx

This PR started with me investigating duplicate react keys showing up in feeds. I started with 1c341e0a5406921b16e857f496711121595e9450 which I expected to solve it, but then it still happened!
This led me to dig deeper into the lifecycle management of the `FeedAPI` and `FeedTuner` that's passed into the `post-feed` RQ. I discovered that they are fundamentally incompatible. RQ's query cache lifecycle is completely independent of React's hook-mounting lifecycles. What we want to do is carry the api and tuner in the RQ lifecycle.
The solution I found was to put them into the page params, which I think is actually fairly logical for this sense essentially they are pager state. It's a little weird, but it does seem to work.

Fix state lifecycle management with post-feed query, solving the duplicate key issue

---

__e2e__/tests/home-screen.test.ts
src/lib/constants.ts
src/state/queries/feed.ts
src/view/com/pager/FeedsTabBar.web.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/TabBar.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileFeed.tsx
src/view/shell/desktop/Feeds.tsx

Implements the feed link in tab bar for users who do not have any pinned feeds or lists, per #2011.
[ed391c3](https://github.com/bluesky-social/social-app/pull/2033/commits/ed391c346d6e6858d0d24c08def2974df8ccbde7): Add a hasPinnedCustomFeedOrList boolean property to the usePinnedFeedsInfos hook (used in the next commit) and refactor the 3 places that were using that hook to get feeds. I included the property in this hook because usePinnedFeedsInfos will, at worst, update only as often as the list of feeds, so this won't cause any extra renders and has the benefit of colocation.
[8ceabe2](https://github.com/bluesky-social/social-app/pull/2033/commits/8ceabe2a11742973447a6e3b4489c8a5660f48c3): Use the hasPinnedCustomFeedOrList property added in the last commit to see if the user has any …

Feeds link in feeds tab bar

---

src/state/preferences/feed-tuners.tsx
src/state/queries/post-feed.ts
src/state/queries/post-thread.ts

- 20b3ff3d10183dbb87ef0f1ec85a348a5204d887 Updates the feed tuners hook to use preferences
- 4be86293c56d0ae79c0022fa1618332259e8bdd1 Moves the application of the feed tuner into the `select()` stage of react-query
It turns out that the `queryFn` closure does, in fact, go stale in some cases. Even more interestingly, values passed in through `meta` also go stale. Once the hook was implemented correctly, the updates just didn't pass into the hook. What's strange is that I've also seen the `queryFn` update its closure, so I haven't been able to suss out the behavior.
Interestingly, the `select` function _does_ get redefined on every call, and so it's quite a good place to handle these kinds of things. An added bonus is, this means a change to the preferences which modifies the feed tuners …

Apply feed preferences (react-query refactor)

---

src/lib/hooks/useWebMediaQueries.tsx
src/view/com/util/layouts/Breakpoints.web.tsx

The breakpoints for the `tablet` and `mobile` viewports are scuffed because some breakpoints have their `minWidth` set to a value of `800` and `1300` respectively while other breakpoints use the same values for their `maxWidth` which causes styles to overlap and look weird.
I changed the relevant `maxWidth` values to `799` and `1299` respectively so that the styles do not overlap anymore.
I got some screenshots of the local development environment here. It's not set up enough to be fully functional, but it was enough to test the fix. 🙂
| `1299px` | `1300px` | `1301px`
|---|---|---
| ![1299px](https://github.com/bluesky-social/social-app/assets/5056880/f5955acf-8170-480d-97dd-485d255deb46) | ![1300px broken](https://github.com/bluesky-social/social-app/assets/5056880/612444e3-e31a-416f-8d59 …

Fix scuffed web styles caused by overlapping viewport breakpoint boundaries

---

src/view/com/pager/PagerWithHeader.tsx

Some misc perf improvements.
- Pull out the tabbar into its own component so we can memo it
- This also solves the animated style being recreated too often, causing header re-renders
- Adjust the other tabs' scroll views on a throttle instead of on every frame
- Pull out the usage of `isScrolling` out of `onScroll` to avoid invalidating `onScroll` when you scroll down
- Make `isScrolling` update non-blocking
We're still managing the header positioning with JS and it's laggy.
I'm not sure if we're gonna have to change the strategy there but at least it's an incremental improvement.
https://github.com/bluesky-social/social-app/assets/810438/5ea2fc27-86df-40a3-a452-ba203863170e
https://github.com/bluesky-social/social-app/assets/810438/299925c1-ba48-4017-8ab0-cac023a60b11

Optimize pager rendering

---

src/state/queries/notifications/feed.ts
src/view/com/notifications/Feed.tsx

- Set stale to infinity. Should fix some surprise invalidations I saw.
- Move mark-all-read to a more stable place

Improve unread notif tracking

---

src/state/queries/feed.ts

We evidently do have access to the statusCode here, so this is a better check.

Better handle feed auth failures

---

src/view/com/pager/PagerWithHeader.tsx

When we push into the nav stack on the web, the previous page remains in the DOM. However, since the screen gets hidden, the layout re-fires with `0` as the height. We save that, which leads to destroying the feed (since we render it conditionally on non-zero height). Then, when we pop the stack, the layout would fire again with the real height, and we'd remount the feed. As a result, the feed's position gets out of sync with the header. The header is translated but the scroll got reset on remount.
There's a few things to think about here.
The simplest fix (which is what I'm doing here) is just to ignore `0` as height in layout events. It means the view is going offscreen and we don't really need to track that. So this naturally solves the issue. (We don't support zero height in this …

Fix scroll jump on Back

---

src/view/com/profile/ProfileCard.tsx

`ProfileCard` item's description text jumps/flickers when blur action is executed on search input in suggested follows tab.  
https://github.com/bluesky-social/social-app/assets/61876765/e212fc72-de6c-4d54-9658-808ac1a678eb
https://github.com/bluesky-social/social-app/assets/61876765/3bcfecd0-4041-4d6a-8c64-d525d1947603
Apparently, `alignSelf: 'baseline'` is the root cause of this issue. To address this, we could replace `baseline` with `flex-start` which ultimately aligns avatar with user's name. Furthermore, we need to add necessary `paddingTop` to add spacing between description content and top content of the `ProfileCard`.
https://github.com/bluesky-social/social-app/assets/61876765/22d14256-6cc3-42e0-ac00-921fd5da2996
https://github.com/bluesky-social/social-app/assets/61876765/84fd41 …

Fix jump in suggested follows tab on blur action (Native)

---

src/view/com/composer/Composer.tsx

Currently we stop you from just posting a link card. This fixes that.

Allow posts with just an external link

---

src/view/com/pager/PagerWithHeader.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx

This makes non-interactive elements pass through their events to the view below, so that the scroll view responds when you try to scroll or drag the profile header. Tested on web, iOS, and Android.
I don't see an easy way to make it work for interactive elements (e.g. the avatar button) without a more significant rethinking of the entire thing. Since the scroll view is below, unless the header is inside of it, it won't know it's being dragged. We could add a panning gesture on top but then we'd also have to handle momentum etc somehow. Not sure that's worth it.
I only made it work for profile, but could also do for lists. Their header is much smaller though so less appealing to drag.

Allow scroll by dragging profile header

---

src/lib/moderation.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/post-embeds/index.tsx

There's an irritating bug where blurred quoted content also covers the image. This PR correctly distinguishes between the two.
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 20 01 26](https://github.com/bluesky-social/social-app/assets/1270099/0df3794d-867d-4022-94cd-690c8f94729e)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 19 55 37](https://github.com/bluesky-social/social-app/assets/1270099/38667659-9a81-4de7-a8ec-58e73f050bed)|

Fix: distinguish between post media and quotes with the moderation hider

---

src/view/com/pager/Pager.tsx

Uses the `onPageSelecting` logic to update the tab bar UI faster. 
https://github.com/bluesky-social/social-app/assets/1270099/71848c39-8510-4243-82ab-4f20f788b9a6
https://github.com/bluesky-social/social-app/assets/1270099/1ccb941f-ea8a-4fa1-810b-dc715fb8879a

Optimistically update the pager tab bar on swipe

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/view/com/posts/Feed.tsx
src/view/com/posts/FollowingEndOfFeed.tsx
src/view/screens/Profile.tsx

This is what the end of a profile feed looked like (test with `test.esb.lol`):
So I added a spacer:
And then figured we might as well tell the user what's up:
While scrolling, I noticed the loader was cut off, and you couldn't even see if before. Now looks like this (had to cut my internet to get this shot, hence no images):
And also noticed that the empty state at the bottom of following feed looked like this:
So I also added some min-spacing to that:

Fix bottom space on feeds

---

src/view/com/post-thread/PostThreadItem.tsx

I'm a little torn about this one. It does two things:
- Changes all replies to be the "small header" form (where previously the first-level replies were "big header" form). This causes all the left-hand spacing to be consistent, fixing the most obnoxious issue.
- Shrinks the avi in the "small header" form, trading legibility of the avis for more consistent spacing.
Comparison shots:
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-03 at 09 13 22](https://github.com/bluesky-social/social-app/assets/1270099/b652d3c0-f480-46db-a5d8-73c73c54f061)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-03 at 09 11 05](https://github.com/bluesky-social/social-app/assets/1270099/a4f5c56c-fb0d-4dc3-86b9-339ccc19bb1b)|
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - …

Tune treeview thread mode to have consistent spacing

---

src/state/queries/util.ts

It turns out that `setQueryData` relies on an exact match for the react-key but `setQueriesData` can do partial matches (which sort of makes sense). This meant that the post feeds were still fetching all subsequent pages -- not truncating.

Fix: correctly partial-match when calling truncateAndInvalidate()

---

src/view/com/posts/Feed.tsx
src/view/screens/Profile.tsx

This is an override that allows you to look at somebody's posts in their profile, eg if you've muted them. Confirmed the logic carried over from before the refactor.

Add back ignore-filters-for behaviors

---

src/state/events.ts
src/state/queries/post-feed.ts
src/view/com/composer/Composer.tsx
src/view/com/posts/Feed.tsx

This one is a little tricky
- After post, have to wait for appview to update
- In feed, only invalidate the cache _if_ just one page of data is loaded. This is really to act as a proxy to a UI issue that react-native can have with flatlists; if the user is scrolled far down, prepending data can cause the scroll position to begin vacillating wildly. Of course, RN doesn't give us a way to just get the scroll position, so this will have to do.

Update feeds on post created

---

src/view/com/pager/PagerWithHeader.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx

The animation was buggy as hell on iOS and somewhat laggy on Android. The reason in both cases is that it triggers the pager `onLayout` logic which tries to readjust the FlatList padding which wreaks havoc *especially* on iOS.
For simplicity I ripped out the animation everywhere.
https://github.com/bluesky-social/social-app/assets/810438/c2496b01-3771-4ccd-b1f1-f6881678e2d9
https://github.com/bluesky-social/social-app/assets/810438/777c2936-2c93-4448-a79e-31e37dd91683
https://github.com/bluesky-social/social-app/assets/810438/9166a4e8-d771-4d41-836d-baac3b98be42
https://github.com/bluesky-social/social-app/assets/810438/98dd7fdd-ef3a-4b2c-8869-d4f9ca0ba303

Fix jump when toggling suggestions

---

src/App.native.tsx
src/App.web.tsx
src/Navigation.tsx
src/state/shell/reminders.ts

This was previously crashing because `unstable__openModal` was being called too early. Also nice to move it out of the critical path. I'll probably move a few other things here too.

Fix email confirmation dialog on startup

---

src/locale/i18n.ts
src/locale/i18n.web.ts
src/view/screens/LanguageSettings.tsx

Reported by [Jake in Slack](https://bluesky-builders.slack.com/archives/C04BH54QDLH/p1701818542377789). The selector library we're using doesn't support `disabled` on its placeholder option (or any option, ugh).
This PR just prevents any locale we're not ready for from being loaded + disables the placeholder option entirely.

Prevent invalid locale from being loaded

---

src/state/persisted/__tests__/legacy.test.ts
src/state/persisted/index.ts
src/state/persisted/legacy.ts
src/state/persisted/schema.ts
src/state/session/index.tsx
src/view/com/modals/ChangeEmail.tsx
src/view/com/modals/VerifyEmail.tsx
src/view/screens/Settings.tsx
src/view/shell/desktop/RightNav.tsx

Noticed a [Sentry log](https://blueskyweb.sentry.io/issues/4699579547/?query=is%3Aunresolved+dist%3Aios.1.57.0.7&referrer=issue-stream&statsPeriod=24h&stream_index=9) about a failed migration. The logs pointed to a validation failure around `email` and `emailValidated`. Sure enough, these were optional fields in the old architecture.
This PR marks those fields as optional and any usages to be more safe. I also added a preemptive validation check so that we can more gracefully handle any unforeseen issues. 
I've tested this a few times by resetting back to 46c2564e6531712538e44ee6880fb4bfce612ab9, clearing storage, etc, and then jumping back to the head of this branch. While doing that I clarified a few logs.

Improvements to persisted state migration

---

src/lib/routes/helpers.ts
src/state/queries/post-feed.ts
src/view/com/feeds/FeedPage.tsx
src/view/screens/Home.tsx

This seems to solve a case of scroll position loss on other tabs (mobile). Here's the deal:
React state updates aren't triggering after the screen loses its focus because of the react-native-screen "freeze" setting. This means that the various `isFocused` values won't be updated by blur, and so the "soft reset" call is getting triggered for the Home screen's feeds when it's off-screen.
About the solution: React navigation has a wildly finicky API. It's _designed_ to scope knowledge of the router to a given component to improve composition, so when you call things like `useNavigation` or `useNavigationState`, it doesn't give you the root navigator. Instead, it gives you the leaf navigator -- which, in the case of mobile, is the stack navigator you're currently on rather than the …

Fix: correctly identify if the screen is focused when handling soft resets

---

src/view/com/post-thread/PostThread.tsx

The PostThread's FlatList has `initialNumToRender` set to the thread length so that it can correctly scroll to the focused post when going to a reply. This is only necessary when using the `onContentSizeChange` => `scrollToOffset()` technique, which is *typically* Web. On Native, we use the `maintainVisibleContentPosition` trick (which recently landed for Android).
On large threads, this setting causes the UI thread to semi-freeze. This manifests as tapping on a thread and nothing happening for a few seconds, and then navigating. Removing this prop solves that entirely, and fortunately Web seems unbothered by the render task.
(Holy shit)
https://github.com/bluesky-social/social-app/assets/1270099/30581efa-43b0-47be-85ba-2289971bbbc2 …

Perf: Dont initial-render full thread on mobile

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx

A little more treeview UI tweaking, as a treat
- More consistent spacing
- Always include one level of "reply bar" to avoid the awkward left-edge visual flow
- Slightly shrink the expanded post's avi (Fons is going to reduce avi sizes in general with the updated designs)
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 12 31 54](https://github.com/bluesky-social/social-app/assets/1270099/d0b412ea-f5ef-40a1-9ba2-f716a24c37cd)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 12 31 16](https://github.com/bluesky-social/social-app/assets/1270099/03b1b892-95e6-46bd-a2d0-171720a3bfab)|
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-05 at 12 32 03](https://github.com/bluesky-social/social-app/assets/1270099/6b0c6eca-d018-48d5-a0d0-3416bc76 …

More treeview UI tweaks

---

src/lib/api/feed/author.ts

Builds on #1757 but updates to use `did` instead of `handle` since that's what we're passing into this query now. Tested with [the up-to-date backend PR](https://github.com/bluesky-social/atproto/pull/1776) 👍

Fix self-threads filter logic

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/view/com/lists/MyLists.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/screens/ModerationModlists.tsx

Previously this error was displayed on the Lists screen
This PR fixes that error by fixing the `keyExtractor` function in the `FlatList` component that renders the user's lists.
It also adds some missing translations

Add missing translations and fix react key error in `MyLists.tsx`

---

src/App.native.tsx
src/App.web.tsx

We're seeing some signs that screen freezing causes pending work to queue up, which then introduces rendering delays when the screen unfreezes. I want to test this in the TF

Disable react-native-screen freezing to test performance implications

---

src/lib/sentry.ts
src/logger/__tests__/logger.test.ts
src/logger/index.ts

Let's get Sentry logs out of the critical path.
Two changes:
- Non-exception messages are put in a queue throttled with a leading edge of 7 seconds. I picked a number that's likely enough to unclog the critical path on a slow network but still reasonable that the app will likely stay foregrounded etc.
- Disable [session tracking](https://docs.sentry.io/platforms/javascript/configuration/options/#auto-session-tracking) cause I don't think we care about this? This was causing an extra request at startup.

Throttle non-critical Sentry messages

---

src/view/shell/Drawer.tsx
src/view/shell/NavSignupCard.tsx

Not a huge deal but noticed it re-renders when we navigate, and there's some icons there etc which isn't free.
Ideally it would be nice to freeze it while it's closed.

Optimize Drawer re-renders

---

src/state/queries/preferences/index.ts

There's no rich entities using shadows inside, and we're planning to refetch this fairly often, and everything reads it, so it's a good idea here.

Enable structural sharing for preference query

---

package.json
src/state/session/index.tsx
yarn.lock

If we have a fresh enough `accessToken`, it should not be necessary to block other network requests on resuming the session. We should be able to optimistically reuse the persisted account without waiting, fire off the request, and then upsert it — if some data is different.
Putting this up for a discussion. This only works while the token is fresh (I think it's within 30 minutes).

Remove getSession waterfall

---

src/state/queries/index.ts

We want to use this endpoint because it has the caching

Update pwi endpoint

---

src/App.native.tsx
src/App.web.tsx
src/lib/analytics/analytics.tsx
src/lib/analytics/analytics.web.tsx
src/lib/analytics/types.ts
src/view/com/feeds/FeedPage.tsx

Simplifies our analytics wiring and moves them out of the blocking startup path.
The provider and the Hook provided by the Segment client don't do anything special or particularly useful. They're just proxying to the client methods. We already have the client right here so we might as well use it directly. The methods exposed by the native and the browser versions of the client, and their signatures, are slightly different. We only use two methods anyway. And we use our custom types for them. So I narrowed down the methods we use to those two methods.
Now that the abstraction is out of the way, we have more control. I use this to make creation of the client lazy. It's created on first use. Since https://github.com/bluesky-social/social-app/pull/2115, that first use is after the module …

Move analytics out of critical path

---

package.json
src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/state/queries/post-thread.ts
src/state/queries/profile.ts
src/view/screens/Moderation.tsx
yarn.lock

This just adds the opt-out toggle. The behaviors for handling the opt-out can come in a follow-up PR (not a blocker until we enable the PWI).
- Added to the moderation screen
- Open to discussing the copy, but we need to settle it by Friday

Add PWI opt-out toggle

---

src/state/queries/post-thread.ts

The post-thread query works like this:
```
usePostThreadQuery mounts
fetch is triggered
if cached data is available, display
if placeholder data is available, display
fetch resolves
display result
```
When the placeholder renders, it looks like this:
```
+-------------------+       
|     spinner       |       
+-------------------+       
|                   |       
|    target post    |       
|                   |       
+-------------------+       
|     spinner       |       
+-------------------+ 
```
When the full data loads, it becomes this
```
+-------------------+       
|       post        |       
+-------------------+       
|       post        |       
+-------------------+       
|                   |       
|    target post    |       
|                   | …
```

Completely disable the RQ cache in post-thread

---

src/view/com/feeds/FeedPage.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx
src/view/screens/Notifications.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

In some cases on Chrome and always on FF, the scroll to top would fail because the animation wouldnt finish before content changed in the feed, causing the scroll to totally fail.
Perhaps a better fix would be to wait until the scroll finishes to queue the work, but I went with the simple solution first.

Disable animation on scrollToTop for web

---

src/view/screens/ProfileList.tsx

Added muting/blocking controls to the dropdown for curational lists. Since a curational list could technically get converted to a modlist, I added an option to unpin that, but no option to re-pin.
Modlist:
Curational list:

Allow blocking/muting to curational lists, unpinning to modlists

---

src/lib/api/feed/merge.ts
src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

- 1fede395531c4e3aa6a96c17b23c6dc1b12a52b8 fixes a case where a lot of empty pages are coming back (it can in fact happen)
- ee6709a09afadb69f192d3f475a9affce125d283 falls back to the mergefeed if the user runs out of posts from followed users (in can in fact happen, a lot more than you'd think actually)
- 9ca884b6774196df72cc43bd8190afa5c94f960f fires a "check for new" poll on feed focus, since we no longer background poll

Grab-bag of post-feed improvements

---

src/state/queries/post-feed.ts

We're always regenerating new data in `select()` so every real re-render with new data would lead to recalculation of all slices and blow away our memoization. Let's add a manual memoization step that reuses pages from the previous selection (which in many cases will work out — notably for pagination). I'm assuming pages are immutable (I think so).
Note that we need to advance the tuner while going over the reused pages.
Also note `structuralSharing` wouldn't help us here because the issue is with the pages that were *not* refetched.
[Review without whitespace.](https://github.com/bluesky-social/social-app/pull/2146/files?w=1)
Every time you fetch a new page, all previous items re-render.
First commit (extraneous and slow -- all pages):
Second commit (expected:
When you fetch a new page, …

Add manual per-page memoization to post select

---

src/view/com/posts/Feed.tsx

Similar to the recent PR to poll for new posts on the feed page change, this PR polls on app foreground, ensuring we never just sit with stale posts

Poll for new posts on app foreground

---

app.config.js
src/lib/notifications/notifications.ts
src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/state/queries/notifications/feed.ts
src/state/queries/notifications/types.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/view/screens/Notifications.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/desktop/LeftNav.tsx

- c1a2819fc79546a443ffcdc48e492486789bdf7b Removes a reset of the notifications feed cache that I'm fairly sure is the cause of the random loads of the feed while you're scrolling
- d78d5c00ceb97376b6aa9fdfa6d6242978e8a501 Small tweak of grouping behavior (reverting a change I tried earlier)
- b541f94f0ec6c61d7b06fa6ac2a3da25997dd725 Takes a new approach to resetting the notifs feed query on focus which avoids losing the user's scroll state 
- 05c39c92ee30d9c57870826d47847f6ed79199f8 Is a minor optimization, bringing back the use of the cached page from unread but only if the page is known to be fresh, avoiding the issue driving its removal in the first place (losing likes by the user)

Multiple notifications fixes

---

src/App.native.tsx
src/App.web.tsx
src/state/session/index.tsx

I [was wrong](https://github.com/bluesky-social/social-app/pull/2129#discussion_r1419286474), we still need this when we DO need to refresh the session.

Add back isInitialLoad to session

---

src/lib/hooks/useAnimatedScrollHandler_FIXED.ts
src/lib/hooks/useAnimatedScrollHandler_FIXED.web.ts
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/notifications/Feed.tsx
src/view/com/posts/Feed.tsx
src/view/screens/ProfileFeed.tsx

It didn't work due to https://github.com/software-mansion/react-native-reanimated/issues/5488.
We already had a workaround checked in, but it wasn't prominent enough so old imports slipped through.
I renamed the export name itself consistently and added it in the places that missed it so that it's harder to copy paste the wrong thing.
[Without whitespace](https://github.com/bluesky-social/social-app/pull/2168/files?w=1)

Fix scroll on profile lists/feeds

---

src/lib/hooks/useAnimatedScrollHandler_FIXED.ts
src/lib/hooks/useAnimatedScrollHandler_FIXED.web.ts
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/notifications/Feed.tsx
src/view/com/posts/Feed.tsx
src/view/screens/ProfileFeed.tsx

Fixes crashes on native that I introduced in https://github.com/bluesky-social/social-app/pull/2168.
I forgot the Reanimated compiler looks at the function name. That's why I didn't rename it back then.
So reverting to the old function name but preserving the fix.

Fix scroll on native

---

src/state/queries/notifications/feed.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/view/com/composer/Composer.tsx
src/view/screens/Profile.tsx

- 6282452911f30fe2f682d7553bf6724ee690556e Don't poll for new posts on profiles. This is a nice-to-have, and the extra load isn't worth it right now.
- 4a0cc3048e36475980779a1dcce9cec361f951c1 Don't confirm new posts have hydrated in the appview. This won't cause any errors; it just means that in the case when a new post is meant to automatically load into the feed view, there is the potential that it won't if the appview hasn't hydrated in time.
- 99557568b02ff6bfa52a420b8e7fe85b940bccb8 No-change-to-behavior optimization, just updates the notifications background query so that it doesn't `getPosts` needlessly.

Additional reductions in request traffic

---

src/state/queries/my-lists.ts

Mixed use here. What we need:
- `Lists` screen — shows all _your_ curate lists
- `ModerationModlists` screen — shows all moderation lists including _yours_ and _those you subscribe to_
- `UserAddRemoveLists` modal — all _your_ lists, NOT including lists you subscribe to
- `Threadgate` modal — all _your_ curate lists
This PR prevents `UserAddRemoveLists` from requesting `all` which previously include modlists you subscribe to (made by others). It does this by adding a new filter `all-including-subscribed` that has the same functionality as `all` did previously.
For now, `all` doesn't really do anything, bc by default this query returns only your curate/mod lists and nothing else.

Clarify MyList filter intent

---

src/state/queries/util.ts

This was showing up in profiles.

Don't validate embeds when traversing cache

---

src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/state/persisted/legacy.ts

This is NOT done. We need to handle a comma-sep locales value in the language settings too.

Patch bad migration, sanitize bad value

---

src/locale/__tests__/helpers.test.ts
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts
src/state/preferences/languages.tsx
src/view/screens/LanguageSettings.tsx

Just wanted to add some type hints and precautions. We can't enforce the value at the storage level unless we do another migration, but we can help ensure we continue using valid values going forward.

i18n settings improvements

---

src/lib/routes/links.ts

This was broken because we pass `''` in one case (from `FeedSlice`), and `isInvalidHandle('')` is `true`. I figured I'd fix it here since `isInvalidHandle` seems to be about a very specific concept that's distinct.

Fix View Full Thread

---

src/lib/api/feed-manip.ts
src/lib/api/feed/custom.ts

Keys were changed to be auto-numbered in an attempt to ensure we never hit duplicate react keys. That approach unfortunately hurt performance and led to state corruption as react would reuse state across components that have the same key.
The change was done out of an abundance of caution. I'm still not 100% sure we never duplicate react keys but I wasnt able to trigger it, whereas the state corruption is happening a lot, so this is the move.

Go back to content-driven slice keys in feeds

---

src/view/com/util/UserPreviewLink.tsx

What this PR does:
It adds a check for `isAndroid` in the `UserPreviewLink` component which means that there will no longer be a profile modal preview on Android devices.
Success criteria:
After this PR is merged, we would like to see a reduction crash rate back to baseline as observed on Play Store Console. Currently, it is 1-2 standard deviations above baseline.

Attempt Android crash fix

---

app.config.js
plugins/withAndroidManifestPlugin.js

Can test with `yarn prebuild -p android` and inspect the built file.
Some android users hit this error when they try to add images to posts:
It looks like this is caused by large images running out of memory (https://github.com/expo/expo/issues/12167). Increasing the heap size [may come with downsides](https://stackoverflow.com/questions/27396892/what-are-advantages-of-setting-largeheap-to-true) but without a clear repro it's hard to establish if this is in our control. If we roll this out, it should be phased so we can monitor error rates.

Add largeHeap to AndroidManifest.xml

---

src/state/session/index.tsx
src/view/com/modals/VerifyEmail.tsx

Adds an effect that closes this modal if it's opened without a `currentAccount`. I added some logs too that should help us diagnose if we ever see this again.

Add fallback to email reminder modal

---

src/lib/hooks/usePalette.ts

Easy win.
Changes in https://github.com/bluesky-social/social-app/pull/2200 weren't enough to skip Feed re-render on scroll down/up.
Changes in https://github.com/bluesky-social/social-app/pull/2200 *are* enough to skip Feed re-render on scroll down/up.

Memoize usePalette

---

package.json
src/state/queries/notifications/feed.ts
src/state/queries/notifications/types.ts
src/state/queries/notifications/util.ts
src/view/screens/Notifications.tsx
yarn.lock

- 678bb587888bc92a32a28cfde02eeb43aeb25c6c Updates mobile to never do an in-place load of content on the focus event to avoid a sometimes surprising loss of your current scroll position
- 98147c7dfc3cc7d81e5afbe7d4ad5990fafdc3c8 Uses the new `seenAt` response from `listNotifications` to more consistently calculate unread state and more consistently clear unreads

More notifications improvements

---

src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/view/com/posts/Feed.tsx

- f5a1f61aa7facfc802e914d42de57a26a685c1f7 Updates the post feed to not show both an error message and an empty message (block somebody and look at their profile for an example of why)
- a9b4860a7fb825774a07ee4c3c7f85bd826117d8 Adds a limit to attempts to fill the first 30 posts to 6 fetches to cap the amount of traffic we generate

Feed bugfixes

---

src/lib/ScrollContext.tsx
src/lib/hooks/useOnMainScroll.ts
src/view/com/feeds/FeedPage.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ListMembers.tsx
src/view/com/lists/MyLists.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/notifications/Feed.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/posts/Feed.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/util/List.tsx
src/view/com/util/MainScrollProvider.tsx
src/view/com/util/ViewSelector.tsx
src/view/com/util/Views.d.ts
src/view/com/util/Views.jsx
src/view/com/util/Views.web.tsx
src/view/screens/Feeds.tsx
src/view/screens/Notifications.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx
src/view/screens/Search/Search.tsx

Stacks on top of https://github.com/bluesky-social/social-app/pull/2197.
This is a pretty chunky refactor but it's meant to mostly keep the data flow as is (with less plumbing).
The main change is we no longer pass down two things:
- `isScrolledDown`. This is now maintained by whoever renders `<List onScrolledDownChanged={...}>`.
- `onScroll` et al (`onBeginDrag` / `onEndDrag` / `scrollEventThrottle`). These are now in context (pager or top level).
More detailed:
- The new `List` abstraction has `onScrolledDownChanged` (similar in spirit to `onEndReached`). You can use this to track `isScrolledDown` yourself next to the list. This is nice because it is *used* very close to the list in most cases. So it's just local state where it's needed. (In the future, we could make this use …

Make scroll handling contextual

---

src/view/shell/desktop/LeftNav.tsx
src/view/shell/desktop/RightNav.tsx

(English ver. by BIng Translation)
cf： https://github.com/bluesky-social/social-app/pull/2209#issuecomment-1857940070 ( @tkusano )
Dear Administrators of this Repository,
Hello.
When I was working on Japanese localization ( https://github.com/bluesky-social/social-app/pull/2209#issue-2040986838 ), a colleague discovered a problem that the GUI display was distorted in the early version of Japanese and that "Profile" was not displayed in Japanese.
With this fix, "NewPost" and "Profile" will be displayed correctly in the selected language, and other languages will be served more smoothly.
I hope you will join us in Merge.
Hima
(Original (Japanese))
関連： https://github.com/bluesky-social/social-app/pull/2209#issuecomment-1857940070 ( @tkusano )
このリポジトリの管理者のみなさん
こんにちは。
日本語のローカライズ作業をしていた（ …

Fix: Some display issues

---

bskyweb/templates/home.html
bskyweb/templates/post.html
bskyweb/templates/profile.html

- handle missing content (PWI opt-out) better
- use opengraph "article" and "profile" types, not just website for everything
- fix timestamps, and used indexed at not created at
- remove site-level twitter handle from most card meta
This is golang HTML template code (using django/jinja2 template language), but I hope should be easy to review what it is doing.

tweak social card meta yet again

---

docs/localization.md
src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po

- Change file name to `localization.md` in the docs folder
- Add a section on where to find credits for our amazing community contributors who helped refine the translations for certain files
- Run `intl:build` again

Add credits to localization doc

---

src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/screens/ProfileFeed.tsx

There are some instances where `colors.red3` is used instead of `colors.like`, which results in a much-complained-about difference between the heart icon and the text next to it when a post is liked.
This PR uses `s.likeColor` everywhere, increasing consistency.
Fixes #2223

Make like colour consistent across the app

---

bskyweb/cmd/bskyweb/rss.go
bskyweb/cmd/bskyweb/server.go
bskyweb/templates/profile.html

Adds a basic public RSS feed for profiles:
- RSS 2.0 (not atom)
- uses public API; no other special caching
- link is in HTML metadata, making auto-detect possible, but no visual indication in-app of course
- respects PWI opt-out
- only top-level posts from the account (eg, no re-posts)
- pretty basic formatting: facets, embeds, other metadata, pretty much just the post text
- I'm not really sure what the idiomatic way to put microblogging content in an RSS feed is: content in the description, handle in the title?
- used AT-URI as the GUID; seems like that should work?
- uses DID in the path, so handle updates don't break feeds

basic public RSS feed for profiles

---

src/lib/analytics/types.ts
src/state/session/index.tsx
src/view/com/auth/create/CreateAccount.tsx

The `track` function for Create Account is moved to the actual function where the account is created and now fires reliably.
`Create Account` has been used in favor of `Create Account Successfully` which has been dropped.
`Try Create Account` is also being tracked

Fix Create Account metrics

---

src/view/com/modals/Confirm.tsx
src/view/com/modals/Modal.tsx

This is a known bug. Basically the issue was that the modal was being `expanded` to the largest position. Now we just snap to the first position.

Fix 2231 Modal overlap on double modal open

---

src/view/com/composer/text-input/TextInput.tsx

Followed docs to set a fixed # of lines. I used a red background to view changes in the inputs height, and on small phones and a link card, the input does get squished. This ensures there's always at least 4 lines of space.
As per docs, this also required adding the `textAlignVertical` for Android.

Set numberOfLines for Android text input

---

src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po
src/view/com/modals/AppealLabel.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

Applies for the highlighted post in a thread only. Other post views do not allow appealing their labels.

Move label appeal to post dropdown

---

package.json

This PR adds `yarn intl:compile` to the postinstall hook.
```diff
-    "postinstall": "patch-package",
+    "postinstall": "patch-package && yarn intl:compile",
```
This trips me up every time - hoping that this reduces the fricton of the i18n stuff for new contributors.

Add `yarn intl:compile` to postinstall hook

---

src/state/queries/actor-autocomplete.ts
src/view/screens/Profile.tsx
src/view/shell/desktop/LeftNav.tsx

Fixes autosuggestion so it doesn't match on `'invalid.handle'` if the user has an invalid handle.
Before:
After:
I also found a couple of places where a comparison was done to `'invalid.handle'` and replaced it with the `isInvalidHandle` utility.

Invalid handle autocomplete

---

src/view/com/composer/text-input/web/EmojiPicker.web.tsx

Okey, I know somebody must have explicitly turned this feature off by stating `autoFocus={false}` in the `EmojiPicker`, but as an end user it feels really weird to me not to have this auto-focus (I realized several time I was typing my search query directly in the post's content).
Maybe there is a good reason it was deactivated in one specific scenario? At least on my standard desktop browser I believe autofocus is a nicer UX.

Restore autofocus on emoji drop down

---

src/view/com/modals/AltImage.tsx

This fixes that the preview image in the alt text modal is cropped if it doesn’t fit the outer box. That makes writing an alt text, especially if it is text-only (such as in the example below), a lot easier.
The fix is done by changing the `contentFit` on the preview image [from the default](https://docs.expo.dev/versions/latest/sdk/image/#contentfit) (`cover`) to `contain`.
| Device | Before | After |
| --- | --- | --- |
| Mobile | ![image](https://github.com/bluesky-social/social-app/assets/28510368/a6c4269a-a5ee-4ba9-a026-568f7e8c8ac4) | ![image](https://github.com/bluesky-social/social-app/assets/28510368/3f9eb155-f989-41cc-88bf-9c6c81c9652a) |
| Desktop | ![image](https://github.com/bluesky-social/social-app/assets/28510368/4116c7d2-f8b1-44b3-a508-00597c24438f) | …

Fix image is cropped in alt text modal

---

package.json
yarn.lock

While testing android in the sim I was able to trigger one of our crash conditions. It happened when using the slide gesture to open the drawer and releasing the gesture. The error stack tracked with https://github.com/react-navigation/react-navigation/commit/3cfb3e63949f0aa6f4b14db02161dd88fd10cb12 which merged in [4.0.0-alpha.1](https://github.com/react-navigation/react-navigation/blob/main/packages/react-native-drawer-layout/CHANGELOG.md#400-alpha1-2023-09-25). Tested this, seemed to work fine.

Bump react-native-drawer-layout@4.0.0-alpha.3

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ListMembers.tsx
src/view/com/lists/MyLists.tsx
src/view/com/lists/ProfileLists.tsx
src/view/com/notifications/Feed.tsx
src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/posts/Feed.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/util/List.tsx
src/view/screens/Feeds.tsx
src/view/screens/Search/Search.tsx

We always render the same `RefreshControl`. Moreover, this prop has some weird behaviors and from what I recall you can’t actually put some different kind of content there. So I think it makes sense to tighten the control for it and to get back to the `refreshing` and `onRefresh` shortcut props. This is the main FlatList API for this anyway — I think we only use the `refreshControl` because we wanted custom colors and offset, which doing it in `List` solves.
(If we later decide to support a customizable `refreshControl` again, we should make it a render prop like `refreshControl({ headerOffset })` because it needs to know the layout information.)
---
These are always either missing or used together for the same goal, and in those scenarios forgetting one would cause a bug. Let's lock it …

Consolidate List props 

---

bskyweb/cmd/bskyweb/rss.go
bskyweb/cmd/bskyweb/server.go
bskyweb/templates/profile.html

- use the fully qualified URL in the profile view HTML head `<link>`
- use the actual request Host as hostname in RSS (not hardcoded to `bsky.app`). note that it is still hard-coded to `https://`, so not perfect for local dev, but should fix staging etc
- handle `/profile/{handle}/rss` as an HTTP 302 (non-permanent) redirect to `/profile/{did}/rss`, as a UX affordance
I think this the is last round of enhancements I can afford to spend time on right now. Eg, not planning to bite off Atom feeds in the near future (though it probably isn't a ton of work, can just copy the current RSS code).
cc: @scripting

yet more RSS tweaks

---

src/state/queries/actor-autocomplete.ts
src/view/com/lists/ListMembers.tsx
src/view/com/profile/ProfileCard.tsx
src/view/screens/ModerationBlockedAccounts.tsx
src/view/screens/ModerationMutedAccounts.tsx

I hastily added a moderation filter on profile cards while adding the PWI behaviors. This missed that we don't want this behavior in 3 settings:
1. Muted users list
2. Blocked users list
3. Curation/moderation user lists
This PR fixes that. I also reviewed the other cases ProfileCard is used and I believe we do want this filter in all of them.
Additionally, the `moderation.account.filter` is true when users are muted, and in some cases that's too extensive (autocomplete, any user listing) so this relaxes that as well.

Fix some account filtering behaviors

---

src/state/queries/feed.ts
src/view/screens/Home.tsx

We use `usePinnedFeedsInfos` to populate the home tabs. That hook will output a truncated array while it finishes loading. We populate `initialPage` for the pager using the preferences directly. That means we were rendering the `<Pager>` with an initialPage set to a higher value than the number of pages. This was quietly dying in prod and somehow never triggering in the simulator, but when run on the build pushed directly to device it finally gave this:
Not super useful on its own, but the index value was the clue I needed because it correlated to the tab I was last on. Thank god.

Fix blank home screen (close #2281)

---

src/view/com/posts/Feed.tsx

Closes #2296 
The feed component was only looking at the first page of posts to establish if a feed is empty. If somebody has been replying a lot, their profile's main tab will filter out that entire first page, leading that `isEmpty` to be true. Other code, however, uses more complete is-empty logic, causing the UI state to vacillate between the empty behavior and the fetch more behavior.
Making the `isEmpty` check more complete fixes that.

Fix: dont incorrectly mark a feed empty based only on the first page (close #2296)

---

src/lib/strings/embed-player.ts

Twitch requires parent param, use the window hostname if on web, otherwise use `localhost` on native.

use the window hostname on web for twitch embeds

---

src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po
src/view/com/composer/Composer.tsx

There have been a lot of attempts to share youtube videos where no metadata is extracted into the link card. The only way I was able to reproduce that was by not waiting for the link card to finish fetching.
This isn't an ideal way to solve that, but it does solve it: it stops the user from posting while it's loading.
Closes #2328

Stop the user from posting before the link card finishes loading

---

src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts
src/view/com/notifications/FeedItem.tsx

- 192c43b30b78cb8cfa6586d36d93cc672a6af696 Makes sure the notifications badge on the app icon gets cleared out
- b6eb191018bed9e3504b4263ee02e9263598ee13 Fixes notifications for likes on your custom feeds
Closes #2275

A couple notifications fixes

---

src/view/screens/Notifications.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

- fcc6d770b71fd7a0e9a5db09429b6c6fb412037e Adds soft-reset to feeds and lists (makes it so clicking the header title works again)
- 14653ef1152f5720cda463b5a1aea7f981e2a4e4 Fixes an issue that was causing the notifications to keep listening to soft resets when not focused

Fixes to feed load triggers

---

bskyweb/cmd/bskyweb/server.go
bskyweb/templates/post.html

in the og spec this is an array: https://ogp.me/#array
this has been used by other large sites (for example twitter, before they removed all the meta tags anyway), so it shouldn't be dangerous

support multiple og:image tags

---

src/lib/ThemeContext.tsx

The [PR in question](https://github.com/facebook/react-native/pull/39439) was merged in late September.
I can't find what release it was actually included in, but according to [their release docs](https://reactnative.dev/contributing/release-faq#when-will-my-fix-make-it-into-a-release), it should be in there by now. Plus, I built locally and couldn't replicate what we saw before: flashing of the theme dark-light-dark upon foregrounding the app.

Remove patched color scheme code

---

src/view/com/util/forms/NativeDropdown.web.tsx

Fix #2345, fix #2332, fix #2348
No changes to functionality or styling on native or desktop web.
On mobile web with the dropdown open, scroll is disabled, and touches outside won't propagate to touchables below until the dropdown is closed.
The on-press styles weren't reliably applying previously, and Radix seems to be overriding styles here too, so I just left them out. Focus styles appear as normal.
While we're here I also added close-on-escape, and changed the trigger from `onPointerDown` to an `onPress` which should help with accidentally triggering it when scrolling on mobile.

Web dropdowns

---

src/view/com/util/forms/SearchInput.tsx
src/view/screens/Feeds.tsx
src/view/screens/Search/Search.tsx

Hopefully I am not PR spamming here...apologies if so. This is just some very minor changes but with very noticeable UX improvements:
- Add a hitslop to the cancel and clear buttons on the search screen (and the clear button on the feeds screen search). These are currently rather difficult to press
- Add `keyboardShouldPersistTaps` to`SearchScreenSuggestedFollows`, `SearchScreenMobile` (autocomplete results), and `Feeds`.  Currently you have to dismiss the keyboard before any interaction with the screen can be made.
- Dismiss the keyboard on scroll on `SearchScreenSuggestedFollows`, `SearchScreenMobile`, and `Feeds`. This resolves issues where some content is hidden below the keyboard.
On the last issue, this is certainly a good fix (both in terms of ease and feel). The alternative would …

minor search screen ux improvements

---

src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts

After what happened with German, we're slowing these down until we can get more thorough reviews

Disable spanish translation until it's more thoroughly reviewed

---

src/view/com/modals/report/InputIssueDetails.tsx
src/view/com/modals/report/Modal.tsx
src/view/com/util/BlurView.android.tsx

Something is horribly wrong here.
We've had various reports from users that a `<TextInput>` will drop user input. Then we got #2344 reported, which gave us two lucky breaks:
1. [A video](https://www.youtube.com/watch?v=e66IKwV7vi4&t=17s)
2. I could repro it in the simulator, thank god
With the repro I massively struggled to figure out the _cause_ of this. Here are all of the bizarre behaviors:
- The input does actually occur, it's just that the text is invisible. You can actually select the invisible text.
- The `onChange` fires and the value is updated and the correct string is passed into the `<TextInput>`.
- Despite the value updating, the `<CharCounter>` wasn't updating either.
I tested a variety of possible causes. I pulled out everything to do with BottomSheet. I removed all …

Disable BlurView on android

---

src/Navigation.tsx

Closes #2308
Users have been reporting that Following/Follower pages are empty, and also that some pages are weirdly "dimmed."
I traced this to react-navigation's animations bizarrely failing to complete. Disabling them fixes it. I'm not inclined to dig deeper into the cause right now.

Disable page-transition animations on android

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx

For some reason, avatars were not consistently showing in the lightbox. I was able to repro this by going to a profile and tapping the profile multiple times -- after the first time, it would consistently fail to show. For some reason, this doesn't happen for embedded posts.
I tried changing a number of things in the lightbox to isolate the cause, and ultimately narrowed it down to the caching behavior. No idea _why_ but memory caching solved it.

Use memory caching for android lightbox

---

src/view/shell/desktop/LeftNav.tsx

#2219 took the width limit off the new post button. This PR fixes it by wrapping in a flexbox that should autosize correctly.

Fix sizing of the leftnav new post btn

---

src/view/com/auth/create/CreateAccount.tsx

Closes #2333 
No idea why, but for some reason the `<KeyboardAvoidingView>` is triggering a UI freeze on iOS prod only. This is quite unfortunate because it breaks account creation. I checked the other places it's used and no freeze seems to occur, so there's something about the create-account UI specifically that experiences this.
This PR removes it and just puts a pad at the bottom of the screen. Tested on iOS (on device), Web, and Android (simulator).

Remove the KeyboardAvoidingView in account creation (close #2333)

---

src/view/com/composer/text-input/web/EmojiPicker.web.tsx

I was going to open an issue, but I figured this would be a quick CSS fix I could do. Currently when opening the emoji picker on web, you can't close it in a significant amount of screen space due to the `padding` lacking pointer events. See attached screenshot. There's a `padding-right: 50px` as well that seems unavoidable regarding `marginHorizontal: auto` without something hacky to my hobby-level CSS knowledge in order to get the emoji picker to line up, but changing the `padding-top` to `margin-top` mostly resolves the issue. There are no secondary effects that I can tell due to the vertically fixed position of the emoji picker and post composer.
As a side note, it'd be nice if SHIFT+LMB did not close the emoji picker in order to allow for multiple emojis to be selected similar to how …

Change paddingTop to marginTop for web emoji picker (EmojiPicker.web.tsx)

---

src/view/screens/PreferencesThreads.tsx

This PR adds marks for localization to options in "Thread Preferences" screen.
Many thanks!

Localize options in "Thread Preferences" screen

---

src/Splash.tsx

See: https://bsky.app/profile/sndtrkng.bsky.social/post/3khr3vnm5cm2m
I ran into this while testing a different PR and marked it up as an emulator issue, but it doesn't seem to be. It actually looks like some sort of issue with `MaskedView`. On platform versions <= 25, the `maskElement` doesn't seem to work at all. I suspect it is something to do with this: https://github.com/react-native-masked-view/masked-view#androidrenderingmode
Setting that prop to `software` doesn't help though. I don't think there's a very large number of people on <= 25 so *probably* this isn't affecting too many users, but there are some. Maybe you can find a better fix 🤷‍♀️
Of note though, it doesn't matter *what* you set as the mask element. An empty `<View />` will cause the issue, so it might not be an …

hackfix for android splashscreen on api <= 25 (white screen)

---

src/state/shell/composer.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/web/EmojiPicker.web.tsx
src/view/shell/Composer.web.tsx

Fixes: https://github.com/bluesky-social/social-app/issues/2390
Fixes: https://github.com/bluesky-social/social-app/issues/2389
Fixes: https://github.com/bluesky-social/social-app/issues/1425
Demo: https://www.youtube.com/watch?v=eGJY9y7i4BY&feature=youtu.be
Right now the picker is being presented as a button dropdown. This limits the "mobility" of the picker, as we cannot control where it's going to be displayed at on the screen.
This creates some issues like what we see here: https://github.com/bluesky-social/social-app/issues/2389
Instead, we want the picker to be movable about the entirety of the screen so that we can adjust to the position of the cursor.
First, we need to move the picker outside of the composer modal so that we can set the position to anywhere on the screen. We do so …

emoji picker improvements

---

patches/expo-image-picker+14.7.1.patch
src/lib/media/picker.shared.ts

fixes https://github.com/bluesky-social/social-app/issues/1617
Right now, expo-image-picker is using `PickVisualMedia`. This does not support the "Browse" option to select files elsewhere on the device except the gallery. Instead, we want to use `GetContent`. See https://android-developers.googleblog.com/2023/04/photo-picker-everywhere.html
This patches expo-image-picker to do so. Tested on SDK 34, 28, and ~~23~~  25. Tested accessing images from files as well as Google Drive with good success.
This is meant to be a temporary fix, and I didn't implement the logic for selecting videos. It's only a few extra lines, however we have to be careful that we properly create the intent (the mime can't be anything other than `image/*` or `video/*` otherwise it won't use the image picker).
We also …

patch expo-image-picker to support "browse" on android

---

src/view/com/modals/AltImage.tsx

Closes #2315 
On android, the `<KeyboardAvoidingView>` is miscalculating the keyboard behavior when the keyboard is closed, causing the bottom half of the interface to get clipped. In this PR I switched it to the bottom sheet, which in a shocking turn of events handles this much better.
Tested on iOS and Android, including on-device for Android.

Rework alt-text input to use bottom sheet

---

package.json
src/Splash.tsx
yarn.lock

Hi 👋
`react-native-bootsplash` author here. I noticed, when using your app, that the splash screen implem doesn't wait for the first render to hide the native splash. This result in a white flash, which is not great given the fact that it's our first experience with the app.
This PR fixes this (without switching lib, I only removed `react-native-splash-screen` as it's unused and autolinked / built for nothing)
**Before (notice the blink) 👇**
https://github.com/bluesky-social/social-app/assets/1902323/a2279214-fce7-46cf-8f8d-9816af8440b8
**After 👇**
https://github.com/bluesky-social/social-app/assets/1902323/5d38486d-5af9-40a2-b85d-3b87e982ccb6

Remove splashscreen blink

---

src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx

This resolves https://github.com/bluesky-social/social-app/issues/2326 as well as normalizes the active/inactive logic on all platforms.
1. The position of the item in the feed never actually changes on native, since landscape is disabled in the app. Therefore, when the screen rotates in the native full screen player, we need to take that into account. Here we will use either the window height when in portrait or the window width when in landscape to get the "real height" of the feed. Desktop behavior stays the same. This is working on both iOS and Android now.
2. Instead of checking against static values like 0 and screenHeight when determining whether or not to dismiss the player, we instead use the safe area insets.
- If the bottom of the player reaches the top of the safe area, then …

Fix various issues with screen dimension detection in external player

---

src/view/screens/Settings.tsx

This PR adds marks for localization to the option to make alt text mandatory, which is left out of the localization in the Settings screen.
Sorry to disturb you with minor localization patches.
Many thanks!

Localize the option to make alt text mandatory

---

src/locale/locales/fr/messages.po

This pull request tries to improve the French localization effort that was already done earlier this month in #2265 (quite well, actually! Congratulations, coming from a native speaker who is nitpicky about translations in software products! 💛).
- Add missing translations (I just run `yarn intl:extract` and translated the empty ones)
- Always use French guillemets («») when applicable — it was already done so congrats for that, but some English ones still slipped through
- Always add an article (le/la/l’) before nouns — those should never be omitted in my opinion, that is never done in other software products unless there are very hard space contraints
- Use … character instead of three dots
- Change _"Mettre en sourdine"_ into _"Masquer"_, used in other similar products to translate …

Improve French localization

---

src/lib/media/manip.web.ts
src/lib/themes.ts
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/post-embeds/index.tsx

Supersedes (and builds upon) https://github.com/bluesky-social/social-app/pull/2379
- https://github.com/bluesky-social/social-app/pull/2379 Fixes the black-box around link card thumbs (thanks @haileyok !)
- 2100f0adc02a1868532ab434f2621da33506f095 Updates desktop link cards to look the same as mobile does
- e4e616ba58334fa3d890c713f467163d7861c40f and 08017c0d77b489a5d808728a988a696f4456d708 Improves the desktop link card and quote post hover behaviors to darken the border on the elements rather than weirdly underlining all the text
https://github.com/bluesky-social/social-app/assets/1270099/2418c84c-0093-4d19-99b5-f7b27cec74dc

Multiple improvements to link cards and quote posts

---

src/lib/constants.ts

Fix #2313 
What this PR does is **assumes we're in production unless we match a localhost PDS URL, OR our staging PDS URL.** This means that the SANDBOX warning labels **only show for local dev and on staging.**

Update IS_PROD check

---

src/locale/languages.ts

Add Portuguese Localization #2407

Update Portuguese for Português

---

__e2e__/util.ts
package.json
tsconfig.e2e.json
yarn.lock

This fixes a bunch of things that mysteriously broke with the recent expo update.

E2E runner fixes

---

src/lib/api/feed/merge.ts
src/lib/constants.ts
src/view/screens/Home.tsx

- 7bd9d9ebc01f4b7e10a1f35a6eb48ac8a4f5ca90 Restores discover to default feeds for new users (should not have been removed)
- 1cb9abad3544c2367fdd3ffd2b18f7079e29229b Updates the mergefeed emergency fallback to only source from discover
- 736aeca7f93f226548631a056eddc2da34be02d4 Makes sure the mergefeed always returns a cursor, which protects against a case where the emergency mergefeed might give the "end of feed" condition prematurely. That has the potential to create an endless spinner if the mergefeed is actually out of posts, but that's very unlikely with multiple custom feeds, while the more likely issue is that the emergency mergefeed will glitch out.
All of this is a temporary solution to ensuring that new users get content after signup. We will replace all of this in the near …

New user home feed fixes

---

src/state/queries/app-passwords.ts
src/state/queries/invites.ts
src/state/queries/notifications/unread.tsx
src/state/queries/post-feed.ts

We're still trying to track down the excessive web traffic. This PR makes two changes:
- 4e7c886fb2c21497b48e00325ae5bc0a97b0796d Stop auto-refetching app passwords and invites on an interval
- bd62ce7668b1ea57654a5dede4990ef738dabcae Stop polling posts and notifications when the tab is backgrounded
The second commit is likely to reduce traffic dramatically on web, where people often have multiple tabs open

Reduce web requests

---

__tests__/lib/string.test.ts
bskyweb/cmd/bskyweb/server.go
package.json
src/Navigation.tsx
src/lib/analytics/types.ts
src/lib/link-meta/link-meta.ts
src/lib/routes/types.ts
src/lib/strings/embed-player.ts
src/routes.ts
src/state/modals/index.tsx
src/state/persisted/legacy.ts
src/state/persisted/schema.ts
src/state/preferences/external-embeds-prefs.tsx
src/state/preferences/index.tsx
src/view/com/modals/EmbedConsent.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/util/post-embeds/ExternalGifEmbed.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx
src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx
src/view/icons/index.tsx
src/view/screens/ExternalEmbeds.tsx
src/view/screens/PreferencesExternalEmbeds.tsx
src/view/screens/Settings.tsx
yarn.lock

Supersedes https://github.com/bluesky-social/social-app/pull/2353 by:
- Updating routing 
- Tuning UIs in the consent settings and modal
- Simplifying copy for the consent settings
- Adding an "allow all media embeds" button in the consent modal
Inherited from the original PR:
implements https://github.com/bluesky-social/social-app/issues/2314
fixes https://github.com/bluesky-social/social-app/issues/2338
fixes https://github.com/bluesky-social/social-app/issues/2386
fixes https://github.com/bluesky-social/social-app/issues/2357
- Twitch clips embeds
- Twitch video embeds
- YouTube mobile embeds
- International spotify embeds
- Adjust aspect ratio for YT shorts
- Vimeo
- Apple Music
- Tenor
- Giphy
- Consent modal
- Per-service consent setting
iOS: …

Additional embed sources and external-media consent controls

---

src/locale/locales/ja/messages.po

This PR adds translations for newly introduced messages, and also corrects language code (ISO 639-1).
Dear @Hima-Zinn @tkusano @dolciss @oboenikui
I would appreciate your review and feedback on these text updates.
Many thanks!

Update Japanese localization (addition + language code correction)

---

src/Splash.tsx

Makes sure mask animates on Android, and improves fallback for <v25

Use android mode, improve fallback

---

src/locale/locales/ko/messages.po

Fixed some existing translations and translated newly updated strings from version 1.63.
Thanks!

Update Korean localization

---

src/Splash.tsx

This PR abandons the mask in Android entirely. I tweaked the animation speed a bit to look better without the mask, looks good with mask (iOS) too.
Android:
https://github.com/bluesky-social/social-app/assets/4732330/05ac5fe5-8c7f-448e-8c05-9139ec6f7d6f
iOS:
https://github.com/bluesky-social/social-app/assets/4732330/cbdaf55d-f62e-4064-96a8-e3538df2972c

Don't use mask for android at all

---

src/state/queries/actor-autocomplete.ts

Case shouldn't matter when making autocomplete suggestions, and followed users should be prioritized but without converting the prefix to lowercase, they are not.
Here, convert the prefix to lowercase in the respective query. 
Before:
After: 
fixes https://github.com/bluesky-social/social-app/issues/2430

convert prefix to lowercase in actor autocomplete query

---

src/state/shell/composer.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/screens/PostThread.tsx

Small addition for something that really bothers me. When replying to a larger post, we lose the ability to see the full context of the post. Sometimes I find myself needing to copy my reply and discard it real quick to see the full post...
This just makes the reply to area a pressable and adds a little `LayoutAnimation` to the expand/collapse so it looks pretty. Also displays images in a square similar to how Twitter does when applicable, as well as shows the text of the quoted post.
https://github.com/bluesky-social/social-app/assets/153161762/961c163d-d8f5-48cc-b3f8-a26c0b3ebccc
https://github.com/bluesky-social/social-app/assets/153161762/3ca6559e-b3bf-4e3e-9d8c-072920a7538b

add expandable context to composer when replying to post

---

src/view/com/composer/Composer.tsx

1. Rerun `yarn intl:build`
2. Add `context` to `<Trans>` to differentiate between post verb and noun

Post verb vs. noun differentiation in localization

---

bskyweb/templates/base.html
web/index.html

Fixes https://github.com/bluesky-social/social-app/issues/2463
Adds `color-scheme: dark` when dark theme is used, this turns scrollbars and native input elements to the appropriate dark-theme versions.

Add the appropriate color-scheme for dark mode

---

src/lib/react-query.ts
src/state/queries/notifications/types.ts
src/state/queries/notifications/unread.tsx
src/state/queries/preferences/index.ts
src/state/queries/profile.ts
src/view/com/feeds/FeedPage.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Feeds.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

- a4c51da869f321a9f39f2da253e76566bb6f4450 Stops fetching preferences and profiles on an interval and instead does it on focus (close #2454)
- 7f9827674b1f8900457ba5f9b925b2a0926fbc56 Makes it possible to refresh the saved feeds in the feeds screen
- 2963d5789c1a7f02f7227636c1264465e6d982f2 and b7686080c9868777feb79daece148d8777412b32 Reduces feed and notifications polling if there's known notifications (close #2451)
- 4d87706c3513edc58c0200d3849eb0b5d723f2ca Disables the hard refresh after 1 hour to test if that's the cause of the random reload on start bug

Reduce polling

---

src/view/com/util/post-embeds/QuoteEmbed.tsx

External embeds are not currently displayed in a quote post, which results in context loss.
I also think it makes more sense here to remove the `.find()` since - unless this is done in anticipation of future changes - there will never be more than a single embed for a post: https://github.com/bluesky-social/atproto/blob/50f70453a9e49621956e4e820226c0e220fe138e/packages/bsky/src/services/feed/views.ts#L434 (thanks @mary-ext). Instead we just need to get the first possible embed from the array.
We do still need to check for types, since we don't want to show a quote's quote.
Of course we could add
```tsx
const externalEmbed = React.useMemo(
() =>
quote.embeds?.find(
embed =>
AppBskyEmbedExternal.isView(embed)
),
[quote.embeds],
)
```
but this feels like some additional logic that isn't …

fix rendering of external in quote embeds

---

src/lib/strings/rich-text-helpers.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1742
- Adds a `richTextToString` function that looks at the rich text facets and adjusts the URL being copied as necessary
- Wire it up into the "Copy Post Text" functionality
If an invalid/misleading link is being copied, we use the `[label](url)` format, but otherwise it just unfurls the url, based on https://github.com/bluesky-social/social-app/issues/1742#issuecomment-1779051689

Use the RichText facets when copying post text

---

lingui.config.js
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts

I reordered the locales alphabetically.
Other fixes include:
* https://github.com/bluesky-social/social-app/blob/c75771047cb49a2cd529f72a2756a456c843a730/lingui.config.js#L3 There were two `es`, so I removed one.
* https://github.com/bluesky-social/social-app/blob/c75771047cb49a2cd529f72a2756a456c843a730/src/locale/languages.ts#L27-L37 Corrected `Indonesian` to `Bahasa Indonesia`. (since they are all written in their own language)
Thank you!

Reorder the locales alphabetically

---

src/view/screens/Search/Search.tsx
src/view/shell/desktop/Search.tsx

Potentially fixes https://github.com/bluesky-social/social-app/issues/2443
Potentially fixes https://github.com/bluesky-social/social-app/issues/1648
I can't reproduce this, but `autocomplete=on` was being put on text inputs, that means the browser gets to make its own judgement on what it should be autocompleting, so let's turn it off and see if this magically solves the issue.

Don't set autocomplete on search input

---

src/locale/locales/uk/messages.po

Shortens a few strings where context allows and reduces the chance of invite code count clipping in the side drawer on mobile devices.

Update Ukrainian translation

---

src/view/com/util/MainScrollProvider.tsx

On native, the minimal shell is shown/hidden in sync with the gesture. However, on the web, this doesn't work well because we don't actually know when the dragging starts and ends. We only get scroll events.
As a result, it gets "stuck" on the web in a half-visible state. This is especially confusing on mobile web where it's easy to mistap.
Let's make the web implementation show/hide simply based on whether we're scrolling up or down. I'm also forcing the header to always show for a little bit (first 200 pixels) so that it disappearing out of sync with the top post doesn't feel weird.
[Review without whitespace.](https://github.com/bluesky-social/social-app/pull/2499/files?w=1)
Should have no effect on native.
https://github.com/bluesky-social/social-app/assets/810438/94949aec-cf1b-40d5-a1 …

Toggle minimal shell on any scroll for web

---

package.json

Tiny fix to fix this error on `yarn build-web` - `cp --verbose` doesn't exist on macos but `cp -v` does.
```
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-aclpsvXx] source_file ... target_directory
error Command failed with exit code 64.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

package.json: cp --verbose doesn't exist on macos

---

src/state/session/index.tsx

This should address the multiple reports of unexpected signouts.
The issue was with users using multiple tabs on web. Both tabs would retain the same `refreshJwt` in memory, and refresh tokens can be used only once. So once a refresh token was rotated in tab A, the tab B _was_ notified but did not update that token on the `agent`, and so when tab B tried to get a new access token, `refreshSession` would fail.
This was a little tricky to pinpoint because if both tabs were periodically reloaded within the access token expiry window, our session handling would pick up the new refresh token from storage and continue as normal for a time. So this issue only existed in long-running multi-tab sessions.

Ensure sessions and tokens are synced between tabs

---

src/locale/i18n.web.ts

Fixes https://github.com/bluesky-social/social-app/issues/2303
Wanted to do it in `src/state/preferences/languages.tsx` to match `src/state/shell/color-mode.tsx` but that would've meant setting an unsanitized value which might be incorrect as translations changes/gets removed/etc

Set document lang attribute to the app language

---

src/lib/api/feed/custom.ts
src/lib/api/feed/merge.ts

Added an Accept-Language header (where the value is the user's Content Language selections joined by commas) to the three getFeed calls. There will be a PR on the backend to forward this header to the feed generator.

Add accept-language header

---

src/lib/api/feed/home.ts
src/lib/api/feed/merge.ts
src/state/queries/post-feed.ts
src/view/com/modals/DeleteAccount.tsx
src/view/com/posts/DiscoverFallbackHeader.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

Currently we're falling back to the "Discover" feed when the following feed comes back empty. We're doing this to patch over weaknesses in our onboarding, which 50% of users skip and therefore land on an empty feed. This is a temporary solution while we work to improve the onboarding; therefore this is a somewhat hacking temporary fix.
|Desktop|Mobile light|Mobile dark|
|-|-|-|
|![image](https://github.com/bluesky-social/social-app/assets/1270099/629e6e8a-694a-4c15-8483-dafaf4dc74d8)|![image](https://github.com/bluesky-social/social-app/assets/1270099/e6c9570e-19c0-4a51-9d59-1bc2d058dbb1)|![image](https://github.com/bluesky-social/social-app/assets/1270099/c4f794b4-409b-4d0d-bf2f-dfd5bd21e6fd)|

Add a new home feed-api wrapper and give a header indicating the fallback behavior

---

src/lib/api/feed/home.ts

There were in fact TWO bugs that didn't reveal themselves, and one bad logical choice
1. We were checking `cursor` instead of `returnCursor` (bug)
2. We werent resetting the `cursor` when switching to discover (bug)
3. We were checking the feed length, which is not the definitive "end of feed" condition

Fix the fallback to discover behavior on the home feed

---

patches/@lingui+core+4.5.0.patch

Fixes #2535 
Temp patch, see filed issue in Lingui repo https://github.com/lingui/js-lingui/issues/1836

Patch `@lingui/core` to fix `unraw` import resolution error

---

src/state/persisted/__tests__/migrate.test.ts
src/state/persisted/legacy.ts
src/state/queries/feed.ts
src/state/queries/notifications/unread.tsx

This PR stops sending 3 logs to Sentry as top-level issues (reduces to `info` level, sends as breadcrumbs which should be batched), and reduces one log from `error` to `warn` for monitoring.

Reduce some Sentry logs

---

src/view/com/posts/DiscoverFallbackHeader.tsx

Modify the position of the `<Trans>` in `DiscoverFallbackHeader.tsx`.
In some languages, the feed name need to be relocated when localizing.
Thank you!

Correct position of `<Trans>` in `DiscoverFallbackHeader.tsx`

---

src/locale/locales/fr/messages.po

Now that we have more opportunities to insert ~~baguettes~~ French everywhere in the app, let's do it.
This should also solves #2425 (ping @fenarinarsa), by removing all usages of `utilisateur` (who implies masculine humans), substituting them by `compte` (gender-neutral) or `personne` (gender-neutral). I struggled with `abonné`, to finally use the interpunct / _point médian_, like what Mastodon does (for example, `123 followers` is now translated `123 abonné·e·s`).
Beside that, fixed a few typos, moved from `nom d'utilisateur` for _username_ to `pseudo` (same as _handle_), again to remove `utilisateur` everywhere to fix #2425.

Update French localization with more strings

---

src/Navigation.tsx
src/view/com/modals/CreateOrEditList.tsx
src/view/screens/Search/Search.tsx
src/view/screens/Settings.tsx

There are excess l10n markups which produce meaningless `msgid`/`msgstr` pairs in message catalogue.

Remove excess l10n related markups

---

src/view/com/lightbox/Lightbox.tsx

fixes #2293 
| Android | iOS |
| ------- | --- |
| ![Android](https://github.com/bluesky-social/social-app/assets/34245032/d80defd6-c0a2-4aff-85b5-bc7ee832be3f) | ![iOS](https://github.com/bluesky-social/social-app/assets/34245032/b263caa7-1bd8-41bb-8013-41dfe0b04af5) |

fix: make alt text selectable in Lightbox

---

src/view/screens/Search/Search.tsx
src/view/shell/desktop/Search.tsx

Users seems to be getting confused about whether they're currently in the "autocomplete view" or the actual "search view" when trying to search for posts (https://github.com/bluesky-social/social-app/issues/849#issuecomment-1888569647). This pull request improves on the UI.
Not sure about the removal of borders on profiles, thought I'd do it to make the distinction between "Search for ..." and profile suggestions even clearer.
`Go to @handle` is powered by a regex that matches domain-like substrings, when it can find one, then it's shown to the user.
---
| --- | --- |
| ![image](https://github.com/bluesky-social/social-app/assets/148872143/25a24a2d-86f7-40a0-aed4-e3fb55f42a3d) | ![image](https://github.com/bluesky-social/social-app/assets/148872143/bf01c714-e14f-4d45-9da …

Improved search autocomplete view

---

src/locale/locales/ca/messages.po

Hello. The current PO file for Catalan language in main is incorrect, see:
msgfmt -c --statistics messages.po 
messages.po:196: keyword "Apel" unknown
messages.po:196:5: syntax error
msgfmt: found 2 fatal errors
It looks like that a last minute fixed went into the wrong line of the file. This fixes the issue:
After this fix:
msgfmt -c messages.po  --statistics 
552 translated messages.

Fixes msgfmt error in line 196

---

src/locale/locales/ca/messages.po

Minor corrections spotted by another bluesky user

Update catalan messages.po

---

src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

fixes https://github.com/bluesky-social/social-app/issues/2556
fixes https://github.com/bluesky-social/social-app/issues/2555
Improves the sizing of external embeds so they don't take up so much screen space.
- Reduce thumb size on mobile from 200 to 180
- Reduce thumb size on web from 300 to 250
- Reduce number of description lines from 4 to 2 unless there is no thumbnail
- Cleanup unnecessary styles and move everything to the stylesheet
https://github.com/bluesky-social/social-app/assets/153161762/dec24810-ae9e-4715-bd8f-10186c822e1b

improve external link design

---

src/view/com/util/moderation/ContentHider.tsx

caps line count to two. could go to one, but better to err on side of showing more context

flex and truncate content hider text

---

src/state/shell/composer.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/text/RichText.tsx

if the user doesn't shorten links before posting, quotes look janky
instead, we can pass the facets into the quote, and add a prop to `RichText` that can optionally disable links, but still deal with shortening them.

properly shorten links in quote embeds

---

src/view/com/post-thread/PostThread.tsx

The way we show replies in a linear mode isn't quite right IMO.
Consider this thread: http://bsky.app/profile/danabra.mov/post/3kjemen7ies27
Opening the root post shows replies to further posts on the same level:
This breaks the flow of conversation. You see replies out of the context to which they were replying — which is not just confusing but can also cause miscommunication (like "I agree" replying to a different post in the thread).
Instead, I think this should work like on Twitter. You only see the reply chains that are *for* the post you currently highlighted.
So on the root post I should see just this:
For the "post 1" post, I should see this:
And so on.
This only affects linear mode. In threaded mode, all replies are still shown.

Fix orphan replies in linear mode

---

src/view/com/post-thread/PostThread.tsx

There wasn't enough space at the bottom, so clicking on a post _sometimes_ jumps scroll. With this change, it doesn't. The problem was web-only; on native, the scroll position is respected but it will bounce a bit upwards when you try scrolling. Which IMO is fine so I didn't change the native number.
https://github.com/bluesky-social/social-app/assets/810438/e8003111-9788-49de-b6cc-df3464887b73
https://github.com/bluesky-social/social-app/assets/810438/9ab4c462-6d75-4bf8-8f41-f087eea73fc8

Fix jump when opening last post in thread

---

src/state/preferences/in-app-browser.tsx

instead of using the system's color scheme, use the user's selected color scheme for the in-app browser

use theme's color scheme in in-app browser

---

src/view/com/composer/text-input/TextInput.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1257
Adds the ability to insert images by drag-and-drop.
The drop trigger covers the whole screen so you don't have to go very far to add the image.
The overlay modal has a box-shadow to compensate for reduced opacity on the backdrop, because having the backdrop opacity be the same as the composer modal seems to make it *too* dark.

Image drag and drop on web composer

---

src/lib/strings/rich-text-helpers.ts
src/state/queries/list.ts
src/view/com/modals/CreateOrEditList.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

List descriptions can contain facets and in the app is rendered with a `<RichText>`, all that's left is to add the resolution step
- Description state is initialized by serializing it to string first and then creating a RichText from it, this way we're starting with a pretty much blank state.
- `richTextToString` function has been modified to add a `loose` property, when it's `true`, invalid links are to be copied with the `[label](url)` format, but if not then it just uses the label. The idea is that copying post text usually means it being shared elsewhere, while for this form we just want to reuse it for the user to edit.
- Description now has a visible counter now rather than mysteriously appending with an ellipsis.

Resolve facets on list descriptions

---

bskyweb/cmd/bskyweb/server.go

Posts that contain images AND a record (e.g. [quoted posts](https://bsky.app/profile/amagire.bsky.social/post/3kjgfxufwfn2z)) currently don't generate any `og:image` tags; this - in theory - fixes that.

Ensure OG:Image is filled when post contains a record

---

bskyweb/cmd/bskyweb/server.go
bskyweb/templates/post.html

#1188 had the side effect that post social cards have truncated links, which means that bsky posts displayed in Slack, among other places, display non-functional URLs. This is increasingly a problem with broader sharing of publicly viewable posts from the web interface. For example:
This PR undoes the effect of shortenLinks() when formatting social cards, expanding these truncated urls back to their original content from the post's facets. Additionally, posts with embedded links get the url of the embedded link appended to the end of the social card if it's not already included in the post so those posts don't appear without their links.
Full disclosure: I don't know much Go and this is my first bluesky-social PR. I've tested this pretty extensively locally, including with multibyte …

Include expanded urls in social cards

---

src/lib/link-meta/bsky.ts
src/view/com/composer/useExternalLinkFetch.ts

Fixes https://github.com/bluesky-social/social-app/issues/1846
It looks like the new feed/list pages are able to resolve the handle without issues unlike before, should we make the "Share feed" and "Share list" menu items use the handle instead of DID for the URL?

Resolve handle in feed/list URLs

---

src/lib/strings/helpers.ts
src/view/screens/Search/Search.tsx

Addresses https://github.com/bluesky-social/social-app/issues/849#issuecomment-1876982941
nit: we should probably close that issue already since it's been fixed for a while now
Adds the ability to search for your own posts using the `from:me` search syntax, this is done by replacing instances of `from:me` with account's DID, special care is taken to avoid string replacements inside quotes, because quotes are exact search matches

Add from:me search functionality

---

src/view/com/composer/text-input/TextInput.tsx

In iOS, a multiline textinput has a scrolling behavior of its own. This created a scrollview-within-scrollview problem on iOS, because we embed the entire composer in a scrollview.
Disabling the scrolling behavior on the textinput solves this issue.
Closes #2413

Disable scroll on the composer TextInput (close #2413)

---

src/view/com/posts/FeedItem.tsx
src/view/screens/Lists.tsx
src/view/screens/ModerationModlists.tsx
src/view/shell/desktop/LeftNav.tsx

* Nudge `LeftNav`.
Before:
After:
* Add left margin of `New` buttons in Lists.
Before:
After:
* Remove left margin of `UserInfoText` in `FeedItem`
Before:
After:
Thank you!

Minor style fixes

---

src/view/screens/Feeds.tsx

This PR scrolls the feed search bar to the top of the screen on focus, to avoid the situation where it's too low on the screen and you can't see the results as you type.
https://github.com/bluesky-social/social-app/assets/10959775/dcfd30e5-6e59-41f4-bcf3-735743b106bc
Implementation notes:
`scrollToIndex` is used on native and works flawlessly. However, that's not available on web, so we use `scrollToOffset` there instead and have a guess at the offset. I measured the height of all the elements so it should be roughly accurate, but in my testing it wasn't perfectly lining up. Luckily there's a fair bit of padding above the search bar so there's plenty margin for error.

Scroll feed search bar to top of screen on focus

---

src/components/forms/ToggleButton.tsx
src/screens/Onboarding/StepModeration/AdultContentEnabledPref.tsx

@estrattonbailey 
This should cleanup the issues. Simplified the AdultContentPref so all the containers use the same background style/rounded corners, etc. w/ less code. Also, made a few adjustments to ToggleButton so it adjust correctly. Tested on an iPhone SE and buttons stay within the container bounds now too.
Hopefully doesn't conflict, or if you've already done this just close it 👍

cleanup moderation styles

---

src/view/com/auth/create/Step1.tsx

Fixes a bug where an icon didn't respond to dark mode and thus was near impossible to see
Before:
After:

Fix server icon in sign up flow not responding to dark mode

---

src/view/com/post-thread/PostLikedBy.tsx
src/view/com/post-thread/PostRepostedBy.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/profile/ProfileFollowers.tsx
src/view/com/profile/ProfileFollows.tsx
src/view/com/util/LoadingScreen.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

Post likes, reposts, profile follows and profile followers were showing a tiny spinner with no paddings.
Now they're using a large spinner with a padding, like post thread does.
This looked especially bad on the web. On the mobile it was fine but I'm going for consistency.
This is now one component; if we want to change how it looks, let's change it across all screens with this layout.
https://github.com/bluesky-social/social-app/assets/810438/7ac5db19-8fa0-4f36-8b97-d7d609027cfd
https://github.com/bluesky-social/social-app/assets/810438/82d2a373-4f49-460a-9cfc-4fae5712f0ed

Use consistent spinners for loading screens

---

src/view/screens/NotFound.tsx
src/view/screens/PostLikedBy.tsx
src/view/screens/PostRepostedBy.tsx
src/view/screens/ProfileFeedLikedBy.tsx

Looks like we're using title case for these. In title case, the first and the last word should be capitalized even if they're prepositions — so "Liked By" not "Liked by".
Verified other headers already follow title case.

Capitalize screen headers consistently

---

src/view/com/util/LoadingPlaceholder.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/com/util/post-ctrls/RepostButton.web.tsx

- Numbers were shown even when zero.
- Buttons were subtle misaligned between different posts.
- Liking a post was shifting the repost button.
https://github.com/bluesky-social/social-app/assets/810438/cce01bc1-0cca-4dad-b0fa-165cd10f7f5b
- Loading shim was using different icons and spacing than the actual content.
https://github.com/bluesky-social/social-app/assets/810438/01d4f379-fc2f-47a9-834a-0a9dc201e5ae
- The number zero is no longer displayed at all.
- Buttons are aligned between different posts.
- Liking a post no longer shifts the repost button.
https://github.com/bluesky-social/social-app/assets/810438/5296cebf-172b-40ec-a6d5-cce71f9a987c
- Loading shim uses the same icons and spacing as the actual content.
https://github.com/bluesky-social/social-app/assets/810438/0a912e6c-7ad7- …

Clean up the post controls UI

---

src/state/queries/profile.ts

In https://github.com/bluesky-social/social-app/pull/1933 I've moved the optimistic update handling from raw mutations to the "queue" methods like `useProfileFollowMutationQueue`. The individual optimistic update logic remained in the underlying mutation logic but was disabled by passing `{skipOptimistic: true}`. I left this as an option in case we want to use the raw mutations somewhere in the interface after all.
A few months later, we're still not using raw mutation methods for those toggles anywhere. And really, we shouldn't—if you're building some new UI, you should just use the queue anyway. So let's remove this option and assume it's always `true`. This lets us simplify the mutations and make it clearer what's actually going on.

Remove dead code for optimistic updates

---

src/locale/languages.ts

This PR adds the English name after the endonym for app languages in Settings and also adds the endonym for Catalan.
Please feel free to close this if it would make the UI cluttered or confusing.

Add English name after endonym for app languages in Settings

---

src/state/cache/post-shadow.ts
src/state/queries/post.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

This is a simplification meant to avoid potential bugs. Not sure if it uncovers any bugs right now.
In principle we should always be able to derive the shadow like count instead of explicitly tracking it. Shadow like count should be `post.likeCount + 1` when `!wasLiked && isLiked`, `post.likeCount - 1` when `wasLiked && !isLiked`, or `post.likeCount` otherwise. A larger divergence than +/– 1 should not be possible because we only use the shadow for optimistic updates. So if it ever happened in practice, it would be due to a bug. Let's make this bug impossible.

Derive shadow like/repost count

---

src/view/com/post-thread/PostThread.tsx

On mobile, it's always at the bottom. On desktop, it's always inline. But on tablet sizes, we didn't show it at all. This makes the interface feel read-only. This change makes the tablet behavior the same as desktop — it's shown inline.

Show composer reply prompt on tablet

---

src/view/com/post-thread/PostThread.tsx
src/view/screens/PostThread.tsx

Currently, when opening a thread post, we'd show two spinners: the one below and the one above. This feels a bit janky/busy and distracts from actually reading the post you clicked on. Twitter solves this by scrolling you down just enough that you *don't see* the parent post (and so there is no need to show a spinner). I'm doing the same behavior here.
This also lets us remove some fragile logic that's bound to eventually get out of sync.
Web:
https://github.com/bluesky-social/social-app/assets/810438/dec6c9a3-0864-4515-a19f-cd668b556200
iOS:
https://github.com/bluesky-social/social-app/assets/810438/87bc5bac-0e1f-484e-96d4-8d7a97133f21
Web:
https://github.com/bluesky-social/social-app/assets/810438/37b51efb-04c0-4375-a35c-f578689d9ec6
iOS: …

Dejank navigation between thread posts

---

src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/com/util/post-ctrls/RepostButton.web.tsx

Fixes a regression I introduced in https://github.com/bluesky-social/social-app/pull/2614.
Tap areas accidentally got stretched there.
This gets them back to the size of the buttons + paddings.
Best [reviewed without whitespace](https://github.com/bluesky-social/social-app/pull/2627/files?w=1).
Clicking around the buttons no longer triggers them.
https://github.com/bluesky-social/social-app/assets/810438/e526a52b-5525-4a5c-ad03-5ba943e874c1

Fix post controls tap areas

---

src/view/com/lightbox/Lightbox.tsx

fixes https://github.com/bluesky-social/social-app/issues/2592
tested on device, alt text is selectable now regardless of whether it is expandable or not. right now, since RN handles the selection long press as a press regardless of length, it expands/collapses the text upon selection which is obviously janky.
similar to what was done in https://github.com/bluesky-social/social-app/pull/2563 except we needed to apply it to the `Text` instead of `Pressable`. Also verified that things still work fine on both other platforms.

android alt text selection fix for expandable alt

---

src/view/com/post-thread/PostThreadItem.tsx

I meant to include it in https://github.com/bluesky-social/social-app/pull/2625 but lost the change somehow.
The highlighted post is "the end of the thread so far" so it should stay avatar-connected to the parent ones.

Present highlighted post as part of the thread

---

src/state/queries/profile.ts
src/view/com/util/Link.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/UserPreviewLink.tsx

This adds prefetching on hover for profile user avatars and profile links in post meta.
We don't need to go wild with this but it's worth doing in some places.
The goal is to instantly jump to the next page's shell.
https://github.com/bluesky-social/social-app/assets/810438/0f23b910-6d53-4a7d-bd7e-a83b9459763b
https://github.com/bluesky-social/social-app/assets/810438/62ec2668-3caa-4545-a095-6bb361279b19

Prefetch profile links on web

---

src/view/com/notifications/Feed.tsx

Add missing top border to notifications loading state

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/LoadingPlaceholder.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

- e748eacb767b421053d1d1fe76c5ed073a7f1081 Reverts #2628 and readds the border to the top of the highlighted post in a thread, even when it's a reply
- 773ef18be2f68a5e60c12ba99e94710f63507dc9 Readds a right pad to the post controls
The issue here is that when opening a reply -- especially on mobile -- the interface looks really odd without a top border. I legitimately thought it was a bug.
It might work better if the scroll position is moved up vertical to always show what it's connected to, but even then I'm somewhat skeptical.
|Before|After|
|-|-|
|![CleanShot 2024-01-26 at 09 48 31@2x](https://github.com/bluesky-social/social-app/assets/1270099/1c26b047-d8c4-4328-a76e-db1b3b634550)|![CleanShot 2024-01-26 at 09 48 17@2x](https://github.com/bluesky-social/social-app/assets/1270099/41b928 …

Two UI tweaks after recent updates

---

src/screens/Onboarding/StepAlgoFeeds/index.tsx

This PR is a suggested wording tweak in one of the onboarding screens that I think would make it a bit clearer that you can select both For You and Discover as your primary feeds, it's not either/or.

Suggest wording tweak in StepAlgoFeeds/index.tsx

---

src/screens/Onboarding/StepSuggestedAccounts/index.tsx

Fix a couple of typos in StepSuggestedAccounts/index.tsx.
Edited to add:
After trying out the new onboarding, also a suggested punctuation tweak: changing the period/full stop to a colon.

Fix typos and suggested punctuation tweak in StepSuggestedAccounts/index.tsx

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

fixes https://github.com/bluesky-social/social-app/issues/2645
just use the `useOpenLink()` hook for opening translations instead of `Linking.openURL()` directly

use in app browser for translations when enabled

---

src/state/queries/feed.ts
src/view/screens/Feeds.tsx

Fixes #2648 
~~To keep consistency with the other screens where the User Lists are displayed, the type of Avatar needs to be changed from 'algo' to 'list' in Feeds.~~
Since feeds can also lack an image, the fix has been changed into a function that returns the type of avatar for each feed element.
After:

Avatar type for Feed check

---

src/state/queries/post-feed.ts
src/state/queries/profile.ts
src/view/com/modals/ProfilePreview.tsx
src/view/com/util/UserInfoText.tsx
src/view/screens/Profile.tsx

Right now we don't clear the post cache at all whenever we block/unblock someone or they block us. We might visit a profile and see that we are blocked since the avatar is blurred and we get the blocked label in the bio, but the posts are still visible. Instead, if we are blocked we should reset the posts query to ensure we can't see any content there.
Same for when we block someone. We technically shouldn't be still seeing the content from the user, rather it should be removed as soon as we block. Here we need to wait a moment for the AppView to receive the block.
We also don't need to invalidate profile queries if they are only for display name resolution. By setting those queries to not invalidate, we can set all the others to a lower 15 seconds ensuring we always have the most recent …

clear cache when blocking/unblocking and whenever we get blocked, better invalidation logic for `useProfileQuery`

---

src/view/com/post-thread/PostThreadItem.tsx

fixes https://github.com/bluesky-social/social-app/issues/2522 (?)
Very specific case where Android on a Pixel 4a and platform 31 (yea, that specific...probably related to that precise screen size) doesn't want to render text when we add the additional padding to the main post. I'm not actually sure that this is a real "fix" as far as it never happening again (I'm inclined to think its an Android bug in text measurement), but it does fix this particular case to remove the padding.
Tested a ton of posts by removing the padding, if anything the visual affect is a bit better. Right now text kind of line breaks a bit too early, removing that bit of padding helps a good deal from all the posts I opened up.
We could say forget it too and just mark it up as an OS bug, but I don't see the harm in …

remove unnecessary right padding in main thread item (fixes weird android cutoff)

---

src/state/modals/index.tsx
src/view/com/modals/AltImage.tsx

- Need a little hack for autofocusing the input correctly on web, but this fixes some weirdness on Android too. The animation duration causes some problems, but if we wait a moment before autofocusing things work well.
- Try to improve the dismissability on native by making sure we are scrolled to the bottom of the scrollview once the keyboard opens. Right now the "Done" button can be hidden below the keyboard by default which is confusing.
- Sneaking in a little eslint fix that keeps bugging me
I think optimally the latter issue would be solved by using a keyboard scrollview library like https://github.com/kirillzyusko/react-native-keyboard-controller but that's moreso something we might want to do throughout the app.

Autofocus the alt text input on all platforms, improve dismissability on native

---

src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts

Adding some logic to `isThreadMuted` for when we don't have a subject URI (when counting)
- We can always check if the thread itself is muted from the post
- We can check root level quotes to see if they are muted
- Same for reposts, we can check if they are muted when the repost is the root
Hopefully will cover the majority of cases for now.
https://github.com/bluesky-social/social-app/issues/2562

check if a thread is muted before incrementing notif badge, filter out quotes

---

src/view/com/util/images/Gallery.tsx
src/view/com/util/images/ImageLayoutGrid.tsx

fixes https://github.com/bluesky-social/social-app/issues/2601
Optimistic that we can use `gap` on native. Removing the negative margins from the container is the key to fixing the swipe issue, and looks like we were using that because of the yoga issue.
Noted that on web, using `gap` with `aspectRatio` definitely didn't work right for 3 images, but it seems to be okay on native. We don't need `aspectRatio` there because expo-image handles the sizing (based on the containers height from the other two images with `aspectRatio: 1`, whereas it looks like on web it doesn't.
Did have to slightly adjust the alt text label as well, since removing that margin moved it in a bit.

fix left swipe on android

---

src/state/queries/notifications/feed.ts
src/state/queries/notifications/unread.tsx
src/state/queries/notifications/util.ts

Noticed these when testing the thread muting
Essentially the notification filtering was interrupting the correct `markAllRead` behavior. We need to be using the `indexedAt` of the most recent notification in `updateSeen`, and so we need to capture that timestamp prior to filtering. I also removed an optimization that assumed that you'd never filter out a whole page of notifs, which you indeed can with a thread mute

Fix notification mark-read behaviors

---

src/view/com/modals/UserAddRemoveLists.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2674
Adding `flex: 1` to the list in the modal doesn't work on web, since a smaller screen will cause it to overflow. Should be handled better with ALF dialog since the content container will adjust height accordingly, but for now a quick fix to just use the screen's height and adjust accordingly.

adjust height of "add to list" modal based on screen size on web

---

src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/lists/ProfileLists.tsx

Original issue in https://github.com/bluesky-social/social-app/issues/1876 isn't reproducible as a padding/margin issue on any platform. Seems that the `ListFooterComponent` always adds the appropriate amount of padding to the view...
This does fix issues where a large list of lists/feeds isn't scrollable on user profiles though, since there was no accounting for the header offset on those tabs. Will keep playing with different follower screens to see if it is ever reproducible.

add padding to user's lists/feeds scrollviews

---

src/view/com/pager/FeedsTabBar.web.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/pager/TabBar.tsx

really just to shut the warning up, but could potentially be an issue. right now just the name is used as a key, which causes the warning if you have two feeds with the same name
also memoizes the array of feed names

prevent duplicate keys in feed tab bar

---

src/state/shell/composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

fixes https://github.com/bluesky-social/social-app/issues/2656
pass `PostModeration` into composer `replyTo` and:
- blur avatars if needed
- hide image embeds if needed

moderate avatars and embeds in composer reply to

---

src/view/com/util/List.web.tsx

This property should in theory be useful for improving paint perf for lists (I haven't measured but I know it can bring good results from past practice). However, it seems currently borked in Safari Technology Preview and Orion. It might be a temporary regression (they're actively landing PRs related to this property in WebKit repo) but for now let's turn it off for Safari.

Workaround Safari content-visibility bug

---

src/view/com/composer/select-language/SuggestedLanguage.tsx
src/view/com/composer/text-input/TextInput.web.tsx

Hopefully closes #2598 
I did more testing sessions on lande's output for given test strings. I noticed that false positives happen seem to correlate to having multiple matches with a score higher than `0.000x` (4 decimals of certainty) and so this adds logic to discard suggestions that match those conditions.

Reduce the odds of false positives in the language suggester

---

src/screens/Onboarding/Layout.tsx

Add a little extra padding so the button isn't stuck to the very bottom of the safe area on android

Add padding to bottom portal to account for safe area

---

src/state/session/index.tsx

This fixes weirdness where if the user changes their handle after creating an account there isn't a handle/display name discrepancy.

set default display name to be blank

---

src/screens/Onboarding/StepSuggestedAccounts/index.tsx

Each step has a start and end. The end has the resulting props on it. Other steps are correct.

Typo in onboarding metric

---

src/screens/Onboarding/StepModeration/AdultContentEnabledPref.tsx
src/screens/Onboarding/StepModeration/ModerationOption.tsx
src/screens/Onboarding/StepModeration/index.tsx
src/state/queries/preferences/types.ts

Improving the moderation configuration:
- Always show the enable toggle
- On iOS where users must use the web to enable adult content, still show the toggle but display a dialog explaining when the user tries to toggle it
- Improve the wording of the requirement to use web to enable
- Don't display the adult content label options if "enable adult content" is disabled.
- Animate in/out those settings
https://github.com/bluesky-social/social-app/assets/153161762/4ad80b82-efe3-4e37-a49f-08d2423581a8

Onboarding moderation improvements

---

src/locale/locales/hi/messages.po

A cleanup PR that removes strings from hi/messages.po that have been superseded and are no longer used.
I also matched some of the superseded strings that had already been translated to their new equivalents.

Remove superseded strings from hi/messages.po

---

src/locale/locales/fr/messages.po

A cleanup PR that removes strings from fr/messages.po that have been superseded and are no longer used.
I also matched some of the superseded strings that had already been translated to their new equivalents.

Remove superseded strings from fr/messages.po

---

src/locale/locales/es/messages.po

A cleanup PR that removes strings from es/messages.po that have been superseded and are no longer used.
I also matched some of the superseded strings that had been translated to their new equivalents.

Remove superseded strings from es/messages.po

---

src/locale/locales/de/messages.po

A cleanup PR that removes strings from de/messages.po that have been superseded and are no longer used.
I also matched some of the superseded strings that had been translated to their new equivalents.

Remove superseded strings from de/messages.po

---

src/locale/locales/en/messages.po

A cleanup PR that removes strings from en/messages.po that have been superseded and are no longer used.

Remove superseded strings from en/messages.po

---

bskyweb/cmd/bskyweb/server.go

The current template rendering logic for OpenGraph data only supports handles in the URL, this should update it to support DIDs as well for previewing profiles and posts.

Support previews for links using DIDs and not just handles

---

src/view/com/util/load-latest/LoadLatestBtn.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx

Inbetween desktop and mobile breakpoints on web, we don't see anything telling the user to sign in or sign up when in the signed out view. This corrects that by showing the bottom bar on both mobile and tablet breakpoints when there is no session present.

show bottom bar on web tablet breakpoints when logged out (signup cta)

---

src/view/shell/index.tsx

`currentAccount` is mutated a couple times as we init e.g. updated the refresh token, which caused these effects to re-run 3x and register a push token 5x (since the listener was destroyed and re-instantiated also).
This PR consolidates these two effects and does a check for a did to make sure it only runs when the account did changes. So `registerPush` should only be called 2x now instead of 5x.
I considered doing this in our `session` state, but as mentioned, some props on `currentAccount` DO need to mutate. So for this use case I thought this was more direct.

Only re-reg push noty token when account changes

---

src/lib/media/manip.web.ts

Partial fix for https://github.com/bluesky-social/social-app/issues/2734
It returned a broken unparseable image, and because there was no event listener to catch it, the promise is just stuck unfulfilled.
This only addresses the fact that cardyb is returning a broken image, this doesn't fix *why* cardyb is returning a broken image to begin with.

Listen for error event on creating resized image

---

docs/build.md

I've seen this come up three times in the past week, and it isn't documented in the React Native docs. On macOS we need to make sure we are running ruby >= 2.7.6 (macos ships with 2.6) and a downgraded version of cocoapods which gets installed through the project's gemfile.

update docs to include info on installing `cocoapods`

---

src/view/screens/Search/Search.tsx

Currently, the error message shows the query *after* it's been transformed, resulting in the DID being visible in the error message:
It seems like there's a general aim to avoid DIDs being surfaced in the UI where possible, so I don't think this behaviour is ideal.
This PR shows the original query in the error message, only using the augmented query for the actual seach request.

Show original query in error message when using "from:me"

---

src/lib/api/feed-manip.ts

Fixes https://github.com/bluesky-social/social-app/issues/875
This partly addresses the complaints of low engagements on replies by bumping the entire slice up to the top of timeline. Given that we're requesting 60 posts at a time in the following feed, this means that threads can be much further apart and still be eligible for bumping.
It's somewhat open for abuse, but I don't think it should be an issue.
| --- | --- |
| <img width=200 src=https://github.com/bluesky-social/social-app/assets/148872143/bc604551-746b-4740-aa95-4ced8acde3f3> | <img width=200 src=https://github.com/bluesky-social/social-app/assets/148872143/322b3356-6976-4477-8294-45b6ae435660> |

Bump replies

---

src/view/com/util/post-embeds/index.tsx

Opens the sharing menu when you long press the external link card. Only applies to native.

Long press external embed to share

---

src/view/com/auth/create/Step2.tsx

I signed up today using my Honduran phone number (8 digits) and the app showed me an error saying `here's something wrong with this number. Please choose your country and enter your full phone number!`
Given that international phone numbers are often < 9 characters in length and there's already a `parsePhoneNumber` included from `libphonenumber-js` I think it's better to use the built-in validator.

Validate phone number based on country

---

__tests__/lib/string.test.ts
bskyweb/cmd/bskyweb/server.go
bskyweb/static/iframe/youtube.html
src/lib/strings/embed-player.ts
src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx

fixes https://github.com/bluesky-social/social-app/issues/2487
Content now loads that previously would not due to YouTube restrictions. If there's no referrer for the request, it doesn't work. By hosting the iframe on `bsky.app` we can get around this.

fix some youtube videos not properly loading

---

src/view/com/modals/AddAppPasswords.tsx

Tested on Android and Web, can't test on iOS.
- Fixes the annoying issue with Enter key not submitting the form on web
- Makes `selectTextOnFocus` actually work (it didn't do anything before, my guess is that this was used to select the default name so you can easily change it, so I did just that)

Submit App Password on pressing Enter

---

src/view/com/util/forms/Button.tsx
src/view/com/util/forms/DropdownButton.tsx

fixes https://github.com/bluesky-social/social-app/issues/2669
Not sure when this broke, but the language selection dialog currently doesn't take into account the scroll position of the container, so if we are not at the top of the page it renders somewhere in the void. This uses click/press position instead of the page position for better accuracy.
https://github.com/bluesky-social/social-app/assets/153161762/705ce7bc-4c52-4676-9c77-71b246251e64

Display the language selection dialog correctly on web

---

src/state/queries/actor-autocomplete.ts

We needed to convert the query to lowercase here before searching. Wondering if this was a v2 change?
We should do this regardless so that searching `KATIE` then a subsequently searching for `Katie` will be cached.
https://github.com/bluesky-social/social-app/issues/2430#issuecomment-1931046814

convert query to lowercase before performing query

---

src/state/persisted/legacy.ts
src/state/persisted/schema.ts
src/view/screens/Home.tsx

I found the existing logic difficult to trace due to the source of truth being slightly ambiguous. We have several types of information (selected index, a list of pinned feeds, fetched/resolved pinned feeds, feed descriptors) and the relationship between them wasn't very clear. In particular, we weren't very careful about which indexes correspond to which arrays. This is why the code was written defensively (e.g. clamping) and a bit unnaturally.
In this PR, I restructure it so that there is always an `allFeeds` array of resolved `FeedDescriptor` values (including the first `'home'` one), the `selectedIndex` always points to an item in that array (and is guaranteed to be in-bounds, i.e. no `-1`), and so that `selectedFeed` is always `allFeeds[selectedIndex]`. If the persisted value is not …

Refactor Home feed pager rendering logic

---

src/locale/locales/ca/messages.po

A tiny PR to fix a typo in the recently-updated Catalan translation, changing a single 'O' to 'P' (they're right next to each other on the keyboard ofc).

Fix typo in ca/messages.po

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/modals/AltImage.tsx

It is pretty common on iOS now for images to use iOS's live text interaction feature. We can enable that in the alt text modal and in the image viewer (when the image is not scaled) with expo-image.
https://github.com/bluesky-social/social-app/assets/153161762/8733507d-de3d-447a-9485-82a0e30963ef

use ios live text interaction in alt text modal and image viewer

---

src/view/com/modals/ModerationDetails.tsx

This very small PR adds the missing word 'in' to the message:
"This user is included the [listname] list which you have muted."
to follow the equivalent message on L43:
"This user is included **in** the [listname] list which you have blocked."

Add missing word in ModerationDetails.tsx

---

src/view/com/util/Link.tsx

On the web, I want to be able to cmd+click a `TextLink`. This currently works if it has no `onPress` handler, but if `onPress` handler is specified, the browser behavior will not be respected. This isn't very good. Ideally, we should *still* let the browser handle in these cases. (Unless its `href` is invalid.)
I've manually searched through all usages to `TextLink` to confirm the new behavior makes sense. E.g. you're now able to cmd+click on a List's title header to open it in a new tab. Same with "Bluesky" header at the top of the feed. The few cases where it didn't made sense had `href="#"` so I explicitly check for that.
I know we have some similar code within `onPressInner`. I didn't touch it because by the time it runs, it's already too late — the custom `onPress` has executed. I …

Fix open-in-new-tab for TextLink

---

src/view/com/composer/text-input/TextInput.web.tsx

`CSSProperties` doesn't like anything but `string`.

use the palette's font color in the composer (as string)

---

src/view/screens/Notifications.tsx

I often have a thought while reading notifications — let's add the button there.
(I considered adding to Search too but it wouldn't work super well in our layout due to overlapping Follow and Compose buttons. Maybe we can do that if we redesign a bit.)
Notifications is logged in only so I didn't add a session check.

Add composer button to Notifications

---

src/view/com/modals/ProfilePreview.tsx
src/view/com/util/error/ErrorScreen.tsx
src/view/screens/Profile.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2756
Profile errors were not rendering correctly since they were accidentally wrapped inside of an additional `<CenterView>`. Also adding a view header on the error screen when rendered in `Profile` (still no header in `ProfilePreview`).
Also using `Not Found` for profile errors found in https://github.com/bluesky-social/atproto/blob/77118a66a7a5703e495464186246fb29fa9fa9df/packages/bsky/src/api/app/bsky/actor/getProfile.ts

Fix error screen on native, use `Not Found` for profile errors instead of `Oops!`

---

bskyweb/templates/base.html
web/index.html

On non-English Windows Chrome, Google Translate appears as shown in the image above. This PR fixes this. Also, we've removed the X-UA-Compatible code as IE support has now ended.

Fix google translate appear

---

src/locale/locales/ja/messages.po

@tkusano @dolciss @oboenikui @noritada
The version of the Japanese display has been updated to 1.68, and the update has been made to follow.
One concern is the dark mode setting.
Please refer to this page for the intention of "Dim" and "Dark": https://github.com/bluesky-social/social-app/pull/2722#issue-2111197246

Add: Followed version 1.68 of Japanese display

---

src/App.native.tsx
src/App.web.tsx
src/state/shell/selected-feed.tsx
src/view/com/pager/Pager.web.tsx
src/view/screens/Home.tsx
src/view/shell/desktop/Feeds.tsx

Another approach to https://github.com/bluesky-social/social-app/pull/2738.
This one is a bit weird but I think it works.
The idea is to have a hierarchy:
- If opened with `/?feed=...`, prefer that. This is for "open in new tab" in the right pane.
- Otherwise, see if we have something in `sessionStorage`. This is tab-local so it ensures refreshing a tab doesn't reset the selected feed. Each browser tab tracks its own selected feed across refreshes.
- If we don't have that either, fall back to `persisted` (i.e. `localStorage`). This is for regular newly opened tabs.
- Finally, fall back to Following.
On native, there shouldn't be any changes.
I haven't tested extensively, but cursory testing seems to show this works.

Keep pager feeds in sync with the right pane

---

src/view/com/profile/ProfileHeader.tsx

Makes bio more obviously selectable on the web (it now shows a caret on hover on the web), see https://github.com/bluesky-social/social-app/issues/2429#issuecomment-1924183432. We couldn't do this before web layout, but now the pointer events stuff isn't needed on the web at all.
I haven't removed it elsewhere but here it's an easy win.

Show text cursor on web bio

---

src/state/cache/profile-shadow.ts
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/UserAvatar.tsx
src/view/screens/Profile.tsx

- Fix profile header avatar flash on load by unifying loading and content trees
- Give avatars a background color to avoid a flash when transitioning from a placeholder
- Show bio after rich text is resolved to prevent jumping the content below
There's more dejanking to be done (e.g. avoiding updates mid-animation) but this will do for now.
https://github.com/bluesky-social/social-app/assets/810438/6d92bc25-ffa2-40d2-9a09-bcb1f77e344a
https://github.com/bluesky-social/social-app/assets/810438/f2397bbb-1e12-4da0-9e94-6ca3860fa171
https://github.com/bluesky-social/social-app/assets/810438/0c0f2728-b2fb-4144-bfd5-dcad7c83dc13
https://github.com/bluesky-social/social-app/assets/810438/5658857f-7560-413b-9072-a99ba5454b31

Fix flashes and jumps when opening profile

---

src/view/com/pager/PagerWithHeader.tsx

Better approach than https://github.com/bluesky-social/social-app/pull/2816.
Believe it or not, the timing of React layout effects in RN isn't well-defined ([yet](https://github.com/rubennorte/discussions-and-proposals/blob/proposal-event-loop/proposals/0744-well-defined-event-loop.md)) with regards to layout. (Oops.)
Instead let's rely on parent-child `onLayout` ordering which in my understanding and testing is reliable.
This works well in my testing.

Measure header layout reliably

---

README.md
bskyweb/templates/base.html
src/view/com/auth/HomeLoggedOutCTA.tsx
src/view/com/auth/SplashScreen.web.tsx
src/view/com/modals/report/Modal.tsx
src/view/screens/CommunityGuidelines.tsx
src/view/screens/CopyrightPolicy.tsx
src/view/screens/PrivacyPolicy.tsx
src/view/screens/Settings.tsx
src/view/screens/Storybook/Links.tsx
src/view/screens/Storybook/Typography.tsx
src/view/screens/TermsOfService.tsx
src/view/shell/Drawer.tsx
src/view/shell/desktop/RightNav.tsx

This PR updates links to `blueskyweb.xyz` found in various places to the equivalent URLs on `bsky.social`.
It makes two other minor changes:
- The superfluous localisation parameters at the end of the Play Store link in README.md are removed.
- The link in `CopyrightPolicy.tsx` which currently points to the Community Guidelines has been changed to point directly to the Copyright Policy (which I'm assuming is the intended location?)
This PR does not, of course, make any changes to any references to `blueskyweb.xyz` relating to how the app is identified for the purposes of the app stores etc.

Update `blueskyweb.xyz` links to `bsky.social`

---

src/view/shell/desktop/LeftNav.tsx

HashtagIcon's active state behaviour seems to generally be to increase the stroke width from 2.25 to 4 in most places, but in the left nav it was left as 2.25, so there was effectively no active state. This fixes that.

Increase stroke width for active hashtag icon in left nav

---

docs/build.md

I spent some time working through errors while following the steps in docs/build.md. I added the steps I needed to follow to remediate these errors. These extra clarifications should help save new developers time getting their dev environment up and running.
Note: While I'm successfully able to install the app on an iOS simulator, I'm _not_ yet able to run the end-to-end tests using the steps under "Run e2e tests"

improves build.md completeness

---

src/locale/locales/ja/messages.po

@tkusano @dolciss @oboenikui @noritada @Hima-Zinn
はじめまして、日本語訳がより分かりやすく・より適切になるようプルリクエストを作成しました。
I have created a pull request for Japanese translation.
I have made changes to make it easier to understand and more suitable.
This is my first pull request, so I apologize if I made any mistakes.
Pictures
"写真" -> "画像"
"写真" means "photo".
"画像" means "image".
attached
"接続" -> "添付"
"接続" means "Connection"
"添付" means "Attachment"

Adjust Japanese translation

---

src/locale/locales/zh-CN/messages.po

In the last pull request #2780 , I made some modification suggestions but they were still pending accepted after merged. 
I thought maybe the contributor didn't see it so I fixed them by myself.

Fix wrong translations in zh-CN localization 

---

src/view/com/post-thread/PostThreadFollowBtn.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/icons/index.tsx

Doing some modifications on the highlighted post.
1. Adding a follow button
- Button is initially visible if the user is not being followed.
- The button stays visible even after the user is followed until the user leaves the screen
- The button will be removed/added both on blur and on focus, so it will maintain visibility with the `viewer` in the profile's shadow
2. Remove the `TimeElappsed` from the highlighted post. We are displaying the timestamp below, and having this there is hindering us having the button there. This is the common behavior in other apps as well.
3. Removing static width on the display name and handle. We flex these properly now so that they take up the full line instead of being truncated. This prevents  some issues that we were seeing with longer display names …

Add follow button to highlighted post

---

src/view/com/composer/text-input/TextInput.tsx

Again addressing RN weirdness with line height in the text composer. This only applies on iOS, there are no visible issues on android using `lineHeight` styles.
The previous patch for this fixed the line height from causing the text to continue off the screen, however, it seems to have introduced a small movement on the first line of text. I think until RN merges a full fix for this the best option is to just not apply a line height on iOS.
Before and after:
https://github.com/bluesky-social/social-app/assets/153161762/48b67175-3838-43ae-aac9-fb3b75da1cc8

remove line height from text input for composer on ios

---

src/view/com/post-thread/PostThreadItem.tsx

Avatar is rendered inside of `PostMeta` in threaded mode so we don't want to apply the margin in that view.

pad right for treeview

---

src/view/com/auth/SplashScreen.tsx
src/view/com/auth/SplashScreen.web.tsx

This pull request adds language selection on the splash screen
Fixes https://github.com/bluesky-social/social-app/issues/2801
This took a bit of wrangling due to `<select>` auto-sizing to fit the longest-name option, we only want the input to fit the currently selected option instead.
| Viewport | English | Chinese (Simplified) |
| --- | --- | --- |
| Desktop | <img width=200 src=https://github.com/bluesky-social/social-app/assets/148872143/88bf3db8-e1a9-4025-8f34-9ad8a5ed62a9> | <img width=200 src=https://github.com/bluesky-social/social-app/assets/148872143/e2f57eb7-32ea-4306-bf53-1497d968674a> |
| Mobile | <img width=200 src=https://github.com/bluesky-social/social-app/assets/148872143/ff9c6416-620a-4ecb-b86f-4f01b509f227> | <img width=200 …

Add language selection on splash screen

---

src/Splash.tsx

Issue: OS-level theme mode and app theme mode can be different (light or dark), which was causing the splash screen to begin in dark mode, then abruptly switch to light mode (or vice versa).
This PR makes it so that the splash screen matches whatever mode your system is set to.

Commit to theme mode of system

---

bskyweb/templates/base.html
src/alf/util/useColorModeTheme.ts
web/index.html

By applying this commit, theme color users selected on settings is applied to the theme-color tag. When users install the web page, color of status bar is synchronized to the theme color.

Add theme-color meta tag and apply selection of theme

---

src/lib/routes/links.ts
src/view/com/util/text/RichText.tsx

> I agree, hashtag support would be very useful precisely for the reasons you point out. Support wouldn't have to be as [detailed or as complex](https://business.twitter.com/en/blog/how-to-create-and-use-hashtags.html) as it is on, say, Twitter, just the simplest functionality mentioned to start with. It really would be a valuable feature.
>
> _Originally posted by @Luke717 in https://github.com/bluesky-social/social-app/issues/848#issuecomment-1577855453_
As atproto/api already parses hashtags, this is as simple as hooking it up like link segments.
This is "bare minimum" because:
- ~~Opening hashtag "#foo" is actually just a search for "foo" right now to work around #2491.~~ I have removed this workaround now that https://github.com/bluesky-social/indigo/issues/578 has been addressed.
- …

Add bare minimum hashtags support

---

src/state/queries/util.ts

Quick one line to add the embed when converting an embed view to a post view. Still will have issues in some cases if the quote's embed is a quote as well as discussed.
If we don't include the embeds, when we open the quote there will be a jump after the image or link embed is loaded.
Re why this is an array: https://github.com/bluesky-social/social-app/pull/2464#issuecomment-1886382953
It is guaranteed to only be a single item if it is defined: https://github.com/bluesky-social/atproto/blob/50f70453a9e49621956e4e820226c0e220fe138e/packages/bsky/src/services/feed/views.ts#L434
https://github.com/bluesky-social/social-app/assets/153161762/9bb4ca8d-5d77-4f9d-a7d8-ca1d33b67332
https://github.com/bluesky-social/social-app/assets/153161762/e6b5d986-05d2-4bf4-aec5-57c83e8a3955

Add embed to post view when converting from embed view

---

src/state/queries/post-feed.ts

When we open a post from the feed, we use `findAllPostsInQueryData()` to get placeholder data if we have it.
Right now, our logic searches each post *and* each post's quote (if one exists) to find this placeholder data. In most cases, this works.
However, in some cases, the post we are opening might have been quoted in another post that is inside our cache. In these cases, right now we might use the incomplete record (embed records don't have all of the information that we would like to have, such as image URIs or thumbnail URIs) as the placeholder data, even though later in the cache we do indeed have the full post view.
This is evidenced by opening post 14 on https://bsky.app/profile/dansshadow.bsky.social. Right now, we will use the incomplete quote record as a placeholder, resulting …

Prefer post over quote when finding cached post

---

src/components/Dialog/index.tsx
src/components/Dialog/index.web.tsx
src/components/Dialog/types.ts
src/components/Prompt.tsx
src/components/icons/Times.tsx
src/view/screens/Storybook/Dialogs.tsx
src/view/screens/Storybook/index.tsx

One major drawback to the dialogs prior to this PR was that on native, the dialog would actually be mounted prior to being opened. This PR fixes that, and more closely aligns with how the Dialog behaves on web.
Review [without whitespace.](https://github.com/bluesky-social/social-app/pull/2933/files?diff=split&w=1)
This PR also includes:
- a fix so that the bottom sheet never extends beyond the safe area top inset
- padding tweaks to look better on all platforms

Improve dialogs

---

src/components/Dialog/index.tsx
src/view/screens/Storybook/Dialogs.tsx
src/view/screens/Storybook/index.tsx

Fixes the main issue I was seeing yesterday, where the content of the dialog would collapse in some circumstances.
I discovered by accident that a dynamically sized dialog with one default snap point at 100% seemed to size just fine. `enableDynamicSizing` inserts a `snapPoint` into your array of snap points, so in this case it results in snap points of `[<dynamic>, '100%']`. This has no effect on other dialogs, or dialogs where we explicitly pass in snap points of our own.
So what this means for dynamically sized dialogs (like Prompt) is that they initially open to whatever natural height they are, but then they can be dragged open to 100% too. Seems like an ok compromise for now.
This PR also improves the backdrop color so that stacked dialogs have sufficient contrast to be clearly …

Improve dialogs issue

---

src/alf/atoms.ts
src/components/Link.tsx
src/components/RichText.tsx
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/lists/ListCard.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx
src/view/com/util/text/RichText.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

Changes between old and new `RichText`:
- text size now defaults to 14, was 15
- line height now defaults to 1.3, was 1.2
Posts in feeds and threads have no (or very very minimal) visual changes. After/before (reverse order sorry) shots:

Swap `RichText`

---

bskyweb/templates/base.html

In my previous pull request (https://github.com/bluesky-social/social-app/pull/2919), two redundant `<meta name="theme-color">` tags exist in `bskyweb/templates/base.html`. Only one tag must exist. 
Note: this problem does not exist in `web/index.html`.

Remove redundant `<meta name="theme-color">` tag

---

src/lib/strings/embed-player.ts
src/view/com/util/EventStopper.tsx
src/view/com/util/post-embeds/ExternalPlayerEmbed.tsx

Instead of using `measure()`, we can just use `aspectRatio` to determine the size of the player. This fixes some jumps when opening threads with player embeds.
We were also able to simplify the styles considerably. The player can use a single wrapper for the `WebView` vs the three from before.

Remove async resizing from external embed player

---

src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/state/queries/post-thread.ts

This reverts https://github.com/bluesky-social/social-app/pull/2935 and applies an equivalent fix in a different place.
The issue we're solving is that, when constructing a PostThread placeholder, we want to reuse the data from cache. The data from cache can include both complete posts (i.e. with like counts and other info) and partial posts (i.e. without like counts and other info).
In https://github.com/bluesky-social/social-app/pull/2935, we changed the logic so that a complete post is preferred. However, we only did it for one source (post thread cache) without accounting for other sources (such as the feed cache). So this fix would not apply to the same situation when the post is retrieved from the feed cache. Additionally, we should consistently prefer full posts no matter which …

Prefer full posts for post thread placeholder

---

src/view/screens/Settings/ExportCarDialog.tsx

This small PR updates the blogpost URL in the CAR export dialog to the new `docs.bsky.app` URL.

Update blogpost URL in ExportCarDialog.tsx

---

src/state/queries/post-thread.ts

In https://github.com/bluesky-social/social-app/pull/2878, I added a shimmer for the metrics when we don't know them to avoid a layout shift. I made the assumption that usually the post you're opening would have some engagement already (that's vastly more common for the posts you're consuming from Feeds or QTs). So by default you see the shimmer, and it goes away if the post has zero likes and reposts.
This backfired a little bit for just-posted posts.
Observe what happens when you navigate into one:
https://github.com/bluesky-social/social-app/assets/810438/63dfaefe-a1a5-4e69-af9b-7054ca42e9da
You now see the shimmer show up for a fraction of a second.
But shouldn't we already have the information about the like count being zero in post thread replies? Normally we do, but currently app …

Fix flash when pressing into just-created post

---

modules/react-native-ui-text-view/ios/RNUITextViewShadow.swift

Fixing an accessibility issue here as well as a rare issue where some posts would get cut off.
We use `NSParagraphStyle` to adjust line height on our text. However, whenever we adjust it, we were not taking into consideration that the line height also needs to be multiplied by the DynamicType multiplier. We can get the multiplier by dividing the scaled font size by the base font size, and times the line height by that value.
In rare cases, a post like this would be cut off prematurely:
```
This is a test post.
First line is short.
Rest are shorter.
```
If the first line does not extend to be the entire width of the screen, then the final line of the text would be cut off. This was pretty rare, because it would only happen if the first line *also* ended in a period. Seems like a weird …

Fix UITextView line height adjustment for DynamicType, always use the max width for the view

---

bskyweb/cmd/bskyweb/server.go
src/Navigation.tsx
src/lib/routes/types.ts
src/routes.ts
src/view/com/feeds/FeedPage.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/screens/PreferencesFollowingFeed.tsx
src/view/screens/Settings/index.tsx

We call the entire tab "Home", and these settings only apply to the "Following" feed. Let's clarify that.
I updated the URLs too cause why not.

Rename Home Feed Prefs to Following Feed Prefs

---

src/lib/strings/time.ts

Fixes the annoying case where a diff of `2024-02-13T09:00Z` and `2024-02-15T07:00Z` is being shown as 1 day apart, despite clearly being 2 days apart.

Normalize relative day

---

src/lib/strings/handles.ts
src/view/com/auth/create/CreateAccount.tsx
src/view/com/auth/create/Step2.tsx
src/view/com/auth/create/state.ts

This adds some validation to handles in the UI. Right now we are not doing any validation aside from checking if the handle is already registered, so the backend receives a lot more invalid handles than it should.
Using regex from https://github.com/bluesky-social/indigo/blob/main/atproto/syntax/handle.go#L10 and other logic from https://github.com/bluesky-social/atproto/blob/main/packages/pds/src/handle/index.ts#L72
While we technically are only allowing handles with a length of <= 30, this sounds like it might change so I'm leaving that validation out and letting the service handle that.
https://github.com/bluesky-social/social-app/assets/153161762/30cd6217-3c14-43ec-b43e-83eb990bc1e9

Add handle validation to create account UI

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.tsx
src/view/com/lightbox/ImageViewing/index.tsx

Small one to hide the iOS "live text" option whenever we hide the controls. Occasionally it gets in the way of text on the screen (pretty bad decision on Apple's part with that).

use `showControls` to show/hide live text icon on ios

---

src/view/com/post-thread/PostThread.tsx

Small changes to the performance props on our `FlatList` in `PostThread`. Right now, we are using the defaults for these two props which are `21` and `50` respectively.
If we adjust the `windowSize` to `11`, we will always have one page rendered in the middle (the visible page), five pages above, and five pages below. This is down from the default of ten on top and ten on the bottom.
https://reactnative.dev/docs/optimizing-flatlist-configuration#windowsize
When opening larger threads right now, even in production there are times where there seems to be a noticeable freeze when rendering. By effectively halving the number of items we render, we can probably clean this up.

Adjust `windowSize` on `PostThread` `FlatList`

---

README.md

Invite codes aren't needed anymore!
Thanks to https://bsky.app/profile/shreyanjain.net/post/3kmdulzeibc2o for pointing this out to me.

Remove invite codes from README

---

src/view/com/util/List.web.tsx

I must've broken it at some point.
Before:
After:
Same on other screens.
No changes on native or tablet/desktop layouts.

Remove side borders on mobile web list

---

src/view/com/feeds/FeedPage.tsx

The calculation wasn't precise, causing double borders on large system font sizes.
Verified small and normal text still works well, too.

Fix imprecise header height calculation

---

src/lib/api/index.ts
src/screens/Onboarding/state.ts
src/state/persisted/__tests__/migrate.test.ts
src/state/persisted/index.ts
src/state/persisted/legacy.ts
src/state/session/index.tsx
src/view/com/auth/login/LoginForm.tsx

Right now we are sending events that we don't really need to look at to Sentry. Things like a new persisted state or uploading an image don't need to be logged unless they fail. Let's scale back some of these to `debug` instead of `info`.
Right now we default to `info` or higher for logs, so this is likely a big part of the reason that we were hitting our limit on Sentry.

Scale back sentry logs for trivial events

---

src/lib/constants.ts
src/state/queries/post-feed.ts

This creates and sends Sentry issues whenever a Bluesky feed errors. Errors are logged with the phrase `Bluesky feed may be offline: $OWNER_DID`.
On the Sentry side, we can create an alert that will send a Pagerduty email whenever X users encounter errors within Y minutes. This creates an extra layer of monitoring incase other monitors fail to detect downtimes. We can route alerts to specific recipients if we want in Sentry based on the DID sent in the error name.
This is especially useful for the Discover feeds, which have a large number of users.

Log to Sentry whenever users encounter Bluesky feed errors

---

src/view/com/feeds/FeedPage.tsx
src/view/com/home/HomeHeader.tsx
src/view/com/home/HomeHeaderLayout.web.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/com/pager/TabBar.tsx
src/view/com/util/MainScrollProvider.tsx

We need to improve the tabbar itself so that it's more usable (e.g. I don't think the way it manages scroll is great right now), but as an incremental improvement, let's replace the "Bluesky" desktop-only header with it. This brings it to parity with tablet and mobile layouts and clarifies what you're looking at (and aligns the information architecture between platforms).
Before:
After:
One awkward point is that the current feed is repeated twice on Home. I think we can live with that.

Show tab bar on desktop web

---

src/state/queries/post-feed.ts

Fixes an issue that caused wrong attribution for reply threads on refresh.
This may be an overly conservative fix:
1) If slice items are always [rendered here](https://github.com/bluesky-social/social-app/blob/d451f82f54974b7b3da1477a7e1f221628860f62/src/view/com/posts/FeedSlice.tsx#L13), there should be no reason to include the slice's key itself. It's enough to distinguish the children.
2) If slice items are guaranteed to be unique posts, then there's no reason to include the index. It should be enough to include the post URI.
I think (1) probably holds true, while (2) may not necessarily. Regardless, this fix works in either case.
Courtesy of @haileyok.
1. Set Home to a List that includes yourself.
2. Reply to someone's post in another tab.
3. "Press" on the list to refresh it. You …

Fix refetching a timeline leading to a wrong reply author being displayed

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx

Future-proofs posts so that bugs like https://github.com/bluesky-social/social-app/pull/3005 can't happen. A post should never "receive" a post with a different URL. Even if the parent component accidentally causes that, we should force a remount in this case.
Revert https://github.com/bluesky-social/social-app/pull/3005, verify its test plan still passes.
(Don't actually revert it tho)

Safeguard posts from clobbered state

---

src/components/RichText.tsx
src/view/screens/Storybook/Typography.tsx

Currently, `RichText` "caches" the first `value` it receives in state, and fails to update it. Combined with missing or incorrect keys, this leads to bugs like https://github.com/bluesky-social/social-app/pull/3005.
A proper way to rewrite this logic (async work dependent on a prop) would be similar to how it's done here:
https://github.com/bluesky-social/social-app/blob/603f3c0be972e013900264d706e2d28b87a93122/src/view/screens/Profile.tsx#L462-L470
However, we generally don't really want to resolve facets on read, and don't have legit cases for it except the profile bio (which in the future will be corrected on the backend). This functionality of `RichText` component isn't used anywhere so let's remove it.
This lets us replace `useState` with `useMemo`, fixing the "stuck" value.
Revert …

Remove dangerous derived state from RichText

---

src/state/queries/feed.ts
src/view/com/home/HomeHeader.tsx
src/view/screens/Home.tsx
src/view/shell/desktop/Feeds.tsx

This might solve the problem where the app would sometimes show a wrong feed header for the selected feed.
The problem (or at least a part of it) is that `usePinnedFeedsInfos` was not deterministic across components. Instead of always using the same query cache, it used state and an effect that fired off requests and saved the successful ones. The set of successful requests could be different depending in the `Home` component and in the `HomeHeader` components, but we assumed in the code that the indexes "match up" between components.  So we could show the wrong feed.
This was easy to reproduce by adding a non-deterministic `throw` when fetching individual items.
First, we're replacing ad-hoc state + effect combo with `useQuery`. I set the stale cache as infinite because (I think) we …

Fix wrong feed being shown

---

modules/react-native-ui-text-view/ios/RNUITextView.swift

Right now, we find the pressed string's indices in the `NSAttributedString` with `fullText.range(of: childText)`. However, we are not taking into account situations where there may be duplicate strings as in the screenshot below. Each of these has a different `onPress` handler, and the press location will not be the same. However, we are not offsetting the search as we loop through each child.
Instead, we need to save the last offset and apply that to the search, like so:
```
let range = fullText.range(of: childText, options: [], range: startIndex..<fullText.endIndex)
```
https://github.com/bluesky-social/social-app/assets/153161762/c38be82e-0a5b-40a7-9b67-fe591ee4212e

Fix collisions in UITextView for onPress events

---

modules/react-native-ui-text-view/ios/RNUITextView.swift

Because of varying emoji lengths, relying on Swift's `String.Index` instead of utf-16 offsets is a safer option when determining a text range. Right now, some emojis may cause links to not be pressable, since we are scanning the incorrect offset.

always use utf8 offsets

---

src/alf/util/platform.ts

This causes problems during compile on web platform, likely due to minification. We can revisit to see if there's another way, but for now let's stick to what we know works.

Remove `Platform.select()`

---

src/components/Dialog/context.ts
src/components/Dialog/index.tsx
src/components/Dialog/index.web.tsx
src/components/Dialog/types.ts
src/state/dialogs/index.tsx
src/state/util.ts

We noticed this morning that we hadn't yet integrated the new dialogs handling into the existing utils for closing all active elements, which includes the lightbox, modals, composer, etc.
We added part of this in #3021, but this is the second part, which is used when handling "back" events on Android.
Furthermore, touching this stuff in #3019 made me realize I could improve these types a bit, and it was necessary for this PR as well.
This PR adds the concept of `openDialogs` in addition to `activeDialogs` (which is a reference to any active dialog control hooks). `openDialogs` represents the IDs of the dialogs that are actually open in view.
This reference is used to determine if a dialog was actually closed or now upon handling an Android "back" event. If nothing was closed, and no …

Integrate new dialogs into old back handling

---

src/components/Link.tsx
src/components/RichText.tsx
src/lib/strings/url-helpers.ts
src/view/com/util/Link.tsx
src/view/com/util/text/RichText.tsx
src/view/screens/Storybook/Links.tsx

There were some recent changes where enabling the mismatch check was forgotten, resulting in some new cases where users could create links with text set to one value but the facet's URI set to another value. Obviously, we should warn users in most cases of mismatches.
However, we also shouldn't let ourselves get into cases where this happens. It's easy to forget to enable that warning when using the `<InlineLink>` component, so it would be better for us to have it as enabled by default, with an option to `disableMismatchWarning` if we want to. At least then if we miss it we are just being over cautious instead of creating possible problems.
Also, we can links going to both `bsky.app` and `bsky.social` hosts, including their subdomains. The current logic only checks for `bsky.app` …

Fix link warnings

---

src/components/Dialog/index.tsx

Right now, there are two cases where the keyboard being visible when a dialog is visible causes problems.
1. When using the handle to dismiss the dialog. If we try to close the dialog while the keyboard is open, it will "bounce off" the keyboard, and will require two swipes to dismiss the dialog.
2. If we progmatically close the dialog, the keyboard will not be dismissed automatically.
1. We want to dismiss the keyboard whenever we touch the handle. By dismissing in `onTouchStart`, we ensure that the keyboard is dismissed in time for us to perform the swipe down gesture on the dialog.
2. We want to dismiss the keyboard in the close callback, so that if we progmatically close the dialog, the keyboard will dismiss as well.
https://github.com/bluesky-social/social-app/assets/153161762/d473a75 …

Dismiss keyboard when closing dialog

---

bskyweb/templates/base.html
web/index.html

browsers/UA sets a default font on buttons and inputs, causing the following screenshot to happen where the hashtag has a completely different font than the rest of the text

Reset button/input font set by UA

---

bskyweb/cmd/bskyweb/server.go
src/Navigation.tsx
src/components/Lists.tsx
src/components/TagMenu/index.tsx
src/components/TagMenu/index.web.tsx
src/lib/routes/types.ts
src/routes.ts
src/screens/Hashtag.tsx
src/state/util.ts
src/view/com/util/ViewHeader.tsx

Got slightly carried away with ALF here, as you know, ALF is very persuasive.
We can hold off on the ALF stuff if we want, it's pretty small though and we should probably start normalizing our lists, list footers, etc anyay. This is an example of how we can do that.
The current behavior of switching to the Search tab is a bit awkward. You cannot easily use native gestures on iOS to swipe back, and there are no animations that show the intended action of "pushing". We should prefer to move forward in the stack rather than switch tabs.
Adding a few components that can be reused in lists elsewhere that all use ALF will make the continual migration fairly easy. These are mainly just spinner components, one for the footer and one for the empty, loading state. This will also let us maintain …

Dedicated screen for hashtags, POC ALF list

---

package.json
src/view/com/composer/text-input/web/LinkDecorator.ts
src/view/com/composer/text-input/web/TagDecorator.ts
yarn.lock

Integrates new detection regex

Integrate new tag detection and regexes

---

src/alf/index.tsx
src/components/Lists.tsx
src/screens/Hashtag.tsx

- Adjust ALF's `gtTablet` to be equal to the old `isDesktop` breakpoint
- Move "Back" button up on breakpoints above `gtMobile`
- Adjust "go back" to support both web and native in one `onPress`
- Don't show share button on any web layout, only native
- Adjustable "Not found" reason (now displaying "No results found" in this case)
- Add borders on web

Few list tweaks on web

---

src/lib/hooks/useIntentHandler.ts

When checking the intent path, we use `new URL(url)` to parse the url. Generally, it is awkward for someone to use `bluesky:///intent/compose` since we commonly only use two slashes in a URL scheme. However, if we use `bluesky://intent/compose`, this makes the first part of the intent the hostname rather than part of the pathname.
Right now, we work around that with an `isNative` check. However, it is also possible for Safari to deep link into our app through `https://bsky.app/`. In that case, our `isNative` check will fail since we are checking the hostname for `=== intent` rather than the first part of the path name.
The best option is to ensure that `bluesky://` is converted to `bluesky:///` so that we can just always check the first part of the pathname for `=== intent` rather than …

Simplify intent path logic, ensure all variations work for bluesky://, bluesky:///, and https://bsky.app/

---

src/Navigation.tsx
src/view/shell/desktop/LeftNav.tsx

React Navigation initializes routes for us on native. We have the initial routes set to be `HomeTab` and `Home` inside of the home tab. However, on web, there are no initial routes. We should ensure one is created so that the new post button still works on web.
We also should fix the root cause of the error, which is caused by attempting to access `routes` whenever there is no navigation state. It isn't a given that `getState()` will actually return a value, so we should unwrap it before using it.
Fixes https://github.com/bluesky-social/social-app/issues/3043

Fix new post button on web after following intent URL

---

src/components/RichText.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx

Highlighting tags, links, etc. in quotes but keeping them unpressable. We should discuss if we actually want to do this though.

Enable tags inside of quotes

---

src/components/Dialog/index.tsx

The `BottomSheetBackdrop` component has some oddities to it. For one, even if a sheet is relatively small, the backdrop will reach its full opacity as soon as it reaches the first offset's height. This causes some inconsistencies between dialogs.
Second, the current implementation doesn't work well with conditionally rendered dialogs. The backdrop will not animate in, even though it will animate out.
This create a similar component with some simple Reanimated logic.
https://github.com/bluesky-social/social-app/assets/153161762/e2dc348c-859b-4573-aecf-1c028371527f
https://github.com/bluesky-social/social-app/assets/153161762/10334fd9-d219-4604-8c4d-924189c7c14c

Fix backdrop issues by using custom logic

---

src/view/screens/Profile.tsx

https://github.com/bluesky-social/social-app/assets/810438/92cce5c2-8658-49b8-96f2-caa029b20ce4
https://github.com/bluesky-social/social-app/assets/810438/7a5555b3-3811-455e-843d-714f76d7efa4
I know, right? It [seems](https://stackoverflow.com/a/42562623) like this may be [this](https://developer.chrome.com/blog/scroll-anchoring) but honestly idk.
I'm not sure why this wasn't happening in my initial web layout PR.
No effect in other browsers.
(╯°□°)╯︵ ┻━┻

Fix Profile tab switch jumps on Chrome

---

src/view/com/home/HomeHeader.tsx
src/view/com/home/HomeHeaderLayout.web.tsx
src/view/com/home/HomeHeaderLayoutMobile.tsx
src/view/screens/Home.tsx

In https://github.com/bluesky-social/social-app/pull/2998, I've added a tabbar to dekstop web. I believe this was necessary because having multiple feeds is a core feature of the app and you need to be aware of which feed you're on. Third-party feeds should feel just as "first-class" as our own feeds, so we shouldn't give preferential treatment to Following.
However, the tabbar was getting pretty noisy due to being tall and due to custom triggers. We could tune those but I think it's actually better to always keep the current header visible. Whereas the very top part can hide on scroll. In other words, we can apply the same UI as we do in Profile — and this also lets us just "use the platform" and do `position: sticky`.
Which this PR does.
You know, whatever's in prod now. …

Sticky desktop header

---

src/components/Dialog/index.tsx
src/components/Dialog/index.web.tsx
src/state/dialogs/index.tsx
src/view/shell/index.tsx

I recommend [reviewing without whitespace.](https://github.com/bluesky-social/social-app/pull/3094/files?diff=split&w=1)
With this PR, with VoiceOver/TalkBack enabled:
- dialogs should be "focused" when opened
- focus should be trapped within the dialog
Easiest to test on a real device: `npx expo run:ios --device` with your phone plugged in.

Improve dialogs a11y

---

src/view/com/home/HomeHeaderLayout.web.tsx

This is a slight iteration on https://github.com/bluesky-social/social-app/pull/3077.
This still uses `position: sticky`, but I'm bringing back the auto-hide behavior for the bottom part. So it combines the old and the new behaviors. Since the part being animated is narrow again, I think it strikes a nice balance — it doesn't feel too noisy when it hides or shows, and it frees up some vertical screen estate that https://github.com/bluesky-social/social-app/pull/3077 has claimed.
https://github.com/bluesky-social/social-app/assets/810438/c4fc501f-f71b-42d2-bdbf-f1f74d22e5e6

Hide feeds topbar on scroll

---

src/components/Dialog/index.tsx

We currently use `onChange` to determine if the dialog has closed or not. This works fine in most cases, however, there is the possibility that if we close the dialog too quickly - i.e. before it has fully opened by pressing on the backdrop - that the `onChange` callback won't be fired. The callback is not fired until it has _fully_ transitioned to the new state. Since the dialog doesn't ever open to it's full state to initially change the `index`, it won't fire when it closes since the index remains unchanged.
The solution is to use `onClose` instead of `onChange` for handling our sheet close behavior.
https://github.com/bluesky-social/social-app/assets/153161762/1387103e-6c08-4996-81ab-6683c44c12bf
- Observe current behavior. Open a dialog and quickly close it by pressing on the …

use `onClose` instead of `onChange` for close callback

---

app.config.js

Small one. Just adding a value for `newArchEnabled` to our `app.config.js`. As we start testing Fabric, the `app.config.js` will need to have `newArchEnabled` set to true. We will also need to re-run `yarn prebuild` and builds when switching between the two.
Because the flag add some environment variables that are "sticky", it's difficult to get rid of the flag unless you explicitly set it to `false` after you've enabled it. This just adds a `false` value so we don't have to worry about weirdness.

add `newArchEnabled: false` flag to app.config.js

---

bskyweb/templates/base.html
package.json
src/components/Dialog/context.ts
src/components/Dialog/types.ts
src/components/Menu/context.tsx
src/components/Menu/index.tsx
src/components/Menu/index.web.tsx
src/components/Menu/types.ts
src/view/screens/Storybook/Menus.tsx
src/view/screens/Storybook/index.tsx
web/index.html
yarn.lock

This PR adds a new abstraction to replace Zeego and the native context menus. It provides essentially the same interface as our `NativeDropdown` wrapper, but replaces the Radix dropdown on web, and uses a bottom sheet on native.
Usage looks like this:
```tsx
<Menu.Root control={menuControl}>
<Menu.Trigger label="Open menu" style={[a.flex_1]}>
{({state, props}) => {
return (
<Text {...props}>Open menu</Text>
)
}}
</Menu.Trigger>
<Menu.Outer>
<Menu.Group>
<Menu.Item label="Click me" onPress={() => {}}>
<Menu.ItemIcon icon={Search} />
<Menu.ItemText>Click me</Menu.ItemText>
</Menu.Item>
<Menu.Divider />
<Menu.Item
label="Another item"
onPress={() => menuControl.close()}>
<Menu.ItemText>Another item</Menu.ItemText>
</Menu.Item>
</Menu.Group>
</Menu.Outer>
</Menu.Root>
```

Add `Menu` component

---

app.config.js
plugins/withAndroidStylesWindowBackgroundPlugin.js
src/App.native.tsx

The current Android app displays a white screen before the splash screen. A white status bar is also displayed. I think this white display degrades the user experience of the app (especially on dark mode).
By applying this fix, white display is gone and startup and splash become more continuous and natural.
Note: this fix is only for Android apps, as I don't have iOS devices. To avoid side effects to the iOS app, I have applied some conditional branches and code separation between Android and iOS. 
* Example 1: Apart from the existing `SPLASH_CONFIG` and `DARK_SPLASH_CONFIG` in `app.config.js`,
`SPLASH_CONFIG_ANDROID` and `DARK_SPLASH_CONFIG_ANDROID` added.
* Example 2: `<StatusBar />` in App.native.tsx is only added on Android.

Improve splash display on android

---

src/view/shell/desktop/LeftNav.tsx

Initially I tried to make a solid version of the same icon but it didn't look good. So I'm just adjusting the existing one to better match in sizing.
The tablet/mobile versions are fine so didn't change those.
https://github.com/bluesky-social/social-app/assets/810438/6fa49259-71f8-496b-b9f1-b9dfec30360a
https://github.com/bluesky-social/social-app/assets/810438/82e5ed5c-5f91-415c-9bf5-d426b828af7e

Fix jumpy moderation icon on desktop

---

package.json
src/lib/app-info.ts
src/lib/sentry.ts
yarn.lock

Note: This relies on the expo package upgrades from https://github.com/bluesky-social/social-app/pull/3096
This PR removes `react-native-version-number` and uses `expo-application` to retrieve the same values. Tested on all platforms and the outputs line up with each other.
Open the settings screen, scroll to bottom, see that the "Build Version" is still correct (it should be 1.71.0 (1) on native, 1.71.0 on web)

Fabric migration - `react-native-version-number` -> `expo-application`

---

package.json
src/lib/haptics.ts
yarn.lock

This PR replaces `react-native-haptic-feedback` with `expo-haptics`. This PR is mostly just a matter of changing syntaxes, no other changes are required and all of the haptics are the same "styles" as they were before.
- Like a post
- Press and hold switch account
Testing these two functions will suffice. We only use `Haptics.default()` in the app as of right now.

Fabric migration - `react-native-haptic-feedback` -> `expo-haptics`

---

app.config.js
plugins/withAndroidManifestFCMIconPlugin.js

In the issue https://github.com/bluesky-social/social-app/issues/2983 , problem about notification icon on Android has been reported.  Although project has resource of notification icon for Android (`assets/icon-android-notification.png`), Is is not shown to real notification. I have built private android app from source code and confirmed this issue.
I think this issue is due to payload sent from FCM. `expo-notifications` library requires ONLY `data` payload. If `notification` payload exists, FCM directly shows notification without process of `expo-notification`. Currently, the app has no settings for FCM icons, so the default app icon appears unexpectedly. Refer the document about expo-notifications.
https://docs.expo.dev/versions/latest/sdk/notifications/#android-push-notification-paylo …

Apply notification icon settings of FCM on Android

---

src/components/Lists.tsx
src/screens/Hashtag.tsx
src/view/com/util/Views.d.ts
src/view/com/util/Views.web.tsx

Right now there's a double border on the hashtag screen's `CenteredView`. This moves the `CenterView` to only wrap the `ListMaybePlaceholder`, since `List` already includes borders.
To facilitate this easily, I'm also adding an optional `topBorder` to `CenteredView`, so that the look maintains consistency. (The border under the `ViewHeader` shouldn't just pop up after the list loads).
There's some pretty inconsistent behaviors across our view header. Some of them have margins on the sides, some do not. This tends to be a result of when and how we add the `ViewHeader` to the screen. Ideally, we'll start normalizing these. To maintain consistency with the best example, there are no side borders here on the `ViewHeader`. This is in line with the behavior of the Notifications screen. It's …

Fix double border on web hashtag list

---

Dockerfile

We need to run `extract` and `compile` when building for web, not just `compile` otherwise we might have outdated localizations.
This is mainly needed now because we are not continuously updating the .po files for releases, since the deploy process has changed. Web gets left out of the mix because of this.

Run `extract` and `compile` when building for web

---

src/lib/hooks/useInitialNumToRender.ts
src/screens/Hashtag.tsx
src/view/com/posts/Feed.tsx

This is the first step of working to improve FlatList performance. There's a couple of different parts that need to be fixed up, but this one addresses window size and the initial render.
The behavior right now renders 10 posts initially (10 posts here means 10 `FeedItem`s, not 10 individual posts, but that is a separate issue). After those ten posts, we fill ten more viewports worth of posts.
Window Size: https://reactnative.dev/docs/optimizing-flatlist-configuration#windowsize
Initial Number: https://reactnative.dev/docs/optimizing-flatlist-configuration#initialnumtorender
In the average feed, we will see between 4-6 posts. On some of the largest screens, the largest number of posts that we will be able to see on the initial render is eight. (There's also a somewhat relevant correlation …

Adjust FlatList performance in main feeds

---

src/components/TagMenu/index.tsx
src/components/TagMenu/index.web.tsx
src/screens/Hashtag.tsx

Sort of for backward compatibility, and for some emojis. There's some encoding happening that we just want to ensure we completely decode.

Allow all encoding for hashtags in URL

---

index.web.js
src/platform/markBundleStartTime.web.ts

Fixes the initial log we show on startup with the total module start time. It's calculated based on this constant which is set on native in the Metro bundle, but is not set by Webpack. This adds some code manually setting it.
We now see this on startup:
The module runs early:
No changes for native.

Mark bundle start time on web

---

src/Navigation.tsx
src/lib/statsig/statsig.tsx
src/lib/statsig/statsig.web.tsx

In the first commit, I copypasted `statsig.web.tsx` into `statsig.tsx` but replaced the SDK with the Expo version. The code is the same otherwise. We could also in principle use the Expo version in both places but I wanted to avoid an extra wrapper on the web so we have a bit more control there. We will unify them later on if this is not needed.
In the second commit, I added an explicit `init` event that's sent unconditionally from the navigator `onReady`. This kickstarts built-in Statsig metrics. Otherwise it doesn't count it as a visit. This also lets us send the time we spent executing the startup-blocking modules (which after https://github.com/bluesky-social/social-app/pull/3147 works on the web too) — so that'll be our first explicit perf metric.
Note any gates will only re-evaluate …

Enable gating and experimentation on native, send init event

---

src/components/Prompt.tsx

One of the driving motivators of moving these modals to ALF is accessibility. If users are using a very large font size, they are currently unable to scroll down to things like "Delete Post" inside of a modal. This is also an issue with the Prompt, since we just use a `Dialog.Inner`. We should instead use a `Dialog.ScrollableInner`, so that if the font size is too large, the user can scroll to the needed button.

Make ALF prompt scrollable for accessibility

---

src/lib/statsig/statsig.tsx
src/lib/statsig/statsig.web.tsx

This sets up a polling mechanism so that we ask Statsig for new configuration once every three minutes. The new configuration would still not be reflected in the UI, but it would get stored in local storage. So it will be used on the next fresh load. Practically, this means that instead of kicking in on N+2 load (where N is when we changed setting), it kicks in on N+1.
In this test, I adjusted the poll interval to be much shorter so we can observe how it works.
Verified that we periodically call `initialize` for the current user and get the config back. Verified that the config includes the latest data, but isn't reflected in the UI until next refresh. Verified updating the UI (e.g. via state updates) doesn't cause it to read new data. …

Poll gate configuration changes

---

src/lib/routes/router.ts
src/lib/strings/url-helpers.ts
src/routes.ts
src/state/preferences/in-app-browser.tsx

Emily noticed that RSS URLs are treated as internal atm. This fixes that.
Test post: https://bsky.app/profile/emily.bsky.social/post/3kn52xdg3cc2a

Fix RSS URLs treated as internal

---

src/view/com/util/post-ctrls/PostCtrls.tsx

The `aria-label` on the Share button was the same as the one on the Like button.
Before:
After:

Fix `aria-label` on the Share button

---

bskyweb/templates/base.html
web/index.html

Specifically looked at this to fix the date input, since `input` is set to `font: inherit` and we had no root element font-family set.

Fix font styles on web

---

src/view/com/util/forms/SelectableBtn.tsx
src/view/screens/Settings/index.tsx

Make the buttons full width in settings so it supports longer strings in other languages.
This is the least bad solution with the current constraints per my research. This would be solved neatly if RN would support `box-sizing: content-box` but it does not.
It's possible there is a more elegant solution, I'm not a CSS expert but I did spend quite a bit googling about this.
Before:
After:
Fixes #3060.

Fix button widths in the Settings on web

---

src/lib/sharing.ts

Should fix a small graphical issue when sharing on Android from the new menu popup. Right now, the dialog starts to close but freezes as the share sheet opens up. This will keep the sheet open until the sharing is complete so it doesn't look janky.

Await `share` before closing menu

---

app.config.js

Apparently this shows up as a possible intent filter on Android, so we can limit it to only being applicable for development.

Don't include `localhost:19006` as intent filter in production

---

src/components/Typography.tsx

On native, setting the `lineHeight` to the `fontSize` adds a bit of extra height that we don't want, preventing us from properly aligning text in some cases. Instead, let's only apply that on web (during testing, it *does* seem to help on web to do this). On native, if the line height is undefined or zero, don't change it.

Fix `lineHeight` problems on native with new `Text`

---

src/screens/Onboarding/StepAlgoFeeds/FeedCard.tsx

Just adding `flex_1` to the wrapper and `numberOfLines` to the feed title.

Fix onboarding `FeedCard` text overflow

---

src/view/com/util/load-latest/LoadLatestBtn.tsx

Fixes #2433
Rather than changing the z-index, I opted to move the button into the feed (aka the tablet layout) when the scroll to top button is at risk of overlapping the left nav. This is because for other languages (such as Spanish), simply placing the button above the left nav would result in the buttons overlapping.
https://github.com/bluesky-social/social-app/assets/10959775/e0d5c46a-a020-4e3d-b919-4d69e0f6fca5

Move scroll to top button inline if viewport is narrow (vertically)

---

src/components/Menu/index.web.tsx
src/components/Menu/types.ts
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/screens/Storybook/Menus.tsx

On the first go-around on Menu I hadn't considered just passing the props from `asChild` through, but after using it a couple times I realized this would be the better move.
This PR makes it so that most `Menu`s should just render a `Pressable` within `Menu.Trigger`. Should be pretty easy since we just spread `props`.
This PR is web only.

Improve `Menu.Trigger` on web

---

src/components/Link.tsx
src/components/Lists.tsx
src/lib/hooks/useDedupe.ts
src/lib/hooks/useNavigationDeduped.ts
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/util/Link.tsx
src/view/shell/bottom-bar/BottomBar.tsx

It's currently possible to encounter situations where you accidentally navigate to a screen twice, i.e. if you quickly press on a post or press twice when switching to a different tab. While this is certainly possible in various `onPress` events throughout the app, most are better handled with logic such as adding `disabled` states to buttons. However, in the case of our `Link` component or `BottomBar` component, it's more intuitive to create a small wrapper for `useNavigation()` that offers deduped functions such as `.push()` and `.navigate()`.
I am only applying this in the places where it is most needed. Generally, `<Link>` components are where we see this the most, as there is a small delay between press and rendering of the next screen. There's also some noticable delay it seems on …

Dedupe navigation events (push, navigate, pop, etc)
