bluesky-social/social-app

bskyweb/templates/base.html

Maximum scale creates accessibility issues for folks who need to zoom in

Remove max scale from viewport config `meta`

---

docs/build.md

This is not the smallest PR in the world, this is just a tribute.
(actually, it's just one byte, so it might be the smallest PR in the world)

Minor typo

---

bskyweb/cmd/bskyweb/server.go

Deploying this manually to fix it right now, but want to get it merged in as well.

Fix /api/waitlist API

---

src/view/com/pager/FeedsTabBarMobile.tsx
src/view/com/search/HeaderWithInput.tsx
src/view/com/util/ViewHeader.tsx

Fixes https://github.com/bluesky-social/social-app/issues/693

Update labels for avatar

---

package.json
src/view/com/posts/CustomFeedEmptyState.tsx
src/view/com/posts/FollowingEmptyState.tsx
yarn.lock

Conditionally navigating to `Search` on Web instead of `SearchTab` (mobile-only) for the empty feeds. Closes #805.

Fix button to find people to follow

---

src/view/screens/AppPasswords.tsx

Fixes https://github.com/bluesky-social/social-app/issues/714
https://jam.dev/c/8d71cf83-6681-423a-af50-020c0d8babaa
https://jam.dev/c/bbb7f277-7d71-4db6-995c-f04d72335662
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

Delete app password confirmation uses browser alert instead of "nice" dialogue

---

src/view/com/profile/ProfileHeader.tsx

Fixes https://github.com/bluesky-social/social-app/issues/697

Update follower/following a11y hints and labels

---

__tests__/lib/string.test.ts
src/lib/strings/time.ts

adjust the behavior of ago() to show the date after a week

show date after 7 days closes #754

---

src/view/com/lightbox/Lightbox.web.tsx

this adds arrow key navigation to the photo viewer
renamed onEscape to onKeyDown

Support arrow key navigation for Lightbox.web.tsx

---

src/view/com/profile/FollowButton.tsx

corrected some typo errors  when onToggleFollowInner log

[typo] correct typo was 'fo' instead of 'to'

---

src/view/com/modals/Modal.tsx

Fix: #732 
| Before      | After |
| ----------- | ----------- |
| <video src="https://github.com/bluesky-social/social-app/assets/8035517/f4b63431-f88f-469a-b4e1-78180e45d024" /> | <video src="https://github.com/bluesky-social/social-app/assets/8035517/f4fce26e-cc6f-4f80-ad56-c2384eff42c3" /> |

fix: content trimmed in server input modal

---

src/Navigation.tsx

Improve tab navigator performance by enabling lazy mode to reduce memory usage on startup.

perf: enable lazy loading for tab navigator

---

package.json
src/lib/ThemeContext.tsx
yarn.lock

This is why a lot of new PRs look like they are failing.
(also minor bump to expo package recommended by expo)

fix linting & type errors

---

src/view/com/pager/TabBar.tsx

Previously, when a feed item was clicked on in the feed tab bar, the `scrollTo` used to make it scroll to the start. This was because the `onLayout` and `measure` functions were not working correctly on Android and always returned `0` for the `x` co-ordinate value of the position of an item.
I refactored them to make the code simpler by using the event from the `onLayout` callback rather than the `ref` and now it works on Android, and faster on other platforms.

[APP-675] Fix feed tab bar scroll behavior on Android

---

src/view/com/posts/FeedItem.tsx

[APP-676] React error shown when deleting posts

---

src/view/com/lightbox/Lightbox.web.tsx

Allows users to click on the alt text to expand it if it takes more than 3 lines (responsive!)

[APP-656] make alt text expandable

---

.github/workflows/lint.yml
package.json
src/lib/api/api-polyfill.ts
src/lib/api/feed-manip.ts
src/lib/hooks/useTimer.ts
src/state/models/content/list-membership.ts
src/state/models/content/list.ts
src/state/models/discovery/foafs.ts
src/state/models/feeds/post.ts
src/state/models/lists/lists-list.ts
src/state/models/ui/shell.ts
src/view/com/composer/useExternalLinkFetch.ts
src/view/com/lightbox/Lightbox.tsx
src/view/com/modals/CreateOrEditMuteList.tsx
src/view/com/modals/ListAddRemoveUser.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/BlurView.web.tsx
src/view/com/util/Html.tsx
src/view/com/util/UserInfoText.tsx
src/view/screens/Settings.tsx
src/view/shell/desktop/LeftNav.tsx
tsconfig.check.json

Kind of a fat PR
- Adds `yarn typecheck` and includes it in our lint & typecheck workflow for all PRs
- Fixes a bunch of type errors that we had let accumulate

Fix a bunch of type errors and add a type-check to the github workflows

---

src/lib/constants.ts
src/state/models/discovery/suggested-actors.ts
src/view/com/search/SearchResults.tsx

This PR moves the suggested follow recommendations to the server, which is more dynamic and opens up more customization to server operators as the network federates

Move suggested follow recommendations to the server

---

src/platform/detection.ts
src/view/screens/Home.tsx

- Adds some helpers to detect web window
- Add a resize listener in feeds
- Cleanup resize listener

[APP-686] Fix mobile web styling

---

src/lib/api/feed-manip.ts
src/state/models/feeds/posts.ts
src/state/models/ui/preferences.ts
src/state/models/ui/shell.ts
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/modals/PreferencesHomeFeed.tsx
src/view/screens/Settings.tsx

Hey y'all 👋 thought this would be fun to have. This PR adds a settings modal with a few content filters like disabling replies, reposts, etc. Did my best with styling, but I'm sure there are improvements to be made.
Lmk if I can add/fix anything, but also feel free to run with this if you're keen, or close it if not ✌️

Home feed content customizations

---

src/state/models/ui/shell.ts
src/view/com/composer/Composer.tsx
src/view/com/modals/Confirm.tsx

Fixes #906 
- Changes text from "Cancel" to "Discard"
- Makes text red
- Makes button red

[APP-711] Fix cancel post dialog confusion

---

src/view/screens/PrivacyPolicy.tsx
src/view/shell/desktop/RightNav.tsx

Fixes some links that I botched when we moved the privacy policy

[APP-712] Fix some broken links on policy docs

---

src/view/com/modals/PreferencesHomeFeed.tsx

Closes #895. Fixes dark mode and updates some copy errors.

[APP-713] Fix copy and dark mode styles in the home feed preferences

---

__e2e__/jest.config.js
__e2e__/mock-server.ts
jest/test-pds.ts
package.json
src/view/com/lists/ListActions.tsx
yarn.lock

A couple of things broke with the simulator that needed fixing
- Switched to the `dev-env` package to make it easier to stay up-to-date
- Fixed some testIDs

Simulator fixes

---

src/view/com/composer/text-input/TextInput.tsx
src/view/com/modals/report/ReportAccount.tsx
src/view/com/modals/report/ReportPost.tsx
src/view/com/search/HeaderWithInput.tsx
src/view/com/util/forms/DropdownButton.tsx

- Composer text input now scales input correctly
- Cancel button in the search header no longer wraps
- Report post/account now scrolls to account for overflow
- Dropdowns now wrap text instead of clipping

[APP-692] Accessibility font-scaling fixes

---

src/state/models/ui/create-account.ts
src/view/com/auth/create/Policies.tsx
src/view/com/auth/create/Step2.tsx

Adds this notice for users who are not yet 18:

Include a notice during account creation for under-18 users

---

src/lib/api/feed-manip.ts
src/locale/helpers.ts
src/locale/languages.ts
src/view/com/lists/ListCard.tsx
src/view/com/lists/ListItems.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx

- When multiple languages are declared on a post, narrows them down using the language model. This is necessary because many multi-lingual users have their devices set to multiple languages and aren't aware they need to declare just one.
- Adds a "Translate" link to posts in a language other than the user's content languages
- Updates some layouts around user text to help with RTL language alignment
|Feed|Thread|
|-|-|
|<img width="390" alt="CleanShot 2023-06-30 at 10 49 38@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/f501bb28-f076-47dd-b622-053e7c03c575">|<img width="400" alt="CleanShot 2023-06-30 at 10 51 06@2x" src="https://github.com/bluesky-social/social-app/assets/1270099/6fbeb969-ac76-4365-983c-c2217df1b05e">|

[APP-718] Improvements and fixes to language handling

---

src/state/models/content/post-thread-item.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx

- Fixes an issue with state sync that would cause mute toggling to fail in some cases
- Fixes copy in the confirmation toast

[APP-719] Fix thread muting

---

src/view/screens/Settings.tsx

- Fixes an issue with account switching where your profile links in the shell would not update

[APP-593] Fix: reset navigation state on account switch

---

src/state/models/discovery/foafs.ts
src/view/com/posts/FollowingEmptyState.tsx
src/view/com/posts/MultiFeed.tsx

This is a pretty basic PR that introduces some changes for onboarding
- Move Discover Custom Feeds button to the top of the feeds tab
- Add Discover Custom Feeds button to empty following page
More concrete changes are still in discovery

[APP-708] Onboarding revamp

---

src/view/screens/SavedFeeds.tsx

Fixes an overflow issue in the scrolling list on Web for the saved feeds screen

Fix saved feeds screen layout on web (close #920)

---

src/lib/media/manip.ts
src/view/com/lightbox/Lightbox.tsx

Add permission checks before saving image

---

src/lib/hooks/useOTAUpdate.ts

Caused a lot of noise on Sentry: https://blueskyweb.sentry.io/issues/4224534379/events/aadc769dfc7b4d0596ccbcc224ae0969/

[APP730] OTA error logging

---

src/lib/api/feed-manip.ts

fix: typo in feed-manip.ts

---

src/lib/notifee.ts
src/state/models/feeds/notifications.ts
src/view/com/notifications/FeedItem.tsx
src/view/com/pager/TabBar.tsx

[APP-702] Render Custom Feed likes properly

---

src/view/com/modals/ChangeHandle.tsx
src/view/com/pager/TabBar.tsx
src/view/com/util/forms/SelectableBtn.tsx
src/view/screens/Settings.tsx

Added instructions for .well-known method (supersedes #887)

---

src/lib/hooks/useIsKeyboardVisible.ts
src/lib/styles.ts
src/locale/helpers.ts
src/locale/languages.ts
src/state/models/ui/preferences.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/char-progress/CharProgress.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/post/Post.tsx
src/view/com/util/forms/DropdownButton.tsx
src/view/index.ts

- Add a simpler dropdown for selecting the language
- Use full language name in the composer footer
- Fix the character counter bouncing the UI around
- Add the translate link to notifications
- Bonus: Fix the iOS composer footer padding when the keyboard is dismissed

[APP-735] Post language improvements

---

src/lib/constants.ts
src/view/com/auth/withAuthRequired.tsx
src/view/screens/Settings.tsx

[APP-28] add status page link 

---

src/state/models/ui/shell.ts
src/view/com/notifications/FeedItem.tsx
src/view/com/post/Post.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserPreviewLink.tsx
src/view/shell/index.tsx

- Fixes a crash error when you navigate from the profile preview
- Fixes the lightbox layering order (goes on top of modals now)
- Adds the profile preview behavior to the notifications screen
- Fixes post meta overflowing on web

Fixes and improvements to the Profile Preview modal

---

src/view/shell/Composer.web.tsx

https://jam.dev/c/e20b85d9-d345-405e-809b-8c222092b6b0
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

[Web] A lot of post content in a modal causes parts of modal to become inaccessible

---

src/view/com/profile/ProfileHeader.tsx

Fix cursor not being a pointer on profile back button

---

src/view/com/composer/text-input/TextInput.tsx

Fixes #929 
Hacky, but appears to fix the issue at hand. We may need to revisit one day 🤞

#929 Wrap `PasteInput` updates in a `setTimeout`

---

src/view/screens/ProfileList.tsx

[APP-778] Fix mute list overflow

---

package.json
src/state/models/discovery/feeds.ts
src/view/screens/DiscoverFeeds.tsx
yarn.lock

Paginate "Discover Feeds" screen

[APP-720] Paginate custom feeds

---

src/state/models/content/list.ts
src/state/models/lists/lists-list.ts
src/state/models/root-store.ts
src/state/models/ui/profile.ts
src/view/com/modals/ListAddRemoveUser.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/screens/Profile.tsx

https://github.com/bluesky-social/social-app/assets/1919066/a886bd7b-bc02-4871-ba96-badf7f5b4ceb
> Last item removal from list of lists
https://github.com/bluesky-social/social-app/assets/1919066/49007655-4ecd-4845-a9a2-619c75b22759
> Save changes on list modal

List cleanup on remove

---

src/view/com/util/EventStopper.tsx
src/view/com/util/forms/NativeDropdown.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

This PR makes it possible to open the dropdown using keyboard events. It requires a bit of a hack (simulating a click) but it gets the job done.

Fix keyboard support on the dropdown

---

src/view/com/modals/ChangeHandle.tsx

Right now the button on the change handle screen says "Verify DNS Record" even if text file based verification is being used. Kinda confusing, small fix :~)

Update copy for text file based username verification

---

src/state/models/cache/posts.ts
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/post-embeds/ExternalLinkEmbed.tsx

- Fixed the black bar appear in the link-cards on mobile
- Fixed the icon color for feed likes in notifications
- Fixed the spacing of post embeds
- Added quote posts to the posts cache so they get the instant render optimization on press

Collection of small UI fixes & improvements

---

src/view/com/post-thread/PostThread.tsx

Fixes an issue in large threads where the windowing behavior would fire `onContentSizeChange` when scrolling, cause it to "fight" the user
https://github.com/bluesky-social/social-app/assets/1270099/5883d7f1-0b71-4bff-a378-31729120657e

Fix repeated firing of scroll into view on large threads

---

src/state/models/feeds/notifications.ts
src/state/models/feeds/post.ts
src/state/models/feeds/posts-slice.ts
src/state/models/feeds/posts.ts

Switch to stable react keys. This should improve performance in the application.

Performance: switch to stable react keys

---

__e2e__/tests/self-labeling.test.ts
package.json
src/lib/api/index.ts
src/lib/icons.tsx
src/lib/moderation.ts
src/state/models/ui/preferences.ts
src/state/models/ui/shell.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/com/modals/ModerationDetails.tsx
src/view/com/modals/SelfLabel.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/forms/SelectableBtn.tsx
src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/moderation/PostAlerts.tsx
src/view/com/util/moderation/PostHider.tsx
src/view/com/util/moderation/ProfileHeaderAlerts.tsx
src/view/index.ts
yarn.lock

Adds the ability to set labels on your own post. Currently just some NSFW labels, will add more over time.
https://github.com/bluesky-social/social-app/assets/1270099/d8a67b20-c7e9-4100-bb4e-8ba265ee936a
Before merging:

Add self-labeling controls

---

src/lib/strings/helpers.ts
src/state/models/media/image.ts

Fixes #1124: Trim alt text before saving

---

__e2e__/mock-server.ts
__e2e__/tests/profile-screen.test.ts
jest/test-pds.ts
src/state/models/ui/profile.ts
src/view/com/feeds/CustomFeed.tsx

Fix to feeds view in profiles

---

src/view/com/lists/ListItems.tsx

Small palette fix. Closes #1170

Fix link color in dark mode (close #1170)

---

src/view/com/util/ViewSelector.tsx

Fixes an issue where some header elements get cut off

Remove view selector offsetting (close #1174)

---

src/state/models/feeds/notifications.ts

use greater of indexedAt or machine clock

---

src/state/models/ui/shell.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/labels/LabelsBtn.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/modals/SelfLabel.tsx

Closes #1173 - newlines no longer inserted when you press cmd+enter
Closes #1149 - selected text is no longer linkified when you paste a url
Closes #1169 - disables the adult content controls if there is no media on the post

A set of composer fixes

---

src/locale/helpers.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx

default translate to device language

---

src/lib/strings/handles.ts

allow handles to start with a number

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx

Fixes #1234
Good place to test from: `/profile/why.bsky.team/post/3k5iqhiguoa22`

fix thread double border

---

src/view/com/auth/login/Login.tsx

[APP-835] trim end of email during login

---

src/state/models/ui/shell.ts
src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/TextInput.web.tsx
src/view/screens/Profile.tsx
src/view/shell/Composer.tsx
src/view/shell/Composer.web.tsx
src/view/shell/desktop/LeftNav.tsx
src/view/shell/index.tsx
src/view/shell/index.web.tsx

Closes #1206 
Web
https://github.com/bluesky-social/social-app/assets/8207733/e0cab755-d7f1-4e55-9c6c-00d9a3db5786
iOS
https://github.com/bluesky-social/social-app/assets/8207733/a98c42c8-1cc3-45da-8d73-66f0252abbe4

[APP-834] Allow @ing someone in post directly from profile

---

src/view/com/util/forms/ToggleButton.tsx
src/view/screens/Settings.tsx

Fixes #1252
- Makes the border in a toggle a little larger
- Fixes copy (h/t @emilyliu7321 )

Fixes #1252 fix alt text setting description toggle

---

src/view/screens/Profile.tsx

Closes #1277 
Saw we had this on web, figured we wanted on mobile too.

don't mention own user from composer

---

src/view/com/post-thread/PostThread.tsx

wrap mutation in runInAction

---

src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/Link.tsx

Closes #1288
Uses CSS to add a `cursor: pointer` to all post cards.

Make posts behave more like links

---

.github/workflows/golang-test-lint.yml
Dockerfile
bskyweb/Makefile
bskyweb/README.md
bskyweb/go.mod
bskyweb/go.sum

We're hitting this in all the other golang repos at the same time.

update golang to v1.21; set GOEXPERIMENT=loopvar

---

src/state/models/ui/create-account.ts
src/view/com/auth/LoggedOut.tsx
src/view/com/auth/create/CreateAccount.tsx
src/view/com/auth/create/Policies.tsx
src/view/com/auth/login/Login.tsx
src/view/com/util/layouts/LoggedOutLayout.tsx

Small UI update to logged out views so that we don't look quite so amateur

Improvements to UI in web logged-out views

---

src/view/com/composer/text-input/web/EmojiPicker.web.tsx

Fixes #1328 and Fixes #1283 
Also:

Fix #1328 fix emoji picker scroll on firefox and chrome

---

src/view/com/notifications/FeedItem.tsx

Show images in notification if post also has record embed

---

src/state/models/feeds/notifications.ts

[APP-838] Refresh when Empty

---

src/state/models/content/post-thread.ts

Sort thread replies by likes

---

web/static/js/emoji-mart-data.js

Opted for a warn in case we ever see this in prod

prevent error screen on startup

---

src/view/com/auth/create/Step2.tsx

Hotfix: Fix unable to enter invite code

---

docs/build.md

- Use pnpm (for atproto repo)
- Clarify when prebuild is needed

Update build instructions

---

src/view/com/pager/FeedsTabBar.web.tsx
src/view/com/util/load-latest/LoadLatestBtn.web.tsx
src/view/screens/CustomFeed.tsx
src/view/screens/Home.tsx
src/view/shell/desktop/Feeds.tsx
src/view/shell/desktop/RightNav.tsx
src/view/shell/desktop/Search.tsx

Updates the desktop UI to move the feeds navigation from the header to a right hand nav that's a little easier to use
https://github.com/bluesky-social/social-app/assets/1270099/72949d7e-3091-42ce-bd52-d57d4ced55f0

Feeds navigation on right side of desktop

---

src/view/com/composer/text-input/web/EmojiPicker.web.tsx

Similar to the composer or the modal, we want to prevent Emoji Picker clicks from bubbling up!
Fixes #1423

Fix 1423 Prevent emoji picker clicks from bubbling up

---

src/state/models/content/list.ts

Closes #1430 
Fixes an issue where large lists would fail deletion by applying too many writes

Separate list deletion into chunks (close #1430)

---

src/view/com/post-thread/PostThread.tsx

Large threads have been reported to crash the app in some cases. This update adds pagination on _render_, which doesn't fully solve the problem but does buy some head room.

Paginate the PostThread to avoid rendering too many posts

---

src/lib/analytics/types.ts
src/view/com/profile/ProfileHeader.tsx

Fix 651 Make followers and following button into a `<Link>`

---

LICENSE

update Bluesky PBLLC to PBC (Public Benefit Corporation)

---

src/lib/ThemeContext.tsx

It's allll coming together now.
Dan brought this up, great call: https://github.com/bluesky-social/social-app/pull/1417#issuecomment-1719879738

fix theme switching on web without refresh

---

src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx

The post controls became a bit too hard to hit recently, this readds the hitslop to fix that

Readd hitslop to post controls

---

src/lib/strings/display-names.ts

Sanitize BIDI characters from display names

---

package.json
src/state/models/ui/preferences.ts
src/view/com/auth/onboarding/RecommendedFeeds.tsx
yarn.lock

Small fixes to issues found during release testing

Various release fixes

---

src/Navigation.tsx
src/lib/routes/types.ts
src/routes.ts
src/state/models/content/post-thread.ts
src/state/models/ui/preferences.ts
src/view/index.ts
src/view/screens/PreferencesHomeFeed.tsx
src/view/screens/PreferencesThreads.tsx
src/view/screens/Settings.tsx

Add thread sort settings

---

docs/build.md

Add a tip about Android emulator memory limit

---

package.json
src/lib/api/feed/merge.ts
src/state/models/content/post-thread.ts
src/state/models/ui/preferences.ts
src/view/screens/PostThread.tsx
src/view/screens/PreferencesHomeFeed.tsx
src/view/screens/PreferencesThreads.tsx
yarn.lock

Updates home feed and thread preferences to store server-side.

Move home feed and thread preferences to server

---

src/view/com/post-thread/PostThreadItem.tsx

Missed this in my last PR, this makes sure that the translator link shows on the expanded post view.

update translator link show logic

---

bskyweb/cmd/bskyweb/server.go

Update backend routes to match frontend

---

src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/com/util/Link.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx
src/view/screens/CustomFeed.tsx
src/view/screens/Feeds.tsx
src/view/screens/Home.tsx
src/view/screens/Settings.tsx
src/view/shell/desktop/LeftNav.tsx

- Adds some missing a11y labels
- Updates the home feed header offset to scale correctly with the text size

Accessibility fixes: add missing labels, dynamically scale home header

---

src/state/models/ui/create-account.ts

Trim whitespace on invite code

---

__e2e__/tests/create-account.test.ts
__e2e__/tests/invite-codes.test.ts
__e2e__/tests/profile-screen.test.ts
src/view/com/testing/TestCtrls.e2e.tsx

Fixes to tests

---

src/view/com/composer/photos/Gallery.tsx

I used real container width, like in ImageLayoutGrid.tsx. And also count gap between images
Fixes #1323

Fix gallery image size

---

docs/build.md

Didn't know how to do this. Documenting for the future.

Add instructions for running on device

---

src/view/com/util/post-ctrls/RepostButton.web.tsx

Use refreshed dropdown style for repost/quote post dropdown

---

src/view/com/notifications/FeedItem.tsx

Fixes #1559
Allows the click to fall through to the underlying pressable, rather than a noop if there's only one person in the group of notifications
Also I've added the tooltip hover for the timestamp too

Don't render a pressable if there's only one notification author

---

src/Navigation.tsx
src/lib/hooks/useAccountSwitcher.ts
src/state/models/ui/shell.ts
src/view/com/modals/Modal.tsx
src/view/com/modals/SwitchAccount.tsx
src/view/com/util/AccountDropdownBtn.tsx
src/view/screens/Notifications.tsx
src/view/screens/Settings.tsx
src/view/shell/bottom-bar/BottomBar.tsx

Supercedes #1555
Closes https://github.com/bluesky-social/social-app/issues/1514

Account quick switch modal

---

src/view/shell/Drawer.tsx

Fix 1449 styling when on FeedsTab

---

src/view/com/util/UserAvatar.tsx
src/view/com/util/UserBanner.tsx

Closes https://github.com/bluesky-social/social-app/issues/1595

Fix bad reference when image picker is canceled

---

src/view/com/auth/onboarding/RecommendedFeeds.tsx

A small change, but one that affects all new users.

Fixed a typo on the onboarding recommended screen

---

src/view/com/profile/ProfileHeader.tsx
src/view/com/util/EmptyState.tsx

Two small fixes to the profile UI
1. Change the press state of the follow recommendations button
2. Add a border to the empty state
|.|.|
|-|-|
|![CleanShot 2023-10-04 at 12 58 23@2x](https://github.com/bluesky-social/social-app/assets/1270099/dc307bb7-d76f-4542-9ce0-50c8ec5acd00)|![CleanShot 2023-10-04 at 12 58 39@2x](https://github.com/bluesky-social/social-app/assets/1270099/070165e4-13f6-49ba-9000-e5db1ffebb03)|
|.|.|
|-|-|
|![CleanShot 2023-10-04 at 12 57 31@2x](https://github.com/bluesky-social/social-app/assets/1270099/dd2d711e-42c5-4cce-8a6c-46e649d3fcf8)|![CleanShot 2023-10-04 at 12 57 59@2x](https://github.com/bluesky-social/social-app/assets/1270099/c034c2fc-57b4-4412-98ce-e1cf808ab725)|

Profile UI tweaks

---

package.json
src/view/com/modals/SwitchAccount.tsx
yarn.lock

Noticed the swipe gestures failing on the bottom-sheet. Pulling latest upstream fixed it.

Pull upstream bugfixes to bottom-sheet

---

src/view/com/composer/Composer.tsx

This was throwing an error on web.

Only listen to back button on android

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx

Fixes a regression introduced in https://github.com/bluesky-social/social-app/pull/1624.
It seems like Reanimated has some kind of compiler behavior that _infers_ `useAnimatedReaction` "dependencies" but since it doesn't analyze functions, it doesn't know that my `getCommittedScale` helper reads `committedTransform.value`.
If I understood it correctly, this seems like a pretty big footgun — would be nice to lint against render scope function calls there then? Anyway, I inlined the helper to its usage points and clarified the intention of the code.
1. Double tap
2. [Without this fix] the controls don't disappear
3. [With this fix] the controls disappear, as they should
1. Pinch in (controls disappear)
2. Double tap out
3. [Without this fix] the controls don't appear
4. [With this fix] the …

Fix stuck lightbox header after double tap

---

src/state/models/cache/my-follows.ts

Missed this in review, must have missed this in my automated test run too. Merging so I can get release out.

Fix bug that prevents unfollowing

---

src/state/models/media/image.ts

react-native-image-cropper -> react-native-image-crop-picker
https://github.com/bluesky-social/social-app/blob/77b21dfb1c2871447bf60ebf9efeb283282a1b51/src/state/models/media/image.ts#L1
https://github.com/bluesky-social/social-app/blob/77b21dfb1c2871447bf60ebf9efeb283282a1b51/package.json#L131
https://github.com/ivpusic/react-native-image-crop-picker

Fix typo in image.ts

---

src/state/models/me.ts
src/view/com/modals/InviteCodes.tsx
src/view/screens/Settings.tsx
src/view/shell/Drawer.tsx
src/view/shell/desktop/RightNav.tsx

Reverts bluesky-social/social-app#1591
Closes https://github.com/bluesky-social/social-app/issues/1655

Revert "Fix invite codes flash on desktop, use loading placeholder"

---

src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx

When some custom feeds were offline, it caused a crash on device

Fix feed switching crash

---

src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx
src/view/com/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx

Same as https://github.com/bluesky-social/social-app/pull/1666/commits/ed8523c117934a96ef2c2fe7d7ab7534d20bd961 but for Android. Added comments.
Don't want to do this at a higher level to avoid breaking memoization.

Fix MobX crash for Android lightbox

---

package.json
yarn.lock

Helps with #1654 
I made a [PR to zeed-dom](https://github.com/holtwick/zeed-dom/pull/9) to fix an infinite loop issue. For now, I've pushed a branch (to my personal github, we may want to change that) that we can install from to use the new version until everything can get updated downstream.

resolve fork of zeed-dom

---

src/lib/analytics/analytics.tsx
src/lib/analytics/analytics.web.tsx
src/state/models/feeds/post.ts
src/view/com/profile/ProfileHeader.tsx

1. Uses hashed did for analytics instead of hashed email
2. Fixes #1364

Update Analytics 

---

src/view/shell/desktop/LeftNav.tsx

This fixes the vertical alignment on the new post button, and improves the text.
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/bluesky-social/social-app/assets/33783503/02f5f330-fe8b-4450-841f-edc4c6a10dd8)  | ![image](https://github.com/bluesky-social/social-app/assets/33783503/1c413df6-ad28-44f9-87cc-a63f90a295e3)  |
Will do another PR to fix the search bar in a moment, similar issues there.

Improve New Post button

---

src/lib/constants.ts
src/lib/strings/helpers.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/text/RichText.tsx

This is for PR #1718 
Requesting review from @pfrazee 
There is a constant `MAX_POST_LINES` in `src/lib/constants.ts` that controls the behaviour. I have set it to `25`
https://github.com/bluesky-social/social-app/assets/11888687/420e6f37-b878-4f90-aef0-ff2baa768851

Added Show More for Long Posts

---

docs/testing.md

Fixed typos in `docs/testing.md`

---

README.md

Updated the mistake

---

src/lib/link-meta/link-meta.ts

Treat PHP pages as HTML

---

src/lib/styles.ts
src/view/com/lists/ListsList.tsx
src/view/screens/Lists.tsx
src/view/screens/ModerationModlists.tsx

Minor layout fixes. Verified works on Android and web too.
https://github.com/bluesky-social/social-app/assets/810438/45a9ecc2-3245-4cc8-84e2-8132af634d32
https://github.com/bluesky-social/social-app/assets/810438/a0873709-84f4-4a84-bcc7-e802ad639701

Fix minor list layout bugs

---

bskyweb/templates/base.html

This PR corrects `<meta>` tag attributes. Many thanks!

Correct meta tag attributes

---

src/App.native.tsx
src/App.web.tsx
src/state/models/ui/preferences.ts
src/state/preferences/index.tsx
src/state/preferences/languages.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/select-language/SelectLangBtn.tsx
src/view/com/modals/lang-settings/ContentLanguagesSettings.tsx
src/view/com/modals/lang-settings/LanguageToggle.tsx
src/view/com/modals/lang-settings/PostLanguagesSettings.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/screens/AppPasswords.tsx
src/view/screens/LanguageSettings.tsx

Refactors the language preferences away from the mobx preferences model and into its own context/hooks with the new persistence layer

Move language preferences to new persistence + context

---

src/state/models/session.ts

Added back to the old model. I've been using model attributes and methods as a todo list of sorts. Will get to these soon.

Fix type errors

---

package.json
src/state/queries/actor-autocomplete.ts
src/state/queries/preferences/index.ts
src/view/shell/desktop/Search.tsx
yarn.lock

Just the desktop autocomplete portion

Desktop user autocomplete search

---

src/lib/link-meta/bsky.ts
src/state/queries/post.ts
src/view/com/composer/useExternalLinkFetch.ts

Should allow us to remove `PostThreadModel`

Update post embed fetching to use new methods

---

src/App.native.tsx
src/App.web.tsx
src/lib/analytics/analytics.tsx
src/lib/notifications/notifications.ts
src/state/events.ts
src/state/models/ui/shell.ts
src/state/session/index.tsx
src/state/shell/index.tsx
src/state/shell/reminders.ts
src/state/shell/tick-every-minute.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/profile/ProfileSubpageHeader.tsx
src/view/com/util/TimeElapsed.tsx
src/view/screens/Home.tsx
src/view/screens/Notifications.tsx
src/view/screens/Profile.tsx
src/view/screens/Search/Search.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/desktop/LeftNav.tsx

- Move tick-every-minute into a hook/context
- Create a new global events bus for soft-resets and session events
- Update UIs, push-notifications, and analytics to use new systems

Shell behaviors update (react-query refactor)

---

src/view/com/modals/ProfilePreview.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/screens/Profile.tsx

Let's bring them back :)
https://github.com/bluesky-social/social-app/assets/810438/6251f030-9279-4c1e-aed3-e550da6dd587
https://github.com/bluesky-social/social-app/assets/810438/ec0273e0-1dba-403a-9faa-3127fe1b4d6b
The "preview to profile" mobile behavior is still a bit borked for me, will look into that separately.

Add profile loading shim

---

src/state/queries/app-passwords.ts
src/state/queries/list-members.ts
src/state/queries/list-memberships.ts
src/state/queries/list.ts
src/state/queries/my-blocked-accounts.ts
src/state/queries/my-lists.ts
src/state/queries/my-muted-accounts.ts
src/state/queries/preferences/index.ts
src/state/queries/profile-extra-info.ts
src/state/queries/profile-feedgens.ts
src/state/queries/profile-follows.ts
src/state/queries/profile-lists.ts
src/state/queries/suggested-feeds.ts
src/state/queries/suggested-follows.ts

(cherry picked from commit 1be2060a2b81741dcf9a392160af87d2747b3497)

Revise cache times

---

src/lib/hooks/useNonReactiveCallback.ts
src/view/com/modals/Modal.tsx

See comments. We're gonna be using this new Hook in a few more places.
https://github.com/bluesky-social/social-app/assets/810438/9418e57f-e36e-4871-b5e6-0a41ab1ed462
https://github.com/bluesky-social/social-app/assets/810438/1760048c-1206-42c3-acbf-2df8b78ff160

Fix jumpy modal regression

---

src/view/screens/Profile.tsx

Add missing type

---

src/view/com/util/UserAvatar.tsx
src/view/shell/Drawer.tsx
src/view/shell/NavSignupCard.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarWeb.tsx
src/view/shell/desktop/LeftNav.tsx
src/view/shell/desktop/RightNav.tsx
src/view/shell/desktop/Search.tsx
src/view/shell/index.web.tsx

https://github.com/bluesky-social/social-app/assets/4732330/1cf0daf0-5ae7-47c8-af34-c800b5d9c353
https://github.com/bluesky-social/social-app/assets/4732330/40d3e9bf-f858-494b-8269-9d7da5c23278

[PWI] Shell

---

src/view/screens/Search/Search.tsx

Updates only affect the default view. Actually searching for things has not changed.

[PWI] Search page

---

src/view/com/auth/LoggedOut.tsx
src/view/com/auth/SplashScreen.tsx
src/view/screens/Search/index.tsx
src/view/screens/Search/index.web.tsx

Tested on my physical android device too, hence the adjusted value on Android.

[PWI] Clean up logged out screen

---

src/state/session/index.tsx
src/view/com/profile/ProfileHeader.tsx
src/view/screens/Profile.tsx

I think this is all there is, lmk if I missed something.

PWI: Profile

---

src/view/screens/Profile.tsx

Show feeds in PWI

---

src/locale/i18n.web.ts
src/locale/i18nProvider.web.tsx

Allow dynamic locale imports for web

---

src/state/queries/feed.ts
src/view/screens/ProfileFeed.tsx

[PWI] Fall back for non-public feeds

---

src/view/com/modals/SwitchAccount.tsx

Was using the wrong account here

Fix bad references in account switcher

---

src/state/persisted/index.ts
src/state/persisted/legacy.ts

I want to track success/failures of this, just in case.

Raise levels of some logs during pre-release

---

app.config.js
eas.json
package.json

Create build v1.57

---

src/lib/hooks/useAccountSwitcher.ts

Changed order of these things. This is not very smooth at the moment, but that's due to how we reset query cache and state, which we plan to fix.

Nav home after switch accounts

---

src/view/com/feeds/FeedPage.tsx
src/view/com/pager/FeedsTabBar.web.tsx
src/view/com/pager/FeedsTabBarMobile.tsx
src/view/screens/Home.tsx

[PWI] Home

---

src/state/queries/post-feed.ts
src/view/screens/Home.tsx

Noticed this while debugging missing content on first load of home screen.

Ensure we use following feed if merge is disabled

---

src/view/com/feeds/FeedSourceCard.tsx
src/view/com/util/LoadingPlaceholder.tsx
src/view/screens/SavedFeeds.tsx

Opted not to include pinning or saving in the optimistic updates since saving is within `FeedSourceCard` and overall it results in a lot of state to manage.

Improve feed reordering with optimistic updates

---

src/state/queries/post-feed.ts

The `select` function is re-executing on every render, and since it is always producing new slices, bailouts below in the tree no longer work. The fix is to [memoize the `select` function](https://tkdodo.eu/blog/react-query-data-transformations#3-using-the-select-option).
https://github.com/bluesky-social/social-app/assets/810438/d90d4b2e-6c67-46d5-bfaf-40b39e725d5b
https://github.com/bluesky-social/social-app/assets/810438/5c2c4e44-7a3c-4925-ba35-5c47a147df6f

Fix lag when switching tabs

---

package.json
src/view/com/feeds/FeedPage.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Home.tsx
src/view/screens/Profile.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

Noticed this happening and thought this was an easy enough fix. Easiest way to test is to throw some logs in, and drop the `pollInterval` in `Feed` to like 3s.

Only poll feed when feed page is focused

---

src/view/com/profile/ProfileHeader.tsx

Fixes dark mode. No changes for light mode.

Fix show suggested button color

---

src/view/com/util/LoadingPlaceholder.tsx

|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 17 11 50](https://github.com/bluesky-social/social-app/assets/1270099/2249f15d-3441-4e7c-a64b-ee9bc65edc6b)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 17 11 11](https://github.com/bluesky-social/social-app/assets/1270099/00da7bf5-5a74-4a33-ab50-3d6c3b725ed6)|
|Before|After|
|-|-|
|![CleanShot 2023-12-02 at 17 12 35@2x](https://github.com/bluesky-social/social-app/assets/1270099/9d3260d6-b732-436e-a64b-42734c6fe900)|![CleanShot 2023-12-02 at 17 00 13@2x](https://github.com/bluesky-social/social-app/assets/1270099/923fc07f-9b91-424a-8e03-4117fce7ccab)|

Tweak the loading placeholders to use the full space and position better

---

src/lib/build-flags.ts
src/view/shell/createNativeStackNavigatorWithAuth.tsx

Going to need a nap after this PR 😮‍💨

Add PWI build flag

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/moderation/PostHider.tsx
src/view/com/util/moderation/ProfileHeaderAlerts.tsx

|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 18 56 14](https://github.com/bluesky-social/social-app/assets/1270099/915d41bc-028c-4820-937f-adf88ee90b32)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 18 56 01](https://github.com/bluesky-social/social-app/assets/1270099/1b63445b-7508-4afd-a0ce-8624b2325287)|
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 18 09 20](https://github.com/bluesky-social/social-app/assets/1270099/8b2fe489-f752-49f7-af1a-a0841a9c4677)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-02 at 18 10 31](https://github.com/bluesky-social/social-app/assets/1270099/709600f7-98ae-4383-b512-34aadb45f58e)|

Improve the post-hiders and the header alerts

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/view/com/posts/FeedErrorMessage.tsx

Handles specifically 429s on feedgens

Handle feedgen 429

---

src/view/screens/Profile.tsx

Rename Posts & Replies to Replies

---

src/state/queries/notifications/feed.ts
src/state/queries/post-feed.ts
src/state/queries/post-thread.ts
src/state/queries/util.ts

Updates the search by the post-thread query for placeholder data to include quoted posts, reducing even more cases where the user might get a spinner during the PostThread load time.

Perf: Include quote posts in the post-thread placeholder

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/state/queries/feed.ts
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedErrorMessage.tsx
src/view/screens/ProfileFeed.tsx

Surface raw server error if exists

---

src/lib/analytics/types.ts
src/state/muted-threads.tsx
src/state/queries/post.ts
src/state/queries/profile.ts
src/state/session/index.tsx
src/view/com/auth/login/LoginForm.tsx
src/view/com/auth/onboarding/RecommendedFeedsItem.tsx
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedItem.tsx
src/view/screens/ProfileFeed.tsx
src/view/screens/ProfileList.tsx

I went through all the analytics events on web and mobile and added, removed, and modified any events that were lost/changed during our state transition.

Check Analytics

---

src/view/com/post-thread/PostThread.tsx
src/view/com/post-thread/PostThreadItem.tsx

Just trying to get this to a non-bad place now. We're going to need a real design pass with Fons on this soon.
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 Pro - 2023-12-06 at 21 02 22](https://github.com/bluesky-social/social-app/assets/1270099/80c4db4e-da92-49f5-bfb0-74196624a280)|![Simulator Screenshot - iPhone 15 Pro - 2023-12-06 at 20 59 28](https://github.com/bluesky-social/social-app/assets/1270099/504a33dc-7c3e-4d89-a8f3-458eb0dc3627)|

Treeview: more UI tweaks

---

src/view/com/util/images/AutoSizedImage.tsx

|Before|After|
|-|-|
|![CleanShot 2023-12-07 at 10 27 02@2x](https://github.com/bluesky-social/social-app/assets/1270099/e4db44d9-12c3-492b-9c24-757f29262953)|![CleanShot 2023-12-07 at 10 26 48@2x](https://github.com/bluesky-social/social-app/assets/1270099/c58d4113-8f53-414f-86ed-fbfa7dfbf4e6)|

Increase the maximum ratio of images from 5:1 to 10:1

---

src/lib/api/feed-manip.ts

Fix: remove replies to deleted and blocked posts from feeds

---

src/view/com/util/forms/PostDropdownBtn.tsx

Had a double separator in this dropdown, fixed in this PR

Fix double sep

---

src/lib/hooks/useAccountSwitcher.ts

Fixes https://github.com/bluesky-social/social-app/pull/2135/files#r1419618341.
Any navigations adjacent to app remounts might need similar fixes.
A more comprehensive alternative could be to adjust our code to always `pushState` early. But that his might break the router so let's wait with that.
https://github.com/bluesky-social/social-app/assets/810438/2e89c7c7-e8b2-45b0-ab96-69d29b32ded7

Fix Home navigation after account switch on the web

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po

Fix bad merge in translations

---

src/locale/locales/cs/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/view/screens/Moderation.tsx

Update pwi opt-out language

---

src/state/cache/post-shadow.ts
src/state/cache/profile-shadow.ts
src/state/queries/actor-search.ts
src/state/queries/search-posts.ts
src/view/screens/Search/Search.tsx

Switches the user search to use the proper endpoint, gets actor and post search integrated with the shadow caches, and fixes the missing cursor in the post search

Various search fixes

---

src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/post-embeds/index.tsx

I think it was just checking the wrong decision prop, post vs quoted post.

Fix quote post moderation check

---

src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/view/screens/Moderation.tsx

Tweak the PWI opt-out copy again

---

package.json
src/lib/api/feed/author.ts
src/state/queries/post-feed.ts
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/Feed.tsx
src/view/screens/Profile.tsx
yarn.lock

Updates atproto deps and uses the new approach in https://github.com/bluesky-social/atproto/pull/1776
Will wait for app view deployment to merge this 👍

Use new filter for Posts tab on profile

---

src/view/com/posts/FollowingEmptyState.tsx
src/view/com/posts/FollowingEndOfFeed.tsx

Fix empty state width

---

src/view/com/composer/threadgate/ThreadgateBtn.tsx

Fixes #2160
Uses the same pattern used elsewhere in the app

Fix 2160: Dismiss keyboard when threadgate settings are opened

---

src/state/queries/feed.ts

If a feed failed to load, we didn't catch the error and filter out that failure, which resulted in no pinned feeds shown to user.

Handle failed pinned feed fetches when rendering list of pinned feeds

---

src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/feeds/ProfileFeedgens.tsx
src/view/com/util/LoadingPlaceholder.tsx
src/view/screens/SavedFeeds.tsx

Revise FeedSourceCard load state to allow deletion for failures

---

src/lib/broadcast/index.ts
src/lib/broadcast/index.web.ts
src/lib/broadcast/stub.ts

Tested using separate tabs and the `Stub` implementation.

Stub broadcast channel for unspported contexts

---

src/view/shell/desktop/RightNav.tsx

[Review this without whitespace](https://github.com/bluesky-social/social-app/pull/2186/files?diff=split&w=1)
https://github.com/bluesky-social/social-app/assets/4732330/f574ff99-f011-480d-92d5-bff5185e0dea

Make right nav scrollable on short screens

---

src/view/screens/Moderation.tsx

Tested on iOS, Android, and Web (including mobile web). Works fine on all platforms.

Make moderation screen scrollable

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/PostMeta.tsx
src/view/com/util/UserAvatar.tsx
src/view/com/util/forms/PostDropdownBtn.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx

Scoping this update a bit tighter to what it actually affects.
https://github.com/bluesky-social/social-app/assets/810438/8335e802-289d-412b-946b-7789e2dcca30
https://github.com/bluesky-social/social-app/assets/810438/11eb21b0-2a16-49d2-8e88-1fb5f9c4ddde

Re-rendering improvements for like/unlike

---

src/view/com/pager/PagerWithHeader.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2185.
Previously, child page refs were registered on render and never cleaned up. The idea was that they'd get GC'd anyway with the parent eventually. However, since the onScroll handler is throttled, sometimes we'd try to access the refs when they're not good anymore. The leads to a weird crash in https://github.com/bluesky-social/social-app/issues/2185.
This PR changes refs to be synced with the React lifecycle so that they would actually get cleaned up on unmount. The throttled listener would still fire, but it would be a no-op because I added a null check before trying to adjust the scroll. To avoid over-firing, I've made `registerRef` a stable function that takes the `index`. The `index` is now passed down by the child itself. …

Clean up pager refs to fix crash

---

src/view/shell/desktop/RightNav.tsx

Today's fix for overflow scrolling on the right nav was causing a deadzone for the mousewheel. This approach fixes that

Rework the rightnav overflow behavior to not obscure the scroll region

---

docs/build.md

This PR fixes build instructions.

Add i18n setup in build instructions

---

package.json
src/Navigation.tsx
src/lib/build-flags.ts
src/locale/locales/en/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po
src/state/queries/actor-autocomplete.ts
src/state/queries/post-feed.ts
src/state/shell/logged-out.tsx
src/view/com/auth/HomeLoggedOutCTA.tsx
src/view/com/auth/LoggedOut.tsx
src/view/com/post-thread/PostThread.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/moderation/ScreenHider.tsx
src/view/screens/Home.tsx
src/view/screens/Profile.tsx
src/view/screens/Search/Search.tsx
src/view/shell/Drawer.tsx
src/view/shell/NavSignupCard.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/bottom-bar/BottomBarWeb.tsx
src/view/shell/desktop/LeftNav.tsx
yarn.lock

- c403f4df11af839c18053974daee86cfc41c1955 Enables the PWI
- 27240df9c84cc051beb9e37407916d0d88992ff9 and d6dd208d6a9ae79c58e37d045885ad0199cf086b Removes feeds from the PWI
- 4bad9783565740d093fb55be16bdb2cd57473bae Replaces the PWI home screen with a CTA
- 62dc3b1db09dcebc9a1ab51a878848968abfc1d6 Updates the signin/create buttons to go straight to the relevant interfaces
- d60684ccada2ff95d230dd03efad77120d82e7fe and cf049eb4d37f995b5bb542de94082a0bc436c323 Improves the screenhider UI for opted out users
- 1a6bdd86c157791a70a7fef7e031691e65068c9f Filters accounts in autocomplete
- e45081ba54a463f622d8c5dfabdec5db3b9d3ec2 Filters reply-branches that are opted out to avoid a bunch of useless "Sign in required" warnings
- c1afb7f5dc3d1bbd3c98bdb83b474b6ba038a9d0 Applies moderation …

PWI behavior updates

---

src/lib/api/index.ts
src/view/com/composer/Composer.tsx

Log post creation failures

---

src/view/com/auth/LoggedOut.tsx

Add search button to logged out view

---

src/view/com/auth/create/state.ts

in my defense, 3 and 8 look reeeeally similar

Fix the is13 check in account creation (close #2258)

---

src/view/com/composer/Composer.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx

- 9b2b527e2d4cc00a05e7a6fa72787e703c78a3f9 Keep the emoji picker visible in the tablet viewport
- ec111fc67f239366ba59843322b77009fe22f8eb Support selecting a mention via pressing tab

Web composer improvements

---

lingui.config.js
src/locale/__tests__/helpers.test.ts
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts
src/locale/locales/en/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po

This PR localizes the Bluesky app in French. It has been independently checked within the team but we are open to community suggestions!

Add French localization

---

bskyweb/cmd/bskyweb/rss.go

- `pubDate` in RFC 822 datetime syntax
- remove `author`, which is supposed to be an email address. we already include the handle in the title of the overall feed
- add `isPermaLink=false` to `<guid>`
Just to note publicly, a known issue with these RSS feeds is going to be that the number of elements varies. This is because we are fetching a fixed number from the API, then filtering out re-posts. For accounts which re-post a lot, this will result in few feed items. We *could* have bskyweb paginated the API until it has enough items, but I think the better solution in the long run would be adding a query param to the feed endpoint to filter out reposts. I opened an issue for that here: https://github.com/bluesky-social/atproto/issues/1984
A sample of what the RSS looks like:
```xml
<rss …
```

bskyweb: iterate on RSS format, based on feedback

---

bskyweb/cmd/bskyweb/rss.go

rss: isPermaLink (case-sensitive)

---

src/view/screens/Settings.tsx
src/view/shell/Drawer.tsx

|Drawer|Settings|
|-|-|
|![CleanShot 2023-12-24 at 14 23 09@2x](https://github.com/bluesky-social/social-app/assets/1270099/8ee0a0e6-84bd-4984-aa11-dfc3a068b081)|![CleanShot 2023-12-24 at 14 23 03@2x](https://github.com/bluesky-social/social-app/assets/1270099/46956e17-e427-4716-b2b7-d54b8a75b804)|

Add policy links to left nav and settings page

---

src/lib/moderatePost_wrapped.ts

Followup to https://github.com/bluesky-social/social-app/pull/2299, apply the "hide post" behavior to quotes

Apply post-hide to quote posts

---

src/locale/i18n.ts

Looks like we had a bad copy pasta on this one

Correctly load spanish localization

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx

Also adds the appeal dropdown in the feed context

Fix: only show appeal CW item on moderated posts

---

src/lib/api/feed-manip.ts
src/view/screens/Search/Search.tsx

This is not an ideal solution, but we need to defend against duplicate react keys so here we are

Protect against react key duplicates (close #2278)

---

src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/PostMeta.tsx

Avis of replies in treeview-mode was missing blurring behavior

Fix missing avatar moderation in replies

---

src/view/com/modals/Threadgate.tsx
src/view/screens/PreferencesHomeFeed.tsx

This PR adds marks for localization to more texts.
Only these messages are left out, while the texts before and after are subject to localization.
Many thanks!

Mark more text for localization

---

src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts

Unfortunately we have to disable the german translation until we can get it fixed.

Temporarily disable the german translation

---

src/view/screens/Search/Search.tsx
src/view/screens/Search/index.tsx
src/view/screens/Search/index.web.tsx
src/view/shell/createNativeStackNavigatorWithAuth.tsx
src/view/shell/desktop/Feeds.tsx
src/view/shell/desktop/RightNav.tsx

Fixes #2253 
Not entirely happy with the logic of figuring out what screen it's on to hide the small one in the right nav. Is there a better way of finding what the current screen is?

Show search in centre column on desktop

---

src/view/com/auth/create/Step2.tsx
src/view/com/modals/BirthDateSettings.tsx
src/view/com/util/forms/DateInput.tsx

Tested using a prod account on web/ios/android and editing the dates between them.

Handle birth dates as UTC, handle locale formatting

---

src/view/com/auth/create/Step2.tsx
src/view/com/auth/login/LoginForm.tsx
src/view/screens/Search/Search.tsx

Modifying some settings to see if they might fix #2333

Create account tweaks

---

lingui.config.js
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts
src/locale/locales/ko/messages.po

Korean localization branched from #2210.

Add Korean localization

---

src/locale/locales/ja/messages.po

This PR adds translations for some messages, and also fixes some existing translations.
Dear @Hima-Zinn @tkusano @dolciss @oboenikui
I would appreciate your review and feedback on these text updates.
Many thanks!

Add and fix Japanese localization

---

src/view/screens/PreferencesHomeFeed.tsx

This pull request aims to enhance the user experience within the Settings UI by addressing the noticeable flickering that occurs when sliding the slider in the left direction.
Previously:
https://github.com/bluesky-social/social-app/assets/52163880/e3eb927b-407a-4d8a-b488-f9f30208de67
Now:
https://github.com/bluesky-social/social-app/assets/52163880/cae749bc-a29c-4eb5-ba10-6cde1b31f6fc

Fix: Slider flicker issue

---

src/lib/styles.ts
src/view/com/feeds/FeedSourceCard.tsx
src/view/screens/Moderation.tsx
src/view/screens/SavedFeeds.tsx
src/view/shell/desktop/RightNav.tsx

Centered delete icon in feed source card
Previously :
Now :
Removed addition border in Edit My Feeds screen and Saved Feeds screen
Previously :
Now : 
Aligned all items in right nav bar
Previously :
Now :

Fix: Web design issues

---

src/lib/styles.ts
src/view/com/feeds/FeedSourceCard.tsx
src/view/screens/Moderation.tsx
src/view/screens/SavedFeeds.tsx
src/view/shell/desktop/RightNav.tsx

Initially merged into this branch to tweak the borders, but nvm, LGTM we can merge this 👍

Fix: Web design issues (#2377)

---

lingui.config.js
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts
src/locale/locales/es/messages.po

We put our Spanish localization through another 3rd party review and now we are confident to enable it

Enable Spanish Localization

---

src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po

There were a few translations that snuck in that were stale (not used anymore). Also Spanish was broken. This fixes that and also recompiles all existing translations with `yarn intl:build`

Recompile all locales

---

src/locale/locales/pt-BR/messages.po

Recompile all locales (https://github.com/bluesky-social/social-app/pull/2411)

Recompile all locales (#2411) for Portuguese (BR)

---

__tests__/lib/string.test.ts
src/lib/strings/embed-player.ts

Fixes https://bsky.app/profile/dlvienna.bsky.social/post/3kibe6kb33c2k

support intl tenor links

---

package.json
src/state/session/index.tsx
yarn.lock

Relies on https://github.com/bluesky-social/atproto/pull/2010

Do not nuke session on unknown backend errors

---

lingui.config.js
src/locale/__tests__/helpers.test.ts
src/locale/helpers.ts
src/locale/i18n.ts
src/locale/i18n.web.ts
src/locale/languages.ts
src/locale/locales/id/messages.po

This PR will add Indonesian localization and solved #2331.

Add Indonesian localization

---

src/view/com/modals/ContentFilteringSettings.tsx
src/view/com/modals/InviteCodes.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/screens/AppPasswords.tsx
src/view/screens/Settings.tsx

This PR adds marks for localization to unlocalized texts left on several screens.
Many thanks!

Mark more texts for localization

---

src/view/com/util/post-embeds/QuoteEmbed.tsx

|Before|After|
|-|-|
|![CleanShot 2024-01-10 at 22 43 09@2x](https://github.com/bluesky-social/social-app/assets/1270099/61865df1-ca44-4233-a11e-838948be49e8)|![CleanShot 2024-01-10 at 22 43 18@2x](https://github.com/bluesky-social/social-app/assets/1270099/71329b8a-a02c-4070-a822-3d66adc36891)|

Increase the number of lines for quote posts from 6 to 20

---

src/view/screens/Settings.tsx

My email gets pretty long :sweat_smile:

Truncate long email addresses

---

src/state/session/index.tsx

Creates a profile record for new users, which helps with search

Create a profile record on new user

---

src/view/com/lists/ListCard.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2335

Show muted/blocked status on list card

---

__e2e__/mock-server.ts
__e2e__/tests/create-account.test.ts
__e2e__/tests/invites-and-text-verification.test.ts
__e2e__/tests/text-verification.test.ts
__e2e__/util.ts
jest/test-pds.ts
package.json
src/state/session/index.tsx
src/view/com/auth/create/CreateAccount.tsx
src/view/com/auth/create/Step1.tsx
src/view/com/auth/create/Step2.tsx
src/view/com/auth/create/Step3.tsx
src/view/com/auth/create/StepHeader.tsx
src/view/com/auth/create/state.ts
src/view/icons/index.tsx
yarn.lock

Adds phone-number verification to account creation driven by server config. Is *not* 2FA. Still needs the api package to get bumped so won't run yet.

Phone number verification in account creation

---

src/view/com/util/Link.tsx

Fixes https://github.com/bluesky-social/social-app/issues/839

Exempt well-known paths from being handled internally

---

__tests__/lib/string.test.ts
src/lib/strings/embed-player.ts

Fixes https://github.com/bluesky-social/social-app/issues/2561

Set start time on YouTube embeds

---

src/view/com/composer/Composer.tsx
src/view/com/modals/Modal.web.tsx

Fixes https://github.com/bluesky-social/social-app/issues/1871

Prevent close on backdrop for alt text edit modal

---

src/Navigation.tsx

fixes this: https://github.com/bluesky-social/social-app/pull/2566#issuecomment-1900054733
@estrattonbailey 👍

set proper content style to fix background color

---

src/view/com/auth/create/Step2.tsx

Modify the position of the `<Trans>` in `Step2.tsx`.
Thank you!

Correct position of `<Trans>` in `Step2.tsx`

---

src/view/com/post-thread/PostThread.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2574

Don't expose post content on no-unauthenticated

---

src/view/screens/Search/Search.tsx

Supersedes #2589
From original PR by @skiniks
> This pull request introduces a search history feature to the application, limiting the history to the 5 most recent searches. This enhancement tracks and displays the user's latest searches, automatically removing the oldest entry when a new search is conducted. The history is displayed under the search bar, allowing for easy repetition of previous searches. Duplicate searches are intelligently handled by bringing the existing query to the top, avoiding redundant entries. This feature, integrated with AsyncStorage for persistence, is designed to blend seamlessly into the existing UI, offering an intuitive and improved user experience.
Changes added:
- Put most recent searches on top
- Only show search history when input is focused and no …

Add local search history (builds on #2589)

---

bskyweb/cmd/bskyweb/formating.go
bskyweb/cmd/bskyweb/formatting_test.go
bskyweb/cmd/bskyweb/rss.go
bskyweb/cmd/bskyweb/server.go
bskyweb/cmd/bskyweb/testdata/atproto_embed_post.json

This PR is on top of https://github.com/bluesky-social/social-app/pull/2427
Additions:
- merges main to fix an unrelated CI failure
- adds a single simple test for URL expansion
- tweaks code a bit to be more readable
- include a note when there is a quote post, though doesn't (yet) actually expand that quoted post text
- also uses this "expanded" text in RSS feeds

more social card tweaks, and include in RSS as well

---

src/locale/locales/de/messages.po

German translation updated.
EDIT: Paul Frazee here, hope you'll forgive the heist @snackpackwayne and thank you for this contribution. Going to reprint my comment below:
We've given up on the agency and are looking for a long-term replacement, but in the meantime we're going to do the following:
- Keep pulling in feedback with this PR.
- In a seperate PR, we're going to temporarily remove the german translation so that we're not pressed for time.
Bear in mind: this is a difficult thing for us to adjudicate because we don't speak german. We struggle to distinguish between suggestions and the reason we use agencies is to help us make the judgment calls. We just need a better agency.

German translation updated

---

src/state/queries/post.ts
src/view/com/util/post-ctrls/PostCtrls.tsx

Applies #1933 to post like/unlike and repost/unrepost. This fixes race conditions that prevented you from quickly unliking an accidentally liked post (or same for reposts).
https://github.com/bluesky-social/social-app/assets/810438/d844a466-c5a5-4de8-b1d7-af80a4afefdd
https://github.com/bluesky-social/social-app/assets/810438/c4a23306-2449-4298-859a-79ce6dba029a

Fix races for post like/unlike and post/repost

---

src/screens/Deactivated.tsx
src/view/com/auth/create/CreateAccount.tsx
src/view/com/auth/create/Step1.tsx
src/view/com/auth/create/Step2.tsx
src/view/com/auth/create/Step3.tsx
src/view/com/util/PostMeta.tsx

- 319fa69816ba5ac763633d53252f2853386239b0 Fix a bug introduced a couple PRs ago
- 071af4034deb63f535aa804e8b40b7f8c67147fa Larger tap targets in account creation
- b83d2a02353ba624a6f2b60ab2b677b9971660ac Smoother keyboard behaviors on mobile for account creation
- 32cee77a37b94dc7c7d42f4f8d888d6df50c8c29 Better autocompletion behaviors on mobile for account creaiton
- e0b6f3bf3a35f1a80f2e9ea1e0eb4f0103b9938a Use the logo in the account-creation queue

Account creation improvements & some other fixes

---

src/screens/Onboarding/StepFollowingFeed.tsx

Corrects a couple of typos which crept into one of the onboarding screens.

Correct typos in StepFollowingFeed.tsx

---

src/view/com/util/LoadingPlaceholder.tsx

Matches the layout changes from https://github.com/bluesky-social/social-app/pull/2647 for the placeholder.

Adjust placeholder to be pixel-perfect

---

bskyweb/templates/base.html
web/index.html

https://bugs.chromium.org/p/chromium/issues/detail?id=1521160

Fix chrome font weight rendering

---

src/view/screens/Notifications.tsx

Fixes an issue where `isScrolledDown` is not correct on focus, which caused us to not invalidate when we should have.
This is kind of a hack.
The `isScrolledDown` is not always reliably synchronous after the web layout PR. I've tried to fix that in a few different ways but it's a bit difficult due to the interplay of React Navigation, React's own rendering cycle, and the scroll restoration behaviors.
It's easier to just synchronously query it directly on web.
Scroll down notifications. Go to another tab. Return to notifications. We're still scrolled down, so no invalidation.
Scroll notifications to top. Go to another tab. Return to notifications. We're scrolled up, so we invalidate.
No changes to behavior on other platforms.

Fix notification invalidation condition on web

---

src/view/com/auth/create/Step3.tsx

I think the left margin is unnecessary because there is already space there.
If that's what you meant, please close this PR.
Thank you!

Remove left margin of full handle in `Step3.tsx`

---

src/locale/locales/ca/messages.po

Update the catalan localization with the newly added lines

Update the catalan localization with the newly added lines

---

src/view/com/pager/Pager.tsx
src/view/com/pager/Pager.web.tsx
src/view/com/pager/PagerWithHeader.tsx
src/view/com/pager/PagerWithHeader.web.tsx
src/view/screens/Home.tsx
src/view/screens/Search/Search.tsx

Bottom position is never being used and already doesn't work properly. Let's rm.

Remove dead code for pager

---

src/view/com/modals/DeleteAccount.tsx

just adding scroll to the delete account modal and an android adjustment so it presents nicely.
https://github.com/bluesky-social/social-app/assets/153161762/2c0bd7ba-5faf-4ec4-936f-37f6960babf5

fix scrolling in delete account modal

---

src/lib/strings/password.ts
src/state/modals/index.tsx
src/view/com/auth/login/ForgotPasswordForm.tsx
src/view/com/auth/login/SetNewPasswordForm.tsx
src/view/com/modals/ChangePassword.tsx
src/view/com/modals/Modal.tsx
src/view/com/modals/Modal.web.tsx
src/view/screens/Settings.tsx

fixes https://github.com/bluesky-social/social-app/issues/2688
- Check that it's base32
- Check that it is properly formatted and trimmed
- Show error on input blur if invalid

password flow improvements

---

src/view/screens/ProfileList.tsx

Fixes https://github.com/bluesky-social/social-app/issues/2659
Checks if `isSaved` or `isPinned` is true, if so, fires a non-blocking mutation to remove the user list from saved/pinned array

Remove user list from pinned once deleted

---

src/view/screens/Moderation.tsx

link in Moderation screen cannot be tapped #2745

link in Moderation screen cannot be tapped #2745

---

src/locale/locales/de/messages.po

Changed "Benachrichtigungen" to "Mitteilungen"

Solved Issue #2793

---

src/locale/locales/zh-CN/messages.po

Translated the Chinese (zh-CN) to version 1.68, and made some adjustments to certain translated terms.

Update zh-CN localization to 1.68

---

src/view/com/pager/PagerWithHeader.tsx

Follow-up to https://github.com/bluesky-social/social-app/pull/2815#discussion_r1483862392.
I think this is sufficient.
I'll test more tomorrow.

Fix layout calculations

---

.github/workflows/deploy-nightly-testflight.yml
app.config.js
eas.json
package.json
scripts/bumpAndroidBuildNumber.sh
scripts/bumpIosBuildNumber.sh

Mainly just setting up the GitHub workflow. Submits build nightly at 10 PM PST.
Also a new convenience script for local bumps:
```sh
yarn bump # Bumps build number for both platforms
yarn bump:ios # Bump just ios
yarn bump:android # Bump just android
```

eas nightlies

---

src/view/com/modals/ContentFilteringSettings.tsx

Always open adult content preferences in Safari on iOS

---

src/screens/Onboarding/StepSuggestedAccounts/index.tsx

Small one. Just changing `Follow All` to `Follow` if we deselect anyone in the follow recommendations during onboarding.

change `follow all` to `follow` if any recommendation is deselected in onboarding

---

src/locale/locales/pt-BR/messages.po

Leave the file identical to the number of lines in the English version!

Cleaning up old codes pt_BR

---

src/view/com/util/forms/SearchInput.tsx
src/view/screens/Feeds.tsx

Adds a button to the header of the feeds list that focus the search input. I think we should focus on reworking this screen a good bit later, think we'll be discussing that coming up.
https://github.com/bluesky-social/social-app/assets/153161762/51243315-e727-4959-a9c5-1ddb26cb8b15

Add search button to header on feeds screen

---

src/view/com/post-thread/PostThread.tsx

In theory these could be duplicate. I couldn't actually repro this case because deletion cuts off the parents but let's fix just in case (and for when we'll fix it to not cut off the parents).

Fix duplicate keys in PostThread

---

src/view/com/post-thread/PostThread.tsx

This is based on the work @haileyok started in https://github.com/bluesky-social/social-app/pull/2755.
Currently, the generator functions produce the FlatList items for the UI, including elements like:
- Top page header
- Individual parent items
- The highlighted post
- The reply prompt
- "Replies are loading" spinner
- Individual reply items
- The footer
They do this while iterating over the post structure (upwards for parents, downwards for children).
There are some issues with this approach.
One issue is that the generators were written to be more expressive than what the backend sends *and* what the component can actually handle. E.g. we could never end up with two child spinners, but the data structure makes it seem like we can. On the other hand, if we *did* end up with two child …

Move visual display logic out of PostThread generators

---

bskyweb/templates/base.html
web/index.html

This PR adds preconnect links to optimize performance by establishing early connections to the following third-party origins: `bsky.app`, `bsky.social`, and `bsky.network`. Potential saving of 280ms according to `Lighthouse`.

Adds `preconnect` links to essencial external domains

---

src/view/com/post-thread/PostThread.tsx

I'm splitting https://github.com/bluesky-social/social-app/pull/2755 into independent parts so that it's easier to understand how the fix is layered, and to ensure that it's correct (especially if we revisit this in the future). The overall problem and the solutions are described in https://github.com/bluesky-social/social-app/pull/2755 in detail.
In this PR, we're including these parts of the fix:
- The native side will no longer try to adjust scroll in `onContentSizeChange`. That's not a good place to adjust scroll because on the native it is asynchronous—so if we failed to maintain the scroll position by this point, the user has already seen a jump. We'd like to always use `maintainVisibleContentPosition` on native, including for cached posts.
- In order to make …

Adjust post thread scroll for cached posts

---

src/view/com/pager/PagerWithHeader.tsx

I first tried https://github.com/bluesky-social/social-app/pull/2816, then I tried https://github.com/bluesky-social/social-app/pull/2817, but that still wasn't enough. I started seeing jumpy layout on my profile. This version works in more hops but seems to actually be reliable. Third time's the charm, right?
Observe the glimmer appearing at just the right vertical offset.
https://github.com/bluesky-social/social-app/assets/810438/64235965-d13d-413b-a12e-7a357f9d5bcd
https://github.com/bluesky-social/social-app/assets/810438/ab2b5570-49cd-4349-b783-c9b775d9e116

Fix layout measurements (again)

---

src/lib/themes.ts

Just overrides more colors using dimPalette, which is 1 stop lighter on the scale.

Bump contrast on dim mode for old ds

---

bskyweb/templates/base.html

Just adding to `bskyweb` since this won't affect dev

Add link header to improve apple messages previews

---

src/lib/constants.ts
src/lib/strings/url-helpers.ts
src/screens/Onboarding/StepTopicalFeeds.tsx
src/view/com/auth/create/state.ts
src/view/com/auth/server-input/index.tsx

`IS_PROD` should only be false if it's a local dev service of the bsky staging service.

Update IS_PROD check

---

src/view/com/util/forms/PostDropdownBtn.tsx

When you're on a post thread route, and then delete the post you're currently viewing, the experience gets confusing. Your URL says you're still on that post, and then a subsequent reply will cause a refetch that will fail.
https://github.com/bluesky-social/social-app/assets/810438/e4d61f80-4fc8-4ad1-8964-b5c148b72dce
To fix this, let's just navigate Back if we're deleting the post we're currently on.
https://github.com/bluesky-social/social-app/assets/810438/eac7cb8a-8d39-41cf-953a-2db74c4f1722
This isn't a perfect fix (what if the post you're navigating to is also deleted?) but it's close enough for the common case. I believe that's what Twitter is doing as well.
Verified on the web and iOS.

Navigate back from a deleted post's route

---

patches/@react-navigation+native+6.1.7.patch
patches/@react-navigation+native+6.1.7.patch.md

Fixes https://github.com/bluesky-social/social-app/issues/710
Patching react-navigation with @SlickDomique's PR below. Tested with the various repros found in the linked issue and am seeing good results.
https://github.com/react-navigation/react-navigation/issues/11832
https://github.com/react-navigation/react-navigation/pull/11833

patch react-navigation to fix history bug

---

src/lib/link-meta/link-meta.ts

Small one. Just bumping the timeout for cardby.

Increase cardyb timeout to 15 seconds from 5 seconds

---

src/components/TagMenu/index.tsx
src/components/TagMenu/index.web.tsx
src/components/dialogs/MutedWords.tsx
src/lib/strings/helpers.ts
src/view/com/util/forms/NativeDropdown.tsx
src/view/com/util/forms/NativeDropdown.web.tsx

Fixes some usability issues that cropped up

Tags menu/muted words improvements

---

src/view/screens/Home.tsx

How are we feeling about this?

Use selected feed for window title on Home

---

src/lib/__tests__/moderatePost_wrapped.test.ts
src/lib/moderatePost_wrapped.ts

Updates API for the match function, and adds exceptions for languages either without spaces, or with space usage that's different from latin and other languages that use spaces between each word.

Improve muted word matching

---

bskyweb/cmd/bskyweb/server.go

Need this for the compose intents

Add /intent/compose to bskyweb

---

src/lib/__tests__/moderatePost_wrapped.test.ts
src/lib/moderatePost_wrapped.ts

If you make a post with a mute word in it, it should still show up in your timeline and on your profile.

Don't mute your own posts

---

src/components/TagMenu/index.web.tsx

Just a safety thing for web usage going forward

Add TagMenu controls stub on web

---

package.json
src/components/TagMenu/index.tsx
src/components/TagMenu/index.web.tsx
src/components/dialogs/MutedWords.tsx
yarn.lock

Bumps SDK to fix ## parsing and removal bugs, as well as sanitization like zero width space and newlines. Adds a little validation to the frontend.

Bump API SDK, add validation to MutedWords

---

src/view/com/util/moderation/ContentHider.tsx
src/view/com/util/moderation/PostHider.tsx

Noticed this could be improved

Fix icons on blurred posts

---

src/lib/moderatePost_wrapped.ts

Uses a pretty heavy hand to mute embeds — basically hides the whole post — but fixes cases where mute words were not applied.

Fix muting of embedded data

---

src/components/RichText.tsx
src/view/com/util/post-embeds/QuoteEmbed.tsx

This reverts commit f016cdbca9660d9e10faefae5c34c8574795419e.

Revert "Enable tags inside of quotes (#3041)"

---

package.json
src/components/forms/DateField/index.android.tsx
src/components/forms/DateField/index.tsx
src/state/queries/preferences/index.ts
src/view/com/util/forms/DateInput.tsx
yarn.lock

This is the same as https://github.com/bluesky-social/social-app/pull/3104 but without all of the other changes in the base migration PR.

Switch date picker libraries

---

src/components/Prompt.tsx
src/view/com/profile/ProfileMenu.tsx

Tweak prompt styles on mobile web

---

src/lib/statsig/events.ts
src/view/com/composer/Composer.tsx
src/view/com/posts/Feed.tsx

Just a couple events so we can get closer to parity with Segment on most important ones.

[Statsig] Track posting, end reached

---

src/view/com/profile/ProfileMenu.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

Add warning about sharing if post author has the !no-unauthenticated label

---

.github/workflows/pull-request-commit.yml

Adding a GitHub action based on https://github.com/expo/expo/blob/main/.github/workflows/pr-labeler.yml to find changes to packages and native modules.

Add package diff PR labeler

---

src/screens/Profile/Header/Shell.tsx
src/view/com/util/UserAvatar.tsx

Cherrypicked commits from #3230 due to 3p moderation branch being merged

Fix nested border radius issue on square avatars

---

src/components/dialogs/BirthDateSettings.tsx
src/screens/Moderation/index.tsx
src/state/queries/preferences/index.ts
src/view/screens/Settings/index.tsx

Mostly set out to integrate the ALF DateField, but decided we [should do a little more work](https://github.com/orgs/bluesky-social/projects/9/views/1?pane=issue&itemId=56843822) on that before we start using it.
Also wanted to fix:
- flash of load state when submitting
- remove need to pass in prefs (prefs should be cached, might as well use query hook)
So just small tweaks:
- hoisted some UI up for initial load state (probably won't ever happen, prefs should be in cache)
- moved `isPending` state to button icon

Bday modal tweaks

---

src/alf/index.tsx
src/components/moderation/ModerationLabelPref.tsx

Mobile mod label setting component

---

src/components/LabelingServiceCard/index.tsx
src/components/ReportDialog/SelectLabelerView.tsx
src/components/ReportDialog/SelectReportOptionView.tsx
src/screens/Moderation/index.tsx

Switches up some copy and the selection item for labelers

Rework the labeler selection step of the report flow

---

package.json
src/state/queries/actor-autocomplete.ts
src/state/shell/composer.tsx
src/view/com/auth/login/ChooseAccountForm.tsx
src/view/com/composer/Composer.tsx
src/view/com/composer/ComposerReplyTo.tsx
src/view/com/composer/Prompt.tsx
src/view/com/composer/text-input/mobile/Autocomplete.tsx
src/view/com/composer/text-input/web/Autocomplete.tsx
src/view/com/modals/ListAddRemoveUsers.tsx
src/view/com/modals/SwitchAccount.tsx
src/view/com/modals/UserAddRemoveLists.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/post/Post.tsx
src/view/com/posts/FeedItem.tsx
src/view/com/profile/ProfileCard.tsx
src/view/com/profile/ProfileHeaderSuggestedFollows.tsx
src/view/com/util/PostMeta.tsx
src/view/screens/PostThread.tsx
src/view/screens/Search/Search.tsx
src/view/screens/Settings/index.tsx
src/view/shell/Drawer.tsx
src/view/shell/bottom-bar/BottomBar.tsx
src/view/shell/desktop/LeftNav.tsx
src/view/shell/desktop/Search.tsx
yarn.lock

Uses `labeler` variant of avatar in all cases

Use consistent avatar shape/defaults for labelers

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx

[Statsig] Include OS and track app state changes

---

src/locale/locales/uk/messages.po

Crowdin project for translation and discussion: https://crowdin.com/project/bsky-app-ua

Update Ukrainian translation

---

src/view/com/composer/Composer.tsx

Small fix for https://github.com/bluesky-social/social-app/issues/3263

Prevent linking to post from an embed in composer

---

src/lib/statsig/events.ts
src/view/com/feeds/FeedPage.tsx
src/view/com/posts/Feed.tsx

Tracks PTR, Load Latest and Soft Reset.

[Statsig] Track feed refresh

---

src/lib/statsig/events.ts
src/lib/statsig/statsig.tsx

Tracks time spent foregrounded when backgrounding. Rounded to a second. Checked web, iOS, Android.

[Statsig] Track active time

---

app.config.js
plugins/withAndroidSplashScreenStatusBarTranslucentPlugin.js
src/App.native.tsx

Merged to a branch to fix conflict and format, which evidently wasn't really needed. Already tested on Android, no change on iOS. This one is ready to go.

Fix android splash jump

---

src/view/com/composer/Composer.tsx

See https://bsky.app/profile/mary.my.id/post/3koagxpdim72g
Because we're using two modal systems at once, we're running into problems here when we use a new dialog inside of the composer for discarding.
- Type some text into the composer
- Press "Cancel"
- Dialog presents asking if you want to discard
- Can no longer use the back button on Android
The prompt's confirm `onPress` calls both the `onClose()` for the composer and the `close()` for the dialog at the same time. The `close()` call though does not complete however and we end up with some ghost navigation state.
Instead, in this case we should use the callback parameter of `control.close(cb)` to close the composer _after_ closing the dialog.

fix android back after closing composer

---

src/screens/Onboarding/StepModeration/AdultContentEnabledPref.tsx
src/screens/Profile/Header/ProfileHeaderLabeler.tsx

Was a string outside of `Text` error in the `Promp.Action` component

Fix crash during onboarding

---

src/view/com/modals/DeleteAccount.tsx

Apply background color to entire scrollview in delete account modal

---

.prettierignore

Follow-up to https://github.com/bluesky-social/social-app/pull/3373. I think this makes more sense — we want to format all JS-ey stuff across the project. Including build scripts etc. I only added explicit ignores for folders with generated code.

Use Prettier at the root

---

package.json

Accidentally added this in https://github.com/bluesky-social/social-app/pull/3373. Let's remove it so it's faster.

Remove unnecessary yarn call

---

src/view/screens/Search/Search.tsx

Generally cleaned up the styles to make everything easier to click

Search - Make entire recent search clickable

---

.github/workflows/bundle-deploy-eas-update.yml

Quick follow up to https://github.com/bluesky-social/social-app/pull/3291 so that the action runs automatically on merges to main.

run bundle/deploy on main pushes

---

src/view/screens/Home.tsx

Just a simple feature gate to start playing with it.
When `disable_min_shell_on_foregrounding` is on, the app will disable minimal shell on foregrounding. The thing I'm curious about is whether this will lead to more Notifications tab navigations (since we won't be hiding the jewel).
I do this on the home tab because it's unsafe to do globally. E.g. don't want to screw up onboarding or logged out state.
Overrode it in the console to `true` for self. Minimal shell gets disabled on foregrounding.
https://github.com/bluesky-social/social-app/assets/810438/5cdb88c0-dcfe-497e-b5fc-9e3c4c96d40d
Also verified on (mobile) web.
Verified logged out state isn't affected by this.

[Experiment] Disable min shell on foregrounding

---

src/locale/locales/zh-CN/messages.po

I noticed that the Simplified Chinese localization hasn't been updated for a while, so I translated those terms. @mitian233 @RitsukiP Please help me review this PR.

Update zh-CN translation

---

.github/workflows/build-submit-android.yml

notify slack on production builds

---

src/lib/statsig/statsig.tsx

To make the separation clearer in the UI.
Don't know how to test for sure but if we trust this constant we should be good.

[Statsig] Mark Testflight as staging tier

---

src/locale/locales/ko/messages.po

Update the Korean localization of added and changed strings on the fly.
I think it would be more helpful for localization if #3285 was merged.

Update Korean localization

---

src/locale/locales/zh-TW/messages.po

This PR updates zh-TW localization based on the latest version.

Update zh-TW Localization

---

src/locale/locales/ca/messages.po

New lines translated, just 26 this time
You can check it @jordimas @darccio @ferranrego @MiquelAdell @mvdan @johnnydement @Mejans @surfdude29

Update Catalan messages.po

---

src/components/dialogs/Signin.tsx

Zhuzh sign in dialog

---

bskyembed/src/screens/landing.tsx

Tweaks the error message to be a bit nicer
Also center aligned the header

[Embeds] Tweak homepage styles

---

src/lib/statsig/statsig.tsx

If we add these to embeds, let's send them when present.

[Statsig] Send ref source

---

bskyembed/src/components/link.tsx
bskyembed/src/screens/landing.tsx
src/components/dialogs/Embed.tsx

Adds `?ref_src=embed` to embed URLs

[Embeds] Add ref_src

---

bskyembed/snippet/embed.ts
bskyembed/src/components/link.tsx
bskyembed/src/screens/post.tsx

Gets the outer location, pass it into the iframe, and add it to the link back to bsky.app

[Embeds] Add ref_url

---

bskyweb/templates/base.html
src/components/ProfileHoverCard/index.web.tsx
web/index.html

[screen-capture (5).webm](https://github.com/bluesky-social/social-app/assets/153161762/5d22442e-2bb8-4a69-9046-262342445363)

Fade in animation for card

---

src/state/session/index.tsx
src/state/session/types.ts
src/view/com/modals/ChangeEmail.tsx
src/view/com/modals/ChangeHandle.tsx
src/view/com/modals/VerifyEmail.tsx

Prep for a potential rollout approach to landing this code

[Session] Compat -> Root

---

bskyweb/templates/post.html

We should probably wait on this one until we are confident the embeds are working the way we want.

add oEmbed links to public post HTML meta headers

---

src/components/ProfileHoverCard/index.web.tsx

I tried to be smart in https://github.com/bluesky-social/social-app/pull/3521 and it totally bit me. I think the impulse to express this as a state machine was correct, but the way I was trying to cheat my way out of React's model was wrong. Specifically, the problem is I tried to read `state` in a bunch of places but it wasn't updated by that point yet. So the logic was wrong, leading to wonky hover/unhover behavior.
This is a rewrite of that code in a way that I believe follows the React model. It might seem a bit convoluted at first but it worked correctly from the first try which is hopefully a sign that the principle is sound. The idea is to express this state machine as a reducer: a function that takes the current state (what state is the system in?) and the action (what has just …

Fix hover card animation with a reducer

---

__e2e__/util.ts
src/components/forms/HostingProvider.tsx
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po
src/screens/Signup/StepHandle.tsx
src/screens/Signup/StepInfo/index.tsx
src/screens/Signup/index.tsx

- Some test updates
- Run intl:extract

Release 1.77.0

---

bskyweb/cmd/embedr/snippet.go

Adds post link (around datetime) and profile link (around display name and/or handle).
Also applies "sort-at" timestamp logic to the created at timestamp (https://docs.bsky.app/docs/advanced-guides/timestamps).
And removes some debug println.

embedr: improved HTML snippet, with links

---

src/view/com/util/forms/PostDropdownBtn.tsx

Fixes https://github.com/bluesky-social/social-app/issues/3567

Hide translate/copy text options when `!no-unauthenticated`

---

package.json
src/view/com/composer/Composer.tsx

Simple, just check if there's a quote before rejecting the submission.

Allow a post to contain only a quote

---

src/lib/statsig/statsig.tsx

My bad, missed it in #3582. Idk why TS didn't catch it.

Make ref_ always strings

---

src/lib/statsig/statsig.tsx

Ensures that gates report consistent values throughout a user's app session, and don't change abruptly in a running app.
Replaces the per-component cache with a single cache ensuring gate reads are the same across the entire component trees for a session. I define a "session" as a period of time with the same `currentAccount?.did`. When the session changes, we throw away the old cache, and the checks start hitting the singleton `Statsig` object which also tracks exposures — getting cache (for the new session) along the way.
Decrease the `setInterval` delay to ~10 seconds.
Open something that depends on a gate (e.g. search). Flip the gate in the tool. Stay on the page. Do some state updates (e.g. navigate to Home and Back). Verify that you still see the previous gate's behavior — it's as …

[Statsig] Isolate cache per session

---

src/locale/locales/zh-CN/messages.po

The zh-CN translations are a bit behind, so I created this PR to improve them. I also made some changes to the translations to make them conform to Chinese grammar.

Update zh-CN localization

---

src/lib/statsig/gates.ts
src/screens/Profile/Header/ProfileHeaderStandard.tsx
src/state/shell/selected-feed.tsx
src/view/com/feeds/FeedPage.tsx
src/view/com/post-thread/PostThreadFollowBtn.tsx
src/view/screens/Home.tsx

Made new versions of these so we can try again with more precise exposures. The goal is to only check the gate when its effect is about to become apparent.
Try a few of these. Verify that they still work like before (e.g. Discover blue dot not showing up, "Follow back" button, restoring the hidden shell on foregrounding etc).

[Statsig] Update experiments

---

src/lib/statsig/statsig.tsx

This is a bit more specific than the information it attaches automatically.

[Statsig] Send locale info

---

src/lib/statsig/gates.ts
src/view/screens/Search/Search.tsx

Backend is in prod and we want to ship it to everyone so don't need the gate.
[Without whitespace](https://github.com/bluesky-social/social-app/pull/3627/files?w=1)
Go to search, try the tabs.

Ungate Top/Latest search

---

src/locale/locales/ja/messages.po

@Hima-Zinn @dolciss @oboenikui @noritada @middlingphys @hibiki @reindex-ot @haoyayoi @vyv03354
Please review
- Add GIPHY related messages
- "Powered by GIPHY"  is left as is without translation
- Add a11y related messagges
- Update a message in empty search screen

Update Japanese translations

---

src/locale/locales/fi/messages.po

Numerous new translations and minor fine-tunings. Also removed strings that are obsolete and no longer used.

Update Finnish translations 

---

src/view/com/composer/Composer.tsx
src/view/com/composer/photos/Gallery.tsx

Reverts bluesky-social/social-app#3609

Revert "Add layout transitions to the composer photo gallery on iOS"

---

src/state/queries/tenor.ts

[GIFs] remove country param

---

src/lib/statsig/gates.ts
src/view/screens/Profile.tsx

This rolled out fine, let's make it unconditional.

Ungate profile scroll fix

---

__e2e__/tests/composer.test.ts
src/locale/locales/ca/messages.po
src/locale/locales/de/messages.po
src/locale/locales/en/messages.po
src/locale/locales/es/messages.po
src/locale/locales/fi/messages.po
src/locale/locales/fr/messages.po
src/locale/locales/ga/messages.po
src/locale/locales/hi/messages.po
src/locale/locales/id/messages.po
src/locale/locales/it/messages.po
src/locale/locales/ja/messages.po
src/locale/locales/ko/messages.po
src/locale/locales/pt-BR/messages.po
src/locale/locales/tr/messages.po
src/locale/locales/uk/messages.po
src/locale/locales/zh-CN/messages.po
src/locale/locales/zh-TW/messages.po

Release 1.79

---

src/view/com/composer/text-input/TextInput.web.tsx
src/view/com/composer/text-input/web/LinkDecorator.ts

Remove unnecessary `.trimEnd()` and fix facet detection

---

src/lib/statsig/gates.ts
src/state/queries/suggested-follows.ts
src/view/screens/Search/Search.tsx

This is out to 100% now so let's clean it up.

Remove old Suggested Follows logic

---

src/locale/locales/ga/messages.po

messages.po: 1239 translated messages.

Irish translation back to 100%

---

src/state/queries/list.ts
src/state/queries/profile.ts

Part 2/? migrating non-trivial usages of `getAgent`.

[Session] Drill into `getAgent` into `whenAppViewReady`

---

src/screens/Onboarding/StepFinished.tsx
src/screens/Onboarding/util.ts

Part 4/? migrating non-trivial usages of `getAgent`.

[Session] Drill `getAgent` into `Onboarding/util`

---

patches/@atproto+lexicon+0.4.0.patch

Brings in https://github.com/bluesky-social/atproto/pull/2452. Temporary to check the effect on TF. We'll update to the real fix when it's out.

Patch lexicon for perf

---

__tests__/lib/string.test.ts
src/lib/strings/embed-player.ts

Adds YouTube Music as a supported player

YouTube Music as supported player

---

src/view/screens/Profile.tsx

We verified they work, let's rm.

Remove test gating code

---

src/locale/locales/it/messages.po

Strings of Bluesky v.179 updated with Italian translations

Italian localization

---

src/components/dms/NewChat.tsx
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/List/index.tsx
src/screens/Messages/Temp/query/query.ts
src/view/shell/bottom-bar/BottomBarWeb.tsx

Also improves styles, especially on web

[Clipclops] Use API data for clipclop list

---

src/screens/Messages/Conversation/MessageItem.tsx
src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Temp/query/query.ts
src/view/com/util/TimeElapsed.tsx

We can expand this to add the retry button down the line

[Clipclops] Add clop sent time to clipclop

---

src/screens/Messages/Conversation/MessageItem.tsx

[Clipclops] Separate messages if there's a time gap

---

src/components/Portal.tsx
src/state/preferences/label-defs.tsx

Just noticed this missing in a few places while reviewing https://github.com/bluesky-social/social-app/pull/3785.

Memoize context value

---

src/screens/Messages/Conversation/MessageItem.tsx
src/screens/Messages/List/index.tsx
src/screens/Messages/Temp/query/query.ts

- Fix line height
- Bold unread last message
- Last message time elapsed indicator
- Own messages are prefixed with "You: "

[Clipclops] Improve message list behaviour

---

src/components/Error.tsx
src/screens/Messages/List/index.tsx

[Clipclops] Add header to empty chat list view

---

src/screens/Messages/Conversation/MessagesList.tsx
src/screens/Messages/Conversation/index.tsx

Popped the `ChatProvider` all the way to the top. We were doing two loading states before so it was taking a bit long.
https://github.com/bluesky-social/social-app/assets/153161762/843034e9-3239-467f-bf09-e35cdf56e361

[Clipclops] Fix list, rework structure

---

assets/icons/paperPlane_stroke2_corner0_rounded.svg
assets/icons/plusSmall_stroke2_corner0_rounded.svg
src/components/dms/NewChat.tsx
src/components/icons/PaperPlane.tsx
src/components/icons/Plus.tsx
src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/List/index.tsx

Sorry :(
Also replaces FAB button envelope with a plus

[Clipclops] Replace 🐴 with real icon

---

src/screens/Messages/Conversation/MessagesList.tsx

Replace viewability config with `onScroll` which is more accurate.

[Clipclops] Remove viewability config

---

src/screens/Messages/Conversation/index.tsx

Small one, fixes https://github.com/bluesky-social/social-app/issues/3787

[Clipclops] rm `<Trans>` from header

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/Conversation/MessageItem.tsx
src/screens/Messages/Conversation/MessagesList.tsx

- Closes keyboard on drag
- Adjust padding
- Enable min shell mode

[Clipclop] Input polish

---

src/screens/Messages/Conversation/MessageInput.web.tsx
src/screens/Messages/List/index.tsx

- Make send button do something
- Adjust leading

[Clipclops] Minor web tweaks

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx

Paper plane icon is visually skewed left, so move it over one pixel

Visually align icon

---

src/components/dms/ConvoMenu.tsx
src/screens/Messages/Conversation/index.tsx

- Wrap name if too long
- Add dividers to convo menu

[Clipclops] Header tweaks

---

src/components/hooks/useRefreshOnFocus.ts
src/screens/Messages/List/index.tsx
src/state/queries/messages/list-converations.ts

refreshes on screen focus + 15 refresh interval

[Clipclops] Chat list - add focus refresh + polling

---

src/screens/Messages/Conversation/MessagesList.tsx

[Clipclops] Reenable tabs

---

src/components/dms/MessageItem.tsx
src/screens/Messages/Conversation/MessagesList.tsx

- Make pending message slightly pale
- Animate into place
- Change time gap for group to 3mins

[Clipclops] Pending message style with layout animation

---

src/components/dms/MessageItem.tsx
src/components/dms/MessageMenu.tsx
src/components/dms/NewChat.tsx
src/screens/Messages/List/index.tsx
src/view/com/util/forms/PostDropdownBtn.tsx

This is a bunch of 5-minute changes that would've bothered me over the weekend
- empty state for new chat dialog
- pending message improved dark mode
- copy message text option
- fix service url input
- slightly reduce horizontal padding on messages

Assorted clipclop fixes

---

src/lib/app-info.ts
src/lib/app-info.web.ts

Typo on the environment variable.

fix typo in `app-info`

---

src/components/dms/ActionsWrapper.tsx
src/components/dms/MessageItem.tsx
src/screens/Messages/Conversation/MessagesList.tsx

- Make messages pressable while keyboard is open
- Close keyboard when opening menu

[🐴] Improve message pressing

---

src/view/com/util/List.web.tsx
src/view/screens/Storybook/ListContained.tsx

- Pass the ref to `Visibility`
- Use getters for `contentHeight` et al.
cc @gaearon 
https://github.com/bluesky-social/social-app/assets/153161762/7009ce0c-58b4-4dda-8e45-692d082edc74

A few `containWeb` List nits

---

__tests__/lib/string.test.ts
modules/expo-scroll-forwarder/src/ExpoScrollForwarderView.ios.tsx
package.json
src/components/LabelingServiceCard/index.tsx
src/components/ProfileHoverCard/index.web.tsx
src/components/moderation/LabelsOnMe.tsx
src/lib/strings/helpers.ts
src/locale/i18n.ts
src/screens/Deactivated.tsx
src/screens/Profile/Header/Metrics.tsx
src/screens/Profile/Header/ProfileHeaderLabeler.tsx
src/view/com/feeds/FeedSourceCard.tsx
src/view/com/notifications/FeedItem.tsx
src/view/com/post-thread/PostThreadItem.tsx
src/view/com/util/post-ctrls/PostCtrls.tsx
src/view/com/util/post-ctrls/RepostButton.tsx
src/view/screens/PreferencesFollowingFeed.tsx
src/view/screens/ProfileFeed.tsx
src/view/shell/Drawer.tsx
yarn.lock

Supersedes https://github.com/bluesky-social/social-app/pull/2382
Uses the lingui API to properly handle plurals. On native, it introduces a polyfill for some missing internationalization APIs.
Massive apology to @tkusano for how long this was left unmerged. I really appreciate you keeping this updated in the meantime, and will try not to let PRs sit like this in the future.

Replace pluralize by plural by @tkusano

---

src/locale/locales/fi/messages.po

Translated new strings (GIF's etc) and cleaned up deprecated ones. I'm native finnish speaker.

Finnish translation update

---

.github/workflows/bundle-deploy-eas-update.yml

typo in if/else

---

src/App.native.tsx
src/App.web.tsx
src/state/messages/events/agent.ts
src/state/messages/events/index.tsx
src/state/messages/events/types.ts

[🐴] Global event mgmt

---

src/state/queries/messages/conversation.ts
src/state/queries/messages/list-converations.ts

Accidentally put it in `onSuccess` instead of `onMutate`

[🐴] Actually optimistic mark as read

---

src/components/dms/ActionsWrapper.tsx

Lowers the delay a bit so it feels more natural. Testing in a simulator feels nice but needs to be tested on device to get a real "feel" for it.

[🐴] Adjust press and hold delay on messages

---

src/screens/Messages/Conversation/index.tsx

- skeleton header
- better error screen

[🐴] Skeleton header

---

src/state/messages/convo/agent.ts
src/state/messages/events/agent.ts

Retries all requests twice before failing and alerting the user.

[🐴] Add retries to all handlers

---

src/screens/Messages/Conversation/index.tsx
src/screens/Messages/List/index.tsx

Tweaks styles

---

src/view/shell/Drawer.tsx

[🐴] Add icons to drawer

---

src/components/ReportDialog/SelectReportOptionView.tsx
src/components/dms/ConvoMenu.tsx
src/components/dms/MessageItem.tsx
src/components/dms/MessageMenu.tsx
src/components/dms/MessageReportDialog.tsx
src/lib/moderation/useReportOptions.ts

[🐴] Report message dialog

---

src/lib/constants.ts
src/view/com/posts/Feed.tsx
src/view/com/posts/FeedShutdownMsg.tsx

https://github.com/bluesky-social/social-app/assets/1270099/ecc8796a-de21-4bcb-a635-3ba1682c3b34
Note: performance is pretty rough when changing pinned feeds. It might be worth doing a deep dive on what gets triggered in response to it.
- Scneario 1
- Pin "For You" and "Discover"
- Go to "For You." Click "Remove feed."
- Feed should be removed
- Scenario 2
- Pin "For You" and save but unpin "Discover"
- Go to "For You." Click "Replace"
- Feed should be removed, discover should be pinned
- Scenario 2
- Pin "For You" and unsave "Discover"
- Go to "For You." Click "Replace"
- Feed should be removed, discover should be pinned

Add shutdown message to For You feed

---

src/state/queries/post-feed.ts

Swaps in our "base" following feed, with no fallback to Discover. Below is what new users will see when they visit the following feed. These buttons take the user to Search and to Feeds, respectively.

[Reduced Onboarding] Swap in base following

---

__e2e__/flows/onboarding-avatar-creator.yml
__e2e__/flows/onboarding.yml
__e2e__/flows/profile-screen-edit.yml
src/lib/media/picker.e2e.tsx
src/view/com/testing/TestCtrls.e2e.tsx
yarn.lock

Adds e2e tests for the new onboarding flows. Unfortunately we don't have a way to control the feature-gate so you currently have to manually override the gate in the code to pass the new tests.

New onboarding tests

---

src/lib/statsig/events.ts
src/screens/Onboarding/StepFinished.tsx
src/screens/Onboarding/state.ts

Stacked on #3997 
Thought it'd be nice to know if the user created an avi, uploaded one, or took no action and used the default.

[Reduced Onboarding] Add avatar metric

---

src/state/queries/post-feed.ts

Conditionally swaps what was done in #3991

Gate base following feed usage

---

__e2e__/flows/feed-reorder.yml
src/view/com/feeds/FeedSourceCard.tsx
src/view/screens/SavedFeeds.tsx

This UI is going to need a redo (as are all the Feed management flows) but I wanted to make things better if we're going to launch movable following feed.
Note that the "Delete" button only shows after unpinning, to conserve screen real-estate.
https://github.com/bluesky-social/social-app/assets/1270099/7ef4150d-b4ae-492c-94d6-78443dcac216

Make feeds easier to reorder

---

__e2e__/flows/onboarding-old.yml
src/lib/statsig/statsig.tsx
src/view/com/testing/TestCtrls.e2e.tsx

Adds a "dangerous" hook to override gates

Add better onboard testing

---

src/components/ProfileHoverCard/index.web.tsx
src/components/ProfileHoverCard/types.ts
src/screens/Messages/Conversation/index.tsx
src/view/com/util/UserAvatar.tsx

https://github.com/bluesky-social/social-app/assets/153161762/618dd94c-0ddb-44a0-b16e-a3ed37dc2ada

[🐴] Disable hover card when blocked or blocking

---

src/screens/Messages/Conversation/MessageInput.web.tsx

[🐴] Tweak padding of web input

---

src/components/Button.tsx
src/screens/Messages/List/index.tsx

[🐴] Tweak header styles

---

src/screens/Messages/Conversation/MessageListError.tsx

Noticed styles were wacky on mobile

[🐴] Fix error styles

---

src/screens/Messages/Conversation/MessageInput.tsx
src/screens/Messages/Conversation/MessageInput.web.tsx

https://github.com/bluesky-social/social-app/assets/153161762/0dd1da12-5d3b-4961-9463-d646912d0f90
https://github.com/bluesky-social/social-app/assets/153161762/7059ed57-e90a-45a4-8d5c-493c773e0911

[🐴] Input hover and focus styles
